### ISSUE TITLE
html texture with input binding [tutorial]

### ISSUE THREAD

**Issue by ImmanuelSamuel** [playcanvas/engine#1001]
I would like to show interactive web pages on in game panels. How would input binding work in this case?

**Comment by willeastcott** [comment]
I believe Google is working on rendering on an iframe -> texture solution:

https://www.youtube.com/watch?v=dAtdE4LQCSc#t=25m22s

Who knows when that will see the light of day or whether it'll become a standard, but it looks pretty cool.

In the meantime, it is possible to render a PlayCanvas scene over an HTML div that is transformed with CSS 3D to match the transform of the PlayCanvas camera. You simply have to render a transparent quad into the PlayCanvas scene where you want to the 3D div to be to write the quad to the z-buffer. But yeah, it's a technique that does kinda work.

**Comment by willeastcott** [comment]
This tutorial should provide what was originally requested:

https://developer.playcanvas.com/en/tutorials/youtube-in-3d-scenes/

Closing. Feel free to reopen if you feel this tutorial is not sufficient.
