### ISSUE TITLE
Building WebGL libraries that work with each other in the same webgl context.

### ISSUE THREAD

**Issue by trusktr** [playcanvas/engine#1003]
##### Description of the problem 

It's difficult and complex these days to mix WebGL libraries together, to draw things using different libraries in the same webgl context. (examples of difficulties: https://github.com/mrdoob/three.js/issues/8147, https://github.com/pixijs/pixi.js/issues/3230, https://github.com/pixijs/pixi.js/issues/3345, https://github.com/pixijs/pixi.js/issues/1366, https://github.com/pixijs/pixi.js/issues/298, https://github.com/jonobr1/two.js/issues/233)

For example, suppose we would like to render Three, Babylon, and Pixi objects into the same WebGL context, in the same 3D space.

It is currently very difficult to do this because each WebGL library manages state of the context in their own ways, and these private internals often change and break solutions that people come up with because there's no standard way to do it.

Pixi.js v4 goes through [efforts to make Pixi compatible with Three.js](https://github.com/pixijs/pixi.js/issues/3230#issuecomment-257381561), so that it can render in a Three scene, but this is obviously fragile.

##### Solution

Enter [Regl](http://regl.party) to the party.

Maybe if the foundations for each library (Three, Babylon, Pixi, Two, etc) were built on Regl, we'd have a common way of rendering to a single context.

Regl makes an abstraction just on top of raw WebGL for managing WebGL state. It doesn't render for you all the things that Three.js can, it only provides the minimal foundation for working with raw WebGL in a stateful way that is easy to manage.

It seems that libraries like Three, Babylon, PlayCanvas, Pixi, Two, etc, could benefit from using a standardized way for managing WebGL state, which would make it easy to combine renderings from any of these libraries into the same WebGL context.

---

What are your thoughts on refactoring the foundation of PlayCanvas to use Regl for managing WebGL state? Does Regl offer enough flexibility for PlayCanvas to do what it needs to do on top of Regl?

**Comment by willeastcott** [comment]
Interesting suggestion. But Running PlayCanvas on Regl will likely make it slower. And since nobody has ever requested the ability to share a PlayCanvas WebGL context with another renderer, it doesn't seem worth doing, TBH. It's an incredibly niche use case.

**Comment by daredevildave** [comment]
As Will mentioned. I don't think this is something we'd implement. Thanks,
