### ISSUE TITLE
text element wrap

### ISSUE THREAD

**Issue by ImmanuelSamuel** [playcanvas/engine#1004]
Can you guys support text wrapping when text element width is fixed? Is there a temporary solution for this? For rpg style games quest descriptions can get quite long.

**Comment by daredevildave** [comment]
A temporary solution would be to insert "\n" newline characters into your text to wrap the text manually.

**Comment by TobiasWehrum** [comment]
Is there any performant way to measure the width of a text via code? My text is coming from an external source, so I can't add the "\n"s manually, I'd need to iteratively measure width and insert "\n" via code.

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/pull/1131
