### ISSUE TITLE
text elements disappears after refresh

### ISSUE THREAD

**Issue by ImmanuelSamuel** [playcanvas/engine#1005]
Also I have a weird problem. The text elements under a screen component appears normally during first load but disappears after refresh. The other elements (images) appear even after refresh.

**Comment by daredevildave** [comment]
Can you provide a reproducible sample for us to be able to look at? Thanks.

**Comment by willeastcott** [comment]
Hi @ImmanuelSamuel - would you like to keep this issue open?

**Comment by ImmanuelSamuel** [comment]
Currently I am busy with work. Maybe we can close this and I can reopen when I get time to replicate this issue. My current project is big and I would need to do quite a bit to get this.

**Comment by willeastcott** [comment]
OK. Please reopen when you have time to investigate. 😄
