### ISSUE TITLE
camera.clearColor.set not work

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#1012]
```js
 // not work
camera.clearColor.set(1, 0, 0, 1);

 // work
camera.clearColor = new pc.Color(1, 0, 0, 1);
```
Not sure this is a bug or feature ?

**Comment by willeastcott** [comment]
It's a feature. You can't set component properties like that. You need an assignment or the underlying engine doesn't get properly notified that the property has changed. Closing...

**Comment by scarletsky** [comment]
Oh, I see, thanks will.
