### ISSUE TITLE
ELEMENTTYPE enum collision

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1029]
We now have:

        /**
         * @enum pc.ELEMENTTYPE
         * @name pc.ELEMENTTYPE_INT8
         * @description Signed byte vertex element type.
         */
        ELEMENTTYPE_INT8: 0,
        /**
         * @enum pc.ELEMENTTYPE
         * @name pc.ELEMENTTYPE_UINT8
         * @description Unsigned byte vertex element type.
         */
        ELEMENTTYPE_UINT8: 1,
        /**
         * @enum pc.ELEMENTTYPE
         * @name pc.ELEMENTTYPE_INT16
         * @description Signed short vertex element type.
         */
        ELEMENTTYPE_INT16: 2,
        /**
         * @enum pc.ELEMENTTYPE
         * @name pc.ELEMENTTYPE_UINT16
         * @description Unsigned short vertex element type.
         */
        ELEMENTTYPE_UINT16: 3,
        /**
         * @enum pc.ELEMENTTYPE
         * @name pc.ELEMENTTYPE_INT32
         * @description Signed integer vertex element type.
         */
        ELEMENTTYPE_INT32: 4,
        /**
         * @enum pc.ELEMENTTYPE
         * @name pc.ELEMENTTYPE_UINT32
         * @description Unsigned integer vertex element type.
         */
        ELEMENTTYPE_UINT32: 5,
        /**
         * @enum pc.ELEMENTTYPE
         * @name pc.ELEMENTTYPE_FLOAT32
         * @description Floating point vertex element type.
         */
        ELEMENTTYPE_FLOAT32: 6,

And:

    /**
     * @enum pc.ELEMENTTYPE
     * @name pc.ELEMENTTYPE_GROUP
     * @description A {@link pc.ElementComponent} that contains child {@link pc.ElementComponent}s.
     */
    pc.ELEMENTTYPE_GROUP = 'group';
    /**
     * @enum pc.ELEMENTTYPE
     * @name pc.ELEMENTTYPE_IMAGE
     * @description A {@link pc.ElementComponent} that displays an image.
     */
    pc.ELEMENTTYPE_IMAGE = 'image';
    /**
     * @enum pc.ELEMENTTYPE
     * @name pc.ELEMENTTYPE_TEXT
     * @description A {@link pc.ElementComponent} that displays text.
     */
    pc.ELEMENTTYPE_TEXT = 'text';

Whoops.

I propose we rename:

ELEMENTTYPE_INT8 -> TYPE_INT8

Since those are actual types. Obviously, we'd support backwards compatibility definitions.

**Comment by vkalpias** [comment]
👍
