### ISSUE TITLE
glTF's default material uses roughness, not glossiness

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1037]
How do we support [this](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#metallic-roughness-material)?

**Comment by guycalledfrank** [comment]
Can add an option for the standard material.

**Comment by willeastcott** [comment]
Rather than add support for this to the engine, I think we should see if we can enhance the glTF loader code instead. Ideally with shader chunks.
