### ISSUE TITLE
Why not rename bumpMapFactor to bumpiness ?

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#1038]
I've read material's source code, and I am confusing with it... 

```js
for (var i = 0; i < data.parameters.length; i++) {
    var param = data.parameters[i];
    if (param.type === "vec3") {
        this[param.name] = _createRgb(param);
    } else if (param.type === "vec2") {
        this[param.name] = _createVec2(param);
    } else if (param.type === "texture") {
        this[param.name] = _createTexture(param);
    } else if (param.type === "cubemap") {
        this[param.name] = _createCubemap(param);
    } else if (param.name === "bumpMapFactor") { // Unfortunately, names don't match for bumpiness
        this.bumpiness = param.data;
    } else if (param.type === 'boundingbox') {
        this[param.name] = _createBoundingBox(param);
    } else {
        this[param.name] = param.data;
    }
}
```

But it seems `bumpiness` will work. 😕

**Comment by willeastcott** [comment]
We could rename the property that we write to the JSON format from bumpMapFactor to bumpiness, but there will still be a large amount of assets that are already created with the old name. However, I do agree that we should probably change the name but we'd have to still look for the old name on load in case it's an older asset.

**Comment by scarletsky** [comment]
This issue will affect the engine users.

As a engine user, I will save the material data which `bumpiness` is named `bumpiness`. But when I init the material, the `bumpiness` will not work until I renamed it to `bumpMapFactor`... 😢
