### ISSUE TITLE
Random Vec2 and Vec3

### ISSUE THREAD

**Issue by Neoflash1979** [playcanvas/engine#1039]
It would be nice (and easy to implement) to have a method to generate a random Vec2 or Vec3. I'm thinking that these two methods could be added to the existing pc.math.random or just along with it.

Ex:
pc.math.random.vec3

or just

pc.math.randomVec3

There is also the possibility to add it directly on the Vec2 and Vec3 classes.

Ex:
pc.Vec3.random

All these would beat having to do:

`new Vec3(pc.math.random(0,1), pc.math.random(0,1), pc.math.random(0,1))`

**Comment by willeastcott** [comment]
Hi @Neoflash1979. TBH, I never liked the PlayCanvas function pc.math.random. If it were up to me, it never would have been added. It goes against my philosophy of keeping the engine lean with a small interface. The following is both succinct and rarely done by developers:

var v2 = new pc.Vec3(Math.random(), Math.random());
var v3 = new pc.Vec3(Math.random(), Math.random(), Math.random());

So I'm afraid I'm going to decline this particular request. But thanks very much for suggesting!
