### ISSUE TITLE
computeGaussian defined in posteffect-bloom.js is wrong or intended?

### ISSUE THREAD

**Issue by AsAddict** [playcanvas/engine#1040]
```
    function computeGaussian(n, theta) {
        return ((1.0 / Math.sqrt(2 * Math.PI * theta)) * Math.exp(-(n * n) / (2 * theta * theta)));
    }

```
should be 

```
    function computeGaussian(n, theta) {
        return (1.0 / Math.sqrt(2 * Math.PI) / theta) * Math.exp(-(n * n) / (2 * theta * theta)));
    }

```

**Comment by willeastcott** [comment]
I just checked the [Wikipedia page](https://en.wikipedia.org/wiki/Gaussian_blur) on this. Actually, shouldn't it be:

 function computeGaussian(n, theta) {
        return (1.0 / Math.sqrt(2 * Math.PI * theta * theta)) * Math.exp(-(n * n) / (2 * theta * theta));
 }

**Comment by guycalledfrank** [comment]
New bloom is coming soon and doesn't even use this function :)
