### ISSUE TITLE
Elements Input mouse event doesn't fire when on a touch screen PC

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#1044]
Thread: https://forum.playcanvas.com/t/mouse-events-not-working-on-machines-with-a-touchscreen/5327

The element is either listening to touch events or mouse events whereas it should allow for mouse events all the time as in line with the rest of the engine: https://github.com/playcanvas/engine/blob/master/src/input/element-input.js#L198

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/a6536735fcd0e177f59efb14a31efce78311146d
