### ISSUE TITLE
Add getAxisAngle method to Quat class

### ISSUE THREAD

**Issue by Neoflash1979** [playcanvas/engine#1058]
The Quat class has both a setFromEulerAngles and getEulerAngles method but only a setFromAxisAngle and no corresponding getAxisAngle method. I know that you are trying to keep the engine lightweight and that this is something users can easily extend on their own but I thought it was worth suggesting only for consistency's sake.  If you think it would be worth adding, I'd be happy to make a pull request.

**Comment by willeastcott** [comment]
I'm not against the idea. :) What would the function signature be?

**Comment by Neoflash1979** [comment]
Inspired by http://glmatrix.net/docs/quat.js.html#line91

```
/**
 * @function
 * @name pc.Quat#getAxisAngle
 * @description Gets the rotation axis and angle for a given
 *  quaternion. If a quaternion is created with
 *  setFromAxisAngle, this method will return the same
 *  values as providied in the original parameter list
 *  OR functionally equivalent values.
 * Example: The quaternion formed by axis [0, 0, 1] and
 *  angle -90 is the same as the quaternion formed by
 *  [0, 0, 1] and 270. This method favors the latter.
 * @param {pc.Vec3} [axis] The 3-dimensional vector to receive the axis of rotation.
 * @returns {Number} Angle, in degrees, of the rotation
 */
Quat.prototype.getAxisAngle(axis)


```

**Comment by willeastcott** [comment]
Sounds good to me. Please feel free to submit a PR. 👍
