### ISSUE TITLE
decodeAudioData TypeError on preload

### ISSUE THREAD

**Issue by TobiasWehrum** [playcanvas/engine#1062]
Hello,

I've gotten TypeErrors multiple times now with the automatic preloading of audio files. Judging from the GET errors before, I assume it's because they are somehow transmitted incorrectly, but I don't know why that is and why no further try is made to correct that.

Two examples in Chrome:
![decodeaudiodata_chrome_2017-12-10_18-01-36](https://user-images.githubusercontent.com/1674310/34342742-f517e8c8-e9b9-11e7-9831-396aad398ef2.png)
![decodeaudiodata_chrome_2017-12-11_14-28-20](https://user-images.githubusercontent.com/1674310/34342743-f54216b6-e9b9-11e7-93be-a2cd253b1552.png)

One example in Firefox:
![decodeaudiodata_firefox_2017-12-10_03-59-30](https://user-images.githubusercontent.com/1674310/34342744-f56544ec-e9b9-11e7-894b-6c617ad9da02.png)

I also had the general case that GETs would fail. I'm not sure if that should be another bug report:
![decodeaudiodata_chrome_2017-12-15_14-43-09](https://user-images.githubusercontent.com/1674310/34342748-14be273c-e9ba-11e7-8f4f-dabdbeda787b.png)

Upon reload, everything worked there.

**Comment by willeastcott** [comment]
So you are not able to reliably reproduce this problem? Without a set of instructions to reproduce the behavior you are observing, it will be hard to resolve this issue.

**Comment by daredevildave** [comment]
Are you only receiving these errors when launching from the Editor? I believe this is a down to a know issue with our launch page, and not an engine issue.

**Comment by TobiasWehrum** [comment]
@willeastcott No, I can't reproduce it. It just happens about once in maybe 30 runs. Apart from whatever is causing it, maybe it would be a good idea for the loader to retry files that fail? (Do I have any way to plug myself into that process and at least display an error message?)

@daredevildave I _think_ so, but I'm not sure. What's the known issue?

**Comment by marionieto** [comment]
We have been suffering this issue for a long time.
This error always happen after launch a project.
The error occurs 3 out of 10 times.

**Comment by willeastcott** [comment]
It was never possible to reproduce this issue so I am closing. Please reopen if further information becomes available.
