### ISSUE TITLE
Please add p2.js example

### ISSUE THREAD

**Issue by goldenratio** [playcanvas/engine#1065]
Hi,

I am getting started with PlayCanvas game engine. Can you please add example for p2.js for fallingShapes demo (https://github.com/playcanvas/engine/tree/master/examples/physics/falling_shapes).

I tried to do it myself based on https://playcanvas.com/project/446127/overview/p2js-integration 
I am getting the following error,
```
playcanvas-stable.js:25340 Uncaught TypeError: Cannot read property 'setValue' of undefined
    at Func.setGravity (playcanvas-stable.js:25340)
    at falling_shape.html:50
```

Please help :)
Thanks.

**Comment by goldenratio** [comment]
![image](https://user-images.githubusercontent.com/3019293/34454928-be9d99a6-ed7d-11e7-9464-0b09521320b8.png)

**Comment by willeastcott** [comment]
This is happening because, in your code somewhere, you are calling:

    this.app.systems.rigidbody.setGravity(x, y, z);

That is the way to set gravity for PlayCanvas' built-in physics engine (Ammo.js), not P2.

**Comment by goldenratio** [comment]
Thanks. Closing it. I started a forum thread https://forum.playcanvas.com/t/recreating-fallingshapes-demo-in-p2-js/5610
