### ISSUE TITLE
Moving an entity with a trigger. Maybe bug.

### ISSUE THREAD

**Issue by maungers** [playcanvas/engine#1074]
Hi guys!
Entity moves but the trigger acts in the same place.

**Comment by willeastcott** [comment]
Did you use the [teleport](https://developer.playcanvas.com/en/api/pc.RigidBodyComponent.html#teleport) function to move the entity? It's useful if you can provide a simple test case showing the problem.

**Comment by maungers** [comment]
I made a simple example, there are no problems with triggers =)
https://launch.playcanvas.com/582175?debug=true
Apparently the problem was in our code, but it is already solved in another way.
I apologize.
