### ISSUE TITLE
Comparison with Three.js

### ISSUE THREAD

**Issue by trusktr** [playcanvas/engine#1077]
Is there such a comparison somewhere? If not, do you mind sharing what are some of the pros/cons of each library compared to each other, as far as you know?

**Comment by willeastcott** [comment]
I'm not aware of any feature matrix comparison. I do know that PlayCanvas is designed to be a generalized game engine and Three is a 3D graphics library. In other words, the codebase in this repo implements a fully integrated set of systems handling not just 2D/3D graphics, but also audio, collision, physics, entity/component system, input devices and more.

I'd say the biggest pro with PlayCanvas is the [online editor](https://playcanvas.com/). IMHO, nothing else comes close.

**Comment by trusktr** [comment]
The online editor indeed looks really awesome, good job on that!

Maybe more specifically, I'm curious to know about how PlayCanvas and Three.js compare with regards just to rendering.

For example, in Three.js the only utility around fixing tweaking shadows (f.e. fixing ACNE) is modifying shadows' `bias`, but there aren't other things like normal bias or slope-adjusted bias. Also is dithering on the shadow ACNE something doable?

1) Does PlayCanvas offer any of these shadow-tweaking utilities besides just plain bias?

In Three.js, resizing a geometry means looping on every vertex of a geometry and modifying it's position, or just creating a new Geometry which effectively does the same thing with added overhead of discarding and creating a new object. This gets tricky if the geometry is shared with multiple meshes.

2) Does PlayCanvas have a way to scale or resize geometries on a per-mesh basis if we use one geometry per mesh, and without re-calculating all the vertices on the CPU but rather in the GPU? If so, then what about with geometries shared across meshes but needing mesh-specific sizing?

Three.js doesn't have automatic instancing which can drastically improve performance on the average case, and [this amazing PR](https://github.com/mrdoob/three.js/pull/10093) was never merged due to adding too much "maintenance overhead" for Ricardo.

3) Does PlayCanvas have an auto-instancing feature?

Three.js [recently received](https://github.com/mrdoob/three.js/pull/13070) this [amazing feature](https://github.com/mrdoob/three.js/issues/7522#issuecomment-157135290) for composing Shaders out of functional nodes.

4) Does PlayCanvas have a feature for easily composing shaders out of dynamically linkable nodes, and for easily modifying these shader compositions on a per material basis, or something similar?

I'm starting to experiment with PlayCanvas, so maybe I'll discover more questions or comparisons I can post.

By the way, I was the guy who presented Polydance with Anastasiia at 3DWebFest 2017 ([video](https://www.youtube.com/watch?v=6x8PFDbogLE) and [codepen](https://codepen.io/trusktr/pen/EoVGge)). I saw you there, but didn't get a chance to meet you. I'm going to Codame's get-together this Saturday.

PlayCanvas is really inspiring. :)

I recently put up documentation pages for my 3D element at http://infamous.io (WIP). This [pen](https://codepen.io/trusktr/pen/rpegZR) shows how to write HTML that blends normal DOM elements with WebGL (`<button>` elements with WebGL lighting and shadows). I dream of eventually having a creation studio too (a general purpose one for any sort of web applications, not necessarily just games), but right now it's just me, a one-man team with no funding, who's project is open source and generates no income despite the big amount of time spent making it. 

Maybe I can learn something from PlayCanvas 😄 ...

**Comment by willeastcott** [comment]
Yes, PlayCanvas offers a few things to allow you to tweak shadows. First, we offer 2 techniques: PCF and VSM. VSM tends not to suffer from the acne you sometimes see with PCF. For PCF, PlayCanvas exposes a [shadowBias](https://developer.playcanvas.com/en/api/pc.LightComponent.html#shadowBias) property, but also a [normalOffsetBias](https://developer.playcanvas.com/en/api/pc.LightComponent.html#normalOffsetBias) to further tune. PlayCanvas even offers different flavors of PCF and VSM for you to enable, via the [shadowType](https://developer.playcanvas.com/en/api/pc.LightComponent.html#shadowType) property. There's a bunch of documentation on shadows [here](https://developer.playcanvas.com/en/user-manual/graphics/lighting/shadows/) but I notice that page hasn't yet been updated with a good description of the difference between VSM and PCF. Must do that soon...

PlayCanvas has the concept of a mesh (vertex buffer + optional index buffer + definition of a primitive). You then assign the mesh to a mesh instance, which is basically a material + mesh + transform. You can have two differently transformed mesh instances pointing to the same mesh.

PlayCanvas has what's called 'batching'. You can add graphical objects (model components and element components) to batch groups. Read more about batching [here](https://developer.playcanvas.com/en/user-manual/optimization/batching/).

PlayCanvas has a shader chunk system. You can find all the GLSL chunks [here](https://github.com/playcanvas/engine/tree/master/src/graphics/program-lib/chunks). The different material types provided by the engine programmatically construct shader programs from these chunks. The shader chunk system has not yet be formalized into public API, but you can certainly get in there and use it. Typical use case is to customize/tweak standard behavior. For example, to make the [pc.StandardMaterial](https://developer.playcanvas.com/en/api/pc.StandardMaterial.html) behave like the material in the [glTF 2.0 spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#metallic-roughness-material) which is done [here](https://github.com/playcanvas/playcanvas-gltf/blob/master/src/gltf-loader.js#L202).

> By the way, I was the guy who presented Polydance
Very cool - I remember it well!! 👍 

 > PlayCanvas is really inspiring. :)
That's so kind of you to say! 😄

**Comment by guycalledfrank** [comment]
Bit more details about shadow acne: 

shadowBias used to be constant offset, but now it's actually slope-scaled. 
https://github.com/playcanvas/engine/blob/master/src/scene/forward-renderer.js#L1696
On WebGL2 non-VSM shadows are rendered into plain depth buffers (no rgba encoding), and slope-scaled bias is achieved with simple gl.polygonOffset.
On WebGL1, depth is encoded in color textures, and with OES_standard_derivatives extension (99% support according to webglstats.com), same polygonOffset behaviour is emulated in a shader.

normalOffsetBias is what you think it is. Bias is applied in object shaders, before sampling the shadow (there is another normal bias variation, when vertices are pushed by normal when rendering the shadow map - unity does it, and it gives significant distortion. I believe they did it because they had no vertex normals in GBuffer, and they care too much about deferred, but since we're forward-rendering oriented, we can use higher quality version).

**Comment by trusktr** [comment]
@willeastcott 

Thanks for all those details!

> You can have two differently transformed mesh instances pointing to the same mesh.

What I'd like to do is be able to re-size a mesh (similar to what a scale transform does), but not affect children in the scene graph tree. In other words, a "size" in this concept is similar to a "scale", but it does not propagate to children. Children in the tree will remain the same size on the screen, but they will still translate/rotate/etc with the resized parent. Is this possible?

((This sizing concept is similar to DOM/CSS3D where resizing a DOM element in a 3D scene with CSS transforms (where all elements in the tree have `transform-style: preserve-3d`) does not resize children, it only grows or shrinks the texture of the element but all children sizes are not affected.))

Here is an animated codepen that shows exactly the concept expressed with CSS3D: https://codepen.io/trusktr/pen/e856997b50496a1b061d586e8730dd02

Note in the CSS3D example, I am rotating the parent node, which rotates (transforms) all the children, yet sizing the second node (not scaling it) does not affect children.

In Three.js this is very difficult to achieve without one of: modifying the scene graph from it's original state, writing a new shader, or re-calculating Geometry vertices on the CPU which means unable to share the same geometry with other meshes otherwise all meshes will be resized.

I'd like to share one geometry with multiple mesh instances (so that one geometry is stored in the GPU), but give them all different sizes (not give them child-affecting scales).

Does PlayCanvas support this sort of sizing?

> Read more about batching here.

That's nice for manual control. That rejected Three.js pull request makes it fully automatic, it's quite awesome. One just writes the scene graph, and can enable auto-instancing on the renderer, then it just works in most cases without having to think about it. It has options to fine tune it manually if needed.

@guycalledfrank 

> but now it's actually slope-scaled.

Oh, I didn't know about that. In other engines (I don't remember where I saw it) it is possible to adjust a variable like `slopeBias` which determines how much the bias grows relative to the slope (it can grow faster or grow not as fast). But I'm not too experienced with it, so I don't know the technicality.

In [this example](https://codepen.io/trusktr/pen/rpegZR) (uses Three.js under the hood), if you go full screen, you can see some shadow ACNE on the backround. I can't find any bias values that make it go away. The docs don't mention a public bias setting relating to slope, though in the code I do find instances of `polygonOffset`, so maybe it's just not exposed in a meaningful way?

**Comment by guycalledfrank** [comment]
> What I'd like to do is be able to re-size a mesh (similar to what a scale transform does), but not affect children in the scene graph tree

Just scale all children inversely then. If there are too many of them, put them in an intermediate node, like
- parent
  |_intermediate
     |_child
     |_child
     |_child

If you set parent's scale to 2, then set intermediate's scale to 0.5 and so on. You should be able to do the same in three, unity and anywhere else as well.

We also have support for the "scale compensation" feature from Maya: http://download.autodesk.com/us/fbx/FBX_Maya_online/files/WS73099cc142f48755-3d114b751181c40f14b1283.htm
It's just a single boolean: entity.scaleCompensation
You can try and see if it does what you want.

>That rejected Three.js pull request makes it fully automatic,
I don't see a nice automatic way to do instancing without making it even slower in some cases. For a small time cost of marking models as belonging to a particular batching group, we remove the overhead of constantly scanning and sorting every frame's draw calls and restructuring transform buffers.

**Comment by willeastcott** [comment]
Closing for now but feel free to reopen if you want to continue the discussion. 😄

**Comment by trusktr** [comment]
@guycalledfrank

> Just scale all children inversely then. If there are too many of them, put them in an intermediate node

I know I can do that, but it has some problems:

1. Introduces a layer of floating point precision error
1. Modifies the child tree. This is not ideal in situations when multiple people are writing different parts of the tree. By modifying their scale, you may interfere with their logic, therefore increasing the chances of causing errors.
1. World matrices need to be recalculated for the subtree.

In CSS3D, size and scale are two separate things. Size does not affect child properties, and does not involve touching or restructuring the child tree.

I want to achieve this feature in a non-impacting way, so currently my [custom elements](https://github.com/trusktr/infamous/) modify the vertices of a mesh's geometry without affecting child in any way, but it is not ideal when animating too many of them because that runs on the CPU, and plus for every mesh with the same geometry but different size it means I cannot instance them currently therefore more memory use and more draw calls.

One way to solve may be to have a geometry scale that is separate from the mesh scale, where the geometry scale is not used in calculation of the world transform. This separate transform is applied per mesh in the shader so that meshes can be instanced. World matrices in this case do not need to be updated for subtrees if only size has changed (win!).

That's what I would like to have. I'm not familiar with the PlayCanvas API yet other than basic demos, so I'm not yet sure how easy it may be to implement.

**Comment by trusktr** [comment]
On a conceptual level, I'm not sure if scaling in the vshader is even doable? How would that impact world transforms? How would we scale a geometry in the mesh's local space? Hmmmm... Maybe it need to be on the CPU, right when we figure the mesh's world transform, we then add a separate scale matrix for the geometry. How does that sound?

**Comment by trusktr** [comment]
@willeastcott We can keep it closed, since it's just discussion and not an issue. :)

**Comment by guycalledfrank** [comment]
I see, well, there's another way: modify the vshader (just multiply verts before transforming by matrix). In fact I have a simple test scene that does just that: https://playcanvas.com/editor/scene/560732

**Comment by trusktr** [comment]
@guycalledfrank Where do I see the code? I tried clicking on the box, and on the script, but the "edit" buttons doesn't seem to work, I can't see the script.

**Comment by yaustar** [comment]
Click on the code editor icon on the left or double click on a script asset.

https://playcanvas.com/editor/code/512433
