### ISSUE TITLE
html form autofill exception

### ISSUE THREAD

**Issue by mcmorry** [playcanvas/engine#1078]
I have an html login form created by JS in PlayCanvas.
When Google Chrome auto-fills it, there is an exception raising multiple times:

```
Uncaught TypeError: Cannot read property 'toString' of undefined
    at Keyboard.toKeyIdentifier (playcanvas-stable.dbg.js:18388)
    at Keyboard._handleKeyDown (playcanvas-stable.dbg.js:18401)
Keyboard.toKeyIdentifier @ playcanvas-stable.dbg.js:18388
Keyboard._handleKeyDown @ playcanvas-stable.dbg.js:18401
```

```
Keyboard.prototype.toKeyIdentifier = function(keyCode) {
    keyCode = toKeyCode(keyCode);
    var count;
    var hex;
    var length;
    var id = _keyCodeToKeyIdentifier[keyCode.toString()]; <=== exception here
    if (id) {
      return id;
    }
    hex = keyCode.toString(16).toUpperCase();
    length = hex.length;
    for (count = 0;count < 4 - length;count++) {
      hex = "0" + hex;
    }
    return "U+" + hex;
  };
```

**Comment by willeastcott** [comment]
Interesting. Auto-fill generates keyboard DOM events? This is kinda difficult to debug without a repro, unless you fancy submitting a PR to address this?

**Comment by mcmorry** [comment]
I'll start by doing a simple repro, and I'll try to do a fix. If I'll not be able I'll call for help :)

**Comment by mcmorry** [comment]
@willeastcott It's a bit more complicated then expected. 
I can't reproduce this issue after publishing the app because the url changes from playcanvas.com to playcanvas.as and Chrome stops suggesting the account (the one of the playcanvas forum).
But this raises another issue: I can't make Chrome to prompt for storing a new account, because I'm doing the submit by Ajax.
I was searching online and there are tons of outdated and awful html/js tricks to do that.
I'll keep trying, but if you have any ready made solution, it's more than welcome.

**Comment by willeastcott** [comment]
Is there a reason why it can't be debugged when running from the Launcher? Just open dev tools when running from the Editor and enable Break on Exceptions.

**Comment by mcmorry** [comment]
Yes for sure I can do that, and I'll do.
I just realized that the auto-saving system doesn't work on Chrome. while on Firefox is ok.

**Comment by mcmorry** [comment]
So I paced a breakpoint on the exception line and the ```keyCode``` argument is undefined.
The call stack is very short and it brings me here:
```
  Keyboard.prototype._handleKeyDown = function(event) {
    var code = event.keyCode || event.charCode;
    var id = this.toKeyIdentifier(code);
    this._keymap[id] = true;
    this.fire("keydown", makeKeyboardEvent(event));
    if (this.preventDefault) {
      event.preventDefault();
    }
    if (this.stopPropagation) {
      event.stopPropagation();
    }
  };
```
event type is "keydown" but both ```event.keyCode``` and ```event.charCode``` are undefined:
```
Event {isTrusted: true, type: "keydown", target: input, currentTarget: Window, eventPhase: 3, …}
bubbles: true
cancelBubble: false
cancelable: false
composed: false
currentTarget: Window {postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, frames: Window, …}
defaultPrevented: false
eventPhase: 3
isTrusted: true
path: (7) [input, form.loginForm, div.loginPanel, body, html.gr__launch_playcanvas_com, document, Window]
returnValue: true
srcElement: input
target: input
timeStamp: 2241.925
type: "keydown"
__proto__: Event
```
I'm not sure what is the best approach in this case.
Maybe to check if ```code``` is undefined and quit the function? Or should we still re-fire the "keydown" event?

**Comment by willeastcott** [comment]
I think it's reasonable to do:

    if (code === undefined) return;

**Comment by mcmorry** [comment]
PR sent
