### ISSUE TITLE
Rename shininess to gloss

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1081]
Shininess is a legacy of the past. It takes a value in the range 0 to 100 which is totally out of step with the other StandardMaterial scalar properties. Also, since a glossMap is essentially per-pixel glossiness, we should rename.

We should:

* Create a new property called glossiness (which is essentially shininess mapped to the 0 to 1 range).
* Alias shininess to glossiness (dividing the value by 100). The setter/getter should print a warning to the JS console that that property is deprecated and glossiness should be used instead.

Note that a property called shininess will remain in the material JSON format, at least for now.

**Comment by slimbuck** [comment]
done in https://github.com/playcanvas/engine/pull/4949

**Comment by willeastcott** [comment]
@slimbuck  Really? How come this is still here:

https://github.com/playcanvas/engine/blob/129062e8602e89b05d2d7311828fad619355b27b/src/scene/materials/standard-material.js#L242-L245

**Comment by mvaligursky** [comment]
Yeah, we should deprecate it .. move this function to deprecated as well.
https://github.com/playcanvas/engine/blob/129062e8602e89b05d2d7311828fad619355b27b/src/scene/materials/standard-material.js#L1113-L1121
