### ISSUE TITLE
Why Entity#getGuid is marked as private method ?

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#1082]
In the source code:

```js
    /**
     * @private
     * @function
     * @name pc.Entity#getGuid
     * @description Get the GUID value for this Entity
     * @returns {String} The GUID of the Entity
     */
    Entity.prototype.getGuid = function () {
        return this._guid;
    };
```

Is it a mistake ? I think `getGuid` should be a public method...

**Comment by willeastcott** [comment]
What do you want to use the GUID for?

**Comment by scarletsky** [comment]
@willeastcott 
I am writing a framework for playcanvas engine, and I need to manage all entities by guid. 😃

**Comment by willeastcott** [comment]
Hmm, OK. I guess we could make the GUID public. However, I'd prefer to:

* Expose pc.Entity#guid. Make this a read-only property by defining only a getter.
* Delete pc.Entity#getGuid.

Thoughts, @daredevildave?

**Comment by scarletsky** [comment]
@willeastcott 
How can you set specific guid for a entity ? 
This is really common when loading a scene.  
Just set `entity._guid` ?

**Comment by willeastcott** [comment]
You can't. [GUIDs are created in the pc.Entity constructor](https://github.com/playcanvas/engine/blob/master/src/framework/entity.js#L50) and should not be changed after that.

**Comment by scarletsky** [comment]
Oh, so I should not depend on `Entity.guid` in the scene.

**Comment by willeastcott** [comment]
How do you mean 'depend'?

**Comment by scarletsky** [comment]
That is, now I save the entities by the following structure:

```
{
    entities: {
        guid1: Entity1,
        guid2: Entity2
    }
}
```

And when I reload scene, I will regenerate entity, and make sure the entity has the same guid.

**Comment by willeastcott** [comment]
The scene loader does this:

https://github.com/playcanvas/engine/blob/master/src/resources/parser/scene.js#L50

So, as you can see, it's 'cheating' by setting the GUID after the entity is created to ensure the GUID is maintained every time the scene is loaded.

**Comment by scarletsky** [comment]
Yes, I know. I am doing the same thing to make sure the entity has the same guid.
And now I don't use scene loader, because I have my own data structure.
I open this issue to ask why I can't get the entity's guid by `getGuid`. As I am using TypeScript to write my framework, and using the [types](https://github.com/scarletsky/playcanvas-typings). The types is generated by @Neoflash1979 , and I notice the `getGuid` method is marked as private method.

**Comment by willeastcott** [comment]
I think I'd prefer to leave GUIDs as a private detail of the engine for now. Your use case is not very typical - you're writing a framework rather than a game/application. So for now, use _guid, but just be aware that you're accessing non-API engine internals.

You may notice that, generally, my default position is to avoid adding new API. I am keen to keen the API small, and only add to it for very good reasons.

I'll close this for now.
