### ISSUE TITLE
feature request: Euclidean distance method on Vector classes

### ISSUE THREAD

**Issue by ronkorving** [playcanvas/engine#1083]
It would be nice if a [Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) method would be exposed on vector classes. While rather trivial to write myself, I feel it makes sense to have on the Vec-classes by default. That avoids me having to expose some `playcanvas-math-helpers` file in my project to expose these functions (one per vector type).

**Comment by vkalpias** [comment]
That would be pc.Vec3#length which already exists.

**Comment by ronkorving** [comment]
Sorry, I should have been more specific. More practically speaking, when I'm looking for the distance between 2 world coordinates, I find myself writing a distance method that does:

```js
function getDistance3(vecA, vecB) {
	const x = vecA.x - vecB.x;
	const y = vecA.y - vecB.y;
	const z = vecA.z - vecB.z;

	return Math.sqrt((x * x) + (y * y) + (z * z));
};
```

So my suggestion is to have:

```js
const myNumber = myVec3.distanceTo(myOtherVec3);
```

**Comment by vkalpias** [comment]
You can subtract two vectors and get their length which is the distance between them. For example vec.sub2(vec1, vec2).length()

**Comment by ronkorving** [comment]
Fair enough 👍  It may still be worth considering a dedicated method for it, but I'll leave it at that. Cheers.

**Comment by mcmorry** [comment]
@vkalpias so if I have vec1 and vec2 I have to allocate a new vector to calculate the difference and finally the length. Is it correct?
In case this distance must be calculated every frame (or more time per frame) will be better to cache the temporary vector in a class field.
The idea to have "static" methods like the one suggested by @ronkorving is not that bad and could be applied in more cases.
To keep the engine source small, we could make an extension library that adds these methods to main engine objects, like pc.Vec3.distance(vec1, vec2)

**Comment by willeastcott** [comment]
I kinda agree with you here. A static function makes sense. The reason why I don't want to do this impulsively, though, is because this _might_ make the API a little inconsistent. For example, if we add a static distance function, should we make the dot and equals functions static too?

**Comment by vkalpias** [comment]
I have found that I almost always need a few temporary vectors in my scripts if I'm to do any vector math so I think in realistic use cases you would have at least one temporary vector stored in your script in initialize and just use that for any math operations.

**Comment by mcmorry** [comment]
When I started using some vector math in PlayCanvas I found very weird the add2 method and alike. I would have probably preferred a pc.Vec3.add(vec1, vec2) that returns a new Vec3, to avoid manually creating a vector for the result.
I mean, add2 is the just a shortcut for `result.copy(vec1).add(vec2);`

One more use case for static methods is the Color.fromString. I feel more natural to type
`var color = pc.Color.fromString('#123456');`
than
`var color = new pc.Color().fromString('#123456');`
of course, if I have to keep doing this multiple times is better to use the instanced method and avoid allocations.

But for sure the methods that would really benefit from being static, are all those methods that return scalar values and not new object instances, like distance or distanceSqr.

Another case is the lerp method. Wouldn't be easier to learn this:
```
var res = pc.Vec3.lerp(vec1, vec2, t);
```
and to avoid allocations also
```
var res = new pc.Vec3();
pc.Vec3.lerp(vec1, vec2, t, res);
```

**Comment by vkalpias** [comment]
I believe the thinking for the math API was to make a minimal API that promotes practices that avoid excessive memory allocations. It's something that might look a bit odd at first but it kinda forces you to think about your allocations beforehand - you can be sure that lots of people who are unfamiliar with JavaScript or programming in general will really abuse the methods that create new instances of vectors..
