### ISSUE TITLE
Errors and poor performance on mac + chrome.

### ISSUE THREAD

**Issue by maungers** [playcanvas/engine#1088]
Hi!
We have errors and poor performance when using mac + chrome
https://interactive.olympicchannel.com/avatar/

![image](https://user-images.githubusercontent.com/22077882/36029621-ea8e476e-0dde-11e8-8c27-d997f7927575.png)

![image](https://user-images.githubusercontent.com/22077882/36029630-fbffd08a-0dde-11e8-9f05-6ae615822255.png)

**Comment by mcmorry** [comment]
I run it on mac + chrome and I didn't get those errors.
Instead, I have tons of "pc.Mat4#invertTo3x3: Matrix not invertible"
Also, I don't have any performance issues, but other types of issue. Probably it's still in development and you already know, but here there are: avatar cap customization crashes, pause->quit->restart sequence is broken, after many games played and going back to "Cross Country Skying" when I tap it turns two times, the opponent to beat has the cap/glasses moving independently from the head.

**Comment by maungers** [comment]
yes, in that you described there are no problems, it's easy to fix)
it's about reducing performance and incomprehensible mistakes when using mac + chrome

all who use mac + chrome please test this app:
https://interactive.olympicchannel.com/avatar/

**Comment by daredevildave** [comment]
I don't see those errors when running? Are there repro steps?

**Comment by willeastcott** [comment]
@maungers Do you still have problems on your Mac system if you use Chrome Canary instead? It may be a regression in Chrome that Google have already fixed.

**Comment by maungers** [comment]
I do not know if this can be reproduced ... I do not have mac + chrome
These problems were reported to us by our testers.
I think the problem was in the old version of chrome, I advised the testers to update the chrome =)
If the problem persists, I will report this...

Thank!

**Comment by willeastcott** [comment]
OK, fine. Chrome Canary can be found [here](https://www.google.com/chrome/browser/canary.html).
