### ISSUE TITLE
[BUG] Enabled flag of children of cloned entity are not working

### ISSUE THREAD

**Issue by mcmorry** [playcanvas/engine#1089]
I have an entity with multiple children that I'm cloning.
In the initialize method of the cloned entity, I set enabled to true or false for each child.
The code is getting executed, but the children stay as they were in the template object.

**Comment by SHADOWELITE7** [comment]
have you applied it

**Comment by mcmorry** [comment]
Probably not. What do you mean?

**Comment by SHADOWELITE7** [comment]
like when you are coding, you would have to apply the script in the code editor so it may sync and work with your object

**Comment by mcmorry** [comment]
Yes of course... I also put breakpoints and tested in multiple ways. Doesn't work.

**Comment by SHADOWELITE7** [comment]
hmm this seems confusing

**Comment by mcmorry** [comment]
repro: 
https://playcanvas.com/project/534820/overview/children-enabled-bug

the Factory script clones the box template and enables it.
The Box script is setting one child enabled and the other not enabled, but both children are visible.

**Comment by yaustar** [comment]
'Fixed': https://playcanvas.com/editor/scene/587196

Unlike Unity3D, when referencing an entity in the attributes, it *isn't* a relative path/reference. So when you clone the parent entity, it is still referencing the entities of the 'prefab'/template.

I think there is consideration to change this but in the meantime, I've worked around this by using `entity.findByName`.

**Comment by mcmorry** [comment]
I understand, but this is really bad...  the clone should really clone the whole entity.

The documentation is even more confusing by not saying that references are not remapped:
https://developer.playcanvas.com/en/api/pc.Entity.html#clone

> Create a deep copy of the Entity. Duplicate the full Entity hierarchy, with all Components and all descendants

And also the names have to be unique and we can't use the editor at full potential.
I really hope the team will consider this (and prefabs) a top priority.

**Comment by yaustar** [comment]
Unfortunately, there was never a 'feature' that entity references could be relative (ie they were always absolute). AKA a clone of a global reference is still a global reference.

It's worth noting the `entity.findByName` only searches it's children if that helps? It means that the entity names only has be unique within the scope of the children.

**Comment by mcmorry** [comment]
yes, but lacking the prefab concept, and having only the clone method to create multiple instances of the same object, is not a missing feature... is more like a flaw in the design.

**Comment by mcmorry** [comment]
Also, I went inside the cloned object and this is also very strange.
The cloned entity has the two children referring both to child1:

![screenshot 2018-02-09 17 55 36](https://user-images.githubusercontent.com/1020257/36039453-cb37e2a6-0dc2-11e8-9cd7-19ec47c2a706.png)

**Comment by yaustar** [comment]
In your project, the template has it's attributes setup incorrectly.

![image](https://user-images.githubusercontent.com/16639049/36039864-acc61b50-0dbb-11e8-9e31-63abf730b0d1.png)

**Comment by mcmorry** [comment]
oh my shame... sorry.
I'm trying now to monkey patch the clone method to take the name from the assigned entities in the attributes and remap them on the cloned object. I hope it will simplify my work.

**Comment by mcmorry** [comment]
so as a workaround I call this function in the initialize:
```
Box.prototype.remapEntities = function() {
    var attrs = this.__scriptType.attributes.index;
    for (var attr in attrs) {
        if(!attrs.hasOwnProperty(attr)) continue;
        if (attrs[attr].type == 'entity') {
            this[attr] = this.entity.findByName(this[attr].name);
        }
    }
};
```

**Comment by yaustar** [comment]
It may be a bit slow as now every entity reference attribute will attempt to find a child entity. Also, in the case of a reference to an entity that is above itself, (e.g a parent or a parent of a parent), it will result in a null reference.

**Comment by mcmorry** [comment]
> It may be a bit slow as now every entity reference attribute will attempt to find a child entity

yes but if this is a cloned object I have to do it in any case for all of them otherwise the reference will be wrong and useless.

> Also, in the case of a reference to an entity that is above itself, (e.g a parent or a parent of a parent), it will result in a null reference.

True, it doesn't address all cases, but is enough for simple entities where the view logic is implemented all in the topmost parent of the prefab.
