### ISSUE TITLE
Shadow Artefacts & Precision issues: point light depth buffer not cleared, large bias issue, inconsistent precision depending on light range.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#109]
1. Point light shadows seems **not clearing depth buffer** before rendering depth maps, leading to geometry outside of range of light affecting depth buffer creating "shadows" where they should not be at all (artefacts).
2. Light **shadow is dependant on Range value dramatically, and inconsistent for different light types**: For Point light low range increases shadow precision. For Spot light low range dramatically decreases precision, and setting very large range for spot light makes shadows way more precise.

Demo to replicate problems:
http://playcanvas.com/max/shadow-culling/designer/pack/d61d3d0c-7c7e-11e4-984b-12313b0a5ec6

 * Blue point light in the middle of the scene is point light, within big box has really weird circular shadows, looks like shadow precision or distance is linear per depth map rather circular relative to light source.
 * Red spot light has low range, and drops nearly no shadows, increasing range makes shadows to appear.
 * Yellow and Green point lights show same problem where they have low range, and have some weird shadows appearing which is related to boxes in the middle. As moving `box_big` will affect that artefact, assuming it is out of range and not cleared.
 * Take in account what Cull state is set to material on `box_big`, and changing that state how it affects shadows too.
 * Change for testing "Cast Shadows" on `floor` - it affects yellow and green lights dramatically.

Screenshot:
![screen shot 2014-12-09 at 15 20 09](https://cloud.githubusercontent.com/assets/636263/5359599/7e4af278-7fb6-11e4-9c97-5edec6617323.png)

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/commit/3e4f3b99739ca9e421b3e6d24a8473c63710f3bb

**Comment by Maksims** [comment]
Most of problems are fixed indeed, except one:
 * Red spot light has low range, and drops nearly no shadows, increasing range makes shadows to appear.

Spot light still get better precision with increased range (which should opposite just as for point light), so that particular bug has been missed.

**Comment by willeastcott** [comment]
So it's very hard to discern the problem by looking at that demo. However, a pixel's RGB is: Ambient contribution + spot contribution. If you have the pixel in shadow, the result is: Ambient contribution. So if the spot contribution is very small, it will be hard to see the shadows. This is what I would expect. And for spots with a small range, the rapid attenuation over a short distance will mean that shadows will be hard to see.

**Comment by Maksims** [comment]
Spot Light Precision issue.
Issue: lower range - worse precision.
Should be: lower range - higher precision.
http://playcanvas.com/max/shadow-culling/designer/pack/49982d82-9be2-11e4-a815-12313b0a5ec6

Point light with no `cast_shadow` flag with geometry close to far_clip of depth camera.
http://playcanvas.com/max/shadow-culling/designer/pack/6d1b4380-9be1-11e4-b6ff-12313b0a5ec6
Issue: low range with some geometry at the end of range, with geometry between that has no `cast_shadows` flag, will render artefacts and shadows where should no be any shadows.
That is issue from above for green/yellow light.

Please fork project to play with packs, and do not modify packs specified above to keep demos with issues as test case.
