### ISSUE TITLE
Performance issue when cloning multiple entities with Element components.

### ISSUE THREAD

**Issue by mcmorry** [playcanvas/engine#1092]
I'm generating 20 poker tables (2D) with 10 seats each.
Each seat is composed by 25 nodes with various elements (text, image) and scripts.
I do it by cloning a Table template, and the table itself clones the Seat template 10 times.
It takes around 30 seconds to do it, and each additional table takes more and more time.

Here is a screenshot of the profile from Chrome.
Any hint on the reason and how to address it?

![screenshot 2018-02-11 13 10 26](https://user-images.githubusercontent.com/1020257/36073216-030957da-0f2d-11e8-977e-74456e8f9b1b.png)

here is a link to download the saved profile:
https://www.dropbox.com/s/0xrw6hux5yqh9kz/Profile-20180211T131113.json?dl=0

**Comment by mcmorry** [comment]
I got a decent improvement by disabling the container of the tables, and enabling back once the tables are created.
As soon as I enable it, it still takes many seconds to resume the app.

**Comment by yaustar** [comment]
20 tables * 10 seats * 25 nodes = 5000 entities being created + any script initialisation calls of scripts attached to the entities.

Do you need all 20 tables created at the same time (ie will everything you have cloned be visible at the same time?)? If not, you could stagger out/lazy load some of the entities over time.

Does creating a single table cause a significant performance hit?
What happens when you remove the UI elements (as it looks like that's what eating up most of the frame)?
Are you moving/reparenting any UI elements?

**Comment by mcmorry** [comment]
Yes are a lot of elements and for sure I can create only 3 tables and recycle them while scrolling, but I was very surprised of the very bad performance.
It get worst and worst after each new table. It looks like that the engine has to go through all the node right after a new node is added in the hierarchy, maybe to define the rendering order or something similar. I'm not sure.

I just clone and add the new entity to a parent. Nothing else.
My initialization scripts are very light and are not the source of the slowdown  (except for the cloning of new entities)

**Comment by yaustar** [comment]
Can you you try the 20 tables without the UI elements (or disable them completely in the template)? 

Does each table have it's own UI screen? Or is it adding elements to the same UI screen?

**Comment by mcmorry** [comment]
By adding a 2D Screen to each table makes it way faster! Thanks.
It still gets slower and slower, but much less. And using other tricks as a lazy loading of the seats or, even better, a recycling of the tables while scrolling will be smooth enough also on mobile.

**Comment by mcmorry** [comment]
On mobile even to generate 2 tables it takes 4 seconds. It can't be...

**Comment by mcmorry** [comment]
@daredevildave @willeastcott 
I set up a simple repro that reproduces the issue. It's private as it contains some reserved content. 
So, please, if you can help, I can add you.

It directly generates some tables (the amount can be changed in real-time in the "LobbyView" attribute) and prints in the log some timings.

3 tables on my Mac takes around 0.7 seconds. On a Samsung S4 around 5.8 seconds.

**Comment by mcmorry** [comment]
ok... I cleaned it from most of the reserved contents and made it public.
Here is the project:

https://playcanvas.com/project/535478/overview/performance-issue

I know that JS is not as fast as native code, but I did much more complex UI in Unity that is loading much faster on mobile than this one on Playcanvas. So, I think it has to be an issue somewhere.

**Comment by vkalpias** [comment]
This is related to each Element component calling `_updateScreen` on every `insert` event which causes parent `Screen` to re-calculate the draw order for every child again and again.

Also there are other optimizations to be done as well in the Element component, mainly updating text should not loop through all the characters in the font every type to find min / max bounds and also any for loops should be optimized as much as possible.

Ultimately we need to avoid the continuous recursion of children during the `syncDrawOrder` call in the Screen component.
