### ISSUE TITLE
loadScene vs loadSceneHierarchy/loadSceneSettings

### ISSUE THREAD

**Issue by stelcheck** [playcanvas/engine#1095]
According to https://github.com/playcanvas/engine/pull/284 `loadScene` is meant for engine users, and `loadSceneHierarchy` and `loadSceneSettings` are meant for convenience. However, `loadScene` is not documented.

  1. Is `loadScene` a public API?
  2. What is the behavior difference between the different loaders?

**Comment by willeastcott** [comment]
`loadScene` was made public in release [1.26.1](https://github.com/playcanvas/engine/releases/tag/v1.26.1).
