### ISSUE TITLE
Errors after destroying cloned objects.

### ISSUE THREAD

**Issue by Tatsujinichi** [playcanvas/engine#1100]
https://playcanvas.com/editor/scene/588649

Maybe worth noting I had no problems when I cloned an entity that I created in code.

**Comment by sethgillett** [comment]
Could you specify what code specifically is causing the error and/or steps to reproduce.

**Comment by Tatsujinichi** [comment]
Just running the project in chrome with the inspector open should trigger
the error after a few seconds.  The failing code appears to be the call to
the update function of a script.  After destroying.

**Comment by sethgillett** [comment]
Interesting. The error seems to occur specifically when an entity has more than one script attached, and one of the scripts calls destroy on the entity. For example, if entity A has script B and script C, and script B calls destroy on entity A, the update method on script C is still called, _even after the entity is destroyed_ resulting in an undefined error.
