### ISSUE TITLE
FRAMEBUFFER_UNSUPPORTED Particle Error on iPhone 5c w/ iOS 10.3.3 (max version)

### ISSUE THREAD

**Issue by pete-richter** [playcanvas/engine#1101]
When using a basic particle system on an iPhone 5c, the following error is thrown:

[Error] ERROR: FRAMEBUFFER_UNSUPPORTED
	error (launch.js:7518)
	_checkFbo (playcanvas-stable.dbg.js:4915)
	updateBegin (playcanvas-stable.dbg.js:5021)
	drawQuadWithShader (playcanvas-stable.dbg.js:6024)
	addTime (playcanvas-stable.dbg.js:15661)
	prewarm (playcanvas-stable.dbg.js:15538)
	rebuild (playcanvas-stable.dbg.js:15241)
	ParticleEmitter (playcanvas-stable.dbg.js:14934)
	onEnable (playcanvas-stable.dbg.js:26650)
	initializeComponentData (playcanvas-stable.dbg.js:21280)
	initializeComponentData (playcanvas-stable.dbg.js:26776)
	addComponent (playcanvas-stable.dbg.js:21256)
	_openComponentData (playcanvas-stable.dbg.js:31992)
	_openComponentData (playcanvas-stable.dbg.js:31998)
	_openComponentData (playcanvas-stable.dbg.js:31998)
	parse (playcanvas-stable.dbg.js:31959)
	open (playcanvas-stable.dbg.js:31126)
	open (playcanvas-stable.dbg.js:30030)
	(anonymous function) (launch.js:7011)
	_preloadScripts (playcanvas-stable.dbg.js:20625)
	(anonymous function) (launch.js:7007)
	done (playcanvas-stable.dbg.js:20516)
	onAssetLoad (playcanvas-stable.dbg.js:20529)
	fire (playcanvas-stable.dbg.js:608)
	(anonymous function) (playcanvas-stable.dbg.js:32333)
	(anonymous function) (playcanvas-stable.dbg.js:30013)
	(anonymous function)
	onload (playcanvas-stable.dbg.js:30848)

**Comment by willeastcott** [comment]
So this is reproduced by:

* Create new empty scene.
* Create a default particle system entity.
* Launch on iPhone 5C

?

**Comment by pete-richter** [comment]
I’ll try it with a fresh scene.  I admit I didn’t isolate it, but disabling it seemed to alleviate the issue.

**Comment by willeastcott** [comment]
Any luck reproducing with a fresh scene?

**Comment by pete-richter** [comment]
Sorry for the delayed response; I thought I already had.

It does not throw the error, it works fine!  My original scene isn't wildly complicated.  I have about 7 spot-lights total, and very very basic materials.  Two with Cubemaps and that's it.  What else might I be doing that's messing it up?

**Comment by willeastcott** [comment]
So many possibilities. 7 spot lights is quite a lot. Are they shadow casting spotlights? Could be running out of VRAM? Hard to say. If you can create a simple scene that reproduces this, I can debug... I don't have a 5C, though. But maybe I can find something similar somewhere in the office.

**Comment by pete-richter** [comment]
I’ll see what I can do.  I’m tinkering right now with implementing word wrap on the Text Element, since I’m needing it pretty badly, as well as a single set of lights that travels with you, and assumes predefined positions/colors/etc for each installation you visit.  Everything else is either unlit or light mapped.

Thank you for looking into this.  I’ll do what I can to help get to the bottom of the issue.  It’s good to know that it’s at least possible, and does run reasonably well with 4 digits worth of particles.

-Pete

**Comment by pete-richter** [comment]
On that topic…

Is there any way to get character metrics from a text element?  :)   I’ll “gaffle” it in the meantime with some magic attributes.

**Comment by vkalpias** [comment]
There's no 'official' way to get character metrics - I suggest going through the text element and checking out the code basically. 

Having said that we are going to implement text wrapping ourselves soonish I believe.

**Comment by pete-richter** [comment]
Already in the weeds, sir!  ;D.    Thanks for the prompt response!

**Comment by willeastcott** [comment]
Hey @pete-richter - I think I'm gonna close this if there's no repro. Please re-open if you can generate something though. Also, you may have noticed but PlayCanvas supports text wrapping for the element component now. Please try it out. 😄

**Comment by pete-richter** [comment]
Totally fine, I should have closed it, sorry.

I do have another question:
I noticed that the new Text Element is either:
- rendering at twice the size when not using device pixel ratio,
- or, rendering at half size when rendering at device pixel ratio

The only workaround I see presently is having some sort of event listening script on text elements that would hear events from my existing AspectRatioManager, but I was curious if you had a better suggestion.

The reason I don’t “just pick one” is because my aspect ratio manager is actively measuring frame rate, and if it determines the fps is too low, it disables device pixel ratio rendering, which is actually working great.  I was just wondering if there was a way to get the UI elements to play along.  :)

**Comment by willeastcott** [comment]
Hmmm. @daredevildave - shouldn't there at least be a mode for screens that's based on proportion of screen size rather than pixel resolution. For games that adjust canvas resolution based on device performance, say, having to adjust UI element sizes to compensate would be a real pain!

**Comment by daredevildave** [comment]
Please make a separate issue/thread.

**Comment by pete-richter** [comment]
On it.
