### ISSUE TITLE
Bug: Cannot start VR with Windows Mixed Reality - Context lost.

### ISSUE THREAD

**Issue by tmey2016** [playcanvas/engine#1104]
Windows Mixed Reality Portal
Edge browser

When I click the orange Goggles to start WebVR, the canvas within the browser turns black. The VR environment does not launch.

F12 Developer Tools console output:

WARNING: Context lost. 
WEBVR22602: VRDisplay.requestPresent is rejected - presenting HTMLCanvasElement's context is not compatible with the VRDisplay. Event.preventDefault() must be called during the firing of webglcontextlost event on the presenting HTMLCanvasElement.

Tested projects: WebVR Hello World, WebVR Lab 
Environment: Windows 10 Pro 1709
Hardware: Samsung HMD Odyssey, Microsoft Surface Pro 2

Taking similar action in three js WebVR sites works correctly: gives the browser prompt, then the VR portal environment is replaced by the WebVR project environment.

**Comment by willeastcott** [comment]
We don't have that device. I don't suppose you're in a position to develop a fix? 😄

**Comment by willeastcott** [comment]
Thanks for taking the time to investigate.

So implementing this doesn't seem _too_ complicated. The main issue is recreating the WebGL resources for certain PlayCanvas objects, namely:

* pc.Texture
* pc.VertexBuffer
* pc.IndexBuffer
* pc.RenderTarget

There might be some others but those 4 are the main ones. To create any of those, we pass the graphics device into the constructor. We could just add 'this' to an array on the graphics device. So when the context is restored, we just iterate over the arrays and invalidate or recreate the required WebGL resources.

**Comment by willeastcott** [comment]
Made pretty good progress on this today. It's maybe 90% implemented now. 😄
