### ISSUE TITLE
Issue with click event on touch screen

### ISSUE THREAD

**Issue by mcmorry** [playcanvas/engine#1107]
I have a button that subscribes to the click event.
As soon as the click occurs I hide the button and I show a new one in the same position.
When I test this on desktop it works fine, but on mobile, it triggers the click event also on the second button.

Here is the repro:
https://playcanvas.com/project/536769/overview/ui-issues2

Hit play and look in the console.
Click on the red button. It shows the blue button and prints “click 1”.
Then click on the blue button. It prints “click 2”.

On mobile, as soon as I touch the red button, it prints “click 1” and “click 2”.

**Comment by mcmorry** [comment]
So is not a Playcanvas bug, but as pointed by @vkalpias, is Chrome that simulates mouse events after touch events.
This can be avoided by calling ```event.preventDefault()``` on touch end event.
While this could not be a valid solution for all situations, it could be probably useful to add this info it in the documentation to avoid hours of debugging.
If you agree, I could try to integrate it.

**Comment by willeastcott** [comment]
Sure! Please go ahead and enhance the documentation to help others who may have problems with this behavior.

**Comment by mcmorry** [comment]
@willeastcott PR sent. I hope it will be good. Otherwise, let me know how to improve it. :)
