### ISSUE TITLE
Should pc.Entity.destroy() not recurse over non-entity graph nodes?

### ISSUE THREAD

**Issue by ronkorving** [playcanvas/engine#1116]
Hi,

We wandered into an interesting problem today. When we attach an object B to the skeleton of an object A, that object B is not destroyed when we destroy object A. This seems a bit weird to us, but could be by design. Can anyone confirm is this is indeed by design?

Because bones are not `pc.Entity` instances, the line of code that prevents recursion to continue through the skeleton is [this](https://github.com/playcanvas/engine/blob/722873b7d3bea4bfeae30dede6170fe3211f9a4c/src/framework/entity.js#L282). To make it work, we could simply remove this line and implement a recursing `destroy` method in `pc.GraphNode`.

**Comment by Maksims** [comment]
The reason it happens, is that Skeleton is made of GraphNodes, but it is not part of Entity children, and belongs to AnimationComponent. Additionally, GraphNodes do not have `destroy` method, it is purely Entity's concept.
So, technically it behaves as it should behave. Although additional feature could be requested: iterate through Skeleton graph, and destroy any descendant entities in case of components entity destruction.

**Comment by mvaligursky** [comment]
This is not an issue with the Render component, which unlike the Model component uses instances of Entity for its bones, and any attached entities get destroyed correctly.
