### ISSUE TITLE
GraphNode#removeChild don't update scene

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#1120]
Here is a demo: 
https://playcanv.as/index/twecYgdm

Type the following test code in console:

```js
m = pc.app.root.findByGuid('bcaabe3f-30cd-4a8b-ae2f-0f9c73c7ea35');
p = m.parent;
p.removeChild(m);
```

The scene DONOT update until you add the following line:

```js
m._notifyHierarchyStateChanged(m)
```

**Comment by willeastcott** [comment]
This demo link now returns a 404. I know this issue is old, but if it can't be reproduced, we'll have to close it.

**Comment by scarletsky** [comment]
Try the model viewer starter kit:
https://playcanv.as/index/tduyP6QP

Then typed the following code in console:
```js
var m = pc.app.root.findByName('Model')
pc.app.root.removeChild(m);
// m._notifyHierarchyStateChanged(m)
```

![Untitled](https://user-images.githubusercontent.com/2386165/59153900-054b6500-8a98-11e9-90cc-fe7ac1bd35d0.gif)

**Comment by willeastcott** [comment]
Ahhh, OK. So, let's say you clone an entity with a model component. I believe it still renders, even if it's not added to the main hierarchy. So, I guess similarly, if you remove a child, it won't stop it rendering. TBH, I'm not sure what the correct behavior should be here. Hey, @vkalpias, what do you think?

**Comment by vkalpias** [comment]
That sounds like a bug to me.

**Comment by willeastcott** [comment]
Just to follow up @Maksims, as far as I can remember, a model component will render even without being added to the hierarchy. So it seems inconsistent to stop rendering when taking a model out of the hierarchy?

**Comment by Maksims** [comment]
That's actually not the case here:
```javascript
var entity = new pc.Entity();
entity.addComponent('model', { type: 'box' });
pc.app.root.addChild(entity); // rendering starts only here
```
Then if hierarchy is affected, like it is disabled - it will stop rendering too.
Although, using removeChild on any of ancestor, will not affect descendants - which is a bug as well.

It makes sense, that if it is not part of hierarchy, it shouldn't work, as many mechanics are tied to hierarchy and its structure.

**Comment by willeastcott** [comment]
Wow, you're right. I just tested. Hmm, I wonder why I thought that.

OK, fine, let's merge. 😄
