### ISSUE TITLE
app.renderLine doesn't work on my 2nd app

### ISSUE THREAD

**Issue by ronkorving** [playcanvas/engine#1122]
My use case (switching from a DOM based out-game to a PlayCanvas in-game) requires the creation and destruction of `app` objects as part of its natural lifecycle.

One problem I ran into is that it seems that `app.renderLine(...)` only works on the very first app. Once I destroy that app, then create a new one, I can no longer render lines on that second app. My guess is it has something to do with [the global state](https://github.com/playcanvas/engine/blob/4a28b63575fbecc98b15b5dc4b8f794ed12e6637/src/scene/immediate.js#L4) that `_addLines` depends on, but I'm not 100% sure.

Does anyone have any advice? Is this indeed a PlayCanvas bug?

**Comment by daredevildave** [comment]
Hmm, yes, I had just noticed there is some global state used by renderLines. I'm currently updating it to work with the new [Layer interface](https://github.com/playcanvas/engine/tree/layers) and I've removed the global state as part of that change. Release for Layers is targeted in the next few weeks, but it's a pretty big change.

**Comment by ronkorving** [comment]
Related: #1086

**Comment by willeastcott** [comment]
Fixed by https://github.com/playcanvas/engine/pull/1124
