### ISSUE TITLE
Text Alignment Doesn't Seem to be WYSIWYG

### ISSUE THREAD

**Issue by pete-richter** [playcanvas/engine#1126]
https://playcanvas.com/project/540564/overview/textbugdemo

In attempting to make a Screen with 2 text elements: 1 anchored to the top as a title, and one anchored to the bottom as content, allowing the layout to be easily adjusted by simply changing the screen height if either element's content changes -- the following was discovered:

The expected behavior is found in the editor, however, upon launch (in both desktop and mobile (Mobile Safari and Chrome Mac) the expected alignment, especially of the top-anchored element, does not match what is seen in the editor.  Desired results can be achieved by manually changing the y-value of the text elements, but that destroys the automation provided by the anchoring attributes.

**Comment by willeastcott** [comment]
I think @daredevildave or @vkalpias are best placed to advise you here. But if I select the Title under screen 1 and set to 'Bottom Left' and then set Y translation to -57, it looks fine and seems to work as expected. Same for Title under screen 2. Set preset to Bottom Left and Y position to -57.

**Comment by pete-richter** [comment]
Was hoping to keep the Y positions at 0.  :)   Semi-Liquid Layout.

**Comment by vkalpias** [comment]
Does it work if you make sure your margin is 0?

**Comment by pete-richter** [comment]
My goal was to keep all margin, alignment, and anchor values at 0 or 1, as they apply to floating the given element to the top, or sinking it to the bottom.  So that the only real arbitrary values were the actual width and height of the elements themselves, and the width and height of the encompassing canvas.

In the editor of the project I supplied, you’ll notice that the Y values of both title and subtitle are 0, yet they stick to the top and bottom, respectively.  And you can control the spacing simply by changing the height of the canvas.  But in the player, it’s not reflected as such.

**Comment by daredevildave** [comment]
I'm not sure I completely follow what you are trying to achieve here. 

However your project as I can see it today is set up incorrectly. Your title elements have anchors set to `[0,1,0,0]` which means your bottom anchor is larger than your top anchor. (We should prevent this in the Editor). You'll notice if you select the anchor gizmo in the viewport it snaps back to 0.

To anchor your title to the top set your anchors to `[0,1,0,1]` and set the pivot to `[0,1]` and your text alignment to `[0,1]`.

I don't see any bug here.
