### ISSUE TITLE
"Create Default Loading Screen" creates Legacy Preloader Script

### ISSUE THREAD

**Issue by pete-richter** [playcanvas/engine#1127]
When using the "Create Default Loading Screen" feature in the Scene Settings panel, a legacy script is created, even in projects that are not set to use legacy scripts.

**Comment by willeastcott** [comment]
The loading screen script format is not related to the script component script format. It just defines a function of the form:

```
pc.script.createLoadingScreen(function (app) {
    // Implement your custom loading screen...
});
```

I just tested the feature with a new project (current scripting system) and edited the page background color in the CSS. Works just fine.

**Comment by pete-richter** [comment]
My mistake, I saw an app…. Reference without a this, and figured it was deprecated, like the Toon Shader example I was messing with the other day.
