### ISSUE TITLE
Exception on screen component removal

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1129]
To repro: 

1. Add a Screen component to an entity.
2. Add a child entity with an element component.
3. Delete aforementioned Screen component.
4. Observe this in Chrome Dev Tools:

![image](https://user-images.githubusercontent.com/697563/37316425-4179af50-261c-11e8-9c84-b18388cc8a8b.png)

**Comment by daredevildave** [comment]
Fixed by 04e03b70636451df81d942260f11929753461309
