### ISSUE TITLE
Implement a trail renderer

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#114]
User: pryme8 wants to implement various projectile effects and stated that he'd be interested in seeing an equivalent of the Unity TrailRenderer in PlayCanvas.

http://forum.playcanvas.com/t/development-log/166/12

This could be implemented completely as a script.

**Comment by Maksims** [comment]
This feature is too case specific. Implementing general purpose trailing system might be too niche. It worth making this as tutorial example as base for experiments and specific implementations by other devs.
Additionally this ticket has been stalled for too long.

**Comment by yhydra** [comment]
Would be great to get this open again

**Comment by 7ombie** [comment]
Personally, I would find this very useful.

**Comment by yaustar** [comment]
We do have a trail example in the project samples section of the tutorials as a starting point: https://developer.playcanvas.com/en/tutorials/rainbow-trail-with-mesh-api/
