### ISSUE TITLE
Light layers

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#115]
We need a way to say that a given light lights a given set of models. This could be automated based on a lights bounding volume or specifiable in the Designer interface (create layer and add models to it and specify the layer on the light).

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/commit/f6c0e75952203887ec6fe49bbaee81be443c3941

Note that we need to expose this in the editor still. This is obviously just the engine component for this feature.
