### ISSUE TITLE
onEnable is not called after initialized

### ISSUE THREAD

**Issue by crazydadz** [playcanvas/engine#1158]
For bug reports, include:

### Description

To listen to onEnable and onDisable, you need to addEvent inside initialize function.
It seems that onEnable is only called after disabling once.

Repro project: https://playcanvas.com/project/544785/overview/onenable-issue

### Steps to Reproduce

1. Press play and check console.logs
2. Keyboard Left Arrow to enable child
3. Keyboard Right Arrow to disable child.

` for(var i = 0, len = this.scripts.length; i < len; i++) {
                script = this.scripts[i];
                script.enabled = script._enabled;

                if (! script._initialized && script.enabled) {
                    script._initialized = true;

                    script.__initializeAttributes(true);

                    if (script.initialize)
                        this._scriptMethod(script, ScriptComponent.scriptMethods.initialize);
                }
            } `

https://github.com/playcanvas/engine/blob/7392a3efcd5df0704fae6aed9ca4f88e60c973a5/src/framework/components/script/component.js line 200-212

script.enabled = script._enabled; should be called after initialize method has been called to ensure onEnable is getting fired correctly.

Thank you,
David

**Comment by vkalpias** [comment]
Hi, this is by design - onEnable will only be called after the script has been disabled. If you need your code in onEnable to be executed after initialize I suggest you add a call to onEnable inside your initialize function.

**Comment by mcmorry** [comment]
It's an unfortunate design choice. I also had this issue. It's more natural to think that an even should be triggered as soon that condition becomes true. And by enabling a disabled object the first time is what you expect to happen.
But going to change it now will go to break all the code that is manually calling the onEnable function :(
