### ISSUE TITLE
VR Template WebVR Polyfill Failure

### ISSUE THREAD

**Issue by pete-richter** [playcanvas/engine#1170]
Project:
https://playcanvas.com/project/546639/overview/targetpractice
Launch:
https://launch.playcanvas.com/601541?debug=true

Present on:

Chrome for Android, Pixel XL v1
Chrome Canary for Android
Firefox for Android
Opera for Android
Mobile Safari, iPad v5

Issue is a blocker for the Pixel XL, as webvr-polyfill fails to initialize.

Issue is present on iPad, but webvr-polyfill does at least initialize enough to bifurcate the view and begin using full motion control, instead of swiping, as is necessary on the Pixel XL.

Was also tested on an iPhone 5c in Mobile Safari with zero issues.

Firefox for Android incorrectly read the accelerometer data.
Chrome Canary went absolutely bonkers with the accelerometer data, sending the camera whipping all over the place, similarly to if one were supplying degrees where radians were expected. 

Ironically, Opera for Android is the only Android browser that seems to, despite still throwing the errors, initialize WebVR polyfill to the point of the application actually being usable.

Error from Pixel XL pasted below:

Failed to recalculate device parameters.

[webvr-polyfill.bad0c71.js:675]: Unable to present.

Error: Unable to present.
at HTMLDivElement.onFullscreenError (https://code.playcanvas.com/webvr-polyfill.bad0c71.js:675:16)
at HTMLDocument.fullscreenerror (https://code.playcanvas.com/playcanvas-stable.dbg.js:145:18)

**Comment by fwelz** [comment]
Hi have the same problem with Moto G5 Plus and Asus ZenFone 2 and 3, so it seems like VR stopped working in any device with Android.

**Comment by willeastcott** [comment]
We're removing the dependency on the WebVRPolyfill from the engine:

https://github.com/playcanvas/engine/pull/1648

Soon, you'll optionally be able to include it yourself in your projects (and be able to select whichever version you want). Therefore, I'm closing this.
