### ISSUE TITLE
Particle system loading

### ISSUE THREAD

**Issue by lvenerosy** [playcanvas/engine#1172]
When I play particle systems through user input, there is a stutter the first time even though the systems have been already played thanks to ```Auto Play```. The goal I am working towards is to be able to have the particles run once during game start so that there is no stutter for the user. So is it a bug that this, what I suppose to be, loading still needs to happen when the particles have already been played ?

Here is my test project inspired by the explosion tutorial https://playcanvas.com/editor/scene/601723. It is possible to spawn an explosion by left clicking.

**Comment by lvenerosy** [comment]
A bit more information, this stutter is more visible on lower end devices.

**Comment by willeastcott** [comment]
Today, we deployed [Engine v1.17.0](https://github.com/playcanvas/engine/releases/tag/v1.17.0) which I believe fixes this problem. Therefore, I'm going to close this issue. But if you feel there's still a problem, feel free to reopen it.
