### ISSUE TITLE
Particle system reuse

### ISSUE THREAD

**Issue by lvenerosy** [playcanvas/engine#1173]
In my test project I offset a particle system in the editor and then set its position to ```(0, 0, 0)``` when I play it back. The first couple of times it is played back through user input, it looks like the effect is moving to random places and it is as if the system is duplicated. Then after a few times, the explosion becomes whiter and whiter, as if there are multiple particle systems being added on top of eachother.

Are there missing steps in this test https://playcanvas.com/editor/scene/601723 in order to be able to reuse a particle system ? When left clicking, the explosion is triggered.

**Comment by lvenerosy** [comment]
My bad about the "whitening", there are 3 particles but I see them at different locations so the difference in intensity was throwing me off. Then my actual problem is still about all the particles not moving together:

![screen shot 2018-04-13 at 11 31 12 am](https://user-images.githubusercontent.com/16996389/38713827-3ec6943e-3f0e-11e8-900c-e3d30ccfd673.png)

**Comment by willeastcott** [comment]
Today, we deployed [Engine v1.17.0](https://github.com/playcanvas/engine/releases/tag/v1.17.0) which I believe fixes this problem. Therefore, I'm going to close this issue. But if you feel there's still a problem, feel free to reopen it.
