### ISSUE TITLE
Problem with ParticleSystem

### ISSUE THREAD

**Issue by hroken** [playcanvas/engine#1176]
This is the discription of the issues:
https://forum.playcanvas.com/t/question-about-particlesystem/6626/10

**Comment by willeastcott** [comment]
I think this _might_ be fixed after the release of [Engine v1.17.0](https://github.com/playcanvas/engine/releases/tag/v1.17.0). Since there is no repro scene to test, I'm not 100% sure though. Please reopen this issue if there's still a problem.
