### ISSUE TITLE
Negative scale without flipping normals

### ISSUE THREAD

**Issue by otrubakarel** [playcanvas/engine#1177]
Make it possible to be able to set negative scale to a mesh (e.g. to mirror a mesh) without flipping it's normals and making it look "inside-out". This problem happens when:

1. Manually setting negative scale in the Playcanvas editor
2. Setting negative scale in modeling program, where the normals look as they should, but after importing to Playcanvas, they flip

For example, when mirroring an object in 3D modeling software, when we use "mirror tool", it just scales the geometry by -1 in set axis. It would be best to keep this consistent across multiple tools. This problem was already addressed (and fixed) in Three.js [here](https://github.com/mrdoob/three.js/issues/4904) and [here](https://github.com/mrdoob/three.js/pull/12787)

Image: default and mirrored (scaled by -1 in X axis) geometry after importing to Playcanvas
![f0cbcd6073ecd740007b9019f3413d25edd68e48](https://user-images.githubusercontent.com/24633729/38984375-ca684c32-43c6-11e8-9d63-5bef241d4ad0.JPG)

**Comment by willeastcott** [comment]
Is it not sufficient to disable backface culling on the material:

![image](https://user-images.githubusercontent.com/697563/39227943-42a40cc0-4810-11e8-80ce-a33a3f9aee3c.png)

Torus knot on the right is negatively scaled in one axis.

**Comment by otrubakarel** [comment]
Disabling backface culling is a way to make this work, but when using really complex model (e.g. car) where multiple mirroring is used with multiple materials, the performance hit is quite noticeable.

**Comment by scarletsky** [comment]
It seems THREE.js solve this by setting `gl.frontFace`.

**Comment by willeastcott** [comment]
Fixed in 95e26070e9242fbc886b52e0f9c175cd8a6f2096
