### ISSUE TITLE
shawdowmaps bug?

### ISSUE THREAD

**Issue by kyousuke916** [playcanvas/engine#1183]
Dear PlayCanvas,

I want to give a bug report.

Launch:  https://launch.playcanvas.com/475211?debug=true&profile=true
Project:  https://playcanvas.com/project/437633/overview/changing-scenes

Situation:
The size of shadowmaps increases with every scene change, leading to slow down on mobile devices after a few scene changes.
It seems like shawdowmaps is not properly flushed, is this a bug? 
If so, please fix as soon as possible.

thanks! 

![shadowmap bug](https://user-images.githubusercontent.com/7872445/39283577-78ab7628-4941-11e8-8aef-7d4a28921691.png)

**Comment by malDuffin** [comment]
I'm seeing the issue on my project as well ( nice catch! )
With t

**Comment by willeastcott** [comment]
Uh, hold your horses! 🐴 The PR isn't merged yet. 😉

**Comment by malDuffin** [comment]
Is there a use_local_engine= that will use the source from the latest master branch?

**Comment by willeastcott** [comment]
Yes, that's the link you have above. It should work now because the PR has now been merged. But in fact, it's also been deployed to production, so you don't even need to use the dev engine.
