### ISSUE TITLE
lightmap and realtime light trans problem

### ISSUE THREAD

**Issue by June4user** [playcanvas/engine#1191]
* sample:
https://playcanvas.com/editor/scene/607912
https://launch.playcanvas.com/607912?debug=true

### Steps to Reproduce
1. We have some problems when we try to run these steps.
Scene 1 (lightmaping): It is normal. 
Scene 2 (realtime light): The lightmap disapper if we switch scene2 to scene1.

2. If we try to recall lightmap function at scene 2
![2018-05-03_154303](https://user-images.githubusercontent.com/38936549/39564989-db67c4fe-4ee8-11e8-85d0-d7a195f321b7.jpg)
it will occur errors as below:
![error](https://user-images.githubusercontent.com/38936549/39565017-ec3bbd1c-4ee8-11e8-92b1-bbb8061d701a.png)

**Comment by willeastcott** [comment]
Replace:

```
Main.prototype.bake = function()
{
    var myApp = this.app;
    this.device = myApp.graphicsDevice;
    this.root = myApp.root;
    this.gameScene = myApp.scene;
    this.renderer = new pc.ForwardRenderer(this.device);
    this.assets = myApp.assets;
    
    this.lightmapper = new pc.Lightmapper(this.device, this.root, this.gameScene, this.renderer, this.assets);  
    this.lightmapper.bake(null, pc.BAKE_COLOR);
    
    console.log("bake!!");
};
```
With:

```
Main.prototype.bake = function () {
    this.app.lightmapper.bake(null, pc.BAKE_COLOR);
    console.log("bake!!");
};
```

**Comment by willeastcott** [comment]
Closing due to age, and also because the original issue was creating a new `Lightmapper` instead of using the one owned by the `Application`. Please reopen if you feel an issue still exists here.
