### ISSUE TITLE
Where to find source code of "After the Flood"

### ISSUE THREAD

**Issue by yiakwy** [playcanvas/engine#1192]
The visual effects of "After the Flood" by Mozilla is stunning. I am not expertized in shaders but I want get the same or event better performance than that. My strength lies in mathematics computing, and some other domain knowledges in CG relevant application. Because this game is just for demo purpose, I am eagerly to use it as a starting point to render a 3d city or testing cases in cloud server generated by CG programmes. 

I hope someone can give me some advices on it. I am familiar with Three.js,  OpenGL 3.0+ and WebGL ES 2.0+.

I want to contact the authors of the game to see whether we could have any opportunies cooperate on it.

**Comment by daredevildave** [comment]
The Project page is here: https://playcanvas.com/project/529572/overview/after-the-flood
