### ISSUE TITLE
particle system problem

### ISSUE THREAD

**Issue by June4user** [playcanvas/engine#1193]
sample:
https://launch.playcanvas.com/608364?debug=true
https://playcanvas.com/editor/scene/608364

### Steps to Reproduce

1. Touch on the mobile phone screen.
2. There have some mobile phone models are not shown in the right position. such as:

model: iPhone6s
ios version:10.3.3

model: iPhone8
ios version:11.2.6

model: samsung S7 edge
android version: 7.0

model: samsung Galaxy note8
android version: 8.0

----------
mobile phone models work normally:

model: HTC One max 
ios version:5.0.2

model: iPhone5s
ios version:11.2.6

model: iPad
ios version:10.3.3

**Comment by willeastcott** [comment]
I believe that Engine [v1.17.0](https://github.com/playcanvas/engine/releases/tag/v1.17.0) has fixed your problem so I am closing this now. If you find that a problem remains, please reopen the issue.
