### ISSUE TITLE
Editor as an independent plugin

### ISSUE THREAD

**Issue by yiakwy** [playcanvas/engine#1194]
After detailed research, comparing playcanvas with three-editor and other open source projects, I think playcanvas' editor is one of the most exciting tools used for interaction for designers.

The project I am working on needs to integrate an editor for inner  purpose usage. I want to use three or playcanvas as a backend rendering engine (The alpha 1.0.2 is based on three.js) to talk with gpu through webgl2 and bulid the editor on top of "react" to develop the frontend. All codes written in webpack, es6.

Playcanvas' editor is really cool and rich in a lot of features. I want to use it as an independant plugin.

Any suggestions?

**Comment by willeastcott** [comment]
Sorry, I'm not sure what you're asking. What's the question?

**Comment by yiakwy** [comment]
@willeastcott Hi I modified my questions. 

Here is what I plan:

```js
// import the editor, all developed in es6, webpack3 
const editor = new Editor("#editor") // playcanvas or some version I can customize 

// Editor is a react component to compute dom representation.
editor.bind(evt, target, cb) 
...
// or do anything playcanvas editor requires us to do
// editor registers elements, set titles, set colors ...

export editor
```

**Comment by willeastcott** [comment]
The PlayCanvas Editor on playcanvas.com does not 'work like a plugin'. There's currently no official way to customize the Editor either. Although you might find this page interesting:

https://forum.playcanvas.com/t/scripting-the-playcanvas-editor/2315

**Comment by yiakwy** [comment]
copy it
