### ISSUE TITLE
Timing issue when using Directional Light with Update Mode set to Once

### ISSUE THREAD

**Issue by Tatsujinichi** [playcanvas/engine#1207]
### Description

The order and timing seem to matter when using a Update mode Once Directional light.
Please find example project here https://playcanvas.com/editor/scene/611806

### Steps to Reproduce

1. open project https://playcanvas.com/editor/scene/611806
2. launch the scene
3. refresh over and over and over

You will notice there are different results depending on the timing. Sometimes the shadow is drawn, sometimes it is not.

**Comment by mvaligursky** [comment]
The repro project no longer works. There were many large changes in the shadow rendering, and this is likely no longer relevant. Please reopen if you can still reproduce the issue.
