### ISSUE TITLE
Alpha to coverage performance problem

### ISSUE THREAD

**Issue by June4user** [playcanvas/engine#1213]
Sample
https://playcanvas.com/editor/scene/611821

Steps to Reproduce

1. We want to overlap different texture to make an effect.
2. Click "Alpha to Coverage"
3. The performance become more rough than the original one on PC and Android.
![2018-05-18_115011](https://user-images.githubusercontent.com/38936549/40217868-75dd40a4-5aa1-11e8-86b8-13196969bfd7.jpg)
4. The performance is more terrible on iPhone. *We try on iPhone 5, 6 and 8.
![unnamed](https://user-images.githubusercontent.com/38936549/40220301-4d3a471e-5aab-11e8-8da5-cb2dcf5a4d45.png)

**Comment by willeastcott** [comment]
Alpha to coverage is a WebGL 2.0 feature. So it's not supported on iOS at the moment (mobile Safari only supports WebGL 1.0). Alpha to coverage works well for things like foliage. But not for things like large areas of graduated alpha. For the example you show, I would just make the ring use alpha test (or even model it with triangles) so it doesn't interfere with the alpha of the spot plane. Alternatively, you could break the spot plane into two planes (above and below the ring. Then, it should sort better. But to be honest, I would just edit the solid ring to not use blending.

**Comment by willeastcott** [comment]
Closing as this has been answered and it doesn't seem to be a bug.
