### ISSUE TITLE
Texture compression: xhr missing header

### ISSUE THREAD

**Issue by lvenerosy** [playcanvas/engine#1221]
When enabling the compression for the textures, I get the warning from https://github.com/playcanvas/engine/blob/d19c883530f6358f90b18dc2cbbbd4d020276ec2/src/net/http.js#L393 with content-type null. After a bit of investigation it seems that xhr doesn't know the dds file type and thus cannot create the content-type header that is needed.
<img width="936" alt="content-type" src="https://user-images.githubusercontent.com/16996389/40716139-eb09a430-6442-11e8-9f95-b13ab7ab9988.PNG">

**Comment by willeastcott** [comment]
You need to configure your web server to set the mime type of DDS file. For Apache, you can add the line:

```
    AddType image/dds .dds
```

...to httpd.conf

**Comment by willeastcott** [comment]
Closing because this seems to be a web server configuration issue rather than anything relating to the PlayCanvas sourcebase. Please reopen if I've misunderstood.
