### ISSUE TITLE
Basic material ..no customChunks?

### ISSUE THREAD

**Issue by Glidias** [playcanvas/engine#1230]
The customChunk code in standard material is missing in basic material. Does it mean basic materials don't support customChunks?

**Comment by willeastcott** [comment]
Yes, only the pc.StandardMaterial supports custom shader chunks (unless @guycalledfrank would care to disagree). 😄

**Comment by guycalledfrank** [comment]
BasicMaterial is basic. It's left as legacy to support cases where it was used. You can always downgrade Standard material to a basic feature set, e.g:
`mat.useFog = mat.useLighting = mat.useGammaTonemap = mat.useSkybox = false;`
and still use chunks :)

**Comment by Glidias** [comment]
I see. That makes sense now.  No wonder there's no such option in the editor and probably an old holdover from the past.
