### ISSUE TITLE
Shadow distance should be a light component property, not a scene property

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#124]
We need to migrate the shadowDistance property from the pc.scene.Scene API to the LightComponent API. This means we can select different shadow distances for different lights. It also makes more sense to find it there.
Also note that this is a property that should be filtered and only visible for the directional light type.

**Comment by daredevildave** [comment]
Released in v0.163.0 becde67cf2c30e1794a6e43d3359473dfd4940fc
