### ISSUE TITLE
The engine calls navigator.getGamepads every frame

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1250]
### Description

The engine currently calls navigator.getGamepads every frame, even when the game has no interest in any connected gamepads. This function is not free and does consistently show up as taking a small percentage of overall application CPU when profiling via Chrome Dev Tools.

Instead, the engine should check for and utilize the gamepadconnected and gamepaddisconnected events to look for the first connected pad. If the events aren't there, we should scan for newly connected pads at a far lower frequency (maybe every 500ms).

Once we have a connected pad, we can start polling via navigator.getGamepads every frame.

For an example showing how it should be done see: http://luser.github.io/gamepadtest/

**Comment by willeastcott** [comment]
Sounds reasonable to me. And ```enableTouch``` too?

**Comment by vkalpias** [comment]
Fixed by adding input project settings.
