### ISSUE TITLE
Element component system allocates many objects whether they're used or not

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1259]
### Description

The element component system allocates 14 materials and 1 texture, whether they're actually used or not. The system is by far the most expensive to create on app startup, despite not even being used by many apps. The materials should be created on demand by the system instead.

Whatever approach is taken to fix this issue should also be applied to the sprite component which is structured similarly although only creates 3 materials.

**Comment by willeastcott** [comment]
You fixed this, right @daredevildave?

**Comment by daredevildave** [comment]
Yes, fixed in #1342 and #1298
