### ISSUE TITLE
Texture atlas replace bug

### ISSUE THREAD

**Issue by Kangsi** [playcanvas/engine#1275]
### Description
Nothing happens if you try to replace a texture atlas with a new one. Replacing a texture atlas is useful if you apply compression techniques on the texture.

Example project: https://playcanvas.com/project/568231/overview/texture-atlas-replace-bug

### Steps to Reproduce

1.  Right on the texture atlas, which is currently being used in the project.
2.  Click on Replace and select the new texture atlas. 

Expected result: the old texture atlas is replaced with the new texture atlas
Observed result: no change at all

**Comment by daredevildave** [comment]
I believe this is now fixed in the Editor
