### ISSUE TITLE
Entities destruction memory leak

### ISSUE THREAD

**Issue by Nokitoo** [playcanvas/engine#1299]
### Description

When destroying entities, RAM as well as VRAM don't seem to be freed.

I first had RAM/VRAM [issues](https://forum.playcanvas.com/t/recreating-the-application-without-memory-leaks/7731/2) when I was trying to recreate `pc.Application` every time I start the game (without page reload).

To track down this issue, I wrote a test in this [repository](https://github.com/Nokitoo/Playcanvas-test) where I only recreate `pc.Entity` instead of `pc.Application`. However, I still have memory leaks.

I tested on IphoneX (iOS 11.4.1) with Safari.
I used Xcode Activity Monitor instrument to monitor the memory usage. Here is a screenshot:
<img width="1276" alt="screenshot at aug 14 17-18-47" src="https://user-images.githubusercontent.com/6523854/44080200-5385a7d2-9fe6-11e8-82a7-2908fbce03b9.png">
And another one, some seconds after:
<img width="1278" alt="screenshot at aug 14 17-19-40" src="https://user-images.githubusercontent.com/6523854/44080205-57b6036a-9fe6-11e8-83bc-b30148195158.png">
The memory usage of `com.apple.WebKit.WebContent` goes from `355MB` to `779MB`. After `1.10GB`, Safari reloads the page (ie. crashes).

Here is a screenshot of http://webglreport.com/:
![img_0086](https://user-images.githubusercontent.com/6523854/44081037-bab5223c-9fe8-11e8-805e-f409b0eba566.PNG)

### Concerns

I didn't find any documentation on how to correctly free a scene or an application so my way to delete the entities may be wrong.

I read a post on Playcanvas forum with an issue closed to mine [here](https://forum.playcanvas.com/t/how-to-free-the-vram-of-destroyed-entities/1781). However, it doesn't seem to free correctly the entities.

### Steps to Reproduce

1. Create 5000 entities with `box` model
2. Destroy them
3. Create 5000 entities with `box` model
4. Destroy them
5. So on so forth...

As I wrote previously, I created a [repository](https://github.com/Nokitoo/Playcanvas-test) to demonstrate this issue.

**Comment by willeastcott** [comment]
This is because a non-asset type model component (i.e. a primitive shape) creates a pc.Model, but on removing the component (on calling entity.destroy()), the model is never destroyed as it is with the asset type. Since the model component has a default material which points to the mesh instance of the box primitive, the boxes never get garbage collected. Instead, the material's mesh instance array just continues to grow. @daredevildave could probably fix this really quickly.

**Comment by Nokitoo** [comment]
Thank you, it would be nice if it could be fixed.

Despite I think it won't fix the leak in our game because we don't use non-asset model components.
Is there a way application assets could leak? I made a simple test where I repeat multiple steps:
1. Create `pc.Application` with `assetPrefix` to our game assets path, and the `canvas` (created only one time)
2. Call `app.configure`
3. Call `app.preload`
3. Call `app.destroy`
4. Repeat
Doing this I have leaks, am I missing something to correctly delete the application? (I don't create any entity)

**Comment by kizzd** [comment]
Can you give any workaround for this problem?
