### ISSUE TITLE
Support 72hz rendering on Oculus GO

### ISSUE THREAD

**Issue by drewwebster** [playcanvas/engine#1326]
Please add support for optional 72hz rendering for Oculus GO at engine level. Or provide instructions on how to inject this with included script in application.

The necessary changes can be found here:

https://gist.github.com/DigiTec/5b022428946a85b936017412dc5b0dbd

vr-display.js this.display.requestPresent should add optional attribute highRefreshRate: true (see gist above)

https://github.com/playcanvas/engine/blob/fab9d05a711d0a075e719dd603e57278c212dfaa/src/vr/vr-display.js#L230

Documentation on this feature on Oculus site can be found here

https://developer.oculus.com/documentation/vrweb/latest/concepts/optimizing-rendering/

**Comment by willeastcott** [comment]
Hey @Maksims - now that we have deprecated WebVR and switched to WebXR, is this still an issue?

**Comment by Maksims** [comment]
No, it should not be an issue, except for small things: particles, animation, and similar components, that have either fixed step simulation of interpolations that assume 60Hz is a top.

WebXR provides own rendering frame buffer and own requestAnimationFrame function, frequency of which depends on platform capabilities.

**Comment by willeastcott** [comment]
OK, I think we already have an issue about the particle system assuming 60Hz. So I'll close this now. Thanks!!
