### ISSUE TITLE
[Question] - Firefox OS compatibilty

### ISSUE THREAD

**Issue by ssavinel** [playcanvas/engine#138]
Hello,
As shown in the title, is PlayCanvas compatible with firefoxOS ?
And so principally considering the hardware limitations of many devices (about 1GHz CPU and 512 Mo RAM).

**Comment by daredevildave** [comment]
Hi,

Yes, PlayCanvas is compatible with FirefoxOS.

In general when targeting low-end platforms you should avoid CPU/GPU expensive features like: real-time shadows, dynamic lighting, physics.

**Comment by ssavinel** [comment]
Great, thank you !
