### ISSUE TITLE
Particles fail on CPU

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#139]
Since the update removing camera nodes it looks like CPU particles don't work.

In particular, [this line](https://github.com/playcanvas/engine/blob/master/src/scene/scene_particleemitter.js#L921) doesn't work. I think view mat is available on the camera object directly now.

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/commit/34e6bfb80238c85f72fc480ca11db50c1b259022
