### ISSUE TITLE
AnimationComponent accepts asset objects instead of ids

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#1390]

**Comment by willeastcott** [comment]
The code will convert an array of pc.Asset objects to an array of asset ids in the set function:

https://github.com/playcanvas/engine/blob/master/src/framework/components/animation/component.js#L232

That's also, say, what the model component code does. I don't see the  problem, beyond the JSDoc suggesting that only pc.Asset[] can be setting on the `assets` property. Can this be closed?

**Comment by willeastcott** [comment]
As mentioned in my previous comment, the `AnimationComponent#assets` property accepts both `Asset[]` and `number[]`. This is documented properly too now. So as far as I can see, there is no bug here and I'm therefore closing, Please follow up if you disagree.
