### ISSUE TITLE
Translucent problem

### ISSUE THREAD

**Issue by gameatp** [playcanvas/engine#1398]
### Description
When the first revision of the blend type is Alpha, the object does not disappear but shows the black.
### Steps to Reproduce

1. Modify blendType to alpha
2.Set intensity to 0
3.Objects are black but not disappear
![image](https://user-images.githubusercontent.com/4427058/46724206-1dba7400-ccac-11e8-929e-8aba2368c1f5.png)

**Comment by yaustar** [comment]
Looks like an editor only problem when you put an alpha'ed object against a skybox. When you launch the app, it looks fine.

**Comment by gameatp** [comment]
> Looks like an editor only problem when you put an alpha'ed object against a skybox. When you launch the app, it looks fine.

Yes, the refresh is correct again. I think the rendering queue has not been refreshed since the blendType has been changed. The sky box should be drawn in front of the translucent object

**Comment by willeastcott** [comment]
I think the problem here is that, when you change a material from opaque to transparent (or vice versa), the engine doesn't move the mesh instances that use that material from the opaque sub-layer to the transparent sub-layer (or vice versa). So yes, this is highly likely to be a bug in the engine.

**Comment by gameatp** [comment]
> I think the problem here is that, when you change a material from opaque to transparent (or vice versa), the engine doesn't move the mesh instances that use that material from the opaque sub-layer to the transparent sub-layer (or vice versa). So yes, this is highly likely to be a bug in the engine.

Yes, it should be an engine bug.

**Comment by Maksims** [comment]
Just checked it on blank project, and it seems to be all fine. Been fixed since?
Someone please verify as well, so this Issue can be closed.

**Comment by gameatp** [comment]
> 只是在空白项目上检查了一下，看来一切都很好。自被修复以来？
> 也请有人验证，以便可以解决此问题。

I guess I've changed the question

https://github.com/playcanvas/engine/pull/1726

**Comment by Maksims** [comment]
So this been fixed, and this issue can be closed?
