### ISSUE TITLE
Changing light type broken, `pc.Scene#removeLight: light is not in the scene`

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#145]
Reproduce:
1. Create new project.
2. Create new pack.
3. Put some geometry around.
4. Select existing light in scene `Directional Light`.
5. Change its `type`.

**Expected:** type to change, and be reflected in renderer.
**Issue:** type is not changing and console log `pc.Scene#removeLight: light is not in the scene`

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/commit/d6c72a12d13104fffe872143138afee887f2ecac
