### ISSUE TITLE
AssetRegistry can't load cross-origin data

### ISSUE THREAD

**Issue by Disorrder** [playcanvas/engine#1451]
I'm loading some images from another domain, but getting error:
![image](https://user-images.githubusercontent.com/2883539/49089618-012ec700-f26d-11e8-8928-6477c39a5147.png)

Can't work locally with images uploaded on production server. How can I fix it fast?

**Comment by kungfooman** [comment]
You need to enable CORS on your production server

This has lots of example configurations for different web servers: https://enable-cors.org/server.html

**Comment by kungfooman** [comment]
What I would suggest is to use an "assets" repo, which you have locally and on your production server. Then you could simply load all data from each corresponding server via e.g. `url = "../assets/"` and the files load faster, because it's not remote anymore for local testing
