### ISSUE TITLE
Material asset can not load again after unloading

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#1458]
### Description

When unloading an texture asset which is used by material asset, the texture is still referenced in material asset's data. So when you try to reload the material asset, the data is invalid in `StandardMaterialValidator`. The result is you can not load the material asset again.

### Steps to Reproduce

1. Create a Model Viewer Starter Kit project.
2. Launch the project.
3. 
```javascript
var a1 = pc.app.assets.find('plastic-orange')
var a2 = pc.app.assets.find('plastic_ao.jpg')
a1.unload()
a2.unload()
pc.app.assets.load(a1)
```

Here is a screenshot:

![image](https://user-images.githubusercontent.com/2386165/49876678-ce84f100-fe5e-11e8-9882-142ce4560829.png)

**Comment by Maksims** [comment]
Investigated it: data is valid inside, and material does reload as supposed to. But, it is not reapplied on meshInstance that it used to be on. So you have to do it manually.
And loading material, will not load it depending texture that has been unloaded. Reloading texture manually, will automatically reapply on material.

Validation warning, is unrelated to loading behaviour here.

```javascript
var assets = pc.app.assets;

var a1 = assets.find('plastic-orange');
var a2 = assets.find('plastic_ao.jpg');

a1.unload();
a2.unload();

assets.load(a1);
assets.load(a2);

pc.app.root.findByName('Model').model.meshInstances[1].material = a1.resource;
```

**This Issue can be closed.**
