### ISSUE TITLE
Particles expand to a regular box shape

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#146]
If you set up a particle system component to expand from a point with random velocity (say -1 to 1 for X, Y and Z), ideally, you would want to see a spherical shape grow from the point. Instead, you see a regular box shape grow from the point with particles appearing at regular intervals along each major axis of the box. See below:

![particleexpansion](https://cloud.githubusercontent.com/assets/697563/5744454/da896910-9c18-11e4-90ef-b47c2a9e9345.png)

**Comment by Maksims** [comment]
It is different spawn bounds shapes feature we lack.
We probably should allow to specify spawning shape to be one of: box, sphere, cylinder, cone.
And parameters based on that spawn shape (radius, height, width, etc).

**Comment by guycalledfrank** [comment]
I'm unsuccessfully trying to get rid of this. The "regular grid" look is more like a precision limitation and can be fixed, but the "box shape" is not that easy to get rid of. The reason of this is that we select random velocity separately for X, Y, Z axis. So for each axis we have equal probability of all values between 2 curves. Shortly speaking, sphere shape requires normalized direction, while our XYZ have independent non-normalized motion. But simply normalizing the velocity kills it's length... I'm not sure what to do here.
I can add sphere spawn shape and add a checkbox that will assign starting velocity to particles based on shape. So particles will start moving spherically, but again, you won't be able to emulate the same kind of motion through just velocity graphs.
Thinking of something more flexible...

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/commit/6e662ca4d32543020f45f3ce8c63ed928f26d560
