### ISSUE TITLE
layer.renderTarget null or undefined - not same.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#1471]
Currently if `layer.renderTarget` is set to specific target, it will render to it - all Ok.
By default it is set to `undefined` - fine.
But if you set it to `null` - then it will not render. Although `null` - should be treated as `undefined`.

As doing this:
```
layer.renderTarget = rt;
// later on
layer.renderTarget = null;
```
Simply will lead to that layer not rendered, and developer confused why it is behaving like that.  
Is there a specific reasons for such behaviour or it is a small conditional bug where it is being overly too specific?

**Comment by willeastcott** [comment]
How about changing:

````
if (renderedRt[k] === rt && renderedByCam[k] === camera) {
````

To: 

````
if (renderedRt[k] == rt && renderedByCam[k] === camera) {
````

**Comment by mvaligursky** [comment]
This has been completely change in https://github.com/playcanvas/engine/pull/2882
