### ISSUE TITLE
Not possible to override fog related shader chunks

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1475]
See the ```fogCode``` function:

https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/program-lib.js#L26

It ignores any custom chunks that may have been passed in in the shader options object.

**Comment by JohannesDeml** [comment]
Pull request https://github.com/playcanvas/engine/pull/1233 already handles the problem in this commit: https://github.com/playcanvas/engine/pull/1233/commits/5342987e56ce6f768a0332bb57fc4fa3af86e5b5

I can do a simpler pull request only containing the changes for the fog chunk handling, or does it make sense to wait for PR 1233 to be merged?

**Comment by willeastcott** [comment]
So the fog fix in that PR is really nothing to do with skin batching. It should have been a separate PR. Also, it looks like gamme correction and tonemapping chunks will suffer the same problem and that PR doesn't address those problems either. So I think we'll need a new and complete PR.

**Comment by Glidias** [comment]
cleaned it up to seperate branch. 
https://github.com/playcanvas/engine/pull/1617
