### ISSUE TITLE
onTriggerExit and onTriggerUpdate are missing

### ISSUE THREAD

**Issue by smkplus** [playcanvas/engine#1499]
I need onTriggerExit and onTriggerStay like Unity
but I couldn't find it in playcanvas
please help me!

**Comment by yaustar** [comment]
It doesn't work in the same way as Unity. In PlayCanvas, you have to explicitly have to listen the event. A tutorial can be found here https://developer.playcanvas.com/en/tutorials/collision-and-triggers/

**Comment by smkplus** [comment]
> It doesn't work in the same way as Unity. In PlayCanvas, you have to explicitly have to listen the event. A tutorial can be found here https://developer.playcanvas.com/en/tutorials/collision-and-triggers/

can you take an example that how it works?

```
var Collider = pc.createScript('collider');

// initialize code called once per entity
Collider.prototype.initialize = function () {
    this.entity.collision.on('collisionexit', this.onCollisionExit, this);
};

Collider.prototype.onCollisionExit = function (result) {
    if (result.other.rigidbody) {
        this.entity.sound.play("hit");
    }
};

```

**Comment by yaustar** [comment]
There are examples in the page that I linked. 

Source project/editor here so you can see how the components should be set up on the entiitis: https://playcanvas.com/editor/scene/440154

Source files here: https://playcanvas.com/editor/code/405871?tabs=4468766,4468765

**Comment by willeastcott** [comment]
Since this already seems possible, I'm closing this. Please reopen if I'm mistaken.
