### ISSUE TITLE
How to Debug Raycast?

### ISSUE THREAD

**Issue by smkplus** [playcanvas/engine#1501]
I couldn't find debugging ray in playcanvas!
It's very hard to guess ray so I need to drawline to debugging it

In unity I Debug Ray by using 
`Debug.DrawLine(transform.position,hit.point,Color.green);`

![debug](https://user-images.githubusercontent.com/16706911/53332713-449adf00-3909-11e9-836b-d4c8530b3b1a.PNG)

that's right I can use renderLine but It's better that playcanvas make it as builtin function
```
    var start = new pc.Vec3(0, 0, 0);
    var end = new pc.Vec3(1, 0, 0);
    var color = new pc.Color(1, 0, 0);
    this.app.renderLine(start, end, color);
```

**Comment by yaustar** [comment]
> that's right I can use renderLine but It's better that playcanvas make it as builtin function

What do you mean by a built in function? `renderLine` is part of the engine so it's already builtin?
