### ISSUE TITLE
Releasing Mouse Problem

### ISSUE THREAD

**Issue by smkplus** [playcanvas/engine#1508]
when I use isPressed for Right click I have idiot bug!!!
it works when I press Right click but when I press Right click and move my mouse It never stop
My browser is Opera
```
var Test = pc.createScript('test');

// initialize code called once per entity
Test.prototype.initialize = function() {
    this.app.mouse.disableContextMenu();
};

// update code called every frame
Test.prototype.update = function(dt) {

    if(this.app.mouse.isPressed(pc.MOUSEBUTTON_LEFT)){
        console.log('Worked');//this work and I haven't any problem here
    }
        if(this.app.mouse.isPressed(pc.MOUSEBUTTON_RIGHT)){
        console.log('WhyPrinting?');//when I move mouse after right click it always printing!!!!
    }
};
```

**Comment by yaustar** [comment]
I assume you are moving the mouse out of the window and releasing the button? (not 100% sure if it's the same as moving the mouse out of the context/canvas too)

You have to listen for the mouseout event on the window unfortunately as the browser doesn't send/detect the mouse release if it's outside the window.

**Comment by smkplus** [comment]
no I don't move my mouse out of window
I haven't this problem in chrome and firefox
It just happened in Opera

**Comment by yaustar** [comment]
Odd. Opera uses Chromium under the hood. Just tried this myself and it seems fine?

![feb-27-2019 14-42-14](https://user-images.githubusercontent.com/16639049/53498366-1dc1e180-3a9e-11e9-884f-231ba9d4151e.gif)

**Comment by smkplus** [comment]
but I tested this in many system and dosen't work
as you can see when I hold right click and move I have this bug!
![record_2019_02_27_21_45_10_743](https://user-images.githubusercontent.com/16706911/53512897-27b50600-3ad9-11e9-852c-c11e556c256b.gif)

**Comment by yaustar** [comment]
Can you post a link to the project that has this issue and the version of opera that you are using please?

**Comment by smkplus** [comment]
I don't like to bother you
any way my opera version is 58.0.3135.79

and link is here that is console to test:
[Test](https://playcanv.as/b/Qe5Zotbq/)

**Comment by yaustar** [comment]
Can you post the project overview page rather than the build please? This is so we can see how the project is setup and also access the source without it being minified.

**Comment by smkplus** [comment]
ok
https://playcanvas.com/project/604623/overview/test

**Comment by yaustar** [comment]
Using your project, I can't reproduce the issue on my Macbook Air, Opera 58.0.3135.79

Do you have any plugins install on Opera that might interfere with right click?

**Comment by smkplus** [comment]
no I tested in multiple computer and have this problem
let's take an example that what happened if right click will not release.

![record_2019_02_28_08_28_58_686](https://user-images.githubusercontent.com/16706911/53542275-f23d0680-3b32-11e9-98f0-8076efca8a42.gif)

I defined right click to determine the power of cue but when I shoot the ball I right click not released and next time that player want to shoot the ball by dragging mouse ball will shoot
you can test this issue in my game
https://playcanv.as/b/VYPBJFxe/

**Comment by yaustar** [comment]
> Hoding Right click -> determine power
> Determine power -> Shoot
> Determine power-> Shoot
> Determine power -> Shoot
> 
> as right click not released Holding Right click is not work!
> 
> you can test this issue in my game
> https://playcanv.as/b/VYPBJFxe/

Sorry, I can't reproduce this bug in Opera on my Mac. It all works as expected.

**Comment by yaustar** [comment]
I've reproduced the error in Opera. 

Can you go to preferences in Opera and see if you have Gestures enabled? 

If so, this overrides the right mouse and drag to detect mouse gestures for the browser.
![image](https://user-images.githubusercontent.com/16639049/53556744-6334ec00-3b3c-11e9-8eee-c43fc564b33f.png)

Disable mouse gestures and it should work as expected.

**Comment by smkplus** [comment]
oh thank you!!
it works!!!
is there a code to disable mouse gesture

**Comment by yaustar** [comment]
The mouse gesture is part of the browser, as far as I know you can't disable it via a script on the site.

I recommend using the space bar as an alternate control for cue strokes or something similar as well as right mouse button (and also detect the browser to warn players). 

This will also help laptop users on trackpads.

You could also disable cue stroke control after the shot is made or if any other button is pressed. That might be enough to get around this issue.
