### ISSUE TITLE
Exception on switch emitter type from box to sphere

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#151]
To reproduce:
- New pack
- Run game
- Create new particle system
- Change Emitter Shape from Box (the default) to Sphere.

Exception is: 
Uncaught TypeError: Failed to execute 'uniformMatrix3fv' on 'WebGLRenderingContext': The 3rd argument provided is either null, or an invalid Array

**Comment by willeastcott** [comment]
To give a little more information, uniformMatrix3fv is being passed a Vec3 for the spawnBounds uniform, rather than a Float32Array. I'm guessing the shader program isn't updating when the emitter type is changed?

**Comment by guycalledfrank** [comment]
I see what's the problem, I'll fix it.
