### ISSUE TITLE
Fast moving rigid bodies pass through other bodies

### ISSUE THREAD

**Issue by smkplus** [playcanvas/engine#1510]
I have many problems with playcanvs physics it's bull shit!
balls crosses from other balls

![record_2019_03_05_11_18_37_795](https://user-images.githubusercontent.com/16706911/53790381-0c645380-3f3c-11e9-8d98-eac1bcec1007.gif)

https://playcanv.as/b/ZlZnaZ7Z/

I like to set physics like this
http://www.flyordie.com/snooker/

**Comment by yaustar** [comment]
Please stop getting frustrated at the problem and indirectly, at the people that are trying to help you. 

1. PlayCanvas is using Ammo physics which is compiled version of Bullet. A well matured and long running physics library used for games.

2. This is a common physics problem for a lot of libraries including the one included in Unity.

3. Have you enabled CCD on the physics like I mentioned in the forums? It's expensive but need for fast moving objects.

**Comment by yaustar** [comment]
As the conversation is going on in the thread here, this ticket can be closed. It isn't a bug with the engine really (beyond maybe exposing CCD options to the user)

https://forum.playcanvas.com/t/physics-not-work/9432/15
