### ISSUE TITLE
More control over syncHierarchy.

### ISSUE THREAD

**Issue by PpHammer** [playcanvas/engine#1517]
Hi all!

Having lots of entities and/or graphnodes can cause syncHierarchy to take up a lot of time.
This can be especially problematic when pushing lots of skinned characters with bones.

While syncing always needs to be done in most cases - in some it would benefit to have manual control over it.

For example skinned characters don't necessarily need to be synced not even when they are on screen (probably cause of their skeleton update?). Our tests with 300 skinned characters and some monkey patching showed an performance gain over 80% on syncHierachy.

Maybe adding an additional var to graphnode (e.g. _shouldSync) and testing this in syncHierarchy would allow for more control over this in specific situations and gain performance?

Thanks,
- Pieter

**Comment by lvenerosy** [comment]
Yes we have a similar issue with many entities. I found weird the way frames look with a lot of time allocated to `syncHierarchy` with not much logic actually happening.

![frame](https://user-images.githubusercontent.com/16996389/58232155-c4531100-7d73-11e9-8c9b-5e3c18077196.PNG)

Over 30 seconds there are 11.4 seconds of js.

![diagram](https://user-images.githubusercontent.com/16996389/58232210-f19fbf00-7d73-11e9-85b5-d3b6de4f3a6b.PNG)

And if I am interpreting the profiler correctly, ~2.7 seconds of these 11.4 seconds are taken up by `children.length` and `children[i]`.

![time](https://user-images.githubusercontent.com/16996389/58232413-6541cc00-7d74-11e9-9ee3-1adaaf298b92.PNG)

On a less performant device it looks like that:

![mobile diagram](https://user-images.githubusercontent.com/16996389/58232451-78549c00-7d74-11e9-9cbd-0a7dd8b95640.PNG)
![mobile time](https://user-images.githubusercontent.com/16996389/58232454-7be82300-7d74-11e9-9b11-15678e8faddd.PNG)


We have pools for most of the dynamic entities so we have many entities but we don't want most of them to be synced.

**Comment by willeastcott** [comment]
Hey, can you check out this PR:

https://github.com/playcanvas/engine/pull/1576

I think it will help a lot with this (if you stop running animations on offscreen skinned characters). Comments welcome!! 😄

**Comment by willeastcott** [comment]
Closing this due to [newly merged optimization for hierarchy synching](https://github.com/playcanvas/engine/pull/1587). 😄
