### ISSUE TITLE
Particles: System does not update when Emitter Radius is changed

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#152]
To repro:
- Create a sphere emitter
- Change the emitter radius

Result:
The particle system does not change

**Comment by Maksims** [comment]
Seems like being fixed some time ago, cannot reproduce using master branch. Please verify so.

**Comment by willeastcott** [comment]
You're not following the (very complicated) instructions to reproduce, @Maksims. I can demonstrate tomorrow if you like.

**Comment by willeastcott** [comment]
This seems fixed now. Closing...
