### ISSUE TITLE
onCollision and Sphere Cast doesn't work when speed is high!

### ISSUE THREAD

**Issue by smkplus** [playcanvas/engine#1521]
In my game I need to do something after ball hit to another ball for example playing sound

I tried using all three methods collisionstart  contactcollision and collisionend

https://developer.playcanvas.com/en/tutorials/collision-and-triggers/

````
if (result.other.tags.has('Ball')){        
        result.other.destroy();
}
````
but when speed is high and sometimes it doesn't work at all!!!!

also I tried using Raycast but didn't work

playcanvas wasted my time!!
playcanvas isn't good name for it assholecanvas is better name

![7bfbd069eb596e7fb516c07c6ebe1848aced6029](https://user-images.githubusercontent.com/16706911/54506735-28f88680-4953-11e9-9b75-899de8052de9.gif)

![99b4107d4128f115e49e4298f2df32c957d99c97](https://user-images.githubusercontent.com/16706911/54506736-28f88680-4953-11e9-88bd-41475f049c75.gif)

https://forum.playcanvas.com/t/collision-detection-problem/9548

**Comment by vkalpias** [comment]
It looks like your issue has been resolved in the forum. Please use the forum if you are not sure that there is an engine bug before opening a new engine issue here. Thanks!
