### ISSUE TITLE
Particle systems have issues when moved, also wrong order with map tiles 

### ISSUE THREAD

**Issue by malDuffin** [playcanvas/engine#1525]
Map tiles are being displayed in an incorrect order.  The rows are reversed.

See https://playcanv.as/p/d48QShHE/ 

And here for more info ( https://forum.playcanvas.com/t/particle-system-change/9582/4?u=mal_duffin )

Also, when moving the particle system, there are lots of glitches ( parts of the particle system are in the wrong place ).

See https://playcanv.as/p/d48QShHE/ 

And here for more info ( https://forum.playcanvas.com/t/particle-system-change/9582/5?u=mal_duffin )

**Comment by malDuffin** [comment]
Hi @e-strokov, I can confirm that your pull request fixes the order of the rendering ( I checked out the branch, and ran it using the local engine option ) - nice one!.  

It doesn't however fix the glitches when moving particle systems.  Click on the Add button when running the example project to see this second issue ( your pull request mentioned that it'll close this issue, when the second issue is still there )

**Comment by malDuffin** [comment]
Just a heads up that the moving bug hasn't been fixed, so the issue hasn't been resolved yet.

Here's a video showing the issue ( I tried with a number of branches, including the latest master and the new particle-emitter-space branch ).

https://drive.google.com/file/d/1YdLjVFPnL8rRcu1VpRSPsnnSFA5Jc7e_/view

In the video you're seeing two explosions on-screen at the one time ( one is like a ghost ).  

You should only be seeing one explosion.

**Comment by willeastcott** [comment]
What're your thoughts on this, @e-strokov?

**Comment by malDuffin** [comment]
I've noticed two issues here... 

Press Add a few times, and keep an eye on the added number system.  Rather than starting at 1 and ending at 64, it starts at 57 and ends at 56. ( 57... 64, 1.. 57 ).

Also, it's still not placing the particles in the right place.  The actual locations of the particle systems seems to be worse now than before! ( I've placed 4 red dots to indicate the position the particle systems will be randomly added to, when you press the ADD button ).

**Comment by e-strokov** [comment]
Hi @malDuffin, I submitted a fix to Particles System yesterday. It's appeared that the bug is platform specific. Could you take a look if any of problems you mentioned are resolved? Unfortunately, I can't reproduce them.
Thanks.

**Comment by malDuffin** [comment]
Hi @e-strokov,

I tried the example project, and the issue with moving still isn't fixed.

I've looked into the example, and have tried to narrow down the issue.

If you load the new project and run it, then press the button in the top corner, you should notice that there are two particle systems that get spawned ( a yellow one, and a white one ).

https://playcanvas.com/editor/scene/733096

These two particle systems are identical (cone was duplicated from the other ), other than one has a yellow tint, and is slightly scaled up.

The other difference is the lifetime.  Yellow has a lifetime of 5, and the white as a lifetime of 1.

When you press the button, you'll notice that the Yellow one appears correctly at one of the 4 red dots.

The white doesn't appear in the correct slot.  However, if you set the lifetime to 5 on white, it does appear at the right location most of the time!   

Somehow, the lifetime value is causing an issue ( there may be other issues ).

If white disappears, and doesn't re-appear after clicking for ages, just refresh the page and try again.  It seems to randomly appear and disappear sometimes.

Hopefully showing this quirk will help identify the moving issue.

Note that the particle index starting at the lower row ( in this case row 7: tile 57, instead of row 0: tile 0) is also visible here, but that's a separate issue.

**Comment by e-strokov** [comment]
Hi @malDuffin, 
So far I could only reproduce last issue (animation frame). But this might be platform specific (I'm testing on Mac). So, may I ask you to switch Sort mode to Camera Distance? Please let me know if this resolves other problems. Thank you.

**Comment by malDuffin** [comment]
Hi @e-strokov, with the Sort mode set to any of the three options other than None, the positioning of the particle system seems fixed.

On Mac, it might be worth you running Bootcamp to be able to debug the problems on Windows also.

**Comment by e-strokov** [comment]
Hi @malDuffin, there is yet another branch with particles changes
https://github.com/playcanvas/engine/tree/particle-refactor
could you take a look if any of your issues being resolved?
Thanks.
Evgeny

**Comment by malDuffin** [comment]
Nice one @e-strokov - that seems to have solved the issues!

**Comment by willeastcott** [comment]
Fantastic! 🎉
