### ISSUE TITLE
9 Slice Tiling seems to be broke

### ISSUE THREAD

**Issue by malDuffin** [playcanvas/engine#1526]
9 Slice tiling seems to be broke...

https://forum.playcanvas.com/t/display-sprite-animations-on-2d-screen/9456/4?u=mal_duffin

**Comment by daredevildave** [comment]
Please make tickets that describe the error. 

This looks like it is behaving as expected.

**Comment by malDuffin** [comment]
Apologies Dave, I'll try to describe the issue below.

Here's how PlayCanvas renders a 9-slice tiled image.
![image](https://user-images.githubusercontent.com/5173839/55020289-75e0fa80-4fee-11e9-8220-aefd93060567.png)

And here's how it should be rendered ( Unity )
![image](https://user-images.githubusercontent.com/5173839/55020332-8b562480-4fee-11e9-9ce2-bc26b74598e3.png)

If you need any more info on how it's broken, I can try to put together a better example.

**Comment by malDuffin** [comment]
I was able to make a bit of progress on this, I was able to feed specific values into the scaling to get correct results for specific cases.  However, as I didn't find a way to see what the values of the variables with the fragment shader were as the code was running ( do you guys have a way to view these? ), I wasn't able to figure out the correct formula to automatically generate the corrrect values - this will hopefully be fairly easy to figure out for the original author of the shader code.

You can see an animated gif, showing the original and modified version of the shader - only the tiling of the UVs of the "cross" section are affected.

![PlayCanvas_TileBugFixAnim](https://user-images.githubusercontent.com/5173839/55093767-f5cd9a00-50ac-11e9-9684-1fa5039a4204.gif)

I took this file...
https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/chunks/startNineSlicedTiled.frag

And added a vec2 scaleFactor ( as the U and V will need different values for different setups ).

The formula I included below isn't correct due to not having access to what the actual values are for eg z and w, but the scaling should be based on the width and height of each inner offset relative to the parent width and height of the rect of the sprite within the atlas.

Hope that makes sense!

```
    vec2 tileMask = step(vMask, vec2(0.99999));

// Calculate scale factor for U and V, based on the inner offset and rect within the atlas
// This needs tweaking, due to lack of info of the values of the variables below

    float scaleFactorU = (1.0 / (innerOffset.z * atlasRect.z));
    float scaleFactorV = (1.0 / (innerOffset.w * atlasRect.w));

    vec2 scaleFactor = vec2(scaleFactorU, scaleFactorV);
	
    vec2 clampedUv = mix(innerOffset.xy*0.5, vec2(1.0) - innerOffset.zw*0.5, fract(vTiledUv*scaleFactor));

    clampedUv = clampedUv * atlasRect.zw + atlasRect.xy;
    nineSlicedUv = vUv0 * tileMask + clampedUv * (vec2(1.0) - tileMask);

```

**Comment by yaustar** [comment]
Reopened as we reverted the PR that fixed this due to side effects on 9 sliced tiled sprites that are placed in the world.
