### ISSUE TITLE
Child element components are not dirtified when their parent is resized

### ISSUE THREAD

**Issue by vkalpias** [playcanvas/engine#1531]
It looks like resizing Element Components who have other Element component as children does not dirtify the children correctly so that they are also resized.

e.g. Create a 2D screen with a Text Element and an Image Element as a child of the Text Element. Make the Image Element have 0, 0, 1, 1 anchors and 0 margins so that it covers all of the Text Element's width and height. 

Then at runtime set for example the lineHeight of the Text Element to something bigger. You should notice that the Image element does not become bigger. 

It looks like this is because _dirtyLocal or _dirtyWorld are not changing in `pc.ElementComponent#_flagChildrenAsDirty`. I don't think this ever happened but because we made various optimizations in `syncHierarchy` they might have affected how this works...

**Comment by e-strokov** [comment]
Fixed in 'Resizing element dirtifys local, but only once. (#1534)'
