### ISSUE TITLE
Parented Camera ViewMatrix Problem

### ISSUE THREAD

**Issue by r2d2Proton** [playcanvas/engine#156]
I noticed that when I parented the camera in the editor it distorts the scene if the object being parented to is scaled.

**Comment by Maksims** [comment]
Will add here too: if camera has viewport `[ 0, 0, 0.5, 1.0 ]` it stretches too.

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/commit/f1c261a99ec341b495364bf33d4a251bd1d0f77c
