### ISSUE TITLE
Improved Camera Support

### ISSUE THREAD

**Issue by r2d2Proton** [playcanvas/engine#157]
It appears that PlayCanvas does not support off-center projection, nor fish-eye projections, etc. Also, the API for LookAt does not contain eyePos. I'd like to suggest allowing the ViewMatrix and ProjectMatrix to be set arbitrarily by developers.

**Comment by guycalledfrank** [comment]
BTW, you can't make fish-eye projection with just matrices, because it's not linear, it's usually simulated with pixel shader, or tessellated geometry and similar vertex shader.

**Comment by r2d2Proton** [comment]
Thank you for pointing that out. I was actually discussing in a general sense. My petition to the team is that the design should not inhibit developers, if possible.

**Comment by Maksims** [comment]
I totally agree that there should be no limitations, and developer should have possible access to as many properties as possible, not everything should be publicly exposed though.  
So potentially it is possible already, but by inspecting actual data and modifying not exposed values.

**Comment by willeastcott** [comment]
Just a point in response to: 

> Also, the API for LookAt does not contain eyePos.

You set eyePos by simply using the setPosition/setLocalPosition functions. e.g.:

    cameraEntity.setPosition(1, 1, 1);
    cameraEntity.lookAt(0, 0, 0);

**Comment by Maksims** [comment]
Closing this ticket due to lack of activity.
