### ISSUE TITLE
Engine requires existence of Blob constructor to parse

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1578]
See line:

https://github.com/playcanvas/engine/blob/master/src/resources/untar.js#L259

Presence of Blob constructor is not guaranteed. For example, it's not present in Node. So even if the app does not use bundles, the engine was fail to load because ```scopeToUrl``` is called at library JS parse time.

**Comment by terence-wang** [comment]
I see a pull request review failed, when can I use this version?

**Comment by willeastcott** [comment]
@terence-wang You want to run the engine in Node? What's your use case? (Just curious)

**Comment by terence-wang** [comment]
I need to run in some Hybrid rendering environments, because there is no JSDom in the Hybrid rendering environment, I blocked the blob by modifying the engine, I really look forward to official support.

**Comment by willeastcott** [comment]
OK, I've merged that PR. Is the engine OK for you now @terence-wang?

**Comment by terence-wang** [comment]
In an environment without JSDOM, many global object properties are artificially simulated, such as HTMLElement. In the _calcTouchCoords function, "target instanceof HTMLElement" is not valid, which will result in "Cannot read property 'parentNode' of null"

**Comment by willeastcott** [comment]
Yes, we have to identify all of those and ensure they are handled correctly.
