### ISSUE TITLE
Building PlayCanvas Engine

### ISSUE THREAD

**Issue by r2d2Proton** [playcanvas/engine#158]
Do I need Java installed to build the engine?

I added both C:\Python27; and C:\Python27\Lib to my path. Do I need to add anything else to my path?

I'm getting the below error when I try to build it:

C:\PlayCanvas\engine\build>python build.py
Traceback (most recent call last):
  File "build.py", line 201, in <module>
    retcode = build(output_path)
  File "build.py", line 95, in build
    retcode = subprocess.call(cmd)
  File "c:\python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by daredevildave** [comment]
Yes. Building the engine runs the closure compiler which requires Java.

**Comment by r2d2Proton** [comment]
Thanks Dave.

Is it safe to say that the latest version of Java is okay to use?
http://www.java.com/en/download/ie_manual.jsp?locale=en

**Comment by r2d2Proton** [comment]
I got it working now using the localserver.bat approach. I really wanted to use Visual Studio so that I can easily step through the code (give that I've used the IDE for a hundred years or so).

As I stated before, I have the project folders intact, the source code isn't minified, and I can view the overall structure more easily. In an effort to get away from copying and pasting the list of source file (all 185 of them) into the HEADER section of each HTML, I created a singe HTML that includes the list of JavaScript files (and in the same order as Dependicies.txt does). Now it's a simple matter of a one-liner in each HTML file, and commenting out the -latest.js reference.

Here's the bummer, as I ran into it anyway. . .Visual Studio 2013 isn't expanding my IMPORT request:

    
    <link rel="import" href="../../SourceFiles.html" />

And when trying to debug the "website" the debugger fails. It doesn't recognize "PC" or "pc", which leads me to believe the JavaScript files aren't being imported.

When I run localhost using the localserver.bat file, it works fine. Any ideas?

**Comment by willeastcott** [comment]
Just to check that your import is actually working, can you run this function:

    function supportsImports() {
        return 'import' in document.createElement('link');
    }

What does it return? Note I found this function here:

http://www.html5rocks.com/en/tutorials/webcomponents/imports/

**Comment by r2d2Proton** [comment]
That's funny. That's the exact link I got the import from. Of course I skimmed over it looking for the punch line. I also got the Xbox/PlayStation Controller link from that site too.

Let me read through it so that I have a better understanding of the function use and I'll report my findings shortly.

**Comment by r2d2Proton** [comment]
Sadly I didn't have to go too far down the page. And worse yet, on IE 11 the function is reporting that import isn't supported.

A side note: it's a little scary when HTML/DOM authors talk about how exciting something like "import" is:

"Let this sit. It's exciting stuff."

Coming upon this issue, that is to centralize the list of files to include, my first question was where in the heck is the #include directive :dancer: 

Btw, the Dojo Toolkit, which I've used in the past makes heavy use of asynchronous loading of JavaScript files.

I'm going to see if I can find a fix for IE.

**Comment by liming0791** [comment]
My java is 64bit version , and I had the same error while building. Do I need a 32bit java SDK to build it ?

**Comment by willeastcott** [comment]
@liming0791 Have you checked that 'java' is in your path on the command line? I don't see why the 64-bit version of Java wouldn't work.
