### ISSUE TITLE
exporting from engine

### ISSUE THREAD

**Issue by japrogramer** [playcanvas/engine#1595]
Is there a way to export an asset as an fbx or any other formatt
from the engine?

I would like to export all the assets in a scene to fbx.

```
app.assets._assets.map(asset => {
 /* what goes here? */
})
```

**Comment by willeastcott** [comment]
There is no built in way to do that.

If I were you, I would descend the hierarchy and find all the model components and then incrementally build a list of vertices and triangles and then write an OBJ out at the end. It's easy to convert OBJ to FBX (and pretty much any app that can read FBX can read OBJ).

**Comment by japrogramer** [comment]
I was able to save the raw json files and import them into blender but the scale, rotation and location is off .

On top of that i still haven't been able to set normals or textures.

I know that the playcanvas editor can export a scene or objects to fbx,
I would like to know where that function is called and how .. so i can maybe export the scene that way.

**Comment by yaustar** [comment]
> I know that the playcanvas editor can export a scene or objects to fbx,

Where have you seen/heard this? AFAIK, it's never had that feature.

**Comment by japrogramer** [comment]
Ah never mind i miss read this 
https://developer.playcanvas.com/en/user-manual/assets/models/exporting/

**Comment by willeastcott** [comment]
OK, well, unless there's anything more to discuss on this, shall I close this issue?
