### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by gameatp** [playcanvas/engine#1608]
![image](https://user-images.githubusercontent.com/4427058/60732893-e00a2380-9f7d-11e9-8407-e6560b209c1c.png)
GraphNode stored in Model is not destroy

**Comment by willeastcott** [comment]
Can you provide a simple test case that shows the problem please?

**Comment by gameatp** [comment]
> Can you provide a simple test case that shows the problem please?
I modified the load model example in examples.
Add an entity and mount an entity to the root node of the entity, then release the entity
   <script>
        var canvas = document.getElementById("application-canvas");

        // Create the app and start the update loop
        var app = new pc.Application(canvas);
        app.start();

        // Set the canvas to fill the window and automatically change resolution to be the same as the canvas size
        app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);
        app.setCanvasResolution(pc.RESOLUTION_AUTO);

        app.scene.ambientLight = new pc.Color(0.2, 0.2, 0.2);
		
        var light, camera;
		var numModel = 0;
        // Load a model file and create a Entity with a model component

		var entity;
		var url = "../assets/statue/Statue_1.json";
		app.assets.loadFromUrl(url, "model", function (err, asset) {
			entity = new pc.Entity();
			entity.addComponent("model", {
				type: "asset",
				asset: asset,
				castShadows: true
			}); 

		 	var attachNode = entity.model.model.graph.findByName("RootNode");
 
			var entityAttach = new pc.Entity();
			entityAttach.addComponent("model", {
				type: "asset",
				asset: asset,
				castShadows: true
			}); 
			
			 if(attachNode){
				entityAttach.reparent(attachNode); 
				entityAttach.setLocalScale(new pc.Vec3(1,1,1));
                entityAttach.setLocalPosition(4,0,-0.0);
                entityAttach.setLocalEulerAngles(new pc.Vec3(0,0,0));
                entityAttach.enabled=true;  
		 	}  
			
			app.root.addChild(entity);
			
			setTimeout(function(){
				entity.destroy();
			},1000);
		}); 


        // Create an Entity with a camera component
        var camera = new pc.Entity();
        camera.addComponent("camera", {
            clearColor: new pc.Color(0.4, 0.45, 0.5)
        });
        camera.translate(0, 7, 24);
        app.root.addChild(camera);

        // Create an Entity with a point light component
        var light = new pc.Entity();
        light.addComponent("light", {
            type: "point",
            color: new pc.Color(1, 1, 1),
            range: 100,
            castShadows: true
        });
        light.translate(5, 0, 15);
        app.root.addChild(light);

        /*app.on("update", function (dt) {
            if (entity) {
                entity.rotate(0,10*dt,0);
            }
        });*/
    </script>

![image](https://user-images.githubusercontent.com/4427058/60852898-4320e200-a22c-11e9-82df-47720baca8a5.png) 
Here, only the graphnode in the model is removed, but the Entity object below is not released, and the model mounted later is also displayed on the screen.

after:
![Uploading image.png…]()

**Comment by gameatp** [comment]
[index.zip](https://github.com/playcanvas/engine/files/3370845/index.zip)
 
![image](https://user-images.githubusercontent.com/4427058/60853762-1d95d780-a230-11e9-95eb-9efa405c4929.png)

![TIM图片20190709095916](https://user-images.githubusercontent.com/4427058/60853791-39997900-a230-11e9-9dd8-96bda75c720e.png)


The first one is that I don't do anything with four graphnodes

The second is that after I loaded the model, I released all the graphnodes that I found, and the number of graphnodes increased.

**Comment by gameatp** [comment]
[index.zip](https://github.com/playcanvas/engine/files/3371093/index.zip)
I did another test, meshInstance also had a memory leak.
 
![W6L%J6C7X_}SZZW{FCE$)NT](https://user-images.githubusercontent.com/4427058/60857975-2641da00-a23f-11e9-9ce2-1fbf4f25fc37.png)
I created 100 spheres and destroy them, but meshInstance did not decrease.

**Comment by gameatp** [comment]
I've found the problem.
