### ISSUE TITLE
Custom layers can't use any posteffects

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/engine#1639]
### Description

If you add a post-effect to a camera with a custom layer, it will not affect that layer (even if it's camera's only layer). Expected behavior should be that all camera layers (incl custom) are affected by the camera's post-effect queue.

### Steps to Reproduce

1. Run public project: https://playcanvas.com/project/631240/overview/posteffect-layer-bug
2. Observe Hue Posteffect (shifts red to green) not affecting `Box`.
3. Also, notice `Box` being rendered on top of everything.

### What I expect to see

![image](https://user-images.githubusercontent.com/255073/62425201-b6592f00-b6d8-11e9-8cdb-25d8c16da15e.png)

### What I see instead

![image](https://user-images.githubusercontent.com/255073/62425195-a17c9b80-b6d8-11e9-9270-f7f1a984a98b.png)

### Scene setup

- 3 models (`Box`, `Sphere`, `Plane`) all using standard material `red`.
- `Camera` has store script `Hue / Saturation Post Effect` (with hue set to `0.5`).
- Scene render order has `MyLayer` listed at the bottom.
- `Camera` and `Light` is set to default layers + `MyLayer`.
- `Box` is set to layer `MyLayer` exclusively.

**Comment by aidinabedi** [comment]
I managed to find the root cause. Its seems post effects won't be applied to any layer below the default `UI` layer, which might seem reasonable since you may not want those layers to be affected. However, I would rather suggest adding a simple toggle to `pc.Layer` which enables or disables post-effects for that specific layer, since in certain cases you might actually want custom "UI" layers to have posteffects. It would also make the behavior clearly obvious, rather than a silent behind-the-scenes distinction. Not sure if this behavior is documented (maybe I just missed it).

**Comment by mvaligursky** [comment]
This has been mostly addressed by https://github.com/playcanvas/engine/pull/2882
