### ISSUE TITLE
GraphicsDevice.Clear with RenderTargets

### ISSUE THREAD

**Issue by r2d2Proton** [playcanvas/engine#164]
When we have a render target set, should the clear command clear the contents of the render target or the front buffer?

**Comment by willeastcott** [comment]
pc.GraphicsDevice#clear should really only be called inside a pc.GraphicsDevice#updateBegin/End block. The render target is only bound in WebGL inside pc.GraphicsDevice#updateBegin. So provided you do call clear inside the begin/end block, whatever is bound (render target or back buffer) will be cleared.

I could tighten up the docs on this to make it more obvious.

**Comment by r2d2Proton** [comment]
Thanks Will.

After reviewing the documentation (again) I remember seeing the description and use of it. So, first call setRenderTarget(target), then make the Begin/End calls followed by setRenderTarget(null).

Is that correct?

**Comment by willeastcott** [comment]
Yes, that should work.

**Comment by r2d2Proton** [comment]
Thanks :)  I'll close this once I finish my testing.

**Comment by r2d2Proton** [comment]
I don't think it's working. I can clear the front buffer with green and see it provided I don't do anything else:

    gd.setRenderTarget(null);
    gd.updateBegin();
    gd.clear({
        color: [0.0, 1.0, 0.0, 1.0],
        depth: 1.0,
        flags: pc.CLEARFLAG_COLOR | pc.CLEARFLAG_DEPTH
    });
    gd.updateEnd();

I can clear the front buffer with green, and render to a target and don't do anything else and see the green as should be the case:

    gd.setRenderTarget(null);
    gd.updateBegin();
    gd.clear({
        color: [0.0, 1.0, 0.0, 1.0],
        depth: 1.0,
        flags: pc.CLEARFLAG_COLOR | pc.CLEARFLAG_DEPTH
    });
    gd.updateEnd();

    gd.setRenderTarget(this.colorRT);
    gd.updateBegin();
    this.DrawBackground(gd);
    gd.updateEnd();
    gd.setRenderTarget(null);

The above still shows green, which is correct. And I can render what was drawn to the rendertarget and see the image:

    var white = new pc.Vec4().copy(pc.Vec4.ONE);
    var rect = new pc.Vec4(0, 0, gd.width, gd.height);
    this.DrawTexture(gd, this.colorRT, rect, white, window.ScreenManager.BlendMode.None);

However, if I just use clear with the rendertarget nothing appears. So instead of rendering my own image, just performing the clear and rendering it to the screen appears not to work:

    gd.setRenderTarget(this.colorRT);
    gd.updateBegin();
    gd.clear({
        color: [1.0, 0.0, 0.0, 1.0],
        depth: 1.0,
        flags: pc.CLEARFLAG_COLOR | pc.CLEARFLAG_DEPTH
    });
    gd.updateEnd();
    gd.setRenderTarget(null);

    var white = new pc.Vec4().copy(pc.Vec4.ONE);
    var rect = new pc.Vec4(0, 0, gd.width, gd.height);
    this.DrawTexture(gd, this.colorRT, rect, white, window.ScreenManager.BlendMode.None);

The only substitution made was the use of "clear" vs. rendering with a texture.

**Comment by willeastcott** [comment]
I suspect this is not working because you are using the default filter modes on your render target, which are mipmapped. Here's code from the pc.Texture constructor:

        this._addressU = pc.ADDRESS_REPEAT;
        this._addressV = pc.ADDRESS_REPEAT;

        if (pc.math.powerOfTwo(this._width) && pc.math.powerOfTwo(this._height)) {
            this._minFilter = pc.FILTER_LINEAR_MIPMAP_LINEAR;
        } else {
            this._minFilter = pc.FILTER_LINEAR;
        }
        this._magFilter = pc.FILTER_LINEAR;

When creating this.colorRT, do this:

        // Create a 512x512x24-bit render target with a depth buffer
        this.colorBuffer = new pc.Texture(gd, {
            width: 512,
            height: 512,
            format: pc.PIXELFORMAT_R8_G8_B8
        });
        this.colorBuffer.minFilter = pc.FILTER_NEAREST;
        this.colorBuffer.magFilter = pc.FILTER_NEAREST;
        this.colorBuffer.addressU = pc.ADDRESS_CLAMP_TO_EDGE;
        this.colorBuffer.addressV = pc.ADDRESS_CLAMP_TO_EDGE;

        this.colorRT = new pc.RenderTarget(gd, this.colorBuffer, {
            depth: true
        });
