### ISSUE TITLE
Vector distance functions

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1643]
To get the distance between two vectors, you currently have to do:

```
var temp = new pc.Vec3();
temp.sub2(v1, v2);
var d = temp.length();
```

This is kind of annoying, especially because you have to allocate a temporary vector. It would be useful to have one or more functions to help. Examples:

```
// Init
var v1 = new pc.Vec3();
var v2 = new pc.Vec3();
var d;

// Static
d = pc.Vec3.distance(v1, v2);

d = pc.Vec3.distanceSq(v1, v2);

// Non-static
d = v1.distance(v2);
d = v1.distanceTo(v2);

d = v1.distanceSq(v2);
d = v1.distanceSqTo(v2);
d = v1.distanceToSq(v2);
```

Personal feelings:

* I don't like the static variants because the vector APIs currently have zero static functions so it'd be setting a new precedent.
* I think I like ```v1.distance(v2)``` and ```v1.distanceSq(v2)``` best. Anyone want to persuade me otherwise before I add?

**Comment by yaustar** [comment]
Could they be added to pc.math as static functions?  Or would that feel like the logic is in the wrong place/file?

**Comment by willeastcott** [comment]
I think ```pc.math``` is almost certainly the wrong place. There'll need to be implementations for ```pc.Vec2```, ```pc.Vec3``` and maybe ```pc.Vec4```.

**Comment by Maksims** [comment]
I think `d = v1.distance(v2);` is simple to remember and straight forward.
Would simply return distance in units.

Most common use would be doing simple distance calculation between two points, so `distance` is easy to remember.
If someone needs some extra maths and specifics, where they wouldn't square the (a * a + b * b), then that person probably knows how to use other methods to achieve his specific case.
So naming `distance` this: `Math.sqrt(x * x + y * y)` - would be most straight forward and simple to remember and use by users.
