### ISSUE TITLE
How to make a 360 panorama ball with palycanvas

### ISSUE THREAD

**Issue by carior** [playcanvas/engine#1644]
This issue tracker is **only** for bug reports and feature requests. For general support/help, visit https://forum.playcanvas.com

For bug reports, include:

### Description

Provide as much information as possible. Include (where applicable):

* URL to a simple, reproducible test case that illustrates the problem clearly
* Screenshots
* The platform(s)/browser(s) where the issue is seen
* A screenshot of http://webglreport.com/ (for graphics related issues)

### Steps to Reproduce

1. 
2.
3.

**Comment by daredevildave** [comment]
Please ask questions on the forum: https://forum.playcanvas.com
