### ISSUE TITLE
Y-axis clamped at 90 when Mat4.setFromEulerAngles

### ISSUE THREAD

**Issue by r2d2Proton** [playcanvas/engine#165]
I performed a simple test and found Y-axis to be clamped. In the below code I'm stepping a half-degree per iteration and printing out the read back Y-axis value:

<code>
var m = new pc.Mat4().setIdentity();

    for (var r = 0; r < 720; r++) {

        var a = m.getEulerAngles();

        console.log("r = " + r + " a.y = " + a.y);

        a.y += 0.5;

        m.setFromEulerAngles(0.0, a.y, 0.0);

}

</code>

The log follows below. Notice that Y bounces near the bottom where I believe it should steadily increase:

r = 0 a.y = 0
r = 1 a.y = 0.5
r = 2 a.y = 1
r = 3 a.y = 1.4999
r = 4 a.y = 2
r = 5 a.y = 2.5
r = 6 a.y = 2.9999
r = 7 a.y = 3.4999
r = 8 a.y = 3.9999
r = 9 a.y = 4.4999
r = 10 a.y = 4.999
r = 11 a.y = 5.499
r = 12 a.y = 5.999
r = 13 a.y = 6.499
r = 14 a.y = 6.999
r = 15 a.y = 7.499
r = 16 a.y = 7.999
r = 17 a.y = 8.499
r = 18 a.y = 8.999
r = 19 a.y = 9.499
r = 20 a.y = 9.999
r = 21 a.y = 10.49
r = 22 a.y = 10.99
r = 23 a.y = 11.5
r = 24 a.y = 11.99
r = 25 a.y = 12.49
r = 26 a.y = 13
r = 27 a.y = 13.49
r = 28 a.y = 13.99
r = 29 a.y = 14.49
r = 30 a.y = 14.99
r = 31 a.y = 15.49
r = 32 a.y = 15.99
r = 33 a.y = 16.49
r = 34 a.y = 16.99
r = 35 a.y = 17.49
r = 36 a.y = 17.99
r = 37 a.y = 18.49
r = 38 a.y = 18.99
r = 39 a.y = 19.49
r = 40 a.y = 19.99
r = 41 a.y = 20.49
r = 42 a.y = 20.99
r = 43 a.y = 21.49
r = 44 a.y = 21.99
r = 45 a.y = 22.49
r = 46 a.y = 22.99
r = 47 a.y = 23.49
r = 48 a.y = 23.99
r = 49 a.y = 24.49
r = 50 a.y = 24.99
r = 51 a.y = 25.49
r = 52 a.y = 25.99
r = 53 a.y = 26.49
r = 54 a.y = 26.99
r = 55 a.y = 27.49
r = 56 a.y = 27.99
r = 57 a.y = 28.49
r = 58 a.y = 28.99
r = 59 a.y = 29.49
r = 60 a.y = 29.99
r = 61 a.y = 30.49
r = 62 a.y = 30.99
r = 63 a.y = 31.5
r = 64 a.y = 32
r = 65 a.y = 32.5
r = 66 a.y = 33
r = 67 a.y = 33.5
r = 68 a.y = 34
r = 69 a.y = 34.5
r = 70 a.y = 35
r = 71 a.y = 35.5
r = 72 a.y = 36
r = 73 a.y = 36.5
r = 74 a.y = 37.00
r = 75 a.y = 37.50
r = 76 a.y = 38.00
r = 77 a.y = 38.50
r = 78 a.y = 39.00
r = 79 a.y = 39.50
r = 80 a.y = 40.00
r = 81 a.y = 40.50
r = 82 a.y = 41.00
r = 83 a.y = 41.50
r = 84 a.y = 42.00
r = 85 a.y = 42.50
r = 86 a.y = 43.00
r = 87 a.y = 43.50
r = 88 a.y = 44.00
r = 89 a.y = 44.50
r = 90 a.y = 45.00
r = 91 a.y = 45.50
r = 92 a.y = 46.00
r = 93 a.y = 46.50
r = 94 a.y = 47.00
r = 95 a.y = 47.50
r = 96 a.y = 48.00
r = 97 a.y = 48.50
r = 98 a.y = 49.00
r = 99 a.y = 49.50
r = 100 a.y = 50.0
r = 101 a.y = 50.5
r = 102 a.y = 51
r = 103 a.y = 51.5
r = 104 a.y = 52.0
r = 105 a.y = 52.5
r = 106 a.y = 53.0
r = 107 a.y = 53.5
r = 108 a.y = 54.0
r = 109 a.y = 54.5
r = 110 a.y = 55.0
r = 111 a.y = 55.5
r = 112 a.y = 56.0
r = 113 a.y = 56.5
r = 114 a.y = 57.0
r = 115 a.y = 57.5
r = 116 a.y = 58.0
r = 117 a.y = 58.5
r = 118 a.y = 59.0
r = 119 a.y = 59.5
r = 120 a.y = 60.0
r = 121 a.y = 60.5
r = 122 a.y = 61.0
r = 123 a.y = 61.5
r = 124 a.y = 62.0
r = 125 a.y = 62.5
r = 126 a.y = 63.0
r = 127 a.y = 63.5
r = 128 a.y = 64.0
r = 129 a.y = 64.5
r = 130 a.y = 65.0
r = 131 a.y = 65.5
r = 132 a.y = 66.0
r = 133 a.y = 66.5
r = 134 a.y = 67.0
r = 135 a.y = 67.5
r = 136 a.y = 68.0
r = 137 a.y = 68.5
r = 138 a.y = 69
r = 139 a.y = 69.5
r = 140 a.y = 70
r = 141 a.y = 70.5
r = 142 a.y = 70.9
r = 143 a.y = 71.4
r = 144 a.y = 71.9
r = 145 a.y = 72.5
r = 146 a.y = 73
r = 147 a.y = 73.5
r = 148 a.y = 74
r = 149 a.y = 74.4
r = 150 a.y = 75
r = 151 a.y = 75.4
r = 152 a.y = 75.9
r = 153 a.y = 76.4
r = 154 a.y = 76.9
r = 155 a.y = 77.4
r = 156 a.y = 77.9
r = 157 a.y = 78.4
r = 158 a.y = 79
r = 159 a.y = 79.5
r = 160 a.y = 79.9
r = 161 a.y = 80.4
r = 162 a.y = 80.9
r = 163 a.y = 81.4
r = 164 a.y = 81.9
r = 165 a.y = 82.4
r = 166 a.y = 82.9
r = 167 a.y = 83.4
r = 168 a.y = 83.9
r = 169 a.y = 84.5
r = 170 a.y = 85.0
r = 171 a.y = 85.5
r = 172 a.y = 86.0
r = 173 a.y = 86.5
r = 174 a.y = 87.0
r = 175 a.y = 87.5
r = 176 a.y = 88.0
r = 177 a.y = 88.5
r = 178 a.y = 89.0
r = 179 a.y = 89.4
r = 180 a.y = 90
r = 181 a.y = 89.4
r = 182 a.y = 90
r = 183 a.y = 89.4
r = 184 a.y = 90
r = 185 a.y = 89.4
r = 186 a.y = 90
r = 187 a.y = 89.4

**Comment by r2d2Proton** [comment]
Actually I think is the getEulerAngles that is causing the problem. Keeping track of the angle and setting it, regardless of previous values in the matrix, works.

**Comment by willeastcott** [comment]
This isn't a bug. The other eulers will have flipped signs at some point in rotating around Y. But you're not printing those. The Eulers are not stored as such. Instead, they are converted to a quaternion on set:

https://github.com/playcanvas/engine/blob/master/src/scene/scene_graphnode.js#L594

And when you query them, they are extracted from the quaternion:

https://github.com/playcanvas/engine/blob/master/src/scene/scene_graphnode.js#L393

This store/extract operation can cause axes to flip, but the rotation remains equivalent. Getting Eulers you have just set does not guarantee returning the same values. But it does guarantee returning the same orientation. You cannot consider one Euler while ignoring the other two.
