### ISSUE TITLE
The POT on texture import is resizing to nearest POT rather than next POT

### ISSUE THREAD

**Issue by JamesWarburton-slipstreamlabs** [playcanvas/engine#1651]
The documentation claims the following:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/53750918/62880193-c69a8b00-bd24-11e9-9bec-60fe0c456d27.png)

When importing a texture with the power of two option ticked rather than resizing to the next highest POT they are actually imported to the nearest POT.

e.g.
Imported with POT turned off
![Non_POT](https://user-images.githubusercontent.com/53750918/62880524-7cfe7000-bd25-11e9-8531-995ef960a4dc.PNG)

Imported with POT turned on
![POT](https://user-images.githubusercontent.com/53750918/62880533-838ce780-bd25-11e9-9379-f7cd44b99ee7.PNG)

### Steps to Reproduce

1. Ensure Textures POT is turned on under Asset Tasks
2. Import a texture that has a dimension where the nearest POT is lower rather than higher

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/developer.playcanvas.com/commit/15a6f866e8216bee7b2b01ccc28300ae5a2c6360
