### ISSUE TITLE
Updating material.opacity does not work as expected

### ISSUE THREAD

**Issue by pjc0247** [playcanvas/engine#1655]
https://playcanvas.com/project/633316/overview/mattest

There are two `2D Screen`s, one is enabled by default, another one is disabled.

First one works as expected, the opacity will be set to `0.5`.
The second element does not work properly, it will be enabled by `Root/delayedEnable` after 1 sec. but opacity won't be changed.

This only happens with texture, So I made 2 elements for each `2D Screen` to explain it.

**Comment by velbi** [comment]
How about this?
![this](https://user-images.githubusercontent.com/39391128/63409940-17009f80-c42d-11e9-87cd-4e9466ba7b8c.PNG)

in your Test.js
```
var Test = pc.createScript('test');


Test.prototype.initialize = function() {
    
    this.entity.element.material = this.entity.element.material.clone();    
    this.entity.element.material.opacity = 0.5;
    
    
    if(this.entity.name === 'Tex (BUG)') {
        var material = new pc.StandardMaterial();
        var blood = pc.app.assets.find('bear.gif', 'texture');
        
        material.diffuseMap = blood.resource;
        material.opacityMap = blood.resource;
        console.log(material.opacityMap);
        material.blendType = pc.BLEND_NORMAL;
        // material.opacityMapChannel = 'r';
        material.update();
        this.entity.element.material = material;
        
        
    }
        
    this.entity.element.material.update();
    
};

```

**Comment by pjc0247** [comment]
@velbi 

Thank you for the solution, but I think your code is a workaround. I wrote the issue to request them to fix it.

And, here's a code how I solved it.
```js
setTimeout(() => {
  this.entity.element.material = this.entity.element.material.clone();    
  this.entity.element.material.opacity = 0.1;
  this.entity.element.material.update();
}, 1);
```

**Comment by mvaligursky** [comment]
#6721 most likely fixed this issue, closing.
