### ISSUE TITLE
Entity belongs to Screen has hidden child

### ISSUE THREAD

**Issue by pjc0247** [playcanvas/engine#1660]
![image](https://user-images.githubusercontent.com/1961216/63561886-7c23d480-c596-11e9-9795-be38a52d9587.png)

![image](https://user-images.githubusercontent.com/1961216/63561818-36670c00-c596-11e9-8fd5-c69a520067cf.png)

![image](https://user-images.githubusercontent.com/1961216/63561915-9c539380-c596-11e9-968a-9e260b4169e3.png)

There's nothing inside `Text` but `entity.children` shows a hidden child. 

https://playcanvas.com/project/634274/overview/childtest

**Comment by daredevildave** [comment]
Entities that have graphical representations have child graph nodes which locate the mesh instances for the 3D data.

model components, image and text elements and sprites all have GraphNode children at runtime.

**Comment by pjc0247** [comment]
@daredevildave I think every internal object/componets should be hidden. I can nothing to do with it, and makes me confusing when I trying to make such as  `destroyAllChildren`.
