### ISSUE TITLE
[Bug] Mouse lock on firefox

### ISSUE THREAD

**Issue by darklight9811** [playcanvas/engine#1669]
### Description

When using mouse lock on any project while on firefox, its sensibility goes from 4 dx/5dy to 700 dx/1000dx (delta of the axis). Fullscreen, published projects, nothing matter.

Provide as much information as possible. Include (where applicable):
Video of the bug: https://www.youtube.com/watch?v=KYQ-0_z9PTc

### Steps to Reproduce

1. Open firefox
2. Open this project: https://playcanv.as/p/HzOzlZOC/
3. Let the mouse be locked

**Comment by kungfooman** [comment]
What OS and browser version are you on? Pointer lock mouse data bugs got quite some history, I made a FPS too, which was bugged by them. I wrote this bug report last time: https://bugzilla.mozilla.org/show_bug.cgi?id=1417702

They fixed it, at least I verified it works on Windows 10.

You can test the attached canvas.html

**Comment by kungfooman** [comment]
You can click on attachment link: https://bug1417702.bmoattachments.org/attachment.cgi?id=8928740

**Comment by willeastcott** [comment]
Excellent. Closing this.
