### ISSUE TITLE
Mat4.setLookAt

### ISSUE THREAD

**Issue by r2d2Proton** [playcanvas/engine#167]
Below is a lookAt function that appears to work correctly in my code. However, when I tried to override the functionality within the Mat4 class, the Camera class didn't work correctly. I believe it has more to do with the Camera class than the function. Would you please consider testing the below function with the camera class, and see if the camera changes are minimal or not. Thank you.

        setLookAt: function (pos, target, upDir) {

            var forward = new pc.Vec3().sub2(pos, target).normalize();
            var left    = new pc.Vec3().cross(upDir, forward).normalize();
            var up      = new pc.Vec3().cross(forward, left).normalize();

            // set inverse translation matrix: Mt
            var matTrans = new pc.Mat4();
            matTrans.data[0]  = matTrans.data[5] = matTrans.data[10] = matTrans.data[15] = 1.0;
            matTrans.data[3]  = -pos.x;
            matTrans.data[7]  = -pos.y;
            matTrans.data[11] = -pos.z;

            // set inverse of rotation matrix: Mr
            // NOTE: M^-1 = M^T if it is Euclidean transform
            var matRot = new pc.Mat4();
            matRot.data[0]  = left.x;     matRot.data[4] = left.y;     matRot.data[8]  = left.z;
            matRot.data[1]  = up.x;       matRot.data[5] = up.y;       matRot.data[9]  = up.z;
            matRot.data[2]  = forward.x;  matRot.data[6] = forward.y;  matRot.data[10] = forward.z;
            matRot.data[15] = 1.0;

            var invPos = new pc.Vec3().copy(pos);
            invPos.scale(-1);

            // compute M = Mr * Mt
            var m = this.data;
            m[0] = left.x;     m[4] = left.y;     m[8]  = left.z;     m[12] = left.dot(invPos);
            m[1] = up.x;       m[5] = up.y;       m[9]  = up.z;       m[13] = up.dot(invPos);
            m[2] = forward.x;  m[6] = forward.y;  m[10] = forward.z;  m[14] = forward.dot(invPos);
            m[3] = 0.0;        m[7] = 0.0;        m[11] = 0.0;        m[15] = 1.0;

            return this;
        },

**Comment by daredevildave** [comment]
Does this produce the same results for the same input as Mat4#setLookAt()?

**Comment by r2d2Proton** [comment]
Mat4.setLookAt doesn't work. Try a simple test. Below the camera position is 1 up the Y-axis, and is looking down. Mat4.setLookAt doesn't honor that request. Also, change the Z-direction. Instead of being in the negative direction, change it to positive and you won't be looking at the origin. Either that, all of my code is messed up. However, if I use the above I get exactly what I'm expecting.

            var cameraPos = new pc.Vec3(0.0, 1.0, -3.0);
            var target = new pc.Vec3().copy(pc.Vec3.ZERO);
            var upDir = new pc.Vec3().copy(pc.Vec3.UP);
            var view = new pc.Mat4().setLookAt(cameraPos, target, upDir);

**Comment by daredevildave** [comment]
Mat4.setLookAt is used all over the place, so I'm pretty sure it works.

**Comment by r2d2Proton** [comment]
Okay, maybe I am doing something wrong. Would you mind reviewing the information below and let me know what I need to change in order to get the correct behavior.

There are a series of screenshots using both pc.Mat4.setLookAt, and the LookAt I posted above. The first lookat the camera is position at (0.0, 1.0, -3.0), and changes to (0.0, -1.0, -3.0), then to looking from the other side (instead of negative z-axis looking at 0,0,0, to a positive z-axis looking at 0,0,0).

![01 translateobjects still pos 0 0 -3 lookat 0 0 0 source](https://cloud.githubusercontent.com/assets/4054178/6400116/28e66506-bdb4-11e4-9b5f-898d270caf05.jpg)
![01 translateobjects still pos 0 0 -3 lookat 0 0 0](https://cloud.githubusercontent.com/assets/4054178/6400120/2cb30626-bdb4-11e4-80f2-ae730e025a37.jpg)


![02 translateobjects still pos 0 0 -3 lookat 0 0 0 source](https://cloud.githubusercontent.com/assets/4054178/6400122/314369ce-bdb4-11e4-973c-60ea82385235.jpg)
![02 translateobjects still pos 0 0 -3 lookat 0 0 0](https://cloud.githubusercontent.com/assets/4054178/6400125/35e5290e-bdb4-11e4-8c7c-8c641507b602.jpg)


![03 not looking at 0 0 0 source](https://cloud.githubusercontent.com/assets/4054178/6400132/3e25e9dc-bdb4-11e4-8d50-4693d275d109.jpg)
![03 not looking at 0 0 0](https://cloud.githubusercontent.com/assets/4054178/6400135/411e346e-bdb4-11e4-84d4-1e9118267549.jpg)

Okay, now with the LookAt using the proposed code (one from the front, and the other from behind):
![04 from the front source](https://cloud.githubusercontent.com/assets/4054178/6400147/52418412-bdb4-11e4-9fda-b73ca04d0c69.jpg)
![04 from the front](https://cloud.githubusercontent.com/assets/4054178/6400149/570c4112-bdb4-11e4-9f37-c65971915bb2.jpg)


![05 from the back source](https://cloud.githubusercontent.com/assets/4054178/6400152/5eefe690-bdb4-11e4-8d19-dc31783b523b.jpg)
![05 from the back](https://cloud.githubusercontent.com/assets/4054178/6400156/60e4439c-bdb4-11e4-9523-55a98002a2dc.jpg)

**Comment by daredevildave** [comment]
Looks like your view matrix is wrong. In scene_forwardrenderer we do this:

            // ViewInverse Matrix
            var pos = camera._node.getPosition();
            var rot = camera._node.getRotation();
            viewInvMat.setTRS(pos, rot, pc.Vec3.ONE);
       
            // View Matrix
            viewMat.copy(viewInvMat).invert();

You need to invert your view matrix.

**Comment by r2d2Proton** [comment]
I should have tried this earlier. If I invert the view matrix it works as expected. (I see your comment now).

Okay, easy enough to follow.
