### ISSUE TITLE
Autocomplete missing in script editor

### ISSUE THREAD

**Issue by vanderry** [playcanvas/engine#1679]
It appears that the script view in the editor no longer provides autocompletion the way it did only a few days ago. It's not a matter of bad syntax from what I can tell. A freshly created script with the template code is equally unresponsive. That would be the reproduction steps.

**Comment by yaustar** [comment]
Please see thread: https://forum.playcanvas.com/t/strange-console-errors-auto-complete-for-scripting-not-working/10860/5?u=yaustar

**Comment by vanderry** [comment]
Happy to hear that the issue is being looked at. I can't tell for sure whether the right place for the report is on the forum or here, but unless there's a case against it I'll leave this one open until the problem has been fixed. Someone else is bound to come looking here for the same thing.

**Comment by yaustar** [comment]
General rule of thumb, if it's an engine issue, then here is fine. If it's a tools/service/site issue then it should be the forums :)

**Comment by vanderry** [comment]
Sounds good. Thanks for the quick response, @yaustar.
