### ISSUE TITLE
Mat3.setIdentity() creates a 4x4 matrix

### ISSUE THREAD

**Issue by zfedoran** [playcanvas/engine#168]
The setIdentity() function sets 16 values rather than 9. This is inconsistent with the rest of the code and may cause unexpected bugs or errors.

```javascript
        setIdentity: function () {
            var m = this.data;
            m[0] = 1;
            m[1] = 0;
            m[2] = 0;
            m[3] = 0;
            m[4] = 0;
            m[5] = 1;
            m[6] = 0;
            m[7] = 0;
            m[8] = 0;
            m[9] = 0;
            m[10] = 1;
            m[11] = 0;
            m[12] = 0;
            m[13] = 0;
            m[14] = 0;
            m[15] = 1;

            return this;
        }
```

**Comment by vkalpias** [comment]
Hi,

You are talking about pc.Mat4 correct? Why is this inconsistent with the rest of the code? A pc.Mat4 is a 4x4 matrix so it has 16 values. The other methods in pc.Mat4 also set 16 values unless there is a method that doesn't somewhere?

**Comment by zfedoran** [comment]
Hi, I am referring to pc.Mat3, not pc.Mat4.

https://github.com/playcanvas/engine/blob/master/src/math/math_mat3.js#L115

**Comment by vkalpias** [comment]
Ah OK, thank you. We're not using pc.Mat3 that much internally so that one must have slipped. Fixed it.
