### ISSUE TITLE
Documentation bug: ZoneComponent

### ISSUE THREAD

**Issue by mast4461** [playcanvas/engine#1680]
The documentation for [`pc.Entity.addComponent`](https://developer.playcanvas.com/en/api/pc.Entity.html#addComponent) refers to something called a "zone", and provides the broken link https://developer.playcanvas.com/en/api/pc.ZoneComponent.html.

Either the documentation page for ZoneComponent is indeed missing, or the documentation for `addComponent` is wrong or outdated. I suspect that the latter.

Is this the right way to report this? I'll apologize and try another way if not.

**Comment by willeastcott** [comment]
I'm confused. I don't see any reference to pc.ZoneComponent. Can you reload that page after clearing your browser cache?

**Comment by mast4461** [comment]
I cleared the browser cache and reloaded the page, and the reference is indeed gone now. Problem solved.

Here's how it looked earlier today:

![image](https://user-images.githubusercontent.com/3101405/64429414-4282bb80-d0b6-11e9-9b23-5f1407a10aaf.png)
