### ISSUE TITLE
Can't tell which Touch results in a pc.ElementTouchEvent

### ISSUE THREAD

**Issue by Blaizer** [playcanvas/engine#1694]
I'm using `entity.element.on(pc.EVENT_TOUCHSTART, ...)` etc. as a way to check for input events while easily knowing if they are being blocked by some Element in the UI. This works well, but the `ElementTouchEvent` does not send which `Touch` the event corresponds to, only the list of `changedTouches`. When there is more than 1 element in the list, then it's impossible to tell which event is for which touch.

The fix would be to simply add a `Touch` property to `ElementTouchEvent` and set it whenever that object is constructed (a few times in element-input.js).

**Comment by Maksims** [comment]
The way it works, touch events has `touches` property, which is a list of touches that are related to that event. It can be more than one. So you have to iterate through them.
Then each Touch object has `identifier` property - which is a unique identifier of a touch event, that persists through life of Touch object within different events: touchstart, touchmove, touchend.

**Comment by Blaizer** [comment]
The method you described works great for when you subscribe to `app.touch` events, but not `entity.element` events. The difference can easily be seen when I run this:

```
this.app.on(pc.EVENT_TOUCHMOVE, e => console.info("App touch", e));
this.entity.element.on(pc.EVENT_TOUCHMOVE, e => console.info("Element touch", e));
```

When I drag with two fingers at once I get this output:

![image](https://user-images.githubusercontent.com/265623/64930985-6becd580-d874-11e9-8b2b-bbfe79874978.png)

For every one app touch, I get 2 element touches. If you drill down you can see that each element touch has a different x and y and a different element the touch is on top of (not shown).

![image](https://user-images.githubusercontent.com/265623/64931053-19f87f80-d875-11e9-9881-f8002492f5f2.png)

Iterating over changedTouches on `ElementTouchEvent`s would actually lead to processing each touch n^2 times, and it wouldn't give me the information I care about which is the entity that each touch is on top of. So I simply need to know the `Touch` that each `ElementTouchEvent` corresponds to, because one `ElementTouchEvent` corresponds to one `Touch` in the `changedTouches` list, but there's no way to tell which one.
