### ISSUE TITLE
Accessing the DepthMap in WebGL1 vs WebGL2

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#1704]
I am attempting to access the DepthMap from a custom shader (PostEffect) and I am unable to properly grab when falling back to WebGL1. In WebGL2 it works as expected.

### Description

* URL for sample scene: https://playcanvas.com/editor/scene/813310
* Tested on Firefox/Chrome
* Related forum thread: https://forum.playcanvas.com/t/depth-buffer-in-material-shader/9120/6

Tried it in two ways:

1. Enabled the **needsDepthBuffer** property in the PostEffect class. Result:

WebGL1: no depth map is rendered
WebGL2: depth map is correctly rendered

1. Disabled the **needsDepthBuffer** property in the PostEffect class and added a custom pc.Script named **RenderDepth** which is used to incrementCounter() on the depthLayer. Result:

WebGL1: no depth map is rendered unless I enable realtime shadows on a directional light. Then a depthMap is rendered and made available as **uDepthMap** uniform but not for the camera perspective but for the light perspective (which is not what is expected).
WebGL2: depth map is correctly rendered

Any idea if I am doing something wrong?

**Comment by guycalledfrank** [comment]
You should use this code to access identical depth values on both GL1 and GL2: https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/chunks/screenDepth.frag

**Comment by highvrahos** [comment]
Sorry for bumping this up. It seems that only realtime shadows render to depth but from a wrong perspective in WebGL1. I can't find a proper fix for this to make a PR without breaking the current logic on who requests a depth map first.

Any idea why we are unable to grab the depth map in WebGL1? This has been a long standing issue with the engine, having to monkey patch methods to be able to grab the depth map. 

Also the current post process effects requiring depth (e.g. bokeh) don't work when running in WebGL1.

**Comment by guycalledfrank** [comment]
... why do you multiply by zero?

Also, I think you also need to "request" the depth buffer first, basically increment its reference counter. You can copy this code from the particle system: https://github.com/playcanvas/engine/blob/master/src/framework/components/particle-system/component.js#L511

**Comment by highvrahos** [comment]
Thanks for the reply. No, I am not multiplying by zero, sorry, the screen grab was wrong.

You can check the sample project, using either the this.needsDepthBuffer = true flag or a custom script as you say to increment the counter requesting depth ... It works for Webgl2 but not 1.

The issue basically is the behaviour should be the same, thinking either it is a bug or not the correct way in doing it.

**Comment by guycalledfrank** [comment]
Well it seems like your project does cause the depth buffer texture on GL2. I can see all the relevant calls being called and the texture is being bound to your post effect. Maybe try scaling the value.

**Comment by highvrahos** [comment]
Thanks for checking it out, though did that. Played with all the possible values for the camera planes (near/far) and also tried a bunch of different variations of scaling the value. 

It is always full white, the sample project is the default blank PlayCanvas project. Any idea? This seems like a bug.

We have rewritten our post processing stuck to provide WebGL1 fallbacks per user demand, but without access to the depth map we are stuck:

https://twitter.com/PlayingInCanvas/status/1182277741867098123

**Comment by guycalledfrank** [comment]
I just forked your project, multiplied depth by 0.1 and it doesn't look white anymore: https://playcanvas.com/editor/scene/815373

**Comment by highvrahos** [comment]
@guycalledfrank your test project still doesn't work in WebGL1, that is basically what this thread is about. Executing your project in WebGL1 results in full white.

https://launch.playcanvas.com/815373?webgl1=true&debug=true

**Comment by guycalledfrank** [comment]
I think it happens because of the renderTarget check here: https://github.com/playcanvas/engine/blob/master/src/framework/application.js#L415

The origins of this line are forgotten though...
