### ISSUE TITLE
gl.MAX_SAMPLES does not exist in WebGL 1

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#1711]
https://github.com/playcanvas/engine/blob/6bf95cd0b0d66859e537c8c5ad591501dad0b690/src/graphics/device.js#L738

Untick 'Prefer WebGL 2.0' in rendering options and a warning will show in console:

```
" playcanvas-stable.dbg.js:4965 WebGL: INVALID_ENUM: getParameter: invalid parameter name

initializeCapabilities @ playcanvas-stable.dbg.js"
```

See thread: https://forum.playcanvas.com/t/invalid-enum-getparameter-invalid-parameter-name/11147

**Comment by willeastcott** [comment]
It looks like that line was introduced by @c0debon here:

https://github.com/playcanvas/engine/pull/1650/files

However, it seems that maxSamples isn't used anywhere in the engine codebase so I suspect we can just delete that line. But I'll leave this to @c0debon.
