### ISSUE TITLE
Internet Explorer 11 incompatibility "LoadModules is undefined"

### ISSUE THREAD

**Issue by wturber** [playcanvas/engine#1738]
When WASM modules are loaded in a published project Internet Explorer fails while loading with:

```
SCRIPT5009: 'LoadModules' is undefined
__start__.js (153,9)
```

The code on line 152 and 153 is:
   ```
 if (PRELOAD_MODULES.length > 0) {
        loadModules(PRELOAD_MODULES, ASSET_PREFIX, configure);
```
This is produced if you have WASM modules loaded - specifically the new WASM ammo files.  If you remove those modules and use the legacy collision, the project will load and run correctly.

**Comment by slimbuck** [comment]
An error is actually being thrown a little earlier at, __modules__.js(18:25): syntax error due to arrow function expression.

**Comment by slimbuck** [comment]
Please note this issue has been fixed on the editor backend and will go live sometime in the future :)

**Comment by wturber** [comment]
Cool.  I look forward to the release that includes it.  
Thanks.

**Comment by willeastcott** [comment]
This has now been deployed so IE11 should now be able to run published projects with the WASM version of Ammo now. Please reopen this issue if you experience any more problems related to this and we'll take another look. Thanks!
