### ISSUE TITLE
Dynamic batching not working on Firefox for Android and WebGL1

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#1740]
### Description
Dynamic batching is not working when running a PlayCanvas app (launch or build) on Firefox for Android on WebGL 1.0. The batched models will disappear and not render at all.

- Sample project: https://playcanvas.com/project/651432/overview/dynamic-batching
- Firefox for Android v68.2.0
- Related forum thread: https://forum.playcanvas.com/t/dynamic-batching-bug/11319

### Steps to Reproduce

1. Enable dynamic batching on a number of models 
2. Run the app with Prefer WebGL 1.0 checked
3. The batched models will not render on Firefox for Android

**Comment by slimbuck** [comment]
Hi @highvrahos,
Please could you add me to the sample project?
Thanks!

**Comment by highvrahos** [comment]
Done!

Fixed the sample project link as well in the initial post (public project).

**Comment by mvaligursky** [comment]
I tried this on Sony Xperia Z from 2013 using Android 68.9.0 and dynamic batching works well.
Perhaps there was fix in Firefox, and also engine code for batching has changed considerably.

I'll close this for now, please re-open with further details if this can be reproduced again.
