### ISSUE TITLE
Add WebXR support

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1748]
The engine currently supports WebVR. This is being [removed from Chrome in version 80](https://caniuse.com/#search=webvr). [WebXR](https://www.w3.org/TR/webxr/) is being [enabled (not behind a flag!) in Chrome 79](https://caniuse.com/#search=webxr).

Question:
Should the engine retain WebVR support for now and add WebXR support? The engine would then attempt to obtain access to the WebXR API first and fall back to WebVR if not present. Alternatively, WebVR support could be stripped out and WebXR added in its place. The former feels like the correct choice.

**Comment by halvves** [comment]
We could also remove first class WebVR support and leverage something like [webxr-polyfill](https://github.com/immersive-web/webvr-polyfill) to handle the WebVR fallback.

**Comment by slimbuck** [comment]
How much code does WebVR comprise in the engine?

**Comment by willeastcott** [comment]
@halvves Good point!
@slimbuck A few hundred lines maybe.

**Comment by terence-wang** [comment]
Chrome has been released, are there any plans for XR related features to start?

**Comment by Maksims** [comment]
Yes, there are plans to implement in-engine support for WebXR.
