### ISSUE TITLE
Typescript binding for ScriptType incorrect for update

### ISSUE THREAD

**Issue by TheJonRobinson** [playcanvas/engine#1757]
### Description

We're updating our project to the latest `playcanvas.d.ts`, generated as per instructions. Previously we used [@types/playcanvas](https://www.npmjs.com/package/@types/playcanvas) with some tweaks where there were omissions.

We know that script's update function takes a dt, but the types claim it's void so we get:
```
Property 'update' in type 'foo' is not assignable to the same property in base type 'ScriptType'.
  Type '(dT: number) => void' is not assignable to type '() => void'.
```

**Comment by willeastcott** [comment]
I'm guessing [this JSDoc block](https://github.com/playcanvas/engine/blob/master/src/script/script.js#L449) is missing a:

```
* param {Number} dt The delta time since the last frame.

**Comment by willeastcott** [comment]
Do you want to submit a PR yourself? Obviously, it's super-easy for me to fix. But might be useful to go through the process in case you want to make future edits to the runtime. 😄

**Comment by TheJonRobinson** [comment]
Sure thing - I've noticed a few little things, so will do a set.

**Comment by willeastcott** [comment]
Cool beans.
