### ISSUE TITLE
Particle System Bug on Mobile Devices

### ISSUE THREAD

**Issue by saadhaider78** [playcanvas/engine#1758]
**Description**
Particle system is not working correctly on mobile devices, effecting both android and iOS. The particles are generated to the right and they reappear from the left side.
On desktop, it is working correctly.

- Sample project: https://playcanvas.com/project/651970/overview/particle-system-bug
- Build: https://playcanv.as/p/nGNEtWuU/
- Related forum thread: https://forum.playcanvas.com/t/particle-system-buggy/10925/7

**Steps to Reproduce**

- Create a new project
- Add particle system to any entity
- The particle generation on mobile devices will be bugged.

Possible immediate fixes, I discovered:

**For Android Devices:**
If you uncheck the "Prefer WebGL 2.0" in the rendering tab, this issue will be fixed.

**For IOS Devices:**
In the particle system, change the "Sort" mode to camera distance, which essentially makes the particle system use the CPU instead on the GPU, and it will work just fine but the performance hit will be very large.

**Comment by saadhaider78** [comment]
Any progress on this? @willeastcott

**Comment by slimbuck** [comment]
Sorry @saadhaider78 I don't believe anyone has had a chance to look into this one yet.

@ellt92 would you mind taking this one?

**Comment by willeastcott** [comment]
I can no longer reproduce this with the linked build.

iPhone XS:

![image0](https://github.com/playcanvas/engine/assets/697563/8b399aee-3113-48a2-8273-6f3e47a12bf5)

iPhone 14 Pro:

![image0 (1)](https://github.com/playcanvas/engine/assets/697563/738fc01a-aa02-4fa6-b042-6f3aac7f8e36)
