### ISSUE TITLE
Unable to preventDefault in orbit-camera-input-mouse.js 

### ISSUE THREAD

**Issue by velbi** [playcanvas/engine#1761]
### Description

When I scrolled out in orbit camera control, zoom works, but produces some error message.
* ![error](https://user-images.githubusercontent.com/39391128/69838348-8ab91080-1296-11ea-9d92-8d94bbcb1ca9.PNG)
* Chrome
* https://launch.playcanvas.com/475886?debug=true

**Comment by kungfooman** [comment]
You can just remove all occurances of `event.event.preventDefault()`, the better approach is to call `event.stopPropagation()` in e.g. overlay HTMLElement's (to not mix HTML-overlay/PlayCanvas events). You probably copied the code from playcanvas-gltf

**Comment by velbi** [comment]
Thanks @kungfooman, how about  `window.addEventListener("mousewheel", this._wheelHandler, {passive: false});` ? // I just added option passive: false

**Comment by AlbertoMalavasi** [comment]
I think I solved the issue above but I'm not currently able to make a pull request due to an Authentication failed error message.
Can someone please help me?

![Screenshot 2019-12-04 at 11 07 27](https://user-images.githubusercontent.com/36632440/70133519-93d72280-1686-11ea-9620-1ff93103177b.png)
