### ISSUE TITLE
Trigger volume - "trigger" events receive only one entity

### ISSUE THREAD

**Issue by NokFrt** [playcanvas/engine#1769]
According to docs both entities should receive "trigger" events:

> If the pc.Entity does not have a pc.RigidBodyComponent then this collision volume will act as a trigger volume. When an entity with a dynamic or kinematic body enters or leaves an entity with a trigger volume, both entities will receive trigger events.

In reality only the entity with trigger volume receive the events: https://playcanv.as/p/W3zZTK8q/

**Comment by daven89** [comment]
Hello, I'm facing exactly the same bug. The trigger events are raised only on the entity with trigger volume and not in the rigidbody entity too.

**Comment by Maksims** [comment]
Well, docs are wrong here, as in the code there is no second event fired.

https://github.com/playcanvas/engine/blob/master/src/framework/components/rigid-body/system.js#L535-L558

**Comment by daven89** [comment]
Hello Maksims, here you can find the documentation we are talking about. https://developer.playcanvas.com/en/api/pc.CollisionComponent.html

In the table there is both triggerenter from rigidbody to trigger entity and from trigger entity and rigidbody.

In 
![Cattura](https://user-images.githubusercontent.com/5869603/70993445-58981300-20cc-11ea-9256-c97c8569633d.PNG)
