### ISSUE TITLE
The Development tools 

### ISSUE THREAD

**Issue by sheafferusa** [playcanvas/engine#177]
Well, as far as I could comprehend, the frameworkbis opensource but what about the development tool or rather the drag & drop visual designer software? That isn't open source, I guess. Am I wrong?

**Comment by daredevildave** [comment]
That's correct. 

The client engine that covers rendering, animation, input, audio, entity/component system, etc, is open source in this repository.

The playcanvas.com website, including the Editor tools are not open-source.
