### ISSUE TITLE
PlayCanvas profiler crashes on v1.25.0-dev

### ISSUE THREAD

**Issue by Kangsi** [playcanvas/engine#1789]
# Description

PlayCanvas profiler crashes on version 1.25.0-dev.
One of the stats seems to be undefined, causing it to crash.
See the images for more information.

![image](https://user-images.githubusercontent.com/8733899/71350172-042fe000-2571-11ea-9875-53a811a2d24d.png)
![image](https://user-images.githubusercontent.com/8733899/71350227-26c1f900-2571-11ea-8934-83595141a0ae.png)

### Steps to Reproduce

1. Open any project.
2. Launch the app with the profiler option ticked
3. Launch the app with the latest dev engine (v1.25.0-dev)
4. Check the logs.

**Comment by willeastcott** [comment]
If you launch with the dev engine and the profiler enabled, you need to be serving the profile build of the dev engine.

```
npm run build:profiler
```

The output engine should be called `playcanvas.prf.js`

**Comment by Kangsi** [comment]
Thanks for the fast reply. I'll do that. Closing the issue.
