### ISSUE TITLE
GL2 defines not working correctly

### ISSUE THREAD

**Issue by PHou81** [playcanvas/engine#1796]
As discussed in this topic:
https://forum.playcanvas.com/t/depth-buffer-in-material-shader/9120/15

When the project compiles each shader on runtime the GL2 flag isn’t respected. Even though it runs on a WebGL2 context the shaders always fallback on the else branch of the GL2 defines.

Direct link to the fragment shader in question:
https://playcanvas.com/editor/code/657274?tabs=26543414

Direct link to the project with a workaround implemented (separate shaders for GL1 and GL2):
https://playcanvas.com/project/657274/overview/toon-water
Forked from this water tutorial project:
https://playcanvas.com/project/533435/overview/toon-water--tuts-tutorial

Tested on Chrome Version 79.0.3945.88 and Firefox Version 71.0 (64-bit) running on Windows 10.

**Comment by mvaligursky** [comment]
Engine inserts this line when it builds shader from chunks:
#define GL2

and so the chunk based shader (such as basic or standard shader) can depend on GL2 define.

If you write a shader yourself, such as the linked shader: https://playcanvas.com/editor/code/657274?tabs=26543414
the define is not inserted and so you cannot depend on it. We don't currently post-process user supplied shaders to insert defines.

There are two ways you can go around it:
1. insert define to your shader as needed (needs code, as this specific define needs to be only inserted on webgl device). Code similar to this perhaps:
`            if (this.webgl2) {
                var gl2define = "#define GL2\n";
                shaderSrc = gl2define.concat(shaderSrc);
            }`
2. write separate shaders for GL1 and GL2 and use appropriate based on device.
