### ISSUE TITLE
loadFromUrl does not load model if its texture has been already loaded

### ISSUE THREAD

**Issue by NokFrt** [playcanvas/engine#1797]
If a model shares a texture with another model, loadFromUrl() fails to load the model because already loaded asset (the texture) does not fire "load" event.

**Comment by NokFrt** [comment]
There is another problem with models and loadFromUrl():
Everytime I load models with loadFromUrl() a get a lot of these error messages into the console:

Error loading Texture: format not supported: ''. If I set a breakpoint to the place where this message is shown, I will see this:

![obrazek](https://user-images.githubusercontent.com/15905244/71711411-2fcc8900-2e01-11ea-83c3-9ed437fec84c.png)

The model I'm trying to load is super simple with one material and one texture.

**Comment by yaustar** [comment]
Can you provide a repro case for these issues please? That will really help

**Comment by NokFrt** [comment]
I use the engine, so it's hard to provide an example.

The first bug (loadFromUrl() fails to load a model whose texture is already loaded) is obvious. loadFromUrl() loads model's mapping file first. After that it tries to load all materials and textures even if they are already loaded. But if the texture or material is already loaded the load() method will just return  and "load" for that asset won't be fired. This is the problem because the engine is waiting for this event. Engine should check if the requested asset is loaded or not before it calls load().

The second bug (Error loading Texture: format not supported:) happens in every project which loads models with loadFromUrl() so it can be seen in for example here: http://playcanvas.github.io/#camera/orbit.html
