### ISSUE TITLE
Shadows do not work correctly with baked lights

### ISSUE THREAD

**Issue by NokFrt** [playcanvas/engine#1799]
Here is a simple project which demonstrates the issue: https://playcanvas.com/project/657746/overview/wrong-shadows-in-lightmaps

There is a baked directional light, 2 boxes and 2 planes. The boxes and the planes are lightmapped, the boxes cast shadows to lightmap and the planes receive shadows, but if you run the project, you will se this:

![obrazek](https://user-images.githubusercontent.com/15905244/71682711-bf861f00-2d90-11ea-8110-114a87620ed4.png)

**Comment by NokFrt** [comment]
There is also another problem with baked light on Android phones but I'm not able to reproduce it in a simple sample project, but I can post a link to my game where it's happening. I use one baked directional light. There are no more lights. The light should affect non lightmapped objects (light.affectDynamic = true). It works in desktop browsers but not on Android. On Android, there are all non-lightmapped object affected only by scene's ambient color but the light doesn't affect them at all.

**Comment by mvaligursky** [comment]
Thanks for reporting this. I fixed the issue with culling of objects when directional shadow map is generated, that fixed the issue on first screenshot (new engine with a fix should be out in a few days). I'm not sure about the second issue, that seems unrelated, and will be investigated separately.

**Comment by willeastcott** [comment]
We fixed the problem with some objects being culled from the baked lightmaps and that was deployed with engine [v1.24.6](https://github.com/playcanvas/engine/releases/tag/v1.24.6). For the second issue, please open a new issue.
