### ISSUE TITLE
Basis depends on Promise API which is not present in IE11

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#1811]
Currently, the Basis module (both basis.js and basis.wasm.js) contains calls to the Promise API which is not available in IE11. To release Basis support officially, we should restore IE11 support.

Suggestions:

1. Since this problem doesn't affect the Ammo module, could this problem be avoided by compiling differently with Emscripten?
2. If we can't factor Promise API calls from the module code, we could possibly build a small Promise polyfill library into basis.js and basis.wasm.js.

**Comment by slimbuck** [comment]
Emscripten had introduced code which broke IE compatibility. That has now been resolved and we are using updated modules which work on IE.
