### ISSUE TITLE
Normals aren't normalized

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#1818]
The shader chunk responsible for unpacking normal map vectors doesn't re-normalize the sampled vector. This causes incorrect lighting especially for specular in shaders with metalness.

An example of the difference that normalizing normals will make in some circumstances is given below. At the top normals are normalized at the bottom they're not.

![normals_diff](https://user-images.githubusercontent.com/11276292/72459891-aedb9d00-37c3-11ea-818f-3da6a12eb3da.jpg)

**Comment by guycalledfrank** [comment]
Note that normals are intentionally non-normalized, because:

- This effecitively performs proper diffuse lighting minification (i.e. minified normals blended together in the distance yield mixed, possibly weaker response, as different microfacets are blended together - this is correct)

- It is also used for Toksvig specular antialiasing approach

The "incorrect lighting" is likely correct - you should compare to a supersampled result. If the surface has many small bumps, these shouldn't be simply skipped, but will average together.

**Comment by slimbuck** [comment]
Hi @guycalledfrank,

Ahh indeed, thanks very much for the info!

The issue we have is that we're busy adding support to Playcanvas for basis compression and require 2 component normal maps since 3 component tangent space normal maps have terrible quality under basis. This has resulted in the discrepancy in the screenshots above.

So ideally we'd do as suggested in the article you link and generate a togsvig roughness map. This would also solve the problems where normal maps store non-unit vectors (which actually seems quite common and I suspect is causing incorrect diffuse and specular lighting in Playcanvas).

Either way, we really need 2 and 3 component (compressed and uncompressed) normal maps to have the same lighting results.

If you have any suggestions or comments on how we could achieve this I'd love to hear!

**Comment by slimbuck** [comment]
Reopening

**Comment by guycalledfrank** [comment]
There is already support for 2-component normals:
https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/chunks/normalXY.frag
https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/standard.js#L944

Just make sure to set the corresponding flag on the material.

Because PC allows using any (e.g. runtime-generated) maps, I chose to use the runtime (not precomputed) version of Toksvig.

**Comment by slimbuck** [comment]
Yes that's all working, however:
> This has resulted in the discrepancy in the screenshots above.

**Comment by guycalledfrank** [comment]
What exactly are you comparing to what? For correct comparison what you need is a highly supersampled image, downsampled to normal size (e.g. render 32x and shrink back). This is what any antialiasing is ultimately trying to solve and this is why small specular highlights don't simply disappear:

![image](https://user-images.githubusercontent.com/7008423/72523211-60380c80-3870-11ea-8168-9a8b33b69f66.png)

When your eye is used to see cheap CG gfx, you'd think first image is "correct". However, supersampling the first image will yield the result the looks more similar to the second image, as many small bright spots get averaged.

If you really want the oily-shiny look of the first image, you need to realize that this shininess comes from surface roughness and reduce it (make normal map flatter).

The real problem with non-normalized normals though is that when using heavy compression, the compression arifacts mix with the desired denormalization and can make it look messy - in which case normalization is preferable.

In fact, you can't find proper variance from a 2-component normal, so I'm fine with patching normalMapXY.frag - but don't change normalMapXYZ.frag.

**Comment by slimbuck** [comment]
Sorry I am obviously not being clear enough.

The issue is that 3 component normal maps currently use toksvig and 2 component normal maps don't. The difference in appearance between them is a problem. We can't have scene lighting change drastically when the user enables texture compression on a normal map.

I am not suggesting getting rid of toksvig, but rather trying to figure out the best way of supporting toksvig in both scenarios. (In fact the 2-component case is arguably the most important for us since clients need high quality compressed textures).

We could do as the author suggests and generate a toksvig glossiness map from normals in the editor. We would then rely on the glossiness map for specular antialiasing in both 2 and 3 component scenarios.

This would simplify the runtime shaders (since we can remove the toksvig code).

This could be more work for the authors though.

**Comment by guycalledfrank** [comment]
>We can't have scene lighting change drastically when the user enables texture compression on a normal map.

Breaking all existing projects by adding normalization isn't a solution for me either.
The best thing to do is to add a separate material option which would be off for all existing projects and on for newly created materials.
