### ISSUE TITLE
Add start and end frame support to particle system texture animations

### ISSUE THREAD

**Issue by Blaizer** [playcanvas/engine#1844]
Right now particle system texture animations support cutting the texture up into tiles of any size, but they only support animating through every tile on the texture. If we could specify a start and end frame (so that the animation goes through a limited, contiguous section of what it would normally) we could much more easily "atlas" our particle textures without having to manually make quads to target different parts of a texture. This would allow us to much more easily optimize our game assets, especially for particle-heavy games.

Here are the current attributes for animation support. 2 extra attributes would be added here to control the start and end frame of the animation.
![image](https://user-images.githubusercontent.com/265623/73229676-8479de80-41ca-11ea-9aae-3aeb361d4849.png)

**Comment by slimbuck** [comment]
Wouldn't it suffice to add a single attribute 'Start Frame'?

**Comment by Blaizer** [comment]
Yes, sorry. Frame Count would let you do what End Frame would otherwise do, so adding Start Frame alone would suffice.
