### ISSUE TITLE
Hardware Instancing

### ISSUE THREAD

**Issue by highvrahos** [playcanvas/engine#1846]
I am aware that hardware auto-instancing has been removed from the engine a while ago, to be replaced by the more robust CPU batch instancing solution now available.

I can see though that per mesh instance hardware instancing is still available in the **pc.ForwardRenderer** class. It seems to be calling the right WebGL methods to forward the per instance vertices to the vertex shader using a divisor etc.

I've tried to write a simple example that makes use of hardware instancing on a single model, though I was unable to make it work:

https://playcanvas.com/editor/scene/868464

@Maksims @guycalledfrank I can see you were involved in the development of the autoInstancing feature back then, do you know if right now what I attempt works against the current Playcanvas engine version? 

Also do you happen to have an example or you can take a look to see what I am doing wrong?

I know that we will have to patch the engine in a place or two (Standard material/program to collect the attributes etc), but at the end it might make for a useful PR.

CPU instancing is generally more useful I agree. But I think there is a place for hardware instancing, if it's relatively easy to configure. For example grass on arch vis could greatly benefit from decreased loading times and memory usage.

**Comment by mvaligursky** [comment]
I'm investigating the possibility of adding hardware instancing to the engine at the moment, stay tuned.

**Comment by highvrahos** [comment]
That's great, let me know if you need any help in testing.

**Comment by willeastcott** [comment]
Presumably this can be closed now, @mvaligursky?

**Comment by mvaligursky** [comment]
yes, the feature is working now and should be released shortly.
