### ISSUE TITLE
Mapping issue with texures loaded from external servers and WebGL 1

### ISSUE THREAD

**Issue by axellent68** [playcanvas/engine#1847]
Loading texture images from an external source and putting them on models lead to weird projection on browsers with WebGL 1 like Safari, Edge und IE. Chrome and Firefox are fine.
<img width="843" alt="correct" src="https://user-images.githubusercontent.com/49154535/73456311-f9d3e380-4371-11ea-91e1-92dd23d64c2c.png">
<img width="925" alt="weird" src="https://user-images.githubusercontent.com/49154535/73456312-f9d3e380-4371-11ea-8d6a-e80856d2e22e.png">

1. Load a texture from a external source, put it via script in diffuse channel and add it to model:
```
if(imageSrc){
            var shape = clone.findByName("imageShape");
            var material = shape.model.meshInstances[0].material;
            var newMaterial = material.clone();
     
            this.app.assets.loadFromUrl(imageSrc, "texture", function (err, asset) {
                asset.ready(function (asset) {
                var texture =   asset._resources[0]; 
                newMaterial.diffuseMap = texture;                
                shape.model.meshInstances[0].material = newMaterial;
                newMaterial.update();
            });
            });      
      }
```
2. Uncheck "Prefer WebGL 2.0" at "Rendering" or view it on Safari, Edge or IE
3. Launch preview

**Comment by slimbuck** [comment]
Hi @axellent68,

If possible, could you please create and share a cutdown example project demonstrating the issue? If this is an editor project please add myself with read access.

Thanks!

**Comment by axellent68** [comment]
Ok, did it. You'll find the code of loading a new texture and getting the URL from stations.json in root.js

**Comment by slimbuck** [comment]
Hi @axellent68,

According to https://www.khronos.org/webgl/wiki/WebGL_and_OpenGL_Differences#Non-Power_of_Two_Texture_Support webgl 1 only has limited support for non-power-of-two textures.

In your case I would suggest either resizing the image to power of two or enabling clamp address mode.

It's possible the engine or editor could be more helpful in cases like this, not sure.

Thanks!
