### ISSUE TITLE
Can't use vUv1 inside a shader

### ISSUE THREAD

**Issue by benunbnd** [playcanvas/engine#1851]
When using vUv1 inside of a fragment shader, it is undefined.

```
ERROR: 0:185: 'vUv1' : undeclared identifier 
```

There doesn't seem to be a way of passing the data into the shader.

**Comment by guycalledfrank** [comment]
Try material.forceUv1?
https://github.com/playcanvas/engine/blob/master/src/scene/materials/standard-material.js#L168

**Comment by mvaligursky** [comment]
see the responses here as well
https://forum.playcanvas.com/t/get-uv1-inside-of-a-shader/11957/4
