### ISSUE TITLE
`event.scroll` in `pc.EVENT_MOUSEWHEEL` always 0 in Firefox

### ISSUE THREAD

**Issue by Ivolutio** [playcanvas/engine#1858]
### Description

In Firefox the `event.scroll` property always equals 0. It does work properly in Chrome and Edge. 

```javascript
MouseInput.prototype.onMouseWheel = function (event) {
    console.log(event.wheel); //always prints 0 in firefox
    this.orbitCamera.distance -= event.wheel * this.distanceSensitivity * (this.orbitCamera.distance * 0.1);
    event.event.preventDefault();
};
```

### Steps to Reproduce

1. Create new Model Viewer project
2. Open it in Firefox
3. Try zooming by mouse scrolling

Forum post: https://forum.playcanvas.com/t/scrolling-not-working-in-firefox/12010

CC: @highvrahos

**Comment by Ivolutio** [comment]
When will this be functional in the editor version?

**Comment by willeastcott** [comment]
I'll aim to deploy a patch release to the engine containing this fix tomorrow.
