### ISSUE TITLE
Frustum Culling API

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#187]
Think of nice Frustum Culling API:  
1. Control culling per camera.
2. Detect if entity is culled.
3. Enable/disable culling for entity.
4. Hierarchal culling: culling happens on AABB of entities (which include all children), so if whole entity is culled, no culling needs to be checked for children. Detecting culling have to respect parents too.

Here are example use cases:
- Someone has car model with some entities inside (turrets, wheels, driver), it is required to cull whole car not partially, and detect when car is culled in script so to prevent any scripts related to rendering (script animations, or particles, etc).
- Multiple camera culling for shadow rendering where shadow camera as well as any active cameras has to be respected during depth map rendering.
- Simple game like tanx has single big level, so dev will be sure that level don't have to be ever culled, or UI elements for example, so to optimise will turn of culling on those entities.

**Comment by willeastcott** [comment]
We really need a fast, reasonably general purpose, space partitioning scheme to do efficient frustum culling of many meshes.

**Comment by daredevildave** [comment]
Is this solved with camera.frustumCulling property?

**Comment by guycalledfrank** [comment]
Partially.
Control culling per camera: yes (camera.frustumCulling);
Detect if entity is culled: no such mechanism yet;
Enable/disable culling for entity: yes (meshInstance.cull);
Hierarchal culling: not yet.

**Comment by daredevildave** [comment]
Marking this as closed as camera's support culling. Suggest we add new ticket for additional features.
