### ISSUE TITLE
Rotation with slider

### ISSUE THREAD

**Issue by velbi** [playcanvas/engine#1871]
### Description

* URL:
https://playcanvas.com/project/626119/overview/setlocaleulerangles-test

* As far as I'm concerned, when basis axis is moved in euler angle, the others two are moved(local).
but it's not, z-axis is always fixed.
So if i move the y-axis 90 degrees, the x-axis and the z-axis will collapse
**Because the z axis did not move.**

* I refer to [this link](http://www.ctralie.com/Teaching/COMPSCI290/Materials/EulerAnglesViz/), and the roll(z-axis) should move like this.

### Steps to Reproduce
0. default
![11](https://user-images.githubusercontent.com/39391128/74308252-124cf080-4dab-11ea-8445-8386ba352f83.png)
1.  set Y-axis 90°
![22](https://user-images.githubusercontent.com/39391128/74308254-137e1d80-4dab-11ea-8829-2fa40dd8136b.png)
2.  set Z-axis **(same as X-axis)**
![333](https://user-images.githubusercontent.com/39391128/74308258-14af4a80-4dab-11ea-8d10-82edc499ae27.png)

**Comment by yaustar** [comment]
This is due to the order that the rotations are applied in. I think PlayCanvas applies the rotations in a ZYX order meaning that the Z rotation is done first, then the Y and finally the X.

Sounds like you want to be using `rotateLocal` instead or create your own order of rotations and calculate you own quanterion.

Here is an example of using `rotateLocal` https://playcanvas.com/project/665567/overview/setlocaleulerangles-test

**Comment by velbi** [comment]
Thank you! @yaustar 

Actually, I knew RotateLocal function
But there's a problem with using it with the slider.
In your example, default slider value like below but move the slider x,y,z and returning to default(like capture image), the model is different from its initial appearance.
This is why I used setLocalEulerAngles.
![default](https://user-images.githubusercontent.com/39391128/74390758-92c02f80-4e45-11ea-9473-edb5592ec5a3.png)

It would be nice if the z axis could move in function. Is there any other way?

**Comment by yaustar** [comment]
If you want exactly the same behaviour as the one in the example you have shown (which is a XYZ order), you have to calculate the rotation quaternion yourself. 

Example: https://playcanvas.com/editor/scene/874765

```
    var setRotationXYZ = function() {
        xQuat.setFromEulerAngles(x, 0, 0);
        yQuat.setFromEulerAngles(0, y, 0);
        zQuat.setFromEulerAngles(0, 0, z);
        
        finalQuat.setFromEulerAngles(0, 0, 0);
        finalQuat.mul(xQuat).mul(yQuat).mul(zQuat);
        
        box.setLocalRotation(finalQuat);
    };
```

**Comment by velbi** [comment]
Thanks @yaustar !
This is what I really wanted.
Also It worked well in my project!

**Comment by velbi** [comment]
@yaustar 
I found when I turn the y-axis 90, the x-axis and z-axis become identical.
I think this should have no gimbal-lock.. because it use quaternion. 
Can you help me again?

**Comment by yaustar** [comment]
This will have gimbal lock as we are really using Euler Angles. The quaternions are used to rotate the entity in order therefore gimbal lock still applies.

**Comment by velbi** [comment]
Thank you for your answer, but I didn't know it would be this difficult to rotate like the link example without a gimbal lock. Let me reopen the issue.

**Comment by yaustar** [comment]
The example you provided also has gimbal lock 

![image](https://user-images.githubusercontent.com/16639049/75673074-ffc32a00-5c79-11ea-8312-dd46c500fcf3.png)

**Comment by yaustar** [comment]
Looking at the example again, it does a YXZ rotation. 

I'm now updated the example to do the same https://playcanvas.com/editor/scene/874765

**Comment by velbi** [comment]
Thanks @yaustar 
That example is very helpful.
