### ISSUE TITLE
Integrate metadata for SpectorJS

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#1877]
SpectorJS has this feature to add metadata which should be used by PlayCanvas engine - perhaps in Profiler mode. But perhaps also in Editor.

```
You can simply add custom data to the capture by adding a special field named __SPECTOR_Metadata to your WebGLObjects.

var cubeVerticesColorBuffer = gl.createBuffer();
cubeVerticesColorBuffer.__SPECTOR_Metadata = { name: "cubeVerticesColorBuffer" };
This will enable the visibility of your custom name in your capture.
```

see more here: https://github.com/BabylonJS/Spector.js

**Comment by willeastcott** [comment]
That does sound super-useful actually. We certainly could leverage this in the debug build.
