### ISSUE TITLE
Emissive Intensity not affecting emissiveMap without Color

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#188]
Currently `emissiveIntensity` only affects emissive result if `emissive` (color) is specified, but if `emissiveMap` is specified without tint, then it wont affect emissive result.

**Comment by willeastcott** [comment]
Hey @guycalledfrank - do you agree this is a bug? I just verified it. Does seem a bit odd that it doesn't affect just the map...

**Comment by guycalledfrank** [comment]
I added intensity as a workaround to inability to set HDR color in color picker, it's basically used as color multiplier. It's not really a bug... I just wouldn't show the intensity slider, unless Tint is enabled. I can, however, make intensity work as separate color-independent intensity, but it would likely make code more complicated, and I'm not sure it's worth it.

**Comment by Maksims** [comment]
I think it should affect color or/and texture in all cases. Otherwise currently in order to affect texture, you need to enable tinting, which is a bit wasteful in this case.

**Comment by guycalledfrank** [comment]
Alright, alright
Fixed in https://github.com/playcanvas/engine/pull/655
