### ISSUE TITLE
Type hinting of `ScriptType` created with `pc.createScript` within prototypes

### ISSUE THREAD

**Issue by Glidias** [playcanvas/engine#1887]
Using the Playcanvas jsdoc typings tsds, I can't get type hinting of `this` to link to `pc.ScriptType` within the method prototypes (on visual studio code, but on online editor it appears fine though), unless i manually jsdoc `var ScriptName = pc.createScript()` with `@type {typeof pc.ScriptType}`.

The thing is: shouldn't this https://github.com/Glidias/engine/commit/5383d8894788c189a99b5d516ede086fbf3c9ff6 be done instead of the jsdoc for typescript typings?

The question though is why the online Playcanvas code editor type-hinting seems fine but not on other ide setups?

Issue:

The problem with using my `typeof ` method though, is that that you lose the ability to add-on `.attributes` and other properties alongside with the created function object.

Here's a possible solution to the above:

Why not define the return type of object created by pc.createScript as:

`@type {typeof pc.ScriptType & {attributes: pc.ScriptAttributes}}`

The type hinting works well for both static attributes and "this" within prototype method implementations using this approach. But having it fare well with ts-check won't work well though with this method. THis is purely to get intellisense to work "nicely".

**Comment by willeastcott** [comment]
I believe that #1908 fixed this. Can you confirm @Glidias?

**Comment by Glidias** [comment]
Not too sure. This isn't deployed to NPM or officla editor yet, right?  I have my issues from looking through the code though which i mentioned in the other issue.

**Comment by willeastcott** [comment]
That's correct. This will go out in the next few days as v1.26.0.
