### ISSUE TITLE
Box-projected cubemaps: rotation

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#189]
Currently Box-Projected CubeMaps can't be rotated.  
Means that if you have one same room with same cubemap on them, you cannot simply duplicate that room and rotate, as box projection won't inherit rotation from room, nor it will work with non-parallel walls which creates loads of restrictions on where box-projection can be used.

Consider adding vec3 (euler) of rotation for box-projected cubemap, additionally to inheriting world rotation of entity.

**Comment by willeastcott** [comment]
Another cubemap related feature request to consider, @slimbuck.

**Comment by Maksims** [comment]
Just to note, there can be 2 modes: local and world in terms of transform, both have uses.

**Comment by willeastcott** [comment]
Closing because we now have `Scene#skyboxRotation` (which is a `Quat`):

https://developer.playcanvas.com/api/pc.Scene.html#skyboxRotation
