### ISSUE TITLE
render sprite in 3d space?

### ISSUE THREAD

**Issue by kenhoff** [playcanvas/engine#190]
Hey all - is there a way to render a sprite in 3D space? I've seen [PlayCanvas' Sprites script](https://github.com/playcanvas/sprites), but it looks like that only allows 2D control.

**Comment by willeastcott** [comment]
Sure. One option is to create an entity, add a model component with type set to 'plane'. You can then orient it however you like using the entity.setEulerAngles/setRotation functions.

**Comment by kenhoff** [comment]
Ah thanks, I didn't realize there was a "plane" model. Now I just have to figure out how to attach a texture/sprite to it, but I'll reopen if I have issues.
