### ISSUE TITLE
Support ES6 script classes

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/engine#1907]
JavaScript introduced the [`class`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) keyword in back in 2015 with the release of ES6. Many top JS libraries, such as `React`, have made classes an indispensable language feature when they introduced support for extending base classes, e.g. `extends React.Component` (instead of using ES5-style `React.createClass()`). In fact, `React` removed support for `React.createClass()` entirely in 2017 in favor of classes. Today, classes are a fundamental part of JavaScript, and many new JavaScript devs don't remember a time before classes.

We don't propose PlayCanvas drop support for `pc.createScript()` but introduce the option of writing ES6 script classes (i.e. `extends pc.ScriptType`). We're a strong believer in letting devs choose the best tool for their job. Example:

```javascript
class CameraController extends pc.ScriptType {

    initialize() {
        // initialize code called once per entity 
    }

    update(dt) {
        // update code called every frame
    }
}
```

Almost all browsers natively support classes (only exception being IE). And if a dev wishes to have both classes and IE-support, then ES6 code (just like TypeScript) can easily be transpiled to vanilla ES5 - making it an non-issue.

![image](https://user-images.githubusercontent.com/255073/76161628-74dca680-6135-11ea-8500-a9f8ed301cbd.png)

**Comment by Maksims** [comment]
From the early beginning, all features of PlayCanvas were intentionally kept ES5, to support all WebGL platforms, without exceptions. Even oldest iPhone 5S (first iPhone to support WebGL), is still supported.

Perhaps this worth a bigger discussion, as introducing features that can encourage developers to reduce their user support - has an associated cost.

**Comment by aidinabedi** [comment]
Thank you @Maksims. Again I wish to emphasize that you don't need to reduce user/browser support. Transpiling (or just compiling as its often also referred to) from ES6 (or later) to ES5 is common practice. [The `google-closure-compiler` PlayCanvas itself uses supports it](https://github.com/google/closure-compiler/wiki/ECMAScript6#transpilation).

For example, `Babylon.js` is entirely written in TypeScript but is compiled into JavaScript ES5 without losing any user support. I'm not saying PlayCanvas should be re-written, just that the API shouldn't restrict which language version you (as a developer) can use.
