### ISSUE TITLE
Robostorm and After The Flood demos do not work in Firefox

### ISSUE THREAD

**Issue by urbenlegend** [playcanvas/engine#1912]
### Description

Robostorm and After The Flood demos do not work in the latest Firefox (73.0.1 as of this writing). Both demos get stuck during loading and the Javascript console displays `TypeError: 'prototype' property of Audio is not an object playcanvas-stable.min.js:734:171`

### Steps to Reproduce

1. Go to https://robostorm.io/ or https://playcanv.as/p/44MRmJRU/
2. Verify that loading is stuck
3. Open Javascript console with Ctrl-Shift-K and observe message about Audio.

WebGL Report screenshots
![image](https://user-images.githubusercontent.com/241316/76270092-3a583400-6231-11ea-8eaa-6626845c1193.png)
![image](https://user-images.githubusercontent.com/241316/76270121-55c33f00-6231-11ea-8d56-47cea0d70e1e.png)

**Comment by mvaligursky** [comment]
We've tried to reproduce this, using the same version of Firefox on both Mac and Windows 10, but both links work correctly without a problem. Do you have any plugins which could perhaps block some functionality / downloads?

**Comment by urbenlegend** [comment]
Ah thanks for the hint. I didn't expect it to be related to add-ons, but apparently the [KDE Plasma Integration Addon](https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/) breaks PlayCanvas.

I am not quite sure what's going on as the addon isn't supposed to block anything but rather integrate with the KDE desktop. It may be because I am currently trying out PlayCanvas in Windows 10 where there is no KDE. I have the KDE addon installed because Firefox automatically syncs addons between my Windows and Linux desktops.

Disabling the addon makes PlayCanvas work.

**Comment by willeastcott** [comment]
You might want to report this to KDE. 😄

**Comment by urbenlegend** [comment]
> You might want to report this to KDE. 😄

It appears someone has beat me to the punch! https://bugs.kde.org/show_bug.cgi?id=414512

**Comment by willeastcott** [comment]
Haha, nice. 👍
