### ISSUE TITLE
Particle System Emitter Extent Value Decrease Does Not Update Properly

### ISSUE THREAD

**Issue by 2percenter** [playcanvas/engine#1914]
When adjusting the emitterExtents values for a particle system, there is some inconsistency in the way the update appears visually.

If you decrease the size of the extents, the system appears to react as expected. If you _increase_ the size, however, the system does not refresh in the same way. The response varies depending on various selections made to the particle system (pre-warm, depth write, etc), but always remains much smaller than expected.

I created a [simple test project](https://playcanv.as/p/kUhqSSU1/) where a red particle system is at 5 x 5 x 5. When you press the "START" button, the red system shrinks down to zero over five seconds and it behaves as expected. After five seconds have passed, a blue system begins to expand from zero to the same 5 x 5 x 5 dimensions. The particle system visually remains a negligible size, even though the console shows that the emitter extent properties have achieved the desired 5 x 5 x 5 dimensions. (See specific directions below.)

This issue was discussed on the [forums](https://forum.playcanvas.com/t/changing-particle-system-extents-behaves-strangely/12264/5) and using the reset and rebuild methods were suggested. This does make the system resize appropriately, but a visual flash or similar effect is seen when the system repaints using these commands, or no change is seen until the extent size remains static for long enough. (The visual response is dependent on various particle properties like opacity, etc).

_Increasing the dimensions of a particle system's extents should work the same as decreasing the dimensions._

**Directions for Using Test Project**
1. Observe that the red particles extent to the 5x5 "floor" and "ceiling" objects.
2. Press the START button.
3. Observe the red particle system shrink.
4. After five seconds, the blue particle system begins to expand from  0 x 0 x 0 to the same 5 x 5 x 5 dimensions the red system started with.
5. The blue expansion will last 5 seconds. The final dimensions of the emitterExtents properties can be viewed in the console.

**Comment by ellt92** [comment]
Hi 2percenter,

Thanks for creating a test project. I've just tested this and it only seems to occur when using the GPU path for the particle system. It looks like there may be a bug with how the the particle positions are calculated in the shader.

I'll take a closer look at whats going on here.
