### ISSUE TITLE
Star Lord demo does not work properly on HTC One

### ISSUE THREAD

**Issue by SquareLi** [playcanvas/engine#192]
Device Info:

Android version: 4.4.2
Software number 5.12.502.2
ualcomm® Snapdragon™ 600

![screenshot_2015-03-23-20-42-34](https://cloud.githubusercontent.com/assets/1891471/6804797/0097cc0e-d216-11e4-88ca-bb05a99bd915.png)

**Comment by Maksims** [comment]
Same problem on One Plus One.

**Comment by willeastcott** [comment]
Ah, so it seems the common thread is the Qualcomm Adremo family of GPUs. One Plus One is an Adreno 330. @Maksims can you provide the http://webglreport.com/ output for your phone?

**Comment by Maksims** [comment]
One Plus One
![screenshot_2015-03-24-16-07-27](https://cloud.githubusercontent.com/assets/636263/6808380/83b289f0-d24b-11e4-8ee6-081eac3e76c9.png)

**Comment by willeastcott** [comment]
So looks like it's not using the EXT_shader_texture_lod code path. But there are 16 textures supported in the fragment shader which should be sufficient. @guycalledfrank any ideas for figuring out what's going on here? It helps that @Maksims has a device that exhibits the problem.

**Comment by willeastcott** [comment]
Hey @Maksims, a bunch of GLSL fixes have been committed recently. Might be worth republishing Star-Lord against the latest engine and verifying this is still a problem (I suspect it is).

**Comment by Maksims** [comment]
@SquareLi please try this build: http://playcanv.as/b/2fAvxRc2
And let us know if problem still persist.
I've received update on One Plus One, so now it works all well, doesn't means issue is gone.

**Comment by willeastcott** [comment]
@SquareLi Can you confirm if this is now fixed? Would be cool to close the issue. :smile:

**Comment by SquareLi** [comment]
@willeastcott  Sorry for the late response. Yeah, the new build works good for me.
