### ISSUE TITLE
Allow loading of assets without proper file extensions

### ISSUE THREAD

**Issue by Ivolutio** [playcanvas/engine#1928]
I am trying to load files from my database where they do not keep their file extensions. When loading this as a model the extension is `.com/_________`. 

It would be nice to have an option to set a fixed extension type when calling `loadFromUrl`, or maybe take this from the filename property? (using v1.26.0-dev revision 08dce38 for gltf support)

**Comment by slimbuck** [comment]
Hey @Ivolutio,

Is this https://github.com/playcanvas/engine/blob/master/src/asset/asset-registry.js#L474 what you need?

**Comment by willeastcott** [comment]
Let's assume that it is. @Ivolutio, if I am mistaken, please re-open the issue. Thanks!
