### ISSUE TITLE
Scripts containing ES6 Class are not properly parsed

### ISSUE THREAD

**Issue by hrmoller** [playcanvas/engine#1934]
### Description

First off it is really great to see some work being done towards enabling ES6 classes in PlayCanvas and with the release of 1.26.0 it seems as we're getting closer but one small step might be missing.

At least it seems as the ES6 classes are not being parsed properly by the engine. Also it is not possible to attach a ES6 class script to an Enity.

Tested on a MacBook Pro 16" with fully updated macOS. Verified in Chrome Canary and Safari.

Screenshots that might help clarify the issue a bit:
![Screenshot 2020-03-25 22 27 41](https://user-images.githubusercontent.com/645472/77588146-9685ae00-6ee9-11ea-8f86-63a00db873f7.png)
![Screenshot 2020-03-25 22 27 50](https://user-images.githubusercontent.com/645472/77588149-984f7180-6ee9-11ea-81c0-39e04294c9be.png)
![Screenshot 2020-03-25 22 28 26](https://user-images.githubusercontent.com/645472/77588150-98e80800-6ee9-11ea-97b3-3519099ddd9d.png)

### Steps to Reproduce
1. Fork this project https://playcanvas.com/project/668763/overview/es6-script-tests
2. Create a new Entity in the Hierarchy
3. Try to attach the es6-script to the newly created Entity (not possible)

**Comment by Glidias** [comment]
This is what happens for me when I click on Parse:
![image](https://user-images.githubusercontent.com/190195/77780745-6f68e100-708f-11ea-9ad1-68a961a3b82b.png)

**Comment by willeastcott** [comment]
ES6-class support is just an engine-only feature for now. The Editor has yet to be updated to parse ES6 scripts. For now, if you're using the Editor, stick with ES5 scripts. Hopefully, we can implement this into the Editor soon but I don't have an ETA just yet.

**Comment by hrmoller** [comment]
@willeastcott OK, thanks for clarifying this. Fingers crossed😊

**Comment by willeastcott** [comment]
This is now fixed. Try again and let us know if you have any problems. Note the code example in the API reference for how to define ES6-based scripts:

https://developer.playcanvas.com/en/api/pc.html#registerScript
