### ISSUE TITLE
Loading glTF with external assets

### ISSUE THREAD

**Issue by godiagonal** [playcanvas/engine#1936]
### Description
I am trying to use the glTF support added in 1.26.0 but run into problems when loading `.gltf` files with references to external assets such as bins and images. The assets are referenced via URI and placed "side-by-side" the `.gltf` as such:

![image](https://user-images.githubusercontent.com/4249058/77760184-3cdeca00-7036-11ea-8674-ae807aa830e0.png)

When i run `app.assets.loadFromUrl("path/to/model.gltf", "container", function (err, asset) {})` the callback is never fired and I get a bunch of 404 results in the network log. I see two issues here:

1. Instead of fetching external assets using the same base path as the loaded `.gltf` file, the engine tries to load the assets from the site root. This is the result in the network log:
![image](https://user-images.githubusercontent.com/4249058/77760084-1c167480-7036-11ea-8370-9cc899649f4b.png)
I suggest a base path based on the `.gltf` path is automatically prepended to all external asset requests since the [glTF 2.0 spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#gltf-basics) says external files should be stored side-by-side the `.gltf`.

2. The callback of `app.assets.loadFromUrl(...)` is never fired when the external asset requests fail. I would assume the callback should be fired with an `err` argument in this case.

### Steps to Reproduce
1. Play the project https://playcanvas.com/project/673806/overview/gltfpathproblem
2. Note that the embedded `.gltf` loads correctly
3. Open network log and check how requests for external assets have failed

**Comment by willeastcott** [comment]
Try GLB instead. Unpacked glTF is not supported in the Editor (yet). Please also note that we'll soon update the Editor to convert FBX/OBJ/DAE to GLB. And the model component will support those GLB assets. So while the engine work is in place now, we have some work still to do on the Editor to finish the integration.

**Comment by godiagonal** [comment]
GLB parsing works great but is not sufficient in my case. I'm working on an application that has to be able to load glb, embedded gltf and unpacked gltf. I'm just using the engine for this project, not the editor, and I'm getting the same error results as displayed in my editor-made example.

To me this seems like an engine problem rather than an editor problem. Looking at the code `GlbParser.parseAsync` has no knowledge of which path the gltf file was fetched from, giving it no way to figure out where external assets are located.

**Comment by slimbuck** [comment]
Hi @godiagonal, I believe @willeastcott just meant that GLB support was our first priority and is officially supported right now. However we're working on getting GLTF working in the engine too!

**Comment by godiagonal** [comment]
I see, thanks for the clarification!
