### ISSUE TITLE
Getting static attributes to work correctly in Typed Definitions

### ISSUE THREAD

**Issue by Glidias** [playcanvas/engine#1939]
https://github.com/playcanvas/engine/pull/1908#issuecomment-603175894

Summary of 2 main issues:

1) `this.attributes` within instance scope should not be type-hinted/sensed. Such a property should not exist.
2) ScriptClass.attributes missing typehinting/intellisense, not recognising availability of `static readonly` property on class itself. Somehow, @static and @readonly in jsdoc doesn't translate itself to recognising something being a static property that should not exist under `this` (see 1)

![image](https://user-images.githubusercontent.com/190195/77421393-bd1ee880-6e06-11ea-8837-01575a83057e.png)

**Comment by willeastcott** [comment]
Does https://github.com/playcanvas/engine/pull/1941 fix this issue?

**Comment by Glidias** [comment]
Yes, it does.
