### ISSUE TITLE
visibleThisFrame always returns true

### ISSUE THREAD

**Issue by highvrahos** [playcanvas/engine#1942]
### Description

It seems that the visibleThisFrame property isn't updated when visibility checks against models are executed while doing Frustum Culling.

### Steps to Reproduce

1. Enable **frustumCulling** on the active camera.
2. Add a script to monitor the **visibleThisFrame** on a meshInstance.
3. Rotate the camera to have the model in the view and out of the view.

This property always returns true, even when the model isn't in the view.

I've debugged the [_isVisible](https://github.com/playcanvas/engine/blob/9b4a312057fd4477aead5962e71061674689967b/src/scene/forward-renderer.js#L509) method in the ForwardRenderer class and the inputs seem correct (model bounding box).

Example project: https://playcanvas.com/editor/scene/897883

**Comment by mvaligursky** [comment]
I cannot open the project (the link gives me 404 Scene not found).

Based on documentation, I just want to make sure you are reading the value inside onPostCull.

boolean visibleThisFrame
Read this value in pc.Layer#onPostCull to determine if the object is actually going to be rendered.

**Comment by highvrahos** [comment]
Hi @mvaligursky ,

Sorry about the link, I've updated my initial post with the right now.

I was under the impression, given on how I was using **visible** or **visibleThisFrame** the previous years (before pc.Layer) was introduced that when frustum culling is enabled and executing that property would get updated with the visibility check.

Could you share a code snippet on how that works today? What's the correct way to check if a model is visible by a camera or not, something asked quite often in the forums.

**Comment by mvaligursky** [comment]
I created new project in editor, that creates cube with name "Box".
I then created a script with this content:

`var MeshVisScript = pc.createScript('meshVisScript');

MeshVisScript.prototype.initialize = function() {
 
    this.app.scene.layers.getLayerByName("World").onPostCull = (cameraIndex) => {
        var entity = this.app.root.findByName("Box");
        var meshInstance = entity.model.model.meshInstances[0];
        console.log("visible: " + meshInstance.visibleThisFrame);
    }    
};`

and attached it on a root node.
Then I Play the project and move the camera entity in Editor. Console log displays visibleThisFrame for the Box correctly, true when visible, false when not.

Of course the code is not optimized, you should not call findByName each frame.

**Comment by highvrahos** [comment]
Many thanks @mvaligursky, this seems to be working fine, it makes to have the property check onPostCull since frustum culling is running per layer.
