### ISSUE TITLE
Make pc.SceneRegistry public

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/engine#1948]
### Description

I know having more public classes is undesirable, so we wouldn't ask for this if it wasn't necessary.

Currently, there is no way for a developer to get a list of scenes, add/remove or search for one by name. This is important when a game or app needs to change or display available scenes etc.

Just like `pc.AssetRegistry`, `pc.SceneRegistry` needs to be accessible. In the future, a scene should preferably be handled like an asset - but as long as that is not the case, it makes sense to make `pc.SceneRegistry` public. It may be worth noting that [Unity's equivalent `SceneManager`](https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.html) is also available to devs for the same reason.

**Comment by willeastcott** [comment]
I checked with @daredevildave who originally added the `pc.SceneRegistry` class and he was OK with this. From my perspective, I have just one comment. Currently, the `pc.Application` API has `loadScene`, `loadSceneHierarchy` and `loadSceneSettings` functions. And these just call directly through to `pc.SceneRegistry` functions with the same name/signature. So it feels like we should deprecate the `pc.Application` versions of these functions and encourage the use or the `SceneRegistry` directly instead.

**Comment by Maksims** [comment]
+1 for better API on `app.scenes`

**Comment by willeastcott** [comment]
Any particular proposal on that @Maksims? Or are you basically just suggesting we do what I describe above?

**Comment by aidinabedi** [comment]
@willeastcott PR is updated based on your feedback.

**Comment by godiagonal** [comment]
@willeastcott Any news regarding this issue/PR? Would be very valuable for us to have this in the coming release.
