### ISSUE TITLE
LightMap UV channel on model without UV channel

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#195]
If you apply lightMap on material, and then material on model that doesn't have UV1 data, then model will not be rendered and it will console warning:  
`[.WebGLRenderingContext]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 1`

It would be great if model would not disappear, and warning would be thrown only once on applying material and with meaningful message.

**Comment by guycalledfrank** [comment]
I remember this problem before, but I actually can't reproduce it right now. Do you have an example?

**Comment by Maksims** [comment]
It appears to happen only on non-ANGLE devices such as Mac and Linux.
Very likely it is related to the way ANGLE handles uninitialized buffer data and still works, where Mac and Linux just throws warning and breaks rendering.

**Comment by guycalledfrank** [comment]
Seems to work on IE11 apart from ANGLE browsers. Mac-only problem?

**Comment by willeastcott** [comment]
Would it help to switch FF or Chrome on Windows to use OpenGL instead of DX?

https://github.com/mrdoob/three.js/wiki/How-to-use-OpenGL-or-ANGLE-rendering-on-Windows

**Comment by guycalledfrank** [comment]
Still can't reproduce, even with GL Chrome.

**Comment by Maksims** [comment]
Does this https://github.com/playcanvas/engine/pull/271 fixes issue described in this ticket?

**Comment by guycalledfrank** [comment]
It should.
