### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dirty' of undefined

### ISSUE THREAD

**Issue by bfischlin94** [playcanvas/engine#1952]
Getting the Error: 

Uncaught TypeError: Cannot read property 'dirty' of undefined
    at ForwardRenderer.renderForward (playcanvas-stable.js:10362)
    at ForwardRenderer.renderComposition (playcanvas-stable.js:11283)
    at Application.render (playcanvas-stable.js:24982)
    at playcanvas-stable.js:25334

when trying to switch scenes and some of the assets in the new scene are not "pre-loaded". I've got an asset-Loader which loads the assets of the other scene in the background, but if the user switches to the scene before all assets are loaded, the scene itself loads the required assets first, before the camera view is enabled. 

But sometimes (not all the time, I'm guessing it's dependent on which assets are already loaded) I get this error. And also my skybox isn't displayed and all objects of my level from which the assets haven't been loaded yet. Funily enough, when a camera switch occurs sometimes the level is then displayed correctly, but another camera switch breaks it again (but the error is not thrown anymore)

![error_scrsht1](https://user-images.githubusercontent.com/42368906/77914260-ecfe3e00-7295-11ea-832f-48d1d46fd5a0.png)

after siwtching camera twice

![error_scrsht3](https://user-images.githubusercontent.com/42368906/77914403-29ca3500-7296-11ea-96c0-0847c90effd8.png)

When all assets are already loaded before switching to the other scene no error is thrown and everything is fine. I have not altered the engine in any way and before Thursday last week (26th of March 2020) everything worked with no errors.

I'm using Chrome on Windows 10 but also tried Firefox, where the problem persisted. I've tried it on multiple computers and it kept on happening. So the issue is not Hardware related. 

![error_scrsht2](https://user-images.githubusercontent.com/42368906/77914520-5716e300-7296-11ea-85c1-1e7893c7feaa.png)

**Comment by willeastcott** [comment]
Hi @bfischlin94. Can you provide us with a specific reproducible so that we can debug and resolve this problem please? It's practically impossible to fix this just by scanning commits in the engine around that date.

**Comment by bfischlin94** [comment]
Hi @willeastcott I can't publicly share my Project. I could send you a Build-Link privately with instructions on how to reproduce the error. I just need a way to share the link with you in private.

Thank you very much.

**Comment by willeastcott** [comment]
Please email it to support @ playcanvas dot com please.

**Comment by bfischlin94** [comment]
@willeastcott thank you, I have written an email!

**Comment by willeastcott** [comment]
This issue seemed to switch to email. It has not been updated in a long time, and I can't find the email thread. Therefore, I am going to close this issue for now. However, if there is still something to resolve here, please do reopen it.
