### ISSUE TITLE
Detail Maps

### ISSUE THREAD

**Issue by animech-sijo** [playcanvas/engine#1962]
### Description

Detail maps (or Secondary maps) allow you to overlay a second set of textures on top of the main textures. Detail maps allows you to give the illusion of more detail in a material by bringing in a tiled Diffuse and Normal map, which layers over the main Diffuse and Normal for an object. Click on the images to see in fullscreen:
![DetailMap1](https://user-images.githubusercontent.com/56446466/78360487-2a750b00-75b7-11ea-994a-ea5035fda69d.jpg)

Detail maps allow us to vary the tiling texture, without affecting the main texture.
![DetailMap2](https://user-images.githubusercontent.com/56446466/78360954-e33b4a00-75b7-11ea-88e4-43bc8a9f191c.jpg)

To achieve this effect without detail maps, you would have to "precombine" the main textures and detail textures.
![Precombined](https://user-images.githubusercontent.com/56446466/78361674-13371d00-75b9-11ea-81cd-e7dd15459ef6.jpg)

By separating main and detail textures (instead of precombining) we can use lower resolutions, and therefore use less data. In the example below, we use 60% less VRAM and 80% less storage because of lower resolutions and more easily compressed textures. This affects the end user, since it lowers memory consumption and requires less data to download.

![MainDetail](https://user-images.githubusercontent.com/56446466/78361704-221dcf80-75b9-11ea-968d-7808f0e3df40.jpg)

Detail maps are supported by major game engines, such as Unity and Unreal:
- https://docs.unity3d.com/Manual/StandardShaderMaterialParameterDetail.html
- https://docs.unrealengine.com/en-US/Engine/Rendering/Materials/HowTo/DetailTexturing

**Comment by Maksims** [comment]
I previously found myself writing shader chunks for something that would be easily implemented using details layer, indeed.

Here is concept idea of potential UI. Basically, it introduces Details Layer to most texture slots, except environment and lightmap slots.
Each details layer would have own parameters like normal layer. So you would be able to tint details layer on diffuse, or change details layer intensity on emissive layer, etc. As well as have layer intensity and mask texture. All textures would have own tiling information.

UI before details layer added:
![add-layer](https://user-images.githubusercontent.com/636263/78450492-84450600-7687-11ea-84c6-59fef5676021.png)

Once details layer added:
![remove-layer](https://user-images.githubusercontent.com/636263/78450494-873ff680-7687-11ea-9d92-7e0b81dd6052.png)

After looking into FBX and GLTF, I could not find any reference to details layers or multi-layered texture slots. So it would be purely in PlayCanvas material, added from code/Editor, and not sourced automatically from imported assets.

**Comment by animech-sijo** [comment]
@willeastcott Any updates on this?

**Comment by mvaligursky** [comment]
it's being reviewed at the moment @animech-sijo.
