### ISSUE TITLE
glTF loader doesn't handle KHR_materials_unlit

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/engine#1969]
### Description

The unlit material extension `KHR_materials_unlit` is not correctly handled in PlayCanvas's built-in glTF loader. It seems at least ambient light and reflections are still being applied to an un-lit material. For more information on how it should look, please see: [KhronosGroup/glTF-Sample-Models/2.0/UnlitTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/UnlitTest)

### Steps to Reproduce

1. Open project: https://playcanvas.com/project/675951/overview/khr_materials_unlit-gltf-test
2. Open scene "Untitled" and launch it.

### What I expected to see
![image](https://user-images.githubusercontent.com/255073/78460638-be7fc900-76c2-11ea-9e2d-ce0181eb687b.png)

### What I see instead
![image](https://user-images.githubusercontent.com/255073/78460595-5cbf5f00-76c2-11ea-9ded-11d0c98f3524.png)

**Comment by cx20** [comment]
I've confirmed glTF's `KHR_materials_unlit` extension is working in the latest version of PlayCanvas.
[PlayCanvas + UnlitTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/18fe78a74f2f7f927e8b6e489d2c695e2d0f44b0/examples/playcanvas/index.html?category=tutorialModels&model=UnlitTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/79347440-a9325680-7f6e-11ea-93a1-b0f749424a53.png)
