### ISSUE TITLE
Oculus Quest V15 - performance issues

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#1979]
Currently there are performance issues with running PlayCanvas apps in Oculus Quest V15.
Seems like regression since V14, as previously was all fine.

Here is bug reported on Oculus forums: https://developer.oculus.com/bugs/bug/520195872260333/

**Comment by willeastcott** [comment]
I'm presuming this is no longer an issue? I haven't seen any performance problems in Quest recently. Please reopen if you feel there's still a problem.
