### ISSUE TITLE
Image element change only visible after browser refresh

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/engine#1985]
### Description
If I add an entity with an element and I make an adjustment in the element, this adjustment is only visible after I refresh the browser. I experience that with several things.

### Steps to Reproduce
1. Create a entity and add a image element
2. Image not visible until you refresh the browser
3. Change the opacity of the image element
4. Change not visible until you refresh the browser

**Comment by slimbuck** [comment]
Hi @Alb3rt1990 this sounds like an editor issue, not an engine issue. Please could you log this issue at github.com/playcanvas/editor instead?

**Comment by Alb3rt1990** [comment]
Done.

**Comment by slimbuck** [comment]
@Alb3rt1990 I see on the forums @willeastcott referred you here and then I refer you to the editor repo!

When you say the browser doesn't refresh do you mean the tab running the game or the tab running the editor?

Thanks!

**Comment by Alb3rt1990** [comment]
Now it has been posted twice. But I didn't say the browser doesn't refresh...

**Comment by slimbuck** [comment]
Sorry what I meant was, do you have to refresh the editor tab or the game tab to see the changes?

**Comment by willeastcott** [comment]
@slimbuck Actually, no, I have a feeling this is an engine issue. Although I'm willing to be proved otherwise. 😄

**Comment by Alb3rt1990** [comment]
@slimbuck  Both. I don't see the changes that i make in the editor until i refresh the editor tab and i don't see it in the game until i refresh the game tab.

**Comment by slimbuck** [comment]
Hahaha @Alb3rt1990 @willeastcott thanks both! :D

**Comment by yaustar** [comment]
![Kapture 2020-09-23 at 13 35 26](https://user-images.githubusercontent.com/16639049/94013279-c2eb8b80-fda1-11ea-9a7e-d80173ff5715.gif)

Only happens if the entity is created first and the element component is added afterwards. A refresh of the browser is needed to render the element

**Comment by FutureFireplace** [comment]
Instead of posting a new issue, I will reference - bottom lines of - this forum post of mine https://forum.playcanvas.com/t/solved-multiple-materials-on-same-meshinstance-looking-to-change-an-assetreg-material/15930/23. 
I am not sure what the future brings for the engine within the 'engine refresh' area - and I do not possess skills in the language of the PC-engine development - but I would personally prefer an engine with a more independent kernel >> meaning: The user should do less refreshing, and better rely on/and trust the engine to react to editor and script changes instantly, without additional/extra (and somewhat unnecessary) F5-clicks at random moments within development processes :-)

**Comment by albertvanveen** [comment]
Is there any progress on this? Very annoying to refresh my browser every time when I’m working with UI elements.

**Comment by yaustar** [comment]
> Is there any progress on this? Very annoying to refresh my browser every time when I’m working with UI elements.

Does the disable/enable workaround work better for you here? https://github.com/playcanvas/engine/issues/1985#issuecomment-697335854

**Comment by albertvanveen** [comment]
Thanks for your response Steven, but that makes no difference to me. The biggest problem is that I first think I'm doing something wrong before I realize it's because of the bug. Even more annoying for users who don't know about the bug.

**Comment by Maksims** [comment]
We've experienced this bug a lot too. It actually affects different element properties. And does appear broken.

Especially when changing settings seems to be ok, but after refresh it looks different.

**Comment by albertvanveen** [comment]
Possible related: https://github.com/playcanvas/editor/issues/159

**Comment by yaustar** [comment]
This is now fixed in https://github.com/playcanvas/editor/releases/tag/v1.19.18

**Comment by albertvanveen** [comment]
Perfect! Thank you!
