### ISSUE TITLE
Animation plays differently in two projects

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#1994]
Same FBX asset in two separate projects and animate differently

One is new and works fine: https://playcanvas.com/editor/scene/904630
![image](https://user-images.githubusercontent.com/16639049/79218517-768e3e00-7e48-11ea-84d6-743f13207f4b.png)

The other was forked from a project from a user that had the asset animating incorrectly and been stripped of everything with the asset reimported. The head animation mesh is very large: ~https://playcanvas.com/editor/scene/904633~

Edit: https://playcanvas.com/editor/scene/912522

![image](https://user-images.githubusercontent.com/16639049/79218646-a63d4600-7e48-11ea-9feb-74c5212eabb7.png)

Can't work out the difference between the two projects yet so using this ticket as a reminder.

As reported on the [forum](https://forum.playcanvas.com/t/character-resize-when-animation-applied/12753).

**Comment by yaustar** [comment]
The only clue I have is that the asset FBX has a huge AABB so the Orbit Camera doesn't frame it correctly. 🤔

**Comment by ayring** [comment]
If i use the walk animation into elf stand character it became small
[walk.zip](https://github.com/playcanvas/engine/files/4497052/walk.zip)

**Comment by slimbuck** [comment]
@yaustar could you please re-check this? importing the FBX into a new project works fine for me

**Comment by yaustar** [comment]
@slimbuck Yep, still an issue 😅 

![image](https://user-images.githubusercontent.com/16639049/144592090-aeed2afb-3383-4c6f-b571-8e35a809cc75.png)

**Comment by yaustar** [comment]
@ayring Is this still an issue for you?

**Comment by yaustar** [comment]
Closing for now @ayring If this is still a problem, please let us know and we will reopen
