### ISSUE TITLE
Support glTF's KHR_draco_mesh_compression extension

### ISSUE THREAD

**Issue by cx20** [playcanvas/engine#2001]
### Description

I think other major WebGL libraries support glTF's `KHR_draco_mesh_compression` extension.
The `Draco` format is an excellent compression format.
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_draco_mesh_compression
I expect PlayCanvas to support the `Draco` format.

**Comment by mvaligursky** [comment]
Excellent suggestion. Yes, this is currently under development.

**Comment by cx20** [comment]
@mvaligursky Thank you for Draco support.

Currently I'm trying it locally but it seems that some models don't look right. Can you check it?

https://rawcdn.githack.com/cx20/jsdo-static-contents/33ab7250/models/gltf/2.0/Itokawa/glTF-Draco/Itokawa.glb

Current result:
![image](https://user-images.githubusercontent.com/1833979/80138182-62340900-85df-11ea-8d39-2a5a5476f10a.png)

Expected result:
![image](https://user-images.githubusercontent.com/1833979/80138630-0918a500-85e0-11ea-93e7-d96d0777aa56.png)

**Comment by mvaligursky** [comment]
hey @cx20 - thanks for testing and reporting this, I have PR #2016 ready. Please let me know if you find any other issues.

**Comment by mvaligursky** [comment]
this has been now merged to main, closing. Please re-open if any additional issues

**Comment by mvaligursky** [comment]
@cx20 - I'm very keen to test draco compressed point cloud as well .. but I cannot find any test data (self container glb draco compressed point cloud) or ay tools that can generate that from other formats. Would you have any ideas here? Thanks!

**Comment by cx20** [comment]
@mvaligursky Thank you for quick repair. I have confirmed that it can be [displayed](https://rawcdn.githack.com/cx20/gltf-test/db135efd9e24eb332ca06fa9240e4ce794e0c41e/examples/playcanvas/index.html?url=https://rawcdn.githack.com/cx20/jsdo-static-contents/33ab7250/models/gltf/2.0/Itokawa/glTF-Draco/Itokawa.glb) correctly with the latest version of PlayCanvas.

BTW, I remembered how I got the data in `Draco` format.
[Itokawa.glb](https://rawcdn.githack.com/cx20/jsdo-static-contents/33ab7250/models/gltf/2.0/Itokawa/glTF-Draco/Itokawa.glb) is test data generated as a result of testing various tools. Probably the procedure is not helpful.

1. Download `.obj` format data from [3D Asteroid Catalog](https://3d-asteroids.space/asteroids/25143-Itokawa)
2. Convert `.obj` format to `.drc` format using [draco_encoder](https://github.com/google/draco)
    `draco_encoder -i Itokawa.obj -o Itokawa.drc`
3. Load data in `.drc` format using Three.js + [draco_decoder.js](https://storage.googleapis.com/demos.webmproject.org/draco/draco_loader_throw.html)
4. Export in `.glb` format using Three.js + [GLTF Exporter](https://threejs.org/docs/#examples/en/exporters/GLTFExporter)
5. Convert `.glb` to `Draco` format using [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline)
    `gltf-pipeline -i Itokawa.glb -o Itokawa.glb -d`

**Comment by tonetechnician** [comment]
> @cx20 - I'm very keen to test draco compressed point cloud as well .. but I cannot find any test data (self container glb draco compressed point cloud) or ay tools that can generate that from other formats. Would you have any ideas here? Thanks!

Hey @mvaligursky, just wanted to follow up on this and find out if you managed to test if the Draco compressed pointcloud works aswell?

**Comment by mvaligursky** [comment]
@tonetechnician - there has been no change on this, as I have not sourced any data for it. It might work, but I cannot confirm it.

**Comment by tonetechnician** [comment]
Thanks @mvaligursky 

I've been working with some point cloud .ply sources + converting into Draco .drc. Seems to be working in Three.js with the their Draco loader, but I'm yet to attempt with Playcanvas. It seems the Draco decoder in Playcanvas is amongst the .glb loader so I'll need to dig a bit to get a handle to to load a regular .drc file. I've been unable to find tools that convert this draco mesh into glb unfortunately, maybe you know of one? 

Here's the .drc point cloud file if it will help you run a test -->  https://pointcloud-test.s3-eu-west-1.amazonaws.com/test.drc 

In the same bucket, you'll. also find a test where I simply exported the point cloud as .txt and filled in a vertex buffer with the positions + colours and was able to get Playcanvas to render it. The time it takes to do this is very long as you can imagine. Draco is definitely the better option --> https://pointcloud-test.s3-eu-west-1.amazonaws.com/index.html. Something interesting I noticed is that when doing this option, once the point cloud was rendered, the playcanvas engine seemed to perform better, I'm not sure if this is just a setting in three, but it was interesting to note.

Here's what that looked like rendered in Playcanvas (I think I messed up some of the colour buffer as it came out very over exposed) --> 
![txt-playcanvas](https://user-images.githubusercontent.com/13471797/99632710-4fcf6000-2a46-11eb-9824-c6d925b18926.jpg)

Here's a snippet of some of the point cloud rendered by Three.js --> 

![drc](https://user-images.githubusercontent.com/13471797/99631848-f7e42980-2a44-11eb-8f5c-b59a0c60a7db.jpg)

**Comment by mvaligursky** [comment]
Hi @tonetechnician. As you mentioned, we don't at the moment have loader for draco files, and only use draco compression for meshes inside glb. I guess you could grab some of the draco code, and build draco loader for your app. I'm not sure what else is inside draco file other than meshes (materials? textures?) but if you only need point cloud loader, that should be pretty straightforward to add I suspect, based on glb-loader code that handles draco.

I tried to find a way to convert different point cloud formats to glb draco compressed point cloud and found no tools. Maybe adding a support for this to some other tools that generate draco glb in a option as well).

And just for reference that you've probably seen already, we have these two examples on how to efficiently render point clouds here (they use pretty basic but fast shaders)
http://playcanvas.github.io/#graphics/point-cloud.html
http://playcanvas.github.io/#graphics/point-cloud-simulation.html

**Comment by tonetechnician** [comment]
Hey @mvaligursky Thanks for the response! 

As far as I understand, Draco is only a mesh compression and that's why is best used in tandem with the gltf container which contains things like material parameters and textures (and of course scenes, animations etc..)

Yeah, grabbing the code and creating a loader sounds like a good option indeed. I literally just need the mesh vertices and colours.

I've also found this resource which I've been considering to use in my project. Will be testing later this evening to see what it would take to get this loader to plug into the playcanvas geometry --> https://loaders.gl/modules/draco/docs/api-reference/draco-loader

Will drop a message here once I've tried a couple things. Maybe it will help someone in the future! 

Yes! These examples have been a huge help for me. It's what got me going with the basic txt file format to load into pc. I think fast shaders are the only option for some of these clouds with 1.3million points being a baseline. Draco's been an awesome help with that, taking some of my 700mb files and compressing them to 90mbs.

**Comment by tonetechnician** [comment]
Hey @mvaligursky 

Just to confirm that using the loaders.gl draco loader worked really well. I simply loaded the drc file, and created a mesh using the POSITION (Float32Array), COLOR (UInt8Array and NORMAL (Float32Array). In order to get the colour right I had to convert the UInt8Array into float32Array before setting it with SetColors. Feels like this shouldn't be required though, maybe I messed something up? Here's some example code: 

```
import * as pc from 'playcanvas'
import * as pcx from 'playcanvas/build/playcanvas-extras.js';
import {DracoLoader} from '@loaders.gl/draco';
import {load} from '@loaders.gl/core';
...
/* Create app stuff */
...

async function loadDraco(filePath) {
	const data = await load(filePath, DracoLoader);
	return data;
}

function convertToFloat32(incomingData) { // incoming data is a UInt8Array
    var i, l = incomingData.length;
    var outputData = new Float32Array(incomingData.length);
    for (i = 0; i < l; i++) {
        outputData[i] = (incomingData[i] - 128) / 128.0;
    }
    return outputData;
}

loadDraco('./assets/test.drc')
.then((data) => {
    var mesh = new pc.Mesh(app.graphicsDevice);
    mesh.clear(true, false);
    mesh.setPositions(data.attributes.POSITION.value, data.attributes.POSITION.size);
    mesh.setColors(convertToFloat32(data.attributes.COLOR_0.value), data.attributes.COLOR_0.size);
    mesh.setNormals(data.attributes.NORMAL.value, data.attributes.NORMAL.size);

    mesh.update(pc.PRIMITIVE_POINTS, false);
    var material = new pc.StandardMaterial();
    material.diffuseVertexColor = true;
    material.update()
    var node = new pc.GraphNode();
    var meshInstance = new pc.MeshInstance(node, mesh, material);

    model.graph = node;
    model.meshInstances = [meshInstance];

    app.systems.model.addComponent(entity, {
        type: 'asset',
        asset: model
    });
    entity.model.model = model;
    app.root.addChild(entity);
}
```

![image](https://user-images.githubusercontent.com/13471797/99773842-aeafda80-2b15-11eb-9975-902c5b4cb334.png)

Here's the model with a funky shader effect

**Comment by mvaligursky** [comment]
That's awesome, I'll create an issue to investigate possible integration with those loads, that's too convenient.

Regarding the colors, try calling mesh.SetColors32, even though that expects 0..255 range which gets converted to 0..1 range, but you code seems to convert it to -1..1 range (mistake?)

**Comment by slimbuck** [comment]
Cool! Might be nice to add a drc loading example to engine examples @mvaligursky?

**Comment by tonetechnician** [comment]
Thanks @mvaligursky! Indeed, you're 100% right. Should be between 0 - 1, messed that up. I'll try the setColors32, I think I misread the documentation when going through those functions. 

Indeed! So nice it works just like that. These loaders provide a bunch of different formats, more than draco. Could just be a tab on integration with other formats using loaders.gl, but not sure how the Playcanvas team would like to approach it. I'd be happy to submit a PR with an example of a point cloud .drc asset in a format similar to the other examples.

**Comment by mvaligursky** [comment]
by the way @tonetechnician - perhaps you should pass true as a second param here:
`mesh.update(pc.PRIMITIVE_POINTS, false);`
to have mesh update its bounding box, as you're not manually setting any bounding box - and so it's default box would be tiny and you might have issue with mesh getting culled.

**Comment by tonetechnician** [comment]
> by the way @tonetechnician - perhaps you should pass true as a second param here:
> `mesh.update(pc.PRIMITIVE_POINTS, false);`
> to have mesh update its bounding box, as you're not manually setting any bounding box - and so it's default box would be tiny and you might have issue with mesh getting culled.

Ah amazing. This was my next step. The mesh has been getting culled indeed! 

The loaders.gl actually also provides an aabb bounding box which I'll be adding in now. Will update the example above.

**Comment by mvaligursky** [comment]
> I'd be happy to submit a PR with an example of a point cloud .drc asset in a format similar to the other examples.

Yes please @tonetechnician, if you can add an engine example, that'd be much appreciated. From the docs it seems the loaders can be loaded directly from their CDN which would probably be the best option for the example, and just include some draco point cloud file into assets folder (something that is free to use).

**Comment by tonetechnician** [comment]
> > I'd be happy to submit a PR with an example of a point cloud .drc asset in a format similar to the other examples.
> 
> Yes please @tonetechnician, if you can add an engine example, that'd be much appreciated. From the docs it seems the loaders can be loaded directly from their CDN which would probably be the best option for the example, and just include some draco point cloud file into assets folder (something that is free to use).

Awesome. I'll submit that a bit later today!
