### ISSUE TITLE
Ability to clone model meshes

### ISSUE THREAD

**Issue by davidpox** [playcanvas/engine#2004]
It would be nice to have the ability to clone model meshes so their vertices can be manipulated without affecting other entities that use the same model.

**Comment by mvaligursky** [comment]
Hi davidpox,

thanks for requesting this.
In the meantime, you can use newly released Mesh API, that should let you do this pretty easily. Have a look at the examples linked at the bottom of the description as well.

https://github.com/playcanvas/engine/pull/1960

Cheers,
Martin

**Comment by mvaligursky** [comment]
I'll close this request as clone on a mesh is not very efficient way to modify mesh. It would mean the clone needs execute, and  then completely overwritten by changes.
More efficient solution is by the user directly construct a modified mesh using meshAPI: https://developer.playcanvas.com/en/api/pc.Mesh.html
