### ISSUE TITLE
Request: Access to the pc.scriptType's name (with Typescript typings)

### ISSUE THREAD

**Issue by TheJonRobinson** [playcanvas/engine#2014]
### Description

As part of our support code, it's useful to be able to access the scriptType's script name. We have been using the constructor's `name` but this is unreliable (we can name scripts differently when registering, and it gets mangled when minified anyway).

In the source `__name` is the script name, but this is an undocumented/internal working detail and not accessible via the Typescript typings generated from the JS-Doc.

It's easy to add a new read-only getter (though we could not call it `name`) - would this be an acceptable PR?

**Comment by willeastcott** [comment]
Pinging @aidinabedi....do you have any opinion on this?

**Comment by aidinabedi** [comment]
@TheJonRobinson Calling it `name` will conflict with the existing built-in property inside `Function`. Some browsers support overriding it (i.e. configurable), [but others don't:
![image](https://user-images.githubusercontent.com/255073/80416707-df5bc880-88d4-11ea-95bf-9c9d27ebc720.png)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name)

I see no problem with adding a getter called `scriptName` (something other than `name`), or make it a function `getName()`.

**Comment by TheJonRobinson** [comment]
Great, I'll get onto a PR. As you say, `name` would be disallowed - I was thinking `scriptName` getter also.
