### ISSUE TITLE
Some models in Draco format do not display correctly

### ISSUE THREAD

**Issue by cx20** [playcanvas/engine#2015]
### Description

I tried to display a model in Draco format with the latest version of PlayCanvas.
However, some Draco format models do not appear to display correctly.

For example, when I try to view the model in Draco format below, it looks like a strange texture is pasted.

https://rawcdn.githack.com/cx20/jsdo-static-contents/33ab7250/models/gltf/2.0/Itokawa/glTF-Draco/Itokawa.glb

Current result:
[PlayCanvas + Itokawa.glb Draco format result:](https://rawcdn.githack.com/cx20/gltf-test/7986323191c16ee765d789c618751a9eb0ff0df6/examples/playcanvas/index.html?url=https://rawcdn.githack.com/cx20/jsdo-static-contents/33ab7250/models/gltf/2.0/Itokawa/glTF-Draco/Itokawa.glb)
![image](https://user-images.githubusercontent.com/1833979/80138182-62340900-85df-11ea-8d39-2a5a5476f10a.png)

![image](https://user-images.githubusercontent.com/1833979/80218134-c3111f00-867b-11ea-9c3e-9c45275c92da.png)

Expected result:
[PlayCanvas + Itokawa.glb Binary format result:](https://rawcdn.githack.com/cx20/gltf-test/7986323191c16ee765d789c618751a9eb0ff0df6/examples/playcanvas/index.html?url=https://rawcdn.githack.com/cx20/jsdo-static-contents/33ab7250/models/gltf/2.0/Itokawa/glTF-Binary/Itokawa.glb)
![image](https://user-images.githubusercontent.com/1833979/80138630-0918a500-85e0-11ea-93e7-d96d0777aa56.png)

**Comment by mvaligursky** [comment]
fixed in #2016, thanks for reporting @cx20
