### ISSUE TITLE
Physically-correct highlights on transparent surfaces

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/engine#2018]
Currently, PlayCanvas doesn't have a mode to account for specular (incl reflection) highlights when applying opacity. In photorealistic applications, this often results in transparent materials appearing flat and physically incorrect, unfortunately.

Below is a 50% transparent metallic glossy sphere in the Editor. Observe the gray color of the highlight:

![transparent_material__0003_PlayCanvas](https://user-images.githubusercontent.com/255073/80316274-28d8e480-87fd-11ea-990e-a2849131960a.png)

Exact same material in different game engines that account for specular highlights over transparency:

* **Unity:**
![transparent_material__0001_Unity](https://user-images.githubusercontent.com/255073/80316432-17dca300-87fe-11ea-98f5-cce51ae4f3b5.png)

* **Unreal:**
![transparent_material__0000_Unreal](https://user-images.githubusercontent.com/255073/80316441-2c20a000-87fe-11ea-9a24-d87ad949ee01.png)

* **Babylon:**
![transparent_material__0002_Babylon](https://user-images.githubusercontent.com/255073/80316442-2c20a000-87fe-11ea-9d2d-83c165ac5527.png)

**Comment by mvaligursky** [comment]
reopening, as we do need a solution to this. See linked PR for possible solution.
