### ISSUE TITLE
AnimatedMorphCube.glb is not displayed correctly in glb-viewer

### ISSUE THREAD

**Issue by cx20** [playcanvas/engine#2026]
### Description

I tried displaying some glTF MorphTarget samples on the latest version of PlayCanvas.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube
However, the display result seems to be different than expected.

PlayCanvas + glb-viewer + AnimatedMorphCube.glb result:
![image](https://user-images.githubusercontent.com/1833979/80404781-a7687b80-88fc-11ea-9ce8-e03376e28509.png)

Expected result:
![image](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/screenshot/screenshot.gif?raw=true)

Also, the name of the Morph Target in glb-viewer is `undefined`.
![image](https://user-images.githubusercontent.com/1833979/80405329-6ae94f80-88fd-11ea-937f-8521839822b2.png)

**Comment by slimbuck** [comment]
Hi @cx20,

Thanks for the heads up on this issue! The fix is now merged.

**Comment by cx20** [comment]
@slimbuck  Thank you for fixing. I have confirmed that the issue of Morph Target becoming `undefined` has been resolved.
![image](https://user-images.githubusercontent.com/1833979/80516913-34740900-89bf-11ea-8aee-27da66e4c480.png)

However, what I ultimately want to achieve is to animate the same as the assumed result.
Is there a way to play the animation?

Expected result:
![image](https://user-images.githubusercontent.com/1833979/80520371-4ad09380-89c4-11ea-94bc-94b9f400b215.png)

![image](https://user-images.githubusercontent.com/1833979/80520450-676ccb80-89c4-11ea-91a4-9827e7a225f2.png)

**Comment by slimbuck** [comment]
Hi @cx20,

Yup you are righ. Glb animations don't drive morph target weights just yet. I'll reopen this till that's done :)

**Comment by cx20** [comment]
@slimbuck  Thanks! I have confirmed that the following models animate correctly on the latest version of PlayCanvas.

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SimpleMorph
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphSphere
