### ISSUE TITLE
RaycastAll memory access out of bounds

### ISSUE THREAD

**Issue by sakidev** [playcanvas/engine#2038]
Hey, I just started a quick project using the newest engine version.

I’m getting the mouse position and then converting to world coords, then raycasting the mouse position to know where the mouse physically is with RaycastAll, then filtering the results using entity name to get the “Ground” entity.

So this works with no issue.

The surprise comes when I’m moving around with the player controller (Sphere rigidbody) and collide it against a box rigidbody which is NOT the “Ground” entity, just an obstacle in the world.

I’m getting this error:

```
launch.js:7876 RuntimeError: memory access out of bounds
    at wasm-function[14]:0x34b1
    at wasm-function[64]:0x567e
    at gB.__destroy__ (https://launch.playcanvas.com/api/assets/files/Ammo/ammo.wasm.js?id=30431389&branchId=90874b16-9c90-4d68-8d41-597770bbb8af&t=6b7ab3989e4f9f17c86e44380f9181c6:660:443)
    at Object.b.destroy (https://launch.playcanvas.com/api/assets/files/Ammo/ammo.wasm.js?id=30431389&branchId=90874b16-9c90-4d68-8d41-597770bbb8af&t=6b7ab3989e4f9f17c86e44380f9181c6:458:110)
    at RigidBodyComponentSystem.raycastAll (https://code.playcanvas.com/playcanvas-stable.dbg.js:32509:12)
    at script.TankController.SeekMouse (https://launch.playcanvas.com/api/assets/files/Scripts/tankController.js?id=30431652&branchId=90874b16-9c90-4d68-8d41-597770bbb8af:75:46)
    at script.TankController.update (https://launch.playcanvas.com/api/assets/files/Scripts/tankController.js?id=30431652&branchId=90874b16-9c90-4d68-8d41-597770bbb8af:98:10)
    at ScriptComponent._scriptMethod (https://code.playcanvas.com/playcanvas-stable.dbg.js:29833:21)
    at ScriptComponent._onUpdate (https://code.playcanvas.com/playcanvas-stable.dbg.js:29869:14)
    at ScriptComponentSystem._callComponentMethod (https://code.playcanvas.com/playcanvas-stable.dbg.js:30284:51)
```
This is the SeekMouse function:

```
var farClip = Game.context.camera.farClip;
    var nearClip = Game.context.camera.nearClip;
    Game.context.camera.screenToWorld(this.mouseScreenPos.x, this.mouseScreenPos.y, nearClip, this.tempVec);
    Game.context.camera.screenToWorld(this.mouseScreenPos.x, this.mouseScreenPos.y, farClip, this.tempVec2);
    
    var results = this.app.systems.rigidbody.raycastAll(this.tempVec, this.tempVec2);
    if(results){
        var groundCast = results.filter(function(elm){
            if(elm.entity.name === 'Ground'){
                return elm;
            }
        });
        if(groundCast !== null && groundCast !== undefined){
            if(groundCast.length > 0){
                this.tempVec.copy(groundCast[0].point);
                this.tempVec.set(this.tempVec.x, this.turretHolder.getPosition().y, this.tempVec.z);
                this.turretHolder.lookAt(this.tempVec);
            }
        }
    }
```
If I move around without colliding against an obstacle, all is good. Problem comes when I do collide against something. It’s been a total surprise.

Things i’ve tried to fix:
- Remove the filter and just use the first result in the results array (exception happens).
- Change the Sphere collider to a Box collider (exception happens).
- Change to RaycastFirst (no exception happens).

What could be going on?

Engine source where the exception happens:

```
raycastAll:function(start, end) {
    if (!Ammo.AllHitsRayResultCallback) {
      console.error("pc.RigidBodyComponentSystem#raycastAll: Your version of ammo.js does not expose Ammo.AllHitsRayResultCallback. Update it to latest.");
    }
    var results = [];
    ammoRayStart.setValue(start.x, start.y, start.z);
    ammoRayEnd.setValue(end.x, end.y, end.z);
    var rayCallback = new Ammo.AllHitsRayResultCallback(ammoRayStart, ammoRayEnd);
    this.dynamicsWorld.rayTest(ammoRayStart, ammoRayEnd, rayCallback);
    if (rayCallback.hasHit()) {
      var collisionObjs = rayCallback.get_m_collisionObjects();
      var points = rayCallback.get_m_hitPointWorld();
      var normals = rayCallback.get_m_hitNormalWorld();
      var numHits = collisionObjs.size();
      for (var i = 0;i < numHits;i++) {
        var body = Ammo.castObject(collisionObjs.at(i), Ammo.btRigidBody);
        if (body) {
          var point = points.at(i);
          var normal = normals.at(i);
          var result = new RaycastResult(body.entity, new pc.Vec3(point.x(), point.y(), point.z()), new pc.Vec3(normal.x(), normal.y(), normal.z()));
          results.push(result);
        }
      }
      Ammo.destroy(points);
      Ammo.destroy(normals);
    }
    Ammo.destroy(rayCallback);
    return results;
```

**Comment by willeastcott** [comment]
Thanks for the detailed bug report. So it looks like the culprit is one of the calls to `destroy` in `raycastAll`. I suspect that the engine is destroying an object which perhaps does not require destroying. It would be useful to know which call to destroy it is though. Did you make to break into the debugger to determine that? You could also try monkey-patching that function in your app and then edit out the calls to destroy to determine if that fixes the problem. You could also remove each call to destroy one by one to determine which one is the problem.

**Comment by sakidev** [comment]
> Thanks for the detailed bug report. So it looks like the culprit is one of the calls to `destroy` in `raycastAll`. I suspect that the engine is destroying an object which perhaps does not require destroying. It would be useful to know which call to destroy it is though. Did you make to break into the debugger to determine that? You could also try monkey-patching that function in your app and then edit out the calls to destroy to determine if that fixes the problem. You could also remove each call to destroy one by one to determine which one is the problem.

Hi Will;

I did some monkey-patching as you suggested (this is how I debug stuff out generally), and the exception stopped happening after I commented this line: https://github.com/playcanvas/engine/blob/8b710c6369fed4f05ad414dc3d4c5464cd3524f9/src/framework/components/rigid-body/system.js#L366

All works good now. I don't really understand why it only happens upon collision with other physics body tho.

How can we fix this? Is it safe to not destroy the Ammo Vector points? I guess it would create a memory leak after a while.

**Comment by willeastcott** [comment]
OK, check out my PR and see if you think it looks sensible. 😄
