### ISSUE TITLE
Error when trying to render a line with 2 colors

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2044]
Works fine when drawing a single line color. Error happens when trying to use 2 colors:

```
launch.js:7876 TypeError: Cannot read property 'layer' of undefined
    at Application._addLines (playcanvas-stable.dbg.js:48205)
    at Application.renderLine (playcanvas-stable.dbg.js:48273)
```

The example, [shown in the docs](https://developer.playcanvas.com/en/api/pc.Application.html#renderLine), will generate the error.
```
var start = new pc.Vec3(0, 0, 0);
var end = new pc.Vec3(1, 0, 0);
var startColor = new pc.Color(1, 1, 1);
var endColor = new pc.Color(1, 0, 0);
app.renderLine(start, end, startColor, endColor);
```

**Comment by mvaligursky** [comment]
Hi @LeXXik - thanks for reporting this, I have a fix incoming.
In the meantime, if you pass options as a next parameter, all works.

**Comment by LeXXik** [comment]
Thank you @mvaligursky . That was what I did after checking the source.
