### ISSUE TITLE
Cannot select mipmap level for prefiltered cubemap in interior (not global skybox)

### ISSUE THREAD

**Issue by TrongHieu90** [playcanvas/engine#2045]
What i would like to achieve is to select different mipmap levels for the prefiltered cubemap just like the skybox settings. I want to use low level mipmap for mirror reflection, while use other higher levels for wooden object reflection, etc.

I tried to use custom shader chunk to make it work but failed to achieve the result.
Here is the shader code
```
uniform float mipmapIndex;
vec4 calcReflection(vec3 tReflDirW, float tGlossiness, float tmaterial_reflectivity, float mipmapIndex) {
    vec3 lookupVec = fixSeams(cubeMapProject(tReflDirW), mipmapIndex);
    lookupVec.x *= -1.0;
    return vec4($textureCubeSAMPLE(texture_cubeMap, lookupVec).rgb, tmaterial_reflectivity);
}
```

And here is where I pass the parameter in:

```
var ShaderManager = pc.createScript('shaderManager');

ShaderManager.attributes.add('mipmapIndexProp', { type: 'number', default:3 });

// initialize code called once per entity
ShaderManager.prototype.initialize = function() {
    var mipmapShader = this.app.assets.find("SetMipMap").resource;
    
    var meshes = this.entity.model.model.meshInstances;
    var dinnerTableMesh = meshes[23];
    //console.log(meshes[23].node.name);
    var mat = dinnerTableMesh.material;
    
    mat.chunks.reflectionCube = mipmapShader;
    mat.setParameter("mipmapIndex", this.mipmapIndexProp);
    mat.update();
};
```

There is no error in the debugger console. But upon changing to any mipmapIndexProp value, the result doesnt create the correct type of blurry or clear cubemap, unlike the setting for skybox.

Not sure if I do it correctly.

**Comment by Maksims** [comment]
Just change glossiness, it will gradually blend between all mip levels. Set lower glossiness on material - it will use lower level mips, set higher glossiness it will use higher level of mip.

**Comment by TrongHieu90** [comment]
Hi @Maksims 
Can you provide a little bit more details on how to copy `material.shader.definition.fshader` and `pc.shaderChunks`. How would I implement those ?

**Comment by Maksims** [comment]
@slimbuck would be cool to be able to know which chunks were used to generate shader in DEBUG engine. For development purposes, that would be really useful.

@TrongHieu90 as mentioned, try simply change glossiness value on material. Based on your description of issue, it is what you want. It is simple. If it is not what you need/want, then here is my workflow of how I implement custom shader chunks:

First find your entity, and get its fragment shader:

```javascript
var entity = pc.app.root.findByName('yourEntity');
var mesh = entity.model.meshInstances[0];
console.log(mesh.material.shader.definition.fshader);
```

It will log into console its shader code. Put it in your favourite IDE, then find part of shader code you want to override. Lets say I want to override part that implements diffuse shading, so I search in [chunks](https://github.com/playcanvas/engine/tree/master/src/graphics/program-lib/chunks) part of code that implements diffuse shading. In my case I search by this line:

```glsl
dAlbedo *= material_diffuse.rgb;
```

In this case it finds this: [diffuse.frag](https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/chunks/diffuse.frag). In engine it is defined as: `pc.shaderChunks.diffusePS`. So I create new shader file in Editor, copy code of that chunk into it, and modify as I want.

Then attach that chunk from asset to material:
```javascript
material.chunks.diffusePS = assetChunk.resource;
material.update();
```

That is basically a workflow of overriding your shader chunks on materials, that I use. **Please bear in mind, that shader chunks - is not a public code, meaning it is a subject to changes by engine updates, means it can break your custom chunks.** Once your project is published with custom chunk - it will stay with fixed engine version. But when you work with project in Editor, engine will be updated time to times.

If you override global shaders under `pc.shaderChunks` then it will apply to all materials created after.

**Comment by slimbuck** [comment]
@TrongHieu90 are you looking for the effect you can see https://playcanvas.github.io/#graphics/material-physical.html?

If so, then all you need to do is specify the material's glossiness in the material inspector panel. You can either specify a constant over the entire material or use a texture channel to localize the effect.

**Comment by slimbuck** [comment]
Closing this issue. Please reopen if you have any more questions!
