### ISSUE TITLE
glTF Parser doesn't support vertex attributes that need normalizing

### ISSUE THREAD

**Issue by aidinabedi** [playcanvas/engine#2053]
### Description

The built-in glTF loader doesn't account for the glTF property [`accessor#normalized`](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#accessornormalized). This results in corrupt data for vertex attributes that should be normalized before usage. To easily reproduce the issue I've prepared a project below, which contains two versions of the officially provided glTF [sample model "Box Vertex Colors"](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxVertexColors):

- First is the original embedded [BoxVertexColors.gltf](https://playcanvas.com/api/assets/30599824/download?branchId=a15469e2-d61b-4030-ac62-a01167da4c95) which uses 32-bit floats as vertex colors.
- Second is a modified version, called [BoxVertexColorsNormalized.gltf](https://playcanvas.com/api/assets/30603492/download?branchId=a15469e2-d61b-4030-ac62-a01167da4c95), which uses 8-bit unsigned bytes for vertex colors (that naturally needs be normalized).

### Steps to Reproduce

1. Open project: https://playcanvas.com/project/683926/overview/gltf-vertex-color-test
2. Open scene "Untitled" and launch it.

### What I expected to see
![image](https://user-images.githubusercontent.com/255073/81097638-785b9680-8f08-11ea-8637-d3f1534f285e.png)

### What I see instead
![image](https://user-images.githubusercontent.com/255073/81097621-74c80f80-8f08-11ea-97dd-807ea44db356.png)

**Comment by willeastcott** [comment]
Thanks for the bug report, @aidinabedi. Hey @slimbuck, does the PlayCanvas GLB writer write vertex colors an unsigned bytes?

**Comment by slimbuck** [comment]
@willeastcott Yes it does.
