### ISSUE TITLE
script.create() not returning instance of script

### ISSUE THREAD

**Issue by SnapWoody** [playcanvas/engine#2057]
### Description

I just found a bug with script.create() function.
I have this line of code:
`this.controller = this.entity.script.create(this.controllerType);`
It creates the object,  but doesn’t pass it back. It comes back as null. (I think it works first time, but after you do
`this.entity.script.destroy(this.controllerType);` 
then another create down the track, it won’t work. My current work around is this code underneath the create line.
`        if(!this.controller)
        {
            this.controller = this.entity.script[this.controllerType];
        }
`
### Steps to Reproduce

1. script.create(type)
2. script.destroy(type)
3. script.create(type)

**Comment by yaustar** [comment]
I've tried to reproduce the error here but was unable to: https://playcanvas.com/project/684213/overview/script-create-issue-205

```
var Sandbox = pc.createScript('sandbox');

var Sandbox2 = pc.createScript('sandbox2');

Sandbox2.prototype.initialize = function() {
    this.foo = this.entity.script.create('sandbox');
    console.log(this.foo);
    this.entity.script.destroy('sandbox');
    this.foo = null;
    this.foo = this.entity.script.create('sandbox');
    console.log(this.foo);
    
    this.entity.script.destroy('sandbox');
    this.foo = null;
    
    this.foo = this.entity.script.create(Sandbox);
    console.log(this.foo);
    this.entity.script.destroy(Sandbox);
    this.foo = null;
    this.foo = this.entity.script.create(Sandbox);
    console.log(this.foo);
};

Would you be able to provide a small project that can reproduce this issue please?
```

**Comment by yaustar** [comment]
@SnapWoody It's been a while 😅 Is this still an issue?

**Comment by willeastcott** [comment]
It's been nearly a year, so due to inactivity, I'm going to close this. However, if a problem still remains, please do reopen this, @SnapWoody.
