### ISSUE TITLE
Support for glTF extension KHR_lights_punctual

### ISSUE THREAD

**Issue by godiagonal** [playcanvas/engine#2061]
### Description
[KHR_lights_punctual](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual) is a glTF 2.0 extension supported by most major WebGL libraries. We propose that the PlayCanvas built-in glTF parser should support this as it is the current de-facto standard for storing light source information in glTF.
​
### Step to reproduce
1. Open project https://playcanvas.com/project/684177/overview/khr_lights_punctual-test
1. Open scene “PointLightTest” and launch it
1. Open scene “SpotLightTest” and launch it
​
### What I expect to see and what I saw instead
Note that the mocked lights for the “Expected” results are an approximation and might not match exactly what a proper implementation would yield.

Point lights:
![Screenshot 2020-05-07 at 09 39 26](https://user-images.githubusercontent.com/4249058/81267731-37b66700-9047-11ea-852d-4969063f7b1f.png)

Spot lights:
![Screenshot 2020-05-07 at 09 39 13](https://user-images.githubusercontent.com/4249058/81267741-3ab15780-9047-11ea-9fe3-2ae56363bb5e.png)

**Comment by willeastcott** [comment]
Blocked on #2063.

**Comment by cx20** [comment]
I too am waiting for `KHR_lights_punctual` to be supported. It would be great to have support for the extensions listed below.

https://github.com/cx20/gltf-test#extension-test-models
![image](https://user-images.githubusercontent.com/1833979/81282569-4e37df00-9096-11ea-9ddb-5bfc0ff64b4c.png)

Test model:
https://github.com/cx20/gltf-test/tree/master/tutorialModels/Lights

**Comment by cx20** [comment]
I have confirmed that this extension is available in the latest version of PlayCanvas and updated the status of [gltf-test](https://github.com/cx20/gltf-test#extension-test-models).

[PlayCnavas v1.44.0-dev + Light.gltf result:](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=Lights&scale=1.0&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/123293919-58919280-d54f-11eb-9b17-7f071285e398.png)

![image](https://user-images.githubusercontent.com/1833979/123293336-dc974a80-d54e-11eb-8460-6c54b20e2a0d.png)

**Comment by willeastcott** [comment]
Thanks for confirming that this test now passes, @cx20. You're the best! 🙏
