### ISSUE TITLE
Load glTF scenes as entity hierarchies

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2063]
Currently, glTF scenes are loaded as `pc.Model` objects. A `pc.Model` has a hierarchy made up of `pc.GraphNode` objects. A `pc.Entity` is a sub-class of `pc.GraphNode`, the main difference being that an entity can have components but a graph node cannot. Until we make this change, we cannot fix issues #2061 and #2062. Note that this issue has significant overlap with #1035.

In the Editor, this would mean importing 3D scenes as template assets rather than model assets.

**Comment by Maksims** [comment]
If it is imported as Template, will it allow modifying its hierarchy and override instances?
That would be very useful feature.

**Comment by willeastcott** [comment]
@zachpeterpaul is probably best placed to answer that. 😄

**Comment by zachpeterpaul** [comment]
I think our plan is to make such templates very similar or even identical to our regular templates, which allow overrides, including changes to the hierarchy - adding new entities, deleting and reparenting. I think unity allows only adding new entities to an instance as an override, for deletion etc it forces you to edit the template itself

**Comment by tonetechnician** [comment]
Hi there,

We've also run into this as an issue. We're unable to attach components to gltf children nodes once they've been imported into playcanvas. It would be fantastic to allow this ability!  

I see there was a pull request #2345 that is trying to sort this. Is there an ETA on when a solution to this might be included?

**Comment by mvaligursky** [comment]
Hi @tonetechnician - the mentioned RenderComponent in #2345 is indeed trying to sort this out, and so far handles glb's loaded into playcanvas at runtime. We're extending this to work on fbx and glb files imported into the Editor now, but that's a large project and will likely take few more months to finish. But we're actively working on it.

**Comment by tonetechnician** [comment]
I see! Thanks @mvaligursky for the update, that's promising work. 

I suppose if we wanted this functionality we could build out your branch and use that instead for the meanwhile then? We're not using the Playcanvas Editor at all currently, just the engine for viewing GLBs and applying some logic and handles to these imported. nodes.

**Comment by mvaligursky** [comment]
You could build a branch with this PR and use it. I'm hoping there won't be many changes to this in the future. Here's an example of how you could load glb and create entity hierarchy using render component:

```
var url = "../assets/models/playcanvas-cube.glb";
app.assets.loadFromUrl(url, "container", function (err, asset) {
            // create instance using render component
            var entity = asset.resource.instantiateRenderEntity({
                castShadows: true
            });
            entity.setLocalPosition(0, 1.5, 0);
            app.root.addChild(entity);
}
```

At the moment both batching as well as runtime lightmap generation is supported and tested, which should be all that is needed on the engine side.

**Comment by mvaligursky** [comment]
Closing this as this has been implemented and released.
