### ISSUE TITLE
Ammo js isn't released when application is destroyed

### ISSUE THREAD

**Issue by ssejjemba** [playcanvas/engine#2064]
This bug happens when you have multiple components running one after the other on the browser. Each component creates a playcanvas application and as it's unmounted from DOM it destroys its pc application with `app.destroy()`. After about 16 of these iterations, ammo.js throws an out of memory exception. `ammo.wasm.js:292 Uncaught abort("OOM"). Build with -s ASSERTIONS=1 for more info`. On firefox, I have worked around it by setting `window.Ammo = null` and `window.AmmoLib = null` after `app.destroy()` but this doesn't work on chrome. On chrome this workaround makes it throw an error after only about 2 iterations of `memory access out of bounds` from ammo.js. Haven't tried it on other browsers but am having the feeling that ammo.js isn't properly released when an application is destroyed in playcanvas.

**Comment by absconcept** [comment]
Any likely hood of fixing this issue? as it is causing a critical problem for us?

**Comment by absconcept** [comment]
Amazing, thank you :)
