### ISSUE TITLE
pc.Application#renderLine fails when rendering to world layer

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2069]
The API reference has the following code example

```
// Render a 1-unit long white line into the world layer
var start = new pc.Vec3(0, 0, 0);
var end = new pc.Vec3(1, 0, 0);
var color = new pc.Color(1, 1, 1);
var worldLayer = app.scene.layers.getLayerById(pc.LAYERID_WORLD);
app.renderLine(start, end, color, {
    layer: worldLayer
});
```

However, if you do this, all mesh instances in the world layer stop rendering and you just see the line.

To repro:

1. Create a new, blank project in the Editor.
2. Create a script with the following code:

```
var Line = pc.createScript('line');

// initialize code called once per entity
Line.prototype.initialize = function() {
    this.vecA = new pc.Vec3(0, 0, 0);
    this.vecB = new pc.Vec3(3, 3, 3);
    this.color = new pc.Color(1, 0, 1);
};

// update code called every frame
Line.prototype.update = function(dt) {
    var worldLayer = this.app.scene.layers.getLayerById(pc.LAYERID_WORLD);
    this.app.renderLine(this.vecA, this.vecB, this.color, {
        layer: worldLayer
    });
};
```

3. Launch the scene with the script enabled and you'll just see the line.
4. Launch the scene again with the script disabled, and you'll just see the box + plane.

**Comment by mvaligursky** [comment]
I had a quick look, and it seems the engine's immediate rendering removes all MeshInstances from a layer, not only the ones added by immediate rendering. I think it was designed to only use pc.LAYERID_IMMEDIATE exclusively, and no other layer.

https://github.com/playcanvas/engine/blob/a6741dabeda5262b4b3c5019314481e0c9c2beec/src/scene/immediate.js#L379-L385

This needs to be fixed / refactored.

**Comment by willeastcott** [comment]
Yeah, it's a bit of a mess. Even the function signature is pretty horrible since it has a number of variations and different parameters can have varying types.
