### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#207]
Currently engine reports exceptions in very weird and uninformative manner, making debugging a huge pain.
Review exception handling and console reporting practices to report true stack of error and meaningful messages from different parts of engine.

This is a blocker for some users to debug and submit errors to github issues, as well as contribute with errors. As open source project we should be open about the way it fails throwing exceptions, that luxury many other engines don't have.

**Comment by daredevildave** [comment]
Fixed by new resource loader.
