### ISSUE TITLE
[Physics] Collision Checking Incorrect

### ISSUE THREAD

**Issue by maxbbb** [playcanvas/engine#2072]
Related forum posts:
[Events not firing properly when increasing fixedtimestep](https://forum.playcanvas.com/t/collision-events-not-firing-properly-when-increasing-fixedtimestep/6241)
[Ammo js not returning collision callbacks](https://forum.playcanvas.com/t/solved-ammo-js-not-returning-collision-callbacks/7064)

The update function in the Rigidbody system file is checking for collisions after stepSimulation is called, but collisions can occur and then stop occurring during a single stepSimulation called if either 

a. The frame rate is low 
b. You decrease the fixedTimeStep to increase simulation accuracy (for example to 1 / 120) 

The easiest way to reproduce this is to increase the fixedTimeStep to something small like 1 / 240 and log collision events, it's clearly noticeable that many collision events are not being fired. 

This is because the stepSimulation will take how many ever substeps in increments of the fixedTimeStep it needs to in order to fill the deltaTime you pass it. So if you are using the dispatcher and the manifolds to check for collisions, if a collision occurs during one of these substeps but then is not occurring at the last substep then Playcanvas will fail to fire a collision event. 

Bullet has a built in method for handling this that is exposed in Ammo as dynamicsWorld.setInternalTickCallback. This will allow you to register a callback (the separated checkCollision function) that fires on each actual simulation step. This is what this looks like. I've tested all of the following code and it fixes the issue. If you'd like a pull request for this stuff let me know. 

```
var callback = Ammo.addFunction(this.checkForCollisions.bind(this), 'vif');
this.dynamicsWorld.setInternalTickCallback(callback);
```

The code for collision checking would then be removed from the update function as follows

```
// onUpdate(dt) function in the rigid-body/system.js

// #ifdef PROFILER
this._stats.physicsStart = pc.now();
// #endif

// Check to see whether we need to update gravity on the dynamics world
var gravity = this.dynamicsWorld.getGravity();
if (
  gravity.x() !== this.gravity.x ||
  gravity.y() !== this.gravity.y ||
  gravity.z() !== this.gravity.z
) {
  gravity.setValue(this.gravity.x, this.gravity.y, this.gravity.z);
  this.dynamicsWorld.setGravity(gravity);
}

// Update the transforms of all bodies
this.dynamicsWorld.stepSimulation(dt, this.maxSubSteps, this.fixedTimeStep);

// Update the transforms of all entities referencing a body
var components = this.store;
for (var id in components) {
  if (components.hasOwnProperty(id)) {
    var entity = components[id].entity;
    var componentData = components[id].data;
    if (
      componentData.body &&
      componentData.body.isActive() &&
      componentData.enabled &&
      entity.enabled
    ) {
      if (componentData.type === pc.BODYTYPE_DYNAMIC) {
        entity.rigidbody.syncBodyToEntity();
      } else if (componentData.type === pc.BODYTYPE_KINEMATIC) {
        entity.rigidbody._updateKinematic(dt);
      }
    }
  }
}

// #ifdef PROFILER
this._stats.physicsTime = pc.now() - this._stats.physicsStart;
// #endif

```

New check for collisions function 

```
      checkForCollisions: function (dw, timestep) {
        // Check for collisions and fire callbacks
        var dispatcher = this.dynamicsWorld.getDispatcher();
        var numManifolds = dispatcher.getNumManifolds();
        var i, j;

        frameCollisions = {};

        // loop through the all contacts and fire events
        for (i = 0; i < numManifolds; i++) {
          var manifold = dispatcher.getManifoldByIndexInternal(i);

          var body0 = manifold.getBody0();
          var body1 = manifold.getBody1();

          var wb0 = Ammo.castObject(body0, Ammo.btRigidBody);
          var wb1 = Ammo.castObject(body1, Ammo.btRigidBody);

          var e0 = wb0.entity;
          var e1 = wb1.entity;

          // check if entity is null - TODO: investigate when this happens
          if (!e0 || !e1) {
            continue;
          }

          var flags0 = wb0.getCollisionFlags();
          var flags1 = wb1.getCollisionFlags();

          var numContacts = manifold.getNumContacts();
          var forwardContacts = [];
          var reverseContacts = [];
          var newCollision, e0Events, e1Events, e0BodyEvents, e1BodyEvents;

          if (numContacts > 0) {
            // don't fire contact events for triggers
            if (
              flags0 & pc.BODYFLAG_NORESPONSE_OBJECT ||
              flags1 & pc.BODYFLAG_NORESPONSE_OBJECT
            ) {
              e0Events =
                e0.collision &&
                (e0.collision.hasEvent("triggerenter") ||
                  e0.collision.hasEvent("triggerleave"));
              e1Events =
                e1.collision &&
                (e1.collision.hasEvent("triggerenter") ||
                  e1.collision.hasEvent("triggerleave"));
              e0BodyEvents =
                e0.rigidbody &&
                (e0.rigidbody.hasEvent("triggerenter") ||
                  e0.rigidbody.hasEvent("triggerleave"));
              e1BodyEvents =
                e1.rigidbody &&
                (e1.rigidbody.hasEvent("triggerenter") ||
                  e1.rigidbody.hasEvent("triggerleave"));

              // fire triggerenter events for triggers
              if (e0Events) {
                newCollision = this._storeCollision(e0, e1);
                if (newCollision && !(flags1 & pc.BODYFLAG_NORESPONSE_OBJECT)) {
                  e0.collision.fire("triggerenter", e1);
                }
              }

              if (e1Events) {
                newCollision = this._storeCollision(e1, e0);
                if (newCollision && !(flags0 & pc.BODYFLAG_NORESPONSE_OBJECT)) {
                  e1.collision.fire("triggerenter", e0);
                }
              }

              // fire triggerenter events for rigidbodies
              if (e0BodyEvents) {
                if (!newCollision) {
                  newCollision = this._storeCollision(e1, e0);
                }

                if (newCollision) {
                  e0.rigidbody.fire("triggerenter", e1);
                }
              }

              if (e1BodyEvents) {
                if (!newCollision) {
                  newCollision = this._storeCollision(e0, e1);
                }

                if (newCollision) {
                  e1.rigidbody.fire("triggerenter", e0);
                }
              }
            } else {
              e0Events = this._hasContactEvent(e0);
              e1Events = this._hasContactEvent(e1);
              var globalEvents = this.hasEvent("contact");

              if (globalEvents || e0Events || e1Events) {
                for (j = 0; j < numContacts; j++) {
                  var btContactPoint = manifold.getContactPoint(j);

                  var contactPoint = this._createContactPointFromAmmo(
                    btContactPoint
                  );
                  var reverseContactPoint = null;
                  if (e0Events || e1Events) {
                    reverseContactPoint = this._createReverseContactPointFromAmmo(
                      btContactPoint
                    );
                    forwardContacts.push(contactPoint);
                    reverseContacts.push(reverseContactPoint);
                  }

                  if (globalEvents) {
                    // fire global contact event for every contact
                    var result = this._createSingleContactResult(
                      e0,
                      e1,
                      contactPoint
                    );
                    this.fire("contact", result);
                  }
                }

                if (e0Events) {
                  var forwardResult = this._createContactResult(
                    e1,
                    forwardContacts
                  );
                  newCollision = this._storeCollision(e0, e1);

                  if (e0.collision) {
                    e0.collision.fire("contact", forwardResult);
                    if (newCollision) {
                      e0.collision.fire("collisionstart", forwardResult);
                    }
                  }

                  if (e0.rigidbody) {
                    e0.rigidbody.fire("contact", forwardResult);
                    if (newCollision) {
                      e0.rigidbody.fire("collisionstart", forwardResult);
                    }
                  }
                }

                if (e1Events) {
                  var reverseResult = this._createContactResult(
                    e0,
                    reverseContacts
                  );
                  newCollision = this._storeCollision(e1, e0);

                  if (e1.collision) {
                    e1.collision.fire("contact", reverseResult);
                    if (newCollision) {
                      e1.collision.fire("collisionstart", reverseResult);
                    }
                  }

                  if (e1.rigidbody) {
                    e1.rigidbody.fire("contact", reverseResult);
                    if (newCollision) {
                      e1.rigidbody.fire("collisionstart", reverseResult);
                    }
                  }
                }
              }
            }
          }
        }
        this._cleanOldCollisions();

        // Reset contact pools
        this.contactPointPool.freeAll();
        this.contactResultPool.freeAll();
        this.singleContactResultPool.freeAll();
      },
```

**Comment by yaustar** [comment]
Thanks for looking into this! Yes, a PR would be greatly appreciated! :)

**Comment by willeastcott** [comment]
@maxbbb OMG - this has been a bug for literally years! If you've found the solution, I'm going to be forever in your debt. 🙏

**Comment by willeastcott** [comment]
I'm actually very nearly finished refactoring the physics engine [here](https://github.com/playcanvas/engine/pull/1997). You might want to check that out. It increases performance dramatically. You suggested change should happily coexist with my changes.

**Comment by maxbbb** [comment]
Haha no problem! I've been digging very heavily into Ammo / Bullet because our games need to be able to play inputs back deterministically (which I've also got working but would require a bit more work to get merged into the engine). I've been checking out that branch very often and have been testing on it actually so yes it does work with your changes. Would you like me to wait until that branch is merged to master or to make the pull request based on that branch? Also you might already know this but something happened in the last couple of commits on that branch that is causing compound bodies to behave incorrectly.

**Comment by willeastcott** [comment]
I knew that triggers are broken in that branch - it's next on my list to fix. What's the problem that you're seeing with compounds? The compound collision engine example I added seems to work fine in that branch.

I'm happy for you to submit a PR whenever and I can just merge it into my branch. Well, whoever merges to master first will deal with any conflicts anyway. 😄  But I'm sure they'll be trivial!

**Comment by maxbbb** [comment]
Okay sounds good. It looks like it is specifically related to kinematic compound bodies. I don't have an easily shareable repo but it looks like some collisions are happening but either the scaling is wrong or the bodies are not being moved from their original position with a set position. Changing them to static fixes the issue so I imagine it's something related with the body syncing. 

For the pull request it looks like exposing the setInternalTickCallback was a recent change in the Ammo repo, so this would be a breaking change for projects that imported Ammo any time before that unless some legacy update function was maintained. Is there any particular way that should be handled? Also in my fork I have broken out the creation of the dynamics world into a separate function and also created a function to properly destroy it, which may help with #2064. Could I also include that in this pull request?

**Comment by willeastcott** [comment]
Hmm. Y'know what, I think two PRs would be better. One to clean the up the dynamics world and the other to leverage the collision callback (since they're essentially unrelated).

As for `setInternalTickCallback` only being added recently, yeah, that's a bit frustrating. I think we might need some conditional code which:

1. Isolates collision detection to a separate function (that you have as `checkForCollisions`).
2. Check for the existence of `setInternalTickCallback`. If it's there, do what you suggest above. If not, call explicitly after stepping the simulation (so maintain current behavior for older versions of Ammo). But print a debug message saying "WARNING: This version of ammo.js can potentially fail to report contacts. Please update it to the latest version."
