### ISSUE TITLE
Prevent shader errors from spamming the JS console

### ISSUE THREAD

**Issue by Christopher-Hayes** [playcanvas/engine#2076]
# Description

When working with shaders, if your shader breaks the browser console gets spammed with errors on every single frame. This is a big problem for me because sheer volume of console logs significantly slows down my browser. If I don't quickly refresh or close the tab, Firefox will go unresponsive. It would be nice if there was some way to limit the shader error message to just showing up once and not every single frame. Working with shaders would be much easier if I didn't have to worry about my browser freezing every time I make a change.

**Comment by Maksims** [comment]
Encountered same issue a lot, and I believe there can be improvements made to shader compilation:
1. If shader fails, do not retry recompiling it before it is updated, or `material.update` intentionally called. This prevents compilation error spam.
2. After shader failed, if shader has changed and `material.update` is called - attempt recompiling it. Currently once shader failed, updating chunks and calling `material.update()` wont bring shader back to working condition.
3. Ensure live updates, still work, as it is often most common way to author and change shaders with live reloading:
```javascript
shaderChunkAsset.on('load', function() {
    material.chunks.someChunk = shaderChunkAsset.resource;
    material.update();
});
```
4. Shader compilation error, to include some reference so developer can find which shader failed, but should not include whole shader code, but only a range of failed line + some before and after. As shaders are often huge, and its whole code is irrelevant.
