### ISSUE TITLE
 Projects no longer run smoothly

### ISSUE THREAD

**Issue by Alb3rt1990** [playcanvas/engine#2081]
### Description
Recently I see that projects no longer run smoothly on my laptop with a screen resolution of 1920x1080 and a refresh rate of 144Hz. When I resize the browser it seems that the problems disappear and everything works more smoothly again.

### Steps to Reproduce
1. Use a screen with a resolution of 1920x1080 and a refresh rate of 144Hz or higher.
2. Move an object with delta time or render a line to a moving object.

**Comment by slimbuck** [comment]
Hi @Alb3rt1990, do you have a project we can test this with?

**Comment by Alb3rt1990** [comment]
You can use this project https://playcanvas.com/editor/scene/923095.

The problem is not constantly visible. Certain factors may play a role in making the problem visible. You can use the Crome browser with the mid-tier mobile option enabled to see what I regularly see on my laptop (i7 with 16gb ram and 100+ download and upload speed).

**Comment by willeastcott** [comment]
Does the same thing happen in Firefox, Chrome and Edge?
Does the same thing happen when launching the scene with previous engine release? e.g.
```https://launch.playcanvas.com/923095?use_local_engine=https://code.playcanvas.com/playcanvas-1.22.0.js```

**Comment by Alb3rt1990** [comment]
Yes, same problem in the previous engine and other browsers.
The problem is the best visible in Firefox.

**Comment by willeastcott** [comment]
My guess it that it's a graphics card driver problem. Do you have the latest drivers installed?

**Comment by Alb3rt1990** [comment]
There was an update needed but it didn't solve the problem.
Is there nobody else that can see what I mean?

**Comment by Alb3rt1990** [comment]
Maybe you can try my own project https://playcanv.as/b/9JBKqXHD/.
The player moves stuttering regularly. Already figured out that it is not my scripts.
To move the player click and hold from the player and drag in the direction you want to move.

**Comment by slimbuck** [comment]
The example project runs fine on my 144hz monitor running on 2017 macbook pro in Chrome.

We recently added a 'mini-stats' which shows CPU&GPU load and browser frame time. This may give some indication as to what's happening but unfortunately it's not available as a launch option yet.

**Comment by slimbuck** [comment]
Tried your own project too on Chrome and Firefox, can't see any stuttering.

**Comment by Alb3rt1990** [comment]
Supposing the problem is caused by my laptop, what are the things I should check?

**Comment by yaustar** [comment]
If you save a performance profile from chrome devtools, we could try to look into your laptop's specific issue.

**Comment by Alb3rt1990** [comment]
It must be something with the CPU. I saw the option slowdown CPU 6x in chome devtools and that immediately gives the effect what I see regularly. I can save the profile in .json format. How can I send it?

**Comment by Alb3rt1990** [comment]
With normal CPU:
![CPUnormal](https://user-images.githubusercontent.com/52896137/82309444-6dead380-99c3-11ea-88dd-334a8979ec38.png)

With slowdown CPU:
![CPUslow](https://user-images.githubusercontent.com/52896137/82309487-7e02b300-99c3-11ea-9494-5e846541c4aa.png)

**Comment by yaustar** [comment]
Can you save the profile please? That will allow us to load it locally :)

**Comment by Alb3rt1990** [comment]
http://www.mediafire.com/file/vten3n1wsx0aetf/Profiles.rar/file

**Comment by Alb3rt1990** [comment]
Here is a video of my own project where you can see the problem:
http://www.mediafire.com/file/0yvd1xqv5jkl8dr/VIDEO-2020-05-19-16-49-17.mp4/file

**Comment by willeastcott** [comment]
One thing to check - are you moving your camera to track the object as it was this frame or last frame? You should always update a camera's position in a `postInitialize` function if it is tracking an entity's position. This ensures that the entity moves first, and then your camera moves to track the _current_ position of the entity as it is _this_ frame.

**Comment by Alb3rt1990** [comment]
Okay, maybe that's the problem. I've applied this now and will let you know in a while if this fixes the problem. Thanks for the hint!

**Comment by willeastcott** [comment]
No problem. 😄

**Comment by yaustar** [comment]
@Alb3rt1990 I've updated the OrbitCamera to use postUpdate instead of update for the test project you posted on the forums and that's smoothed out an juddering I previously saw. Good call Will :)

**Comment by Alb3rt1990** [comment]
Yes, I think the problem has indeed been solved! Sorry for the inconvenience and thank you for investigating.
