### ISSUE TITLE
UI Masks should allow fading

### ISSUE THREAD

**Issue by sakidev** [playcanvas/engine#2083]
Hi guys, this is a suggestion i've come up with after avoiding using Masks for the sole reason that they're highly pixellated.

This is an issue from the forum: https://forum.playcanvas.com/t/ui-mask-pixelated/11346

Something similar happens with what i'm trying to implement, you can see here:
![masks](https://user-images.githubusercontent.com/49696473/82275162-50e1e080-9982-11ea-91a9-6ab359890195.png)

I have this setup in which the cursor is this shape, and the background image of the shape (inside a Mask with the same shape image) scrolls in a direction, making for a pretty cool effect.

You can see how the image that is being used as the Mask comes up really pixellated, it would be amazing if we could have UI Masks that actually allow fading so this pixellated effect doesn't happen.

Note: On some screen resolutions it is less appreciable but it's still there.

**Comment by sakidev** [comment]
Update:

So I don't know if Masks are not intended to be used for things like this, but I found a neat workaround since you guys made it possible for UI elements to use custom Materials.

You make a New Material, you set the Opacity texture to the shape you want to mask the Image as, and then it just works, smooth as hell!

![masks](https://user-images.githubusercontent.com/49696473/82331835-ef9f2900-99e4-11ea-9a00-0ba3903f82ad.png)

I'll now post this solution on the forum in case anyone runs into the same issues. UI Masking is really good for stuff like a scrollview which are rectangular shaped, but anything complex causes these pixellated artifacts - and maybe it's just the way it should be.

In any case, lemme know!

**Comment by raytranuk** [comment]
@sakidev - thanks for the update - the masking uses the stencil buffer and with stencils pixels are a either stenciled or not - and this can lead to pixelated if the edge is not exactly horizontal or vertical - the workaround you found: using a material with opacity map is an efficient solution - which is probably the recommended method for your use case.

**Comment by TheLevelord** [comment]
UI Element Image does not allow materials, only textures.  What am I missing here?

**Comment by yaustar** [comment]
> UI Element Image does not allow materials, only textures. What am I missing here?

There's an API for it here: https://developer.playcanvas.com/en/api/pc.ElementComponent.html#material

![image](https://user-images.githubusercontent.com/16639049/101165763-1cd4c100-362f-11eb-9ef8-fd55431ff0c5.png)

**Comment by TheLevelord** [comment]
How did I miss that!  I'm sorry for wasting your time :(
