### ISSUE TITLE
Program fails to link on Chrome OS

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#209]
To repro, run the Lambo scene:

https://playcanvas.com/project/7068/overview/lamborghini-murcilago

Error printed:

ERROR:   Failed to link shader program. Error: error: fragment shader varying vTangentW not written by vertex shader
.error: fragment shader varying webgl_6ccc0e73d2b9d4de not written by vertex shader

Looks like it's the wheels that are affected.

![screenshot 2015-03-30 at 3 39 26 pm](https://cloud.githubusercontent.com/assets/697563/6898594/046993a8-d6f3-11e4-9ed8-6118405666f7.png)

**Comment by guycalledfrank** [comment]
Should be fixed, check it
