### ISSUE TITLE
Shadow artifact recently introduced

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#210]
The Lambo demo has recently started exhibiting a nasty artifact:

![image](https://cloud.githubusercontent.com/assets/697563/6916198/2594634c-d792-11e4-951d-0d753de8a7ea.png)

See the unwanted presence of the shadow in the top right of the screenshot. This has only started happening since recent PRs were merged updating shadow code.

**Comment by guycalledfrank** [comment]
Should be fixed, check it

**Comment by Maksims** [comment]
If you open editor, then it does a bit weird things with shadows until you zoom in: https://playcanvas.com/editor/scene/7069

**Comment by guycalledfrank** [comment]
This one should be fixed now too

**Comment by willeastcott** [comment]
Indeed it is.
