### ISSUE TITLE
Add support for all texture formats when loading them as part of glb/gltf

### ISSUE THREAD

**Issue by pavle-goloskokovic** [playcanvas/engine#2101]
Loading textures as individual assets is currently supported for following formats:
- images: `.jp(e)g`, `.gif`, `.png`, and `blob:`
- `.dds`, `.ktx`
- and `.basis`.

https://github.com/playcanvas/engine/blob/559cf0e3b51d629641b16df2c4ecd7de6540a304/src/resources/texture.js#L281-L354

On the other hand, only images formats are supported when loading textures as part of `.glb`/`.gltf`:
https://github.com/playcanvas/engine/blob/ad5c7ab892ee851a2fdf4c47748ed0912cf74b52/src/resources/parser/glb-parser.js#L1352-L1405

Also note that the image object used for loading `.glb`/`.gltf` textures has no `onerror` event handler, so in case of any error, the loading progress simply stalls indefinitely. This is handled properly when loading textures individually.

It would be great if the same logic and support for various texture formats, used when loading textures individually, can be used when loading textures as part of `.glb`/`.gltf`.

That way we could have the benefit of a single file binary format of `.glb`, and hence a single network request when loading the asset, with the benefit of, e.g., packing `.basis` supercompressed cross-platform texture format withing that single `.glb` file.

If we currently want to use the benefits of both `.glb` and `.basis`, we would need to load the assets separately and then apply the texture to the model in code.

**Comment by slimbuck** [comment]
Hi @pavle-goloskokovic,

Thanks for this. We currently support the standard glTF image types, but extensions have been proposed for more formats at https://github.com/KhronosGroup/glTF/tree/master/extensions.

I like your idea of using the engine's asset loading system to handle gltf images. This will be necessary anyway when we add support for the additional formats. We're particularly keen to support embedding and loading basis textures in glb.

**Comment by pavle-goloskokovic** [comment]
Hi @slimbuck,

Thanks for the quick reply!

Glad to hear there is room for this to be implemented :)

I am using the standalone engine and have created a custom asset pipeline to optimize assets to be used within PC.

I was able to do the following:
- Unwrap `.glb` into `.gltf`
- Encode original images to `.basis` format
- Update images' references in `.gltf` json file to point to new `.basis` files instead of the original ones
- Wrap everything back to a single `.glb` file

All of this works pretty nice so far. This basically means that textures of any format can be packed into `.glb`, even if those formats are not yet officially supported by the standard.

I was also able to load this new `.glb` data from within PC, but the issue appears when glb parser tries to use `.basis` binary data as `Image` object source.

The functionality for handling `.basis` and other formats' binary data is obviously there, in the asset loading system, and the solution seems to be just using the same logic when handling `.glb` textures.
Texture format can easily be determined based on images' `uri` extension stored in `.gltf` json.

This functionality can also be very useful when optimizing assets from within the editor, and thus improving performance of all project that are built using it.

Anyways, thanks again for addressing this promptly!

**Comment by gandhars** [comment]
Hi @pavle-goloskokovic @slimbuck 
I agree with this request. This would be very useful for optimizing GLB models and their unnecessary use of GPU memory with textures in the standard format. Specially on older mobile devices. Support for BASIS textures inside the GLB would be great.
Here is my modified version of 'glTF-Shell-Extensions' http://h-art.cz/glTF-Shell-Extensions-basisSupport.zip
With this utility you can extract a GLB file, replace JPGs or PNGs files with BASIS, modify GLTF json file (overwrite paths for JPGs or PNGs texture) and pack them back in GLB.
Thank you for resolving the issue.
Radek

**Comment by slimbuck** [comment]
Hi @pavle-goloskokovic, Do you have a sample packaged glb I could use for testing? Thanks!

**Comment by gandhars** [comment]
Hello @slimbuck, here is some model http://play3d.cz/modelWithBasis.glb

**Comment by pavle-goloskokovic** [comment]
@slimbuck Here is a `.glb` model of a wooden crate, converted from `.fbx` model used in several pc tutorials:

[Wooden Crate.zip](https://github.com/playcanvas/engine/files/4710932/Wooden.Crate.zip)

It has the original `.jpg` texture, let me know if you need one with `.basis` texture.

One thing to take into consideration is handling `glb` with multiple textures of different formats.

**Comment by slimbuck** [comment]
Thanks @gandhars and @pavle-goloskokovic. I have both these models loading in the PC viewer. I have a few things to tidy up then will submit PR. If you have any other models that test edge-cases that'd be great for testing. Thanks again!
