### ISSUE TITLE
pc.RigidBodyComponentSystem#raycastFirst

### ISSUE THREAD

**Issue by qWici** [playcanvas/engine#2102]
### Description

Using [this tutorial](https://developer.playcanvas.com/en/tutorials/entity-picking-using-physics/) I create a project and when I click somewhere - got error "Uncaught TypeError: Cannot read property 'setValue' of undefined"

[Test project](https://playcanvas.com/editor/project/684711)

**Comment by willeastcott** [comment]
You need to Import Ammo. 😄 

Go to 'Settings' -> 'Physics' and hit the 'Import Ammo' button.

**Comment by qWici** [comment]
@willeastcott yeap, thanks)
