### ISSUE TITLE
PlayCanvas needs a proper build system

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2103]
Currently, the engine is built using the [`build\build.js`](https://github.com/playcanvas/engine/blob/master/build/build.js), a Node.js script that loads all scripts that appear in [`build\dependencies.txt`](https://github.com/playcanvas/engine/blob/master/build/dependencies.txt) and concatenates them. This concatenated script is then compiled (optimized/minified) with the Google Closure Compiler. This works OK. However, it's time we considered the benefits of a proper JS module builder.

Options are probably:

* [Webpack](https://webpack.js.org/)
* [Rollup](https://rollupjs.org/)
* [Parcel](https://parceljs.org/)
* [Browserify](http://browserify.org/)
* [esbuild](https://github.com/evanw/esbuild)

There are lots of blog articles advocating the different options. For example, [here's one](https://blog.bitsrc.io/choosing-the-right-javascript-bundler-in-2020-f9b1eae0d12b) advocating for Parcel (it has an interesting comparison table).

Some benefits:

* We can easily output different flavors of the engine (browser, Node.js, module).
* We can trivially leverage lots of plugins (Babel, Typescript, etc).
* We can easily generate source maps.
* Potentially reduce engine footprint (current module structure is quite verbose and could be simplified).

(Please comment below and if you have additional benefits or even disadvantages and I'll add them to this issue description. Feel free to advocate for your build system preference to help us make a decision).

**Comment by coderitual** [comment]
Hey @willeastcott . I would go for rollup. It will take more time to configure and setup correct plugins at the beginning but later on you have more control over build process. I think that maybe people from three.js can have some thoughts as they're alredy using rollup.

PS. I think the link with comparison is wrong, but I like what I saw.

**Comment by willeastcott** [comment]
Sorry, yeah, cut and paste error with the link. I've corrected it now. Thanks for the recommendation for rollup. It does look good.

**Comment by SlipstreamPhil** [comment]
Is Gulp also under consideration Will? https://gulpjs.com/
We use this, it does the job quickly and well for our use-case. That said I have zero experience of any of the other options, or even whether Gulp is necessarily an appropriate solution for the problem(s) you're trying to solve. But throwing it out there anyway :-)

**Comment by knownasilya** [comment]
Gulp is more a task runner and not a bundler on its own. It would use one of these. Personally I'd not go with gulp because the development community has been moving away from it for a while.

Rollup or parcel are probably best bets. Parcel tries to do a bit too much, so it feels spread thin, but rollup is focused but a bit low-level. I think parcel might be better for apps while rollup for libraries.

**Comment by Maksims** [comment]
Current build process is simple, and fast enough (on that below), and most important - does not require anything else to start building. **Just one command line.**
Here is what I believe is important to follow:

1. Simple to start building, no need to install complex stuff, or platform dependant things.
2. Closure compiler provides source map generation, so it is already possible to add.
3. Move towards modules to allow compiling engine excluding some feature. This provides optimising size of engine, which I believe is expected to only grow with time.
4. Provide fastest/simple compilation options for engine developers. Currently even waiting 5+ seconds, is actually not fun, when working fast on engine PRs.
5. Moving engine from strict ES5 JS, is probably a good move forward. Although build process should provide ability to compile to ES5 target. This probably will lift some ES5+ code restrictions.

Some of those tools, will unnecessary take very long time to do its tasks. This gets even worse with number of tasks.

**Comment by hxhieu** [comment]
Probably this is what you are after, just a single command line without any configuration fuzz https://github.com/evanw/esbuild

**Comment by willeastcott** [comment]
One concern for me about adopting esbuild is this line in the README:

```
As far as I know, this hasn't yet been used in production by anyone yet. It's still pretty new code and you may run into some bugs.
```

Maybe @evanw has some additional thoughts on that.

**Comment by kungfooman** [comment]
`esbuild` doesn't support ES5 and watch mode, so `parcel` seems to be the best bet. Made a simple parcel implementation and its quite fast (less than a second once .cache folder is created):

![image](https://user-images.githubusercontent.com/5236548/83136362-a25b3f80-a0e7-11ea-953e-9e85b8647983.png)

In "watch" mode via `npm run parcel:watch` (observering saved files and recompile on the fly) it even just takes half a second:

![image](https://user-images.githubusercontent.com/5236548/83136749-4b099f00-a0e8-11ea-9123-b9e18ab58063.png)

So `npm run parcel:watch` would be the best bet for quick development cycles (no need to constantly switch to a console/shell for triggering a rebuild).

**Comment by hxhieu** [comment]
> One concern for me about adopting esbuild is this line in the README:
> 
> ```
> As far as I know, this hasn't yet been used in production by anyone yet. It's still pretty new code and you may run into some bugs.
> ```
> 
> Maybe @evanw has some additional thoughts on that.

Don't we want to be the first one on the list ;-)? Everything starts from nothing isn't it?

Vue next build tool [vite](https://github.com/vitejs/vite) is using esbuild and it is getting massive momentum of the impressive build speed.

**Comment by willeastcott** [comment]
It does look interesting. But @kungfooman is now [well into an effort to migrate to Parcel](https://github.com/playcanvas/engine/pull/2106). The benefits are clear when compared to the current build system. If we choose to migrate from Parcel to esbuild after that due to a compelling argument, I'm all for that.

**Comment by willeastcott** [comment]
Haha. I just noticed you've submitted an alternative PR! Well, we now have two alternatives to benchmark. Very cool. 😄

**Comment by willeastcott** [comment]
Hey @kungfooman, what do you think about the esbuild PR?

**Comment by hxhieu** [comment]
> It does look interesting. But @kungfooman is now [well into an effort to migrate to Parcel](https://github.com/playcanvas/engine/pull/2106). The benefits are clear when compared to the current build system. If we choose to migrate from Parcel to esbuild after that due to a compelling argument, I'm all for that.

@willeastcott Yep, I saw that, really a lot of effort that I tried to avoid 😄 

PlayCanvas source still in ES5 so we just need a good minifier and that is lots of code and it looks way overkilled just for that.

**Comment by willeastcott** [comment]
I should point out that we already have a good minifier:

```
npm run closure
npm run uglify
```

What we don't have is a path address some of the things that I and @Maksims call out earlier in this thread. 😄

**Comment by hxhieu** [comment]
So as far as I understand now, we have quite a few unique steps

- Shaders concatenation
- Preprocessing directives

IMO, this cannot be just a "simple" build system as those steps will not be ALL available out-of-the-box from any of the bundlers out there. We'd still need to do custom code/tasks for them.

Now, it is the question how would we want to manage those unique tasks?

1. I'd prefer a simple approach with a `tasks` folder and run them with `gulp`. This means we can "compose" the tasks we want for the target build and to update a task just simple as update a Node module .js file
2. Of course, we could also go with a full-blown bundler plugins/add-ons setup (namely Parcel transforms). But then we need to follow their [ecosystem](https://github.com/parcel-bundler/parcel/issues/590) such as public NPM and naming convention etc. So to update a task, we would need to do all the overhead with configuring and publishing etc.

Don't get me wrong, I love Parcel. My latest project using Parcel with my own plugin [parcel-plugin-playcanvas](https://github.com/hxhieu/parcel-plugin-playcanvas) to push local bundle to the PlayCanvas editor. Parcel is smart and it works really well with general web development where your application might depend on many ecosystems such as ES6/TS and/or SCSS etc. But when comes down to low level bundling like what we are trying to do, I am not 100% sure that Parcel is still doing well - as we still need to write a lot of code with it.

Just to get the answer from the question above, how far would we want to go with this?

I will just continue update my PR with `gulp` now and let you guys do the homework. I shall just borrow the original build script for shaders concatenation and probably just a few line of code to do the directives replace.

Just FYI, esbuild has no supports for plugins - yet as it stands for simplicity, just does one job and does it right. I have created an issue on esbuild repo for our directives replacement [#161](https://github.com/evanw/esbuild/issues/163) and hope for an answer soon so I can eliminate one of the custom tasks.

Cheers,
H
