### ISSUE TITLE
Cubemap asset loading from blob url throws an error

### ISSUE THREAD

**Issue by ssejjemba** [playcanvas/engine#2104]
Engine seems to fail loading an asset from a blob url. This happens when I want to load all my static assets in cache and then serve them to my application from blobUrls. some part of my application uses playcanvas and I am getting an error when I try to load cubemap from blob URL.

```
// Preloading the cubemap asset
const makeRequest = function (url = '') {
            const fileName = url.split('/').pop()
            const xhr = new XMLHttpRequest()
            xhr.open('GET', url, true)

            xhr.responseType = 'arraybuffer'

            // Process the response when the request is ready.
            xhr.onload = function () {
                if (this.status === 200) {
                    const buffer = new Uint8Array(this.response)
                    const blob = new Blob([buffer.buffer])
                    self.all_assets.set(fileName, blob)
                }
            }

            xhr.send()
 }

makeRequest('./helipad.dds')
```

Then after when getting from cache
```
const blob = this.all_assets.get(`${asset_name}`)
return URL.createObjectURL(blob)
```
Then loading asset to cubemap
```
const cubemapAsset = new pc.Asset(
            'helipad',
            'cubemap',
            {
                url: this.props.apiStore.getStaticAsset('helipad.dds'),
            },
            {
                rgbm: true,
            }
        )
        cubemapAsset.ready(function () {
            app.scene.gammaCorrection = pc.GAMMA_SRGB
            app.scene.toneMapping = pc.TONEMAP_ACES
            app.scene.skyboxMip = 1 // Set the skybox to the 128x128 cubemap mipmap level
            app.scene.setSkybox(cubemapAsset.resources)
            // Disable the skyBox layer such that it is not rendered
            app.scene.layers.getLayerById(pc.LAYERID_SKYBOX).enabled = false
            app.renderNextFrame = true // ensure we render again when the cubemap arrives
        })
        app.assets.add(cubemapAsset)
        app.assets.load(cubemapAsset)
```
Throws an error `Error loading Texture from: 'blob:http://localhost:3000/2d641183-166d-416e-ba17-9f3465d96894'`

**Comment by yaustar** [comment]
Can you check if the latest version of the engine fixes this (https://code.playcanvas.com/playcanvas-latest.js)? I think the PR I did and merged yesterday fixes this: https://github.com/playcanvas/engine/pull/2100

**Comment by ssejjemba** [comment]
Alright thanks, @yaustar .. I'll check and confirm this...

**Comment by ssejjemba** [comment]
Sorry, It don't seem to me like it is sorting the issue...

**Comment by yaustar** [comment]
Had a look and realised that the texture loader for the DDS file is dependent on the URL having a .dds as a file extension. However, as it is a blob URL, there's no extension so it tries to load it as a normal image file. 😅 

@slimbuck , any ideas on this one?

**Comment by slimbuck** [comment]
Hello!

Sorry just getting to this now. You can provide a filename and url. This is now loadFromUrl works. See https://github.com/playcanvas/engine/blob/master/src/asset/asset-registry.js#L471

Thanks!

**Comment by ssejjemba** [comment]
@slimbuck I have tried something like this to load the cubemap from the blob URL but it doesn't look like it works... It's crashing...
```
app.assets.loadFromUrlAndFilename(
    blobUrl,
    'helipad',
    'cubemap',
    (err, asset) => {
      if (err) {
        console.log(err);
        return;
      }
      app.scene.gammaCorrection = pc.GAMMA_SRGB;
      app.scene.toneMapping = pc.TONEMAP_ACES;
      app.scene.skyboxMip = 1; // Set the skybox to the 128x128 cubemap mipmap level
      app.scene.setSkybox(asset.resources);
    }
  );
```

**Comment by slimbuck** [comment]
Hi @ssejjemba, the filename argument to ```loadFromUrlAndFilename``` must include the image file extension. This is used to determine which format handler to load the image with.

**Comment by ssejjemba** [comment]
ohhh cool let me try with that..

**Comment by slimbuck** [comment]
...oh wait you're loading a cubemap. Sorry I thought this was a texture. Not sure about this, will have to check.

**Comment by ssejjemba** [comment]
yeah... as it seems not to work...

**Comment by slimbuck** [comment]
If the blob contains a regular dds file you can load it as a regular ```texture``` resource instead of ```cubemap``` and set that as the skybox. If the dds file contains prefiltered lighting data, it's a little more complicated and unfortunately right now I don't believe it's possible.

**Comment by slimbuck** [comment]
This was fixed in #2216

**Comment by ssejjemba** [comment]
Details
TIN Number - 1015686372
Contact Person
name - Ssejjemba Daniel
email - ssejjembadan@gmail.com
phone - +256706650884

**Comment by willeastcott** [comment]
@ssejjemba I'm assuming you left this info by mistake?

**Comment by ssejjemba** [comment]
sorry... replied to the wrong email.... 😃
