### ISSUE TITLE
Publish viewer

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2109]
The last stable version of the viewer should be published somewhere publicly. I propose:

https://viewer.playcanvas.com/

One cool thing we could do then, is add a right click context menu option for GLB files in the Editor Asset panel 'View...' which will launch the viewer in a new tab (or maybe an iframe) to leverage some of the viewers functions. But that'd be a new feature request in the Editor repo. 😄

**Comment by Maksims** [comment]
If viewer.playcanvas.com will be used to view Editor's assets, then there is some considerations for authentication and session, to comply with assets access permissions.
Although viewer should probably work anonymously as well. Simple and straight forward.

**Comment by willeastcott** [comment]
Hmm. Well, we already have:

`https://playcanvas.com/editor`

So maybe:

`https://playcanvas.com/viewer`

...is better. And would presumably not have the authentication/access problem of a new sub-domain.

**Comment by slimbuck** [comment]
Done, get it at https://playcanvas.com/viewer!
