### ISSUE TITLE
Wrong .d.ts typing for NodeGraph.lookAt

### ISSUE THREAD

**Issue by Disorrder** [playcanvas/engine#2116]
### Description

As I understand `build/output/playcanvas.d.ts` generates automatically after install from npm.
Well, there is a mistake in lookAt() method, where at least 3 arguments are required, but in docs this method is usable with only 1 argument.
[API reference](https://developer.playcanvas.com/en/api/pc.GraphNode.html#lookAt)

![image](https://user-images.githubusercontent.com/2883539/83360696-d35b9e80-a38b-11ea-85f9-2a9796ac4770.png)

![image](https://user-images.githubusercontent.com/2883539/83360543-ba062280-a38a-11ea-8f44-7118179e9c4a.png)

Obviously, args `y` and `z` should be marked with `?` sign as well.

**Comment by willeastcott** [comment]
Thanks for reporting this! Hopefully #2117 addresses this to your satisfaction. 😄
