### ISSUE TITLE
Creating a certain refraction 'Render target' within a new project. 'Difference between two projects - Refraction'

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#2119]
As mentioned within the Playcanvas Forum topic: https://forum.playcanvas.com/t/difference-between-two-projects-refraction/13329/6, there seem to be a large difference within the 'code backbone' a certain Refraction example ressource ( https://playcanvas.com/editor/scene/927015), and the one users have to make from bottom up. 

* URL to a simple, reproducible test case that illustrates the problem clearly + 
Screenshots: photos lay within the link above: all should lay within topic above
* The platform(s)/browser(s) where the issue is seen: chrome
* A screenshot of http://webglreport.com/ (for graphics related issues):
![image](https://user-images.githubusercontent.com/6838800/83489130-42c9af00-a4ae-11ea-8d2c-f14c8208bab6.png)

### Steps to Reproduce

Al steps should be reproducable from link above, as well :-)

**Comment by mvaligursky** [comment]
closing for now as no issue has been identified based on the forum discussion - please reopen if further assistance is needed.
