### ISSUE TITLE
Constistent Transparency

### ISSUE THREAD

**Issue by sakidev** [playcanvas/engine#2120]
Hi guys, I've been trying to fake Ambient Occlusion cheaply with planes with a texture gradient on them which will be placed on top of the floor but I can't get it to work right.

The issue i'm having is when two of these planes touch with each other, their transparency gets incremented as part of the blending process leading to this result:

![image](https://user-images.githubusercontent.com/49696473/83528365-4f1f2d80-a4e9-11ea-9128-69a2fff0b018.png)

I want to get around this so the transparency will always be consistent.

One idea I had was to use the batcher to merge these meshes into one and see if that would solve it, but it doesn't. The closest i've got is this: 

![image](https://user-images.githubusercontent.com/49696473/83528599-95748c80-a4e9-11ea-8ee0-6f5fb9d21cc3.png)

(using Min blend type, but it still looks very badly, and it also introduces weird black screen flashes when moving the camera around)

Here's an editor link of the public project we're tinkering around with:
https://playcanvas.com/editor/scene/931843

Got any ideas on how to work around this?

**Comment by mvaligursky** [comment]
You could render these to a single render target, and then render it in the world - that would probably be the best option.

**Comment by sakidev** [comment]
@mvaligursky So, creating a separate canvas that only renders the fake AO layer where these planes are on, apply the renderTarget thing which would basically create a "screenshot" of what that camera views, and then applying the resulting texture to a plane on top of the ground?

Will try this right away & report, but I don't understand why rendering to a texture should behave differently as the problem is the alpha blending process.

**Comment by mvaligursky** [comment]
not separate canvas .. just a texture you render these to. See example here: http://playcanvas.github.io/#graphics/render-to-texture.html

The difference is - you clear that texture to white each frame, and render these rectangles in with min blend mode, and mathematically it will add them up correctly without double darkenning.

You cannot do this in the scene, as your rectangles render over something that is in the scene already and that changes it's color - so min blending no longer works.

In a way that's a solution you tried .. with min blend .. but your solution only works on white background .. if you put some texture there, it breaks.

I had a look at your project, and got it to work with min blending .. but do get flickering you mentioned .. that seems to be a bug in the engine, not an issue with your rendering approach.

**Comment by sakidev** [comment]
@mvaligursky Sorry, I actually meant separate layer, not canvas. I'm working on it, will report back, althought I'm having some issues rendering the texture on the separate plane, the texture is empty, troubleshooting it rn.

**Comment by sakidev** [comment]
@mvaligursky Okay, can you check out the project?

I've managed to render it to texture, but I got two issues:
- Alpha is not rendering as it should.
- How can I have the AO Camera not render the clear color and have the background be alpha so the plane below the AO plane is also viewed?

**Comment by sakidev** [comment]
Okay, I got the render target to render the alpha correctly so the ground plane behind the AO plane will now be shown.

Only issue pending @mvaligursky is that with the min blending this isn't rendering even how it looks in the editor. here you can see:
![image](https://user-images.githubusercontent.com/49696473/83555601-c74c1a00-a50e-11ea-8ebc-d9d7ac279d79.png)

**Comment by mvaligursky** [comment]
@sakidev - have you managed to get this working for your need?

**Comment by mvaligursky** [comment]
I'll close this for now, please let me know if there's anything else we can help you with.

**Comment by sakidev** [comment]
@mvaligursky I didn't with the solution you mentioned, worked around it by drawing shapes in a separate canvas, then using a blur filter on it, then render that on a world plane.

This is still a feature that would be cool to have tho, if possible.
