### ISSUE TITLE
PlayCanvas v1.28.1 fails to load some glTF models

### ISSUE THREAD

**Issue by cx20** [playcanvas/engine#2139]
### Description
I have updated the PlayCanvas version of [gltf-test](https://github.com/cx20/gltf-test) from `1.28.0-dev` to `1.28.1`.
However, the latest version of PlayCanvas `1.28.1` fails to load some models.

### Steps to Reproduce

OK: [PlayCanvas v1.28.0-dev + Duck.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/7d6d1fa5d48a146b40777df7cef100227e744eb6/examples/playcanvas/index.html?category=sampleModels&model=Duck&scale=1&type=glTF)

> The glTF model resource refers to the same folder as the model.
```
/sampleModels/Duck/glTF/Duck.gltf
/sampleModels/Duck/glTF/Duck0.bin
/sampleModels/Duck/glTF/DuckCM.png
```

NG: [PlayCanvas v1.28.1 + Duck.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/8e22bc2808b914382307a849483bdada324a47fa/examples/playcanvas/index.html?category=sampleModels&model=Duck&scale=1&type=glTF)

> The resource of glTF model does not refer to the same folder as the model but refers to the folder under the library.
```
/sampleModels/Duck/glTF/Duck.gltf
/examples/playcanvas/Duck0.bin
/examples/playcanvas/DuckCM.png
```

**Comment by cx20** [comment]
The following is the actual sample folder structure.

```
/gltf-test
    /examples
        /playcanvas
            /index.html
            /index.js
    /libs
        /playcanvas
            /v1.28.1
                /playcavnas-latest.js
    /sampleModels
        /Duck
            /glTF
                /Duck.gltf
                /Duck0.bin
                /DuckCM.png
```

**Comment by slimbuck** [comment]
Hi @cx20, as always, thanks for logging this issue!

I'm having a little trouble understanding how Duck.gltf under sampleModels containing references to 'Duck0.bin' and 'DuckCM.png' results in requests to files under examples?

Do you know how I can reproduce the network error using my own engine? I tried loading the problem model in the PC viewer but that worked ok.

**Comment by cx20** [comment]
Hi @slimbuck 

> Do you know how I can reproduce the network error using my own engine? 

I tried preparing a reproducible sample of the problem in jsfiddle.

OK : PlayCanvas v1.27.0 + Duck.gltf
https://jsfiddle.net/cx20/ev30uh2c/

NG : PlayCanvas v1.28.1 + Duck.gltf
https://jsfiddle.net/cx20/jpmd9r63/

The code for loading the glTF file is as follows.
```javascript
var url = "https://rawcdn.githack.com/cx20/gltf-test/9fb5f39992bdd548e17fb18b256c41b14fb8840e/sampleModels/Duck/glTF/Duck.gltf";
var filename = url.split('/').pop(); // "Duck.gltf"
app.assets.loadFromUrlAndFilename(url, filename, "container", function (err, asset) {
    var resource = asset.resource;
    gltf = new pc.Entity('gltf');
    gltf.addComponent('model', {
        type: "asset",
        asset: resource.model
    });
    
    app.root.addChild(gltf);
});
```

>  I tried loading the problem model in the PC viewer but that worked ok.

Hmm. I tried running the PC Viewer locally, and the result was as follows:

|glTF format    |resources used by the model      |result             |
|:--------------|:--------------------------------|:-----------------:|
|[glTF](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF)                     |Duck.gltf, Duck0.bin, DuckCM.png |:x:                |
|[glTF-Binary](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF-Binary)       |Duck.glb                         |:white_check_mark: |
|[glTF-Draco](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF-Draco)         |Duck.gltf, Duck0.bin, DuckCM.png |:x:                |
|[glTF-Embedded](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF-Embedded)   |Duck.gltf                        |:white_check_mark: |
|[glTF-Quantized](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF-Quantized) |Duck.gltf, Duck0.bin, DuckCM.png |:x:                |

**Comment by cx20** [comment]
@slimbuck I've reviewed recent changes and found that the following changes are affecting:

https://github.com/playcanvas/engine/blob/64208cb84675ddf4f41266543e1d81ba9d0dd91e/src/resources/loader.js#L149-L152

Previously, `original` parameter was passed as the `url`, but recent commits, it seems that the `filename` akes precedence. As a result, it seems that the `urlBase` argument of `GlbParse` is no longer working.

**Comment by slimbuck** [comment]
Ahh yes @cx20, thank you! The container resource is extracting the wrong path as a base for loading external urls, check out https://github.com/playcanvas/engine/blob/master/src/resources/container.js#L100. It should be using url.load not url.original. I'll submit a PR to get this fixed asap.

**Comment by cx20** [comment]
@slimbuck Thanks! I have confirmed that PlayCanvas `v1.29.0-dev` resolves this issue.
