### ISSUE TITLE
AnimComponentBinder not working in minified build

### ISSUE THREAD

**Issue by godiagonal** [playcanvas/engine#2153]
### Description
I have been testing out the new `AnimComponent` and noticed that it doesn't work properly for minified builds. After some digging I found that `constructor.name` is used to determine how an animated property should be handled in `AnimComponentBinder`. This unfortunately does not work in minified builds since the constructor names are obfuscated.

In the image below the object `property` is actually of type `pc.Vec3`.
<img width="348" alt="Screenshot 2020-06-10 at 17 49 41" src="https://user-images.githubusercontent.com/4249058/84289516-db150300-ab42-11ea-9bcf-218568cfac47.png">

**Comment by willeastcott** [comment]
Fixed by #2154
