### ISSUE TITLE
GLB models/assets do not render on some older Android Devices

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2157]
Example project: https://playcanvas.com/project/693898/overview/glb-android-bug

GT-I9500 (https://www.gsmarena.com/samsung_i9500_galaxy_s4-5125.php) renders fine. 
WebGL report
![GT-I9500 native browser 2](https://user-images.githubusercontent.com/16639049/84419333-60b2b480-ac10-11ea-9d9a-7e8e734d1b4d.png)

SM-J320F (https://www.gsmarena.com/samsung_galaxy_j3_(2016)-7760.php) does not render:
![SM-J320F 2](https://user-images.githubusercontent.com/16639049/84419226-3660f700-ac10-11ea-880f-8d6050498431.png)

Neither device supports WebGL 2. No errors or logs in console.

**Comment by yaustar** [comment]
So far, it seems related to having 0 Texture Image Units

**Comment by mvaligursky** [comment]
I tried my old "Sony Xperia Z" from 2013, and this renders fine on it. It has vertex textures support, if that's related.
