### ISSUE TITLE
No way to pass optional features into a WebXR session

### ISSUE THREAD

**Issue by benunbnd** [playcanvas/engine#2158]
### Description

Using WebXR on Chrome, the DOM isn't available or shown at all. Since Chrome 83, a new optional feature has been included to include a DOM overlay, e.g (from [https://immersive-web.github.io/webxr-samples/ar-barebones.html](https://immersive-web.github.io/webxr-samples/ar-barebones.html)):

```
navigator.xr.requestSession('immersive-ar', {
    optionalFeatures: ['dom-overlay'],
    domOverlay: {root: document.getElementById('overlay')}
}).then(onSessionStarted, onRequestSessionError);
```

However looking through the engine code for XrManager, there's no way to pass in additional data: 
```
var optionalFeatures = [];

if (type === pc.XRTYPE_AR)
    optionalFeatures.push('light-estimation');

navigator.xr.requestSession(type, {
    requiredFeatures: [spaceType],
    optionalFeatures: optionalFeatures
}).then(function (session) {
```
Could there be a way to pass in the optionalFeatures? Perhaps in entity.camera.startXr?

**Comment by willeastcott** [comment]
Hey @Maksims, want to take this?

**Comment by Maksims** [comment]
Sure. Will think and add ways to pass not only options, but also required/optional features to requestSession.
