### ISSUE TITLE
can i just edit in your web editor? is there any way to dploy my own editor by your code?

### ISSUE THREAD

**Issue by WensonYang** [playcanvas/engine#2169]
This issue tracker is **only** for bug reports and feature requests. For general support/help, visit https://forum.playcanvas.com

For bug reports, include:

### Description

Provide as much information as possible. Include (where applicable):

* URL to a simple, reproducible test case that illustrates the problem clearly
* Screenshots
* The platform(s)/browser(s) where the issue is seen
* A screenshot of http://webglreport.com/ (for graphics related issues)

### Steps to Reproduce

1. 
2.
3.

**Comment by yaustar** [comment]
I assume you would like to use the online scene Editor but use your own code Editor like Visual Studio Code?

We will soon be open sourcing a node.js library that can sync a project to your local PC so you can use any code editor you like :)

**Comment by yaustar** [comment]
Closing as inactive for almost 2 weeks now. Please re-open if you need more information :)
