### ISSUE TITLE
CORS not working properly on 1.28.4

### ISSUE THREAD

**Issue by mariogarranz** [playcanvas/engine#2175]
Our game builds stopped working recently, reporting a CORS error:

```
Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.
    at a.uploadTexture (https://localhost:8080/playcanvas-stable.min.js:211:3)
    at a.setTexture (https://localhost:8080/playcanvas-stable.min.js:216:390)
    at a.draw (https://localhost:8080/playcanvas-stable.min.js:219:254)
    at g.drawInstance (https://localhost:8080/playcanvas-stable.min.js:488:498)
    at g.renderForward (https://localhost:8080/playcanvas-stable.min.js:506:473)
    at g.renderComposition (https://localhost:8080/playcanvas-stable.min.js:531:315)
    at e.render (https://localhost:8080/playcanvas-stable.min.js:1099:39)
    at https://localhost:8080/playcanvas-stable.min.js:1114:499
```

I did some checks on the error. Verified that the image causing the error has the correct CORS headers and forced anonymous cross origin on the loader. Nothing fixed it.

`app.loader.getHandler("texture").crossOrigin = "anonymous";`

We had not changed anything in the game code and the server seemed to be sending files properly. I did different tests and I see this error started happening when our builds wen from version:

1.28.3 9fafe16

to 

1.28.4 e358926

If I replace the playcanvas-stable.min.js file in the failing builds with the old version, it works just fine.

**Comment by slimbuck** [comment]
Hi @mariogarranz, 

Sorry about this. We split out the engine's image loaders and must have inadvertently changed the handling of CORS in the process. Is there any chance you are able to share with me a repro project?

Thanks

**Comment by slimbuck** [comment]
@mariogarranz You can also try the following:
```app.loader.getHandler("texture").imgParser.crossOrigin = "anonymous";```

**Comment by mariogarranz** [comment]
Thanks @slimbuck.

The issue is happening when loading player avatars from Facebook. I wish I could create a repro project but I really have a lot of stuff to work on today and can't invest much time on this right now.

If you still can't figure it out during the weekend I will try to create a project to replicate it.

**Comment by slimbuck** [comment]
@mariogarranz No worries, I understand.

The only issue I can see with the latest release is that the following no longer works (CORS is not enabled):
```app.loader.getHandler("texture").crossOrigin = "anonymous";```

If you have always done that in your project, then this will shortly be fixed. If you weren't enabling CORS on the texture handler anyway then I'm still not sure what the issue might be.

**Comment by mariogarranz** [comment]
Using

**Comment by slimbuck** [comment]
Here is a build with the latest change if you have a chance to try @mariogarranz 

[playcanvas.js.zip](https://github.com/playcanvas/engine/files/4804350/playcanvas.js.zip)

**Comment by yaustar** [comment]
We created a project that creates the same error and the 1.28.6 release should fix this issue. Thank you for your patience and understanding!

**Comment by slimbuck** [comment]
Going to close this. Please reopen if necessary!
