### ISSUE TITLE
Cloning a disabled entity, then enabling the clone renders without being added to scene graph

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2183]
Project: https://playcanvas.com/project/696174/overview/cloned-entities-with-no-parents

Cloning a disabled entity and enabling the clone renders the cloned entity with it having a parent

**Comment by yaustar** [comment]
Looks related to this bit of code where if the parent is null, the onEnable functions are called of all the components on the pc.Entity: https://github.com/playcanvas/engine/blob/master/src/scene/graph-node.js#L142

Is this meant to be an '&&' instead of '||'?

**Comment by Maksims** [comment]
> Is this meant to be an '&&' instead of '||'?

It cannot be && as this will lead to never executing, and if parent will be null will lead to exception.

**Comment by yaustar** [comment]
Sorry, I was thinking of when I said `&&`:
```
if (this._parent && this._parent.enabled)
```

**Comment by mvaligursky** [comment]
> Sorry, I was thinking of when I said `&&`:
> 
> ```
> if (this._parent && this._parent.enabled)
> ```

I agree with this, in case enabled is true in the function. If enabled is false, we need to call it as well to disable child subtree in the hierarchy
