### ISSUE TITLE
Consider using ImageBitmap API to load images

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2185]
API: https://developer.mozilla.org/en-US/docs/Web/API/ImageBitmap
ImageBitmap provides an asynchronous and resource efficient pathway to prepare textures for rendering in WebGL

Issue: I created a project in Editor with single cube, material, and attached 6 large jpg textures on the material. Textures are marked as not for preload, to start the application ASAP and load textures later. Each time a texture is loaded, profiler shows around 100ms being spent on main thread to upload the texture to WebGl, large part of which is Image Decode.

<img width="995" alt="Screen Shot 2020-06-22 at 1 55 13 PM" src="https://user-images.githubusercontent.com/59932779/85289962-1c38db80-b490-11ea-95a4-3efcdde5a4af.png">

It's possible this cost could be removed by using the mentioned API.

Some other references:
https://wiki.whatwg.org/wiki/ImageBitmap_Options
https://threejs.org/docs/#api/en/loaders/ImageBitmapLoader

Note: Not supported by all browsers.

**Comment by kungfooman** [comment]
That would be great, I have the same problem, it causes quite some lags in the first seconds of a game (and whenever models are dynamically added):

![image](https://user-images.githubusercontent.com/5236548/85298843-d9cdc980-b4a4-11ea-82c6-d1e5a1ecc8de.png)

**Comment by slimbuck** [comment]
We could also possibly compile a c++ png decoder to webassembly. The benefits would be:
- decode on a web worker
- works on safari
- would fix the iOS PNG premultiplied alpha issue

**Comment by willeastcott** [comment]
I like it. Why use PNG when you can just use WebP?

**Comment by leonidaspir** [comment]
> 
> 
> We could also possibly compile a c++ png decoder to webassembly. The benefits would be:
> 
>     * decode on a web worker
> 
>     * works on safari
> 
>     * would fix the iOS PNG premultiplied alpha issue

This is JS PNG decoder, quite fast: https://github.com/photopea/UPNG.js
