### ISSUE TITLE
glB will load alright, but the mapping.json call will not (CORS)

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#2194]
I have had help from the forum already in relation to loading of glB, and after much help in there plus source gathering on a lot of other places (Google my webhotel provider, Fiverr etc.) I made it work.

Now when I try to load the texture alongside, the image does appear, but without the proper mapping. As I have solved the CORS issue in general (the main things loads), I urge you to make a fix that solves; load of mapping.json.

* URL to a simple, reproducible test case that illustrates the problem clearly: my uploaded test (will be visible for 14 days approx) http://www.amfibios.dk/Deson/assets/m2/index.php
* Screenshots
![image](https://user-images.githubusercontent.com/6838800/85521995-5b3c6d80-b605-11ea-99fe-54d0f784c6a5.png)

* The platform(s)/browser(s) where the issue is seen: Chrome
* A screenshot of http://webglreport.com/ (for graphics related issues)
Not sure such performance-benchmarks are needed

### Steps to Reproduce

1. the glb-load functional code (if needed):
"
var LoadGlbExternalFX = pc.createScript('loadGlbExternalFX');
LoadGlbExternalFX.attributes.add('url', {type: 'string'});
LoadGlbExternalFX.attributes.add('url_Texture', {type: 'string'});
LoadGlbExternalFX.attributes.add('localEnt', {type: 'entity'});

// initialize code called once per entity
LoadGlbExternalFX.prototype.initialize = function() {

    var app = this.app;
    var self = this;

     self.app.loader.getHandler("texture").crossOrigin = "anonymous";

        app.assets.loadFromUrl(self.url, 'model', function (err, asset) {
            // Add the loaded scene to the hierarchy
            self.entity.addComponent('model', {
                asset: asset,
                material: self.app.assets.get(30625063).resource
            }); 
        });
     

    //2; NB ANDRE-modeller - Farve/diffuse (@1) + Glosiness (@2):
};

LoadGlbExternalFX.prototype.update = function(dt){
     var app = this.app; var self = this; var image = new Image();
    console.log("self.entity.model.asset: "+self.entity.model.asset);
    if(self.entity.model.asset.toString() ==="-53"){ console.log("self.entity.model.mat: "+ self.entity.model.material);
    
   app.assets.loadFromUrl(self.url_Texture, 'texture', function (err, asset) {
    // Add the loaded scene to the hierarchy
            console.log("AS: "+asset.resource); 
            //1; NB KUN Foxy-model (@0):
            image.src = self.url_Texture;
            var texture = new pc.Texture(self.app.graphicsDevice);   
           texture.setSource(image);
        
    var assetTex = new pc.Asset("myTexture", "texture", {
        url: self.url_Texture
    });
   
    
    self.app.assets.add(assetTex);
        
            var meshes = self.entity.model.model.meshInstances; console.log("MIL: "+assetTex.resource); 
        
            var colorR = 58/255; var colorG = 50/255;var colorB= 47/255;  
                          for(var i=0; i<meshes.length; i++){ 
                              var mesh = meshes[i];
                              mesh.material.diffuseMap = asset.resource;
                              mesh.material.update(); 
                        }
         
            self.app.assets.load(assetTex);
        });
    } else{console.log("FALSE");}
};"

**Comment by FutureFireplace** [comment]
PS: The model and the texture+mapping that came along the sketchfab-bought model, works perfectly as local playcanvas-FBX

**Comment by yaustar** [comment]
The CORs issue is usually a server setup issue where the resource is hosted.

Trying it myself, 'https://www.amfibios.dk/Deson/assets/monkey/Mist.mapping.json' gives 404 error. Can you double check that the file is there?

**Comment by FutureFireplace** [comment]
The 'mapping.json' does not seem to be an independent file.
As it rather looks like being part of the total realtime-unfolded glB-file, I chose to write in here ... there must be engine-coders who knows the flow of the glB-loadhandling in PC? While exporting the glB in Blender, there is (for instance) 15-20 settings to set (amongst those 4 in regards to material and mapping of the object ... settings that are packed into binary file - should such settings not be readable/transferable to the mapping.json parser?)

**Comment by FutureFireplace** [comment]
Meanwhile; I did find this (a post of yours): https://github.com/playcanvas/editor/issues/76  ... but in my mind that sounds like 'the system' of my exported project, is trying to download the glB-file? Again; are there resources to how this works and/or does anybody else in here know what is up and down? :-)

**Comment by yaustar** [comment]
I think I see the issue here.

A GLB file is a container that can contain meshes, animations, materials, textures etc.

At the moment, you are loading it as a model asset:
```
    app.assets.loadFromUrl(self.url, 'model', function (err, asset) {
```
Which I believe means that you are only taking the mesh (model) part of it. And as you know, every model asset in PlayCanvas normally has an accompanying mapping.json file in the same directly as the model asset that maps materials to the mesh instances.  

From the looks of things, it feels like you should be loading the GLB file as a container asset as shown in this example:
https://playcanvas.com/editor/scene/922242

Code: https://playcanvas.com/editor/code/655732?tabs=30952649

This will give you access to all the container assets. 

It be also worth looking (and using) the GLTF viewer in the engine to get a better idea on how to access the assets that are loaded from the GLB: https://github.com/playcanvas/engine/blob/master/tools/viewer/src/viewer.js#L351

**Comment by yaustar** [comment]
Looking at your current GLB, the materials are not part of the container: https://playcanvas.com/editor/scene/944286

**Comment by FutureFireplace** [comment]
great info + approach ... will have a look at it

**Comment by FutureFireplace** [comment]
Tried it and 'we' might still have problem: http://www.amfibios.dk/Deson/assets/m3/index.php
 - yes the mapping.json seem to be working alright now, but the actual uw-mapping is still wrongly handled (while being fetched as a external .jpg alongside the .glB-file). Could it be related to the two sets of texcoord? (texcoord0 and texcoord1 -> I have previously been subject to altering those in relation to editor material/texture settings)

**Comment by FutureFireplace** [comment]
Ok, with a little help from blender-versions (exported by 2.83 instead of 2.79) it worked ... still having trouble with the external texture though (but not super-essential for my plans) - I consider this solved for now (my model is quite highend and might be ready for these handling types) //thx

**Comment by slimbuck** [comment]
@FutureFireplace is it possible to share with me the FBX that didn't load correctly? If there is an issue with the glb loader we'd like to know about it!

**Comment by FutureFireplace** [comment]
Hello Donovan/@slimbuck. Saw that Kevin/@yaustar closed the issue, but for formalities/general github service-mindness sake here is an update for my personal progression within the issue: I found some methods that seem to work much better, and as a parallel  my grasping of both Blender-side and PlayCanvas-side is much better in relation to UV-mapping/textures/materials etc.
