### ISSUE TITLE
Optimize bone skinning system - matrices

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2202]
At the moment this is the skinning matrix operations:
- scene hierarchy store Mat4 worldMatrices as an input for skinning
- we invert root node world matrix of the character hierarchy
- for each bone of the character:
    - we multiply its world matrix with inverted root matrix to have it in root space
    - we multiply this result with default pose
    - when mesh is visible, we write all these matrices to GPU (either float texture, or uniforms)

The last loop is 2 Mat4 multiplies, and a copy, costing us about 0.5ms on CPU for a test character.

Proposal:
- change shader code to use transposed matrix of 4x3 size, allowing us to drop 4 floats.
- change matrix multiplies to use 4x3 matrix part only, saving 25% of the cost
- perhaps inline transpose into it (write results transposed) to avoid extra copy.

**Comment by mvaligursky** [comment]
Note: batching code is using the same system (in a lots simpler way - just a matrix copy) and would need to be adjusted as well.

**Comment by wdl000001** [comment]
> Note: batching code is using the same system (in a lots simpler way - just a matrix copy) and would need to be adjusted as well.

What should I do to render skinned mesh? I tried to set the render.batchGroupId directly, but the skeleton animation won't work.

**Comment by wdl000001** [comment]
> > What should I do to batch render skinned mesh?
> 
> Note that this is not supported, see here: #3543

I see some code in the engine source code that seems to be related to it, such as SkinBatchInstance, skinBatchTex. Aren't they used to support batch rendering of skinned mesh?

**Comment by mvaligursky** [comment]
> I see some code in the engine source code that seems to be related to it, such as SkinBatchInstance, skinBatchTex. Aren't they used to support batch rendering of skinned mesh?

Those are not related to batching of skinned meshes, but it are related to dynamic batching of normal meshes, that use skinning under the hood to allow individual meshes to be moved (by a bone) while still being rendered using a single draw call. This is the example demonstrating this: https://playcanvas.github.io/#/graphics/batching-dynamic
It has 7 draw calls for all of this.
