### ISSUE TITLE
WebXR broken in latest update

### ISSUE THREAD

**Issue by benunbnd** [playcanvas/engine#2209]
### Description

Since the engine moved to ES6, WebXR has stopped working in PlayCanvas. If you launch the WebXR UI example project ([https://playcanvas.com/project/460449/overview/webvr-ray-input](https://playcanvas.com/project/460449/overview/webvr-ray-input)) it works through the play link but not launching through the editor. In my own projects after doing some testing it appears that ```xr.isAvailable ('immersive-ar')``` will always return false, even if AR is supported. On the tutorial link above, both the AR and VR button are disabled.

**Comment by willeastcott** [comment]
This is now fixed by #2210 and deployed yesterday as [Engine v1.30.0](https://github.com/playcanvas/engine/releases/tag/v1.30.0).
