### ISSUE TITLE
pc.inherits works only when constructor arguments are all the same

### ISSUE THREAD

**Issue by Nigh7Sh4de** [playcanvas/engine#221]
By passing the same `arguments` object in `core_inheritance.js:58` to both the `Super` and `Self` constructor you are forcing the same arguments to be given to every constructor function in the inheritance chain.

For example:
If I create a function `Enemy` which inherits from `Entity` and takes a `type` parameter, then when my `Enemy` is created, due to the way that the `Entity` constructor is set up, `Enemy._app = type` which is clearly wrong. 

Instead one should be able to specify how the `Super` constructor gets executed (ie with what parameters\arguments)

**Comment by daredevildave** [comment]
`pc.inherits` has been deprecated in favor of `Object.assign`

**Comment by Nigh7Sh4de** [comment]
Thanks for resolving this :D
