### ISSUE TITLE
Setting 0 to element.text results in an empty string being set

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2220]
https://github.com/playcanvas/engine/blob/master/src/framework/components/element/text-element.js#L1217

value when `0` resolves to false

**Comment by LeXXik** [comment]
Probably the line in question is:
https://github.com/playcanvas/engine/blob/bd1a927fed6887b0e73fbd5ed0c1fe1de58a5981/src/framework/components/element/text-element.js#L1212
