### ISSUE TITLE
Support for glTF texture extensions

### ISSUE THREAD

**Issue by godiagonal** [playcanvas/engine#2224]
### Description
I am using the recently introduced `preprocess`, `process` and `postprocess` callbacks in the GLB parser (great feature, thank you!) and noticed there is no way to process extensions for textures. The texture callbacks receive image data instead of texture data which means there is no way to access the extension data for a texture. This is a bit limiting and also confusing. To my knowledge extensions on texture objects is far more common than on image objects.

I propose that the current texture callbacks are renamed "image callbacks" and that new texture callbacks, which use texture data, are added.

**Comment by slimbuck** [comment]
Hi @godiagonal,

Yes this makes sense.

There is a slight complication in that multiple gltfTextures can reference a single gltfImage (meaning a single image could result in multiple textures, each with different filters/wrapping modes). We currently ignore this possibility and create a single texture per image.

I'll try sort that detail and make the callback changes you suggest.

Thanks!

**Comment by godiagonal** [comment]
Great to hear, thanks!

**Comment by slimbuck** [comment]
Hi @godiagonal,

I am busy looking at exposing this better. Could you perhaps explain your use case for accessing texture extensions? From your perspective, where would like to intervene in the loading process and what information do you need?

Thanks!

**Comment by slimbuck** [comment]
It seems standard gltf texture extensions specify an alternative gltfImage index to use and very little else.

In the texture process step are you wanting to make the choice of gltfImage or are you packing other information into the texture extension block? If you are, then must you use that extension information to construct the texture or do you want to post-process with this info?

**Comment by godiagonal** [comment]
My use case is that the application relies on a custom glTF extension to specify encoding like so:

```json
"textures" : [
  {
    "source": 0,
    "extensions": {
      "ANI_texture_hdrencoding": {
        "encoding": "RGBM"
      }
    }
  }
],
```

For this a `postprocess` callback with args `gltfTexture` and `texture` would suffice.

**Comment by slimbuck** [comment]
Thanks @godiagonal, that's a great use of extensions. (We might look to do something similar in our backend pipeline).

Texture callbacks now take the following structure (as you know they took gltfImages before):
'''javascript
preprocess(gltfTexture);
processAsync(gltfTexture, gltfImages, callback);
postprocess(gltfTexture, textureAsset);
'''

Image callbacks now look as follows:
'''javascript
preprocess(gltfImage)
processAsync(gltfImage, callback)
postprocess(gltfImage, textureAsset)
'''

Seems like this will cover your use case too.

**Comment by godiagonal** [comment]
Fantastic, thank you! This should definitely cover my use case. I will try it out as soon as it's released.
