### ISSUE TITLE
Object.freeze all constants in engine

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2246]
Currently the constants in the engine are all over-writable which can lead to undefined behaviour in the engine and issues that are hard to debug as the symptom is rarely close to the cause.

We can use [Object.freeze](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) to prevent them from being overwritten at the expense of some code bloat.

Example:
```
Object.defineProperties(Vec3, {
    ZERO: { value: new Vec3(0, 0, 0) },
    // etc
});
Object.freeze(Vec3.ZERO);
```

Test code: 
```
console.log(pc.Vec3.ZERO);
var foo = pc.Vec3.ZERO;
foo.x = 3;
console.log(pc.Vec3.ZERO);
pc.Vec3.ZERO = new pc.Vec3(0, 0, 3);
console.log(pc.Vec3.ZERO);
```  

Output:
```
Vec3 {x: 0, y: 0, z: 0}
Vec3 {x: 0, y: 0, z: 0}
Vec3 {x: 0, y: 0, z: 0}
```

**Comment by willeastcott** [comment]
Fascinating. I had never heard of `Object.freeze` before. Sounds good to me.
