### ISSUE TITLE
Phong material should ignore skybox cubemap

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#225]
When you create a default box in a scene with prefiltered skybox assigned, the default phong material that is on all primitives reflects the skybox. Should we either:

- ignore prefiltered skybox for phong materials
- change the default material used on primitives to have reflectivity = 0.
?

**Comment by guycalledfrank** [comment]
I think we should ignore it, because it doesn't work as expected anyway.

**Comment by daredevildave** [comment]
sounds good, can we get this fixed as this will be visible with the new deploy.

**Comment by guycalledfrank** [comment]
Yeah almost done

**Comment by guycalledfrank** [comment]
It should be fixed
