### ISSUE TITLE
Loading a material after cubemap loaded doesn't assign cubemap

### ISSUE THREAD

**Issue by yusjoel** [playcanvas/engine#2262]
Project: https://playcanvas.com/project/701726/overview/test

### Steps to Reproduce

1. Luanch project, cube is fine
2. find cubemap/Helipad, check Preload, launch project, cubemap is missing.

https://github.com/playcanvas/engine/blob/master/src/resources/material.js#L303
please use "assetReference.asset.loaded", cubemapAsset.resource can be null after loaded

**Comment by terence-wang** [comment]
The same situation exists when setting the skybox after monitoring the cubemap resource loading is completed

**Comment by slimbuck** [comment]
Thanks for this issue @yusjoel and the simple repo - much appreciated!

**Comment by slimbuck** [comment]
@terence-wang do you perhaps a repro for the skybox case?
