### ISSUE TITLE
Why is the loading interface suddenly black? 

### ISSUE THREAD

**Issue by 861172923** [playcanvas/engine#2265]
I changed the style of the load interface,
But all of a sudden when I load it, it goes black and I change it

`var createCss = function () {

    var css = [
        'html {',
        '   height: 100%;',
         '   background-color: transparent;',
        '}',
        'body {',
         '   background-color: transparent;',
        '}',

        '#application-splash-wrapper {',
        // '    background-color: #009AB6;',
        '   background-color: transparent;',
        '    position: absolute;',
        '    top: 0;',
        '    left: 0;',
        '    height: 100%;',
        '    width: 100%;',
        '    background-size: cover;',
        '}',

        '#application-splash {',
        '    position: absolute;',
        '    top: calc(50% - 28px);',
        '    width: 264px;',
        '    left: calc(50% - 132px);',
        '}',

        '#application-splash img {',
        '    width: 100%;',
        '}',

        '#progress-bar-container {',
        '    margin: 20px auto 0 auto;',
        '    height: 2px;',
        '    width: 100%;',
        '    background-color: #1d292c;',
        '}',

        '#progress-bar {',
        '    width: 0%;',
        '    height: 100%;',
        // '    background-color: 	#FFFFFF;',
        '    background-color: #f60;',
        '}',
        '@media (max-width: 480px) {',
        '    #application-splash {',
        '        width: 170px;',
        '        left: calc(50% - 85px);',
        '    }',
        '}'
    ].join("\n");

    var style = document.createElement('style');
    style.type = 'text/css';
    if (style.styleSheet) {
      style.styleSheet.cssText = css;
    } else {
      style.appendChild(document.createTextNode(css));
    }

    document.head.appendChild(style);
};

createCss();

showSplash();

app.on('preload:end', function () {
    app.off('preload:progress');

    
});
app.on('preload:progress', setProgress);
app.on('start', hideSplash);
});
![20200708_104851](https://user-images.githubusercontent.com/32476412/87125677-7b368700-c2bd-11ea-9f31-2e0ddcc08049.gif)

**Comment by yaustar** [comment]
This is an editor issue and I see that you have posted there so I'm going to close this.
