### ISSUE TITLE
IOS Safari Game breaking bug - [Error] WebGL: INVALID_ENUM: texParameter: invalid parameter name texParameteri

### ISSUE THREAD

**Issue by basharhamdan** [playcanvas/engine#2270]
### Description

Playcanvas does not work on safari browser on the iphone and ipad devices at all.
Here is the demo with nothing loaded in: [https://imgur.com/CTnW6Cc
[Consoleplaycanvasbmw.txt](https://github.com/playcanvas/engine/files/4906651/Consoleplaycanvasbmw.txt)
![WhatsApp Image 2020-07-11 at 3 09 02 PM](https://user-images.githubusercontent.com/25364080/87223039-94f1d000-c38a-11ea-94e5-116134d9cdf5.jpeg)

]

Here is the console error log on safari debug mode on mac: [https://pastebin.com/W7mGKuVM]

### Steps to Reproduce

1. Open bmw demo on iphone safari debug mode
2. check error list in console

**Comment by basharhamdan** [comment]
![WhatsApp Image 2020-07-05 at 3 53 14 PM](https://user-images.githubusercontent.com/25364080/87223069-dc785c00-c38a-11ea-9181-a66e70340f0c.jpeg)
Here is the ios version

**Comment by basharhamdan** [comment]
![WhatsApp Image 2020-07-11 at 3 29 51 PM (1)](https://user-images.githubusercontent.com/25364080/87223146-88ba4280-c38b-11ea-98e3-616c30c99713.jpeg)
![WhatsApp Image 2020-07-11 at 3 29 51 PM](https://user-images.githubusercontent.com/25364080/87223148-8952d900-c38b-11ea-8dfe-d906fee3f393.jpeg)
![WhatsApp Image 2020-07-11 at 3 29 48 PM](https://user-images.githubusercontent.com/25364080/87223151-89eb6f80-c38b-11ea-85ae-b2a18fa89e1e.jpeg)

more screenshots

**Comment by yaustar** [comment]
Is this with existing published projects, new projects or both?

**Comment by basharhamdan** [comment]
> Is this with existing published projects, new projects or both?

Both, I have a project deployed and the client reported customers are always complaining about safari browser not working. I have done tests with new builds and old, none worked.

**Comment by yaustar** [comment]
It's weird that existing published projects don't work as they don't get modified regardless of what we do 🤔

**Comment by yaustar** [comment]
![IMG_20200711_171921](https://user-images.githubusercontent.com/16639049/87228690-c4a8d400-c39a-11ea-975b-2c6029aef6f9.jpg)

iPhone 5S on iOS 12.4.5

**Comment by basharhamdan** [comment]
> ![IMG_20200711_171921](https://user-images.githubusercontent.com/16639049/87228690-c4a8d400-c39a-11ea-975b-2c6029aef6f9.jpg)
> 
> iPhone 5S on iOS 12.4.5

The one im testing on, and all the clients complaints seem to be coming from 13.5.1

**Comment by willeastcott** [comment]
Here's iPhone XS running 13.5.1:

![Image from iOS (3)](https://user-images.githubusercontent.com/697563/87229347-3b47d080-c39f-11ea-8046-699e9c12a2af.png)

**Comment by yaustar** [comment]
> The one im testing on, and all the clients complaints seem to be coming from 13.5.1

This is going to sound like a silly question: Are you and your clients in the same country?

**Comment by yaustar** [comment]
I've had a few members of the community try the car demo on their devices for 13.5.1 and so far have had no reports of issues.

It's really odd that you and your clients have this, especially with an older, already published build.

Could you check in the network tab of devtools for Safari to see if anything had failed to download? Maybe that will give some clues.

**Comment by basharhamdan** [comment]
Hello, so after intense debugging, and trying new things to fix this on the affected devices, i have found that the problem can be solved by toggling the expermintal features of WebGL and WebGPU on and off will fix this issue. I have worked with the client to put in the support channels as one of the fixes, and the reports came in as a good fix.

**Comment by yaustar** [comment]
> toggling the expermintal features of WebGL and WebGPU on and off will fix this issue.

Good find!

Were any of them on non default settings?

**Comment by basharhamdan** [comment]
> > toggling the expermintal features of WebGL and WebGPU on and off will fix this issue.
> 
> Good find!
> 
> Were any of them on non default settings?

Actually non were on non default settings, but messing around my team found the fix was this. IOS development in a nutshell...I am glad that nightmare was over.
