### ISSUE TITLE
Scope seems to be cloaked by certain code structure standard

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#2277]
Description:
While using certain code structure {this.app.graphicsDevice.on('resizecanvas', ... etc} PC seem to cloak an otherwise declared this.-var:

```
var ScrSizeChg = pc.createScript('scrSizeChg');

// initialize code called once per entity
ScrSizeChg.prototype.initialize = function() { 
    this.scrSzSC = false;
    
    this.app.graphicsDevice.on('resizecanvas', function(width, height) {
        console.log("canvas resized: "+ width +"::"+ height + " : SCRSZCHG: "+ this.scrSzSC);
    });
};
```

Providing as much information as possible. Include (where applicable):

* URL: _https://playcanvas.com/editor/scene/955290_   + method also referenced here: _https://forum.playcanvas.com/t/onaspectratio-camera-change-event/2696_
* The platform(s)/browser(s) where the issue is seen: _Chrome_

**Comment by slimbuck** [comment]
scope is an optional this parameter to pc.EventHandler.on, see https://developer.playcanvas.com/en/api/pc.EventHandler.html#on

**Comment by FutureFireplace** [comment]
ok, got it working (will try the forum in similar cases, on forward)
