### ISSUE TITLE
Type error in graphics_shader.js

### ISSUE THREAD

**Issue by amerkoleci** [playcanvas/engine#228]
In function createShader the line addLineNumbers(src) should be addLineNumbers(error)

**Comment by willeastcott** [comment]
I don't think this is the case. The line is:

              logERROR("Failed to compile " + typeName + " shader:\n\n" + addLineNumbers(src) + "\n\n" + error);

addLineNumbers prepends a line number to each line of shader source (the string held in 'src') and then, lastly, the error returned from WebGL is printed (with no line numbers required).

**Comment by amerkoleci** [comment]
Ok sorry then, closing now, thank you
