### ISSUE TITLE
No more than 2 key presses register

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#230]
Try the following script:

    pc.script.create('key', function (app) {
        // Creates a new Key instance
        var Key = function (entity) {
            this.entity = entity;
        };
    
        Key.prototype = {
            // Called once after all resources are loaded and before the first update
            initialize: function () {
            },
    
            // Called every frame, dt is time in seconds since last update
            update: function (dt) {
                var keyboard = app.keyboard;
    
                // Detect a chord
                var held1 = keyboard.isPressed(pc.KEY_1);
                var held2 = keyboard.isPressed(pc.KEY_2);
                var held3 = keyboard.isPressed(pc.KEY_3);
                var held4 = keyboard.isPressed(pc.KEY_4);
    
                var msg = "";            
                if (held1) msg += "1 ";
                if (held2) msg += "2 ";
                if (held3) msg += "3 ";
                if (held4) msg += "4 ";
                console.log(msg);
            }
        };
    
        return Key;
    });

A maximum of 2 key simultaneous key presses will ever register.

**Comment by daredevildave** [comment]
This is almost certainly a hardware limitation. Most keyboards can only detect limited keypresses (plus modifiers)

**Comment by willeastcott** [comment]
Can we please verify that? It's surprising to me. What happens on your Mac?

**Comment by daredevildave** [comment]
http://gaming.stackexchange.com/questions/6669/how-do-i-remove-the-limit-on-pc-keyboard-button-presses

**Comment by willeastcott** [comment]
So @Maksims recommended me a laptop with a crap keyboard. Grrr.

**Comment by Maksims** [comment]
Please try this script: http://jsfiddle.net/6mjjspdn/
Press more than 2 buttons, if keyCodes appear for more than two keys, then it is engine issue.

**Comment by willeastcott** [comment]
I can confirm that this script works on my keyboard.
