### ISSUE TITLE
pc.TransformFeedback example not working

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2300]
The `pc.TransformFeedback` [example from the docs](https://developer.playcanvas.com/en/api/pc.TransformFeedback.html) is not working.

[Demo project](https://playcanvas.com/project/704264/overview/transform-feedback)

![image](https://user-images.githubusercontent.com/5677782/87921303-087a9800-ca83-11ea-9926-9957a52950b7.png)

**Comment by mvaligursky** [comment]
hey thanks for the report .. I fixed the example. To fix the project, just remove 3 lines with "tangent" in it from shader code - the engine does not use tangents anymore.

**Comment by mvaligursky** [comment]
I added small engine test example for this
http://playcanvas.github.io/#graphics/transform-feedback.html
