### ISSUE TITLE
Line render issue

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/engine#2329]
# Description
I have noticed that a line render in combination with opacity makes the line almost unvisible on my iPhone X with iOS 13.5.1.

![OpacityDifference](https://user-images.githubusercontent.com/52896137/89062617-11af1300-d367-11ea-9f80-c4bfaf25f1d5.png)
[Sample scene](https://playcanvas.com/editor/scene/964731)

### Steps to Reproduce
1. Enable Device Pixel Ratio in the settings.
2. Create a line render and add a color with opacity.
3. Compare the visibility of the line on diffrent devices.

**Comment by willeastcott** [comment]
Lines are rendered 1 pixel wide. So this is exactly what I would expect to see, since pixels on your iPhone X will be physically smaller than those on your laptop screen. iPhone X has a physical resolution of 1125 x 2436.

**Comment by albertvanveen** [comment]
Hi Will! Thanks for your reply! Is there a way to make this more equal on both devices?

**Comment by willeastcott** [comment]
Well, what you want is to render a line which has fixed thickness in world space, let's say 1cm or something (instead of 1 pixel). To do that, you _could_ maybe render a long, thin cylinder. It would be kinda wasteful, but it'd work!

**Comment by Maksims** [comment]
Unfortunately WebGL native line renderer does not support consistently lines wider than 1 pixel. This is probably due to underlying GAPIs.
What you need, is to respect devicePixelRatio to compensate for visual pixel width. As pixels on iOS device are much smaller physically. Custom line renderer could do that, but it doesn't exist.

**Comment by albertvanveen** [comment]
For now I have applied Will's way. Hopefully there will be a line render with more options in the future.
