### ISSUE TITLE
Incorrect gpu size for PIXELFORMAT_L8_A8

### ISSUE THREAD

**Issue by yusjoel** [playcanvas/engine#2335]
### Description

in Profiler, VRAM used for PIXELFORMAT_L8_A8 texture is not correct.

Project: https://playcanvas.com/editor/scene/967049

### Steps to Reproduce

1.  Launch with Profiler
2. Click white button on top left
3. A plane with 4096x4096 PIXELFORMAT_L8_A8 texture appear, VRAM increase about 22MB
4. In Safari memory timeline, Layer increase 32MB

In pc.Texture.calcGpuSize():
```
_pixelSizeTable[PIXELFORMAT_L8_A8] = 1;  // <=== here, i think it's 2
```
In pc.Texture.gpuSize()
```
    gpuSize: {
        get: function () {
            var mips = this.pot &&
                    (this._mipmaps ||
                        this._minFilter === FILTER_NEAREST_MIPMAP_NEAREST ||
                        this._minFilter === FILTER_NEAREST_MIPMAP_LINEAR ||
                        this._minFilter === FILTER_LINEAR_MIPMAP_NEAREST ||
                        this._minFilter === FILTER_LINEAR_MIPMAP_LINEAR) &&  // <=== here
                        !(this._compressed && this._levels.length === 1);

            return Texture.calcGpuSize(this._width, this._height, this._depth, this._format, mips, this._cubemap);
        }
    },
```
My texture's mipmaps is disable, but minFilter is always FILTER_LINEAR_MIPMAP_LINEAR, and I cannot set it to FILTER_LINEAR.
In pc.GraphicDevice.setTextureParameters(), engine check texture._mipmaps, and change filter to FILTER_LINEAR, I dont know why engine check minFilter for calculate gpu size.

**Comment by mvaligursky** [comment]
Hi @yusjoel - thanks for reporting this, I agree with you on both points and have a fix PR.
