### ISSUE TITLE
Particle system stops rendering meshes at > 326 particles.

### ISSUE THREAD

**Issue by ChristianTucker** [playcanvas/engine#2336]
### Description

Minimum Repo Project: https://playcanvas.com/project/708534
Build: https://playcanv.as/b/1xhI8LmV/

Provide as much information as possible. Include (where applicable):

Whenever you increase the maximum particle count past 327 it will no long render the mesh provided. 
- Chrome, Brave, Edge 
![webgl2](https://user-images.githubusercontent.com/23084841/89410116-00a03200-d6d8-11ea-9c84-23190ea544a5.png)
![webgl1](https://user-images.githubusercontent.com/23084841/89410117-00a03200-d6d8-11ea-80be-4f7a61971faa.png)

### Steps to Reproduce

1. Create a new project
2. Upload any mesh to the project assets
3. Create a particle system
4. Apply the mesh to the particle system
5. Increase size to any number above 326

**Comment by LeXXik** [comment]
That number 326 is subject to your mesh only. The vertex buffer can store a limited amount of vertices. The buffer is finite and there is no way to stretch it.
To spawn more meshes, you should reduce amount of vertices the mesh has. You can also add another particle system to increase the overall particles count.
