### ISSUE TITLE
Bug on Audio Component with 3D positional sounds

### ISSUE THREAD

**Issue by devcem** [playcanvas/engine#2338]
Audio component has a bug for positional audio. For some reason SoundComponentData has no attributes like positional and slots, and because of that onUpdate function isn't working for looped and auto played sounds.

For bug reports, include:
Bug can be showed on this example project : https://playcanvas.com/editor/scene/967277

Reproduce :
1- Create a moving entity.
2- Set an audio file to it with sound component, make it loop and auto play, and positional.
3- Add audio listener to camera, so you can hear sounds 3D positional.

Issue is basically occurs on this line : 
https://github.com/playcanvas/engine/blob/6974f24081ac1a4900c3cce12a8e9220120f6710/src/framework/components/sound/system.js#L105

If I set "positional" and "slots" for componentData it works as expected.

I fixed that problem with this function :
```
this.entity.sound.data.positional = true;
this.entity.sound.data.slots = this.entity.sound.slots;
```

So https://github.com/playcanvas/engine/blob/6974f24081ac1a4900c3cce12a8e9220120f6710/src/framework/components/sound/data.js file requires slots and positional variables on that, so it can store data.

**Comment by slimbuck** [comment]
Hi @devcem,

This seems like quite a serious bug! Thanks so much for reporting it and providing a repro.

As you can see @willeastcott has submitted a fix and your example now works correctly with the latest engine.

Thanks again!
