### ISSUE TITLE
Optimize visibility calculation for skinned characters

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2352]
Visibility calculation for characters has a very high cost. It calls MeshInstance.aabb, which transforms bounding boxes of each bone into world space, ads them up, computes final  bounding sphere and uses this for frustum check.

In my test case with 100 characters of 70 bones each, this takes about 8ms on the MacBook Pro and it is about 10% of the frame.

Would could perhaps at init time evaluate the largest possible bounding box / let user specify it, and use this for early / the only culling.

Alternatively, instead of computing total bounding spheres for each bones, which has no early out, we could cull per bone, which would early out for any visible bone. Or test visibility of root bone of characters at least, before computing total bounding volume for bones.

**Comment by Maksims** [comment]
Calculating largest possible AABB based on animation keyframes, will work, but not for case when bones animated manually and gets complex when need to take morphing and animation groups in account.

First figuring out min/max AABB in local space, based on bones radius max(distanceFromParentBone, initialRadius), and then transforming it to world, probably will be much faster than current generic approach?

**Comment by mvaligursky** [comment]
@Maksims - in the current implementation, when mesh is loaded, we find bounds in bone space for all vertices a bone affects. (and even morphing is applied to those to enlarge those bounds by it per bone). Then each frame, we transform those per bone bounds by bone matrix into world space, and add them up to final bounds. It sounds like this is what you're suggesting or something else?
