### ISSUE TITLE
I want to DELETE PREFILTERED DATA in my project which use engine directly,or other way to solve my problem,thank you

### ISSUE THREAD

**Issue by qiansanwansan** [playcanvas/engine#2360]
In Editor,I cliked button named "PREFILTER CUBEMAP",the ground is here(picture's name:unnormal):
![unnormal](https://user-images.githubusercontent.com/18042499/90504442-a4331d00-e183-11ea-8711-92173b4c1f02.png)

I cliked button named "DELETE PREFILTERED DATA",the ground is here(this is what I want and this effect is good):
![normal](https://user-images.githubusercontent.com/18042499/90388958-45a26c00-e0bb-11ea-8ef9-78e882ebbeb0.png)

Then I downloaded this cubemap(contains a dds file and some pictures).

I load this cubemap in my new project named NewProject which use engine directly.,the code is here:
```
        var cubemapAsset = new pc.Asset('New Cubemap.dds', 'cubemap', {
            url: "../FYPlaycanvas/Cubemap/32569764/New Cubemap.dds"
        }, {
            // "minFilter": 5,
            // "magFilter": 1,
            // "anisotropy": 1,
            // "deletePrefilteredData": "New Cubemap.dds",
            "textures": [
                "../FYPlaycanvas/Cubemap/32569557/back.jpg",
                "../FYPlaycanvas/Cubemap/32569760/right.jpg",
                "../FYPlaycanvas/Cubemap/32569558/top.jpg",
                "../FYPlaycanvas/Cubemap/32569559/buttom.jpg",
                "../FYPlaycanvas/Cubemap/32569761/front.jpg",
                "../FYPlaycanvas/Cubemap/32569756/left.jpg",
                // left right top bottom front back
            ]
        });
        cubemapAsset.on('load', function () {
            app.scene.ambientLight = (0.2, 0.2, 0.2);
            app.scene.skyboxIntensity = 0.18; // 0.18
            app.scene.exposure = 8; // 8
            app.scene.fog = pc.FOG_NONE;
            app.scene.lightmapSizeMultiplier = 16;
            app.scene.lightmapMode = pc.BAKE_COLORDIR;

            app.scene.gammaCorrection = pc.GAMMA_SRGB;
            app.scene.toneMapping = pc.TONEMAP_FILMIC;
            app.scene.skyboxMip = 0; // Set the skybox to the 128x128 cubemap mipmap level
            app.scene.setSkybox(cubemapAsset.resources);

            app.setCanvasFillMode(pc.FILLMODE_FILL_WINDOW);
            app.setCanvasResolution(pc.RESOLUTION_AUTO);

            // for (var i = 0; i < 7; i++) {
            //     if (i == 0) {
            //         cubemapAsset.resources[i].type = 'rgbm';
            //     } else {
            //         cubemapAsset.resources[i].type = 'default';
            // type:pc.TEXTURETYPE_RGBE
            // type: pc.TEXTURETYPE_DEFAULT,
            //     }
            // }

        });
        cubemapAsset.loadFaces = true;
        app.assets.add(cubemapAsset);
        app.assets.load(cubemapAsset);

```
The cubemap in NewProject works well,but the ground did not,it is same as picture named unnormal,so I ask for help as this issue's title.thank you!

I also asked in forum :https://forum.playcanvas.com/t/what-does-delete-prefiltered-data-do-or-is-there-any-api-corresponding/14380/5

**Comment by slimbuck** [comment]
Hi @qiansanwansan,

When you click on "PREFILTER CUBEMAP" in the editor, it creates the DDS file. When you click on "DELETE PREFILTERED DATA" it removes the DDS file.

So, if you want to construct a cubemap in the engine without the DDS file, do:
```javascript
var cubemapAsset = new pc.Asset('New Cubemap.dds', 'cubemap', null, {
    "textures": [
...
```
instead of:
```javascript
var cubemapAsset = new pc.Asset('New Cubemap.dds', 'cubemap', {
    url: "../FYPlaycanvas/Cubemap/32569764/New Cubemap.dds"
}, {
    "textures": [
...
```

Hope that helps.

**Comment by qiansanwansan** [comment]
According to what you said, this sky box is really what I want.
but my ground model and other models are so dark:
<img width="362" alt="dark" src="https://user-images.githubusercontent.com/18042499/90460864-6dcfb080-e137-11ea-9a77-4e01edb47f45.png">
May be I should set something,could you tell me,thank you.

**Comment by slimbuck** [comment]
Hi @qiansanwansan,

I'm sorry, but without access to both the editor project and engine-only project it's very difficult to guess what the problem might be.

I can only suggest that you tackle lighting one element at a time:
1. disable all lighting in the editor apart from the cubemap
2. now get your engine project to look identical with only the cubemap and no other lighting
3. enable one light in the editor (to make things easier you can even disable the cubemap for now)
4. get your engine project to look identical with just the one light
5. continue step 3 and 4 until all lights are identical between the two

At each step check that all the settings are the same - color, intensity, exposure etc.

Hope that helps.

**Comment by qiansanwansan** [comment]
Thank you,@slimbuck ,
In my Editor,Skybox has no effect on the model, whether I turn skybox off or on,and this is right.
but in my new project with engine,my code like this:
```
var cubemapAsset = new pc.Asset('New Cubemap.dds', 'cubemap', null, {    
            "textures": [
                "../FYPlaycanvas/Cubemap/32569557/back.jpg",
               ...
            ]
        });
        cubemapAsset.on('load', function () {
           ....
            app.scene.skyboxMip = 0;
            app.scene.setSkybox(cubemapAsset.resources);
```
my scene's screenshot is here:
![截屏2020-08-18 18 05 12](https://user-images.githubusercontent.com/18042499/90500709-d6418080-e17d-11ea-92c3-db449be7b0a0.png)
the skybox is good,but all models are so dark.

but when my code like this:
```
var cubemapAsset = new pc.Asset('New Cubemap.dds', 'cubemap', null, {    
            "textures": [
                "../FYPlaycanvas/Cubemap/32569557/back.jpg",
               ...
            ]
        });
        cubemapAsset.on('load', function () {
           ....
            app.scene.skyboxMip = 0;
            // app.scene.setSkybox(cubemapAsset.resources);
```
YES,I did not set my skybox.
my scene's screenshot is here:
![截屏2020-08-18 18 11 03](https://user-images.githubusercontent.com/18042499/90500969-359f9080-e17e-11ea-8106-482b39db8fc8.png)

I don't know if this will give you some clues to help me solve the problem.Thank you

**Comment by slimbuck** [comment]
Hi @qiansanwansan,

Did you mange to resolve your issue here? As I said before, it's very difficult to help out without access to your project.

I will resolve for now, but please reopen if you have any further questions.

Thanks!
