### ISSUE TITLE
Typescript definitions fixes

### ISSUE THREAD

**Issue by NokFrt** [playcanvas/engine#2363]
pc.BoundingSphere
- would it be possible to make "center" and "radius" public properties? BoundingBox also has center and halfExtents public.

pc.TouchEvent/pc.MouseEvent/pc.KeyboardEvent
- type of the property "event" is Event not pc.TouchEvent/pc.MouseEvent/pc.KeyboardEvent

Thanks
Tomas

**Comment by willeastcott** [comment]
This issue is now fixed.

The `BoundingSphere` properties have been exposed in the API for some time now, and therefore also appear in the TS declarations (see #3387).

The `event` property of `KeyboardEvent`, `MouseEvent` and `TouchEvent` are now correctly typed (see #3845).
