### ISSUE TITLE
User created shader chunk breaks on publish, works fine in Editor

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2369]
Project: https://playcanvas.com/project/710112/overview/particle-breaks-on-publish
Published build: https://playcanv.as/p/F52MVTvc/

Error message in published build:
```
ERROR: 0:57: 'vPositionW' : undeclared identifier
ERROR: 0:57: 'y' :  field selection requires structure or vector on left hand side
```

**Comment by mvaligursky** [comment]
is this what @raytranuk was looking at recently?

**Comment by raytranuk** [comment]
The end result of this issue is a PR from Max: https://github.com/playcanvas/engine/pull/2454 - which allows the custom fog shader chunk to avoid the bit that crashes if it is a particle material.
