### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by yushimatenjin** [playcanvas/engine#2372]
### Description

Using Node.js I get a window is not defined when importing node modules from playcanvas.

I updated the version of PlayCanvas from 1.32.3 to 1.34.0, and now I get this error.

#### Versions

- Node.js : v14.8.0
- playcanvas: v1.34.0
- macOS Catalina 10.15.5

### Steps to Reproduce

1. npm install playcanvas
2. import playcanvas package

**Error**

```jsx
> const playcanvas = require("playcanvas")
Uncaught ReferenceError: window is not defined
at /Users/yushimatenjin/workspace/playcanvas/node_modules/playcanvas/build/playcanvas.js:405:2
at /Users/yushimatenjin/workspace/playcanvas/node_modules/playcanvas/build/playcanvas.js:440:3
at /Users/yushimatenjin/workspace/playcanvas/node_modules/playcanvas/build/playcanvas.js:7:65
```

**Error line**

playcanvas.js:405:2

```jsx
window.setupVertexArrayObject = function(gl) {...
```

**Comment by marklundin** [comment]
This looks like it's the polyfill for `OES_vertex_array_object` is this something that can be modified so that it doesn't add to the window global, or is that actually part of the spec?

**Comment by willeastcott** [comment]
I believe PlayCanvas no longer has a problem running in Node.js. Therefore, I am closing this issue. If you believe a problem still remains @yushimatenjin, please reopen the issue.
