### ISSUE TITLE
Margin precision in editor

### ISSUE THREAD

**Issue by Cr0c81** [playcanvas/engine#2380]
Margin values rounded to 1/100, can not set 1/1000 and less.
If screen is 1900+ size - margin minimal distance is 19+px (((

**Comment by ellthompson** [comment]
Hi there, we have a dedicated repo to track editor specific issues: https://github.com/playcanvas/editor/issues . Would you mind recreating the issue there? It would also be great if you could provide an example / screenshot of the issue you're experiencing.

Thanks!

**Comment by Cr0c81** [comment]
Done
