### ISSUE TITLE
Samsung S9 Internet Browser stretches the screen

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2386]
See thread here: https://forum.playcanvas.com/t/samsung-internet-browser-canvas-resolution-wrong/12272/3

Unsure if this is an Editor issue with the generation of the HTML page or an engine issue.

![image](https://user-images.githubusercontent.com/16639049/91294766-f088e900-e791-11ea-9a0c-2499bb494552.png)

**Comment by Cr0c81** [comment]
If build on playcanvas (playcan.as) bug is absent.

**Comment by yaustar** [comment]
Sample project with this issue: https://playcanvas.com/project/708548/overview/image-stretch

**Comment by LeXXik** [comment]
Additional info: only the 2D Screen elements are stretched.

**Comment by yaustar** [comment]
Reproduced the bug on an S7 with an iframeless playcanvas link (adding `/e` before the `/p`). Looks like the iframe does something extra to resize the app correctly.

**Comment by yaustar** [comment]
A workaround for this is to change line 140 onwards in the __start__.js file from
```
app.loadScene(SCENE_PATH, function (err, scene) {
    if (err) {
        console.error(err);
    }

    app.start();
});
```

```
app.loadScene(SCENE_PATH, function (err, scene) {
    if (err) {
        console.error(err);
    }

    app.start();
    app.setCanvasResolution(app.resolutionMode);
});
```

I don't understand why calling `app.setCanvasResolution` after `app.start` matters as there is no change to the width/height of the canvas or window at this stage.

**Comment by yaustar** [comment]
Further investigation shows that changing the reflow function from:
```
    var reflow = function () {
        app.resizeCanvas(canvas.width, canvas.height);
        canvas.style.width = '';
        canvas.style.height = '';

        var fillMode = app._fillMode;

        if (fillMode == pc.FILLMODE_NONE || fillMode == pc.FILLMODE_KEEP_ASPECT) {
            if ((fillMode == pc.FILLMODE_NONE && canvas.clientHeight < window.innerHeight) || (canvas.clientWidth / canvas.clientHeight >= window.innerWidth / window.innerHeight)) {
                canvas.style.marginTop = Math.floor((window.innerHeight - canvas.clientHeight) / 2) + 'px';
            } else {
                canvas.style.marginTop = '';
            }
        }
    };
```
to
```
    var reflow = function () {
        canvas.style.width = '';
        canvas.style.height = '';
        app.resizeCanvas(canvas.width, canvas.height);

        var fillMode = app._fillMode;

        if (fillMode == pc.FILLMODE_NONE || fillMode == pc.FILLMODE_KEEP_ASPECT) {
            if ((fillMode == pc.FILLMODE_NONE && canvas.clientHeight < window.innerHeight) || (canvas.clientWidth / canvas.clientHeight >= window.innerWidth / window.innerHeight)) {
                canvas.style.marginTop = Math.floor((window.innerHeight - canvas.clientHeight) / 2) + 'px';
            } else {
                canvas.style.marginTop = '';
            }
        }
    };
```

Also fixes the issue and sets the width/height of the canvas to the correct height.

**Comment by LeXXik** [comment]
Thank you for looking into it, @yaustar !

**Comment by yaustar** [comment]
The alternative fix is to remove these two lines: https://github.com/playcanvas/engine/blob/master/src/framework/application.js#L1621

Will need to check what these are for. They might be related to different fill modes.

**Comment by yaustar** [comment]
For more context, the extra styling affects the value of `window.innerHeight` and width during the `application.resizeCanvas` function.

**Comment by yaustar** [comment]
This should be resolved now.
