### ISSUE TITLE
PlayCanvas + WebGL 2 doesn't work on iPadOS 14 beta

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2392]
See this report on Twitter:

https://twitter.com/iwgtest1/status/1298644918622195713

**Comment by slimbuck** [comment]
Does anyone on the team have an ipad? @mvaligursky are you able to test this on an emulated device?

**Comment by willeastcott** [comment]
I have an iPad that's maybe 2 years old. I can install iPadOS 14 on it sometime today.

**Comment by mvaligursky** [comment]
I tried in simulator (ipad 9.7" 4th gen and iPad pro 12" 2nd gen) - few engine examples I tried worked correctly, but it's so slow I cannot test all (20s to load example, 0.5fps running).

**Comment by willeastcott** [comment]
I just tried Seemore on my iPad Pro (10.5 inch) with iPadOS 14 beta (18A5357e). It works fine with both WebGL 1 and WebGL 2:

![Image from iOS](https://user-images.githubusercontent.com/697563/91841279-faa35f80-ec49-11ea-9e7c-beded0cc8081.jpg)

Therefore, I am closing this since we are unable to reproduce the issue. Please reopen if additional information becomes available.

**Comment by macguffin** [comment]
Hi I have found that no webGL content is working on iPad. I am testing on an iPad Air 2  software version (18A5357e)

None of these examples on other sites work either.

Do they work for you on your iPad Pro running iOS beta?

https://get.webgl.org/
https://webglsamples.org/

Thanks for your help.

**Comment by willeastcott** [comment]
Yes, everything works fine on my iPad Pro. If you are saying that *no* WebGL content runs on that device, that's a Safari bug and not a PlayCanvas bug so maybe consider opening a new issue on the WebKit project:

https://webkit.org/reporting-bugs/

**Comment by macguffin** [comment]
Thanks - yes I believe it is a webkit issue. I am just trying to find other iPad users on iPasOS14 to confirm the issue. I have already reported via the feedback tool but will also report via the link above.

Thanks for checking.
