### ISSUE TITLE
Texture based morphing + WebGL 2 doesn't work on iOS 14 beta

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2393]
float framebuffer extension is not support on WebGl 2 experimental release (EXT_color_buffer_float), even though it is supported on WebGl 1 device.

This will likely be fixed when the extension support is added, but creating this issue for visibility.

**Comment by mvaligursky** [comment]
Support for this is being implemented.
See:
- https://bugs.webkit.org/show_bug.cgi?id=216010
- https://github.com/KhronosGroup/WebGL/issues/3093
- https://github.com/KhronosGroup/WebGL/pull/3146

**Comment by willeastcott** [comment]
Just thought I would mention that I tried this in iOS 14.3 and it's still a problem (with WebGL 2 enabled - still not on by default).

**Comment by mvaligursky** [comment]
Could you please check in webglreport if EXT_color_buffer_half_float is exposed in webgl2 on your device now @willeastcott ? It was exposed in WebGl1 before, but it's expected to come to WebGl2 now as well.

**Comment by willeastcott** [comment]
It's not exposed in iOS 14.3. I'll try updating to iOS 14.4 Beta 2...

**Comment by willeastcott** [comment]
...it's not present in iOS 14.4 Beta 2 either. 😢

**Comment by mvaligursky** [comment]
EXT_color_buffer_half_float is present in iOS 14.5 public beta, and so this can be implemented now for future webgl2 on iOS.
