### ISSUE TITLE
Camera#screenToWorld nearClip/farClip division by zero breaks scene

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#2399]
I am working with some filigree models and in order to even see them I simply set quite a low `nearClip`, which constantly broke my scene, but I didn't know why, until I figured this problem out:

`w` can be `0` for a significant enough `nearClip`/`farClip` difference:

https://github.com/playcanvas/engine/blob/d96a75e5004c777ae7a7bae6c073d89ed265cc5e/src/scene/camera.js#L462

Minimal testing code for https://playcanvas.com/viewer:

```js
viewer.camera.camera.nearClip = 0.0001
viewer.camera.camera.farClip = 10000
viewer.camera.camera.screenToWorld(10, 10, 0.01);
V {x: Infinity, y: -Infinity, z: Infinity}
```

And then just use hold/move right-mouse for panning, because it relies on `Camera#screenToWorld`

This breaks the entire scene, as these Infinity values quickly escalate into `NaN` and then all sorts of variables are NaN'ed aswell, just because `nearClip`/`farClip` had some strange values. Not sure what would be a "proper" solution to prevent that the entire scene breaks, because of inherent floating point precision issues. Any ideas to prevent this?

**Comment by mvaligursky** [comment]
I change the implementation of the Camera.screenToWorld to handle this range, but it's possible that with this range some other functionality can fail as this gets precision of some numbers at the range of float for some calculations.
