### ISSUE TITLE
Integrate glb-parser material chunks into the engine

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2404]
In order to implement glb materials, glb parser contains some additional shader chunks:
https://github.com/playcanvas/engine/blob/0e3022cef2075f6c8fd7d49ffddd54521a68c0d9/src/resources/parser/glb-parser.js#L794-L881

These should be integrated into the engine chunk system, allowing glb parser to just set some options on material.

**Comment by raytranuk** [comment]
I will also investigate an alternative mapping of roughness to glossiness

**Comment by mvaligursky** [comment]
Done here now: https://github.com/playcanvas/engine/pull/4949
