### ISSUE TITLE
Positional sound is distorted

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2407]
I noticed the issue when we were making a game for jam event. When the audio is set as positional, it sounds distorted. Once positional setting is off, the distortion goes away.

I made a simple project to demonstrate. The setup is simple - a cube with a sound component that has a positional audio on a loop. You can hear cracks in the audio.

https://playcanvas.com/project/716838/overview/audio

**Comment by LeXXik** [comment]
Hmm, now I can't hear the distortion... Seems like there is some precondition that has to take place for it to appear.

**Comment by willeastcott** [comment]
The 'streamable' URL is no longer valid. Is this still an issue @LeXXik, or should we close this?

**Comment by Maksims** [comment]
Was it a crackling sounds? There are often issues with crackling sounds, and they seems like platform dependant.

**Comment by LeXXik** [comment]
Hmm, I haven't used any positionoal audio recently, but at least I cannot hear distortions from the project in the original post. We can close this.
