### ISSUE TITLE
Sprite Batching

### ISSUE THREAD

**Issue by davidpox** [playcanvas/engine#2412]
I love the recent addition of quickly creating frames for each sprite in a texture atlas, but in my opinion the texture atlas support in general (unless using animated sprites) is useless if we don't have any sort of sprite batching. If I have a menu screen with several buttons, special text, images, that can easily add up to 30+ drawcalls, which is going to kill performance especially on mobile devices

I see that in PR https://github.com/playcanvas/engine/pull/1623 of last year there was simple sprite batching added, but it doesn't seem to work nor is it exposed to any kind of editor menus

I think sprite batching is a key feature that a lot of developers will appreciate, and definitely necessary for well performing mobile games

**Comment by yaustar** [comment]
Is this about using sprite assets with the Sprite component and/or the UI system?

I can see we have the batch group exposed on the Simple Sprite and Element component but not the Animated Sprite.

**Comment by davidpox** [comment]
My bad, I do see that now. Does this batch same sprites only or is it batching all sprites on a texture atlas? The latter would be preferred because that's what will cause drawcalls to go down if you have separate sheets for each part of your game and aren't really reusing a lot of the same sprite

**Comment by yaustar** [comment]
It should be all sprites on the texture atlas. I'm not at a PC to check but should be easy to verify with Spectre.js browser plugin.

**Comment by yaustar** [comment]
Just tried it in a simple scene. All sprites are from the same atlas:

![image](https://user-images.githubusercontent.com/16639049/95247611-fb617f80-080d-11eb-9912-fe56e8de2129.png)

**Comment by davidpox** [comment]
Awesome! Would it be possible to have Sprite batching for 3D sprites too, not ones attached to an Element component, but rather sprites in a 3D scene? Currently there's no batch group field those those 
![Jdn53aOT](https://user-images.githubusercontent.com/7888472/95321777-6bfeaf80-0893-11eb-8454-4d15db1a3a32.png)

**Comment by yaustar** [comment]
Oh whoops. Sorry, this is my bad. I've forgot that I'm a super user and the batching of 3D sprites is in testing at the moment :swe

**Comment by mvaligursky** [comment]
I've confirmed normal Sprite batching works as expected, and has released the feature to the public. It should show up in Editor within few days, when it gets published.

I'm closing this, please ping here or new issue if you discover some problems.
