### ISSUE TITLE
Add draw call count to Mini Stats

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2416]
One of the more common stat points for developers is draw calls. If we can add this to the mini stats, that would be great!

**Comment by slimbuck** [comment]
if possible it would be nice to have the following changes made to mini-stats:
- have timers specify graph scaling (currently hard-coded to 48)
- have timers specify units (currently hard-coded to 'ms')
- give application control over graph sizing (currently only mouse clicks toggle graph sizes)
- give application control over which graphs to construct (currently all graphs are constructed)
- apart from draw calls, other stats that may be of use:
    - number of primitives (broken down by #triangles, #lines, #points)
    - batching stats (@mvaligursky has details)
