### ISSUE TITLE
Consider AVIF image format for future inclusion in the engine

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2418]
https://jakearchibald.com/2020/avif-has-landed/

AVIF is a new image format derived from the keyframes of AV1 video. It's a royalty-free format, and it's already supported in Chrome 85 on desktop. Android support will be added soon, Firefox is working on an implementation

**Comment by slimbuck** [comment]
See also https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4

TBH AVIF looks extraordinary, even compared to webP.

**Comment by marklundin** [comment]
As I understand it, the AVIF format would automatically work if the browser supports it? Would be great to use this. Also as it has a lossless compression, I'm wondering If it's possible to use with the LUT problem in #774

**Comment by mvaligursky** [comment]
It seems AVIF supports HDR but I suspect this might be 10-12bit precision vs full floats .. would that be enough?

**Comment by NicolasVZ777** [comment]
Any update on that topic? Or what about webp? Draco is working so well for meshes but regarding textures, if Im not mistaken, Playcanvas is only using JPG and PNG

**Comment by marklundin** [comment]
You can also use Basis compressed textures

**Comment by mvaligursky** [comment]
webp format inside glb should be supported I believe using EXT_texture_webp extension, I tested this a while back. See https://github.com/playcanvas/engine/pull/5360

You can also load webp as an assert.

But using it as a source in the Editor is not supported yet.

**Comment by willeastcott** [comment]
AVIF now support: https://blog.playcanvas.com/avif-webp-land-in-editor/
