### ISSUE TITLE
Error generating/loading cubemap

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2420]
I made a sample project here:
https://playcanvas.com/editor/scene/985695

Original HDRI is in `/src` folder.

My steps:

1. Download an HDRI image from HDRI Haven. I used this one, 2k version:
https://hdrihaven.com/hdri/?c=outdoor&h=shanghai_bund

2. Use online HDRI to Cubemap converter:
https://matheowis.github.io/HDRI-to-CubeMap/

3. The generated result is a a series of HDRI images used as sides for cubemap. I placed them in `/src` folder.

4. Editor auto generated PNG files from the HDRI ones during upload.

5. Since the editor didn't recognize the file naming pattern, I placed them manually into the cubemap slots:
naming convention: `px` = **P**ositive **X**, `ny` = **N**egative **Y**
```
      py
nx    pz    px    nz
      ny
```

The first and probably related issue can be seen that the cubemap failed to generate the thumbnails:
![image](https://user-images.githubusercontent.com/5677782/92589453-3e7a1280-f2a3-11ea-90ce-d52b8bd63939.png)
Error: `No texture resolution data available`

6. Set the cubemap for skybox in project Rendering settings.

7. Error thrown on app launch prevents it from starting:
![image](https://user-images.githubusercontent.com/5677782/92589738-af212f00-f2a3-11ea-8d38-c4381437209c.png)

**Comment by LeXXik** [comment]
Just for test, I also tried to generate the HDRI faces for cubemap using the [cmftStudio](https://github.com/dariomanesku/cmftStudio). It gives me the same result, unfortunately.

**Comment by slimbuck** [comment]
Hi @LeXXik sorry about this. It may be a backend issue. We're looking into it!

**Comment by slimbuck** [comment]
Can you check again please? Hopefully this is now sorted.

**Comment by LeXXik** [comment]
It works, thank you!
