### ISSUE TITLE
Expose the 'frame' in XR Manager

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2421]
To further help WebXR developers using PlayCanvas, we should expose the frame so that they aren't reliant on engine releases to access new XR features/functionality.

I'm thinking about having the update event also pass the frame variable?

https://github.com/playcanvas/engine/blob/master/src/xr/xr-manager.js#L460

From:
```
    this.fire('update');
```

To:
```
    this.fire('update', frame);
```

What do you think @Maksims ?

Related thread: https://forum.playcanvas.com/t/webxr-ar-is-this-possible-to-get-detected-planes-on-floor/14758/2

**Comment by Maksims** [comment]
Yep, sounds reasonable, I will make a PR to publicly expose session and frame objects.

**Comment by yaustar** [comment]
Thanks @Maksims
