### ISSUE TITLE
GL_INVALID_OPERATION : glBlitFramebufferCHROMIUM: src and dst formats differ for depth/stencil

### ISSUE THREAD

**Issue by Christopher-Hayes** [playcanvas/engine#2425]
### Description

On very specific Mac devices this WebGL error shows when using fog effects. Visually, it causes the fog effect to show in front of objects that are closer to the camera when it should be behind them. So far only seen this on a device running OS X 10.13. However, the issue was reproduced on both Safari and Chrome, so it looks like a hardware support issue.

**Error in Chrome on OS X 10.13:**

`[.WebGL-0x7fba65070000]GL ERROR :GL_INVALID_OPERATION : glBlitFramebufferCHROMIUM: src and dst formats differ for depth/stencil`

I'll update this issue with a minimally reproducible project if I get the chance, currently I'm having trouble finding devices to test on since most Mac devices seem to be unaffected.

**A device that did show the artifact + error:**
![image](https://user-images.githubusercontent.com/6013871/92951332-2d104200-f42c-11ea-939b-e80f451bb2d0.png)

**WebGL Report of the device above that shows the artifact + error:**
![image](https://user-images.githubusercontent.com/6013871/92950729-26cd9600-f42b-11ea-8451-a6327027dc5d.png)

**A Mac device that did not show the artifact + error:**
![image](https://user-images.githubusercontent.com/6013871/92951283-1cf86280-f42c-11ea-8e05-237c9084d57e.png)

**Comment by mvaligursky** [comment]
I could be interested to see log from Firefox as well, they tend to have more details in what is actual problem in their error messages.

**Comment by willeastcott** [comment]
@Christopher-Hayes This issue seems to have gone stale, having not been updated in over a year. @mvaligursky made a request about how the issue manifests in Firefox. If you'd like to follow up still, be my guest. But macOS has moved on in the interim so perhaps this is no longer a problem? Anyway, due to the age of the issue, I'll close for now (although happy to reopen).
