### ISSUE TITLE
Migrate engine to typescript

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#2433]
We would like to start migrating the engine codebase to typescript in order to leverage its well known advantages.

Given the engine codebase size though, it is unfeasible to convert everything in one go. Instead we must find a way of migrating the engine bit by bit (by file or module). Presumably we would start with the lowest-level code (i.e. the leafs of the code dependency tree) and work our way up to the highest level code. A good candidate might be the math lib.

One question is: how can we generate a set of docs and bindings for the engine when it comprises both JS and TS source? Has anyone attempted or managed this before?

Some of this might already be answered in #2213.

**Comment by kungfooman** [comment]
I started the migration process once (with help of @jtenner), but in effect all upstream changes were so hard to merge and it just turned into an experiment (and due lack of time, it just died out): https://github.com/KILLTUBE/PlayCanvasTS

Also tried to generate C++ from TypeScript, so I would be able to use either AssemblyScript or Emscripten to generate either WebAssembly or native binaries, for reusing the PlayCanvas math code in different game engines/bindings (e.g. as binding for embeddable Duktape JavaScript interpreter).

`One question is: how can we generate a set of docs and bindings for the engine when it comprises both JS and TS source?`

Can you explain further? Not sure what you mean by "bindings" and which bindings have to be generated. TypeScript boils down by definition to JavaScript, the "simplest" thing would be to rename *.js to *.ts (it works, it will just rain errors tho).

**Comment by slimbuck** [comment]
Hi @kungfooman,

Thanks for the info. By bindings I mean the playcanvas.d.ts typescript definitions we generate from jsdoc (and also the API reference documentation).

I'm not sure how we go about combining jsdocs from JS and TS files. (I haven't even tried this, perhaps it's a matter or running all source through tsc with some special flags?).

**Comment by jtenner** [comment]
tsdoc is always an option. However, writing the source in TypeScript in the first place is usually better, because then d.ts can be generated as a byproduct without the help of jsdoc.

**Comment by jtenner** [comment]
I realize that saying "starting with typescript" is unhelpful in this case, but perhaps just making a fork and switching to the typescript compiler in general should be a great first step.

Typescript will bundle regular js modules too.

**Comment by mvaligursky** [comment]
two possible interesting links:

https://www.bookstack.cn/read/typescriptlang-3.7/spilt.7.055dccf6c3f8aae3.md
The most impactful outcome of this feature might a bit subtle: with TypeScript 3.7, users can write libraries in JSDoc annotated JavaScript and support TypeScript users.

https://medium.com/@wojciechkrysiak/typescript-jsdoc-better-docs-7c03b6ea04df
JSDoc based documentation for projects with both .js and .ts files

**Comment by willeastcott** [comment]
We have since decided to stick with ESNext + Babel (and auto-generate TypeScript declarations from JSDoc comments using the TypeScript compiler). Additionally, JSDoc + VS Code gives us pretty good real-time type checking.

We should continue to keep an open mind about adopting TypeScript in the future, but for now, we should close this.
