### ISSUE TITLE
Cannot Load Playcanvas Links in iOS 14.2 Beta

### ISSUE THREAD

**Issue by maxbbb** [playcanvas/engine#2440]
When attempting to load any playcanvas link in the iOS 14.2 Public Beta, the link crashes with the message in Safari of "A problem repeatedly occurred on "link.com". When trying to debug this in the Safari console there were no error messages, so I'm not sure what the issue could be. Babylon JS games also have the same issue, so I thought it was a WebGL problem but Three JS links are working fine so maybe not. I'm assuming this is an Apple problem and not a Playcanvas one, but just wanted to give a heads up so that a bug report could be filed with them if needed. 

Steps to reproduce:
1. Get iOS 14.2 beta
2. Open playcanvas link

**Comment by Maksims** [comment]
Check if you can enable/disable WebGL 2 support in Safari.

**Comment by maxbbb** [comment]
It's still disabled by default, but testing this enabled or disabled doesn't make a difference.

**Comment by mvaligursky** [comment]
iOS 14.2 beta 1 was pulled from iPhone XR, so I could not test, but 14.2 beta 2 showed up yesterday, and I've tested many engine examples from http://playcanvas.github.io/#animation/blend.html and also Seemore, Spacebase and after the flood, and all that seems to work on the device just fine. Perhaps bug fixed?

http://launch.playcanvas.com/741889

http://launch.playcanvas.com/446278

https://launch.playcanvas.com/581133

**Comment by willeastcott** [comment]
Confirmed fixed on iPhone XS running the latest iOS 14.2 Beta that was released in the last 24 hours. Closing.

**Comment by maxbbb** [comment]
Was just about to follow up that 14.2 Beta 2 fixes this, thanks.
