### ISSUE TITLE
Instanced meshes only rendered in one eye in WebVR

### ISSUE THREAD

**Issue by evan-omnivor** [playcanvas/engine#2444]
### Description

Instanced meshes only render in one eye in WebVR. The shadows render in both. An example project is included here. https://playcanvas.com/project/722033/overview/batchingomnivor

### Steps to Reproduce
1.  Connect WebXR compatible headset and open WebXR compatible browser
2. Open https://playcanvas.com/project/722033/overview/batchingomnivor
3. Notice that instanced cubes are visible
4. Click on page to start VR
5. Notice instanced cubes are only visible in one eye

**Comment by evan-omnivor** [comment]
@mvaligursky Do you know which release this will likely go into?

**Comment by slimbuck** [comment]
Hi @evan-omnivor,

This should go out with the next engine release, which is planned for early next week.

Thanks!
