### ISSUE TITLE
Masking of 3D scroll views doesn't work on Mobile VR

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2465]
https://playcanvas.com/project/725268/overview/scrollview-in-vr-bug

On desktop browser
![image](https://user-images.githubusercontent.com/16639049/95181591-66ce3180-07bb-11eb-83c6-a20b5727323e.png)

On Mobile VR
![Screenshot_20201006-100152_Chrome](https://user-images.githubusercontent.com/16639049/95182553-b4976980-07bc-11eb-9085-edb92855931e.jpg)

**Comment by Maksims** [comment]
And how it looks not in VR?

**Comment by yaustar** [comment]
It looks like the desktop browser version

**Comment by mvaligursky** [comment]
likely related https://github.com/playcanvas/engine/issues/3917
