### ISSUE TITLE
"Settings" error in both Touch examples

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#2467]
Hello. While trying to find out if the touch examples contains 'jquery-mobile'* within 'Settings' of these forked examples:
A) https://developer.playcanvas.com/en/tutorials/basic-touch-input/
B) https://developer.playcanvas.com/en/tutorials/multitouch-input/
- the editor does not show the Script loading order >> seen here in one of my other projects:

![image](https://user-images.githubusercontent.com/6838800/95683690-1c024e80-0bed-11eb-8211-af0adde8ea5c.png)

*) As seen here: https://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_events_swipeleft

```
<link rel="stylesheet" href="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
```

Here is how the forked examples both look like:
![image](https://user-images.githubusercontent.com/6838800/95683704-48b66600-0bed-11eb-857c-c2e1351c32a2.png)

I have been down the road of 'being forced' to alter such a forked project, in order to get the special functions to work -> subsequently without luck :-/

**Comment by yaustar** [comment]
Posted and answered on forum.

Feature requested posted on Editor repo https://github.com/playcanvas/editor/issues/180
