### ISSUE TITLE
collision volume type mesh not matching the object when scaled in editor

### ISSUE THREAD

**Issue by FrantzVZ777** [playcanvas/engine#2469]
There seems to be an issue with collision volume type mesh. The collider is not visible with the physics debug script. Also the collider volume seems not to matching the object anymore when the object is called in the editor.
https://playcanvas.com/project/725931/overview/vehicle-physics

See video in zip.

[mesh physics.mp4.zip](https://github.com/playcanvas/engine/files/5370166/mesh.physics.mp4.zip)

**Comment by yaustar** [comment]
Hi @FrantzVZ777 The project is private unfortunately, can you make it public please :)

**Comment by FrantzVZ777** [comment]
@yaustar sorry my bad. public now

**Comment by yaustar** [comment]
This is a way overdue reply, sorry this slipped so badly through the net.

Mesh collision is only currently supported if the scale is uniform/same of each axis. I will add a ticket to show this as a warning.
