### ISSUE TITLE
Should we set picker.layer.passThrough to true ?

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#2470]
### Description

When we call `Picker#prepare`, it will add opaque and transparent meshInstances into `picker.layer.opaqueMeshInstances`, and then call `ForwardRenderer#renderComposition` to render it.

However, `LayerComposition#_update` is called in `ForwardRenderer#renderComposition`, and this method may **RESET** the `picker.layer.opaqueMeshInstances` and `picker.layer.transparentMeshInstances` in a very complex scenario, such as changing the skybox, changing meshInstance's material etc.

This will cause the renderer do not render the transparent meshInstances in the picker layer, and `Picker#getSelection` will return wrong result when clicking transparent meshInstances.

The related code is here:

```diff
LayerComposition.prototype._update = function () {
    // ...
    if (this._dirtyBlend) {
        // TODO: make it fast
        result |= COMPUPDATED_BLEND;
        var opaqueOld, transparentOld, opaqueNew, transparentNew;
        for (i = 0; i < len; i++) {
            layer = this.layerList[i];
            if (layer.passThrough) continue;
            opaqueOld = layer.opaqueMeshInstances;
            transparentOld = layer.transparentMeshInstances;
            opaqueNew = [];
            transparentNew = [];
            for (j = 0; j < opaqueOld.length; j++) {
                if (opaqueOld[j].material && opaqueOld[j].material.blendType !== BLEND_NONE) {
                    transparentNew.push(opaqueOld[j]);
                } else {
                    opaqueNew.push(opaqueOld[j]);
                }
            }
            for (j = 0; j < transparentOld.length; j++) {
                if (transparentOld[j].material && transparentOld[j].material.blendType !== BLEND_NONE) {
                    transparentNew.push(transparentOld[j]);
                } else {
                    opaqueNew.push(transparentOld[j]);
                }
            }
            layer.opaqueMeshInstances.length = opaqueNew.length;
            for (j = 0; j < opaqueNew.length; j++) {
+               layer.opaqueMeshInstances[j] = opaqueNew[j];
            }
            layer.transparentMeshInstances.length = transparentNew.length;
            for (j = 0; j < transparentNew.length; j++) {
+                layer.transparentMeshInstances[j] = transparentNew[j];
            }
        }
        this._dirtyBlend = false;
    }
}
```

A possible solution is to set `picker.layer.passThrough = true`. And I am not sure whether it will cause other problem too.

**Comment by mvaligursky** [comment]
I think `layer.passThrough` might not help completely, as it would not sort transparent meshes on those tricky frames and so you would get meshInstance on top that maybe should be behind others.

Maybe a better option could be to update the index->meshInstance table (or create new table used for resolving ids from render target) inside this:

```
 onDrawCall: function (meshInstance, index) {
                self.pickColor[0] = ((index >> 16) & 0xff) / 255;
                self.pickColor[1] = ((index >> 8) & 0xff) / 255;
                self.pickColor[2] = (index & 0xff) / 255;
                pickColorId.setValue(self.pickColor);
                device.setBlending(false);
            }
```

**Comment by mvaligursky** [comment]
I've done what I suggested, please give it a go in your repro case.

**Comment by scarletsky** [comment]
Hmm, not work in my repo case. I will investigate it.
