### ISSUE TITLE
Allow the powerPreference option to be specified when the context is created

### ISSUE THREAD

**Issue by marklundin** [playcanvas/engine#2471]
Currently, the [`powerPreference`](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2.1) option is not defined in the webGL context creation parameters. This makes sense, however, it would be useful for authors to specify the powerPreference settings in the editor during build time as a rendering option.

**Comment by ellthompson** [comment]
Closing this issue as it's currently tracked under editor issues.
