### ISSUE TITLE
Replace json based file format with protobuf

### ISSUE THREAD

**Issue by MrMabulous** [playcanvas/engine#2472]
Currently meshes get HUGE (in terms of data size). Often they take even more space than an obj (which is a very space-unoptimized format) would.

Protobuf is easy to use and could easily result in an order of magnitude less wire data for models.

Please consider replacing

**Comment by slimbuck** [comment]
Hi @MrMabulous ,

We completely agree! We will imminently be releasing an update which offers the option of GLB format instead of JSON.

Thanks!

**Comment by Maksims** [comment]
Actually, GZIP + JSON, is not that much different than straight forward binary format. And protobuff won't make much difference, but actually will shift binary parsing from other threads into main JS thread - which is bad. Plus protobuff is not meant to be used for large file transfers.
Make sure you've enabled GZIP on your hosting.

What really saves download size for models, is attributes compression. And GLB has a solution for it: Draco Compression. Which then can be GZIP'ed as well. That will make biggest difference in transfer amounts. But there is a cost of decompression on main JS thread trade off (probably could be offloaded into WebWorker).

**Comment by MrMabulous** [comment]
I'd disagree about protobuf not being suited for large files. All of google earth data is served via protobuf - and especially if an integer vertex format is used and delta encoding, size can get very small thanks to VarInts

protobuf is as flexible as json without the data overhead

**Comment by Maksims** [comment]
> I'd disagree about protobuf not being suited for large files. All of google earth data is served via protobuf - and especially if an integer vertex format is used and delta encoding, size can get very small thanks to VarInts

The link you've probably read regarding this (first one in google), please read further: they split large files in small chunks/messages. Protobuff is not a runtime file format for 3D, nor it is a compression format. It is firstly used as binary storage format to reduce networking bandwidth.

3D models - is completely different area, and as mentioned before GLB + Draco + GZIP - is an existing solution, without the need to re-invent own 3d runtime file formats.

**Comment by MrMabulous** [comment]
Well, I worked on the product (google earth) so I understand very well how it works

I didn't say GLB + Draco was a bad choice (actually I don't know it) - just saying that protobuf definitely IS a good choice for things like this and would be pretty much like a more efficient drop-in replacement for the json.
