### ISSUE TITLE
Too few GraphNode unit tests

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#2477]
I need quite some GraphNode unit tests for my AssemblyScript PR, because currently the existing tests all succeed - but the entire scene is effectively white/defective.

I compiled a little list of what is actually missing:

| Property     |          |                 |
|--------------|----------|-----------------|
|    right     | get      | 0x in  0 tests  |
|    up        | get      | 0x in  0 tests  |
|    forward   | get      | 0x in  0 tests  |
|    enabled   | get/set  | 0x in  0 tests  |
|    parent    | get      | 6x in  1 tests  |
|    path      | get      | 2x in  2 tests  |
|    root      | get      | 0x in  0 tests  |
|    children  | get      |22x in 10 tests  |
|    graphDepth| get      | 0x in  0 tests  |

|                          Method    |                     |
|------------------------------------|---------------------|
|    _notifyHierarchyStateChanged    |                     |
|    _onHierarchyStateChanged        |                     |
|    _cloneInternal                  |                     |
|    clone                           | 0x in  0 tests      |
|    find                            | 1x in  1 tests      |
|    findOne                         | 0x in  0 tests      |
|    findByTag                       | 0x in  0 tests      |
|    _findByTag                      |                     |
|    findByName                      | 3x in  3 tests      |
|    findByPath                      | 4x in  4 tests      |
|    forEach                         | 0x in  0 tests      |
|    isDescendantOf                  | 0x in  0 tests      |
|    isAncestorOf                    | 0x in  0 tests      |
|    getEulerAngles                  |10x in  5 tests      |
|    getLocalEulerAngles             | 2x in  2 tests      |
|    getLocalPosition                | 2x in  2 tests      |
|    getLocalRotation                | 0x in  0 tests      |
|    getLocalScale                   | 0x in  0 tests      |
|    getLocalTransform               | 0x in  0 tests      |
|    getPosition                     | 2x in  2 tests      |
|    getRotation                     | 0x in  0 tests      |
|    getScale                        | 0x in  0 tests      |
|    getWorldTransform               | 0x in  0 tests      |
|    reparent                        | 5x in  4 tests      |
|    setLocalEulerAngles             | 0x in  0 tests      |
|    setLocalPosition                | 0x in  0 tests      |
|    setLocalRotation                | 0x in  0 tests      |
|    setLocalScale                   | 0x in  0 tests      |
|    _dirtifyLocal                   |                     |
|    _unfreezeParentToRoot           |                     |
|    _dirtifyWorld                   |                     |
|    _dirtifyWorldInternal           |                     |
|    setPosition                     |  2x in  2 tests     |
|    setRotation                     |  0x in  0 tests     |
|    setEulerAngles                  |  6x in  3 tests     |
|    addChild                        | all over            |
|    addChildAndSaveTransform        |  0x in  0 tests     |
|    insertChild                     |  5x in  3 tests     |
|    _debugInsertChild               |                     |
|    _onInsertChild                  |                     |
|    _updateGraphDepth               |                     |
|    removeChild                     | 4x in  2 tests      |
|    _sync                           |                     |
|    syncHierarchy                   | 2x in  1 tests      |
|    lookAt                          | 0x in  0 tests      |
|    translate                       | 1x in  1 tests      |
|    translateLocal                  | 1x in  1 tests      |
|    rotate                          | 6x in  2 tests      |
|    rotateLocal                     | 3x in  3 tests      |

**Comment by willeastcott** [comment]
Now closing since `GraphNode` unit tests are now much more complete:

https://github.com/playcanvas/engine/blob/main/test/scene/graph-node.test.mjs

90.61% of lines in the module are now tested.

**Comment by kungfooman** [comment]
Just quick testing of what still isn't tested at all:

- `clone`
- `findOne`
- `getLocalRotation`
- `getRotation`
- `getScale`
- `setLocalRotation`
- `setRotation`
- `addChildAndSaveTransform`
- `lookAt`
- `root` (property)

**Comment by willeastcott** [comment]
I just quickly added `root` and `findOne`: https://github.com/playcanvas/engine/commit/741541404d94e10f1da45b8181a2d03c32309676

Now at 92.06% coverage.
