### ISSUE TITLE
Create a tutorial for display Iframe into PlayCanvas in 3D

### ISSUE THREAD

**Issue by ClementGuerin** [playcanvas/engine#2479]
Hello,

Sorry to bother you but I would like to suggest that you do a tutorial for a feature that is very close to my heart and that I think would be of interest to many PlayCanvas users like me.

[Here ](https://forum.playcanvas.com/t/how-to-insert-webpage-into-playcanvas-3d/15336)I write a post for asking help about a hack @willeastcott talked about, this hack result to displaying an Iframe and with CSS transform scale it into a plane.

I tried to do it but I don't success to do the code necessary for get the plane position on the screen and transform my iframe for scale it into the plane. It's really complicated for me.

But for genius like you, maybe it's easier, It's possible do a tutorial for doing this ? For me this feature is really useful, if we can display webpage into PlayCanvas with some tricks I see a lot of possibilities for events for example.

Thanks in advance.

**Comment by willeastcott** [comment]
This tutorial project is now available:

https://developer.playcanvas.com/en/tutorials/youtube-in-3d-scenes/

This originated from this forum thread:

https://forum.playcanvas.com/t/how-to-mix-div-and-canvas-together/15525

@yaustar is your point of contact here.

Is there anything else required here or can we close this issue?

**Comment by ClementGuerin** [comment]
I see this now, wow thanks you so much, you're just AWESOME wooow !!

**Comment by hankdangerfield** [comment]
Would I be able to create a character that could walk around this? I have seen a few of these examples and am curious how to create a sort of character controller for this as this uses CSS. Please tell me it is possible lol

**Comment by yaustar** [comment]
As long as it's not in VR, it should be possible
