### ISSUE TITLE
Investigate implementation of OffscreenCanvas API

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2481]
Investigate implementation of https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas. This would give us:
- possible additional performance for the application, as playcanvas part of the application including webgl would execute on separate thread
- ability to use Atomics library https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Atomics on both webgl and worker threads, allowing us to write a job system which can execute jobs triggered on webgl thread and get results back inside the same frame, without using messages for synchronization.

**Comment by issacclee** [comment]
Hi guys,
Is there any update regarding to implement this feature?

**Comment by slimbuck** [comment]
Hi @issacclee, we've not spent time investigating this yet. Probably not high priority until there is support in Safari?

**Comment by slimbuck** [comment]
@mvaligursky wondering whether webgpu supports this out of the box?

**Comment by mvaligursky** [comment]
it does not in the initial release, but the support is expected later.

**Comment by issacclee** [comment]
Thanks for answering guys, am I right to assume that this probably won't get implemented unless Safari starts to support the spec?

**Comment by mvaligursky** [comment]
It will be implemented, when somebody has some time and considers this a high priority, regardless of the Safari (and Firefox by the way) support. Benefits on the android platform which is mostly using Chrome browser could be very nice.
Perhaps somebody from our community of contributors could implement this as well, as this is an open source engine.

**Comment by issacclee** [comment]
https://webkit.org/blog/13686/release-notes-for-safari-technology-preview-161/
FYI, safari will be getting offscreencanvas as shown here in the new tech review release announcement.

**Comment by Maksims** [comment]
This fall webgl context will be added for offscreencanvas to Safari.
https://webkit.org/blog/14205/news-from-wwdc23-webkit-features-in-safari-17-beta/

**Comment by mvaligursky** [comment]
related: https://github.com/playcanvas/engine/pull/5168

**Comment by mvaligursky** [comment]
I'll reopen this as I don't think we have all we need to easily allow users to run the rendering on a worker, which is the goal here.

**Comment by AlexAPPi** [comment]
@mvaligursky @willeastcott Is there any news regarding this decision?

**Comment by mvaligursky** [comment]
Not at the moment, but I'll add it to a list to consider for engine v3 when we get to that!

**Comment by AlexAPPi** [comment]
> Not at the moment, but I'll add it to a list to consider for engine v3 when we get to that!

It’s a pity, but I think I’ve finally found the “holy grail” between physics, rendering, and other features that help parallelize the workload for high performance.

The CoverageBuffer approach worked especially well: it reduced occlusion culling lag to just 1 frame instead of the 3–4 frames seen in earlier HiZ/Readback approaches. Depth buffer reprojection eliminated all the lag issues, but shifted the bottleneck to the CPU—now the tight spot is occlusion testing against the buffer on the CPU. This new mechanism could offload that work from the CPU and, in theory, even deliver the result within the current frame without a race condition (e.g., via atomics).
