### ISSUE TITLE
Weird grabpass and texture_grabPass behavior

### ISSUE THREAD

**Issue by devcem** [playcanvas/engine#2496]
### Description
I was working on grabpass shader and noticed it doesn't work on my friends's computer, on my phone and safari. But works properly on my computer (Chrome latest version) for some reason. Then I wanted to prepare a reproducing demo but this time it doesn't work at all even on my computer.

For some reason on different project or computers "texture_grabPass" doesn't provide anything.

## Demo that works my computer on first try :
https://playcanv.as/b/QOQGf2Z9/

## Demo that I prepared for reproducing step, simpler 
https://playcanv.as/b/6wOtRyWu/

Error : launch.js:7988 ERROR: FRAMEBUFFER_INCOMPLETE_ATTACHMENT
[.WebGL-0x7fd05bae6e00]GL ERROR :GL_INVALID_OPERATION : glCopyTexImage2D: no valid color image

 I couldn't figure out, maybe it's my mistake, but on simpler version the image I put as a sampler2D works properly. But "texture_grabPass" doesn't work.

**Comment by mvaligursky** [comment]
Hi @devcem - are you able to share the Editor project for the simpler repro as well?
Thanks!

**Comment by devcem** [comment]
> Hi @devcem - are you able to share the Editor project for the simpler repro as well?
> Thanks!

Hello,
Here is the editor version of simpler repo : 
https://playcanvas.com/editor/project/731620

**Comment by mvaligursky** [comment]
I'm still looking for the best solution, but it seems that changing the 'transparent canvas' setting in Rendering section can fix it. I'm still working on a solution that works with either state of that setting - and have one apart from Chrome.
