### ISSUE TITLE
Allow env cube maps to be rotated

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2505]
At the moment they cannot be rotated in the world (to say align sun in the cube map with some specific world direction where user wants to place directional light).

We should implement this (possibly as an optional shader chunk).

At the moment we also flip cube map lookup on x-axis. We should perhaps remove the instruction and adjust the 3x3 matrix instead.

```
vec3 calcReflection(vec3 tReflDirW, float tGlossiness) {
    vec3 lookupVec = fixSeams(cubeMapProject(tReflDirW));
    lookupVec.x *= -1.0;  // <===========
    return $textureCubeSAMPLE(texture_cubeMap, lookupVec).rgb;
}

```

This would allow us to use this for dynamically rendered cube maps, which do not need the flip at all.

**Comment by raytranuk** [comment]
@mvaligursky: #2527 PR is ready for review - I haven't incorporated a flip in the x axis in the 3x3 matrix yet - because I wasn't sure when not to apply it - but it should be easy to add once this and your #2523 PR are in.
