### ISSUE TITLE
Curve tension

### ISSUE THREAD

**Issue by maungers** [playcanvas/engine#2506]
Hi guys! 
What is "curve tension" and how to change it?
![CurveTension](https://user-images.githubusercontent.com/22077882/97583400-e0131a00-1a31-11eb-843a-6da373209439.jpg)

**Comment by willeastcott** [comment]
I think @slimbuck can explain. 😄

**Comment by slimbuck** [comment]
Hi @maungers, 

A curve's tension defines how the cardinal spline's tangents are calculated, see the [wikipedia article](https://en.wikipedia.org/wiki/Cubic_Hermite_spline#Cardinal_spline).

I guess you're using the engine API directly? In that case you should have an instance of the [curve class](https://developer.playcanvas.com/en/api/pc.Curve.html) and set the (undocumented) `tension` member.

Sorry about the patchy docs, we'll get em fixed asap.

Thanks!

**Comment by maungers** [comment]
Great! It works.
It will be nice if this is added to the documentation.

Thanks!
