### ISSUE TITLE
Engine exception if model has no graph node

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2514]
The engine will throw, if a model that has no graph node is added to the entity. For example, the following will result in engine error:

```
    var entity = new pc.Entity();
    entity.addComponent('model', {});
    entity.model.model = new pc.Model();
```

The cause is in the model component:
https://github.com/playcanvas/engine/blob/d369b822bc742db9e16c97a2252fc6b5f467a61b/src/framework/components/model/component.js#L716
which then tries to look for null's parent:
```
		addChild: function (node) {
			if (node._parent !== null)
```

**Comment by mvaligursky** [comment]
I'm not sure this is an actual problem. The model class is designed to contain a hierarchy (a single node would do), which is then connected to the entity when you add the component to it. 

See the API docs:
https://developer.playcanvas.com/en/api/pc.Model.html
_... It contains a hierarchy and any number of mesh instances._

**Comment by LeXXik** [comment]
I agree. Thought perhaps you wanted to put a guard for unhandled exception, hence the report. Feel free to ignore.

**Comment by mvaligursky** [comment]
We had a discussion and will at some point implement a larger system to handle this.
https://github.com/playcanvas/engine/issues/2529

Thanks for bringing this to our attention.
