### ISSUE TITLE
Forward Renderer error when using first layer

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2518]
Steps to reproduce:

1. Add an opaque layer to the very top of the layers list (before `World`) and give it a name, e.g. "Custom"
2. Use script that adds a camera with this layer:

```
    var layer = this.app.scene.layers.getLayerByName('Custom');
    var cameraEntity = new pc.Entity();
    cameraEntity.addComponent('camera', {
        clearColor: new pc.Color(0.0, 0.0, 0.0, 0.0),
        layers: [layer.id],
    });    
    this.app.root.addChild(cameraEntity);
```

Forward Renderer throws an error:
![image](https://user-images.githubusercontent.com/5677782/97871189-c49f5c00-1d1c-11eb-8ea3-eb101f01e58b.png)
![image](https://user-images.githubusercontent.com/5677782/97871285-f284a080-1d1c-11eb-89ad-2331255cb43b.png)
`cameraPass` is 0 in this case, resulting in `settings` being `undefined`.

**Comment by mvaligursky** [comment]
This is on my radar to fix already, but I don't have a fix yet. 
It's related to a layer which uses shadow map from directional light used before the shadow map is rendered for that frame.

**Comment by devcem** [comment]
I came here to raise a bug ticket for that issue. Adding Custom layer on directional light solves issue, ALSO on engine code checking "settings" variable on that line and if it's not exist setting the "pass" variable to 0 solves issue.

Here is the line :
https://github.com/playcanvas/engine/blob/0342db03a2e8214a43167f94a0fb82f3f8b6a00e/src/scene/forward-renderer.js#L1369

Here is the screenshot for change :
<img width="500" alt="Screen Shot 2020-11-06 at 18 04 03" src="https://user-images.githubusercontent.com/7432641/98381156-8d9db300-205a-11eb-882c-4418b1e9edbf.png">
