### ISSUE TITLE
Feature request: black or at least dark light within light cookies

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#2538]
Can you develop the option of black or at least dark light within light cookies? ... I want to make a tool for Tattoo artists, where edges need to be really black.
Not possible right now.

cf my project: https://playcanvas.com/editor/scene/968488

**Comment by yaustar** [comment]
Sounds like you want to project a texture onto a model.

These two demos may help in that regard
https://github.com/playcanvas/playcanvas.github.io/blob/master/graphics/painter.html
https://developer.playcanvas.com/en/tutorials/character-damage-demo

**Comment by dexterdeluxe88** [comment]
> Can you develop the option of black or at least dark light within light cookies? ... I want to make a tool for Tattoo artist, where edges need to be really black.
> Not possible right now.

This would be also very useful to project blob shadows.

**Comment by FutureFireplace** [comment]
@yaustar: in case you are referring to https://playcanvas.github.io/#graphics/painter.html, it will not help. I have a model character which recieves the texture in a bad way (what is projected on the back is also projected on the front - a bit like a mirror effect, but only that the mapping is off {ps: UV unwrap is not always a walk in the park - many of my tried Blender unwrap methods does, for example, not transfer at FBX-export to PC}) 
- the painter example paints on each of the 6 sides as well :-/

I am more interested in the damage-example, where the UV mapping seem to perfect already (there is no mirrored effect, as all seams and islands on the black/white rendertexture to the left are mapped correctly). Here I want to project a readymade texture to the model. Kind of the reverse procedure of the present 'damage' infliction. Here is my project with a naïve approach to the problem (blue tattoo put at decal-texture): https://playcanvas.com/editor/scene/1028837

**Comment by FutureFireplace** [comment]
BTW @yaustar: I have found a compromise solution for the mapping problem ... you don't have to pursue this (just in case ... but thx again)

**Comment by FutureFireplace** [comment]
Having summed up the different mehods to project an image to a character (to a total four methods), I hereby return to this issue as each of them seem to possess their own challenge. In case the developers think that it is possible to use the two most obvious ones (texture and rendertexture), they both have inherit flaws in the shape of 'seams' and 'distorted stretches' that prevails me to make fluint dynamic movement of an image across the character without a lot stretching: https://playcanv.as/b/9tQ1i4Cq/ (forked from a Leonidas tutorial)  + https://playcanv.as/b/FiSGfBFX/ (note the stretch on the back of the upper left arm). Theese dynamic stretches are (close to) never a problem when making UV-mapping for games, as the textures are static in such cases. But here the texture is dynamic, and the inherit original mapping structure (from when being developed in Blender etc.) reveals itself ... conclusion: Although not-being a natural category of physique, 'black light' as a light cookie option, would be very useful, as it can bypass mapping issues al together.

**Comment by yaustar** [comment]
> Although not-being a natural category of physique, 'black light' as a light cookie option, would be very useful, as it can bypass mapping issues al together.

Even if this is possible, you are going to have the same problem as you are not projecting onto a flat surface.

**Comment by FutureFireplace** [comment]
I am already ahead of that problem, as I am using a 'rolling effect' that changes the UV-tiling of the material as a function of the camera-to-bodypart position.

**Comment by Maksims** [comment]
Decals?

**Comment by FutureFireplace** [comment]
A) As an option I can go back to the https://developer.playcanvas.com/en/tutorials/character-damage-demo (that includes decals) option, but so far I have seen this example as being taylor made for special game situations (and thus very relevant for most PlayCanvas developers). 
B) As a parallel I made this post in the forum: https://forum.playcanvas.com/t/shooting-an-image-on-to-a-surface/15755 yesterday. From there I pursued https://playcanvas.com/project/704805/overview/paint-3d-test (also decals)

From both A) and especially B) I seem to be stuck at this line [from B)]:
`this.material.setParameter("paintColor",new pc.Vec3(1.0,1.0,1.0).data);`
- is there a `material.setParameter` method/approach for 'painting' with an image?

**Comment by FutureFireplace** [comment]
(please note that this issue now have made me post this parallel https://github.com/playcanvas/engine/issues/2556 - it might help my/an overall goal of a more wider option pool and/or a better rendering pipeline ... all in all; so at least of of the above mentioned four approaches [texture, rendertexture, decals and light cookie] improves :-) )

**Comment by mvaligursky** [comment]
I've converting this discussion to a request to implement a decal system:
https://github.com/playcanvas/engine/issues/4053
