### ISSUE TITLE
Create a mechanism to dynamically render to cubemaps

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#254]
Say I want to dynamically update a cubemap. It would be good if I could create six camera that render to offscreen buffers that are the 6 faces of a cubemap and then use that cubemap in the same frame. I guess the only thing the engine is missing for this is the ability to specify which mesh instances are rendered by which cameras? So layers?

**Comment by Maksims** [comment]
To render cubemap. I believe it should be as easy as possible, actually without even a need to create a cameras, just be able to call render of cubemap specifying position and resolution.

**Comment by detzt** [comment]
That would be a great feature!
