### ISSUE TITLE
Accessing Depth Buffer of a Render Target results in black texture?

### ISSUE THREAD

**Issue by AshMobilePie** [playcanvas/engine#2541]
Example project:
https://playcanvas.com/editor/scene/1029149

Creating a Render Target with a Depth Buffer like this:
```javascript
    this.texture = new pc.Texture(this.app.graphicsDevice, {
        width: this.app.graphicsDevice.width,
        height: this.app.graphicsDevice.height,
        format: pc.PIXELFORMAT_R8_G8_B8_A8,
        autoMipmap: true,
        minFilter: pc.FILTER_LINEAR,
        magFilter: pc.FILTER_LINEAR,
        addressU: pc.ADDRESS_CLAMP_TO_EDGE,
        addressV: pc.ADDRESS_CLAMP_TO_EDGE
    });
    
    this.depthBuffer = new pc.Texture(this.app.graphicsDevice, {
        width: this.app.graphicsDevice.width,
        height: this.app.graphicsDevice.height,
        format: pc.PIXELFORMAT_DEPTH,
        mipmaps: false,
        addressU: pc.ADDRESS_CLAMP_TO_EDGE,
        addressV: pc.ADDRESS_CLAMP_TO_EDGE
    });
    
    this.renderTarget = new pc.RenderTarget(this.app.graphicsDevice, this.texture, { depth: true, depthBuffer: this.depthBuffer });
```

And assigning the texture to an object renders as black. Apparently there aren't any issues with the project and I was suggested to post it here.

Cross-post from: https://forum.playcanvas.com/t/accessing-depth-buffer-of-a-render-target/15722

![Capture](https://user-images.githubusercontent.com/16780479/98544213-94f7d300-228b-11eb-87a8-05ad6d53d3c6.PNG)

**Comment by mvaligursky** [comment]
I see this warnings in console, likely related

[.WebGL-0x7feefd0bf400]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?

**Comment by mvaligursky** [comment]
by the way, we have PR for accessing depth texture fix here. Perhaps you can see if you might need some of that in your project.
https://github.com/playcanvas/engine/pull/2537/files

**Comment by AshMobilePie** [comment]
@mvaligursky Which browser? I'm using the latest public Chrome version (86.0.4240.183) and I'm not seeing that warning?

I'll take a look at that PR link. Thank you.

**Comment by mvaligursky** [comment]
I see the error in Mac Chrome 84.0.4147.125 (Official Build) (64-bit).

I tried Max Firefox, and depth seems to render in red channel - I need to come close to the cubes to see it .. maybe you need to remap the range?

<img width="1081" alt="Screen Shot 2020-11-09 at 2 37 20 PM" src="https://user-images.githubusercontent.com/59932779/98554916-30437500-2299-11eb-8056-4e44bb781e3e.png">

**Comment by mvaligursky** [comment]
I just updated to 86.0.4240.183 (Official Build) (x86_64) on Mac and still get the error.

**Comment by AshMobilePie** [comment]
I'm using Windows Chrome 86.0.4240.183 (Official Build) (64-bit) and Windows Firefox 82.0.2 (64-bit). Neither has any warnings WebGL or texture warnings.

On both versions, if I zoom right into the cubes, the texture remains black for me. If I try to change the Depth Buffer texture format, I get the following error:
`playcanvas-stable.dbg.js:53825 Incorrect depthBuffer format. Must be pc.PIXELFORMAT_DEPTH or pc.PIXELFORMAT_DEPTHSTENCIL`

**Comment by mvaligursky** [comment]
Maybe try changing these Graphics Settings in Editor to different combination and see if that makes a difference:
- Transparent Canvas
- Antialiasing
(not saying it's a solution, but help identify the problem)

**Comment by AshMobilePie** [comment]
No luck so far on either version, sorry.

![image](https://user-images.githubusercontent.com/16780479/98558322-32a7ce00-229d-11eb-9693-3613a5eadb60.png)

**Comment by mvaligursky** [comment]
install https://spector.babylonjs.com/ as Chrome plugin, capture frame and try to investigate to see what happens perhaps - that might at least confirm stuff gets rendered into that render target. But I guess it does, as color side of it works ok.

I don't have any other suggestion at the moment, sorry.

**Comment by mvaligursky** [comment]
also try setting minFilter and magFilter of depth buffer to FILTER_NEAREST

**Comment by AshMobilePie** [comment]
The min and max filter did the trick:

![image](https://user-images.githubusercontent.com/16780479/98559756-ebbad800-229e-11eb-8348-1761f7d4b00f.png)

So no bug, just a setting I was missing. Thanks for your help, I appreciate it.

**Comment by mvaligursky** [comment]
Great! Ok, I'll close this.
