### ISSUE TITLE
bug in function LayerComposition.prototype._update

### ISSUE THREAD

**Issue by Casval111** [playcanvas/engine#2544]
1.sory for my poor english 
2.in following block 
"this._dirtyBlend = dirtyBlend1 || dirtyBlend2" seems should be:
"this._dirtyBlend = this._dirtyBlend || dirtyBlend1 || dirtyBlend2" or
"if(dirtyBlend1 || dirtyBlend2) this._dirtyBlend = true"

// rebuild this._meshInstances array - add all unique meshInstances from all layers to it
    // also set this._dirtyBlend to true if material of any meshInstance has _dirtyBlend set, and clear those flags on materials
    if (this._dirty) {
        result |= COMPUPDATED_INSTANCES;
        this._meshInstances.length = 0;
        this._meshInstancesSet.clear();
        var dirtyBlend1, dirtyBlend2;

        for (i = 0; i < len; i++) {
            layer = this.layerList[i];
            if (!layer.passThrough) {

                // add meshInstances from both opaque and transparent lists
                dirtyBlend1 = addUniqueMeshInstance(this._meshInstances, this._meshInstancesSet, layer.opaqueMeshInstances);
                dirtyBlend2 = addUniqueMeshInstance(this._meshInstances, this._meshInstancesSet, layer.transparentMeshInstances);
                this._dirtyBlend = dirtyBlend1 || dirtyBlend2; //*** here 
            }

            layer._dirty = false;
            layer._version++;
        }

        this._dirty = false;
    }

**Comment by slimbuck** [comment]
Hi @Casval111, thanks for issue - we'll get on this asap!

**Comment by slimbuck** [comment]
I think the update could also be:
```
this._dirtyBlend = addUniqueMeshInstance(this._meshInstances, this._meshInstancesSet, layer.opaqueMeshInstances) || this._dirtyBlend;
```

**Comment by Casval111** [comment]
That works fine

**Comment by mvaligursky** [comment]
Thanks for the report and fix @Casval111 !

**Comment by slimbuck** [comment]
FYI this fix has been released.
