### ISSUE TITLE
Add overlay blend mode to particle systems

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2547]
Request for overlay blend mode to particle systems. Split from this ticket: https://github.com/playcanvas/editor/issues/13

Example reference is the Photoshop overlay blend mode https://www.photoshopessentials.com/photo-editing/layer-blend-modes/overlay/

**Comment by Maksims** [comment]
As I'm aware, `overlay` is not simply another blend mode, and there are no native (OpenGL ES) blends that do what `overlay` blending does.

**Comment by mvaligursky** [comment]
perhaps something like this could be useful, it is often used with particle systems

https://wiki.popcornfx.com/index.php/Particle_tips_TexturesForAlphaBlendAdditive

**Comment by mvaligursky** [comment]
one more link about this possible solution (not actual overlay blend mode of course)
https://gamedev.stackexchange.com/questions/138813/whats-the-difference-between-alpha-and-premulalpha
Super-Power #1: Pre-Multiplied Alpha can combine layer and additive blending

**Comment by yaustar** [comment]
We will be getting a concept doc from the client to establish the feature request.

**Comment by yaustar** [comment]
Closing as the request was mis understood: #2557
