### ISSUE TITLE
Add method to get the active camera while rendering

### ISSUE THREAD

**Issue by vkalpias** [playcanvas/engine#255]
See this thread for more http://answers.playcanvas.com/questions/1432/get-camera-used-for-rendering

**Comment by Maksims** [comment]
It is somewhat more complicated with multiple cameras used. So it is more encouraged to the developer to manage own cameras references and act accordingly.

There might be a case where something is rendered to different cameras and need to be modified so. This probably will require a clone of renderable model with different culling mask on it to ensure they are rendered to own cameras and modified accordingly.

**Comment by guycalledfrank** [comment]
I think it's very useful. Currently using scene._activeCamera for that all the time, but we should have a reliable public method.

**Comment by Maksims** [comment]
How does this addresses concern of multi-camera cases?

**Comment by guycalledfrank** [comment]
_activeCamera is currently the last rendered camera actually (if you're checking in in update()). However, if you have a pc.Command() that is executed inside the rendering loop, the _activeCamera will what it is.

**Comment by Maksims** [comment]
So would that be an event on MeshInstance that would be called for every render by different cameras?

**Comment by guycalledfrank** [comment]
Probably just make scripts subscribe to camera rendering start? Events per culled mesh instance is overkill.

**Comment by Maksims** [comment]
That would do :)

**Comment by daredevildave** [comment]
I feel like this is probably covered by the [Layer System](https://developer.playcanvas.com/en/api/pc.Layer.html). If not it's now out of date so a newer and more specific issue should be opened.
