### ISSUE TITLE
Optimization of texels is not possible (texture being distorted on character arm no matter the UV-mapping method).

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#2556]
Within the post rendering sector and main game development sector it is possible, to define how textures are being rendered; in relation to having **a robust rendering pipeline**.
More specifically meaning, that the 'texel density and stretch' beneath the vertex wiring follows the 'distance between the vertices'.
Having spent a great amount of time trying to eliminate texel stretch distortions, it seems like there is an inherit flaw in the engine, that make this elimination impossible upon the arms and legs of a character. As if the compiler/pipeline handles the object with a one-fits-all approach (and a character is quite far from, for instance, a sphere).

{in case wished I can list all the types of UV-mapping methods used from Blender 2.83 to PlayCanvas, but for now I choose to leave them out}
Here is a base example of stretch issue:
https://playcanv.as/b/FiSGfBFX/
And here is an example of my latest workaround (by use of the bought Blender addon [Tesselator](https://blendermarket.com/products/tesselator), and therefore not left out):
https://playcanv.as/b/GvTX6Dkw/
 - note how the Tesselator addon/plugin have optimized the distance between vertices succesfully  (the faces are roughly the same size ... unfortunately this does not matter for the PlayCanvas rendering pipeline >> it craves to stretch the texture on the top of the arm) 

...the texel density has been optimized as well (from front and back below one can tell that the checker coordinate letters are the same size)
![image](https://user-images.githubusercontent.com/6838800/99070418-7574e900-25b0-11eb-8287-9216cc5f3698.png)

![image](https://user-images.githubusercontent.com/6838800/99070381-65f5a000-25b0-11eb-8425-1c80d139a1f0.png)
PS: Seams marked at head, hands and shorts areas.

**Comment by mvaligursky** [comment]
how do you place those moving textures on the model? are you using light cookies?

**Comment by FutureFireplace** [comment]
Hello Martin/@mvaligursky. Since I wrote this post I pressed on, and got to two different conclusions: 
A) It was actually possible to optimize a character shape on Blender-side. Here you see a tesselator-optimized character (note that head would not be part of final PC-composition). The red incirclement (left) rep. the torso-part of the UV-apping, where the blue (farthest left) rep. the arm. 

![image](https://user-images.githubusercontent.com/6838800/99775451-989f1b80-2b0f-11eb-8c92-ab0df034ee34.png)

After optimizing vertex distances, I had to overcompensate height of squares on the arm to counter stretching there (black incirclement). At yellow arrows, the seams revealed a gordian knot, where the texture repetition is structurally flawed (even for all game developers who wants to move textures in a character in realtime) ... all-in-all a Blender and Gamedev-sector problem more than a PlayCanvas-problem.
B) But! ... the question also rise in relation to 'all the boxing' between a 2D rep. (UV-mapping) and a 3D representation (a model, that in many cases can be character). Could be nice to have a 3D rep. of the bitmap material (https://stackoverflow.com/questions/16368187/3d-equivalent-of-bitmap-bmp) at both Blender-side and PlayCanvas-side. Not UV-only, but TUV where 'T' is the third dimension:
![image](https://user-images.githubusercontent.com/6838800/99776392-08fa6c80-2b11-11eb-95d2-f29c8a53751d.png)

But I will move forward with that idea in other fora (Blender devs and maybe my old University)

**Comment by FutureFireplace** [comment]
PS and NB!: Please consider to discuss this issue with your PlayCanvas peers:
Feature request: black or at least dark light within light cookies #2538 (my main issue, that started my _grand character-projection quest_)

- as this can proof extremely valuable to me and other playCanvas developers. Not only can the black-light effect help me within projects for tattoo artists worldwide, but also with projects targeted car-stickers. Imagine the effect for the rallycar market? The amount of car stickers comercials on a rallycar is massive (and by use of light cookie [with all* color nuances], multiple comercial stickers can be move around simultaneously, independently and quite effortless :-D ) ... together we can realize this and **push PlayCanvas ahead as being a true frontrunner within that sector**

**Comment by mvaligursky** [comment]
Closing this as it does not contain feature request nor bug a description - it's more of a discussion on the texture mapping limitations in general.
