### ISSUE TITLE
Add support for glTF extension: KHR_texture_transform

### ISSUE THREAD

**Issue by raytranuk** [playcanvas/engine#2563]
Add support for glTF extension: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform

Currently failing related tests on: https://github.com/cx20/gltf-test:

![image](https://user-images.githubusercontent.com/11779961/99427238-12ab8680-28fd-11eb-9ad7-f74cc2fe3fd5.png)
![image](https://user-images.githubusercontent.com/11779961/99427346-340c7280-28fd-11eb-8cf8-ceb77f6ef684.png)

Priority of this may change if users request / require this extension to be supported.

**Comment by slimbuck** [comment]
Note that we already support the scale and offset attributes of this extension https://github.com/playcanvas/engine/blob/master/src/resources/parser/glb-parser.js#L923.

**Comment by cx20** [comment]
I tested it on the latest version of PlayCanvas and noticed that the results have changed.
Is this an expected change?

|Library|TextureTransformTest.gltf result|
|:----:|:----:|
|[PlayCanvas v1.44.2](https://rawcdn.githack.com/cx20/gltf-test/ca7c5c1f4be263d67179d25f80c092127eac61d2/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformTest&scale=1&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/126215771-ab28d00c-c274-480a-ae31-4cf7ebaf0acf.png)](https://rawcdn.githack.com/cx20/gltf-test/ca7c5c1f4be263d67179d25f80c092127eac61d2/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformTest&scale=1&type=glTF)|
|[PlayCanvas v1.45.0](https://rawcdn.githack.com/cx20/gltf-test/0d6cee5b5faecf8a2ff546bb6446ab1268ab632c/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformTest&scale=1&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/126215806-007da6e6-bbe5-4c13-a9fa-2631e7ae9a83.png)](https://rawcdn.githack.com/cx20/gltf-test/0d6cee5b5faecf8a2ff546bb6446ab1268ab632c/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformTest&scale=1&type=glTF)|

**Comment by cx20** [comment]
I don't know if it's related to the above, but I can see some changes in the test results of the `KHR_mesh_quantization` extension model.

|Library|Duck/glTF result|Duck/glTF-Quantized result|
|:----:|:----:|:----:|
|PlayCanvas v1.44.2|[![image](https://user-images.githubusercontent.com/1833979/126217690-a3ce0d97-c2e7-4b7c-90f9-ab8f5eeeaedf.png)](https://rawcdn.githack.com/cx20/gltf-test/ca7c5c1f4be263d67179d25f80c092127eac61d2/examples/playcanvas/index.html?category=tutorialModels&model=Duck&scale=1&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/126217706-9aa0db02-fd99-4810-bcbe-70d03006a925.png)](https://rawcdn.githack.com/cx20/gltf-test/ca7c5c1f4be263d67179d25f80c092127eac61d2/examples/playcanvas/index.html?category=tutorialModels&model=Duck&scale=1&type=glTF-Quantized)|
|PlayCanvas v1.45.0|[![image](https://user-images.githubusercontent.com/1833979/126217730-c4999a38-a4e4-479d-8dbd-638d60f68a41.png)](https://rawcdn.githack.com/cx20/gltf-test/0d6cee5b5faecf8a2ff546bb6446ab1268ab632c/examples/playcanvas/index.html?category=tutorialModels&model=Duck&scale=1&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/126217750-492fe55c-826c-44aa-9224-cd94a86e725c.png)](https://rawcdn.githack.com/cx20/gltf-test/0d6cee5b5faecf8a2ff546bb6446ab1268ab632c/examples/playcanvas/index.html?category=tutorialModels&model=Duck&scale=1&type=glTF-Quantized)|

**Comment by slimbuck** [comment]
Thanks @cx20, I will address the texture transform issue.

**Comment by cx20** [comment]
Thank you so much. 
I have confirmed that `TextureTransformTest.gltf` and `glTF-Quantized Duck.gltf` are displayed correctly in PlayCanvas `v1.46.0`.

**Comment by cx20** [comment]
I think [TextureTransformMultiTest.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformMultiTest) has also improved considerably.
There seems to be some issue about `Unlit` and `Clearcoat Normal`.

|[PlayCanvas v1.45.3](https://rawcdn.githack.com/cx20/gltf-test/349ca3dc55b7ff3533f0450b6fd0510d7c345ef9/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformMultiTest&scale=1&type=glTF)|[PlayCanvas v1.46.0](https://rawcdn.githack.com/cx20/gltf-test/d0f1fe6217c43e8f514bdc46f865807e80c3effb/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformMultiTest&scale=1&type=glTF)|
|:----------:|:----------:|
|[![image](https://user-images.githubusercontent.com/1833979/129778109-1fd64b63-2b18-4b04-a1ac-1f75853f928d.png)](https://rawcdn.githack.com/cx20/gltf-test/349ca3dc55b7ff3533f0450b6fd0510d7c345ef9/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformMultiTest&scale=1&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/129778144-22766bf2-3db1-43ed-b589-9b594df8b3ca.png)](https://rawcdn.githack.com/cx20/gltf-test/d0f1fe6217c43e8f514bdc46f865807e80c3effb/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformMultiTest&scale=1&type=glTF)|

**Comment by cx20** [comment]
Hmm, It is the display result of [PlayCanvas v1.46.0 + TextureTransformMultiTest.gltf](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformMultiTest&scale=1&type=glTF) above, but it seems that a shader error is appearing. Is it a matter of usage?
```
playcanvas-latest.js:15394 

Failed to compile fragment shader:
  :
ERROR: 0:61: 'vUv0' : undeclared identifier
ERROR: 0:61: '=' : dimension mismatch
ERROR: 0:61: '=' : cannot convert from 'const highp float' to 'highp 2-component vector of float'
```

**Comment by willeastcott** [comment]
Been a while since this issue was updated @slimbuck. Would you like to reassign this to @GSterbrant perhaps?

**Comment by slimbuck** [comment]
This is fixed

**Comment by willeastcott** [comment]
Oh, was it fixed in this PR: https://github.com/playcanvas/engine/pull/4254

Because the deployed glTF viewer still shows the problem.

**Comment by slimbuck** [comment]
Actually I was trash talking. Unlit was still broken.

However: https://github.com/playcanvas/engine/pull/4396

**Comment by willeastcott** [comment]
@slimbuck  Cool OK, so when we deploy 1.55.0 this week, @cx20 can flip the cross to a tick for that test?

**Comment by slimbuck** [comment]
yep

**Comment by cx20** [comment]
I tested it again with PlayCanvas v1.55.0. I think the test below has passed.
[PlayCanvas v1.55.0 + TextureTransformMultiTest.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/9f12b61dfaa1d27a24a482a9766b3e970d2f5c3c/examples/playcanvas/index.html?category=tutorialModels&model=TextureTransformMultiTest&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/179812020-e914ba18-94a5-4665-b40a-b7325e837f67.png)
