### ISSUE TITLE
Particle render issue with transparent canvas

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2565]
Using a transparent canvas with a camera clear colour of alpha of 0 and particle effects results in the particles being alpha'ed according to the colour of the document.

Reproducible: https://playcanvas.com/project/738423/overview/particles-on-transparent-canvas

Grey background
![image](https://user-images.githubusercontent.com/16639049/99519105-54820e80-2989-11eb-93b3-50b95ade4304.png)

White background
![image](https://user-images.githubusercontent.com/16639049/99519509-e12ccc80-2989-11eb-9b37-b4d0abab3876.png)

**Comment by raytranuk** [comment]
`alphaWrite` on the particle material was set to `false` and needs to be set to `true` to work with transparent canvas - example here: https://playcanvas.com/project/738727/overview/particles-on-transparent-fork
