### ISSUE TITLE
Transparent mesh instances may stay in layer.opaqueMeshInstances list

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#2576]
### Description
When you update meshInstance with new materials(no `material._scene`) in one frame, and if the material's blendType are not the same, the meshInstance may stay wrong visible list in the layer.

### Steps to Reproduce

1. Open the page http://playcanvas.github.io/graphics/model-box.html
2. Open the console
3. Paste the following snippet:

```js
entity = new pc.Entity();
entity.addComponent('model', { type: 'box' });
pc.app.root.addChild(entity);

// add child will make layer dirty, and re-sort the result.
// Use raf to skip it.
requestAnimationFrame(() => {
    material2 = new pc.StandardMaterial();
    entity.model.model.meshInstances[0].material = material2;

    material3 = new pc.StandardMaterial();
    material3.blendType = 2;
    material3.opacity = 0.5;
    entity.model.model.meshInstances[0].material = material3;
});
```

And then you will get the wrong result:

```
> app.scene.layers.getLayerById(0).opaqueMeshInstances
(3) [MeshInstance, MeshInstance, MeshInstance]
> app.scene.layers.getLayerById(0).transparentMeshInstances
[]
```

The correct result should be:

```
> app.scene.layers.getLayerById(0).opaqueMeshInstances
(2) [MeshInstance, MeshInstance]
> app.scene.layers.getLayerById(0).transparentMeshInstances
[MeshInstance]
```

### Affects
We are using custom sort callback for layers, if the `opaqueMeshInstances` and `transparentMeshInstances` are wrong, our draw orders are wrong too...

**Comment by mvaligursky** [comment]
Hi @scarletsky - thanks for the report and the repro, I'll fix it for the next engine release.
