### ISSUE TITLE
Fbx to GLB import drops UV1 channel

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2582]
see more on the forum: https://forum.playcanvas.com/t/glb-drops-uv1-from-3ds-max-fbx-export/15415

**Comment by LeXXik** [comment]
I also made a ticket in Editor repo previously. I think it is the same issue:
https://github.com/playcanvas/editor/issues/220#issue-742755253

**Comment by mvaligursky** [comment]
duplicate of https://github.com/playcanvas/editor/issues/220
