### ISSUE TITLE
Glb parser can not parse empty glb file

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#2588]
### Steps to Reproduce

1. Open https://playcanvas.com/viewer
2. Extract [Empty.glb.zip](https://github.com/playcanvas/engine/files/5633208/Empty.glb.zip) and drag it to the viewer. (or you can export an empty glb from blender. This glb file is exported by blender too)

Here is the reason:
![image](https://user-images.githubusercontent.com/2386165/100954710-0f94d500-3550-11eb-8a9b-41d4d50e186e.png)

**Comment by mvaligursky** [comment]
I have at least partial fix to this in different PR:

https://github.com/playcanvas/engine/pull/2488/files#diff-d753c91eaa9c40608fb12c65ad186b5f05fa66db50cf74750e55cba07ea62e69
