### ISSUE TITLE
How to find the “depthTest = false” mesh in the depthMap?

### ISSUE THREAD

**Issue by wei292224644** [playcanvas/engine#2592]
When I turn off the depthTest, it cannot be found in the depthMap…

depthTest = true
![1607050634(1)](https://user-images.githubusercontent.com/16398073/101150428-33910d00-365b-11eb-9713-4e2397f46ec0.jpg)

When I only turn off depthTest,this object disappears in the depthMap.
![1607050657(1)](https://user-images.githubusercontent.com/16398073/101150486-473c7380-365b-11eb-8668-649a2cd0ce50.jpg)

**Comment by mvaligursky** [comment]
are you able to share the repro project for this @wei292224644 ?

**Comment by mvaligursky** [comment]
it seems the project is linked here https://forum.playcanvas.com/t/how-to-find-the-depthtest-false-mesh-in-the-depthmap/16154/3

**Comment by wei292224644** [comment]
Hi @mvaligursky ,
Yes,I raised this question.
