### ISSUE TITLE
Performance drop on destroying entity with light component

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2598]
Performance is affected when destroying an entity with a light component.

Forum topic: https://forum.playcanvas.com/t/hiccups-when-destroying-an-object-with-light/16249

Repro project: https://playcanvas.com/project/745476/overview/light-bug

How to repro:
1. Run along the orbs to destroy each on trigger collision.
2. Notice FPS drop.
3. Go to Editor, disable light component on one orb template and apply to all.
4. Run again - no FPS drop.

**Comment by LeXXik** [comment]
![image](https://user-images.githubusercontent.com/5677782/101596755-5d04bc80-39fe-11eb-9174-0f0f9a908a94.png)

**Comment by Maksims** [comment]
It triggers shader re-compilation, and if shader scenario is complex, then compilation will take long time. As it is currently a blocking operation.

**Comment by mvaligursky** [comment]
It seems that as lights are destroyed, a ground mesh receives smaller number of lights, and a shader variation gets compiled for it. getProgramParameter basically waits for the compilation to be done.

The forum mentions this does not happen without using collision triggers, which I have not investigated. 

At the moment there is no good solution to this. Long term we're having discussions on how to change shader pipeline to use dynamic branches and similar techniques to avoid the compilation when number of lights changes, but this is not a near future.

At the moment, perhaps the best workaround would be to not destroy the lights and only set them to black / zero intensity.

**Comment by lscardinali** [comment]
@mvaligursky it was a mistake on my part, it also happens just by destroying the lights after a delay. I've updated the post.

I've debugged and arrived at that same conclusion, it isn't a bug.

Thanks for the feedback!

**Comment by LeXXik** [comment]
Good points. I remember there was your thread @Maksims long ago about async shader compilation. I guess it would help with such scenarios once it is in place.

**Comment by Maksims** [comment]
> I remember there was your thread @Maksims long ago about async shader compilation. I guess it would help with such scenarios once it is in place.

It can help indeed. Application logic would have to take it in account, as deleting light with async shader compilation would not have immediate effect. But can be assisted with callbacks to help developer have control and understanding of what is going on.

**Comment by mvaligursky** [comment]
I'll close this ticket as it is as designed at the moment.
But as I said, we're considering long term solution to address this already.
