### ISSUE TITLE
Object instance

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2599]
I faced an issue today, where the entity would not get positioned correctly because the graph node fails to identify the vector for some reason. Here are my steps:

Working in Code Editor online, I do a convex cast in dynamics world of Ammo and generate a convex cast result the same way the engine currently generates a raycast result:
```js
const ConvexCastResult = function ConvexCastResult(entity, hitFraction, point, normal) {
    this.entity = entity;
    this.hitFraction = hitFraction;
    this.point = point;
    this.normal = normal;
};
const result = new ConvexCastResult(
     body.entity,
     hitFraction,
     new pc.Vec3(point.x(), point.y(), point.z()),
     new pc.Vec3(normal.x(), normal.y(), normal.z())
);
```

Once the result is received, I act on it:
![image](https://user-images.githubusercontent.com/5677782/101621645-b2e95c80-3a1e-11eb-8edf-9502300c488d.png)

Before setting the position:
![image](https://user-images.githubusercontent.com/5677782/101621804-e926dc00-3a1e-11eb-8807-8040730144df.png)
![image](https://user-images.githubusercontent.com/5677782/101621860-f80d8e80-3a1e-11eb-9338-d828ebf167fe.png)

Then I step into `setPosition()`:
![image](https://user-images.githubusercontent.com/5677782/101621976-27bc9680-3a1f-11eb-932e-c0d9e95334a7.png)

Here it somehow fails to see it as a vector, and assigns it to `x`, corrupting the position as a result.  As a workaround, I pass scalars for `x`, `y` and `z` values to `setPosition`.

**Comment by mvaligursky** [comment]
Would you have any repro you could share with us @LeXXik ?
That would make it a lot easier to track down.

**Comment by LeXXik** [comment]
@mvaligursky I will try to make a repro during this weekend.

**Comment by LeXXik** [comment]
After creating a duplicate case, I wasn't able to reproduce it. Reverting back to my original case, it appears my web worker was using `Vec3` instance, instead of `pc.Vec3` hence the final result. I am closing this issue, as the cause was a bug in my own code.
