### ISSUE TITLE
New animation component doesn't work for clone object

### ISSUE THREAD

**Issue by devcem** [playcanvas/engine#2606]
When we clone an object with anim state component, basically `this.entity.anim.setTrigger('Run');` function doesn't work for cloned object.

I tested this behavior with script clone and also editor clone, both doesn't work. Function only sets original object's anim state.

Expected behavior : `this.entity.anim` variable should set current object's animation evaluator.

In this examples, both characters has animation state component and test.js script.
Test.js script basically triggers "Run" animation when you press "Space". You'll see that in example, only first and original character triggers animation properly.

Project editor link : https://playcanvas.com/editor/scene/1052339
Project demo link : https://launch.playcanvas.com/1052339?debug=true

**Comment by ellthompson** [comment]
Hi @devcem, thanks for highlighting this issue! It looks like the same stateGraph parameters are being used by both entities. I'll create a PR to resolve this issue shortly.
