### ISSUE TITLE
Tapping the screen causes the screen to be highlighted in iOS

### ISSUE THREAD

**Issue by saadhaider78** [playcanvas/engine#2619]
Tapping and holding down the finger for around 2 seconds causes the screen to be highlighted in iOS on multiple devices. We have used multiple CSS tricks to resolve the issue but to no avail. The issue is effecting both of our games 

https://www.blockletegames.com/
https://rareboards.secondlegion.com/

particularly we discovered the bug while testing the darts game, since in the mechanic you have to tap and hold the "Throw dart" button so the power needle goes up and you release it to throw the dart. The highlighting make the game unplayable.

We also tried to reproduce in a base Starter Kit: Model Viewer project and also reproduced it here:
https://drive.google.com/file/d/1pHfDIioJZOu3sxOPDeDKkEwHgMc82zDO/view

This is on iphone X with iOS version 14.2 
The weird thing about the bug is that only if you tap and hold the **left side of the screen** then the bug occurs, while on the right it doesn't.
This is what happens,
Right side give haptic feedback like it wants to highlight, but no highlighting occurs.
Left side gives haptic feedback AND highlights.

When the screen gets highlighted, there is no way to un-highlight it (other then reloading the page)
The bug has occured on the following devices and browsers;
iphone X 14.2 Chrome and Safari
iphone 11 14.2 Safari
Also we are not not sure if it happens on older iOS versions. The bug does not happens on a android device.

Steps to reproduce:
1) Run chrome/safari on a iphone having 14.2
2) Run https://playcanv.as/p/nJ0wkUD4/  (Project: https://playcanvas.com/editor/scene/1055110)
3) Tap and hold your finger on the left side of the screen for around 2-3 seconds.

**Comment by leonidaspir** [comment]
I can confirm this issue. The CSS rule I've found works in this case (tested on an iPhone XR and on an iPad 2020 under iOS 14.2) is the following:

`document.body.style['-webkit-user-select'] = 'none';`

**Comment by Droopy78** [comment]
We tried these CSS rules to no avail:

  user-select: none;
  -webkit-touch-callout:none;                /* prevent callout to copy image, etc when tap to hold */
  -webkit-text-size-adjust:none;             /* prevent webkit from resizing text to fit */
  -webkit-tap-highlight-color:rgba(0,0,0,0); /* prevent tap highlight color / shadow */
  -webkit-user-select:none;                  /* prevent copy paste, to allow, change 'none' to 'text' */
  -moz-user-select: none;

@leonidaspir  We applied the rules the iFrame element we are running the game in.  Where did you apply it?

**Comment by leonidaspir** [comment]
On the body element of the iframed webiste. Basically I've been doing this in a regular Playcanvas script:

`
// initialize code called once per entity
PlayerController.prototype.initialize = function() {
    // CSS touch fix for iOS
    document.body.style['-webkit-user-select'] = 'none';
};
`
Rule `user-select` didn't work for some reason and had to target specifically the `-webkit-user-select` version.

**Comment by saadhaider78** [comment]
Thanks @leonidaspir adding that rule inside a pc script resolved the issue!

**Comment by Droopy78** [comment]
Thanks, that works!!  And thanks for the quick response!

**Comment by yaustar** [comment]
As an alternative to the above, you can add the following in a script:
```
(function() {
var style = document.createElement('style');
document.head.appendChild(style);
style.innerHTML = 
"canvas{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;outline:0;-webkit-tap-highlight-color:rgba(255,255,255,0)}" +
"body{-webkit-touch-callout:none;-webkit-user-select:none;-khtml-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;outline:0}";
})();
```
And change the asset loading type to be 'Before Engine' which will mean it be one of first things that is loaded and ran:
![image](https://user-images.githubusercontent.com/16639049/102245920-09124000-3ef6-11eb-8b70-e84be41fe9b7.png)
