### ISSUE TITLE
PlayCanvas version control conflict resolver fails to display script contents

### ISSUE THREAD

**Issue by h0lmiew** [playcanvas/engine#2622]
### Description

The past two days, our team have experienced an issue where the playcanvas version control fails to display the contents of a conflicted script. See screenshot:

![image](https://user-images.githubusercontent.com/5739868/102359572-3ec82f00-3fb1-11eb-8177-52e31bdb17c8.png)

This script is not empty - it contains many lines of code.

This does not just happen for this script, it happens for any conflicted script.

### Steps to Reproduce

1. Create a master branch
2. Create two child branches
3. Modify the same script, on the same line in both child branches.
4. Merge first child branch into master
5. Merge second child branch into master.
6. A conflict will appear, but the script displays no content.

If for resolving you select "USE ALL FROM..." either of master or the branch, then all the contents from the selected branch will be displayed correctly in the script.

This means that currently we have to back up the contents from both branches when resolving a merge conflicts, in order to manually do a comparision check in Notepad++, and the readd changes after having done "USE ALL FROM..." one of the branches.

**Comment by yaustar** [comment]
Confirmed with a small code file. No errors in dev console.

**Comment by yaustar** [comment]
Thanks for the report, a fix has been released now. Sorry for manual merging you had to done till, that's not fun :(

**Comment by h0lmiew** [comment]
Thank you for the quick fix 👍
