### ISSUE TITLE
WebGL error when zooming in Editor

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2635]
To repro:

* Load this scene: https://playcanvas.com/editor/scene/1044803
* Open JS console
* Mouse wheel zoom in and out

You should see this:

![image](https://user-images.githubusercontent.com/697563/102883628-39069980-4448-11eb-9d30-f8e9c94174fa.png)

**Comment by weilichuang** [comment]
editor.js 55426 line 
`renderer.boneTextureSizeId.setValue([boneTexture.width, boneTexture.height]);`

should be:
`renderer.boneTextureSizeId.setValue([boneTexture.width, boneTexture.height, 1.0/boneTexture.width, 1.0/boneTexture.height]);`

**Comment by mvaligursky** [comment]
thanks @weilichuang , awesome job, fix incoming
