### ISSUE TITLE
Implement support for KHR_mesh_quantization extension for GLB

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2636]
Specification: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_mesh_quantization

This extension is needed to handle all cases of EXT_meshopt_compression (#2630), especially a case with morph targets, where morph attributes are specified in quantized format.

**Comment by issacclee** [comment]
Hi Guys,
Just wondering, if this feature is being actively working on. We are thinking about adding support for KHR_mesh_quantization to better integrate with mesh_opt compression to achieve better compression ratio as well. If you guys haven't commenced any work towards supporting this extension, maybe we can help.

**Comment by mvaligursky** [comment]
Hi @issacclee ,

We have not started to work on this and don't have any ETA on when we will be able to at this stage. Please go ahead and investigate if you can help out, that would be much appreciated. I assume you've seen my comments here https://github.com/playcanvas/engine/issues/2630 regarding the partial support of EXT_meshopt_compression in our viewer - perhaps the level of functionality you need is already supported by the viewer (you can test your models here: https://playcanvas.com/viewer)?
