### ISSUE TITLE
Audio console warning

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2678]
Recently console started to show the audio warning (Chrome, Launcher):
![image](https://user-images.githubusercontent.com/5677782/103765912-9d1f8500-5026-11eb-99e6-474486e9dcd7.png)

A side note - the project has no sound, so no audio files in the assets. The google link redirects here:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

**Comment by willeastcott** [comment]
Hey @vkalpias, perhaps we should be lazy creating the AudioContext anyway. I mean, no point creating one for applications that don't play any sound anyway.

**Comment by vkalpias** [comment]
We can up to a degree. I believe we can make it not create an AudioContext if there are no audio assets or audio related components in the scene. 

However the AudioContext is needed to load any audio assets or to setup an AudioListener.

**Comment by LeXXik** [comment]
I think the assets might not include a sound file at the start of the app, or at least it might think it doesn't. I remember a project, where I implemented dynamic loading of audio assets and creating sound componenents on the fly. The app contained lots of game levels, where each level would have own set of images + sounds zipped in an archive. On level load, I would unzip the archive and generate texture and audio assets out of them.

**Comment by willeastcott** [comment]
The AudioContext is now created lazily so the warning only shows for apps that actually try to play audio. However, since we do not have control over how Chrome works in this regard and the warning is informative and harmless, I am closing this issue.
