### ISSUE TITLE
Messenger logs

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2679]
I would like to propose disabling the messenger logs by default, as it keeps clogging the console with redundant messages:
![image](https://user-images.githubusercontent.com/5677782/103767185-dd800280-5028-11eb-8e43-69e4ca37abdd.png)
![image](https://user-images.githubusercontent.com/5677782/103767221-ebce1e80-5028-11eb-8955-365232f4f60f.png)

**Comment by willeastcott** [comment]
This is an Editor issue, rather than an Engine issue. Can you log there please?

https://github.com/playcanvas/editor/issues

**Comment by Maksims** [comment]
Sometimes when reconnect happens, it does not recover fully state of the things in Editor, so refreshing page is then required. I notice this log and usually refresh page after. So either please look into recovering state properly, or keep the message so refresh decision can be still made.
