### ISSUE TITLE
Investigate alternative options to store prefiltered lighting cubemaps

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2685]
This could be a good solution to store our prefiltered cubemaps including mipmap cubemaps - they store 6 cubemaps (smaller and smaller sizes) in 2d texture https://twitter.com/Omar4ur/status/1049121014796509184

![octa](https://user-images.githubusercontent.com/59932779/103878613-92202f80-50ce-11eb-8d13-b48473b26922.jpeg)

Some more info on sampling (of a single of these) is few pages down here
https://webglinsights.github.io/downloads/WebGL-Insights-Chapter-16.pdf

and this could probably be used to pick mipmap of this
https://twitter.com/SebAaltonen/status/1327188239451611139

related PRs https://github.com/CesiumGS/cesium/pulls?q=is%3Apr+octahedral

**Comment by Maksims** [comment]
If stored in reverse: smallest to largest, then potentially streaming is possible, by uploading to GPU smallest size when available, and then progressively adding more as file gets downloaded.
Also it is probably possible using headers to instruct to load only certain amount of file, that way texture LoDs can be achieved.

**Comment by mvaligursky** [comment]
some other clever way to store cubemap with mipmaps in 2d texture.
advantage - you can find out the face, and then just easily compute offset / scale to get the mipmap

![cubemap-packed](https://user-images.githubusercontent.com/59932779/104856199-237e7580-5909-11eb-9cc0-337358c87aa3.jpg)

**Comment by willeastcott** [comment]
Haha, very smart. 🔥

**Comment by mvaligursky** [comment]
some more details on octahedral webgl use in the section on Environment Mapping here 
https://webglinsights.github.io/downloads/WebGL-Insights-Chapter-16.pdf

**Comment by willeastcott** [comment]
Fixed by https://github.com/playcanvas/engine/pull/3783
