### ISSUE TITLE
Add a 3D text mesh geometry creator

### ISSUE THREAD

**Issue by probitaille** [playcanvas/engine#2689]
This feature is a request that were asked multiple times in the forum. 

See my last post about it here: [3d text geometry generator](https://forum.playcanvas.com/t/3d-text-geometry-generator/16690)

### Description

The need for this feature is to be able to generate a 3D text geometry constructed by providing a string of text and other parameters like:

- the font;
- the color
- the space between letter;
- the alignment;
- the font weight (can be mixed with font);

### Examples

- Here an example from Three.js : https://threejs.org/examples/#webgl_geometry_text
- Here the documentation from Three.js: https://threejs.org/docs/#api/en/geometries/TextGeometry

Other engines can also do it:

- Unreal: https://docs.unrealengine.com/en-US/Basics/Actors/3DText/index.html
- Unity: https://docs.unity3d.com/Manual/class-TextMesh.html

### Image

![image](https://user-images.githubusercontent.com/2374739/103930275-7deb2b00-50ec-11eb-955d-bfe45b550f14.png)

**Comment by willeastcott** [comment]
This would be super-cool. I guess it breaks down into two parts:

* Code to tessellate a string into triangles.
* Code to extrude the mesh into 3 dimensions. Support for options for things like bevel would be useful here.

**Comment by willeastcott** [comment]
More generally, it would be cool to replicate the type of modifiers you find in apps like 3DS Max. e.g. 

* Bend
* Taper
* Twist
* Ripple
* Wave
* Extrude
* Subdivide
* ...etc

**Comment by willeastcott** [comment]
So this looks like a good library to use to extract the font outlines:

https://github.com/opentypejs/opentype.js

48KB gzipped.

**Comment by willeastcott** [comment]
Basically, you can load any TTF and then query a set of path 'commands' as follows:

https://github.com/opentypejs/opentype.js#path-commands

With that outline, we should be able to tesselate the path and then extrude it.

**Comment by willeastcott** [comment]
Progress so far:
I've used opentype.js and [earcut](https://github.com/mapbox/earcut) to implement this:

![textmesh](https://user-images.githubusercontent.com/697563/104842857-703d5e80-58bf-11eb-8329-ee072022d84e.gif)

**Comment by willeastcott** [comment]
More progress:

![image](https://user-images.githubusercontent.com/697563/104855843-18c2e100-5907-11eb-8932-c1446c75b31b.png)

Tessellation problems remain for: A, B, D, d, e, g and q (for an Arial TrueType font).

**Comment by willeastcott** [comment]
In case anybody would like to examine my progress in more detail, the project is here:

https://playcanvas.com/project/755330/overview/3d-text

The script is here:

https://playcanvas.com/editor/code/755330?tabs=41164910

**Comment by LeXXik** [comment]
I like this! I defeinitely need more spare time though... Going to fork it and help with removing Bezier.js dependency and use pc.Curve instead.

**Comment by willeastcott** [comment]
I'm not convinced `pc.Curve` will give as good results as `Bezier.js`. This is because the LUT generation (point sampling the curve) of `Bezier.js` samples the points based on curve's rate of change (if that's the right phrase). 😄  `pc.Curve` only allows you to sample based on time.

I think the priorities are to make the tessellation robust. Then we can figure out how to extrude the mesh.

The current problems with tessellation are probably because I'm not telling Earcut where the holes are in the characters (notice all problem characters have holes - despite some characters with holes tessellating fine). I believe that character holes have an anticlockwise path winding, versus a clockwise winding for outer paths. Maybe it's possible to do an area calculation of the path and do a test against zero. If anyone has a better idea, I'm open to suggestions.

**Comment by willeastcott** [comment]
I've confirmed that Earcut does what we need if you tell it which paths are holes:

![image](https://user-images.githubusercontent.com/697563/104894233-573eb700-596c-11eb-845b-5322fb86c5ab.png)

**Comment by willeastcott** [comment]
All characters now tessellate correctly:

![image](https://user-images.githubusercontent.com/697563/104950952-84658680-59b9-11eb-908f-b348a88805e4.png)

Next:
* Extrude glyphs
* Generate sensible normals

Normal generation isn't quite as simple as I would have hoped. `pc.calculateNormals` doesn't take hard edges into account. It can only generated smooth normals, which isn't what we want in this case. So we'll need a solution for that.

**Comment by mvaligursky** [comment]
I assume you want to keep the front face flat regarding the normals? Perhaps all you need to do here is to duplicate those vertices (do not share them with the extruded size faces) so they can have independent normals. That should make it compatible with calculateNormals function - it should not smooth the edge as there is no shared vertex / edge.

**Comment by willeastcott** [comment]
Sure. But what about the sides. 😉

**Comment by mvaligursky** [comment]
What look are you after? What should be smooth? I guess in general what needs to be done that for each vertex where you don't want smoothing, the vertex needs to be duplicated between faces that share it.

![image](https://user-images.githubusercontent.com/59932779/104952953-67cb4d80-59bd-11eb-9ee0-8aa5554f7e15.png)

In the example - if you want smooth edge in the middle, you need to create 4 vertices in total and two triangles to use them. If you want the edge to be sharp, you duplicate those two shared vertices and end up with 6 vertices, and each triangle would reference its vertex.

**Comment by willeastcott** [comment]
I'd probably want to be able to specify a crease angle above which the vertex would be split and you'd get a hard edge. Probably >30 degress perhaps?

**Comment by willeastcott** [comment]
Getting there:

![image](https://user-images.githubusercontent.com/697563/105105629-5dd44800-5aac-11eb-9c7c-59477c069774.png)

**Comment by willeastcott** [comment]
Normals now correctly calculated:

![playcanvas-text-mesh](https://user-images.githubusercontent.com/697563/105245992-8a4e9980-5b6a-11eb-896d-163ec254a058.gif)

**Comment by willeastcott** [comment]
Getting similar to the screenshot originally posted for this issue:

![image](https://user-images.githubusercontent.com/697563/105258768-58493180-5b82-11eb-9153-973cd8d33d08.png)

Beveling the text geometry is the main difference that would still need to be implemented (if you want that).

**Comment by willeastcott** [comment]
Added kerning support:

![kerning](https://user-images.githubusercontent.com/697563/105419390-8be59380-5c36-11eb-8b77-a980b88802f4.gif)

**Comment by Maksims** [comment]
Emoji?

**Comment by willeastcott** [comment]
😭 

![image](https://user-images.githubusercontent.com/697563/105420319-0b279700-5c38-11eb-9ec4-806cee749aba.png)

**Comment by mvaligursky** [comment]
maybe in a different font?

**Comment by Maksims** [comment]
I can imagine a game built using Emojis models.

**Comment by willeastcott** [comment]
Oh actually:

![image](https://user-images.githubusercontent.com/697563/105422930-7ffcd000-5c3c-11eb-8ea7-c7cbd28859ad.png)

The code was handling UTF-16 wrong. Sooo, looks like the sides have reversed winding, but otherwise kinda almost works. I'm wondering if the TTF file has to stroke color. If that's there, I should be able to color meshes correctly.

**Comment by willeastcott** [comment]
Added support for alignment:

![alignment](https://user-images.githubusercontent.com/697563/105432875-6d8c9180-5c50-11eb-9ed9-c7c8b76b5851.gif)

**Comment by willeastcott** [comment]
Quick experiment applying a custom shader chunk to the font's material:

![plasma](https://user-images.githubusercontent.com/697563/105434187-f99fb880-5c52-11eb-9a0c-39cb0602b42a.gif)
