### ISSUE TITLE
Add support for shadow map atlases 

### ISSUE THREAD

**Issue by raytranuk** [playcanvas/engine#2691]
- This will allow for more shadow casting lights without running out of texture sampler slots.
- Point light shadow map cube maps may need to be stored in multiple atlas slots and/or reprojected.
- We will have to support variance shadow maps as well as depth maps
- We may want to support non-uniform size atlas slots
- We may want to support pre-rendered static shadow maps that can be combined with dynamically rendered shadow maps

**Comment by mvaligursky** [comment]
closing in favor of https://github.com/playcanvas/engine/issues/3522
