### ISSUE TITLE
Leftover class to be converted to ES6

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2692]
Files that still need to be converted:

- [x] asset-reference
- [x] asset-variants
- [ ] channel
- [ ] channel3d
- [x] object-pool - rename to allocate-pool?
- [x] stats
- [x] program-library
- [x] vertex-format
- [x] I18nParser
- [x] controller
- [x] element-input
- [x] game-pads
- [x] glb-parser
- [x] audio
- [x] untar
- [x] script-attributes
- [x] script-type
- [ ] instance
- [ ] instance3d
- [x] sound
- [x] xr-dom-overlay
- [x] xr-finger
- [x] xr-joint

**Comment by willeastcott** [comment]
Looks to me like `AllocatePool` and `ScriptType` are migrated in the ES6 EventHandler PR.

**Comment by willeastcott** [comment]
Mostly done. I think we should just merge my PR and refactor the audio system separately. Also, @mvaligursky, the `VertexFormat.init` function probably needs some thought too as it doesn't easily migrate.

**Comment by mvaligursky** [comment]
You had a busy start of the weekend, well done!
vertex-format seems like it should be ok .. what is the problem you see? the init function as well as _defaultInstancingFormat and the property that returns it should all be static, and that should work?

**Comment by willeastcott** [comment]
OK, I'll try again. 😄

**Comment by willeastcott** [comment]
OK, done.
