### ISSUE TITLE
ParticleSystem — how to turn off the depth test?

### ISSUE THREAD

**Issue by superluffa-kei** [playcanvas/engine#2704]
There is no way to turn off the depth test.

My use case is, I want to add the camera space speed line effect. However, the particle is sometimes occluded by other objects. What I want to do is, just displaying the particle as is, without being affected by the current depth buffer state.

Currently, the only way to work around is drawing the particle system in another camera, after clearing the depth buffer. However, this solution harms the performance, as it has to re-write the entire depth buffer.

[https://pasteboard.co/JJfPb29.png](https://pasteboard.co/JJfPb29.png)
As we can see from this sample image, the box occludes the particles

Can we add the flag like "depth test" in the particle system? 

Thank you.

**Comment by yaustar** [comment]
You can change the for the particle system in code to disable the depth write and also put the particles systems on a layer that is after the layers you want to render on top of.

Here is an example of editing the material on the particle system: https://playcanvas.com/editor/code/738423?tabs=38272674

**Comment by mvaligursky** [comment]
I'll close this, please reopen if you find some issue.
