### ISSUE TITLE
Sponza looks different with candidate 1.38.0 release

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2716]
With 1.37.1:

![image](https://user-images.githubusercontent.com/697563/104377217-0c611180-551e-11eb-9526-be4937ee21df.png)

https://playcanvas.com/editor/scene/423508

With latest master branch:

![image](https://user-images.githubusercontent.com/697563/104377162-efc4d980-551d-11eb-8a1b-95ac14550201.png)

https://playcanvas.com/editor/scene/423508?use_local_engine=https://code.playcanvas.com/playcanvas-latest.dbg.js

Interestingly enough, there were already errors in the JS console for this scene. So there might be more than one problem in play here.

**Comment by mvaligursky** [comment]
This change is causing it: https://github.com/playcanvas/engine/pull/2535
@raytranuk - can you investigate please?

What I see is that some objects are very bright .. and the lightmap is not showing the way it should.

**Comment by raytranuk** [comment]
@mvaligursky - I will take a look
