### ISSUE TITLE
Find a way to hide class constructor from API docs

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2724]
At the moment we don't seem to have a way to hide a constructor from API docs generated by JSDoc. Example: I'd like to hide Lightmapper constructor, only the bake function should be exposed.
https://developer.playcanvas.com/en/api/pc.Lightmapper.html#Lightmapper

I want to hide it as it's not meant to be created by a user, and it exposes pc.ForwardRenderer as a parameter. This blocks us from hiding ForwardRenderer completely. 
https://developer.playcanvas.com/en/api/pc.ForwardRenderer.html

I tried this but could not get it to work
https://jsdoc.app/tags-hideconstructor.html

**Comment by mvaligursky** [comment]
@kungfooman - would you have any idea about this?

**Comment by FarazzShaikh** [comment]
Hello, I have been investigating this. The problem can be solved by having `@playcanvas/jsdoc-template` support the `@hideconstructor` tag. 

Changing [this line](https://github.com/playcanvas/playcanvas-jsdoc-template/blob/47020b968ab69e7af0879eaaa49f709aa5789e2e/tmpl/class.tmpl#L175) `tmpl/class.tmpl` within the `@playcanvas/jsdoc-template` node module to:

```html
    {{#if cls._class}}
        {{#unless cls.hideconstructor}}
            <h2>Constructor</h2>
            <!-- Constructor -->
            {{> method obj=cls}}
        {{/unless}}
    {{/if}}
```

Makes the `@hideconstructor` tag work if put in the class's JSDoc comment like so:
```js
/**
 * @class
 * @name Lightmapper
 * @classdesc The lightmapper is used to bake scene lights into textures.
 * @hideconstructor
 */
class Lightmapper { /*...*/ }
```

I will file a PR in `playcanvas-jsdoc-template` for the fix.

**Comment by mvaligursky** [comment]
This works great, thanks @FarazzShaikh
