### ISSUE TITLE
Allow user to set the ratio of DIPs to physical pixels

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#273]
PlayCanvas currently assumes that the canvas is the same resolution as the device independent pixel resolution of the canvas. However, the physical resolution can be different. The physical resolution is indicated by the window.devicePixelRatio property. So for a canvas with a styled width of 640x480 but a devicePixelRatio of 2.0, the physical resolution is actually 1280x960. We need to give the user the control to set the desired pixel ratio on the graphics device to take advantage of retina screens.

**Comment by guycalledfrank** [comment]
Added in https://github.com/playcanvas/engine/pull/278
