### ISSUE TITLE
Button element doesn't leave hover-state

### ISSUE THREAD

**Issue by MoserAlex** [playcanvas/engine#2730]
Since engine release v.1.38.0 the hover state of buttons doesn't seem to work correctly anymore in published builds when using sprites instead of colored tints. When switching back to v.1.37 by manually replacing the minified playcanvas engine, it still works.

Steps to reproduce:
- create a button element
- set transition mode to sprites
- add a default state and a hover state

The hover effect seems to work, when pressing launch in the editor, but it doesn't work properly when publishing the project.
I created a small test project to show the issue:

Project: https://playcanvas.com/project/754538/overview/testing-buttton-elements
Published Build: https://playcanv.as/p/pjSvIkBu/

**Comment by vkalpias** [comment]
Confirming that this works:

https://launch.playcanvas.com/1069751?use_local_engine=https://code.playcanvas.com/playcanvas-stable.js

But this doesn't:

https://launch.playcanvas.com/1069751?use_local_engine=https://code.playcanvas.com/playcanvas-stable.min.js

**Comment by willeastcott** [comment]
Maybe this is a good time to switch from Closure Compiler to Terser. 😄

**Comment by willeastcott** [comment]
To be thorough, I forked your test project (thank you for providing that!) and tested a published build against Engine 1.38.1. The problem is indeed fixed. 🎉

**Comment by MoserAlex** [comment]
Nice, thanks
