### ISSUE TITLE
Area Lights Example is not working on some Android devices.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#2739]
This URL: https://playcanvas.github.io/graphics/area-lights.html

Only have limited information:

1. One of devices webglreport.com screenshot:
![image](https://user-images.githubusercontent.com/636263/104758318-ee3a2200-5766-11eb-97f1-3783e7bb3a26.png)

2. Second device is Redmi 8 pro

They both see just black geometry, no illumination/textures.

**Comment by mvaligursky** [comment]
I wonder if the problem takes place with 1.38.0 or 1.38.1.

We've deployed the fix (fingers crossed) to the issue in 1.38.1
https://github.com/playcanvas/engine/pull/2736

**Comment by Maksims** [comment]
Another report, with iOS device:

webglreport.com:
![image](https://user-images.githubusercontent.com/636263/104759562-c350cd80-5768-11eb-936f-63002b016b5b.png)

Screenshot:
![image](https://user-images.githubusercontent.com/636263/104759602-d2d01680-5768-11eb-8d71-c69f6b96e57b.png)

**Comment by Maksims** [comment]
> I wonder if the problem takes place with 1.38.0 or 1.38.1.
> 
> We've deployed the fix (fingers crossed) to the issue in 1.38.1
> #2736

I don't have non-working device at hands. Have feeling it is hitting uniform count limit, which is not even related to Area Lights.

**Comment by mvaligursky** [comment]
it's not listed as it's private example for now .. even though I guess we sent a long to it so it's not so private anymore :)
We'll expose it in the next release.

**Comment by willeastcott** [comment]
Can you try again @Maksims? I believe this is fixed - I've just tested on iPhone XS and Samsung A5 - all good now.

**Comment by Maksims** [comment]
Here is another report, but this time it works, but notice how white sphere is skewed when on sides:

https://user-images.githubusercontent.com/636263/104763946-57be2e80-576f-11eb-8404-b9b0774064a9.mp4

**Comment by mvaligursky** [comment]
That's perspective isn't it? Looks like that in my browser as well. And on phone in landscape mode, in portrait the view is not as wide.

**Comment by mvaligursky** [comment]
Ah I see what you mean .. the reflection on left.

**Comment by willeastcott** [comment]
The white sphere is actually a disk. Just sayin'.
