### ISSUE TITLE
Circular Dependency: ProgramLibrary -> StandardMaterial -> ProgramLibrary

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2742]
The engine's layered design means that `src/graphics` should be independent of (so 'lower level' than) `src/scene`.

Currently, `src/program-library.js` imports `StandardMaterial` from `src/scene/materials/standard-material.js`.

The program library should not need a standard material to be able to generate shader code _for_ a standard material. It should just take options to control the generation.

This code is the problem:

https://github.com/playcanvas/engine/blob/master/src/graphics/program-library.js#L17-L25

**Comment by mvaligursky** [comment]
related: https://github.com/playcanvas/engine/issues/3788

This specific one might already be fixed in my opened PRs I think

**Comment by willeastcott** [comment]
Fixed by @mvaligursky...closing.
