### ISSUE TITLE
Mesh collider fails to see a collision

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2744]
Forum post: https://forum.playcanvas.com/t/adding-mesh-collider-though-script/16677/14
Repro project: https://playcanvas.com/project/755286/overview/collider-test

For some reason, when using an entity set from Editor as a collider (mesh collision), it works fine. However, adding the collider through script fails.

How to repro:
1. The scene has "Lever" entity with 2 scripts `fromEditor` and `fromScript`, where one is using collider from script, the other from editor.
2. Enable `fromEditor` script to use a collider set in the Editor (works).
3. Disable `fromEditor` and enable `fromScript` - collision fails.

On a side note, I am using yaustar's booklet for drawing physical shapes at run-time. The booklet doesn't work, e.g. trying to change opacity of the physical shape will crash, stating that it cannot find meshInstances of undefined. Perhaps related? If not, let me know and I will create a new issue.

**Comment by yaustar** [comment]
There's an error in the documentation (or code depending on the POV 😅 ) `asset` needs an id, not pc.Asset

Fixed fork: https://playcanvas.com/project/768847/overview/collider-test-fork

https://user-images.githubusercontent.com/16639049/109224580-0e242300-77b4-11eb-8457-85365e1809f1.mp4

See PR: https://github.com/playcanvas/engine/pull/2915

**Comment by yaustar** [comment]
Side note: The debug physics visualiser doesn't support mesh collision 😅 It's due an update the next time I need to use it :)

**Comment by yaustar** [comment]
@LeXXik Turns out you forgot to add the trigger script to the from script script file 😅 

```
        entity.addComponent('script');
        entity.script.create('trigger');
```

Fixed version here: https://playcanvas.com/editor/scene/1099325
