### ISSUE TITLE
Type checking engine source code using VSCode

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2752]
VSCode allows us to leverage some of the TypeScripts's type checking in regular JS files. This depends on JSDoc types in the source code. See more about it here:
https://code.visualstudio.com/docs/nodejs/working-with-javascript#_type-checking-javascript

This does not work with the engine JSDoc types at the moment, as they contain reference to pc name space.
<img width="447" alt="Screen Shot 2021-01-19 at 10 40 15 AM" src="https://user-images.githubusercontent.com/59932779/105023372-c7b80780-5a42-11eb-8c60-bd5a19d4ee95.png">

It would be great to remove pc. from documentation:
- it should be kept in examples (that are included in engine source code)
- existing links to API docs should still work (either by generating the same links, or adding redirects ... ) - example: https://developer.playcanvas.com/en/api/pc.BatchGroup.html

**Comment by mvaligursky** [comment]
@vkalpias - please have a look at this if possible.

**Comment by mvaligursky** [comment]
I guess this is now done @willeastcott ?

**Comment by willeastcott** [comment]
It is!
