### ISSUE TITLE
Cloning an animation component creates a copy of all animations

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#276]
Instead, animations should be referenced. The offending line is:

            clone.animation.animations = pc.extend({}, entity.animation.animations);

...in animation_system.js, Not only does this use a lot of memory but it's incredibly slow to copy entire animations.

**Comment by vkalpias** [comment]
Fixed with https://github.com/playcanvas/engine/commit/6820b49021723feb5a4a3cc2ae30bf176350f48a
