### ISSUE TITLE
AnimComponent is broken when multiple entities have the same name

### ISSUE THREAD

**Issue by IgorIFGD** [playcanvas/engine#2762]
Having multiple entities with the same name on the scene, animation isn't playing on all of them but first one.

Example project: https://playcanvas.com/editor/scene/1073891

Issue demo: https://launch.playcanvas.com/1073891?debug=true

The same scene works well under v1.37.1: https://launch.playcanvas.com/1073891?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.37.1.js

The issue may be possibly caused by using the entity name as cache key in default-anim-binder.js: https://github.com/playcanvas/engine/blob/cd60fd1889b94a497be63ccdba5411715c1d5b17/src/anim/binder/default-anim-binder.js#L23

**Comment by ellthompson** [comment]
Hi @IgorIFGD, i'm sorry you ran into this issue! It was caused during a rewrite of the anim system in v1.38.1. It has been resolved in https://github.com/playcanvas/engine/pull/2759 and will be fixed in engine v1.38.4!

I'm going to close this issue as a fix is currently in master.

**Comment by willeastcott** [comment]
Deployed:

https://github.com/playcanvas/engine/releases/tag/v1.38.4
