### ISSUE TITLE
Investigate the possibility of generating unwrapped uv coordinates during load time

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2766]
I’m curious about how expensive that uv unwrapping code we have is? The idea is to perhaps run it at load time instead of storing it in the glb uv1. I assume it might be too slow for complex models / levels but how about for simpler one? Load level without uv1, unwrap it, bake it, render it. No need to figure out how to store uvs in glb files. Could also atlas those uvs, that’d be quick part, to get better batching by sharing lightmaps between models. Perhaps even do this in worker.

**Comment by Maksims** [comment]
As I remember, unwrapping is a complex task, and very difficult to produce decently packed UVs and do it fast. Especially for medium/large models.
Also, it has to be deterministic for consistent baking.
We've previously midified JSON models, adding additional UV's buffers. Why not do same for GLB? Amount of data is not significantly large, and doing it once is better than doing it on every load, especially for laeger projects with async loading.

**Comment by mvaligursky** [comment]
I agree doing it ahead of time is better for most cases, but this case could be useful as well and should be considered. I agree with what you say on all counts.

But there are cases where people use external glb models (that we cannot import / export in Editor yet), or even build scene dynamically from these.

**Comment by mvaligursky** [comment]
I'll close this for now .. I've tried the current unwrapper on relatively simple meshes (50k polys) and that took about a minute. Not load time friendly ;)
