### ISSUE TITLE
WebGL 2.0 Compute

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#2773]
There is new Spec in the works, that will add Compute Shaders support to WebGL 2.0: https://www.khronos.org/registry/webgl/specs/latest/2.0-compute/

I've noticed related github logs in Chromium, so it is possible it will be available soonish.

**Comment by Maksims** [comment]
Read more on topic, it was pushed by Intel, but with WebGPU been abandoned as there is no easy way to implement Compute Shaders on Mac OS due to lack of such natively.

**Comment by cx20** [comment]
This is reference information. `WebGL 2.0`'s `Compute Shader` was implemented experimentally in `Chrome Canary` for a while, but has now been removed.
https://bugs.chromium.org/p/chromium/issues/detail?id=1131991&q=enable-webgl2-compute-context&can=2
The Compute Shader seems to recommend the use of the upcoming `WebGPU`.
