### ISSUE TITLE
Make Shadow Bias give more consistent results

### ISSUE THREAD

**Issue by raytranuk** [playcanvas/engine#2780]
Currently, shadow acne artifacts, for both dynamic and runtime light mapped lights, can be seen when running in WebGL1 that cannot be seen when running in WebGL2 with the same shadow bias - adjustment of the bias can remove the artifacts on WebGL1. 

This issue can be seen in this test project:
https://playcanvas.com/editor/scene/1077268

It would be better for the user if the same bias value set by the user would remove the shadow artifacts on both WebGL1 and WebGL2.

**Comment by mvaligursky** [comment]
Also, the slope bias is very shadow resolution dependent, and perhaps it should be auto-adjusted based on the assigned shadow slot: the bias should be larger if a smaller resolution slot is assigned. The specified bias value should be assumed to be specified for some resolution, for example 1024, and adjusted up or down based on the actual resolution used.
