### ISSUE TITLE
Tidy up and improve placeholder/default texture creation

### ISSUE THREAD

**Issue by raytranuk** [playcanvas/engine#2794]
description and requirements to be expanded upon - discussion started here: https://github.com/playcanvas/engine/pull/2731/#discussion_r566074361

**Comment by raytranuk** [comment]
NB Texture placeholders have been updated/fixed/improved in PR: https://github.com/playcanvas/engine/pull/3074

**Comment by willeastcott** [comment]
Hey @slimbuck and @mvaligursky - it's not clear to me what this issue is advocating for. Do either of you know? If not, I suggest we just close it.

**Comment by slimbuck** [comment]
I actually think the issue was addressed in the linked PR #3074. Probably fine to close.

**Comment by willeastcott** [comment]
Great stuff. Closing.
