### ISSUE TITLE
Blendshapes (morphs) exported from third-party .glb exporters are not importing correctly

### ISSUE THREAD

**Issue by GrimOrk** [playcanvas/engine#2802]
I had exported one .fbx file with different .glb exporters: Playcanvas converter (through the Editor), FBX2glTF (https://github.com/facebookincubator/FBX2glTF), and Blender 2.82.
The only one working correctly is by the PlayCanvas exporter. Blendshapes from all other files are importing, but they are blank, do not affect the mesh.

The structure of those files is different. 
GLB by PC converter:
`{
			"type": "VEC3",
			"componentType": 5126,
			"count": 1996,
			"sparse": {
				"count": 166,
				"values": {
					"bufferView": 68
				},
				"indices": {
					"bufferView": 66,
					"componentType": 5125
				}
			}
		},`

GLB by FBX2glTF:
`{
"componentType": 5126,
"type": "VEC3",
"count": 1996,
"bufferView": 12,
"byteOffset": 0,
"min": [
-0.0135115785524249,
-0.0042192074470222,
-0.0074337050318718
],
"max": [
0.0135115832090378,
0.0130863953381777,
0.00405951496213675
],
"name": "Face.M_F00_000_00_Fcl_ALL_Fun-3854"
},`

Files to reproduce:
[PCConverter](https://vrbaka.site/files/models/from_playcanv.glb)
[FBX2glTF](https://vrbaka.site/files/models/fbx2gltf_test.glb)

**Comment by mvaligursky** [comment]
relevant forum post
https://forum.playcanvas.com/t/suggestion-fbx-to-glb-offline-converter/17216/4

**Comment by slimbuck** [comment]
The FBX2glTF blendshapes seem to work in https://gltf.insimo.com/ but not https://gltf-viewer.donmccurdy.com/ or https://sandbox.babylonjs.com/. The PlayCanvas model produces validation errors we should address:
![Screenshot 2021-02-01 at 09 42 01](https://user-images.githubusercontent.com/11276292/106441302-c985c000-6471-11eb-977a-bea4c003bf0d.png)

**Comment by GrimOrk** [comment]
The FBX2glTF blendshpes are working in https://gltf-viewer.donmccurdy.com/ But because of inverted normals it is hard to see it. Try to rotate the camera around the face if you want to check it. At https://sandbox.babylonjs.com/ blendshapes are blank indeed.

**Comment by mvaligursky** [comment]
@GrimOrk - are you able to test your glb files with the latest engine / viewer?

**Comment by GrimOrk** [comment]
Sorry, this issue was quite old and I don't use Playcanvas right now. I've also lost the test files and I can't confirm if #3431 fixed it or not.
I'll close this issue.
