### ISSUE TITLE
Soft Area light shadows

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2815]
Implement soft area light shadows. Possible implementation is PCSS:
https://www.gamedev.net/blogs/entry/2265228-effect-area-light-shadows-pt-1-pcss/

This could be used at least for the lightmap baking, and during runtime on higher end platforms.

![image](https://user-images.githubusercontent.com/59932779/106465537-fe097400-6491-11eb-9e0f-44250c59b606.png)

**Comment by yaustar** [comment]
This would be pretty sweet!

**Comment by mvaligursky** [comment]
some relevant links
https://developer.download.nvidia.com/presentations/2008/GDC/GDC08_SoftShadowMapping.pdf
https://gregory-igehy.hatenadiary.com/entry/2015/12/08/000330
