### ISSUE TITLE
issue- highlighting on a mesh looks pixelated

### ISSUE THREAD

**Issue by savyashreea** [playcanvas/engine#2821]
Hello,
I'm facing some an issue while highlighting a particular mesh by using https://playcanvas.com/project/682988/overview/model-outline project as a reference.

In gameplay, when we highlight some mesh it looks pixelated. 
please find a sample project- https://playcanvas.com/editor/scene/1049546 
Here i tried adding a cube into the scene and highlighting it. Even here we can see that sometimes the cube has the slightly zigzag outline. is there any way to avoid this issue?

please find a screenshot attached, which shows the issue mentioned above
![image](https://user-images.githubusercontent.com/68535228/106560832-ac262400-654d-11eb-8f51-cf2f8fc4fa99.png)

**Comment by slimbuck** [comment]
Looks like the postprocess buffer isn't multisampled.

**Comment by raytranuk** [comment]
It probably is not multi-sampled - I shall investigate - it require an engine change to have post process buffers respect AA settings.

**Comment by raytranuk** [comment]
After some investigation, to have post processes properly work with MSAA we need the proposed WebGL extension: https://www.khronos.org/registry/webgl/extensions/proposals/WEBGL_texture_multisample/ to be approved, ratified and implemented. Unfortunately it was proposed in 2017 and remains on the proposed extensions list.

I will try modifying the post process shader to try to preserve the blending of the samples in the resolved outline source - it may give improved results?

**Comment by LeXXik** [comment]
I am using an outline effect to add a border around a custom mesh. However, that aliasing is not pretty :( 

![O552YefDrj](https://user-images.githubusercontent.com/5677782/109501990-12e12380-7aa1-11eb-9c19-4424c2e2ab4a.GIF)

@raytranuk, do you have any suggestions on what I may try? 

I guess, if nothing else, an alternative would be to add more vertices and make the border as a  mesh instance...

**Comment by mvaligursky** [comment]
@LeXXik - outline post-process is pretty GPU heavy operation .. for what you do in that gif, I'd suggest some other solution - custom mesh / quad with smooth alpha on the edges or similar.

**Comment by LeXXik** [comment]
@mvaligursky, thank you for the tip! Yes, I was considering it. Using an outline post process was the simplest way to implement it, and given there was plenty of GPU budget I could use, I went for it. 

When you say smooth alpha, do you mean interpoplating alpha channel in the shader, to go from fully opaque to transparent? I thought that if adding extra vertices to make a mesh instance, then there would be no aliasing issues, as that can be then controlled by the project level anti-aliasing setting?

**Comment by mvaligursky** [comment]
@LeXXik - yep I understand your reasoning, but I guess using post-processing solution would use up the battery on devices faster then it could.

if you mesh is just a line and a circle, I thought about rendering them using a quad with some texture on it .. and that texture could have nicely antialiased lines in it. But if that needs to be 3d, than yes, additional enlarged mesh could do it nicely.

**Comment by raytranuk** [comment]
Closing this issue - as post processes do not seem like the preferred solution - and can not be done fully correctly.
NB a possible post process based approximate solution is  to use the existing FXAA post process pass.
