### ISSUE TITLE
cubemap-renderer.js - Trying to bind current color buffer as a texture

### ISSUE THREAD

**Issue by maungers** [playcanvas/engine#2852]
Using the default script cubemap-renderer.js in the editor results in an error: Trying to bind current color buffer as a texture

https://playcanvas.com/editor/scene/1088850

And how to use prefiltered data whit a rendered cubemap? A simple change to the glossiness does not work.

**Comment by mvaligursky** [comment]
please see here
https://forum.playcanvas.com/t/dynamic-cubemaps-reflection-probes-render-to-texture-in-2020/15959
