### ISSUE TITLE
Post process effect regression in 1.39.0

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#2853]
Could be related to #2848.

The outline layer is very first one in the layers composition. It works correctly with build 1.38.4, but starts "lagging" behind the model with 1.39.0 (similar to my old issue #2519). Changing the layer order doesn't seem to change anything.

Please, let me know if a repro is needed.

**Comment by mvaligursky** [comment]
a repro would be useful. I'm investigating some issues with post-effects at the moment.
Thanks!

**Comment by LeXXik** [comment]
Here is the repro:
https://playcanvas.com/project/764016/overview/post-process-issue

As a side note: in the repro, I could not set the outline layer as the very first one in the layers composition- the app throws. This doesn't happen in the production project, though. Not sure, perhaps the shadows were calculated by then. I moved it after World layer in the repro.

**Comment by mvaligursky** [comment]
I was testing this yesterday in my fork, and still had some issues .. but right now with this PR it seems to work correctly
https://github.com/playcanvas/engine/pull/2882

I was changing priorities of camera and maybe few other little bits, not entirely sure.

The engine release with the PR should be out in the next few days .. fingers crossed this is a good solution.

**Comment by willeastcott** [comment]
@mvaligursky My results:

* 1.38.4 - no lag (https://launch.playcanvas.com/1088894?use_local_engine=https://code.playcanvas.com/playcanvas-1.38.4.js)
* 1.39.0 - lag (https://launch.playcanvas.com/1088894?use_local_engine=https://code.playcanvas.com/playcanvas-1.39.0.js)
* 1.39.3 - lag (https://launch.playcanvas.com/1088894?use_local_engine=https://code.playcanvas.com/playcanvas-1.39.3.js)

So yes, it still seems to be a problem with the latest engine.

**Comment by mvaligursky** [comment]
It needs changes to camera priority now .. try this
https://launch.playcanvas.com/1093398?debug=true

the project: https://playcanvas.com/project/766088/overview/post-process-issue--lex

**Comment by LeXXik** [comment]
Thank you for looking into this, @mvaligursky!

So, from the looks of it, the only thing changed in your project was the Camera priority from 0 to 1, making it lower in priority than the Outline Camera. However, when I changed that priority in my sample project, I get the following error:
![image](https://user-images.githubusercontent.com/5677782/108986715-1a688d00-769b-11eb-820b-e224683c4886.png)

It is as if I set the Outline layer the very first one in the layers composition. Same throw. Do I need to change something else?

**Comment by mvaligursky** [comment]
This is the long standing issue in the engine I still need to untangle, related to directional shadow map being used in the camera / layer before the world or something along these lines (not entirely sure on the conditions). I might have to either disable the light from the first camera / layer or change type to non-directional, experiment with that please.

**Comment by LeXXik** [comment]
Right, changing the light to Spot or Point mitigated the error with the shadow map.

**Comment by mvaligursky** [comment]
related issue (there are more I think)
https://github.com/playcanvas/engine/issues/2518

I'll close this, but please reopen if anything else is needed on this.
