### ISSUE TITLE
Implement support for WEBGL_depth_texture extension

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2856]
At the moment on WebGl1 platforms, we re-render World layer to a Depth texture to give post-processing and similar give access to scene's depth.

WebGl1 implements mentioned WEBGL_depth_texture extension: https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/

and based on this, we can pretty much take it for granted on all devices:
https://webgl2fundamentals.org/webgl/lessons/webgl1-to-webgl2.html

This could be a considerable performance gain in some cases.

Note - it's not supported by IE11 .. we can keep the old path for this, or we can perhaps disable any post-effects that require depth.

**Comment by Maksims** [comment]
> or we can perhaps disable any post-effects that require depth.

This would make development and debugging for users a difficulty. Not all users have access to IE11, also in engine, pretty much all features have a fallback, so this very likely shouldn't be an exception. If fallback has a slow path - that is different story, but at least it works as expected.

**Comment by mvaligursky** [comment]
I just checked on iOS 14.5, and WEBGL_depth_texture is supported there - we should definitely use it there.

**Comment by mvaligursky** [comment]
This is less relevant with the release of iOS 15, which supports WebGl2 and hence the extension is no longer required.

**Comment by willeastcott** [comment]
Let's close then...
