### ISSUE TITLE
1.39.0 now rendering of cubemaps using pc.drawFullscreenQuad does not work.

### ISSUE THREAD

**Issue by maungers** [playcanvas/engine#2862]
In this project, an array of spherical harmonics is made.
Algorithm:

```javascript
for (let i = 0; i < 6; i++) {
    the camera turns in the desired direction
    the face of the cubemap is rendered
    syncToCpu
}

shFromCubemap
```

The new way to render a cube map does not allow this, since there is no loop in which to render faces.
And the old method stopped working with the release of update 1.39.0

How do I get this to work now?

Rendering takes place in the render-sh.js script.

Before update: https://playcanv.as/p/eE6ilhhe/
After update: https://launch.playcanvas.com/1090695?debug=true
Project: https://playcanvas.com/editor/scene/1090695

**Comment by mvaligursky** [comment]
Your example uses non public API and so the compatibility is not guaranteed. To fix this, add the 3 lines to the place shown in the screenshot.

```
    let newLayers = this.camera.camera.layers;
    newLayers.push(layer.id);
    this.camera.camera.layers = newLayers;

```

<img width="693" alt="Screen Shot 2021-02-18 at 9 42 33 AM" src="https://user-images.githubusercontent.com/59932779/108338123-d45c8680-71cd-11eb-9945-d40d91fbaef0.png">

In the near future I'll be adding new public API to render cubemaps once off like this, for similar purpose (probe rendering)
