### ISSUE TITLE
Loading error in top left corner (multiple browsers)

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#2865]
While loading published webapps on (both Chrome and Edge), a black spot is shown early in the load:

(I do respect the list of requirements to write issues, but here I will let videos show the issue instead - better in this case)
https://www.youtube.com/watch?v=EzIFehCDDAw&feature=youtu.be
https://www.youtube.com/watch?v=yq1GZmYaRs4&feature=youtu.be

**Comment by yaustar** [comment]
That looks like the image you are using for the background of the loading screen html hasn't been loaded yet.

**Comment by FutureFireplace** [comment]
ok, will check up upon it (skeptical though, as the rectangle does not expands from top to bottom, nor is the background an image but a css gradient)

**Comment by yaustar** [comment]
Without a reproducible, all we can do is guess here.

**Comment by FutureFireplace** [comment]
Ok, I am going to leave it, as this is not a major-major problem; as the box only occurs at PC-server published launches. If uploaded to server the problem is gone - therefore the problem is pointing towards the Playcanvas server.
... still could be nice if solved in the future, as it is so much easier to make a rapid PC-published version, if one wants to share an early project (but does not want the black rect to show -> it looks a bit un-pro)

**Comment by yaustar** [comment]
The issue is that unless we have a reproducible, we can't investigate. When I load a published build on the playcanvas servers, I don't get the black square as shown below.


https://user-images.githubusercontent.com/16639049/107952220-61ff6280-6f91-11eb-959c-4e6a37595b0d.mp4


If you would like us to investigate, you will need to provide a reproducible for us to look at.

**Comment by FutureFireplace** [comment]
ok, with that in mind ... fair enough (as it must be local - yet I did get it on both PC and mobile)
But if you don't get the same rendering at all -let it rest /thx anyways for responding

**Comment by yaustar** [comment]
Bear in mind that it can be project specific, maybe there's a particular asset or size of assets could be the issue?

**Comment by FutureFireplace** [comment]
ok, I did see it on different projects ... yet again, it can be omitted by full export (which, on the other hand, does take longer).
Was/is wondering if it correlates to the console - it is/was in the same side
