### ISSUE TITLE
Better progression status for Unwrapping within the 'Pipeline' for imported 'Models'

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#2870]
For now there are a couple of effects within Unwrapping of the UV1 map of models, that are less service minded. As a user I often question if this - solely server process - is crashed or not?
![image](https://user-images.githubusercontent.com/6838800/107938715-0d0a1f00-6f86-11eb-8515-f8161c28601f.png)

Often the problem rise with a human character model above 20 MB (having a large degree of detail), and it is therefore not a surprise that the unwrapping of such takes longer - but how much longer exactly should one expect?
I therefore bring forth two suggestions:
1) The first one is maybe a bit far reaching, as this would contain a 'local machine' solution. Instead of unwrapping serverside, would it then be possible to download and install a little 'Unwrapping sw', that can produce an unwrapping file, for then to upload to the editor? (this way it might be easier to recognize if process have crashed on local machine or not)
2) There is already a progression bar for the unwrapping process, but can this be expanded to include some sort of console data output? (maybe as in the launch 'Profiler') This way the user is more secure of what is going on serverside.

**Comment by Maksims** [comment]
This should be in https://github.com/playcanvas/editor repo.
Unwrapping happens on client side.

**Comment by yaustar** [comment]
For such a large model, you may be best off unwrapping locally within the 3D modelling package instead

**Comment by FutureFireplace** [comment]
Ok, I hear you both: 
At yaustar > I understand the concept of your answer but not the concrete method?
(cf my already written statement: " ... would it then be possible to download and install a little 'Unwrapping sw', that can produce an unwrapping file, for then to upload to the editor? ... ")
How to do it locally? - I already unwrapping within modelling sw (being Blender in my case)

PS: Feel free to answer in newly created thread :-) ... https://github.com/playcanvas/editor/issues/309

**Comment by yaustar** [comment]
Sorry, I'm afraid you will have to ask someone from a 3D modelling background. I would literally doing the same as you in terms Googling a doc or tutorial for blender.

**Comment by mvaligursky** [comment]
closing this, as the thread has moved to Editor now .. https://github.com/playcanvas/editor/issues/309
