### ISSUE TITLE
Non-power-of-two textures cannot be mipmapped under WebGL 2

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2873]
Check out this scene:

![image](https://user-images.githubusercontent.com/697563/107957318-54011000-6f98-11eb-8fda-089680ad912b.png)

Left cube is 512x256 texture.
Right cube is 384x256 texture.

The right cube is clearly not mipmapped.

This is because of this `if` clause:

https://github.com/playcanvas/engine/blob/master/src/graphics/graphics-device.js#L2117-L2123

And also this `if` clause that generates the mipmaps:

https://github.com/playcanvas/engine/blob/master/src/graphics/graphics-device.js#L2045

WebGL 2 has the ability to mipmap non power-of-two textures. So the `if` statements should/could be updated to check `this.webgl2`. The only downside here is that this will cause the engine to produce different graphical results under WebGL 1 and WebGL 2. But I personally think that's OK, particularly with WebGL 1 becoming less and less prevalent.

This issue was originally identified here:

https://forum.playcanvas.com/t/whats-wrong-with-these-bricks-mipmaps/17824

**Comment by mvaligursky** [comment]
related to https://github.com/playcanvas/engine/issues/2607
