### ISSUE TITLE
Humanoid rig from UE4 does not animate as expected (e.g shoulder separates)

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2875]
Forum thread with expectations: https://forum.playcanvas.com/t/fbx-import-to-pc-not-working/17840

Note that the left shoulder is 'dislocated'

https://user-images.githubusercontent.com/16639049/107971911-f924e400-6faa-11eb-84a8-95584f528879.mp4

This is with GLBs as model and animation. The same occurs with the Anim Component too.

Project: https://playcanvas.com/editor/scene/1091710
Viewer: https://playcanvas.com/viewer?load=https://playcanvas.com/api/assets/42621772/file/SK_Mannequin.glb?branchId=ddeacd00-a903-49ea-8103-a25feaf4967c&load=https://playcanvas.com/api/assets/42621778/file/Unreal%2520Take.glb?branchId=ddeacd00-a903-49ea-8103-a25feaf4967c

**Comment by mvaligursky** [comment]
I tried the fbx files for both mesh and animation in Unity, and getting the same. This points to the issue with the fbx assets.

<img width="371" alt="Screen Shot 2021-02-15 at 7 16 09 PM" src="https://user-images.githubusercontent.com/59932779/107985621-54ae9c00-6fc2-11eb-9e98-2b5817a92a62.png">

**Comment by slimbuck** [comment]
Maya
![Screenshot 2021-02-15 at 22 42 12](https://user-images.githubusercontent.com/11276292/107999354-196e9600-6fdf-11eb-8bc5-281437a23b76.png)

**Comment by yaustar** [comment]
Closed as the issue is on the exporter, not PlayCanvas.
