### ISSUE TITLE
TextureEncoding inconsistency

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2890]
Upstream thread: https://github.com/KhronosGroup/glTF-Sample-Models/pull/296

easiest repro for me is to load this, while debug console is opened:
https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=TextureEncodingTest&scale=0.2&type=glTF-Binary

The spheres in left column are brighter than in the other columns, while they should be the same.
It does not happen each time this is reloaded.

<img width="790" alt="Screen Shot 2021-02-19 at 1 39 37 PM" src="https://user-images.githubusercontent.com/59932779/108512080-a011c480-72b8-11eb-9ea3-bc0e9ee1bfe8.png">

**Comment by slimbuck** [comment]
managed to reproduce in the viewer too:

https://playcanvas.com/viewer?load=https://cx20.github.io/gltf-test/tutorialModels/TextureEncodingTest/glTF-Binary/TextureEncodingTest.glb


(Reload tab with browser cache disabled)

**Comment by willeastcott** [comment]
@cx20 We don't seem to be able to repro this any more. I suspect it has been fixed. Can you confirm with the gltf-test texture encoding test?

**Comment by cx20** [comment]
I tested it again with PlayCanvas v1.55.0.
This problem is no longer reproducible, so I think it's probably fixed.

**Comment by mvaligursky** [comment]
Closing this as fixed.
