### ISSUE TITLE
Add a gizmo system

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#2904]
The Editor has a great translate/rotate/scale gizmo.

![gizmo](https://user-images.githubusercontent.com/697563/108835334-3d297180-75c7-11eb-9c8c-ee207abb8f07.gif)

It would be great if the engine supported a generic gizmo system that could be shared between various applications. Here are some feature I would like to support in this system:

* Shouldn't be dependent on framebuffer picker (because this relies on the GPU and is inefficient). Just use math to perform ray-intersection tests.
* Support translate/rotate/scale but potentially any type of gizmo that could depend on hover and pick+drag type input.
* Configurable graphical representation (size on screen, thickness/size of graphical elements, etc)
* Shading controls (flat shaded vs lit)

**Comment by kungfooman** [comment]
More like a general question, would code from Three.js or Babylon be welcome?

![image](https://user-images.githubusercontent.com/5236548/109813605-de4ea280-7c2d-11eb-9928-1880c3efa80e.png)

The example is here: https://threejs.org/examples/misc_controls_transform.html
Actual code is here: https://threejs.org/examples/jsm/controls/TransformControls.js

It would only require like 20 "polyfills" for the Three.js imports.

There is also more code I would like to use in PlayCanvas, like their FBX importer and glTF exporter.

**Comment by willeastcott** [comment]
I don't think we'll need to use that code. I've got most of the Editor code extracted in this project:

https://playcanvas.com/project/768040/settings

Next, I'm going to replaced the framebuffer picker with ray-triangle intersection tests for the gizmo. This should be more performant and make it easier to use in an XR app.

I agree that adding a glTF exporter would be very valuable. But that's a different issue. Again, I don't think we need to take code from anywhere to implement that.

**Comment by mvaligursky** [comment]
For the picking, perhaps we could resurrect this one https://github.com/playcanvas/engine/pull/989

**Comment by willeastcott** [comment]
Yes. We should. I'm gonna put a simple ray-triangle function into my gizmo script for now though. BTW, it should be easier to write the code to do Mesh/Ray intersection now, since you added `Mesh#getPositions/getIndices`.
