### ISSUE TITLE
Documentation for GraphicsDevice

### ISSUE THREAD

**Issue by detzt** [playcanvas/engine#2916]
I noticed that several methods of GraphicsDevice have no documentation and are therefore not showing up in the typings.d.ts and the API reference. Maybe they are simply internal methods and can be ignored, but similiar methods are public.

For example:

https://github.com/playcanvas/engine/blob/70df06dac6381c5f7370f9816af34a10fd8e26c2/src/graphics/graphics-device.js#L1227
https://github.com/playcanvas/engine/blob/70df06dac6381c5f7370f9816af34a10fd8e26c2/src/graphics/graphics-device.js#L2545
https://github.com/playcanvas/engine/blob/70df06dac6381c5f7370f9816af34a10fd8e26c2/src/graphics/graphics-device.js#L2550
https://github.com/playcanvas/engine/blob/70df06dac6381c5f7370f9816af34a10fd8e26c2/src/graphics/graphics-device.js#L2557
https://github.com/playcanvas/engine/blob/70df06dac6381c5f7370f9816af34a10fd8e26c2/src/graphics/graphics-device.js#L2567
https://github.com/playcanvas/engine/blob/70df06dac6381c5f7370f9816af34a10fd8e26c2/src/graphics/graphics-device.js#L3160
and various texture and shader methods.

I'm unsure about creating a PR, because I don't know which of them are intended to be part of the public API.

**Comment by mvaligursky** [comment]
Do you have a particular need to use these?
As we're considering adding WebGPU support this year, I'd prefer to not expose any additional functions as most of these are subject to change.

**Comment by detzt** [comment]
I'm only using `setFramebuffer` and `readPixels` to create a screenshot from a second camera. Since TypeScript complained that they are missing the in typings file I just wanted to let you know ;) I can understand your point and don't mind if you take that path.

**Comment by mvaligursky** [comment]
Closing for now. Thanks for reaching out.
