### ISSUE TITLE
depth buffer is not working correctly after adding layers and removing them again

### ISSUE THREAD

**Issue by raytranuk** [playcanvas/engine#2932]
This can be seen when launching this editor scene:

https://playcanvas.com/editor/scene/1102016

a workaround is to delete the camera and add a new one.

**Comment by mvaligursky** [comment]
@raytranuk  How do you re-create the problem? I see it goes away when I disable current camera and create new camera with the same settings / scripts . But how do you then break this new camera? I tried removing layers from it and adding them again in few different orders without problems.

**Comment by mvaligursky** [comment]
Closing as it cannot be reproduced.
