### ISSUE TITLE
Add support for gltf KHR_texture_basisu extension

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#2935]
https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_texture_basisu/README.md

**Comment by donmccurdy** [comment]
Just FYI, this documentation may be helpful for supporting KTX and Basis Universal: https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/KTXDeveloperGuide.md. It's a fairly new document, please let us know if you have any issues with it.

/cc @lexaknyazev (author)

**Comment by slimbuck** [comment]
Wow that's super cool - thanks!

**Comment by slimbuck** [comment]
This was added in #3380
