### ISSUE TITLE
Implement support for cascaded shadow maps for directional light

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2937]
Possible features:
- cascades 1 .. 4
- different frequency of updates of individual cascades
- non-linear distribution of cascades
- optional cross blend between cascades (either by blended or dithered transition)

Note: partial implementation is here: https://github.com/playcanvas/engine/pull/2936

**Comment by willeastcott** [comment]
@leonidaspir is going to love this for his large, expansive terrains!

**Comment by Maksims** [comment]
What API will be for controlling distance per/forall cascades.
`numCascades` - will become public later?
Will it work well with PCF and VSM techniques?

Awesome addition to an engine, long-awaited.

**Comment by mvaligursky** [comment]
yes numCascades will be public later. I'm not sure about other API yet at all, further detail when I spend some more time on it .. so far I've only did very basic infrastructure support for it.
I'd hope it should work with PCF / VSM just fine.
