### ISSUE TITLE
Allow Collider component to accept Render as a source of mesh, in addition to Model

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2944]
- CollisionComponent accepts .model, needs to accept .render as well
- the asset could be then either of these
- CreatePhysicalShape needs to change to handle both (see screenshot) - it would just loop over mesh instances of model or render and do the same with both
- fix editor/public/js/editor/gizmo/gizmo-collision.js to handle the presence of a renderAsset

![Screen Shot 2021-03-05 at 4 02 33 PM](https://user-images.githubusercontent.com/59932779/110143064-bd718300-7dce-11eb-98fe-4c2f7fe66a5b.png)

**Comment by LeXXik** [comment]
Hmm, does it mean the `CollisionComponentData` would get a new property `.render`?

**Comment by mvaligursky** [comment]
also perhaps implement example using render:
https://github.com/playcanvas/engine/issues/2958
