### ISSUE TITLE
Shaders generated by BasicMaterial instances are falsely shared between static and skinned MeshInstances

### ISSUE THREAD

**Issue by potentially-null** [playcanvas/engine#2945]
### Issue:
Shaders generated by BasicMaterial instances are falsely shared between static and skinned MeshInstances. As a result, the shader breaks for either all skinned or all static meshes rendered using these material instances.

### Expected:
Two BasicMaterial instances with identical configurations can be used to render different kind of MeshInstances (static, skinned, blend shapes).

### Steps to Reproduce

1. Create a BasicMaterial instance and assign it to a static/not skinned MeshInstance
2. Create a second BasicMaterial instance with an identical configuration and assign it to a skinned MeshInstance
3. Shader breaks for one of the two MeshInstances.

Possibly caused by shader key generation not taking options.skin into account:

https://github.com/playcanvas/engine/blob/135c8fe81af851e36860fcc019452f5025e254c3/src/graphics/program-lib/programs/basic.js

```
generateKey: function (options) {
        var key = 'basic';
        if (options.fog)          key += '_fog';
        if (options.alphaTest)    key += '_atst';
        if (options.vertexColors) key += '_vcol';
        if (options.diffuseMap)   key += '_diff';
        key += '_' + options.pass;
        return key;
    }
```

https://github.com/playcanvas/engine/blob/38649760a3afd22161d5bdae59f1e25abce4cbeb/src/scene/materials/basic-material.js
```
updateShader(device, scene, objDefs, staticLightList, pass, sortedLights) {
        var options = {
            skin: !!this.meshInstances[0].skinInstance,
            vertexColors: this.vertexColors,
            diffuseMap: !!this.colorMap,
            pass: pass
        };
        var library = device.getProgramLibrary();
        this.shader = library.getProgram('basic', options);
    }
```

The same issue probably occurs with blend shapes, but I haven't tested that.

**Comment by mvaligursky** [comment]
Would you have any repro for this @potentially-null ? I spent few minutes trying to recreate the issue without much luck.

**Comment by potentially-null** [comment]
Hi @mvaligursky,

I've created a small project for you: https://playcanvas.com/project/810149/overview/repro-issue-2945

<img width="922" alt="issue_2945" src="https://user-images.githubusercontent.com/80072747/124509218-d23c4280-ddd1-11eb-86f1-0efdf95b76e6.PNG">

There's a script on the root node which creates a BasicMaterial instance and assigns it to all mesh instances of the entities set in the inspector.
If there are exclusively entities with static or with skinned mesh instances assigned, all of them are rendered as expected. As soon as there are both static and skinned mesh instances in the list, one of the two types is not rendered correctly.

**Comment by mvaligursky** [comment]
Thanks for the repro @potentially-null, that was very helpful. The fix is now ready.
