### ISSUE TITLE
Investigate and fix non-power of 2 textures problems with webGL 1

### ISSUE THREAD

**Issue by raytranuk** [playcanvas/engine#2949]
Some investigation was done but root issue was not found and developers worked around the issue by switching to power of 2 size textures.

Opening this issue to remind to try to find the root cause of the problem:

References: 
https://forum.playcanvas.com/t/dynamic-driving-situation-update/18055
https://forum.playcanvas.com/t/solved-image-not-appearing-on-the-model-on-ios/18410

**Comment by saadhaider78** [comment]
Issue has been reproduced in this project 
https://playcanvas.com/editor/scene/1171428

**Comment by willeastcott** [comment]
WebGL 1 has the following restriction:

If a texture is non-power-of-two, it *must* have:
* mipmapping disabled with minification filter set to nearest or linear
* address modes set to clamp

At the moment, the engine correctly kicks the minification filter down to nearest or linear. But it ignores the address mode.

The engine already has code that will downsample an image to 'max texture size' supported by the WebGL implementation. We could potentially make image nearest power-of-two there. Slightly concerned about a couple of issues with that though:
* It would probably break texture atlases
* It would not work for compressed/basis textures

**Comment by yaustar** [comment]
The 'best' solution here may be to show warnings in the Editor when those options are configured: https://github.com/playcanvas/editor/issues/251

**Comment by yaustar** [comment]
Closed in favour of showing warnigs
