### ISSUE TITLE
pc.createMesh doesn't use device.extUintElement?

### ISSUE THREAD

**Issue by Glidias** [playcanvas/engine#2951]
I noticed createMesh function only creates UInt16 array and doesn't go for a big indices Uint32 array format if it's supported.

**Comment by mvaligursky** [comment]
Hi @Glidias - thanks for reporting it, we'll try and address it in the future.
In the meantime, please use the Mesh API to create your meshes which automatically uses 32bit indices if needed. See more details here: https://developer.playcanvas.com/en/api/pc.Mesh.html

And also examples here (called Mesh***) http://playcanvas.github.io/#graphics/mesh-decals.html
