### ISSUE TITLE
Support glTF extension: GLTF MSFT_lod - progressive loading

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#2960]
GLTF has [MSFT_lod extension](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/MSFT_lod), which allows adding different LoD versions to the model. Also, models are written into a file in order of lowest poly LoD, to the highest, which allows to progressively parse loading. This would be really useful for async loading, especially larger models.

Integration specifics:
1. Should upload LoD models to GPU during file load, and trigger "load" event on asset, so that render component and other places will react to it.
2. Rely on LoD system (does not exist), which would allow to set up LoDs distances and utilize them from this extension.
3. Provide ability to specify minimum LoD "preload", which would allow to start loading models, and be able to start application without waiting for high-poly LoDs to be loaded fully.

**Comment by willeastcott** [comment]
At the moment, we've decided to just implement ratified glTF extensions. This is a vendor specific extension, so closing.
