### ISSUE TITLE
Some languages don't text wrap because they don't utilise spaces in the language (eg chinese)

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2963]
eg
![image](https://user-images.githubusercontent.com/16639049/111135178-40839d80-8574-11eb-8914-01c5dc97fda5.png)

We need to add some exceptions in place for some languages to allow them to wrap even if there are no spaces. This makes text unreadable when the text is resized to fit.

**Comment by yaustar** [comment]
Unable to reproduce at the moment with an example project, waiting on a reproducible:

https://playcanvas.com/editor/scene/1111638

**Comment by yaustar** [comment]
Created a reproducible: https://playcanvas.com/editor/scene/1111638

When changing the min font size, we can see that the chinese with no spaces (middle text element) in the text gets as small as it can before it is force to break to new lines.

Whereas the chinese with spaces will break to new lines without going smaller.

https://user-images.githubusercontent.com/16639049/111361110-69478800-8685-11eb-9217-b6fb54e6f01d.mp4

**Comment by raytranuk** [comment]
@yaustar - I have a fix for the behavior - how do we tell if it is an asian font (or a font that treats characters as words)?

**Comment by yaustar** [comment]
@raytranuk Unfortunately, that's part of the problem. There's no setting on the Editor side to say whether it is an asian font or not beyond the locale code :( 

I don't know whether we should do based on locale code as we would have to be careful about what happens if there is no translation present and it fallbacks to another language (e.g english)

**Comment by mvaligursky** [comment]
@raytranuk - so what is the fix you mention? At what point do you spit the string if space is not there? Some special characters you detect or something? I wonder if the way you fix it could be used as a way to detect if fix is needed?

**Comment by LeXXik** [comment]
Perhaps the locale JSON could specify if the wrap should be on char, or default to word.

**Comment by yaustar** [comment]
Looking at how VIM has fixed this issue: https://github.com/vim/vim/issues/2579

**Comment by yaustar** [comment]
@raytranuk Issue re-opened as punctuation should not be word wrapped.

![image](https://user-images.githubusercontent.com/16639049/112954170-10bcc400-9136-11eb-82d2-bd8dd523d360.png)

In regards to where the line break opportunities are in CJK, this page seems to have a good explanation: https://w3c.github.io/i18n-drafts/articles/typography/linebreak.en

![image](https://user-images.githubusercontent.com/16639049/112954297-2c27cf00-9136-11eb-8bd0-8c92cf28c873.png)

![Uploading image.png…]()

**Comment by yaustar** [comment]
Wikipedia has a more comprehensive ruleset of what characters cannot start at the beginning of a line: https://en.wikipedia.org/wiki/Line_breaking_rules_in_East_Asian_languages

**Comment by yaustar** [comment]
It's been reported that it isn't working with Japanese text (ja-JP)

![image](https://user-images.githubusercontent.com/16639049/113114826-a70aeb80-9203-11eb-8ff2-4d9b071e8159.png)

**Comment by yaustar** [comment]
@raytranuk Going to have to add Thai to this list. Looks like they don't have visible spaces between words https://w3c.github.io/i18n-drafts/articles/typography/linebreak.en#sec_se_asia

![Uploading image.png…]()

**Comment by yaustar** [comment]
Asking client if zero width spaces are used between words in the Thai translations as I think that's the best we can do. I don't really want to go down the route of a dictionary lookup 😅

**Comment by yaustar** [comment]
Checked the text and there aren't any zero width characters in their translations. Will ask our internal translation team on what would be the best way forward here
