### ISSUE TITLE
Blending between differs greatly pending the animation used

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#2964]
Repro: https://playcanvas.com/editor/project/770335

Returning to the idle anim on the right bitmoji should not end up in plank position

https://user-images.githubusercontent.com/16639049/111144864-898d1f00-857f-11eb-8775-6b328c17b3a0.mp4

**Comment by ellthompson** [comment]
This was discovered to be related to the animation data used. If animations do not contain curves for certain bones, then previous values for that bone will remain. When blending two animations together, those animations should contain animation curves for all blended bones.
