### ISSUE TITLE
Clean up constructor of RenderTarget class

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#2968]
- at the moment based on JSDocs, the RenderTarget constructor takes options as the only parameter
- but it handles a case where Graphics Device is passed instead, followed by other parameters
- if device is passed in, it's not stored on the class .. and destructor does not do any cleanup
- most internal calls to this constructor in engine and examples use the undocumented constructor with the device

**Comment by willeastcott** [comment]
Yes, this is a horrible mess and it would be great to clean it up. 😄

**Comment by mvaligursky** [comment]
separate note: RenderTarget handles options using this code:

`        if (options instanceof GraphicsDevice) {`

which forces import of GraphicsDevice
which in turn generates circular dependency

`src/graphics/render-target.js -> src/graphics/graphics-device.js -> src/graphics/render-target.js`

**Comment by mvaligursky** [comment]
This has been done, engine internally and engine examples now only passes the options.
Constructor also sets this._device to null, which gets later updated by GraphicsDevice when the actual framebuffers are allocated.
