### ISSUE TITLE
alphaTest should be respected by pc.Picker and shadow mapping

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#300]
Currently `alphaTest` is not respected by `pc.Picker`, so it is possible to pick on occluded pixels.
As well as for shadow mapping, it has hardcoded static alphaTest value instead of using the one from material if it is set.

**Comment by guycalledfrank** [comment]
Alpha test cutoff threshold is already respected in shadow mapping. Not in picker though.

**Comment by guycalledfrank** [comment]
The problem with the picker is when you drag-n-drop an alpha-tested material onto object. If your mouse happens to be on a transparent pixel, then the next frame picker will select a different object behind the first. Then, again, first object becomes opaque again, and picker will select it, and so it flickers back and forth...

**Comment by willeastcott** [comment]
I think that's an Editor problem, not an engine problem. Although I'm not entirely sure how I'd fix it in the Editor codebase.

**Comment by guycalledfrank** [comment]
Added picker alpha-test support in https://github.com/playcanvas/engine/pull/654

In Editor, if you drag a material, you must set
picker._ignoreOpacityFor = last picked meshInstance
to prevent flickering.
