### ISSUE TITLE
v1.40 pc.createMesh implementation breaks custom collision meshes

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#3010]
The new implementation of pc.createMesh introduced in v1.40 breaks custom collision meshes consumed by Ammo.js. I can confirm when using the older v1.39.4 build everything works as expected.

### Steps to Reproduce
1. Open the Terrain From Heightmap example
2. Launch and watch the collision mesh being out of place (seems inverted or something?)
3. Launch with `?use_local_engine=https://code.playcanvas.com/playcanvas-1.39.4.js`, everything works as expected.

**Comment by mvaligursky** [comment]
I see the issue .. CollisionMeshSystemImpl.createPhysicalShape assumes mesh format is interleaved .. I'll fix that code.
`var stride = format.size / 4;`

**Comment by willeastcott** [comment]
I've added this project to the engine test plan. I'll deploy 1.40.2 after this bug is fixed.
