### ISSUE TITLE
Generated glTF materials look too shiny compared to reference glTF renders

### ISSUE THREAD

**Issue by raytranuk** [playcanvas/engine#3013]
It's been noted several times that materials in the PlayCanvas viewer looks incorrectly more shiny that in other glTF viewers.

After some investigation, the options to fix this issue are:
1) a) Enable GGX Specular on all materials that are generated from GLTF import.
    b) Add support for the roughness property in materials - see https://github.com/playcanvas/engine/issues/2559
    c) Add a new GGX variant without Anisotropy for improved performance when no Anisotropy is present
    d) Use half angle for Fresnel calculation.
    e) Add a GGX variant of our IBL.
2) a) Add some fudge factors into the generated materials from GLTF import to make the Blinn-Phong model look closer to GGX (it will not exactly match).
    b) Use a non-linear conversion of Roughness to Shininess (Glossiness).
    c) Use half angle for Fresnel calculation.
    d) Add fudge factors to the IBL too.

Useful reference implementations: 
https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/source/Renderer/shaders/brdf.glsl
https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/source/Renderer/shaders/ibl.glsl

**Comment by willeastcott** [comment]
@slimbuck Isn't this resolved now?

**Comment by slimbuck** [comment]
Yes, closing.
