### ISSUE TITLE
9-sliced image element edge blur

### ISSUE THREAD

**Issue by weilichuang** [playcanvas/engine#3017]
![9-sliced](https://user-images.githubusercontent.com/2355262/112637736-6e70b800-8e79-11eb-8693-a12c2d7b1863.png)
project:https://playcanvas.com/editor/project/779332
demo:https://playcanv.as/p/WtigPhKa/

**Comment by LeXXik** [comment]
You can try increasing the Pixel Per Unit to for example 1.5 in the Element Component properties.

**Comment by weilichuang** [comment]
Yes,increasing the Pixel Per Unit will fix the problem. but the edge is a little different
