### ISSUE TITLE
WebXR AR experience doesn't look like it depth tests

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3031]
Android Chrome

Test project: https://playcanvas.com/editor/scene/1120517 (when in AR, look for a floor, dinosaurs should appear as you move around the room)

<img width="1293" alt="Screenshot 2021-03-29 at 09 32 52" src="https://user-images.githubusercontent.com/16639049/112809875-692a8d80-9072-11eb-84e0-52ee87051fa8.png">

https://user-images.githubusercontent.com/16639049/112809993-85c6c580-9072-11eb-85d9-36d0085c122e.mp4

The feet/legs can be seen through the body and the circle should be below the dinosaur too.

Sometimes the issue goes away after moving around the room or looking from certain angles.

The dinosaur models can be looked at separately in this scene https://playcanvas.com/editor/scene/1120526

**Comment by yaustar** [comment]
Also tested against the earliest version that still works with this AR experience: https://t.co/YUcFNikNpB?amp=1

**Comment by mvaligursky** [comment]
@Maksims - any idea about this one?

**Comment by Maksims** [comment]
> @Maksims - any idea about this one?

Could this be related?
https://github.com/playcanvas/engine/blob/master/src/framework/application.js#L2302

XRSession provides its own framebuffer, so rendering in XR session happens not into backbuffer, but a provided framebuffer. I actually not sure why it is happening.

**Comment by mvaligursky** [comment]
Just looking at the documentation and code, wondering if this is related:

- @Maksims pointed out we use frame.session.renderState.baseLayer.framebuffer as a framebuffer
- the BaseLayer api https://developer.mozilla.org/en-US/docs/Web/API/XRWebGLLayer/XRWebGLLayer specifies that we can pass depth property, which we don't but it defaults to true anyways .. so perhaps not needed?
- this bit here https://developer.mozilla.org/en-US/docs/Web/API/XRWebGLLayer/framebuffer talks about opaque framebuffer, but mentions: _Opaque framebuffers initialized with the depth property set to false will not have a depth buffer and will rely on the coordinates alone to determine distance._ As we don't sppecify false, this should be ok? It seems like the behaviour seems consistent with depth being false though.

**Comment by mvaligursky** [comment]
possibly related as well (missing stencil buffer on the Quest)
https://forum.playcanvas.com/t/stencil-buffer-on-oculus-quest/21471/3

**Comment by mvaligursky** [comment]
This is possibly fixed by https://github.com/playcanvas/engine/pull/4038, but I cannot confirm as on my Android Chrome device I cannot reproduce the issue. https://github.com/playcanvas/engine/pull/4038

**Comment by mvaligursky** [comment]
@yaustar - are you able to re-test this one please

**Comment by yaustar** [comment]
Re-tested, looks good! Thanks!
