### ISSUE TITLE
Static enabled spot lights do not light up the scene as expected

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3052]
Scene: https://playcanvas.com/editor/scene/1122796
Forum thread: https://forum.playcanvas.com/t/issue-with-static-lights/19233/

Spotlight with static disabled
![image](https://user-images.githubusercontent.com/16639049/113150602-28767400-922c-11eb-8cd6-df465eb83ae0.png)

Spotlight with static enabled
![image](https://user-images.githubusercontent.com/16639049/113150685-3d530780-922c-11eb-84f0-ed42b5bdfb82.png)

**Comment by mvaligursky** [comment]
maybe related to https://github.com/playcanvas/engine/issues/2079
