### ISSUE TITLE
_assignTexture fault

### ISSUE THREAD

**Issue by Casval111** [playcanvas/engine#3061]
function, MaterialHandler.prototype._assignTexture, changes materialAsset.data[Texture parameter name];
that will lead to wrong destroied Texture assigned to Material , if I unload the Texture asset and Material asset then reload them.

**Comment by yaustar** [comment]
Example from the forums:
 
https://forum.playcanvas.com/t/unloading-and-reloading-materials/18838/15 
 
> Here is an example that shows the error. Go to Scene02 and then back to Scene01. See the console WebGL errors due to the material asset’s data texture references pointing to now destroyed Textures. To see a workaround uncomment line 21 of _dev.js ( link below )
> 
> https://playcanvas.com/project/779957/overview/asset-helper
> https://playcanvas.com/editor/code/779957?tabs=45050271
> 
> The work around is when a material is unloaded, I reset the material asset’s data texture references back to the texture assets ID.
