### ISSUE TITLE
Forward rendered cullShadowmaps bug

### ISSUE THREAD

**Issue by devcem** [playcanvas/engine#3063]
After the latest release this function has a bug, I couldn't determine the pattern but on game maps, nothing changed. For some reason, it appeared after the latest engine release.

Here is a screenshot from it :
<img width="591" alt="Screen Shot 2021-04-05 at 21 14 14" src="https://user-images.githubusercontent.com/7432641/113610357-ac2dc780-9655-11eb-906e-694088233ca1.png">

The only pattern I determined is when I remove all objects from the scene and add new ones, including lights.
I have this issue right now on the game, live version, it freezes the user's game for one second on map load then it doesn't occur again.

I'm not sure how I can provide a scene for reproducing it. I'll try to investigate it more. But I wanted to post this issue because it's on live and maybe PlayCanvas team has an easy solution for it.

Potential causes :
- I change the scene and it also removes batched entities, maybe the new culling system somehow caches entities and when they are not on the list, it causes the issue.
- I have some custom shaders on the scene, like a flag, they also have shadows, but maybe that can also cause the issue.
- Lights has "once" option on them, I update them once when scene loaded, I'm not sure if this has any affect on issue.

**Comment by mvaligursky** [comment]
Hi @devcem - thanks for the report, I'll investigate this tomorrow .. from looking at the code, this should be quick to sort out.

**Comment by mvaligursky** [comment]
In the meantime, perhaps release the game with the previous version of the engine is possible?

**Comment by mvaligursky** [comment]
@devcem - I've looked over the code, it's related to the shadows for the directional light based on the callstack, but I don't see an obvious way to reproduce it or see where it could possibly happen in code. Is there a way I can reproduce it in your project? If so, a link / repro steps would be great.

**Comment by devcem** [comment]
@mvaligursky I prepared a demo for you, so you can test it out quickly.

- Open the link, wait until the game ends
- Vote "Temple" map
- You'll see an error in logs
- Since the game is short it will continue to switch maps, select different maps on each case to trigger it

https://playcanv.as/index/rFDxa2Km#NDA

Make sure it has "#NDA" has at the end, otherwise it doesn't connect server properly.

**Comment by mvaligursky** [comment]
Ok I have a fix .. I have not tested it with your game, but I'm very confident this is the reason. Thanks for the report and repro, that was very useful in tracking this down.

**Comment by willeastcott** [comment]
@devcem Now that this has been fixed, when would you like us to deploy 1.10.5?

**Comment by devcem** [comment]
> @devcem Now that this has been fixed, when would you like us to deploy 1.40.5?

Well if possible, today would be great. So I can update the game today. I know it doesn't crash the game but I believe it causes some issues on map switches, like frame drops, etc.

Also thank you for quick response and fix :)

**Comment by willeastcott** [comment]
@devcem 1.40.5 has finally be deployed. Can you let us know if you continue to have problems with this?

**Comment by devcem** [comment]
@willeastcott it's fixed, thank you!
