### ISSUE TITLE
mulScalar() is not a function?

### ISSUE THREAD

**Issue by michael-mccrickard** [playcanvas/engine#3072]
[https://github.com/playcanvas/engine/issues/2942](url)

Apparently, a recent re-factor of the vector code discussed above has made the Vec3 function mulScalar() for engine-only users like myself.  When I try to use it with new pc.Vec3 variable, I get:

`TypeError: vec.mulScalar is not a function`

Leonidas suggested that I bring this issue up here.

**Comment by yaustar** [comment]
Odd, I just ran this in the console with no problem:
![image](https://user-images.githubusercontent.com/16639049/114061009-d8338d80-988d-11eb-93cf-6a8c9b78f03b.png)

Is there an example/repro that can be shared?

**Comment by willeastcott** [comment]
Check you're actually using the latest engine. If you grab it with NPM, you might still be on an earlier version.

**Comment by mvaligursky** [comment]
closing, as it was confirmed the old engine version was used.
