### ISSUE TITLE
Setting soundInstance.currentTime, callbacks are not suspended correctly

### ISSUE THREAD

**Issue by wei292224644** [playcanvas/engine#3082]
When I modify 'soundComponent.slots[''].instances[0].currentTime',I think the stop callback also needs to be suspended.

https://github.com/playcanvas/engine/blob/038154c4efaba04f18948647875b6e7e31394cb1/src/sound/instance.js#L707

![image](https://user-images.githubusercontent.com/16398073/114382093-89a02f00-9bbe-11eb-928e-f1d360737634.png)

**Comment by yaustar** [comment]
More like?
```
                const suspend = this._suspendInstanceEvents;
                this._suspendInstanceEvents = true;
                
                // stop first which will set _startOffset to null
                this.stop();
                // set _startOffset and play
                this._startOffset = value;
                this.play();
                
                this._suspendInstanceEvents = suspend;
```

**Comment by wei292224644** [comment]
Yes ,i think it might be like this. @yaustar
