### ISSUE TITLE
Text elements in World space aren't transparent from certain angles and distances

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3087]
https://playcanvas.com/editor/scene/1130143

Zoom out at an angle and the 'background' of each glyph starts to be more visible. Related to https://forum.playcanvas.com/t/text-node-visible-through-meshes/19445/6 ?

![image](https://user-images.githubusercontent.com/16639049/114540766-d67f1680-9c4d-11eb-9f50-93b8b68098b6.png)

**Comment by yak32** [comment]
ok, we use MIPMAP_LINEAR for texture filtering, but don't generate mipmaps for texture atlases

**Comment by yak32** [comment]
using FILTER_LINEAR and using discard in the fragment shader fixes the issue: 
![image](https://user-images.githubusercontent.com/7876371/121219152-4f2fd700-c87b-11eb-967b-efbcb4705271.png)

**Comment by yaustar** [comment]
Another developer with a similar issue: https://forum.playcanvas.com/t/3d-text-blur-problem/22877

![image](https://user-images.githubusercontent.com/16639049/141974808-1a34d39e-3104-4a78-95dc-c5a658dd0b5d.png)
