### ISSUE TITLE
Add visibility property for Model and Render Components

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#3089]
It would be nice to have a property representing a visibility state of all mesh instances, which can be toggled via show/hide methods. A mesh instance may have a setter for the visibility property, which would adjust the component's property, if toggeled individually. At the moment, the only way to check if a model is visible is to loop through all mesh instances. However, if the mesh instances are not toggled individually, that is an unnecessary overhead that can be avoided.

An option to handle the multiple instances is to add a third enum flag, which would represent a partial. For example:

```
VISIBILITY_STATE = 0;   // hidden
VISIBILITY_STATE = 1;   // visible
// they would still get evaluated to true/false in existing code

VISIBILITY_STATE = 2;   // mesh instances may potentially be of different states
```

**Comment by mvaligursky** [comment]
internally, the function would need to loop anyways, as it cannot guarantee it was not switched on some mesh instance. And considering this is 2 lines of code to do, the complexity of state 2 you mention seems just not worth it.

**Comment by LeXXik** [comment]
Yes, initially I was thinking 0/1 would be only set via hide/show, avoiding the internal loop. But after second thought, I agree, it is easier to track the visibility state separately.
