### ISSUE TITLE
It is not possible to set a procedurally created mesh on a collision component

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#31]
If you create a model procedurally and set it on a model component for rendering, it is not currently possible to also set it on a collision component to make the mesh into a static body. Not using the API anyway. A workaround is to call:

            context.systems.collision.addComponent(this.entity, {
                type: 'mesh'
            });
            this.entity.collision.model = model;
            context.systems.collision.implementations.mesh.doRecreatePhysicalShape(this.entity.collision);

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/7121f902e44fcca4f05db5682e3a3284cb6da483
