### ISSUE TITLE
Changing tiling on material with clear coat will make the material white

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3110]
See video
https://user-images.githubusercontent.com/16639049/115580136-ba6b1d00-a2be-11eb-86f4-ed38805a900e.mp4

**Comment by mvaligursky** [comment]
this is the shader error we're getting, when tiling is enabled and clear coat normal map texture set up on a new material
[clear-coat-tiling-error.txt](https://github.com/playcanvas/engine/files/6607952/clear-coat-tiling-error.txt)

**Comment by willeastcott** [comment]
So yeah, this line looks wrong, no?

```
21:	varying vec2 vUV0_1;
```

Presumably it should be:

```
21:	varying vec2 vUv0;
```

**Comment by mvaligursky** [comment]
Perhaps, but this is generated in code, not a chunk. I suspect the story is more complicated though, as we can have some uv coordinates transformed individually or not at all per texture slot, so multiple texture coordinates need to be supported. Would need deeper investigation.
