### ISSUE TITLE
[Question] Confused about the fresnel formula

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#3112]
The origin fresnel schlick is:

![](https://render.githubusercontent.com/render/math?math=F_%7BSchlick%7D(v%2Ch%2C%20f_0%2C%20f_90)%20%3D%20f_0%20%2B%20(f_90%20-%20f_0)(1%20-%20v%20%5Ccdot%20h)%5E5)

This is what Filament do (From [brdf.fs](https://github.com/google/filament/blob/24b88219fa6148b8004f230b377f163e6f184d65/shaders/src/brdf.fs#L173-L182))

```glsl
vec3 F_Schlick(const vec3 f0, float f90, float VoH) {
    // Schlick 1994, "An Inexpensive BRDF Model for Physically-Based Rendering"
    return f0 + (f90 - f0) * pow5(1.0 - VoH);
}

vec3 F_Schlick(const vec3 f0, float VoH) {
    float f = pow(1.0 - VoH, 5.0);
    return f + f0 * (1.0 - f);
}

float F_Schlick(float f0, float f90, float VoH) {
    return f0 + (f90 - f0) * pow5(1.0 - VoH);
}
```

This is what Babylon.js do (From [pbrBRDFFunctions.fx](https://github.com/BabylonJS/Babylon.js/blob/5e6321d887637877d8b28b417410abbbeb651c6e/src/Shaders/ShadersInclude/pbrBRDFFunctions.fx#L115-L123))

```glsl
vec3 fresnelSchlickGGX(float VdotH, vec3 reflectance0, vec3 reflectance90)
{
    return reflectance0 + (reflectance90 - reflectance0) * pow5(1.0 - VdotH);
}

float fresnelSchlickGGX(float VdotH, float reflectance0, float reflectance90)
{
    return reflectance0 + (reflectance90 - reflectance0) * pow5(1.0 - VdotH);
}
```

This is what Three.js do (From [bsdfs.glsl.js](https://github.com/mrdoob/three.js/blob/66b9fa344ce01581033d171e1de09dd86bd5a3d7/src/renderers/shaders/ShaderChunk/bsdfs.glsl.js#L59-L70))

```glsl
vec3 F_Schlick( const in vec3 specularColor, const in float dotLH ) {
	// Original approximation by Christophe Schlick '94
	// float fresnel = pow( 1.0 - dotLH, 5.0 );
	// Optimized variant (presented by Epic at SIGGRAPH '13)
	// https://cdn2.unrealengine.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf
	float fresnel = exp2( ( -5.55473 * dotLH - 6.98316 ) * dotLH );
	return ( 1.0 - specularColor ) * fresnel + specularColor;
} // validated
```

This is what PlayCanvas do (From [fresnelSchlick.frag](https://github.com/playcanvas/engine/blob/f1692a66dcccc9a1127616a5b780b99b6ccbcd12/src/graphics/program-lib/chunks/fresnelSchlick.frag))

```glsl
void getFresnel() {
    float fresnel = 1.0 - max(dot(dNormalW, dViewDirW), 0.0);
    float fresnel2 = fresnel * fresnel;
    fresnel *= fresnel2 * fresnel2;
    fresnel *= dGlossiness * dGlossiness;
    dSpecularity = dSpecularity + (1.0 - dSpecularity) * fresnel;

    #ifdef CLEARCOAT
    // ...
    #endif
}
```

All of them use the half vector when calculating fresnel except playcanvas.
The three.js implementation is a little different, and it is migrated from 2013SiggraphPresentationsNotes.

I have the following confusion:
1. Why playcanvas use `V dot N` instead of `V dot H` ?
2. What does `dGlossiness * dGlossiness` do here ? Is it used to replace `f90 - f0` ?

**Comment by mvaligursky** [comment]
@scarletsky - great timing, @raytranuk is just investigating the lighting problems with this specifically ;)

**Comment by raytranuk** [comment]
@scarletsky - you observations were correct - the fresnel implementation in PlayCanvas was not using the half-angle and this did result in non-standard specular lighting results that differed significantly from other implementations. A related PR has now been submitted: https://github.com/playcanvas/engine/pull/3172 - which switches the fresnel calculations to use the half-angle and should bring PlayCanvas more in line with other implementations. The use `dGlossiness` in the fresnel calculation is also non-standard in Cook-Torrance PBR models - but is used a bit like a Geometry term in the Blinn-Phong model that is the default for punctual lights in PlayCanvas.

**Comment by mvaligursky** [comment]
related to https://github.com/playcanvas/engine/issues/3013

**Comment by willeastcott** [comment]
Hey @mvaligursky and @GSterbrant - I'm scanning some older issues to see if any can be closed. What's the current status of this one?
