### ISSUE TITLE
XRFrame : Depth sensing feature is not supported by the session

### ISSUE THREAD

**Issue by jimmiefriberg** [playcanvas/engine#3113]
We've started to receive this bug the last couple of days. First I thought it was project specific but after going back to older projects I still encounter the same issue. I've also tried different engine versions but the error still remains which makes me think it's an issue with Google Chrome rather than PlayCanvas. However, I'm not sure so if anyone knows what's up that would be great. I can't share the projects as they're all private but I can set up a demo on request.

![Screen Shot 2021-04-22 at 9 26 56 am](https://user-images.githubusercontent.com/3803139/115639584-57c65f80-a358-11eb-9e2f-14c3d4618469.png)

Phones that have been tested where the error appears:
Samsung S10, S9, S9+
Google Chrome 90.0.4430.82 

Just before posting this we did test a phone with Chrome 87 and everything worked well. Which suggest that the issue is with the versions of Chrome. I still wanted to post it though as more people might run into the same issue and I could be completely wrong about it being browser related.

**Comment by yaustar** [comment]
Hi, Google released a breaking change to the WebXR API. A fix is currently in a PR https://github.com/playcanvas/engine/pull/2947
