### ISSUE TITLE
Runtime lightmapper fails if UV1s don't exist - should give warning

### ISSUE THREAD

**Issue by wyozi** [playcanvas/engine#3120]
Hey,

### Description

I have a pretty simple scene with a cube created and exported from blender as a .glb. (link here: [ground.glb.zip](https://github.com/playcanvas/engine/files/6370868/ground.glb.zip) as a .zip, because GH doesn't support .glb)

Baking the mesh results in a completely black mesh, and if I disable baking and use dynamic lighting, everything works fine. 

Is baking .glb files even supposed to work or is there something fundamentally wrong with that specific model that means it only works for dynamic lighting? Tried on Safari, Chrome and Firefox on OS X

```ts
// from .glb; solid black
this.ground.addChild(asset.resource.instantiateRenderEntity({
  lightmapped: true
}))
app.lightmapper.bake(null, pc.BAKE_COLOR)

// from a plane; works fine
this.ground.addComponent('render', {
  lightmapped: true,
  type: "plane"
});
app.lightmapper.bake(null, pc.BAKE_COLOR)
```

**Comment by yaustar** [comment]
Using the runtime lightmapper requires a second set of UVs with some extra details here https://developer.playcanvas.com/en/user-manual/graphics/lighting/runtime-lightmaps/#auto-unwrapping-and-uv1-generation

At the moment, the UV1 unwrap in the editor doesn't work with GLBs and therefore, they need to be added to model in the modelling package.

**Comment by wyozi** [comment]
Ah, great. I'll try that, thanks! I tried quite a few search keywords but somehow didn't end up there. Maybe because I'm only using engine

**Comment by wyozi** [comment]
Second UV solved it. Thanks!

To keep this as an issue, maybe there could be a warning in the engine if you're trying to bake lightmaps into models without second UVs? It could save some time from someone else using the engine directly

**Comment by yaustar** [comment]
Yeah that sounds like a good call. I rename the topic.
