### ISSUE TITLE
Add API to be able to transition directly to a state in the Anim Component

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3144]
Similar to the older Animation Component API
```
myAnimStateGraphLayer.transitionTo(someStateName, optionalBlendTime);
```

I can see where this could be handy as a complete reset but I can imagine it be tough to implement if there are other transitions active with conditions that are valid as well 🤔 What should happen in that scenario?

**Comment by mvaligursky** [comment]
I think we discussed this initially, and decided to keep the transition data driven, which means by setting up transition including the blend time and other properties in the Editor / data, vs calling it directly from code. It makes it complicated to understand and debug the project if transitions can be triggered by two different ways, especially in a way that the graph does not allow.

**Comment by yaustar** [comment]
Addressed in https://github.com/playcanvas/engine/pull/3237
