### ISSUE TITLE
[launch.js:10505]: len is not defined

### ISSUE THREAD

**Issue by keslyh** [playcanvas/engine#3150]
### Error 'len is not defined' when moving a entity in editor hierarchy

Stack Trace:
![image](https://user-images.githubusercontent.com/65982751/117395833-71a58d80-ae94-11eb-98cf-c95457e12ff6.png)

In launch.js line 10505:
![image](https://user-images.githubusercontent.com/65982751/117395623-ffcd4400-ae93-11eb-919b-c279056f8571.png)

### Steps to Reproduce

1. Have a project launched in another window/tab.
2. Drag a **entity** in the editor hierarchy to another location.

### Steps to Resolve

In launch.js line 10503:
`let i, len;`

**Comment by slimbuck** [comment]
Thanks for submitting this @keslyh - a fix is in the pipeline!

**Comment by slimbuck** [comment]
This should now be fixed.
