### ISSUE TITLE
Asset file prefix

### ISSUE THREAD

**Issue by demalus** [playcanvas/engine#316]
Would it be possible to add an optional url prefix for assets? Currently, this exists for scripts in framework_application.js:_preloadScripts `scriptUrl = pc.path.join(this._scriptPrefix, scripts[i]);`.  

It would be useful to have another field in the Application options (or maybe reuse scriptPrefix?) for the rest of the assets loaded in config.json (materials, textures, models, etc.). This is useful if the URI does not match the file locations - for example, if your page is served as part of a REST API call, the content is likely to be stored at a different URI. This also allows static assets to be served from S3 or a CDN.

**Comment by daredevildave** [comment]
I think that sounds reasonable. I'd probably add an new option to the AssetRegistry to append a prefix to the asset url.

**Comment by demalus** [comment]
I think that since there's already a structure to the export (files/assets/id), that it makes sense there would only be one location for all the assets.  Splitting up the files directory, in my opinion, is not a likely case because it would bring a whole host of other problems - at that point you'd be better off using the engine directly instead of using an export from PlayCanvas.com
