### ISSUE TITLE
Post process effects and render order issue

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#3168]
We observed in a number of projects that use planar reflections when adding a post process effect (any) the render order breaks leading to artifacts. We observed the same in the Planer Mirror Reflection example. I am not fully sure if it's an engine bug or something in the example implementation, any thoughts are welcome.

Without post process:
![image](https://user-images.githubusercontent.com/29543178/118509514-62de9680-b730-11eb-9d12-a8fc1e064ec8.png)

With post process:
![image](https://user-images.githubusercontent.com/29543178/118509492-5c501f00-b730-11eb-8b25-954fa65b3d00.png)

Steps to reproduce:
1. Fork the Planar Mirror Reflection example.
2. Add any post process effect from the engine repo.

Project url: https://playcanvas.com/editor/scene/1153271

**Comment by mvaligursky** [comment]
The project is using Layer.renderTarget which was deprecated. Ideally it's ported to use Camera.renderTarget.
I don't believe post-processing on render targets set up on layers is supported. It is supported when set up on cameras .. example here: https://github.com/playcanvas/engine/pull/3070

**Comment by mvaligursky** [comment]
At some point it'd be probably good to refactor it, and add it as a script here:
https://github.com/playcanvas/engine/tree/master/scripts/utils called perhaps "planarReflectionRenderer" or similar .. so that it can be shared easier as well.

**Comment by leonidaspir** [comment]
Right, thanks Martin, most likely that's the fix currently for the planar reflections example. I will check if it's easy to update it and share any findings.

**Comment by leonidaspir** [comment]
I can confirm moving the reflections render target from layers to a camera that is rendering before the main one solves the issue.
