### ISSUE TITLE
Compressed SceneItem cannot be reloaded

### ISSUE THREAD

**Issue by marklundin** [playcanvas/engine#3186]
When a SceneItem is loaded using `loadSceneHierachy`  it will mutate the SceneItem and [remove ](https://github.com/playcanvas/engine/blob/137f6cb19fdb01caf2f936029bd76ae2fe0ce2a9/src/resources/parser/scene.js#L47) the `compressedFormat` field. If this scene is subsequently unloaded and then reloaded the `compressedFormat` field does not exist and will throw an error.

Steps

```javascript
loadSceneData('config.json')
const scene = app.scenes.find('sceneName')
app.scenes.loadSceneData(scene)
app.scenes.loadSceneHierarchy(scene)// <-- removes compressedFormat field 

// some point later delete scene

app.scenes.loadSceneHierarchy(scene) // <-- Throws error

```

It makes sense that SceneItems are immutable, but there may be a reason why it is deleted. Either way this throws an error

**Comment by yaustar** [comment]
@zachpeterpaul one for you?
