### ISSUE TITLE
Application.start when called twice will re-initialise systems

### ISSUE THREAD

**Issue by marklundin** [playcanvas/engine#3187]
`application.start` will call initialize on the component system and start a new animation loop even if it has already been called before. This causes multiple render loops and it's not clear this is the intended behaviour. Ideally the 2nd call to `start()` is a noop and the Application maintains reference to whether this has already been called

**Comment by yaustar** [comment]
Just to confirm, this is only in the case when calling application.start twice?

**Comment by marklundin** [comment]
Yep. Granted, it's trivial for a developer to track whether an Application has already started, but it seems this should also be tracked in the Application itself?

**Comment by mvaligursky** [comment]
To me calling the API correctly seems a responsibility of a developer - engine should not need to handle a case user initialises the engine multiple times.

**Comment by marklundin** [comment]
I've run into issues accidentally calling start multiple times but it wasn't clear this was the case. I think if it is the devs responsibility, there should be more feedback that calling it multiple times can cause side effects.
