### ISSUE TITLE
Animation system using curves, blending of multiple animations over time, blend trees and root motion

### ISSUE THREAD

**Issue by whydoidoit** [playcanvas/engine#319]
The current animation system is pretty limited and it's hard to get great character effects due to the limitations around animation blends.

Suggest that the following is needed over time:
- Animation interpolation based on curves
- Ongoing blending of multiple animations at the same time
- Duration management for blending animations with different underlying durations
- Animation masking to allow different animations on different body parts
- Development of a generic "Avatar" body representation to allow animation retargeting
- Root motion and rotation driven by centre mass displacement due to animation
- Animation state machines and blend axes to allow for "Mecanim" like states driven by user input.
- Animation events system to allow: at a moment, between times, before and after functions driven from the animation system.
- IK to enable better foot placement and integrated IK targeting for upper body rotation

**Comment by willeastcott** [comment]
Have you tried updating motion.js yourself?

We've been working on a replacement animation system here:

https://github.com/playcanvas/playcanvas-gltf/blob/master/src/playcanvas-anim.js

It supports animation curves and better animation crossfading. It should evolve into what is outlined in the OP.

**Comment by TheCodeCrafter** [comment]
Ok, I'll check it out. Looks pretty good! Is the animation crossfading planned to be implemented into the actual component ever, or just as a functional scripting component?

**Comment by TheCodeCrafter** [comment]
I know curving is a big deal in PlayCanvas, but I also see many unanswered questions (from last year mostly) about how to mask animations and layer animations, etc. I have also made a post in the forums about this. Maybe if you could help out and explain how to mask/layer animations on a skeleton, on this forum post? I just haven't seen any good explanations for a simple way to do this!

https://forum.playcanvas.com/t/skeleton-blending/8055/2

**Comment by thomasbiang** [comment]
I think blending is supported https://github.com/playcanvas/playcanvas-gltf/blob/4f12805e95ec71b09c1d0cbe7644f47a09d478ba/src/playcanvas-anim.js#L1289
You can blend one animation clip or one curve (DOF). But currently it is not organized as a blend tree. 
It should be easy to add blend mask support.

**Comment by TheCodeCrafter** [comment]
@thomasbiang Thanks! That sounds pretty neat. If you need any help implementing the feature, I'm here. I have some previous experience working with the WhitestormJS folks off yonder, but I still have very little engine Javascript experience, so forgive me for my mistakes or stupidity 🤣 

Of course, once this is integrated into Playcanvas, I can make a nice little tutorial about animation layering so that we can clear that confusion up once and for all.

**Comment by TheCodeCrafter** [comment]
Got it figured out! @yhydra helped me out

**Comment by yhydra** [comment]
https://github.com/yhydra/playcanvas-animator

If anyone else is looking for animation layering, avatar masking

**Comment by thisredone** [comment]
Are you guys still working on this?

**Comment by slimbuck** [comment]
Please note that glb animation support combined with this https://github.com/playcanvas/engine/pull/2007 is addressing many of the features requested here.

**Comment by willeastcott** [comment]
Good point @slimbuck. Although the new `pc.AnimComponent` doesn't include everything requested here, I think we should we should close this issue. A separate issue should be opened for each feature _not_ included in #2007, and we can work through them one by one (e.g. IK, root motion compensation).
