### ISSUE TITLE
Basis Compression: allow user to prioritize VRAM over quality

### ISSUE THREAD

**Issue by Kulodo** [playcanvas/engine#3191]
Currently with Basis the "most desirable gpu texture compression format given the device's capabilities" is defined in the following function.

[https://github.com/playcanvas/engine/blob/master/src/resources/basis.js#L268](https://github.com/playcanvas/engine/blob/master/src/resources/basis.js#L268)

However, there are cases where a developer needs to choose the format that consumes the least VRAM rather than the format with the best quality.  

It would be most flexible if the user could choose "per texture",  via the texture inspector basis settings, whether to prioritize VRAM or quality.

<img width="382" alt="Screenshot 2021-05-30 at 15 27 03" src="https://user-images.githubusercontent.com/74154551/120108887-ff585e00-c15e-11eb-82da-df3372a9b463.png">

Here is the forum thread

[https://forum.playcanvas.com/t/basis-compression-ios-android-issue/20317](https://forum.playcanvas.com/t/basis-compression-ios-android-issue/20317)

**Comment by Maksims** [comment]
I believe this is based on what compressed texture file formats are supported by the end platform and can be transcoded from basis.
PVRTC for example, does support 2-bit and 4-bit per block, few other texture formats do support different block sizes too.

It is worth investigating the list of supported by transcoder formats.
