### ISSUE TITLE
Screen depth artifacts on mobile (iOS / Android)

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#3197]
A simple shader that calculates depth height on a plane, using the screen to world depth difference, produces visible banding on mobile.

Here is on desktop:

![Screenshot 2021-05-26 104527](https://user-images.githubusercontent.com/29543178/119632618-44a02700-be11-11eb-82cd-e8d40083c280.jpg)

Here is on Android 10, Samsung Galaxy S10:

![image](https://user-images.githubusercontent.com/29543178/119632670-5255ac80-be11-11eb-8fad-c5be8300effd.png)

Here is on an 2020 iPad, iOS 14.3:

![image](https://user-images.githubusercontent.com/29543178/119632728-5eda0500-be11-11eb-9fc1-205fe5b5fb90.png)

The shader code is pretty simple:

```
varying vec2 vUv0;
varying vec3 vPositionW;

void main() { 
    
    float waterDepth = getLinearDepth(vPositionW);
    float depth = getLinearScreenDepth();

    float depthDiff = clamp(pow(abs(waterDepth - depth) * 27.5 * 0.002, 0.5), 0.0, 1.0);

    gl_FragColor = vec4( vec3(depthDiff), depthDiff);
}
```
Project sample: https://playcanvas.com/editor/scene/1164740

It seems like a texel size / resolution issue, though we were unable to find the exact fix by overriding the internal screen depth chunk methods.

**Comment by mvaligursky** [comment]
maybe it needs

`#define GL2`

**Comment by leonidaspir** [comment]
> maybe it needs
> 
> `#define GL2`

Added that to the top of the PS shader, but still the result is the same on mobile.

**Comment by mvaligursky** [comment]
how about 
`precision highp float;`
I suspect it might default to lowp if not specified

**Comment by leonidaspir** [comment]
Added it but still the same. We thought it may be some precision issue, we even rendered to a render target on another example and messed with the texture formats to increase precision but still the same issue.

**Comment by mvaligursky** [comment]
I tried the example on Google Pixel 3A, Android 11, and also iPhone XR on 14.5, and cannot see any banding there.

**Comment by leonidaspir** [comment]
It seems to reproduce here on the following devices:

Samsung Galaxy S10, Android 10, Chrome

![image](https://user-images.githubusercontent.com/29543178/124499963-2ee23200-ddbf-11eb-900a-f4cb2f909379.png)


iPad 2020, iOS 14.2, Safari

![image](https://user-images.githubusercontent.com/29543178/124499943-24c03380-ddbf-11eb-9af9-8f63a490c67b.png)

**Comment by leonidaspir** [comment]
So issue seems to persist, tested on the following devices:
- iPhone iOS 14 (WebGL 2.0 enabled)
- iPad 2020, iOS 14 (WebGL 2.0 enabled)
- Samsung Galaxy S10, Android 11

All produce the same result, interestingly when switching to WebGL 1.0 the issue is resolved. Any idea why the same shader produces a different output?

We are about to release an open alpha of our open world game, it would be great if we could solve this. On the same device/OS/browser, WebGL 1.0:

![rn_image_picker_lib_temp_ee532064-3707-4f03-a366-155108ab5dc6](https://user-images.githubusercontent.com/29543178/130324118-62deb35b-24c9-45c7-98a0-ee513d93f777.jpg)

WebGL 2.0:

![rn_image_picker_lib_temp_bf1d57fd-1ed4-4efb-998c-75d473929b94](https://user-images.githubusercontent.com/29543178/130324129-0a28a189-2a7a-40f6-95bb-f0861fb23567.jpg)

**Comment by willeastcott** [comment]
Presuambly there is a bug in the `GL2` code path for `getLinearScreenDepth`:

https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/chunks/screenDepth.frag#L36

**Comment by willeastcott** [comment]
Although then I would expect the bug to happen on desktop too under WebGL 2.

**Comment by leonidaspir** [comment]
This may be related: https://github.com/mrdoob/three.js/pull/18696

**Comment by leonidaspir** [comment]
> Although then I would expect the bug to happen on desktop too under WebGL 2.

Yeah, I thought so. Initially I thought something with the screen size may be the issue but I wasn't able to reproduce the issue on desktop emulating mobile screen sizes ( pixel ration > 1).

**Comment by willeastcott** [comment]
I seem to be able to fix this by overriding the screenDepth.frag chunk and editing:

```
uniform sampler2D uDepthMap;
```

to:

```
uniform highp sampler2D uDepthMap;
```

**Comment by leonidaspir** [comment]
Confirmed, that indeed fixes the issue. Many thanks @willeastcott for the find!

**Comment by leonidaspir** [comment]
For anyone coming across this and until the fix is added to the engine, you can do the following **before** using the `screenDepthPS` shader chunk:

```
// --- fix precision of depth map on mobile
pc.shaderChunks.screenDepthPS = pc.shaderChunks.screenDepthPS.replace('uniform sampler2D uDepthMap', 'uniform highp sampler2D uDepthMap');
```

**Comment by willeastcott** [comment]
The fix for this is now deployed so you can remove the workaround from your application code. 😄
