### ISSUE TITLE
pc.AssetRegistry findAll(name, type) 

### ISSUE THREAD

**Issue by SirFizX** [playcanvas/engine#320]
- suggestion regarding findAll(name, type)
- instead or in addition have findAllContaining( substring , type );
- match all assets of given type with name containing provided substring

**Comment by Maksims** [comment]
We could add `filter` method, where you provide a filter callback, that iterates through each asset and by returning `true` will include it to result list.
You have to understand that iterating through each asset like so is a costly operation, and should be done very few times, probably on loading only and not on every frame.
Something like:

```javascript
var items = app.assets.filter(function(asset) {
    return asset.type === 'material' && asset.name.indexOf('monster') !== -1;
});
```

**Comment by willeastcott** [comment]
What about supporting wildcards in the regular find function?

**Comment by vkalpias** [comment]
We could maybe provide two ways to call the find method. One with a simple string and one with a regex.

**Comment by Maksims** [comment]
Added PR https://github.com/playcanvas/engine/pull/322
