### ISSUE TITLE
changedTouches on TouchEvent is referencing Mozilla Touch event instead of our own

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3222]
https://developer.playcanvas.com/en/api/pc.TouchEvent.html?filter=bound#changedTouches

Should be referencing https://developer.playcanvas.com/en/api/pc.Touch.html not https://developer.mozilla.org/en-US/docs/Web/API/Touch

**Comment by willeastcott** [comment]
Fixed in #3845
