### ISSUE TITLE
Static models with an assigned batch group disappear when reloading the scene

### ISSUE THREAD

**Issue by davidpox** [playcanvas/engine#3229]
### Description

Static models in a scene that have a Batch Group assigned disappear when the same scene is destroyed and reloaded, regardless of whether or not the batcher has ran. 

[Project Link](https://playcanvas.com/project/803952/overview/batch-minimal)
[Forum Post Link](https://forum.playcanvas.com/t/batched-models-disappear-after-reloading-scene/20637)

Upon first load, you'll see a couple of plane entities laid out. The outer circle of planes have no batch group assigned, whereas anything inside the circle have a single batch group assigned with its layer set to World. Once you reload the scene by pressing 'L', you'll notice that all the planes that had a batch group assigned disappear from the scene, and the ones without a batch group remain in place as expected. 

Tested on Windows 10 (2004 - 19041.985) using Google Chrome v91.0.4472.77, and Firefox v89.0, PlayCanvas v1.42.0

### Steps to Reproduce

1. Create a few entities around the scene and set them to be Static
2. Create a new Batch Group and give it the World layer
3. Assign the new batch group to the entities
4. Load the game, see that all entities load fine
5. Use `SceneRegistry.loadSceneHierarchy` to reload the scene and destroy the old hierarchy
6. Observe that the entities with a batch group have disappeared.

### Screenshots

Screenshot 1 - Before reloading the scene
![Iy78cxYn](https://user-images.githubusercontent.com/7888472/121571020-6a851880-ca1a-11eb-820c-dea962fdfe4a.png)

Screenshot 2 - After reloading the scene
![EIodJzAK](https://user-images.githubusercontent.com/7888472/121571051-71ac2680-ca1a-11eb-8397-7f468a32e13f.png)

**Comment by mvaligursky** [comment]
I tried looking into this, but have not found an issue .. it would need more time and deeper investigation, perhaps another time.

As a workaround (not the same behaviour, I understand) would be to remove the previous scene before new one gets loaded.

```
SceneSwitchButton.prototype.loadScene = function() {
    var oldHierarchy = this.app.root.findByName('MyScene');
    var scene = this.app.scenes.find("GameScene");
    oldHierarchy.destroy();
   
    this.app.scenes.loadSceneHierarchy(scene.url, function (err, parent) {
        if (!err) {
        } else {
            console.error(err);
        }
    });  
};

```

**Comment by yaustar** [comment]
A smaller repo of this project as another client ran into this issue: https://playcanvas.com/project/971118/overview/adding-batch-group-entity-at-rt
