### ISSUE TITLE
WebGL failure on Nexus 6, Note 4

### ISSUE THREAD

**Issue by robknopf** [playcanvas/engine#327]
PlayCanvas applications fail to run on Nexus 6 and Note 4, throwing a WebGL error ("hit a snag").  Tested with simple, single object pack as well as Tanx (http://tanx.playcanvas.com).  Tested with both Firefox and Chrome.

**Comment by willeastcott** [comment]
@Maksims @vkalpias @guycalledfrank Can you guys test TANX on your Android devices? Anybody get a WebGL crash?

**Comment by vkalpias** [comment]
Works for me

**Comment by guycalledfrank** [comment]
Works on Samsung Galaxy Tab.

**Comment by Maksims** [comment]
If it is a "hit a snag" it is a browser problem, and is under our control.
Work on my One Plus One too.

**Comment by willeastcott** [comment]
Just tested on a Nexus 4. That's fine too. @robknopf I'm amazed but it could just be that you're very unlucky with the devices you have. I think I have a Note 4 at home. I'll try it on that tonight.

**Comment by robknopf** [comment]
I'm not seeing a problem on my other Android devices, just those two.  I have an S6 I can test later today, but FWIW, the same browsers on the same phone (Note 4) are displaying other WebGL content such as ( http://labs.gooengine.com/pearl-boy ) without an issue. 
Multiple page refreshes will eventually let me into Tanx, but the tanks are not rendering.  My simple test ( http://playcanv.as/p/SnveiZwO ) is also failing.

Anything I can do to help ferret this out?

**Comment by willeastcott** [comment]
What I would recommend, Rob, is submitting this to Chromium. As @Maksims says, this is highly likely to be a browser bug.

https://code.google.com/p/chromium/issues/list

If you fill out an issue there listing a link to the content that causes the problem and the devices/Android version/browser and browser version, then paste the bug link here, and we'll all star it (to stay notified and hopefully bump up the priority at Google).

**Comment by daredevildave** [comment]
Chrome team are aware of the issue:

Note 4: https://code.google.com/p/chromium/issues/detail?id=470894
Nexus 6: https://code.google.com/p/chromium/issues/detail?id=498947

Both are driver bugs which have been fixed, but are slow to be rolled out. 

This Chrome update should fix some issues with Note 4 and S6: https://code.google.com/p/chromium/issues/detail?id=512992

**Comment by Maksims** [comment]
Worked around by 9d8b7a2185b269d33ce27f7115fa9c80e95bd5f8

**Comment by guycalledfrank** [comment]
Wow. How did you find it out?
