### ISSUE TITLE
Engine can't build if downloaded as zip

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#3273]
This didn't use to happen since I've been doing that quite often. Not sure if it's expected now, steps to reproduce:

1. Download the engine zip from the main GitHub page.

2. Extract and open a terminal.

3. Run `npm install`

4. Run `npm run build` and it will fail. Rollup will complain there is no `.git` folder available.

If instead of step 1. you run `git clone` from your terminal and a local Git instance is installed, everything builds as expected.

**Comment by willeastcott** [comment]
Fixed by #3274
