### ISSUE TITLE
`maxPixelRatio` is not respected in screenToWorld, and bugged on iOS initial load

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#328]
iOS initial load with double DPI shows not reflowed canvas, after changing orientation issue goes away.

`screenToWorld` seems not respecting DPI too.

**Comment by guycalledfrank** [comment]
* @param {Number} cw The width of PlayCanvas' canvas element.
         * @param {Number} ch The height of PlayCanvas' canvas element.

Use graphicsDevice.width/height there.

**Comment by Maksims** [comment]
Does mouse coords has to take density of a pixel in account? Because on DPI 2 screens, mouse coord like 10,10 will be 20,20 in canvas pixel space. Should that be handled by engine, or should it be handled by user?

**Comment by scarletsky** [comment]
Any updates about this issue?

**Comment by willeastcott** [comment]
Seems fixed! I just tested this on iPhone X running iOS 11. Works fine with this little script with Device Pixel Ratio enabled and disabled:

var ScreenToWorld = pc.createScript('screenToWorld');

```
// initialize code called once per entity
ScreenToWorld.prototype.initialize = function() {
    this.app.mouse.on('mousemove', function (e) {
        var pos = this.entity.camera.screenToWorld(e.x, e.y, 2);
        this.app.root.findByName('Sphere').setPosition(pos);
    }, this);
    if (this.app.touch) {
        this.app.touch.on('touchmove', function (e) {
            var pos = this.entity.camera.screenToWorld(e.touches[0].x, e.touches[0].y, 2);
            this.app.root.findByName('Sphere').setPosition(pos);
        }, this);
    }
};

```
