### ISSUE TITLE
Better shader compilation error reporting

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#3280]
When a shader fails to compile, a whole shader is printed with errors at the end. Ideally we could only print lines around the error and the error message. Maybe attach complete shader after that as well.

**Comment by LeXXik** [comment]
While you are at it, may I ask, how you guys usually stop the error log spam when there is an error in shader? I usually pause the execution by hitting F8, but tmaybe there is a better way? Like "report once and stop" kind of method?
