### ISSUE TITLE
Clamp shadow map resolution to max supported value

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#329]
Don't allow creating WebGL textures with size higher than supported by implementation, clamp it instead (otherwise users get spammed by console errors).

**Comment by willeastcott** [comment]
I thought that's what this does:

https://github.com/playcanvas/engine/blob/master/src/graphics/graphics_device.js#L742

**Comment by guycalledfrank** [comment]
Right, but we don't use it when creating shadow maps. So mostly it's about shadow maps.

**Comment by willeastcott** [comment]
Ah OK, good point. :)

**Comment by guycalledfrank** [comment]
Fixed in https://github.com/playcanvas/engine/pull/336
