### ISSUE TITLE
The Viewer fails to load glTF model with textures using relative paths

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#3309]
See the details and repro models here:
https://forum.playcanvas.com/t/the-viewer-will-fail-if-the-gltf-model-contains-relative-paths/20976

**Comment by mvaligursky** [comment]
@slimbuck - any idea on this one? glb version loads fine, but gltf with textures does not.

**Comment by cx20** [comment]
> The model's materials still don't look correctly so we probably need to investigate that next.

[PearlGoldOliveCoveredGlassDish.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/PearlGoldOliveCoveredGlassDish/2.0/PearlGoldOliveCoveredGlassDish) uses many [glTF extensions](https://github.com/KhronosGroup/glTF/tree/master/extensions#in-progress-khronos-and-multi-vendor-extensions).

[KHR_materials_ior](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_ior)
[KHR_materials_specular](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_specular)
[KHR_materials_transmission](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_transmission)
[KHR_materials_volume](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_volume)

I hope this will be addressed in the future, but I don't think it is within the scope of this issue.
