### ISSUE TITLE
[Examples Browser]: Video texture doesn't play on Chrome Android

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3311]
http://playcanvas.github.io/#/graphics/video-texture does not play video on Chrome on Android

No errors in console.

**Comment by LeXXik** [comment]
I think there is a typo in adding the video element. That should be a node, rather than string, probably:

![image](https://user-images.githubusercontent.com/5677782/124799870-afd73000-df5d-11eb-9366-3db1dca1db50.png)

**Comment by yaustar** [comment]
How odd that it works on desktop :thi

**Comment by yaustar** [comment]
Had a quick look and it does fix up the DOM but video texture still doesn't play.

The MP4 doesn't show up in the network tab either in devtools which is odd

**Comment by yaustar** [comment]
Ah, it looks like the video is off the end of the page/browser view so the mobile browser doesn't start loading the video
