### ISSUE TITLE
Firefox on Ubuntu v1.44.0 Error - Can't access property COMPRESSED_RGB_ETC1_WEBGL

### ISSUE THREAD

**Issue by Christopher-Hayes** [playcanvas/engine#3316]
### Description

On engine release v1.44.0, I'm getting this error that breaks the scene for me:
![image](https://user-images.githubusercontent.com/6013871/124950754-b3f86180-dfe0-11eb-86e6-bb139768e9c7.png)

This is what the engine source debug is showing:

![image](https://user-images.githubusercontent.com/6013871/124951071-0174ce80-dfe1-11eb-8376-80e0559aa79e.png)

### Platforms Tested

:x: Error happens on Firefox 90 on Ubuntu
:heavy_check_mark: Firefox 90 on Windows 11 has no errors
:heavy_check_mark: Chrome 91 on Ubuntu has no errors
:heavy_check_mark: Chrome 93 on Windows 11 has no errors

**Comment by Christopher-Hayes** [comment]
After further testing, this error seems strangely specific to Firefox on Ubuntu

**Comment by slimbuck** [comment]
Hi @Christopher-Hayes,

Sorry about this. If possible, could you share the error scene so I can take a look?

Thanks!

**Comment by Christopher-Hayes** [comment]
> Hi @Christopher-Hayes,
> 
> Sorry about this. If possible, could you share the error scene so I can take a look?
> 
> Thanks!

Hi @slimbuck, it's a rather complex scene that I can't share publicly. If I give you the project URL and do you have god powers to look at it? I can work on making a reproducible demo project, it'll just take a while to narrow things down.

**Comment by slimbuck** [comment]
If you can give me (slimbuck) read access to the project I can take a look?

**Comment by Christopher-Hayes** [comment]
> If you can give me (slimbuck) read access to the project I can take a look?

I think you should have read access now, I'm not really sure how it works with us just having 1 seat though. The project is titled "Pool Configurator"

**Comment by slimbuck** [comment]
Got it thanks. Which scene causes the issue?

**Comment by Christopher-Hayes** [comment]
"All Environments Dynamic" is the one we use. We actually don't use the other scenes anymore, should really remove those.
