### ISSUE TITLE
Orient images correctly

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#3322]
The PlayCanvas engine and backend considers textures as originating at the bottom left corner. This is in line with OpenGL (and modelling tools like Blender, Maya) which maps the UV coordinate (0, 0) to the bottom left corner of the image (i.e. the first pixel data encountered in texture memory is located at the bottom left of the image).

Inexplicably however WebGL considers the texture origin to be top left instead, see https://www.khronos.org/registry/webgl/specs/1.0/index.html#TEXIMAGE2D_HTML - “The first pixel transferred from the source to the WebGL implementation corresponds to the upper left corner of the source”.

More background on glTF choice of top-left can be found at https://github.com/KhronosGroup/glTF/issues/1021.

We must update the engine to use top-left texture origin in order to be in line with the industry and add better support for shared assets like glTF.

In order to accomplish this, we must make the following changes:
- refrain from flipping images at load time (png, jpg etc)
- refrain from flipping glTF V coordinates at load time (which currently compensates for the flipped images)
- flip PlayCanvas json model texture V coordinates at load time
- generate correctly oriented V coordinates for all dynamically-generated texture coordinates, this includes:
    - built-in shapes (sphere, cylinder, plane etc)
    - 2d elements (image element, text element, sprite normal, 9-sliced, 9-sliced-tiled)
- modify the PlayCanvas backend to stop flipping textures at compress time
    - this will require users to re-compress their project textures once the updated engine is released

**Comment by willeastcott** [comment]
It's worth scanning the WebGPU spec to see how it treats textures. Decisions we take now maybe be relevant to our future WebGPU support.
