### ISSUE TITLE
Animation events

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#334]
Would be good to fire events when animations start, end, etc.

**Comment by vkalpias** [comment]
+1

**Comment by MONKATRON** [comment]
+1

**Comment by milg15** [comment]
+1

**Comment by mvaligursky** [comment]
at some point I'd like to see events on a time specified by the user. For example when the shooting animation actually should release a projectile, an event should be fired so that the user can shoot a projectile.

**Comment by yaustar** [comment]
> at some point I'd like to see events on a time specified by the user. For example when the shooting animation actually should release a projectile, an event should be fired so that the user can shoot a projectile.

I'm thinking this would be set on the anim component rather than state graph as each animation can be different

**Comment by mvaligursky** [comment]
usually those events would be part of the animation clip properties .. so if you use the animation on any graph, it triggers those events. It's like an extra track .. with key and a name, that's associated with the animation.

**Comment by ellthompson** [comment]
In an engine only world I wonder whether we should also be able to pass this event data as an optional extra to [pc.AnimComponent#assignAnimation](https://developer.playcanvas.com/en/api/pc.AnimComponent.html#assignAnimation). Allowing users to attach event data to glb loaded animations. We should also allow users to define them in their anim clip's JSON data.

**Comment by mvaligursky** [comment]
It would say the events are something a user should be able to maybe attach to the AnimTrack. So when they attach anim track to anim component, those events would just trigger.
