### ISSUE TITLE
Anim component using vec2.data when blending

### ISSUE THREAD

**Issue by keslyh** [playcanvas/engine#3369]
I have a minor issue. While blending with 2d cartesian in the new Anim Component, I am getting warnings for engine code calling vec2.data.

**Stack Trace:**
![image](https://user-images.githubusercontent.com/65982751/127308255-6b28dcef-db2d-4f08-8b3a-ac8b3a2f2225.png)

**Engine code in AnimBlendTreeCartesian2D:**
![image](https://user-images.githubusercontent.com/65982751/127308488-aebd707a-51bd-416e-9304-9cac680eb86e.png)

### Steps to Reproduce

1. Create Anim Component and create a ANIM_BLEND_2D_CARTESIAN type anim graph.
2. Blend weight.

**Comment by mvaligursky** [comment]
This has been fixed, closing.
