### ISSUE TITLE
static geometry batching

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#338]
http://answers.playcanvas.com/questions/1738/lowering-draw-calls

We can add static batching (just append many meshes into one on load) and dynamic batching (use array of matrices and per-vertex IDs to transform many objects inside single draw call)

**Comment by yard** [comment]
Wouldn't it make more sense to actually combine meshes on CPU (baking transforms) and submit to resulting mesh to GPU instead? This should perform better for hundreds of meshes - consider a sprite-heavy game where a lot of quads are rendered, for instance.

**Comment by Maksims** [comment]
@yard this options would be fully static, and wouldn't allow further manipulations of entities within single geometry.

Perhaps both sounds like different options.
Complicated bit is UVs and materials.

**Comment by Maksims** [comment]
And on webgl2 using Transform Feedback operations on transforming VB's and merging into single buffer can be GPU accelerated.

You right on complexity with shader batching approach.

Just on your opinion, do you think that shall be runtime feature and/or tools feature?

**Comment by guycalledfrank** [comment]
Dynamic CPU mesh combining can be okay-ish for very simple lowpoly geometry. For heavy geometry it would introduce serious performance drops. For static geometry it's great.
For dynamic stuff a good solution (suggested in the first comment) is to combine once and bake mesh ID per-vertex, then we can just update a uniform buffer/vertex texture with transforms.
Another solution is instancing, but it only helps identical meshes. We have some instancing code in the engine, but it often doesn't work as fast as desired in dynamic scenarios...
Materials: I'd simply batch per-material (not combining multiple materials in a single batch), would be good enough already. In WebGL2 it can be possible to combine multiple similar materials in one batch by using texture arrays.
Another non-trivial thing is batching vs culling: on one hand it's good to combine as much as possible, on the other hand, if you have a huge mesh, containing polys from different parts of the world, it will be never culled, because the bounding box is huge. Not sure if Unity does anything about it - their static batching produced similar meshes to me. I think some poly locality should be taken into account.
I'm not sure that transform feedback can help us here in any way.

**Comment by yard** [comment]
I think transform feedbacks can be utilized to offload actual mesh transformation onto GPU - however for the case of highly dynamic meshes the overhead of interacting with GPU might eliminate the win from math. 

Re comp cost for big meshes - well, I guess we have an upper bound of 65k vertices per mesh anyway, so it's quite easy to test. Plus, we can update only parts of supermesh (affected by transform change) which can save a lot. 

The part re huge aabb ia valid, but is easily solvable by tags or smth - we can always give a control on which meshes to batch to together in some flexible way. 

As for realtime vs static impl - well, being runtime is the whole point of dynamic batching, and tools can utilize it for precomputed approach.

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/pull/1041
