### ISSUE TITLE
PlayCanvas application can not be created in browserless environment.

### ISSUE THREAD

**Issue by OlegGedzjuns** [playcanvas/engine#3388]
### Description

In PR https://github.com/playcanvas/engine/pull/3381 browserless feature was merged, but it is impossible to create pc.Application without canvas element

Node environment

### Steps to Reproduce

1. Build PlayCanvas engine from master
2. Add PlayCanvas library to your node project
3. Try to create a PlayCanvas application
4. You will be unable to create an application without the canvas element, and it is impossible to create Element in Node because document does not exist.

**Comment by slimbuck** [comment]
Hi @OlegGedzjuns,

Yes correct. Internally we have created a `HeadlessCanvas` stub object in order for engine to render in browserless environment. It was also necessary to patch the `ImgParser`, since the `Img` element is only available in browser.

We will likely put this code in a browserless example repo and release that at some point.

Thanks!

**Comment by willeastcott** [comment]
I'd recommend putting it in this repo.

**Comment by Maksims** [comment]
It would be great to be able to run engine on server without renderer, with common use case: multiplayer context.

**Comment by yaustar** [comment]
Would using `autoRender = false` handle that or is there still stuff going in the background?

**Comment by OlegGedzjuns** [comment]
I see that browserless feature was released, any updates on my issue?

**Comment by OlegGedzjuns** [comment]
During application destroy exception is thrown

document is not defined at destroy
https://github.com/playcanvas/engine/blob/4e8adc8b7cc85c6763d7d18eb9b37f3c6e4a12c6/src/framework/application.js#L1975

**Comment by mvaligursky** [comment]
this has been now fixed, pending engine release

**Comment by jscraftsman** [comment]
Is there an example code to run a browserless environment?

**Comment by OlegGedzjuns** [comment]
> Is there an example code to run a browserless environment?

You can find example here: https://github.com/meta-space-org/playnetwork
