### ISSUE TITLE
Duplicating a template asset does not produce expected result

### ISSUE THREAD

**Issue by jlanis** [playcanvas/engine#3389]
### Steps to Reproduce

1. Create a template 
2. Duplicate the template asset by copy & pasting within the Assets window, and change the name
3. In a script, instantiate both templates and notice the name is the same for both, and attributes are getting overwritten (see sample project)

Sample project: https://playcanvas.com/project/821309/overview/templatebug 

**_In the sample project, replacing Box02 with Box_NotDuplicated in the spawner object results in the correct behavior, even though Box02 and Box_NotDuplicated are identical._**

In addition, when renaming _any_ template asset, objects instantiated in script using that template asset still have the original (old) template name.

**Comment by yaustar** [comment]
Just want to check a few details:

> Duplicate the template asset by copy & pasting within the Assets window, and change the name

Are you changing the name of the asset or the name of the entities in the template?

> and attributes are getting overwritten

What do you mean by this?

**Comment by jlanis** [comment]
@yaustar To answer your first question, I am changing the name of the asset itself. 

To answer your second question, I've updated the sample project to demonstrate more clearly. Take a look at these logs. In both cases, the instances were exactly the same. The only difference between the 1st and 2nd screenshot, is that in the 2nd one I did not instantiate box2. Notice how simply not instantiating this template resulted in box3 having different halfExtents.

<img width="283" alt="Screen Shot 2021-08-12 at 8 27 32 AM" src="https://user-images.githubusercontent.com/2446901/129224875-86cafb17-cc64-4597-9b78-7feb7723fb1e.png">
<img width="287" alt="Screen Shot 2021-08-12 at 8 29 02 AM" src="https://user-images.githubusercontent.com/2446901/129224900-e6a02fd2-e753-43f1-a7f0-3168c6616a24.png">

**Comment by zachpeterpaul** [comment]
Our current copy paste is probably too generic for templates, but this should work correctly in Vaios’ new api. He says he’ll check to make sure

**Comment by zachpeterpaul** [comment]
Regarding names: the template asset name can be different than the name of its root entity. Since we are (intentionally) not treating a change of the name of an instance root as an override (along with its position, for instance), there's currently no way to change the name of the root entity of a template asset, once that asset has been created. This may change when we implement a "template editor", ie direct editing of template assets.

**Comment by jlanis** [comment]
> Regarding names: the template asset name can be different than the name of its root entity. Since we are (intentionally) not treating a change of the name of an instance root as an override (along with its position, for instance), there's currently no way to change the name of the root entity of a template asset, once that asset has been created. This may change when we implement a "template editor", ie direct editing of template assets.

Just to clarify: I am not changing the name of the instance of the template, I am changing the name of the template _before_ instantiating it. Also, the fact that you can change some properties of the transform (such as scale) and have it apply to the template, but not other properties (such as position or rotation) is seems inconsistent/arbitrary.

**Comment by zachpeterpaul** [comment]
Right, you are changing the name of the asset, which does not affect the name of its root entity. Position etc of the root of the instance are not treated as overrides because in most cases users don't intend to apply them to the asset. They will become editable on the asset when we implement a template editor.

**Comment by yaustar** [comment]
This has now been fixed as part of editor release 1.19.5 (https://github.com/playcanvas/editor/releases/tag/v1.19.5)

**Comment by jlanis** [comment]
@yaustar I still can't duplicate templates directly like other assets using cmd+d

**Comment by yaustar** [comment]
@vkalpias Did Cmd D work for all assets? I think it's only for a few right?

@jlanis Does Cmd C + Cmd V work?

**Comment by jlanis** [comment]
@yaustar Yes, Cmd C + Cmd V works. Which would lead me to presume that Cmd D should do exactly the same thing?

**Comment by yaustar** [comment]
Errr, conceptually yes but I think the code paths are different as duplicate was a separate feature that existed long before copy and paste 😅
