### ISSUE TITLE
Bug cloning or setting materials for an entity that has skinning and was created with instantiateRenderEntity()

### ISSUE THREAD

**Issue by luizcarlosfx** [playcanvas/engine#3393]
Hi, I'm loading a glb file at runtime, but when I clone my entity to have more than one copy the second will be completelly bugged. The same problem happens when I create a new material with my custom shader and set it to a meshInstance. Actually the bug is all about losing the skinning in both of these situations. Unfortunately I can't post a screenshot because I can't share the model.

To reproduce:
1 - load a glb file 
2 - clone it and add to the scene
3 - the meshes won't be affected by the bones anymore

With materials:
1 - load the glb file
2 - iterate it's mesh instances setting a newly created material with a custom shader
3 - the meshes won't be affected by the bones anymore

**Comment by mvaligursky** [comment]
I think @ellthompson was looking at this issue before. I think perhaps the issue was that the rootBone this points to an entity of the hierarchy does not get clone properly to point to a matching bone in the cloned hierarchy. I think a workaround was to set the rootBone manually after cloning. Give this a go perhaps. Specifically:
- both render and anim component in your hierarchy have rootBone property - please make sure it points to the cloned hierarchy.

Alternatively, don't clone the hierarchy created using instantiateRenderEntity, but call instantiateRenderEntity again to get another copy.

**Comment by mvaligursky** [comment]
> 2 - iterate it's mesh instances setting a newly created material with a custom shader

What custom shader are you setting here? Is it custom vertex / fragment shader, or a shader with some chunks overwritten? Either way, the shader needs to support skinning - which means it needs to accept bones as either texture or vertex uniforms, and apply them to the position.

**Comment by luizcarlosfx** [comment]
To make this clear, I've fixed both issues. I've added the skinning code to my custom vertex/fragment shader and when duplicating the object I've generated the skin again like this.

`XrsResourceLoader.prototype._fixGuidsAndSkinning = function(prefabInstanceRoot, instanceNode, prefabNode)
{
    instanceNode.xrProjGuid = prefabNode.xrProjGuid;

    if(prefabNode.render !== undefined)
    {
        var prefabMeshes = prefabNode.render.meshInstances;
        var entityMeshes = instanceNode.render.meshInstances;

        for(var i = 0; i< prefabMeshes.length; i++)
        {
            var refSkin = prefabMeshes[i].skinInstance;
            if(refSkin !== null)
            {
                var rootBonePath= refSkin.rootBone.path;
                var rootBone = prefabInstanceRoot.findByPath(rootBonePath);
                var entitySkin = new pc.SkinInstance(entityMeshes[i].mesh.skin);

				entitySkin.resolve(rootBone, instanceNode);
                entityMeshes[i].skinInstance = entitySkin;
            }
        }
    }

    var children = instanceNode.children;
    var refChildren = prefabNode.children;

    for(var i = 0; i < children.length; i++)
    {
        this._fixGuidsAndSkinning(prefabInstanceRoot, children[i], refChildren[i]);
    }
};`

**Comment by mvaligursky** [comment]
There still is an issue here we need to fix, so let's leave it opened.

Have you tried just calling instantiateRenderEntity to avoid all that SkinInstance recreation? That's probably a cleaner solution using public API.

**Comment by luizcarlosfx** [comment]
> There still is an issue here we need to fix, so let's leave it opened.
> 
> Have you tried just calling instantiateRenderEntity to avoid all that SkinInstance recreation? That's probably a cleaner solution using public API.

The original model is instantiated with instantiateRenderEntity then I add colliders and other components before start duplicating. It would be kind of painfull to reconfigure again and again with each instance.
