### ISSUE TITLE
Ensure all components clone the 'enabled' property

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#3413]
For some context:
https://github.com/playcanvas/engine/pull/3408#discussion_r690714489

We need to make sure all components are consistent and clone the enabled property

**Comment by mvaligursky** [comment]
related / duplicate https://github.com/playcanvas/engine/issues/3888

**Comment by willeastcott** [comment]
This issue _must_ be fixed with the support of unit tests. If a PR to fix this does not have unit tests, it won't get approved. 😄
