### ISSUE TITLE
Particles renders incorrect on Samsung M31

### ISSUE THREAD

**Issue by Sarletor** [playcanvas/engine#3415]
### Description

Particles renders incorrect on:
**Samsung M31
Android 10.0
CPU - Samsung Exynos 9611** 

Should be this: 
![image](https://user-images.githubusercontent.com/37019196/129930315-8d76cb3d-d4c0-4be0-acbb-ebf122de1c1b.png)
On Samsung M31:
![image](https://user-images.githubusercontent.com/37019196/129930428-c1c14782-e272-43b0-b73f-55e94eecc02b.png)
![image](https://user-images.githubusercontent.com/37019196/129930516-0dca55b2-402a-4dc2-89f5-142a75a1e35f.png)

Project: https://playcanvas.com/editor/project/823129

**Comment by mvaligursky** [comment]
Does it support WebGL2?

**Comment by Sarletor** [comment]
Yes

**Comment by Sarletor** [comment]
![image](https://user-images.githubusercontent.com/37019196/130095731-ce087c19-7b16-4ba4-b974-9b456c701179.png)

**Comment by yaustar** [comment]
I've been to the office and unfortunately all the Samsung devices that we have are Snapdragon CPUs and don't showcase the issue :( (S10, S10+ and S7)

**Comment by dexterdeluxe88** [comment]
> I've been to the office and unfortunately all the Samsung devices that we have are Snapdragon CPUs and don't showcase the issue :( (S10, S10+ and S7)

@yaustar thanks for checking at the office. What's your proposed solution for the given problem then? Maybe I can send you a device - its overseas, but possible.

**Comment by yaustar** [comment]
@dexterdeluxe88 Trying to see if our remote device lab can source a device despite being in the US. I'm also going to have a look if I can find an exact model number and source one in the UK

**Comment by yaustar** [comment]
Just to get an idea of urgency, is this a blocking issue?

**Comment by yaustar** [comment]
Testing project: https://playcanv.as/e/p/RWgZ7YlT/ on a range of Exynos devices I've found

Not reproducible on:
SM-A730F - Exynos 7885 (Android 7.1.1)
SM-G935F - Exynos 8890 (Android 7)
SM-J260M - Exynos 7570
SM-A520W - Exynos 7880
GT-I9500 - Exynos 5410

**Comment by yaustar** [comment]
The S10 has a Exynos 9820 and the M31 has a Exynos 9611 so maybe this is super specific to the 9 series CPU?

**Comment by yaustar** [comment]
Not reproducible on:
Galaxy S9 with Exynos 9810

**Comment by leonidaspir** [comment]
I can reproduce the issue on this project, as well, on Samsung Galaxy S10 with Exynos 9820, running on WebGL2.

Switching to WebGL1 resolves the issue.

**Comment by yaustar** [comment]
Reproduced on Samsung Galaxy A51 SM-A515F. Trying to get hold of one now

**Comment by yaustar** [comment]
Device has been add to device lab: https://deviceremote.sc-corp.net/#!/devices 

As Samsung SM-A515F 

Use the following guide to remote debug: https://docs.google.com/document/d/1yinoGlv1Qi5IwmsC91RqEl3Jyhc3f5VAoZpLQIv76yk/edit#heading=h.bj1ncrj0ki7r

Or use ngrok to use a locally hosted project. https://ngrok.com/

**Comment by yaustar** [comment]
We have manage to get hold of one and connected to a remote device lab that we can reproduce the issue on

**Comment by yaustar** [comment]
As we think this is a hardware driver issue, we've created a workaround that forces using the CPU on ARM based Samsung devices: https://github.com/playcanvas/engine/pull/4147

**Comment by yaustar** [comment]
Closing this as this is no longer reproducible. See PR https://github.com/playcanvas/engine/pull/5255/
