### ISSUE TITLE
Instantiating a template with an anim component that has Root Bone set doesn't play animations  

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3426]
Project: https://playcanvas.com/editor/scene/1218229
Forum thread: https://forum.playcanvas.com/t/solved-animcomponent-not-work-with-templates/21578

Press space to instantiate a new instance of a template.

It looks like the root bone reference in the new instance is referencing a non existing entity (getByGuid with the referenced GUID returns null).

I'm not sure if this is an Anim Component issue or a Template one.

**Comment by mvaligursky** [comment]
we have the same issue with the render component's rootBone. This is not template related, but component clone issue - even cloning the entity with those components has this issue.

**Comment by mvaligursky** [comment]
another instance of this bug https://github.com/playcanvas/engine/issues/3393
