### ISSUE TITLE
Should we add a warning for positional audio usage for iOS?

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3435]
Due to this issue on Webkit, positional audio usage on iOS causes the sound to be corrupt after a few minutes of play.

https://github.com/playcanvas/engine/issues/2866

As it's an issue that affects every project on Webkit that uses positional, it's been suggested that we should add a warning 'somewhere' to advise users.

Suggestions have been:

- Directly in the Editor inspector
- A warning at the engine level
- In the user manual so it's easily searchable

A couple of things to consider. 
- It's not easy to find all entities that have a specific component (yet) so having to go back retroactively and find all the entities can be time consuming.
- The default setting for adding a sound component is to be positional (maybe this should be changed?)
- Is it a good UX experience to encounter the issue after making the project with positional audio only to run into the issue, find it in the manual and go back to retroactively fix it?

**Comment by leonidaspir** [comment]
We are getting audio glitches with **positional** sounds, not only on iOS and not after some time but directly as soon as the app starts, on Chrome (92.0.4515.159)/Windows.

Do you think it's related?

https://user-images.githubusercontent.com/29543178/132131604-f6dd9004-ac4d-4238-81c1-0788f34481f3.mp4

**Comment by leonidaspir** [comment]
Issue persists when updating to Chrome latest version: 93.0.4577.63

We've tried a random WebGL example that uses spatial audio, no glitches there:
https://threejs.org/examples/#webaudio_orientation

In our PlayCanvas project we've tried both with compressed (mp3) and uncompressed (wav) audio files, it didn't make any difference.

**Comment by yaustar** [comment]
What kind of glitches am I listening out for? Static?

**Comment by leonidaspir** [comment]
Yes, static from time to time. Still researching if it's specific to this machine or not, though on the Three.js example always works fine.

**Comment by LeXXik** [comment]
To add here - I tried various audio formats/codecs and also recorded audio at different bitrates - none helped, so it must be something else. A quick look on the three sources, they use a different panning model - [HRTF](https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/panningModel):
https://github.com/mrdoob/three.js/blob/342946c8392639028da439b6dc0597e58209c696/src/audio/PositionalAudio.js#L17

And PC is not setting a panning model, which defaults it to `equalpower` setting (less quality, higher efficiency). Perhaps this could be tried out.

**Comment by LeXXik** [comment]
I tested the `HRTF` mode and it didn't help. The sound changed, but the static is still there.

https://user-images.githubusercontent.com/5677782/132255335-8eb996e6-18c2-4698-ab51-77721b148549.mp4

**Comment by LeXXik** [comment]
There is a Chrome bug. Firefox affected too:

https://bugs.chromium.org/p/chromium/issues/detail?id=1242647

**Comment by vkalpias** [comment]
> Issue persists when updating to Chrome latest version: 93.0.4577.63
> 
> We've tried a random WebGL example that uses spatial audio, no glitches there:
> https://threejs.org/examples/#webaudio_orientation
> 
> In our PlayCanvas project we've tried both with compressed (mp3) and uncompressed (wav) audio files, it didn't make any difference.

I tried downloading the Threejs example and changed the sound to the engine sound that we have in our example. If I move closer to the audiosource I can hear crackling there too... And when I tried the original sound from threejs's example in PlayCanvas I didn't notice crackling.

**Comment by yaustar** [comment]
I found a related issue in Howler.js which points to different sample rates being used the potentially cause of the issue https://github.com/goldfire/howler.js/issues/1141#issuecomment-803593982
