### ISSUE TITLE
Orbit Camera target error

### ISSUE THREAD

**Issue by akaadream** [playcanvas/engine#3448]
There an issue on the orbit camera script i just discovered while i was trying to fix a camera position error.

### Description

When you give to the script a target to look at, if the model you gave is a template with only renders, it will not work because in the orbit camera script, the target system require the mesh instances of the model to work. So, to fix my problem, i had to import a model with a mesh, make it transparent and use it as the target. Not so clean.

The following screens shows the configuration i needed to make it work.

![image](https://user-images.githubusercontent.com/18325858/131851433-c7599471-6b88-4066-8e59-e72b1b4c74ae.png)
![image](https://user-images.githubusercontent.com/18325858/131851482-63cc6ea0-4ef2-4f1c-8bb2-5c1a326f4d6a.png)

**Comment by yaustar** [comment]
Are you using the engine's orbit camera script or the one from the model viewer template on PlayCanvas.com

If the latter, I've updated the project sample below to handle both model and render components.

https://developer.playcanvas.com/en/tutorials/orbit-camera/

**Comment by akaadream** [comment]
I used the script from the link you gave.

**Comment by yaustar** [comment]
That project has now been updated so you can grab the latest code to handle render components.

**Comment by akaadream** [comment]
I take the latest code to try but it does not correct the problem.
The camera is supposed to be focused on the car you can see on the first screenshot.
But actually, when I run the projet, the camera is looking the ground like the second screenshot.

![image](https://user-images.githubusercontent.com/18325858/131870064-50d7939d-dfc9-4c73-8cf1-27eed029280d.png)
![image](https://user-images.githubusercontent.com/18325858/131870222-4fc1422b-4a70-48ab-9e96-4a1025dd48fe.png)

**Comment by yaustar** [comment]
Can you create a separate project with just the car asset and the orbit camera script for me to look at please?

**Comment by akaadream** [comment]
Here is the link of the separate project : https://playcanvas.com/editor/scene/1223745

**Comment by yaustar** [comment]
Looking at the project, the container and render assets are not preloaded so they aren't loaded (and there not rendered) when the camera initialises and tries to focus on the entity on the first frame of the app.

You will need to have the camera focus on the entity (there's a function on the orbit camera called `focus`) after all the assets are all loaded.

Or use an entity with a disabled render component and box type to focus on instead, eg https://playcanvas.com/editor/scene/1223777

**Comment by akaadream** [comment]
Oh ok i see, thanks for your response !
