### ISSUE TITLE
the cubemap parameters of material are missing

### ISSUE THREAD

**Issue by Casval111** [playcanvas/engine#3452]
the cubemap parameters of material (texture_prefilteredCubeMap128, texture_prefilteredCubeMap64, ... texture_prefilteredCubeMap4) are missing

1. Because I call the material.update function in the script update

2. pc.Material.prototype.update will set dirty flag of material to true.

3. if material.dirty is true, then pc.StandardMaterial.prototype.updateUniforms will be called and clears material.parameters first.

4. Then calling pc.StandardMaterial.prototype.updateLightingUniforms is required to reset the parameters of the cube map.

5. However, updateLightingUniforms is only called by pc.StandardMaterial.prototype.updateshader, 
   but the shader is not updated because it is determined that the shader of the material has not been changed. 
   pc.StandardMaterial.prototype.updateShader is not called, and the parameters of the cubemap are not set, they are all undefined.

**Comment by slimbuck** [comment]
Hi @Casval111, this is some great detective work! :)

Are you setting the cubemap on the material itself or on the scene?

**Comment by Casval111** [comment]
> Hi @Casval111, this is some great detective work! :)
> 
> Are you setting the cubemap on the material itself or on the scene?

the cubemap is set on the material itself in the editor. I don't set the cubemap in script, I change other parameters.

**Comment by slimbuck** [comment]
Could you possibly share a repro project with me so I can take a look?

**Comment by Casval111** [comment]
> Could you possibly share a repro project with me so I can take a look?

https://playcanvas.com/project/827498/overview/cubemap-test

**Comment by slimbuck** [comment]
> > Could you possibly share a repro project with me so I can take a look?
> 
> https://playcanvas.com/project/827498/overview/cubemap-test

Awesome, thanks! I've submitted #3455 to address this.
