### ISSUE TITLE
[feature request] Built-in way to encapsulate functionality

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/engine#3459]
I am not sure if this is already available or not, but I am looking for a way to create sub programs within studio, that I can later instantiate at real time, or drag to the hierarchy. 

Kindly take a look at the following links, in order:

1. [https://docs.zap.works/studio/subsymbols/introduction/subsymbol-overview/](https://docs.zap.works/studio/subsymbols/introduction/subsymbol-overview/)
2. [https://docs.zap.works/studio/subsymbols/blank-symbol/](https://docs.zap.works/studio/subsymbols/blank-symbol/)

Having something like this is great for encapsulation and separation of concerns and functionality. Maybe something similar is already available?

**Comment by yaustar** [comment]
The closest you have to this is Templates. You can copy and paste assets (including Templates) from one project to another.

**Comment by marcusx2** [comment]
Ah, I see. Very similar to Unity's prefab system. What I'm suggesting is better, but the prefab system is almost as good to be honest.

**Comment by yaustar** [comment]
Closing this unless there is something specific that is missing or that you need that Templates can't provide
