### ISSUE TITLE
Internal 'blendWeight' exception occurs under certain conditions when changing a model's mesh through code.

### ISSUE THREAD

**Issue by h0lmiew** [playcanvas/engine#3467]
### Description

When changing the mesh of a disabled model, and subsequently playing an animation with blend on it, PlayCanvas engine will throw an exception every frame:

```
playcanvas-stable.dbg.js:45499 Uncaught TypeError: Cannot set properties of undefined (setting 'blendWeight')
    at AnimationComponentSystem.onUpdate (playcanvas-stable.dbg.js:45499)
    at Function._helper (playcanvas-stable.dbg.js:43440)
    at Function.update (playcanvas-stable.dbg.js:43455)
    at Application.update (playcanvas-stable.dbg.js:70607)
    at playcanvas-stable.dbg.js:71315
```

### Steps to Reproduce

1. Open the test project: https://playcanvas.com/editor/scene/1187304 
2. Enter play mode
3. Press D to disable the model entity
4. Press 2 to switch from Fox model to Bull

This will immediately cause the exception to occur. This is because the following happens in code:
1. Pressing D disables the model entity
2. Pressing 2 will cause a switch of the mesh on the model from Fox to Bull,
3. Then it will reenable the entity of the model
4. Then it will play an animation with blend value on it

This specific combination causes the exception. 
- If the model was never disabled, there is no problem when switching mesh and playing new animation (E.g. try pressing 1 and 2 repeatedly after opening play mode).
- Disabling prior to switch and reenabling alone will not cause any exception either, it must be in conjunction with playing an animation with blending - if it has 0 value for blending, no exception is thrown.
- If the enabling of the entity happens before the mesh is changed, no exception is thrown either (E.g. if line 66 in animChanger.js is moved to line 55).

See code in animChanger.js, and browser logs in playmode for more explanation.

### Expected Behavior
No internal animation system error is thrown regardless of order of disabling/switching mesh/ anim blending value.

**Comment by yaustar** [comment]
I don't think that's feasible as it's an older game where replacing the component is a significant chunk of work?

**Comment by h0lmiew** [comment]
We worked around it by changing the execution order, just wanted to let you guys know the bug exists :)

**Comment by yaustar** [comment]
Ah, cool so you aren't blocked :) 

Thanks!
