### ISSUE TITLE
GL Null when Destroying texture

### ISSUE THREAD

**Issue by lukasharing** [playcanvas/engine#3483]
This line makes gl = null
https://github.com/playcanvas/engine/blob/df4bb2aae6ff70f37feb9f89f37e85c3d61b90fc/src/framework/application.js#L2088

This destroy every texture in the cache, calling `destroyTexture`, that uses gl and thus breaks
https://github.com/playcanvas/engine/blob/df4bb2aae6ff70f37feb9f89f37e85c3d61b90fc/src/framework/application.js#L2091

calling:
`
app.destroy()
`

**Comment by lukasharing** [comment]
The solution is simply swapping the destroy function:

``` 
this.renderer.destroy();
this.renderer = null;

this.graphicsDevice.destroy();
this.graphicsDevice = null;
```

**Comment by mvaligursky** [comment]
Thanks for the report @lukasharing - the fix is now merged in and will be released with the next engine release.
