### ISSUE TITLE
Physics is working incorrectly on low fps

### ISSUE THREAD

**Issue by OlegGedzjuns** [playcanvas/engine#3486]
### Description

All physics start to work faster when fps drops

* URL to a simple, reproducible test case that illustrates the problem clearly
https://playcanvas.com/project/829603/overview/test

Start moving, press T to toggle fps reduce, you will start moving faster on low fps.

**Comment by yaustar** [comment]
This might be due because the damping in the project is applied per frame via script and therefore it's not slowing down during the physics update.

Using the linear damping in the rigid body component gives the correct behaviour: https://playcanvas.com/project/831657/overview/physics-test-low-fps

**Comment by yaustar** [comment]
Closing as it's not an engine issue but specific to a project.
