### ISSUE TITLE
playcanvas.github.io doesn't run on iOS 8 (iPhone 6) due to use of ES6

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3488]
Example error: http://playcanvas.github.io/#/graphics/hardware-instancing
![image](https://user-images.githubusercontent.com/16639049/133636001-0f42c713-fa2d-46b3-a79d-8139753f798d.png)

**Comment by willeastcott** [comment]
I suspect this is related to the use of the spread operator in object literals:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#browser_compatibility

**Comment by mvaligursky** [comment]
at the moment engine itself does not support iOS 8 - see https://github.com/playcanvas/engine/issues/3658

**Comment by willeastcott** [comment]
Even iPhone 4S supported iOS 9.3.6. iOS 8 itself is now 10 years old. Closing...
