### ISSUE TITLE
basis.KTX2File is not a constructor

### ISSUE THREAD

**Issue by wei292224644** [playcanvas/engine#3490]
https://github.com/playcanvas/engine/blob/1786fdb3f30b839bef41ff5d2e57cca056714952/src/resources/basis-worker.js#L162

I can not found KTX2File constructor with basis.

**Comment by yaustar** [comment]
Hi @wei292224644 can you provide a code sample of what you are trying to do that we can use to reproduce the error that you are getting please?

**Comment by slimbuck** [comment]
Hi @wei292224644,

You are likely using an older version of the basis runtime library which doesn't include KTX2 support.

Please make sure you update to the latest version of the library, which is available [here](https://github.com/playcanvas/engine/tree/master/examples/src/lib/basis).

**Comment by mvaligursky** [comment]
Could we perhaps add a check just before we call the function to detect the case and print some handy error message?
