### ISSUE TITLE
PostEffect with needsDepthBuffer = true - is leaking VRAM on device resize.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#3492]
When a canvas is resized, if post effect with `needsDepthBuffer = true` is used, it is leaking VRAM (not releasing previous depth buffers).

### Steps to Reproduce

Example is Model Viewer project, with SSAO post effect from [here](https://github.com/playcanvas/engine/blob/master/scripts/posteffects/posteffect-ssao.js).

https://playcanvas.com/project/831974/overview/needsdepthbuffer-vram-leak

1. Enable profiler for Launcher
2. Launch provided project
3. Resize window

### Issue:

Check `Texture Other` under `VRAM` panel, memory usage is constantly growing on each resize.

Disabling `needsDepthBuffer` in `ssao.js` eliviates an issue, but obviously, effect is not working then.

**Comment by mvaligursky** [comment]
Thanks for the report @Maksims , got it sorted out. Out in the next engine release.
