### ISSUE TITLE
Variance Shadow Map iPad 2 Air crashes APP

### ISSUE THREAD

**Issue by lukasharing** [playcanvas/engine#3494]
### Description
iPad 2 Air - Variance Shadow Map crashes Ionic APP, error log is not shown.

I could fix this bug by changing it to Shadow Map PCF

### Steps to Reproduce (Two ways)
1. Initialize game
2. Pause Game
3. Unpause Game

1. Initialize game
2. Let the game run for +10s

**Comment by yaustar** [comment]
Does this crash on Safari?

**Comment by lukasharing** [comment]
I just tried it on Safari but it works perfectly, could it be the webview?

**Comment by lukasharing** [comment]
The path of the project: https://launch.playcanvas.com/1093280

**Comment by yaustar** [comment]
Could be related to texture and VRAM usage? Maybe Ionic requires more RAM for the wrapper. A webview crash can mean using too much VRAM.

**Comment by lukasharing** [comment]
I guess that should be, but it is working on every other ios device but not in iPad Air 2. We could partially fix this if we pause the game in the middle of the lap for 1s, and unpause it.

**Comment by yaustar** [comment]
Do the other devices have more RAM?

**Comment by lukasharing** [comment]
I tried with iphone 6 (1GB RAM and it is working) while Air 2 has (2GB RAM)

**Comment by yaustar** [comment]
How odd, I wonder if it's a resolution related too 🤔 

Can you try reproducing the issue by removing the skybox and related assets?

**Comment by mvaligursky** [comment]
I had a quick look to make sure we don't allocate vms blur texture each frame or similar .. but I dont see a problem here, just one extra texture allocated in the cache.

I agree it could be related to memory use on the device, or possibly some memory leak in your code - that's one of the few reasons the operating system on iOS can simply just close the application.

**Comment by lukasharing** [comment]
Skybox Test (VSM 16 bits):
- ON: BREAKS 2seconds
- OFF: Works

**Comment by yaustar** [comment]
Feels like a VRAM crash if the it works without the the skybox. Can you try with the skybox but reduce the textures from 2048 x 2048 to 1024 x 1024

**Comment by lukasharing** [comment]
WORKS!! Perfect

**Comment by yaustar** [comment]
Cool, chances are that the game is using too much VRAM with textures, especially on low memory devices.
