### ISSUE TITLE
Compatibility issue with Safari 15

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#3500]
Playcanvas engine fails to initialize on just released Safari 15. This seems to affect both Webgl1 and Webgl2 context.

This is the line that fails / makes the page reload:
https://github.com/playcanvas/engine/blob/6baccc6a2dd2bac5045c46d603fa40a17d0af9f3/src/graphics/graphics-device.js#L301

When this line is commented out, the engine starts up:
https://github.com/playcanvas/engine/blob/6baccc6a2dd2bac5045c46d603fa40a17d0af9f3/src/framework/application.js#L438

I don't see this problem mentioned online yet. 

Looking at documentation:
https://www.w3.org/TR/webxr/

it's recommended makeXRCompatible() is suggested to be used instead of this flag for multiple reasons. It could trigger context loss which is possibly the reason we do not use it at the moment.

**Comment by willeastcott** [comment]
CC @Maksims

**Comment by mvaligursky** [comment]
This seems to have the same behaviour in Safari Technology Preview Release 132 (Safari 15.4, WebKit 16613.1.1.5)

**Comment by mvaligursky** [comment]
Some related discussions
https://github.com/immersive-web/webxr/issues/1014
https://github.com/mrdoob/three.js/issues/19275

**Comment by Maksims** [comment]
The use of `makeXRCompatible` can lead to context loss on multi-gpu systems.
One quickest option for action here: as Safari is misbehaving, then it should be a Safari-only fix not to affect all the other users.
As Safari does not support WebXR, we can safely not set the flag for Safari only. I understand this is not desired behaviour when we do platform-specific fixes, but this is a platform-specific bug with misbehaving from their side.

**Comment by mvaligursky** [comment]
This is the initial PR which added `xrCompatible` to options .. projects published before this are ok (Jan 2020)
https://github.com/playcanvas/engine/pull/1834

**Comment by willeastcott** [comment]
Reopening until we know what Apple intends to do...

**Comment by mvaligursky** [comment]
another issue related to Safari 15: https://github.com/playcanvas/engine/issues/3506

**Comment by grorg** [comment]
We fixed this here: https://bugs.webkit.org/show_bug.cgi?id=230525

I've tried with tip-of-tree WebKit on the various reported pages and it seems to work now.

**Comment by willeastcott** [comment]
Closing since Safari has now been fixed (albeit not deployed yet).
