### ISSUE TITLE
Clustered lighting example does not work on Safari 15

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#3506]
Works in other browsers. Used to work in Safari before 15, which was using WebGl1, but crashes the tab in Safari 15.
http://playcanvas.github.io/#/graphics/clustered-lighting

**Comment by grorg** [comment]
I just checked this also. It's working for me in tip-of-tree Safari on Monterey.

**Comment by mvaligursky** [comment]
Thanks @grorg !
