### ISSUE TITLE
How to enable ImageBitmap in the engine

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#3518]
The `ImageBitmap` interface is able to load textures in a more performant manner and does so off the main thread, compared to the browser \<img\> element.

The engine already has support for ImageBitmap (see https://github.com/playcanvas/engine/blob/master/src/resources/parser/texture/img.js#L24), but currently has it disabled. The reason is that some applications assume `pc.Texture.source` is an \<img\> element and so these applications break when ImageBitmap is used instead.

How should we go about enabling ImageBitmap in the engine? The options seem to be:
- disable ImageBitmap by default, but give user opt-in
- enable ImageBitmap by default, but give user opt-out
- always enable ImageBitmap and get users to modify their app

**Comment by yaustar** [comment]
I vote for disable ImageBitmap loading by default on the engine level but with the examples and in the Editor, enable it as default in new projects (as it's a performance increase) as it's rarer for users to use the image element.

**Comment by Maksims** [comment]
If it alters significantly existing projects, then I agree with @yaustar - it should stay for existing projects as is by default.
Engine-only users should be well informed if there is a behavioural change for new engine version, and likely can be enabled by default, but ONLY if it does not require any migration and will not break existing projects.

New projects in Editor would benefit from this change indeed.

I believe it was disabled by default, due to a difference in ImageBitmap implementation by Browsers.

**Comment by slimbuck** [comment]
Hmm perhaps I overstated the breakage to existing projects.

ImageBitmap behaves the same as before as far as user is concerned. Existing projects will only break if they access the `pc.Texture` source and assume it's a <img> element. I know of one project that does this: they use the texture source in custom dynamic HTML. I can't find this project now unfortunately, but TBH I'm not sure why they didn't just add img elements.

Going forward, I expect ImageBitmap will be the default for almost all projects (especially since Safari appears to be adding support). I think it will be strange for the engine to default this off.

@Maksims ImageBitmap was disabled before because the engine required images to be flipped and ImageBitmap made this difficult. (ImageBitmap has a constructor vflip option whereas the engine was flipping at GPU upload time). As you probably know, we've since changed the engine to keep images native orientation and so this is no longer an issue.

**Comment by mvaligursky** [comment]
This seems to be one of the cases where users use undocumented behaviour - I don't believe Texture's documentation promises to deliver data in <img> compatible format. As such, we should be free to change its internal implementation as we see fit. 
An exception can be taken if the private implementation is expected / used by lots of projects, which does not seem to be the case here.
And so we should handle this in the same way we handle any private API changes - change them and document the change to let the users know.

**Comment by Maksims** [comment]
> This seems to be one of the cases where users use undocumented behaviour - I don't believe Texture's documentation promises to deliver data in  compatible format. As such, we should be free to change its internal implementation as we see fit.

[texture.getSource](https://developer.playcanvas.com/en/api/pc.Texture.html#getSource) - is actually public.

**Comment by slimbuck** [comment]
> > This seems to be one of the cases where users use undocumented behaviour - I don't believe Texture's documentation promises to deliver data in  compatible format. As such, we should be free to change its internal implementation as we see fit.
> 
> [texture.getSource](https://developer.playcanvas.com/en/api/pc.Texture.html#getSource) - is actually public.

The format of the data isn't specified though. If you load a dds file then data is array of bytes, for example.

**Comment by slimbuck** [comment]
I feel like this almost falls in the cracks between public API and not :)

**Comment by yaustar** [comment]
> The format of the data isn't specified though. If you load a dds file then data is array of bytes, for example.

![image](https://user-images.githubusercontent.com/16639049/134937144-6d5954ee-0d34-4435-a088-edb88d5a8e60.png)

It says that it returns a HTMLImageElement in this case though?

**Comment by slimbuck** [comment]
Oh interesting, I missed the return value doc. Actually return value can be HTMLCanvasElement, HTMLImageElement, HTMLVideoElement or POD.

**Comment by slimbuck** [comment]
(or ImageBitmap)

**Comment by Maksims** [comment]
> Oh interesting, I missed the return value doc. Actually return value can be HTMLCanvasElement, HTMLImageElement, HTMLVideoElement or POD.

So devs are already common with multi-type return, so it is totally fine to add new one.

With Y flip change, this should be a breeze!
I guess ImageBitmap will reduce freezes when uploading large image to GPU as a texture?

We've been reducing freezes by using compressed textures instead of JPGs.

**Comment by slimbuck** [comment]
I just tested ImageBitmap in Firefox and Safari.

Firefox still doesn't support constructor options so it's not possible to specify `premultiplyAlpha: 'none'`. This is a long-standing issue https://bugzilla.mozilla.org/show_bug.cgi?id=1367251. The result is serious banding in RGBM textures.

Safari appears to accept `premultiplyAlpha: 'none'`, but still premultiplies alpha and has the same banding issue as Firefox and \<img\> tag.

![Screenshot 2021-09-28 at 09 40 57](https://user-images.githubusercontent.com/11276292/135054901-44afd009-dbbb-4539-aa5c-1c0e02aaba23.png)

This is unfortunate, because until all browsers support ImageBitmap correctly we can't rely on it to solve the banding issues with RGBM.

**Comment by willeastcott** [comment]
Will the PNG RGBM problems never end? This is really holding us back. Can we at least use ImageBitmap for non-RGBM images?

**Comment by willeastcott** [comment]
That bug you link to is apparently fixed in Firefox 93? That is due for release on 5th October.

**Comment by slimbuck** [comment]
This is not to detract from enabling `ImageBitmap` in the engine. `ImageBitmap` works well in Chrome so should result in good win there at least. The sooner we enable ImageBitmap in the engine (even limited to Chrome initially) the better. Over time as platforms improve their support we can enable this feature there too.

**Comment by slimbuck** [comment]
@willeastcott you've suggested before that we use a JS loader for RGBM PNG textures only (https://github.com/playcanvas/engine/pull/3419#discussion_r692982570). I actually think this is a great option for us until we get uniform support for `ImageBitmap` in all browsers.

**Comment by Maksims** [comment]
If decoding of PNG using JS decoders can be done in a WebWorker (to avoid JS thread blocking) and is not dramatically slow, then it is a good option for misbehaving browsers (iOS in particular). So there would be a white list of platforms to fall back to JS png decoding, while good ones can use in-built decoding, and modern whitelisted can use ImageBitmap.

**Comment by yaustar** [comment]
Imagebitmap is now available in the engine since 1.57.
