### ISSUE TITLE
Low frame rates on Android (Chrome 94) with WebGL 2

### ISSUE THREAD

**Issue by potentially-null** [playcanvas/engine#3532]
### Description
Considerably lower frame rates when using WebGL 2 as compared to WebGL on Android (Chrome 94).

Reproduced on Samsung Galaxy Tab S7+, Samsung Galaxy S8+
The screenshots below were taken on the Galaxy Tab.

### WebGL 2
![Screenshot_20211001-142305_Chrome](https://user-images.githubusercontent.com/80072747/135623493-8a9561f3-6247-41d2-b9ad-bb21468a149e.jpg)

### WebGL
![Screenshot_20211001-142155_Chrome](https://user-images.githubusercontent.com/80072747/135623513-18703c5d-e422-43ad-93f7-7db880e2b321.jpg)

Example project: https://playcanvas.com/project/836325/overview/webglwebgl-2-perf-test

**Comment by mvaligursky** [comment]
Hi @potentially-null - thanks for the report. You mention it's a regression - do you have any additional info on this? Are you comparing it to an earlier version of Chrome? Or an earlier version of the engine? And specific versions?

**Comment by potentially-null** [comment]
Hi @mvaligursky, I have not tested it on any other versions of Chrome or with any other versions of the engine. The regression is that it is slower on WebGL 2 than on WebGL 1. I do not know if it has always been like this. Sorry for the confusion, I am going to change the heading.

**Comment by Maksims** [comment]
Can you post a screenshot from webglreport.com of both tabs (WebGL1 and WebGL2).

**Comment by potentially-null** [comment]
![Screenshot_20211016-115344_Chrome](https://user-images.githubusercontent.com/80072747/137583484-419b91d7-6798-4afc-8045-721215defe0e.jpg)
![Screenshot_20211016-120121_Chrome~2](https://user-images.githubusercontent.com/80072747/137583508-ee5fb4a5-d097-4ba3-850a-ca10bea4c284.jpg)
![Screenshot_20211016-115406_Chrome](https://user-images.githubusercontent.com/80072747/137583503-90452fdf-dc3d-4866-860d-47933d6b432f.jpg)
![Screenshot_20211016-120106_Chrome~2](https://user-images.githubusercontent.com/80072747/137583511-54741723-3d1c-49d0-9ad0-6e536eb01f62.jpg)

**Comment by mvaligursky** [comment]
I'll close this as won't do.
