### ISSUE TITLE
[Request]: on_floor method for physics bodies

### ISSUE THREAD

**Issue by psstoyanov** [playcanvas/engine#3535]
This issue tracker is **only** for bug reports and feature requests. For general support/help, visit https://forum.playcanvas.com

For bug reports, include:

### Description
It took me years but I believe finally, I can word my request better.

Please, consider the creation of `on_floor` , `on_ceiling` and `move_and_slide` methods similar to Godot's implementation:
https://github.com/godotengine/godot/blob/1c0ae31c9eb1cd7d228e82ea6ad6babee5231395/scene/2d/physics_body_2d.cpp#L1307

PlayCanvas is amazing on many levels, having simplified methods to handle those very common use-cases would make it even more approachable.

**Comment by yaustar** [comment]
What do these options do?

**Comment by yaustar** [comment]
Not sure how much/if any of this can be implemented as we are bound by what Ammo/Bullet can give us feature wise

**Comment by psstoyanov** [comment]
Thank you, @yaustar . 

In that case, it's better to close this ticket.

Will later some time (much later) once I learn more about the kinematic system used by Godot.
