### ISSUE TITLE
WebGPU Support

### ISSUE THREAD

**Issue by hottestchilipepper** [playcanvas/engine#3536]
Is there a plan to integrate with WebGPU?

Or, is it possible to integrate with WebGPU?

**Comment by yaustar** [comment]
There are plans to, yes. Work hasn't started on this yet. Currently, plans for the work to be completed in 2022

**Comment by slimbuck** [comment]
Hi @hottestchilipepper, as @yaustar says this is on our roadmap. I'm just wondering, why specifically are you interested in webgpu? Is there a feature you're after or something else? Thanks!

**Comment by mvaligursky** [comment]
>  plans for the work to be completed in early 2022

that's the plan for the prototype, not a full solution.

**Comment by heretique** [comment]
Interested in this as well, looking forward for proper compute support, but still, it'll take a while until the WebGPU API is stabilized.

**Comment by mvaligursky** [comment]
closing in favour of https://github.com/playcanvas/engine/issues/3986
