### ISSUE TITLE
Investigate parallel shader compilation

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#3559]
Try the suggestion here:
https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#compile_shaders_and_link_programs_in_parallel

It's tempting to compile shaders and link programs serially, but many browsers can compile and link in parallel on background threads.

**Comment by Adriaaaaan** [comment]
Very much looking forward to progress in this area, my use case is very dynamic in terms of loading in assets and so shader compilation pauses are very detrimental
