### ISSUE TITLE
Bitmoji issue with 1.47.0

### ISSUE THREAD

**Issue by flyingbaba** [playcanvas/engine#3562]
With a 1.47.0 release we are getting weird blinking of the Bitmoji in the game same as in this project: https://playcanvas.com/editor/scene/1023597

### Steps to Reproduce

1. Open: https://playcanvas.com/editor/scene/1023597
2. Hit Play from Editor

**Comment by slimbuck** [comment]
And after a few reloads, I see flicker again.

**Comment by mvaligursky** [comment]
we're on it, thanks!

**Comment by flyingbaba** [comment]
Looks like it is fixed. we are not getting this bug anymore.
