### ISSUE TITLE
Negative UI-element scale breaks the input

### ISSUE THREAD

**Issue by fotik333** [playcanvas/engine#3570]
### Description

There`s no way to mirror UI-element horizontally or vertically to keep the inputs.

### Steps to Reproduce

1. Create UI-element
2. Set "useInput" to active
3. Set scaleX to -1

**Comment by jpauloruschel** [comment]
Yes, but recent changes shouldn't have changed this behaviour. I'll look into this and provide updates in this thread.

**Comment by jpauloruschel** [comment]
Fix for this issue has been merged to `engine` and will be available in one of the next releases.
