### ISSUE TITLE
Precise draw order control

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#361]
Implement proper layer system.

**Comment by crazydadz** [comment]
Any ETA on that feature? xD

**Comment by willeastcott** [comment]
No ETA yet, but the dev team discussed the need for 3 new engine features after completing a recent project. This was one of them, so it's bubbling closer to the top of the priority list.

**Comment by daredevildave** [comment]
See [Layers](https://developer.playcanvas.com/en/user-manual/graphics/layers/)
