### ISSUE TITLE
FOV of camera does not reflect the FOV used when rendering in XR

### ISSUE THREAD

**Issue by potentially-null** [playcanvas/engine#3635]
### Description
During an active XR session, the XR system does not update the camera's FOV but only uses it internally for rendering. As a result, methods such as worldToScreen return incorrect values.

### Expected
The XR system updates the camera's FOV along with its position and rotation, so methods like worldToScreen can be used.

This [example project](https://playcanvas.com/project/845467/overview/issue-3635) logs CameraComponent::fov and the FOV extracted from the xr projection matrix to console.

**Comment by mvaligursky** [comment]
These issues are likely related to this code: https://github.com/playcanvas/engine/blob/6042bada715359d93a6ad1cf125fed2b210e9733/src/scene/renderer/forward-renderer.js#L383-L408

It's used to sync view / projection matrix params both ways between the engine and XR. I guess this needs to be improved to handle position / origination / fov and similar. But perhaps more work is needed, as doing it at this rendering stage, which takes place after user scripts are executed, could cause the user using the camera (for example for ray-casting) to be a frame behind. Perhaps cameras need to be somehow synced in between update and postUpdate.

**Comment by yaustar** [comment]
Fixed by https://github.com/playcanvas/engine/pull/4837
