### ISSUE TITLE
Support glTF extensions for refraction, color attenuation and volumetric properties

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#3642]
Specifically these extensions: 
- https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_ior/README.md
- https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_volume/README.md
- https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_specular/README.md

![image](https://user-images.githubusercontent.com/59932779/139648742-c86bb6ab-5d36-4c0c-8a4b-1ca3759719c0.png)

See more here: https://www.khronos.org/news/press/new-gltf-extensions-raise-the-bar-on-3d-asset-visual-realism
Forum: https://forum.playcanvas.com/t/creating-the-effect-of-transparent-glass-and-plastic/22637

**Comment by willeastcott** [comment]
I would split this into 3 issues, since each glTF extension is likely to be addressed by a single PR.

**Comment by mvaligursky** [comment]
closing and creating separate issues
