### ISSUE TITLE
Engine no longer supports iOS 8

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3658]
On startup, iOS 8 gives the following error on the default scene setup 

Forum: https://forum.playcanvas.com/t/iphone4s-revisited/22666

From the debug build

```
8a96-51-148-130-218.ngrok.io/:4 Viewport argument key "viewport-fit" not recognized and ignored.
playcanvas-stable.dbg.js:33551 TextDecoder not supported - pc.Untar module will not work
playcanvas-stable.dbg.js:70501 Powered by PlayCanvas 1.49.0 eb609bf4e
playcanvas-stable.dbg.js:14675 WebGL: INVALID_OPERATION: texImage2D: type HALF_FLOAT_OES but ArrayBufferView is not NULL
playcanvas-stable.dbg.js:14679 Above error related to HALF_FLOAT_OES can be ignored, it was triggered by testing half float texture support
playcanvas-stable.dbg.js:6718 DEPRECATED: pc.Application#loadScene is deprecated. Use pc.Application#scenes and pc.SceneRegistry#loadScene instead.
__start__.js:203 Error while loading scene JSON 1265092.json: undefined is not a function (evaluating 'Array.from(o)')
_unsupportedIterableToArray@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:1438:53
_createForOfIteratorHelperLoose@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:1454:61
_processParameters@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:13618:56
updateUniforms@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:13764:27
submitCasters@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:22613:29
render@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:22667:24
renderShadows@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:23955:32
renderComposition@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:24665:24
render@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:71155:35
https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:71770:23
start@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:71114:13
https://8a96-51-148-130-218.ngrok.io/__start__.js:206:34
_loaded@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:70258:16
_preloadScripts@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:70855:13
https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:70262:31
https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:35118:14
_onSuccess@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:2127:21
_onReadyStateChange@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:2079:23
onreadystatechange@https://8a96-51-148-130-218.ngrok.io/playcanvas-stable.dbg.js:2015:30(anonymous function) @ __start__.js:203(anonymous function) @ playcanvas-stable.dbg.js:70265(anonymous function) @ playcanvas-stable.dbg.js:35132_onSuccess @ playcanvas-stable.dbg.js:2129_onReadyStateChange @ playcanvas-stable.dbg.js:2079onreadystatechange @ playcanvas-stable.dbg.js:2015
__loading__.js:33 TypeError: null is not an object (evaluating 'splash.parentElement')hideSplash @ __loading__.js:33fire @ playcanvas-stable.dbg.js:796start @ playcanvas-stable.dbg.js:71101(anonymous function) @ __start__.js:206(anonymous function) @ playcanvas-stable.dbg.js:70265(anonymous function) @ playcanvas-stable.dbg.js:35132_onSuccess @ playcanvas-stable.dbg.js:2129_onReadyStateChange @ playcanvas-stable.dbg.js:2079onreadystatechange @ playcanvas-stable.dbg.js:2015
1932playcanvas-stable.dbg.js:1438 TypeError: undefined is not a function (evaluating 'Array.from(o)')
```

**Comment by willeastcott** [comment]
Ahhh, yeah, great detective work @mvaligursky. 

https://caniuse.com/mdn-javascript_builtins_set_--iterator

**Comment by mvaligursky** [comment]
needs to be swapped to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/forEach

**Comment by Maksims** [comment]
If it is executed on every tick, best to avoid forEach as it leads to function allocations, also iterators - as they do generate GC also.
The best is ES5 `for(;;)` loops if it is executed on every tick.

**Comment by mvaligursky** [comment]
foreach is the only option on a set / map which is this case .. otherwise agreed.

**Comment by willeastcott** [comment]
Apparently there is still a problem on iOS 8? Reopening until any remaining bug(s) are found.

**Comment by yaustar** [comment]
Safari iOS 8 tab crashes on engine version 1.43.0+

Last working version of the engine for iOS 8 is 1.42.0

**Comment by willeastcott** [comment]
What's the current status here, @yaustar? I tested 1.49.1 on an iPhone 6 running iOS 8 on BrowserStack and it worked (after the latest round of fixes). They didn't seem to have an option to select an iPhone 4S running iOS 8.

**Comment by mvaligursky** [comment]
I tried iPhone 6 with v8.1 (browserstack) running some of our engine examples - some work well, but some crash out the tab, with nothing in the console. 

When I disable shadows on the directional light in these 3 engine examples, they work:
- render-cubemap
- clustered-lighting
- lights

Omni and spot shadows are ok.

So it seems something related to directional shadows. I'll try some more experiments there to see if I can get more details.

**Comment by mvaligursky** [comment]
This chunk is causing the issue:
https://github.com/playcanvas/engine/blob/dev/src/graphics/program-lib/chunks/shadowCascades.frag

This gets included with directional shadows (fadeShadow executes even without cascades).

It seems ios8 fails (kills the tab) when it's compiling a shader line which passes a uniform array to a function, even if the function is empty. This line is added to the main shader, which is causing the isssue:

`    fadeShadow(light0_shadowCascadeDistances);`

Possible workaround would be to not have the chunk, but generate that code inlined in the main shader code.
I tried multiline macro to do it, but it seems iOS8 does not support that either.

Another possible workaround is to use a custom engine, and strip that offending line, and not using shadow cascades. Or even completely disable directional shadows on a light, this works without custom engine. 

I'm leaving this as is for now. The workaround is to upgrade iOS device to version 9, which is available even for iPhone 4S, which is the minimum device we aim to support.

**Comment by willeastcott** [comment]
Closing as iOS 8.x and below [now accounts for ~0.21% of iOS market share](https://gs.statcounter.com/ios-version-market-share/).
