### ISSUE TITLE
WebGL errors when drawing mesh

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#367]
Check out this project that renders NCC 1701-B:

https://playcanvas.com/editor/scene/347790

The model is broken into two. I think I did this to avoid going over 65535 vertices. Anyway, the rear section does not render and you get the console messages:

messenger.js:105 messenger connected
6launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
8launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
39launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
2launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
10launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
4launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
15launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
7launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
10launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
6launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
8launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
39launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
2launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
10launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
4launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
15launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
7launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
10launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
6launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
8launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: attempt to access out of range vertices in attribute 0
25launch:1 [.WebGLRenderingContext-0E758CD0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer
launch:1 WebGL: too many errors, no more errors will be reported to the console for this context.

**Comment by guycalledfrank** [comment]
Fixed in https://github.com/playcanvas/engine/pull/368
