### ISSUE TITLE
Investigate a single texture slot solution for Image Based Lighting

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#3681]
At the moment IBL on most platforms uses 6 cubemaps to handle prefiltered lighting data for different roughness. This uses up 6 out of 16 samplers on most platforms, causing us to run out of these when clustered lighting is enabled (2-4 samplers depending on enabled features - shadows and cookies are optional) along with some materials using multiple textures, and area lights (1 LUT sampler)

The hope is to investigate and implement a solution that uses a single texture sampler:
- could be some form of an atlas of prefiltered data with manual lookup
- or perhaps even use one of the existing solutions, but apply it to all platforms: use a single cubemap with mipmaps storing levels of prefiltered data. The limitation here is that not all platforms allow us to manually sample LODs based on roughness. Possible workaround here is to simply as a fallback always sample top level on those platforms - assuming this is only required on small number of old devices.

**Comment by mvaligursky** [comment]
related: https://github.com/playcanvas/engine/issues/2685

**Comment by willeastcott** [comment]
https://github.com/playcanvas/engine/pull/3783
