### ISSUE TITLE
Material assets/resources don't load again after being unloaded since version 1.48.0+

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3683]
Project: https://playcanvas.com/project/849163/overview/error-when-adding-template

Steps to repro:

1. Launch Scene 'Start'
2. Press Space to load the Untitled scene with the Ambulance
3. Press Space again to load the scene 'Start' with the cube
4. Press 1 to unload assets with the tag 'Maze1'
5. Press Space to load the Untitled scene with the Ambulance
6. Crash with the following callstack

```
playcanvas.dbg.js?version=1.49.1:20557 Uncaught TypeError: Cannot read properties of null (reading 'alphaToCoverage')
    at MeshInstance.updateKey (playcanvas.dbg.js?version=1.49.1:20557)
    at MeshInstance.set (playcanvas.dbg.js?version=1.49.1:20828)
    at new MeshInstance (playcanvas.dbg.js?version=1.49.1:20465)
    at Model.clone (playcanvas.dbg.js?version=1.49.1:28839)
    at ModelComponent._onModelAssetLoad (playcanvas.dbg.js?version=1.49.1:59592)
    at ModelComponent._bindModelAsset (playcanvas.dbg.js?version=1.49.1:59569)
    at ModelComponent.set (playcanvas.dbg.js?version=1.49.1:59713)
    at ModelComponentSystem.initializeComponentData (playcanvas.dbg.js?version=1.49.1:60091)
    at ModelComponentSystem.addComponent (playcanvas.dbg.js?version=1.49.1:43636)
    at SceneParser._openComponentData (playcanvas.dbg.js?version=1.49.1:35086)
```

On engine version 1.47.2, the scene loads fine both times

https://launch.playcanvas.com/1268937?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.47.2.js

Breaking commit since 1.47.2 is https://github.com/playcanvas/engine/pull/3557

**Comment by yaustar** [comment]
Functionality to change the meshInstance material back to default was removed here: https://github.com/playcanvas/engine/pull/3557/files#diff-9ae4b2931c405acfbabe05b21475b6c7f96ddebc38cc36d934a1f10405646abfL438

**Comment by yaustar** [comment]
Super stuck on this one, either the meshInstance or the material needs a reference to the default material in scene.js. But I can't find an elegent way to get a reference to it so considering some sort of app ref counting global.

**Comment by willeastcott** [comment]
Hey @mvaligursky, can you lend a hand here please?

**Comment by yaustar** [comment]
We could have global object in globals.js that maps an app id to a default material that is managed by scene.js. So far, that's my cleanest workaround 🤔

**Comment by mvaligursky** [comment]
My proposal:

**Generic update:**
- a default material needs to be unique per GraphicsDevice, as its shaders are compiled using the device.
- Application and GraphicsDevice have 1:1 relationship
- at the moment we create defaultMaterial in the Scene - which is not ideal if there are multiple Scenes - MeshInstances could have pointers to either of these default materials, and few things might not behave as expected
- so we create defaultMaterial in the Application instead, and pass Application to the Scene in the constructor. This will allow Scene to return Material that is owned by the Application.
- create new class DefaultMaterial, with static getDefaultMaterialForDevice and maybe getDefaultMaterialForApplication
- when the Application is created, it will add its standard material to this cache, optionally remove it when it's destroyed

This will allow us to access standard material if we know device or application. Not only scene as currently.

**This issue specific change:**
we need to get default material for meshInstance. Mesh instance has mesh which has a device .. and we can use this DefaultMaterial cache to look up default material for this device.


**API CHANGE** - as mentioned, the Scene will take Application in a constructor
- there is one use of it in the engine - will fix it
- there are two places this constructor is called in the Editor. Initially, before Editor is updated, when App is undefined, Scene will allocate Default material as well, just as currently, so Editor does not break. Later, this can be removed.
- Alternatively, we release Editor first, which passes the App pointer to Scene constructor, this would be simpler.

**Later**
- remove defaultMaterial from the Scene completely .. and change all access to get it from DefaultMaterial class. This will likely allows us to remove few strange assignments of the scene to some objects to be able to access it.

**Comment by yaustar** [comment]
> at the moment we create defaultMaterial in the Scene - which is not ideal if there are multiple Scenes - MeshInstances could have pointers to either of these default materials, and few things might not behave as expected

We only have one scene now at the moment right?

**Comment by mvaligursky** [comment]
| We only have one scene per application now at the moment right?

Engine has one. Editor creates scenes as it generates thumbnails. 
Users can create scenes as well.

It's not about exact number, it's about where things correctly belong on the architecture level.
And it allows me to solve this bug, which is a side benefit.

**Comment by mvaligursky** [comment]
Also, @slimbuck mentioned yesterday he'd like to use multiple scenes in a single application .. which makes sense. This would bring us closer to being able to do it.

**Comment by slimbuck** [comment]
Nice investigation @mvaligursky!

Is it a requirement that each application instance have a unique device? Feels like the default material should be strictly per device, not application.

**Comment by yaustar** [comment]
Okay, sounds like it would be fine to me.

**Comment by mvaligursky** [comment]
| Is it a requirement that each application instance have a unique device? Feels like the default material should be strictly per device, not application.

Well conceptually sure. Maybe a simpler way would be:
 - Application constructor currently creates a device, then creates defaultMaterial and passes it to device. We can then get it from the device, and remove it from the scene.

**Comment by yaustar** [comment]
As side curiosity question, how will the material or mesh instance be able to reference the default material/how getDefaultMaterialForDevice return the correct material?

**Comment by mvaligursky** [comment]
> As side curiosity question, how will the material or mesh instance be able to reference the default material/how getDefaultMaterialForDevice return the correct material?

as mentioned before, meshInstance.mesh.device will be used to look it up in the cache. Or as mentioned, we could store defaultMaterial on the device directly, but that's dirty, cache is cleaner.

**Comment by yaustar** [comment]
Oh cool, I missed that the mesh had a reference the graphics device last night 🤦 That's great!

**Comment by Maksims** [comment]
Device cannot live without Application, right?
So there should be no problem providing app reference to a device. So material can easily live on either of them.
Global cache - seems wonky solution, to the problem of references.

While app and device go 1:1, it is a totally valid for app not to have a device (renderless case).

**Comment by willeastcott** [comment]
My only concern around any of this is.... 🌴 shaking.

Is the Application a low-level core object with few to no dependencies. Or is it a high level object that depends on lots of other classes?

If it's the latter, we run the risk of introducing more cyclic dependencies. So please do think about that.

**Comment by mvaligursky** [comment]
| it is a totally valid for app not to have a device (renderless case).

This is not valid at the moment I believe? But the plan is to implement a NullDevice or similar.

| So there should be no problem providing app reference to a device.

In proper design, a lower level library / level (GraphicsDevice) should not have access to higher level (Application).

**Comment by mvaligursky** [comment]
> My only concern around any of this is.... 🌴 shaking.

Yep I considered this. But storing a pointer on an object does not require the import of the class, so this does not change the 🌴 shakeability.

**Comment by Maksims** [comment]
> This is not valid at the moment I believe? But the plan is to implement a NullDevice or similar.

It kinda is, but with hacks and overrides to make it work. Would be great to be able to run the engine without mock canvas, no DOM, and render context at all. We did make it work that way locally, but it was an effort and feels like "hacky".
