### ISSUE TITLE
[API Enhacement Request] Expose additional information to the AnimComponent and AnimComponentLayer APIs

### ISSUE THREAD

**Issue by heretique** [playcanvas/engine#3688]
Hi PlayCanvas team,

Working on a flipbook animation feature for our particular use case we think we've found some limitations in the current `AnimComponent` APIs. The reason for these requests are explained in [this](https://forum.playcanvas.com/t/is-there-an-easy-way-to-get-the-name-of-the-animation-track-asset-associated-with-an-anim-state/22805) post on the PlayCanvas Forum.

It would be useful if the public API would expose methods to retrieve all the layers added to an `AnimComponent` not just the `baseLayer`.
Also on the `AnimComponentLayer` it would be great if we can also get methods to allow retrieval of the associated animation assets and animation tracks for each state without having to rely on internal functionality that might change.
One more thing that I think it might be useful is to have automatic animation events (`START, END`) for each animation with information about the animation (track name, asset name, etc…whatever might be useful).

I hope you consider this request as I believe it may be useful for other developers as well.
Thank you!

**Comment by ellthompson** [comment]
Also the `assignMask` function in `AnimComponentLayer` should be converted to a get/set `mask` property.

**Comment by ellthompson** [comment]
Needs to be updated with changes from: https://github.com/playcanvas/engine/pull/3919.
