### ISSUE TITLE
Loading GLBs at runtime only loads singular mesh piece

### ISSUE THREAD

**Issue by RandomPandaStudios** [playcanvas/engine#3702]
1. I have a imported morph-target GLB in the PlayCanvas Editor
2. The GLB is comprised of two mesh pieces (`Character` + `Gun`)
3. When I use the PlayCanvas demo for loading glTF/GLB models at runtime, it only loads the `Character` mesh piece.
https://developer.playcanvas.com/en/tutorials/loading-gltf-glbs/

PlayCanvas Project Demo:
https://playcanvas.com/project/851279/overview/assaultcube-model-viewer

Raw Model (It's also in the Editor project):
[AC_PlayerModel_Test.zip](https://github.com/playcanvas/engine/files/7541927/AC_PlayerModel_Test.zip)

## Model (Tested locally) in Microsoft 3D Viewer:
Shows character + gun.
https://cdn.discordapp.com/attachments/408617316415307778/909914319800643594/unknown.png

## Model (Tested online) in BabylonJS Viewer:
Shows character + gun.
https://cdn.discordapp.com/attachments/408617316415307778/909921310166110258/unknown.png

## Model (Tested online) in PlayCanvas Editor:
Shows only character and no gun.
https://cdn.discordapp.com/attachments/408617316415307778/909914365568909332/unknown.png

**Comment by yaustar** [comment]
Are the discord links viewable if people aren't on the server?

**Comment by RandomPandaStudios** [comment]
> Are the discord links viewable if people aren't on the server?

Yes they are visible to those who do not have Discord or are not on the PlayCanvas Discord. The media files are public.

**Comment by yaustar** [comment]
Odd that this model in particular is causing issues. In the GLTF test, we have multiple morph targets animating here successfully: https://cx20.github.io/gltf-test/examples/playcanvas/index.html?category=tutorialModels&model=MorphStressTest&scale=2.0&type=glTF

**Comment by mvaligursky** [comment]
I had a quick look .. we load one node which has two meshes on it, so this matches other viewers.
But only one of them gets rendered .. which suggests the gun is getting most likely frustum culled. This probably means that it's placed incorrectly (outside of the frustum) or something similar.

**Comment by yaustar** [comment]
Martin is bang on the money, after disabling the cull on the meshinstances, the gun appears

![Uploading image.png…]()
