### ISSUE TITLE
Have an Aspect Ratio component

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/engine#3726]
Something exactly like Unity's https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/script-AspectRatioFitter.html . The use case?

It's not possible to make image elements with different anchors and pivots work under the same group. It's not possible to have 1 image anchored to the bottom, 1 to the bottom right, while having both under the same group and have it work across all screens for example.

Maybe I'm doing something wrong though. But I guess the issue lies with the fact that I can't make a group fill the whole screen. There isn't an option to do that. I can make the group fill 1280x720 like the 2d screen, and place the images inside the group. It will seem like it works, but then when you run on different screen resolutions it doesn't. If there was an option to make the width/height fill the parent container(2D screen on this case), it would solve the problem,

**Comment by yaustar** [comment]
> It's not possible to make image elements with different anchors and pivots work under the same group. It's not possible to have 1 image anchored to the bottom, 1 to the bottom right, while having both under the same group and have it work across all screens for example.

Set the group elemnt anchors to be 0, 0, 1, 1 as shown here for the render texture https://developer.playcanvas.com/en/tutorials/resolution-scaling/

By doing so, it will always fill to the size of the parent.

Aspect size fitter is a valid request but does have more specialised behaviour compared to what is being asked for here
