### ISSUE TITLE
WebXR immersive VR launching issues on Desktop with Oculus AirLink

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3733]
There's some oddness that I can't explain when launch PlayCanvas WebXR VR experiences on desktop via Oculus AirLink.

Forums thread: https://forum.playcanvas.com/t/recommended-setup-for-xr-development/22794

Setup:
Oculus Quest 1
Connected to Windows 10 with Oculus software using Air link
Using the Oculus OpenXR runtime
Chrome on Windows

PlayCanvas experiences only launches correctly if it's the only tab open that has a WebGL app.

If I have more than one tab (eg and Editor tab and Launch tab), the VR experience fails to load as shown below

https://user-images.githubusercontent.com/16639049/143031177-720c0cae-24cb-479c-a3b6-dbb2440810ef.mp4

However, the hello world from immersive web loads fine no matter the situation: https://immersive-web.github.io/webxr-samples/immersive-vr-session.html

Examples paths I've tried:

Two tabs open with https://immersive-web.github.io/webxr-samples/immersive-vr-session.html , starting VR in either works fine

One tab with https://immersive-web.github.io/webxr-samples/immersive-vr-session.html and another with https://developer.playcanvas.com/en/tutorials/webxr-controllerhand-models/ , starting VR in PlayCanvas fails while immersive-web works fine.

Two tabs open with https://developer.playcanvas.com/en/tutorials/webxr-controllerhand-models/ , neither succeeds entering into VR.

**Comment by yaustar** [comment]
Forgot to mention that there weren't any error messages in the console log of the browser either.

**Comment by yaustar** [comment]
I've not found a solution, no :(

**Comment by magnetica** [comment]
Omg. Very frustrating..

**Comment by Clicky02** [comment]
After a ton of debugging, I found a fix to this issue and just made a PR for it. It was incredibly annoying to figure out what was causing the issue because using breakpoints in the chrome dev tools would stop the issue from occurring.
