### ISSUE TITLE
ability to change the color and opacity of models just like images

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/engine#3739]
Title says it all.  There is a tool that can do this, [Zapworks Studio](https://zap.works/studio/). (Idk why the video is not showing here, just download it).

https://user-images.githubusercontent.com/5656275/143520569-6518da9e-7cfd-4271-8067-961bdefc75ef.mp4

**Comment by mvaligursky** [comment]
We have this ability exposed using Materials on the MeshInstances of the models.

**Comment by marcusx2** [comment]
This is different. You can also change the color messing with the materials on Studio. But they have a system to change the color of the models on top of any existing materials, that works like changing the color of images. And easily change the opacity to make the model fade in/fade out.

**Comment by marcusx2** [comment]
And also, I am trying to change the color of a model right now. The model has a diffuse texture, I am trying to mess with the color property but the color of the model doesn't change.

**Comment by Maksims** [comment]
> And also, I am trying to change the color of a model right now. The model has a diffuse texture, I am trying to mess with the color property but the color of the model doesn't change.

You have to enable Tint.

**Comment by marcusx2** [comment]
This is already possible, no point in keeping this issue open.
