### ISSUE TITLE
Add raycastAll

### ISSUE THREAD

**Issue by chenstopher** [playcanvas/engine#374]
It would be awesome if there was a raycastAll function that gives back all the entities hit by a ray. The raycastFirst function is kinda limited. It only gives back the first entity it hits and you can't ignore specific entities.

I took a look at the ammo.js/bullet stuff and bullet does have a raycast callback that does return all hits. http://bulletphysics.org/Bullet/BulletFull/structbtCollisionWorld_1_1AllHitsRayResultCallback.html. But there doesn't seem to be a binding for it in ammo.js. I'm not sure how to get that to work.

**Comment by Disorrder** [comment]
Any progress?

**Comment by yaustar** [comment]
Doesn't look like in the ammo.js repo: https://github.com/kripken/ammo.js/blob/master/ammo.idl

There are enough bindings exposed in ammo.js currently that allow you to do filtering if that helps?

Looking at PlayCanvas engine code, it looks like there was support for AllHitsRayResultCallback at one time: https://github.com/playcanvas/engine/blob/master/src/framework/components/rigid-body/system.js#L465

PlayCanvas have a fork of ammo.js that you can submit a PR to if you want to have a go at exposing it yourself: https://github.com/playcanvas/ammo.js

**Comment by willeastcott** [comment]
Update on this.

@daredevildave requested `AllHitsRayResultCallback` to be properly exposed in ammo.js here: https://github.com/kripken/ammo.js/issues/37

That has now been done, so we can now add a `raycastAll` quite easily.

**Comment by willeastcott** [comment]
Another update. So while the master ammo.js repo has exposed `AllHitsRayResultCallback` for some time, the ammo builds checked in to this repo still do not have it. @slimbuck - do you know why? If we update our builds, I can submit a PR.
