### ISSUE TITLE
particle screen space anchor

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/engine#3740]
We should be able to anchor a particle system like any other UI element when using screen space.

**Comment by marcusx2** [comment]
Interesting. However, I'd still like it if I as able to anchor a particle to the screen like any other UI element. It would be great for the user this normalization of behavior.

**Comment by yaustar** [comment]
You basically can by making the particle system entity a child of an entity with an element component.

Then you can anchor the element entity how you would normally.

**Comment by marcusx2** [comment]
> You basically can by making the particle system entity a child of an entity with an element component.
> 
> Then you can anchor the element entity how you would normally.

It doesn't work. Try making a particle system a child of an element that is anchored to the bottom of the screen.

**Comment by yaustar** [comment]
https://playcanvas.com/editor/scene/1281372

It looks anchored to me

https://user-images.githubusercontent.com/16639049/143674399-1cd5d1c8-9ce4-4143-b9a0-5864bd05aebd.mp4

**Comment by marcusx2** [comment]
Hm....I must've done something wrong then.
