### ISSUE TITLE
rotate() behaves differently to rotateLocal() at 120fps

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3759]
Thread: https://forum.playcanvas.com/t/rotate-having-issues-that-rotatelocal-does-not/23153

Test project that forces dt to be 1/120 to replicate the issue: https://launch.playcanvas.com/1285029?debug=true

https://user-images.githubusercontent.com/16639049/144244505-2205d545-5e09-4ec4-8e71-708c95af7e27.mp4

I can't see anything in the Engine code that is obvious to cause the rotation to go backwards at a particular point and only at 120fps.

At 60fps, they rotate fine

**Comment by kungfooman** [comment]
Using RTI.js it is almost trivial to fix bugs like this now:

1) Go to http://pc.runtimetypeinspector.org/#/misc/hello-world

2) Replace app-on-update code with:

```js
box.setEulerAngles(70, 11, 84);
app.on('update', (/** @type {number} */ dt) => {
    dt = 1 / 120;
    box.rotate(5 * dt, 6 * dt, 7 * dt);
});
```
3) Figure out how RTI works

(I just did some website refactoing, so I hope the DNS is working for everyone, gotta add HTTPS again too)

**Comment by willeastcott** [comment]
Ooooh, interesting! So does the `rotation` quat here need to be normalized after the `mul2` op?

https://github.com/playcanvas/engine/blob/5a6ff8668e0c0f3deb56ce89d4897b523b020abd/src/scene/graph-node.js#L1629

**Comment by kungfooman** [comment]
> Ooooh, interesting! So does the `rotation` quat here need to be normalized after the `mul2` op?

Just did a little test:

```js
let diff = 0;
for (let i=0; i<100; i+=0.2)
for (let j=0; j<100; j+=0.2)
for (let k=0; k<100; k+=0.2)
{
    box.setEulerAngles(i, j, k);
    const tmp = Math.abs(1 - box.getRotation().length());
    if (tmp > diff) {
        console.log("new diff", tmp.toFixed(10), "for", {i, j, k});
        diff = tmp;
    }
}
```

Last outputs:

```
VM455:9 new diff 0.0000000125 for {i: 0, j: 52.0000000000002, k: 98.80000000000086}
VM455:9 new diff 0.0000000128 for {i: 0, j: 54.80000000000024, k: 97.60000000000085}
VM455:9 new diff 0.0000000129 for {i: 0.2, j: 56.80000000000027, k: 97.20000000000084}
VM455:9 new diff 0.0000000129 for {i: 0.2, j: 56.80000000000027, k: 99.40000000000087}
VM455:9 new diff 0.0000000152 for {i: 0.2, j: 99.40000000000087, k: 58.60000000000029}
```

The value `0.0000000152` seems rather small, but the error seems to creep quickly through some matrices, resulting in the strange zigzag movement.

So I would normalize the quaternion directly where it's coming from, to fix other projects aswell, that may suffer from this:

```diff
 getRotation() {
    this.rotation.setFromMat4(this.getWorldTransform());
-   return this.rotation;
+   return this.rotation.normalize();
  } 
```

But I'm still not sure, maybe there is a way to prevent the precision loss in the matrices in the first place? Best case would be to not call too many methods that contain `Math.sqrt`.
