### ISSUE TITLE
Standard Material GGX specular highlight issue

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#3762]
The engine (at least 1.50.0) fails to compile shader for a standard material that has GGX specular highlight option enabled.

Repro:
https://playcanvas.com/editor/scene/1285178

![image](https://user-images.githubusercontent.com/5677782/144279553-3f02ac78-d199-4ea4-85da-8c32538d59df.png)

It seems in repro project the shader compiles fine at runtime, but in our project it also fails (both in Editor and in Launcher).

**Comment by yaustar** [comment]
The Editor update to 1.50.0 hasn't been released yet so the Editor page is still using 1.49.4.

Looks like the error only happens in the Editor when the cube or material is selected.

**Comment by LeXXik** [comment]
In the live project it crashes when a template that has that entity gets instantiated at runtime.

**Comment by yaustar** [comment]
Does it happen in 1.49.4? Or just 1.50.0?
