### ISSUE TITLE
pc.createMesh is broken in 1.5.0

### ISSUE THREAD

**Issue by heretique** [playcanvas/engine#3776]
### Description

Environment: Windows 11, Firefox 94.0.2

I'm trying to use the `pc.createMesh` method to create a new mesh based on some vertex data I get from multiple other skinned meshes.
I've noticed that the current implementation is calling the `mesh.setVertexStream` with wrong arguments for the `SEMANTIC_BLENDINDICES` semantic
```
        if (opts.blendIndices) {
            mesh.setVertexStream(SEMANTIC_BLENDINDICES, opts.blendIndices, 4, TYPE_UINT8);
        }
```
The fourth parameter should be the number of vertices based on the signature:
```
setVertexStream(semantic, data, componentCount, numVertices, dataType = TYPE_FLOAT32, dataTypeNormalize = false)
```

**Comment by mvaligursky** [comment]
Well spotted, thanks!

In the meantime, feel free to create mesh directly instead of using this wrapped function.
