### ISSUE TITLE
Make anim events fire for reversed anims.

### ISSUE THREAD

**Issue by SpotTrace** [playcanvas/engine#3808]
### Description

Make anim events work when an animation is running in reverse due to using a negative speed setting.

### Steps to Reproduce

In the Animation Events example, if you swap the sign on the speed, the anim events don't fire:

`113: modelEntity.anim.assignAnimation("Walk", walkTrack, undefined, -0.62);`

**Comment by mvaligursky** [comment]
forum link https://forum.playcanvas.com/t/anim-events-for-reversed-anims/23346/3
