### ISSUE TITLE
Should render target samples option be capped to graphicsDevice.maxSamples?

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3813]
Looks like the render target doesn't cap the samples to the maximum that the device supports, is this a problem? 

Graphics Device https://github.com/playcanvas/engine/blob/d1ed79490ab300886409e43c34f55d37eb0c326e/src/graphics/graphics-device.js#L1326

Render target: https://github.com/playcanvas/engine/blob/dev/src/graphics/render-target.js#L111

**Comment by SlimeQ** [comment]
It's a pretty opaque problem to figure out. I ended up with this configuration

`this.renderTarget = new pc.RenderTarget({
            colorBuffer: colorBuffer,
            depth: true,
            flipY: true,
            samples: pc.app.graphicsDevice.maxSamples
        });`
        
As you've noted on discord though, pc.app.graphicsDevice is a private API property and subject to change. Probably would be nice to have something more solid.
