### ISSUE TITLE
Freezes on UI loading and on any change after update from 1.50.0 to 1.50.1

### ISSUE THREAD

**Issue by OlegGedzjuns** [playcanvas/engine#3814]
The project contains a lot of UI elements, when the project is loaded and starts to initialize, everything freezes up to 30 seconds.
After the project is initialized, enabling any UI element causes the same freeze for up to 30 seconds.

The issue is connected with this commit https://github.com/playcanvas/engine/commit/6c3d7dd66c4d5875fdf8538ecdbf0488fc14777c
Building engine before this commit fixes issue.

**Comment by mvaligursky** [comment]
related to https://github.com/playcanvas/engine/pull/3761

**Comment by yaustar** [comment]
@OlegGedzjuns Would you be able to share such a project please? I don't think I have one big enough on hand

**Comment by yaustar** [comment]
Nevermind, it doesn't seem to take much. Example project: https://playcanvas.com/project/861340/overview 

Causes Editor to take ages to load.

Old version: https://playcanvas.com/editor/scene/1294360?use_local_engine=https://code.playcanvas.com/playcanvas-1.50.0.js

**Comment by yaustar** [comment]
Had deeper look. It seems to be related to the UI setup with buttons but haven't established what exactly. 

This scene with 285 buttons seems to be fine for me: https://playcanvas.com/editor/scene/1294446

Still investigating

**Comment by yaustar** [comment]
Created a repro scene that will not be changed: https://playcanvas.com/editor/scene/1294360
