### ISSUE TITLE
Loading models does not work

### ISSUE THREAD

**Issue by Tricho340** [playcanvas/engine#382]
I imported a .fbx model, exported it using the "Export Model Archive" option to .json and then tried to load it in my app using the loadFromUrl function. The callback passed to loadFromUrl is never called and the model is not shown in my app (everything fails silently). The same model is visible in the online editor @ playcanvas.com.

I have pulled the latest version of PlayCanvas from github and have built it.

By the way, when I:
- start a local HTTP server in the folder of your repository on my machine
- try to access the examples/load Model section
the model is not shown as well, so I guess there is an issue indeed.

**Comment by daredevildave** [comment]
Fixed in 8e91a8f037bd32af58b497bdb546f8c9c25b484a
