### ISSUE TITLE
EventHandler#fire not in docs anymore

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#3827]
https://github.com/playcanvas/engine/blob/3ce5abb8ffed7592985113be56951c2265ce3024/src/core/event-handler.js#L141-L163

There shouldn't be another comment between the JSDoc and the `fire` method, maybe just put it after the `fire` method?

Since so many classes inherit from `EventHandler`, the "inherited methods" of each miss this method in the docs aswell.

Problematic line at 160: `/* eslint-enable valid-jsdoc */ `

**Comment by willeastcott** [comment]
Ah, well spotted! I'll fix now. 😄
