### ISSUE TITLE
requestPointerLock crashes in Safari

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#384]
Try this game: http://playcanv.as/p/VXuXQkTe

It doesn't start in Safari because we crash when app.mouse.enablePointerLock() is called.

Probably should check for support before crashing.

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/54c2b2641a335fe6dca8eb16909b20d18e31a3bc
