### ISSUE TITLE
[DOCS] Script Attributes "args.type" Links Are Broken

### ISSUE THREAD

**Issue by rpaladin** [playcanvas/engine#3856]
Documentation Link: https://developer.playcanvas.com/en/api/pc.ScriptAttributes.html
Visual Location:

![image](https://user-images.githubusercontent.com/69180012/147842608-bfc14f4e-07c1-4df4-a263-93e763dcab6b.png)

**Comment by willeastcott** [comment]
Fixed by https://github.com/playcanvas/playcanvas-jsdoc-template/commit/699122dd07691a21dce37aaa0b704ce084e72dd6
