### ISSUE TITLE
autoPlay option doesn't work in looping particle systems

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#387]
If autoPlay is set to false for a particle system, I would expect it not to start with the application. If the particle system is set to looping, it will start regardless of the autoPlay state.

In addition if the autoPlay and loop is false, when the application starts, the particle system appears frozen in space. I would expect there to be no visible particles

**Comment by guycalledfrank** [comment]
First problem was fixed: https://github.com/playcanvas/engine/pull/391
Not sure if 2nd is a bug though... maybe in some situation you want particles to persist on spawned positions, but only start simulating since some event? You can always control visibility separately.
