### ISSUE TITLE
`GlbContainerResource` is not public API

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#3872]
Currently, `GlbContainerResource` does not appear in the API reference manual. So we have no public docs for functions like `GlbContainerResource#instantiateRenderEntity`. This is despite the viewer and 25 engine examples using this function. And as a result, it does not appear in the TypeScript declarations.

However, I would argue that this function is not named or located (source-wise) correctly. All other resources do not have `Resource` appended to the name. e.g. `Model`, `Texture`, `Material`, etc. And all of those resources appear in the relevant subsystem folder (e.g. `graphics`, `scene`, etc). I would have thought it should be `GlbContainer` in `scene`, perhaps. That said, the `scene` layer doesn't otherwise know what a GLB is, so I'm not completely comfortable with that either.

**Comment by yaustar** [comment]
We have a page for this now: https://developer.playcanvas.com/api/pc.ContainerResource.html
