### ISSUE TITLE
Graphnode findByName method should be nullable in TS definition

### ISSUE THREAD

**Issue by membla** [playcanvas/engine#3880]
I would assume the same should apply for other methods whose return type is a singular `GraphNode`

**Comment by willeastcott** [comment]
Fascinating. I just learned that if you place a `?` before a type in JSDoc, you define a nullable type:

https://jsdoc.app/tags-type.html

I'll have to try it out.

**Comment by willeastcott** [comment]
So it works for the TypeScript declarations:

```typescript
    /**
     * The shader definition for the fullscreen quad. Needs to be set by the custom post effect
     * (default is null). Used when calling {@link drawFullscreenQuad}.
     *
     * @type {?Shader}
     */
    shader: Shader | null;
```

But I lose the `null` in the generated JSDocs. Before:

![image](https://user-images.githubusercontent.com/697563/148431882-f7c22698-06d7-4fd5-908e-53edc44b3003.png)

After:

![image](https://user-images.githubusercontent.com/697563/148431937-d6a89ddb-768f-4556-bdad-8def32e754c1.png)

**Comment by willeastcott** [comment]
I think I will see if the JSDoc `?` operator is something we can adopt later. For the time being, I've audited the API and ensured all nullable return values are now marked as such: https://github.com/playcanvas/engine/pull/3882
