### ISSUE TITLE
Clone() doesn't respect the disabling of a render component

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/engine#3888]
If you clone an entity with a disabled render component, this component is enabled after cloning. Disabling the component by script after cloning is a temporary solution.

**Comment by yaustar** [comment]
Can you please provide a simple repro project for this?

**Comment by albertvanveen** [comment]
https://playcanvas.com/editor/scene/1308016

**Comment by yaustar** [comment]
Bump: https://forum.playcanvas.com/t/bug-with-cloning-entities-with-render-disabled/24278
