### ISSUE TITLE
Stencil buffer does not work in WebXR AR

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3917]
Forum: https://forum.playcanvas.com/t/stencil-buffer-not-working-in-webxr-ar-image-tracking/23902
Project fork: https://playcanvas.com/project/872788/overview/f-webxr-stencil-buffer

Stencil buffer works until the user enters AR

**Comment by yaustar** [comment]
Could be related to: https://github.com/playcanvas/engine/issues/3031

**Comment by mvaligursky** [comment]
Fixed by https://github.com/playcanvas/engine/pull/4038
