### ISSUE TITLE
Ignore Mip options for textures with size non power of 2

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#392]
Currently it is a user responsibility to set Mip/Map/Mag options on texture to "none" if texture size is not a power of 2.
But it makes sense to have a check on engine level too, and just ignore Mip/Map/Mag settings for those textures, that way there would be no ugly warnings in console.

**Comment by guycalledfrank** [comment]
Fixed in https://github.com/playcanvas/engine/pull/653
