### ISSUE TITLE
Bone scales the model and rotates it but appears ok inside the editor

### ISSUE THREAD

**Issue by lukasharing** [playcanvas/engine#3924]
Inside the editor
![image](https://user-images.githubusercontent.com/964739/151126745-40e30133-7cdf-44d0-8b34-43fde9c49bd7.png)

Inside the game appears rotated and scaled up.
![image](https://user-images.githubusercontent.com/964739/151127056-23511f4c-3114-4b57-85ee-c1836871f4f7.png)

Blender Tree
![image](https://user-images.githubusercontent.com/964739/151126892-a79a1226-c0b6-4ee9-9f63-1e3dc0d50c27.png)

**Comment by lukasharing** [comment]
It works if the bone gets removed

**Comment by lukasharing** [comment]
Removing the modifiyer "Armature" Seems to not transform the model but the animation seems to not work

**Comment by yaustar** [comment]
It could be an animation setup issue. Can you please post this on the forums with a small project that allows us to take a look? https://forum.playcanvas.com/

**Comment by yaustar** [comment]
Will close this issue as we will take a closer look on the forums :)
