### ISSUE TITLE
Large dark surfaces with directional light has banding at certain angles

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3944]
![image](https://user-images.githubusercontent.com/16639049/151447180-3c460b1a-6ab1-4a09-ac26-f7e427cefb03.png)

Project: https://playcanvas.com/project/875481/overview/light-banding

To reproduce:
- Fork the project
- Change the 3D view from Perspective to Camera
- Notice the circular banding of light on the surface from the material

**Comment by albertvanveen** [comment]
![image](https://user-images.githubusercontent.com/52896137/151447879-ff2bfc4e-2373-4ed4-a5e7-b997b36e4d65.png)

**Comment by mvaligursky** [comment]
That's the 8bit monitor which cannot display smooth gradients here. I tried Unity and get the same results.
The darker the image, the more banding you see.
To fix it, you need monitor that can display 10 bit colors, and also render to HDR (10-10-10-2) framebuffer.
