### ISSUE TITLE
PlayCanvas not running on certain iOS devices

### ISSUE THREAD

**Issue by tizkzks96** [playcanvas/engine#3951]
This issue tracker is **only** for bug reports and feature requests. For general support/help, visit https://forum.playcanvas.com

For bug reports, include:

### Description

1. I tested it with a device with a specific ios device and ios version combination. When I connect the project to local hosting, the scene is not received and the retry is displayed and an error "A problem repeatedly occurred on localhost.index.html" is displayed.
2. project : https://playcanvas.com/project/831153/overview/simple_orbit (But You can use any project.)
3. device & version (Versions I found): 
    - iPhone 12 Pro Max & 14.5
    - iPhone 12 mini & 15.3
    - iPhone 11 Pro Max & 14.5

4. It happens the same on real devices and on the simulator.
5. It is not browser affected.
![image](https://user-images.githubusercontent.com/11674965/151540794-6bba8ca9-8771-4606-8aeb-be765a1fb090.png)

### Steps to Reproduce

1. Download any project
2. project to self local hosting
3. Access the hosting site with an ios device

I think it's a fatal error, so I hope you'll raise the priority. thank you

**Comment by yaustar** [comment]
Odd that it is only on those devices

**Comment by yaustar** [comment]
Having trouble finding a device or simulator to crash :( 

![Uploading image.png…]()

**Comment by yaustar** [comment]
Can you try against an older version of the engine please?
https://launch.playcanvas.com/1323005?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.50.2.js

And against the current stable
https://launch.playcanvas.com/1323005?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.51.5.js

Do both crash for you?

**Comment by tizkzks96** [comment]
It seems to be the same symptom.
I've been testing since version 1.0.0.

Occasionally it will finish loading but open very slowly. Also the orbit camera doesn't work.

Again, this only reproduces on specific devices and os.

![image](https://user-images.githubusercontent.com/11674965/151563530-265a0a91-67f1-4db8-ad41-3407f93240aa.png)

![image](https://user-images.githubusercontent.com/11674965/151563958-f1557f8d-9bf1-4727-b9af-299585894668.png)

**Comment by slimbuck** [comment]
I reproduced very slow load and render on 12 Pro Max simulator running ios 14.5.

From a quick profile it seemed like all the time was spent in 'DrawElements' call so might be something webgl related.

I also notice the rendered cube has strange markings which also points to drawelements being a possible cause.

**Comment by tizkzks96** [comment]
So what can we do?

**Comment by slimbuck** [comment]
I'm not sure. It doesn't just happen in published builds either. Even the launch page running 14.5 simulator has very slow load and spends most time in drawElements.

**Comment by yaustar** [comment]
We are a little stuck where were can't reproduce the crash on a device, even on the ones that you've listed above. We are continuing to investigate but until we can reproduce the crash reliable, we are stuck :(

**Comment by slimbuck** [comment]
Might be related to https://bugs.webkit.org/show_bug.cgi?id=218949

**Comment by tizkzks96** [comment]
![image](https://user-images.githubusercontent.com/11674965/151661680-ee4aef0d-88c6-4523-ad21-558f74893032.png)

I mentioned local hosting, but it seems that you played playcanvas. Can you try local hosting?

**Comment by yaustar** [comment]
@tizkzks96 It shouldn't make a difference unless there's something REALLY old about your local server setup. I've tried it on both during testing with Python's Simple Server and could not reproduce the issue

**Comment by yaustar** [comment]
Another confirmation on Discord for iOS 12 devices.

https://discord.com/channels/408617316415307776/408617316415307778/938206057224863746

> Looking at the iPhone 12+ crash discussion above, we built a PlayCanvas site for mobile and desktop for an event in December last year. The site was working fine for weeks, but just a few days before the event we started getting the crash screen on new iPhones. Not on iPads or desktops or Androids. After digging around, we managed to isolate the problem to a custom built shader. Removing it from the project solved the crash. And we're 100% sure the site used to work on this particular iPhone model, and then suddenly it didn't
> 
> This is the project  https://morphosys.live/
> This is the desktop version that still has the shader in question, it's used for the cells
> The shader related files are called "SubsurfaceScattering..."


https://discord.com/channels/408617316415307776/408617316415307778/938160003058122792

> So uh, I was finally able to pin down the issue with ios. It only occurs on pretty new iPhones (~iPhone 12 +)
> It looks like it was actually an issue with trying to render to multiple render targets in a single scene. I'll try and reproduce the issue with a new project and create a forum post about it when I've got the time

Maybe it's related to the increased resolution on the iPhone 12 and 13 devices?

**Comment by tizkzks96** [comment]
![image](https://user-images.githubusercontent.com/11674965/152295144-a32b7d60-5ca1-4876-b541-830eb78c0e23.png)

![image](https://user-images.githubusercontent.com/11674965/152295315-6bf7f1cc-fe24-4f42-89e1-a41581a704bc.png)

three js : https://threejs.org/examples/#webgl_animation_keyframes


It doesn't seem to have anything to do with the increased resolution. Please refer to the table that summarizes the issues.
I used iphone 8 pro simulator.

There seems to be a problem with the rendering side of webgl.

I want to get a clear answer whether it is a playcanavas issue or a webgl issue.

Please use the same iphone 8 pro and iOS 14.5 when reproducing. Other iOS doesn't have the same issue.

**Comment by yaustar** [comment]
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/16639049/152520584-f38aa493-3011-4250-8285-0d3419e1c480.png">

Renders correctly on iOS 14.5 and iPhone 8
<img width="466" alt="image" src="https://user-images.githubusercontent.com/16639049/152520516-020672fe-ae10-42c7-b857-32333e237a16.png">

**Comment by yaustar** [comment]
Are you seeing this issue on real devices?

**Comment by yaustar** [comment]
It's really odd as I'm in the state where we can't reproduce the issue locally

**Comment by tizkzks96** [comment]
Can you directly access the url below on iOS 14.5 and iPhone 8/12 Pro Max/11 Pro Max devices?

https://playcanv.as/p/bV88Uw9F/


It's really weird...

As a result of my research, it seems that there are reports of webgl bugs on iPhones. Have you never heard of it?

**Comment by yaustar** [comment]
> As a result of my research, it seems that there are reports of webgl bugs on iPhones. Have you never heard of it?

There area a number of WebGL related issues on WebKit including the one that was linked above by Donovan: https://bugs.webkit.org/show_bug.cgi?id=218949

> Please check if the issue below is also related.
> https://developer.apple.com/forums/thread/662251

That is with a BETA version of iOS so unless that's the version you have installed, I wouldn't use that forum thread as reference.

> I tested it with the m1 and the intel chip mac mini and the rendering didn't break on the intel chip mac mini. But the fps is coming out close to zero. I'm guessing it's a memory leak or etc.

Simulators are not 100% accurate and this type of thing should be done on a real device. We have not had any other reports of this particular FPS issue on real devices.

> I need to check whether it is a playcanvas issue or a webgl issue.

We are unable to reproduce the issue or have any other reports come in about this so currently, it's an issue that is localised to you and your devices.

**Comment by tizkzks96** [comment]
Same problem with real devices. I'm referring to the simulator to introduce a reproducible environment.

There is an issue where fps or render or load cannot be done on the actual device below.

- iPhone se 2 /15.2.1
- iPhone 13 mini / 15.1.1
- iPhone 12 mini / 15.3

Please test it with the above device or test it with the simulator.

The reason I will tell you about the chip is because the phenomenon that appears depending on the server environment is different.
Can you tell me about the specs of your mac?
I will also test in an environment similar to yours.

Again, this is not just a simulator problem.

**Comment by yaustar** [comment]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/16639049/152788892-705e6c24-9147-4b29-8886-e7b87570c11e.png">

**Comment by tizkzks96** [comment]
Yes I tested it using a simple python server.

I also tested it with the nginx server.

**Comment by tizkzks96** [comment]
> 예, 간단한 Python 서버를 사용하여 테스트했습니다.
> 
> 또한 nginx 서버로 테스트했습니다.

**Comment by tizkzks96** [comment]
> 예, 간단한 Python 서버를 사용하여 테스트했습니다.
> 
> 또한 nginx 서버로 테스트했습니다.
> 
> 다른 webgl 도구에서 제공하는 서버도 테스트하고 playcanvas 호스팅 서버를 사용해 보았습니다.

**Comment by yaustar** [comment]
If all the above is having trouble then it's unlikely to be a PlayCanvas specific issue unless we all are making the same error.

Therefore, it's most likely iOS/WebKit or something specific to your devices.

**Comment by tizkzks96** [comment]
Issues occurring in the simulator and issues occurring in real devices were different.
In conclusion, the issue that occurred in the actual device was the problem.
This was an issue that occurred when the playcanvas default canvas size was different when running in nginx. The above was not the only cause.

We will reopen when we find the conditions for reproduction. Until then, I will close.

Thanks for looking for it together.

**Comment by yaustar** [comment]
@tizkzks96 could be related to this issue? https://github.com/playcanvas/engine/issues/3592

**Comment by RipcordDev** [comment]
I came to this page because I'm running into the same issue.  

I have access to 3 iPhones. 

- iPhone 13 / iOS 15.2
- iPhone 13 / iOS 15.1.1
- iPhone 11 / iOS 14.6

I'm currently working with 2 separate but very similar projects.  Project A runs fine on all 3 devices, Project B only runs on the iPhone 11.  Opening the URL for Project B presents the "A problem repeatedly occurred"  error.  I've had no issue running either project on desktop browsers or a bunch of Android devices.

After a lot of trial and error and comparing the two projects I found the cause of the issue.

Project A uses the following settings:
- Resolution Width: 1920
- Resolution Height: 1080
- Resolution Mode: Auto

Project B uses the following settings:
- Resolution Width: 2560
- Resolution Height: 1440
- Resolution Mode: Auto

Changing the resolution width and height in Project B to match Project A solved the issue, confirmed on both iPhone 13's.  Reverting the settings back to the larger resolution causes the error to appear again.

It would seem that in my case, the issue is definitely related to [#3592](https://github.com/playcanvas/engine/issues/3592) @yaustar

**Comment by tizkzks96** [comment]
I think it's the same as [#3592](https://github.com/playcanvas/engine/issues/3592)@yaustar.

**Comment by yaustar** [comment]
On iOS, they are restrictive about how large canvas' can be. Any larger and it crashes the tab

**Comment by seanhalls3** [comment]
Certainly I am exeperiencing this as well with iPhone 13 and 14 Pro Max

**Comment by willeastcott** [comment]
@seanhalls3 What specific content is not loading on those devices for you?
