### ISSUE TITLE
Move `Texture#getDds` out of the engine

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#3960]
Currently, the Editor prefilters cubemaps from 6 PNG files (RGB or RGBM). The generated texture then calls `Texture#getDds` which is very specific to what the Editor needs (it can only generate a DDS representation for RGBA8 textures). This DDS is then added to the project.

I would argue that this function does not belong in the `Texture` API. Instead, it should move to the Editor codebase, IMHO.

**Comment by Maksims** [comment]
While it is used only by the editor, it was previously possible for engine-only developers to create a tool for generating prefiltered cubemap for later usage.
What would be a recommended way to prefilter and save the DDS file for engine-only users?

**Comment by Maksims** [comment]
Thank you a lot for such a good explanation. This makes perfect sense.

**Comment by mvaligursky** [comment]
Also, probably worth mentioning that you can use https://playcanvas.com/texture-tool and convert HDRI textures to envAtlas png, and use that in the engine directly - that's what most of the engine examples do.
