### ISSUE TITLE
[BUG] Intensity affects all cubemaps in project

### ISSUE THREAD

**Issue by maungers** [playcanvas/engine#3979]
![image](https://user-images.githubusercontent.com/22077882/152401588-1cb9f25e-854f-4b9c-b1fc-c0e6b4393a10.png)
![image](https://user-images.githubusercontent.com/22077882/152403327-a68839fd-b9ca-4122-af1f-d7ef36a96170.png)

https://playcanvas.com/editor/scene/1327573

1. Open settings.
2. Set intensity value to 0.
3. All cubemaps in the project are now black.

**Comment by yaustar** [comment]
Moved to engine as it looks like an engine issue?

**Comment by slimbuck** [comment]
Hi @maungers, thanks for logging this.

Looks like a horrible bug indeed, will investigate.
