### ISSUE TITLE
Examples browser iframe rollup bundle

### ISSUE THREAD

**Issue by ellthompson** [playcanvas/engine#3987]
The examples browser iframe uses a bunch of different scripts including the PlayCanvas engine and a set of polyfills for ie11. We should explore using a rollup bundle to minimise the network cost of downloading these.

**Comment by mvaligursky** [comment]
@ellthompson - is this still relevant?

**Comment by ellthompson** [comment]
Closing this as all scripts are now bundled with rollup.
