### ISSUE TITLE
Deleting Entity with Collision Component (Mesh) but without RigidBody leads to exception.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#399]
**Reproduce:**
1. Add Entity.
2. Add Collision Component.
3. Set type to `Mesh`, and set mesh asset.
4. Disable/Enable or Delete Entity.

**Issue:**
It will assume that there is a rigidbody, and call rigidbody component system methods, which will lead to exceptions.

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/8dfa8b40d62a9eb664b311e4945c1f9b6d38f22d
