### ISSUE TITLE
TypeScript declarations issues with v1.52.1 

### ISSUE THREAD

**Issue by pavle-goloskokovic** [playcanvas/engine#3995]
TS defs of the current version of the engine are noticeably worse and less accurate than of the previous version.
Major concern is type inaccuracy and great number of `any` types used all over. Here are some concrete problems:

- `ModelComponent` `asset` property should accept `Asset` values.

``` 
/**
* The asset for the model (only applies to models of type 'asset') can also be an asset id.
*
* @type {Asset|number}
*/
set asset(arg: number);
```

- `ScriptType` methods are defined as properties, causing issues when extending and overriding methods:

```
TS2425: Class 'ScriptType' defines instance member property 'update', but extended class defines it as instance member function.
TS2425: Class 'ScriptType' defines instance member property 'initialize', but extended class defines it as instance member function.
```

defs:
```
update: (dt: number) => any;
initialize: () => any;
```
also notice return types `any` where they should be `void`.

- Classes have odd names and aliases:

```
type Asset$7 = Asset$6;
type AssetRegistry$a = AssetRegistry$c;
type Application$h = Application$7;
type ResourceHandler$g = ResourceHandler$h;

declare class Material$2
...
```

- `Material` class `clone()` method is declared to return `Material`, causing type mismatch when called on subclass such as `StandardMaterial`. This was not previously an issue.

- Most private properties are not declared as private, e.g. `Entity` class:

```
readonly sprite: SpriteComponent;
_batchHandle: any;
c: {};
_app: Application$7;
_guid: string;
_destroying: boolean;
_template: boolean;
```

- `ContainerHandler` methods' attributes are all defined as `any`, previously defined with correct types.

```
_getUrlWithoutParams(url: any): any;
_getParser(url: any): any;
load(url: any, callback: any, asset: any): void;
open(url: any, data: any, asset: any): any;
patch(asset: any, assets: any): void;
```

- Callbacks' types are not exported:

```
type resourceHandlerCallback$1 = (err: string | null, response?: any) => any;
```

- `ResourceHandler` `patch()` method is not declared as optional.

- `TS2339: Property 'stop' does not exist on type 'SoundInstance$1'.`

**Comment by willeastcott** [comment]
This is great. Thanks for compiling this list @pavle-goloskokovic. I'll be taking a look at fixing all this sometime during this week.

**Comment by willeastcott** [comment]
A little update:

* The `ModelComponent` types have been improved: https://github.com/playcanvas/engine/pull/4002
* `Material#clone` actually should return a `Material` and it's right that you should cast it as appropriate.
* Classes have the $ suffixes because of Rollup. But they are aliased to the correct names at the bottom of the playcanvas.d.ts file. I'm considering also including the unbundled type declarations in the NPM package that will not have the aliasing.
* The old process for generating `playcanvas.d.ts` relied on the code explicitly saying what you want included. The new process includes everything and we must explicitly say what's private. This is a pretty massive job and I suspect that we won't fully mark everything that is private on the final release of 1.52.x. But hopefully this won't cause major problems for people.
* The `SoundInstance` and related types have now been improved: https://github.com/playcanvas/engine/pull/4008

TODO:
* I'm aware of a problem with `ScriptType`. I'll investigate.
* Yes, `ResourceHandler` needs fixing.
* I'll look into the callbacks.

**Comment by pavle-goloskokovic** [comment]
> * `Material#clone` actually should return a `Material` and it's right that you should cast it as appropriate.

I agree with the above, but consider this example:

```javascript
const sm = new pc.StandardMaterial();
const clone = sm.clone();
```

What should be the type of `clone` constant?

**Comment by willeastcott** [comment]
You would do:

```
const sm = new pc.StandardMaterial();
const clone = sm.clone() as pc.StandardMaterial;
```

**Comment by kungfooman** [comment]
He is pointing at the change introduced here:

https://github.com/playcanvas/engine/commit/130dca17c71b006702662b20568b3e3ffef5ce2c#diff-3d28fa0b12934d0b6f4314eb2637fca0e13c4f2e191ddce393fc8d473c27a06e

`StandardMaterial#clone` used to return the type from the initial instance, but its "shadowed" by just relying on `copy` now (in `Material#clone`).

**Comment by willeastcott** [comment]
Yeah, I know. `clone` now lives on the `Material` base class. So this really doesn't have anything to do with the switch in how we generate the TS declarations. This is an API change that doesn't impact JS devs. But will require TS devs to update their code.

**Comment by kungfooman** [comment]
It still feels wrong to return the unextended type?

Its fixable with JSDoc `@template`:

```js
const a  = new StandardMaterial();
const b  = a.clone();
```

![image](https://user-images.githubusercontent.com/5236548/153422746-a24ddbfb-b1d9-487c-aee8-a9fc7cc4f8b9.png)

![image](https://user-images.githubusercontent.com/5236548/153422788-d63022e0-8325-408f-8b22-7f099011f814.png)


Over `class StandardMaterial`:

```js
@augments Material<StandardMaterial>
```

Over `class Material`:

```js
@template T
```

`Material#clone` function JSDoc becomes:

```js
    /**
     * Clone a material.
     *
     * @returns {T} A newly cloned material.
     */
    clone() {
        const clone = new this.constructor();
        return clone.copy(this);
    }
```

And then the typing is on par with what JS is doing here.

**Comment by pavle-goloskokovic** [comment]
You can also consider this:
https://www.typescriptlang.org/docs/handbook/advanced-types.html#polymorphic-this-types

**Comment by willeastcott** [comment]
Some more improvements here: https://github.com/playcanvas/engine/pull/4019

That PR removes or makes private some `Entity` properties/functions. Definitely getting closer to a new, releasable set of types.

**Comment by willeastcott** [comment]
`ScriptType` functions as properties issue fixed: https://github.com/playcanvas/engine/pull/4023

I'm tentatively estimating a couple of days before we can publish 1.52.2.
