### ISSUE TITLE
Add engine sourcemaps to code.playcanvas.com

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#3997]
Now that we have sourcemaps available, we should consider uploading them to code.playcanvas.com (at least the debug verison) to make issues easier to debug in the launch tab of the Editor

**Comment by yaustar** [comment]
Requested by @michael-graves-dojo here: https://github.com/playcanvas/engine/pull/4099#issuecomment-1063034953

**Comment by mvaligursky** [comment]
I believe this has been done for the debug engine, using inline sourcemaps.
@slimbuck ?

**Comment by slimbuck** [comment]
Correct
