### ISSUE TITLE
Previously used material asset deleting leads to materials disappear.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#400]
**Reproduce:**
1. Upload model
2. Create entity
3. Set model component to uploaded model
4. Create new material and make it slightly different from already existing one on model
5. Apply new material on model asset (asset, not override)
6. Apply back old material
7. Delete new material asset

**Issue:**
Old material will be replaced with default one (empty).
Assuming asset `remove` event are not properly removed after asset been changed on model asset.

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/5760452b90f563ce3133bcd7a2e4416aab452696
