### ISSUE TITLE
WEBGL_debug_renderer_info is deprecated in Firefox

### ISSUE THREAD

**Issue by rpaladin** [playcanvas/engine#4021]
<img src="https://cdn.discordapp.com/attachments/408617316415307778/941834682880905236/unknown.png">

I get this error in Firefox in any PlayCanvas Editor project, even in an empty project.
Note: I am on the latest Firefox edition, so I don't believe it's an outdated browser issue.

**Comment by mvaligursky** [comment]
I can repro it as well, which is strange as based on this, the extension is supported:
https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_debug_renderer_info

**Comment by willeastcott** [comment]
This is 100% fine. Firefox is just saying that the extension will no longer work soon. PlayCanvas queries it (since some apps use the queried info to influence things like what resolution to render at) but the engine doesn't rely on it itself.
