### ISSUE TITLE
Collision mesh system implementation issue

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#4026]
At the moment, when recreating the shape using a render asset, a render asset is passed to `loadAsset()`, when it should be an id of the asset:
 https://github.com/playcanvas/engine/blob/e7a6f50ec200c65195eee7f1f1d31c8ba33dc5a0/src/framework/components/collision/system.js#L423-L432

https://github.com/playcanvas/engine/blob/e7a6f50ec200c65195eee7f1f1d31c8ba33dc5a0/src/framework/components/collision/system.js#L437-L442

**Comment by mvaligursky** [comment]
Thanks! Would you have any repro steps / repro project handy?

**Comment by mvaligursky** [comment]
This seems to work correctly to me - data.asset and data.renderAsset are ids, not assets themselves. The debugger confirms this:
![Screenshot 2022-02-23 at 12 13 22](https://user-images.githubusercontent.com/59932779/155317683-3b34e866-22cf-4acc-be2f-73b4462a124b.png)

If you have some repro case which does not work, please reopen the ticket with the details.

**Comment by LeXXik** [comment]
Hey, sorry for late reply, just got time to look into it again. I tried to repro in a new project with a simple mesh as a collider, but it behaves as in your screenshot - the `renderAsset` contains the id, rather than a render asset object. I will try to see why is it different in the production project.

**Comment by LeXXik** [comment]
Tried to replicate the issue from the production project, but got stuck with #3638 crash. We can return to this one, after we find a solution for the preloading a collision mesh issue.
