### ISSUE TITLE
Instantiated template attached to first application

### ISSUE THREAD

**Issue by Sarletor** [playcanvas/engine#4027]
Related to #4024 

The issue is that when a template instantiated, entity is attached to the first created app

1. Create app 1, template handler will create new Template with attached app 1 https://github.com/playcanvas/engine/blob/bb5aa65caa880ab546ce9de456ef5bc195533f74/src/resources/template.js#L34
2. Instantiate template. Entity attached to app 1, as needed
3. Create app 2, instantiate the same template. Entity attached to app 1

It would be better if, when creating templates, it was attached to the app from which they are created but without the need to pass the app argument in instantiate function

**Comment by mvaligursky** [comment]
doesn't https://github.com/playcanvas/engine/pull/4025 fix this?

**Comment by Sarletor** [comment]
No, it's fixed parser part, when we need to pass the parser's app to the created entity.
But we also need to pass app to Template.instantiate

We are using this hack in our project. But I don't think that it's a good long-term solution
```
pc.Template.prototype.instantiate = function instantiate(app) {
    if (app) {
        this._app = app;
    }

    this._parseTemplate();

    return this._templateRoot.clone();
};
```

**Comment by mvaligursky** [comment]
Would you be able to put together some small project that demonstrates the issue?
I'm not sure I understand the step 3 .. it seems that you're trying to use resource (template) created on app1, and instantiate it on app2? I think perhaps you need to load and create that template on app2 and then instantiate it on app2?

**Comment by Sarletor** [comment]
https://github.com/Sarletor/playcanvas-issue-4027

**Comment by Sarletor** [comment]
I think it's because asset passed by reference to app.assets.add()
Maybe as solution: implement and add asset.clone() in [assets.add](https://github.com/playcanvas/engine/blob/e7a6f50ec200c65195eee7f1f1d31c8ba33dc5a0/src/asset/asset-registry.js#L217) function

**Comment by mvaligursky** [comment]
The problem here is that you create a single Asset. When this gets loaded by app1, the resources are associated with app1 and device1 (for example vertex buffers would be created on a device that app1 owns).

When you then try to load the same asset to app2, it's internally marked as loaded, and returns the resource which is linked to app1/device1. This cannot be used / rendered on app2/device2.

The solution here is to create new asset (with the same data) for the app2, so specifically:

```
        const asset2 = new Asset(json.name, json.type, null, json.data);
        asset2.id = 123;

        app2.assets.add(asset2);
        app2.assets.load(asset2);
```
