### ISSUE TITLE
[bug] When using webxr to place objects (hit test), it's impossible to detect a tap on the placed object.

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/engine#4035]
You can check my project [here](https://playcanvas.com/project/882990/overview/webxr-hit-test).
I have tried:

1. [Frame buffer picking](https://developer.playcanvas.com/en/tutorials/entity-picking/)
2. [Entity Picking Without Collision](https://developer.playcanvas.com/en/tutorials/entity-picking-without-physics/), as suggested by @yaustar.

Related forum thread: [https://forum.playcanvas.com/t/hit-test-1-finger-to-rotate-2-to-scale/24369](https://forum.playcanvas.com/t/hit-test-1-finger-to-rotate-2-to-scale/24369).

Maybe I'm the one doing something wrong, but I've been on this for hours and I can't find a solution, so maybe it's a bug. I can't tell. I just want to be able to detect a tap on a placed object using webxr. That's all.

**Comment by mvaligursky** [comment]
It's possibly related to this https://github.com/playcanvas/engine/issues/3635

**Comment by marcusx2** [comment]
Oh no...I'm hoping I'm just doing something wrong and not that there's an actual bug involved here...

**Comment by mvaligursky** [comment]
It could be both. But I guess I would expect the frame buffer picking to work regardless of this bug I mentioned, as that happens in the screen space, and that does not depend on the camera matrix and similar.

**Comment by marcusx2** [comment]
And here I thought I had solved the problem because the template was disabled, so I enabled the template thinking the code to pulsate wasn't activating because the template was disabled. Nope....still not working. Jesus.

**Comment by willeastcott** [comment]
Should this be a doc issue for the user manual?

**Comment by Maksims** [comment]
In docs it is mentioned briefly what types of input are covered by input source.
We probably can explicitly mention: in XR session, DOM touch events will not be fired, and input source events should be used instead.

**Comment by marcusx2** [comment]
@yaustar 
> there are no DOM elements so there are no touch events fired from the browser.

I am confused now because I found this [video](https://www.youtube.com/watch?v=BdVSXV8kRWA&ab_channel=RafaTec.XR) where the guy makes the model rotate in webxr mode using touch input, but it's in threejs. How can I get this to work in PlayCanvas? I also did a lot of research that you can check at [my latest reply](https://forum.playcanvas.com/t/hit-test-1-finger-to-rotate-2-to-scale/24369/25).

**Comment by yaustar** [comment]
Looks like they are using DOM overlays https://developer.playcanvas.com/en/tutorials/webxr-ar-dom-overlay/

**Comment by willeastcott** [comment]
Here's the PlayCanvas XrDomOverlay API: https://developer.playcanvas.com/api/pc.XrDomOverlay.html

@Maksims add this.

**Comment by Maksims** [comment]
Yes, you can use regular DOM events (mouse/touch), on DOM elements that are added as XrDomOverlay. This works only for AR of course.
