### ISSUE TITLE
Inaccurate type for sound.slot()?

### ISSUE THREAD

**Issue by vmwxiong** [playcanvas/engine#4050]
The documentation for SoundComponent.slot has a return type of `SoundSlot`, but if you pass in a name of a non-existent slot, then you'll get `undefined`. Not sure if this is intentional and the possibility for it to be undefined is implied or not.

**Comment by vmwxiong** [comment]
https://developer.playcanvas.com/en/api/pc.SoundComponent.html#slot

**Comment by kungfooman** [comment]
Code: https://github.com/playcanvas/engine/blob/dev/src/framework/components/sound/component.js#L364-L376

Yes, its an inaccurate type and making the TS compiler flags stricter can show these type inaccuracies to fix corresponding type issues:

```json
{
    ...
    "compilerOptions": {
        ...
        "checkJs": true,
        "noUncheckedIndexedAccess": true,
        "strictNullChecks": true,
        ...
    }
    ...
}
```

![image](https://user-images.githubusercontent.com/5236548/155701782-80072441-9c57-4369-b607-45926ccb7ce4.png)

However, for normal use cases it is too strict:

![image](https://user-images.githubusercontent.com/5236548/155702740-3706caeb-8388-4790-b5ee-7f5a002aa5e9.png)

![image](https://user-images.githubusercontent.com/5236548/155702767-49171b1d-dc14-4abc-b0b7-43e3ece6283c.png)

The compiler isn't able to detect these false positives, but at least one can use it as a hint for potential errors for JSDoc typing.

The easiest solution is to probably just rewrite the type as `SoundSlot|undefined` and the example could make use of `?.`:

```js
this.entity.sound.slot('beep')?.volume = 0.5;
```

(Maybe good first PR)
