### ISSUE TITLE
Shadow artifact

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#4058]
Noticed a strange artifact in both Editor and Launcher (Win 11, Chrome)

https://user-images.githubusercontent.com/5677782/155851344-a68c51a6-bdfd-4b62-ab97-e0146b349168.mp4

**Comment by mvaligursky** [comment]
Try adjusting the bias on the light - it makes it go away.

**Comment by mvaligursky** [comment]
We adjusted it a while back .. but little bit is still left there .. it depends on geometry mostly, and as its mostly only visible on the sphere, its not considered a priority. Too much bias creates other issues so this is acceptable for now I think.
