### ISSUE TITLE
Particle inner extents do not apply on box shape emitter

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4061]
Project: https://playcanvas.com/project/889017

Forum post: https://forum.playcanvas.com/t/particles-inner-extents-not-working/24554

> Hi everybody
> 
> I noticed a problem with the particle system. I wanted an are to be excluded from generating particles so I used the inner extents but unfortunately particles are still generated in that area?
> 
> this is a sample project: https://playcanvas.com/editor/scene/1347650
> 
> ![image](https://user-images.githubusercontent.com/16639049/155994432-a0a5eecb-9e04-488e-83db-4f855a3990dc.png)
> 
> As you can see in the image I created a particle system and the emitter extent is (30, 1, 30). and the inner extent is (25, 1, 25) so it shouldn’t generate any particles in that inner extent area, how ever it still does that.
> am I doing something wrong or is this a problem with playcanvas?

**Comment by mvaligursky** [comment]
I cannot reproduce the issue. The box has dimensions of 30 x 1 x 30 .. and the particles generate on all faces, so it seems they're inside. But they're just on top / bottom face. Change the settings to this to understand, the inside of the cube is empty:
![Screenshot 2022-06-20 at 13 52 08](https://user-images.githubusercontent.com/59932779/174606327-8229349e-85ca-4462-88ab-1310f969ead7.png)

**Comment by yaustar** [comment]
Oh, top face as well, that makes sense
