### ISSUE TITLE
Build 1.52.3 - Warnings in Launcher 

### ISSUE THREAD

**Issue by flyingbaba** [playcanvas/engine#4114]
On a latest build Build 1.52.3 we are getting a lot of warning messages like: 

- Entity has no component with name element
- Entity has no component with name scrollbar

<img width="305" alt="Screenshot_a2" src="https://user-images.githubusercontent.com/10512039/158185817-f1bae7b9-925b-4d8c-8048-d4cee2a16cef.png">

### Steps to Reproduce

1. Locate https://playcanvas.com/project/873803/overview/sprite-load--render-issue (public project for issue #3922)
2. Open Editor 
3. Hit Launch
4. Open the dev console to see the same issues

P.s.: With &use_local_engine= and a few previous engine versions works as expected without any warnings.

**Comment by jpauloruschel** [comment]
I've confirmed this issue is related to this change: https://github.com/playcanvas/engine/commit/5d0fbff7e6bdb0f8e75f44e54d6f5e753e55750c
Looking into it now.
