### ISSUE TITLE
Application destroy doesn't clear all memory

### ISSUE THREAD

**Issue by OlegGedzjuns** [playcanvas/engine#4135]
After each application create/destroy cycle extra heap memory is used.

https://github.com/OlegGedzjuns/multi-application-destroy

1. npm install
2. npm run start

**Comment by yaustar** [comment]
Have you find any clues of which parts of the engine aren't being cleaned up properly?

**Comment by OlegGedzjuns** [comment]
No, unfortunately I did not see anything unusual in the memory profiler

**Comment by mvaligursky** [comment]
I'm not sure how much these number represent memory that is not released, but if they do, there have been some improvements:

<img width="302" alt="Screenshot 2022-11-17 at 15 29 17" src="https://user-images.githubusercontent.com/59932779/202488100-38b44c8d-111a-42bb-9ada-0726168b041c.png">

**Comment by mvaligursky** [comment]
@OlegGedzjuns - could you please check the status on the engine 2.1.0? There were many deallocation changes since the last update 2 years ago.

I'll close this ticket, but please re-open it when you still find some leaks in 2.1.0, thanks!
