### ISSUE TITLE
Particle system component should have sensible defaults

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#416]
If you add a particlesystem component to an entity with no options set, it should still display something sensible. Right now, you don't see anything, which makes it hard to get to the point where you start iterating options to get the effect you want. I suggest the same defaults that are used when creating a particle system component in the Editor.

**Comment by guycalledfrank** [comment]
Critical part is fixed here: https://github.com/playcanvas/engine/pull/417
Not sure about other parameters though.

**Comment by willeastcott** [comment]
I'm happy to have this closed for now then, since at least _something_ is now visible.
