### ISSUE TITLE
Remove WebVR API support from the engine

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#4176]
Today, everyone should be targeting AR/VR via the engine's WebXR support. WebVR is now only supported by Firefox on Windows:

https://caniuse.com/webvr

I believe that now is a suitable time to strip this functionality from the engine codebase. This would involve removing the files in `src/vr` and stripping the creation and management of the `VrManager` from the `Application`.

I would move a minimal set of API into `deprecated.js` that always returns false for availability of WebVR so existing apps just fail to enter VR (via WebVR) instead of crashing.

Hey @Maksims, do you see any problem with this?

**Comment by Maksims** [comment]
Don't see a problem with it at all. Knew it will come one day.
Deleting code - always feels nice :)

Worth kicking out thinking about Internet Explorer support as well, recently saw Babylon.js looking into dropping its support (which is Microsoft them self), as Microsoft is not supporting IE anymore too, and fully stop patching it by June this year.

**Comment by willeastcott** [comment]
I'll spin up a new issue about IE11 support. Thanks!
