### ISSUE TITLE
Shader uv expression error, SPRITE_RENDERMODE_SLICED

### ISSUE THREAD

**Issue by Casval111** [playcanvas/engine#4192]
1. src\graphics\program-lib\programs\standard.js
 function _getUvSourceExpression
if (isMainPass && options.nineSlicedMode === SPRITE_RENDERMODE_TILED) {
     expression = "nineSlicedUv, -1000.0";
}

2.  standard\opacity.frag.js
#ifdef MAPTEXTURE
 dAlpha *= texture2D(texture_opacityMap, $UV, textureBias).$CH;
 #endif

3.  
#ifdef MAPTEXTURE
dAlpha *= texture2D(texture_opacityMap, nineSlicedUv, -1000.0, textureBias).a;
#endif

**Comment by mvaligursky** [comment]
This has been fixed now, and fix released.
