### ISSUE TITLE
Shall `for-of` loops be transpiled into huge iterators via `_createForOfIteratorHelper`?

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#4196]
Example code is:

```js
		const model = new Model();
		const skinInstances = [];

		for (const skin of glb.skins) {
			const skinInstance = new SkinInstance(skin);
			skinInstance.bones = skin.bones;
			skinInstances.push(skinInstance);
		}

		model.graph = GlbContainerResource.createSceneHierarchy(glb.scenes, "GraphNode");
```

As it transpiles right now:

```js
			var model = new Model();
			var skinInstances = [];

			var _iterator3 = _createForOfIteratorHelper(glb.skins),
					_step3;

			try {
				for (_iterator3.s(); !(_step3 = _iterator3.n()).done;) {
					var skin = _step3.value;
					var skinInstance = new SkinInstance(skin);
					skinInstance.bones = skin.bones;
					skinInstances.push(skinInstance);
				}
			} catch (err) {
				_iterator3.e(err);
			} finally {
				_iterator3.f();
			}

			model.graph = GlbContainerResource.createSceneHierarchy(glb.scenes, "GraphNode");
```

How it IMO should be (concerning code size and performance (even though the length should probably also be cached)):

```js
			var model = new Model();
			var skinInstances = [];

			for (var _i9 = 0, _glb$skins2 = glb.skins; _i9 < _glb$skins2.length; _i9++) {
				var skin = _glb$skins2[_i9];
				var skinInstance = new SkinInstance(skin);
				skinInstance.bones = skin.bones;
				skinInstances.push(skinInstance);
			}

			model.graph = GlbContainerResource.createSceneHierarchy(glb.scenes, "GraphNode");
```

Everything together the iterators are adding 5kb:

![image](https://user-images.githubusercontent.com/5236548/163364677-08b5caf7-70b3-4a3c-bb0a-eca702beec47.png)

It can be disabled via:

```js
const es5Options = {
    babelHelpers: 'bundled',
    babelrc: false,
    comments: false,
    compact: false,
    minified: false,
    presets: [
        [
            '@babel/preset-env', {
                loose: true,
                modules: false,
                targets: {
                    ie: '11'
                }
            }
        ]
    ],
    plugins: [
        [
            "@babel/plugin-transform-for-of", {
                //loose: true, // defaults to false
                assumeArray: true // defaults to false
            }
        ]
    ]
};
```

But if I remember correctly `for-of` loops actually were always translated into a quick/normal `for` loop, was there a decision to turn them into iterators? I can't find any PR/issue about a change.

**Comment by willeastcott** [comment]
Actually, `for .. of` loops transpile to vanilla `for` loops _if_ the array length is known by Babel. If not, it transpiles to the iterator format. At the moment, `for .. of` loops are used very infrequently in the engine codebase, I believe, and not in places that are called every frame (normally object creation/deletion for example).

**Comment by willeastcott** [comment]
I'm going to close this since the ESM builds do not transpile `for..of` loops and the UMD build is on a path to be deprecated.

**Comment by kungfooman** [comment]
Pure ESM may add some load time, at least that is what people from mathjs reported: https://github.com/josdejong/mathjs/discussions/3007

But otherwise good point and I agree, would be nice to reduce build complexity and build time :100:
