### ISSUE TITLE
Cannot use iframes on Firefox 99

### ISSUE THREAD

**Issue by stratus-dev-fr** [playcanvas/engine#4200]
### Description

Hi,

After having updated my Firefox's browser to 99th version, iframes started to not working on my Playcanvas project.
Here's my demo project : https://launch.playcanvas.com/1393301

What I have on Brave : 
https://cdn.discordapp.com/attachments/793382333339271178/965613825296584714/Screen_Shot_2022-04-18_at_4.03.21_PM.png

What I have on Safari iOS :
https://cdn.discordapp.com/attachments/942814078575984650/965614171574112276/IMG_7034.PNG

What I have on Firefox : 
https://cdn.discordapp.com/attachments/793382333339271178/965614713138466836/Screen_Shot_2022-04-18_at_4.07.48_PM.png

### Steps to Reproduce

1. Go to https://launch.playcanvas.com/1393301
2. See if the iframe in front of the camera is clear

Have a good day,
Corentin

**Comment by yaustar** [comment]
I'm afraid this isn't an issue with the engine but more of the iframe implementation and/or browser  capability/version
