### ISSUE TITLE
Video textures don't render on Firefox Android 106

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4204]
Forum: https://forum.playcanvas.com/t/video-texture-does-not-work-under-ff-for-android/25344

Test project: https://playcanvas.com/project/405850/overview/tutorial-video-textures

The video texture just stays black and has the following warning:
```
WebGL warning: tex(Sub)Image[23]D: Failed to retrieve source bytes for CPU upload. [playcanvas-stable.min.js:6:323810](https://s3-eu-west-1.amazonaws.com/apps.playcanvas.com/Z0FlzPma/playcanvas-stable.min.js)
WebGL warning: generateMipmap: The texture's base level must be complete. [playcanvas-stable.min.js:6:324479](https://s3-eu-west-1.amazonaws.com/apps.playcanvas.com/Z0FlzPma/playcanvas-stable.min.js)
```

**Comment by yaustar** [comment]
Works fine on FF 99 Desktop. I've also tried disabling mipmaps on the texture and reducing the texture upload rate to once per second and neither helped

**Comment by yaustar** [comment]
No longer an issue with the latest version of FF

**Comment by marcusx2** [comment]
@yaustar This issue should be re-opened. The problem happens on Firefox for Android.

**Comment by yaustar** [comment]
Confirmed not working on build 106

**Comment by mvaligursky** [comment]
Works fine on Pixel 8 Pro, Android 126.0
