### ISSUE TITLE
MSAA render targets resolve too many times

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#4219]
By default render targets are created with `autoResolve` true.

This results in many unnecessary resolves due to forwardRenderer calling [updateEnd](https://github.com/playcanvas/engine/blob/main/src/scene/renderer/forward-renderer.js#L1391) on the device for every rendered layer, which itself autoResolves render targets.

Ideally render targets would be resolved automatically only when they are:
- dirty
- about to be used as a texture in a rendering operation

**Comment by mvaligursky** [comment]
When multi-sampled RTs are used, there could be multiple resolves taking place.
The automatic resolve takes place inside `device.updateEnd()`, which gets called by:
1. forward renderer at the end of each layer (this is to support RT being set on a layer, which is not officially supported, but still works). At the very least it should not be called when layer has no meshes and does not clear.
2. By `drawQuadWithShader` functions. Those are possibly executing resolves for each time a quad is rendered, which could be an issue if more quads are rendered to a single RT

**Comment by mvaligursky** [comment]
related to https://github.com/playcanvas/model-viewer/pull/174

**Comment by mvaligursky** [comment]
related https://github.com/playcanvas/engine/issues/2396

**Comment by slimbuck** [comment]
Another thing: the current implementation of `resolve` doesn't check first whether the render target is actually multisampled before invoking the gl function. We must either only resolve RT when `_samples > 1` or expose `_samples` so user can do the same.

**Comment by mvaligursky** [comment]
> We must either only resolve RT when `_samples > 1`

Done locally, nice one! PR later with other fixes.

**Comment by mvaligursky** [comment]
closing down, as this issue has been addressed by #4317
