### ISSUE TITLE
The generated API documentation does not indicate some properties are read only

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#4229]
For example all properties of the RenderTarget class are read only (only have getters but not setters), but the API documentation does not mention it:

https://developer.playcanvas.com/api/pc.RenderTarget.html

I believe this was displayed as ReadOnly.

**Comment by willeastcott** [comment]
The API now shows the read only properties as accessors with just a getter. For example:

https://api.playcanvas.com/classes/Engine.Texture.html#pot

Closing.
