### ISSUE TITLE
When Cubemap Asset is loaded, .ready() doesn't think it is loaded

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4246]
Example project: https://playcanvas.com/project/940344/overview/cubemap-loaded-bug

Cubemap is preloaded, script has the following code: 

```
// initialize code called once per entity
AssetReadyTest.prototype.initialize = function() {
    var readyCb = function() {
        console.log('should be called');
    };

    var asset = this.app.assets.find('Helipad', 'cubemap');
    asset.ready(readyCb);
    this.app.assets.load(asset);
};
```

If an asset is loaded when .ready is called, it should call the callback. 

https://github.com/playcanvas/engine/blob/main/src/asset/asset.js#L464

However, cubemap assets don't store the resource in `resource` but as an array in `resources` so this check in .ready is not valid for cubemaps

**Comment by slimbuck** [comment]
NOTE: this is an issue for cubemaps with no faces (cubemaps that only have prefiltered lighting data) because the faces cubemap texture is stored in `resources[0]` (which is what `resource` returns).

**Comment by yaustar** [comment]
> because the faces cubemap texture is stored in resources[0] (which is what resource returns).
```
    ready(callback, scope) {
        scope = scope || this;

        if (this.resource) {
            callback.call(scope, this);
        } else {
            this.once('load', function (asset) {
                callback.call(scope, asset);
            });
        }
    }
```
That's odd as if `resource` returns `resources[0]`, the ready call should work as it's checking `this.resource`

**Comment by yaustar** [comment]
Looking at cubemap.update, I can't see where asset.resource is set. Should it be? https://github.com/playcanvas/engine/blob/main/src/resources/cubemap.js#L93

**Comment by slimbuck** [comment]
https://github.com/playcanvas/engine/blob/main/src/resources/cubemap.js#L192

**Comment by yaustar** [comment]
> https://github.com/playcanvas/engine/blob/main/src/resources/cubemap.js#L192

That's to .resources, not .resource? Isn't .resource meant to reference .resources[0]?
