### ISSUE TITLE
Primitives with procedural material don't clone properly

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#425]
To repro:
Create an entity with basic primitive (e.g. box)
Create a pc.PhongMaterial and set it on this.entity.model.material.
Clone the entity.

Result:
The material is not cloned.

See the physics engine example to see this bug.

**Comment by daredevildave** [comment]
Why is this expected behaviour? The material is an asset. We don't clone assets when we clone entities.

**Comment by Maksims** [comment]
Material is a resource of an asset. And I believe we actually do clone materials for each model instance individually.

**Comment by vkalpias** [comment]
The problem is not that the material itself is not cloned but rather the model does not have the material of the original model.

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/7ce6c5e7fc610c9a797af10efcc36413a4fd0507
