### ISSUE TITLE
Remove uses of deprecated function string.substr()

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#4252]
There are multiple calls to this deprecated function in the codebase.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr

**Comment by kungfooman** [comment]
I highly doubt this function will ever be removed and it is way simpler on the eye than `String#substring`.

For example, this is using so much more code for the `end` argument calculations:

https://github.com/playcanvas/engine/blob/18479af56d93eeceaa062d06a78e44c179d31039/src/core/string.js#L69-L70

Compared how it would be written via `String#substr`:

```js
    const first  = string.substr(index    , 2);
    const second = string.substr(index + 2, 2);
```

So why even remove it? I would rather replace `substring` with `substr` and add a polyfill if it ever were deleted (which would break like every 2nd website and make browsers/engines alienate their users).

To get rid of this obtrusive deprecation `warning` you can simply add e.g. `substr.d.ts` in the root dir:

```ts
interface String {
    /**
     * Gets a substring beginning at the specified location and having the specified length.
     * @param from The starting position of the desired substring. The index of the first character in the string is zero.
     * @param length The number of characters to include in the returned substring.
     */
     substr(from: number, length?: number): string;    
}
```

**Comment by willeastcott** [comment]
You're right that `substr` is never likely to be removed from browsers. However, I don't feel that the additional characters required to switch to `substring` are significant. And for the price of that, we don't need to mess around with hacking `.d.ts` files or polyfills. So yeah, I'd just recommend we make the switch at some point. Obviously, this is kinda low priority! 😄
