### ISSUE TITLE
Consider OVR_multiview2 extension to speed up multiview rendering

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#4259]
The OVR_multiview2 extension is part of the [WebGL API](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API) and adds support for rendering into multiple views simultaneously. This especially useful for virtual reality (VR) and WebXR.

https://developer.mozilla.org/en-US/docs/Web/API/OVR_multiview2
https://community.arm.com/arm-community-blogs/b/graphics-gaming-and-vr-blog/posts/optimizing-virtual-reality-understanding-multiview
https://blog.mozvr.com/multiview-on-webxr/

**Comment by willeastcott** [comment]
Duplicate of https://github.com/playcanvas/engine/issues/1906
