### ISSUE TITLE
Rendering seem to fail on external GLB files (works at first load, but not second)

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#4268]
When loading new materials onto externally loaded GLB-files, the object seem to disappear after a second loading procedure.
At first load (going from one 'visually enabled' to another) it works all right, but the next time around.

Video example (have focus/emphasis on the mouse clicking 1 and 2 piece of jewelry): https://www.youtube.com/watch?v=YYGBCwv4el8

This puzzles me as quite a few debugging routes have been taken already as well (with or without refraction and with or without runtime opacity change).

Code-snip: 
`if(self.meshesModeHolders[m] === "4001" /* Cobalt */) {
                                        self.meshes[m].material = self.app.assets.get(67084159).resource; 
                                        self.setRfr=0; // set to 1===refraction at debugging
                                        self.meshes[m].material.opacity =0.68; // commented out at debugging`

My best own guess is; that it is related to the material.update()-procedure, that has issues with the layers.

`self.meshes[m].material.update();`

If so one could start thinking that there should be a limit to the 'Layers handled runtime', but there should not be according to: https://forum.playcanvas.com/t/solved-performance-and-layers/12657

I am afraid I will not let the code become free to examine, as I preserve it to be non-disclosure worthy (due to a lot of other functionality I need to hide).
My question is rather: If you know something about such material-issues relating to layers and/or GLB-files please elaborate.
Still have a hunch that this is a real bug though.

I am using Chrome browser

![image](https://user-images.githubusercontent.com/6838800/169882008-1f4b0779-6937-435c-81a4-9b1e649772e3.png)

**Comment by yaustar** [comment]
Again, difficult to tell without a build to look at and repro steps on how to get the issue.

From the video, it looks like it is flickering in and out?

Does this open with the GLB outside of your project? For example, if you load the GLB in https://playcanvas.com/model-viewer does the issue still happen?

I also recommend using https://spector.babylonjs.com/ to debug rendering issues as it shows each draw call.
