### ISSUE TITLE
UI layer's elements are not rendered if behind a model with transparent material in iphone

### ISSUE THREAD

**Issue by flyingbaba** [playcanvas/engine#4278]
We recently noticed that the UI layer's elements are not rendered if behind a model with transparent material in iphone (not sure about the ios).

Changing Blend Type does not solves an issue. 

Steps to reproduce: 

1. Open: https://playcanvas.com/editor/scene/1431046
2. Launch with Iphone: https://launch.playcanvas.com/1431046?debug=true

Iphone: 
![photo_2022-05-28_10-45-07](https://user-images.githubusercontent.com/10512039/170816073-6207e4f8-5392-4dec-8d5d-249c10fe652b.jpg)

Android:
![photo_2022-05-28_10-45-12](https://user-images.githubusercontent.com/10512039/170816075-e47c62f1-bc4e-4560-a0cd-38e69b26eedb.jpg)

Pc:
![Screenshot_4](https://user-images.githubusercontent.com/10512039/170816122-0733a703-0d7a-497a-a25e-31c6092ed2f0.png)

**Comment by slimbuck** [comment]
cc @jpauloruschel

**Comment by jpauloruschel** [comment]
Hey!
What iOS and iPhone are you using? I've just tested on an iPhone 13 iOs 15.5 Safari and Chrome and could not reproduce.

One thing you can try is to set the `Layers` property in your `Element` to be `World`, rather than `UI`.

**Comment by flyingbaba** [comment]
Tested with Iphone 5s with software version 12.5.5. This is our bottom line device. But this bug was noticed and reported few weeks ago with iPhone 13 (don't know the software version)
