### ISSUE TITLE
Particle color space: HDR vs sRGB

### ISSUE THREAD

**Issue by querielo** [playcanvas/engine#4284]
Consider not to [transform colors of particles to sRGB](https://github.com/playcanvas/engine/blob/main/src/graphics/program-lib/chunks/particle/frag/particle_end.js#L4) in case of enabled HDR as we do [here](https://github.com/playcanvas/engine/blob/main/src/graphics/program-lib/chunks/lit/frag/end.js#L13). Skybox has [the similar problem](https://github.com/playcanvas/engine/blob/main/src/graphics/program-lib/chunks/skybox/frag/skyboxHDR.js#L11)

**Comment by mvaligursky** [comment]
I had a quick look as I worked in the area, and the skybox works as expected - screenshot from my HDR test-bed:

<img width="830" alt="Screenshot 2023-12-19 at 16 07 24" src="https://github.com/playcanvas/engine/assets/59932779/65fb44dc-1b9e-4d98-87d6-6945bbed8a95">

Line 136 calls `toneMap` and `gammaCorrectOutput`, but in HDR mode with no tone mapping those are pass-through functions.

**Comment by mvaligursky** [comment]
And similarly in particle system:

<img width="991" alt="Screenshot 2023-12-19 at 16 11 16" src="https://github.com/playcanvas/engine/assets/59932779/64eb8f96-256a-4d90-9761-5d7e715293fb">

**Comment by mvaligursky** [comment]
I'll close this but please reopen this if I missed something.
