### ISSUE TITLE
For an array of JSON type script attributes, allow to set default values

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4306]
Given:
```
Test.attributes.add('testObjects', {
    type: 'json',
    array: true,  
    schema: [{
        name: 'foo',
        type: 'entity'
    }, {
        name: 'bar',
        type: 'string',
    } ],
    default: [{foo: null, bar: ""}]
});
```

It would be great if we can autofill the default values of a script type with these types rather than just have an array of 0

**Comment by kpal81xd** [comment]
You set the `default` property for each element in the schema not on the surrounding object as you have done. For your example, you would set it as

```
Test.attributes.add('testObjects', {
    type: 'json',
    array: true,  
    schema: [{
        name: 'foo',
        type: 'entity',
        default: null,
    }, {
        name: 'bar',
        type: 'string',
        default: '',
    } ],
});
```

**Comment by willeastcott** [comment]
@kpal81xd Ah yeah, makes sense.

@yaustar I'm going to close this since it appears you specified the JSON attribute incorrectly. However, if you believe there's still a problem here, please let me know.

**Comment by Maksims** [comment]
I guess there is still no way to specify default value for a whole JSON array? I guess this applies for any array-like attribute.
