### ISSUE TITLE
Shadow markup requires color attribute

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#4308]
The markup introduced in https://github.com/playcanvas/engine/pull/4302 fails at runtime unless the `shadow` tag specifies a `color` attribute.

This is because `fromString` is being passed a null [here](https://github.com/playcanvas/engine/blob/main/src/framework/components/element/text-element.js#L514).

Ideally color would be unaffected in this case, but it could also just take the global shadow color instead.

cc @querielo

**Comment by querielo** [comment]
Thanks for the report. Tried to fix it [here](https://github.com/playcanvas/engine/pull/4311).
