### ISSUE TITLE
Remove flipv code from glb loader

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#4313]
Once we are able to automatically reconvert affected glb models (or users are easily able to do this themselves), we must reintroduce the change in https://github.com/playcanvas/engine/commit/dcbfd71c36e6ee1b1adbaa3d4c8a12fdcf0f159d (reverted in #4097).

**Comment by willeastcott** [comment]
@slimbuck Reapply the commit for v2.0.0?
