### ISSUE TITLE
Shader pass bugs

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#4325]
Since the number of supported shadow types was increased from 5->6 (in https://github.com/playcanvas/engine/pull/3763), some existing code mistakingly categorises shaders incorrectly.

For example see:
https://github.com/playcanvas/engine/blob/main/src/graphics/program-lib/programs/standard.js#L295 and https://github.com/playcanvas/engine/blob/main/src/graphics/program-lib/programs/standard.js#L479

We must:
- change the constants defined at https://github.com/playcanvas/engine/blob/main/src/scene/constants.js#L631
    - redefine SHADER_PICK to be value 3
    - redefine SHADER_SHADOW to be value 4
- perhaps add helper functions to make sense of it all
- use the new helpers around the codebase instead of relying on the value `17` in the codebase
- consider renaming the defines from `SHADER_SHADOW` to `SHADERPASS_SHADOW`

**Comment by mvaligursky** [comment]
I've refactored the code in the linked PR. I have avoided the constant renames in this PR, as that would possibly create a larger conflict with shader refactoring open PR.
