### ISSUE TITLE
Regression, prefiltering cubemaps no longer possible

### ISSUE THREAD

**Issue by Mistale** [playcanvas/engine#433]
In the latest version of playcanvas-stable.js, prefiltering no longer works.
The reason seems to be a recent change inside of prefilterCubemap() in graphics_prefiltercubemap.js, where you have replaced "if(cmapsList[pass] != null)" with "if(cmapsList[pass] !== null)" in two locations.

The test no longer fails but instead causes an error during processing, probably because one of the elements of cmapsList is undefined, not null. And undefined !== null.

Please fix this asap, I guess many users are affected.
I managed to use a local version of playcanvas-stable.js in the editor and verified that I could prefilter cubemaps after changing the comparisons back to how they were before.

**Comment by willeastcott** [comment]
Apologies for the inconvenience. Fixing right now.

**Comment by Mistale** [comment]
Thank you very much, that was quick!

**Comment by willeastcott** [comment]
Fixed in 76db905c2edc770b31d844964cbbd18a17c323c7

I'm so sorry this bug affected you.
