### ISSUE TITLE
Add support for 16 bit PNGs to be used as normal maps for high resolution

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4334]
Related to: https://forum.playcanvas.com/t/16-bit-normal-maps-how-to-get-them-in/5340

Some users are having issues with 8 bit PNG and 'stepping'. Being able to use 16 bit PNGs would help a lot

**Comment by willeastcott** [comment]
I agree with what @guycalledfrank says in the thread:

> Browsers don’t load 16-bit precision data from PNGs at all. Nothing engine can do here. Suggestion: use geometry for large curved surfaces. Use normal maps for finer details.

You could potentially use some JS PNG decoder to get the data out, but this isn't something we'd be likely to add to the core engine repo (even as an example). Closing.
