### ISSUE TITLE
Engine 1.54.1 cannot handle depth softening in particle systems

### ISSUE THREAD

**Issue by nikitaosyak** [playcanvas/engine#4338]
When particle system has depth softening, weird things start to happen in latest pc engine.

this is with orthogonal camera:
https://user-images.githubusercontent.com/1550079/174116386-f8ecdff9-a0e2-40ed-88d1-bff6ccbc5a17.mp4

it seems that color map is being drawn in viewport and masking particles. here's the colormap:
![chrome_95zBj7INXw](https://user-images.githubusercontent.com/1550079/174116595-dadce968-aed3-463b-8c68-4bc850d65e28.png)

this is with perspective camera:
https://user-images.githubusercontent.com/1550079/174116454-ae1d02b0-158d-46dd-95c9-cc90ef670917.mp4

all available here: https://playcanvas.com/project/946532/overview/mystery-mask-problem

**Comment by slimbuck** [comment]
cc @mvaligursky

**Comment by nikitaosyak** [comment]
the process of discovering this was like a chapter in a detective novel

**Comment by nikitaosyak** [comment]
![image](https://user-images.githubusercontent.com/1550079/174118981-1343ffe3-e919-4f7b-9789-bde99c8157ae.png)

**Comment by yaustar** [comment]
Video of issue:
https://user-images.githubusercontent.com/16639049/174120782-8f4b0d58-807e-4b65-8a81-732d3deeb110.mp4

**Comment by yaustar** [comment]
Tried adding the requestSceneDepthMap on the camera and now it doesn't render the particles at all

https://playcanvas.com/project/946538/overview/f-mystery-mask-problem

**Comment by yaustar** [comment]
Oh actually, adding the request AND changing the near clip to be non-zero makes the particles render fine

**Comment by mvaligursky** [comment]
Closing at it seems it's working now. Please reopen if I'm mistaken.
