### ISSUE TITLE
Audiosource won't play on activate unless all assets are preloaded

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#434]
Create an audiosource component and add two assets to play. Set the component to activate (play on load).

If the second asset is not preloaded the audio of the first asset will not play. The state of the second asset shouldn't effect the state of the first.

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/8e97720e5395469557882fa0362c1e8950ac0ceb
