### ISSUE TITLE
Refactored grabpass in v1.54.1 doesn't work with sprites

### ISSUE THREAD

**Issue by dbaronica** [playcanvas/engine#4351]
Engine version 1.53.4:
We use grabpass in our blur shader to blur the background that consists of various sprites. Works ok.

Engine version 1.54.1
Using grabpass and setting camera.requestSceneColorMap(true); as required by the refactored grabpass functionality.
Meshes are affected/blurred, but sprites or UI elements are not.

**Comment by mvaligursky** [comment]
My guess here is that your sprites render after the Depth layer, and not before, and so are not part of the capture. And so the suggestion is to move those sprites to a layer (possibly a new layer) that renders before the Depth layer.

**Comment by dbaronica** [comment]
Thank you for your help. You are correct! I didn't know Depth layer is crucial for the grabpass effect, and sprites are by default rendered in World Transparent layer which is behind Depth layer. Creating a new layer that is rendered before the depth layer sorts the issue.
Thank you.
