### ISSUE TITLE
Fix programlib

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#4358]
The `programlib` object is currently included directly in `GraphicsDevice` and also exported as a public object (though not documented).

Ideally we should:
- refrain from exporting programlib publicly
- register programs in the application instead - this will aid with tree shaking

**Comment by willeastcott** [comment]
Since https://github.com/playcanvas/engine/pull/4692 was merged, what's left to do here?

**Comment by mvaligursky** [comment]
I'm still hoping to do a minor cleanup, but this can be closed as done.
