### ISSUE TITLE
`AssetListLoader` occurs twice in the codebase

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#4382]
See:

* https://github.com/playcanvas/engine/blob/3cef14e200edf1a6888224676d3f93b2d1be2686/src/asset/asset-list-loader.js#L23
* https://github.com/playcanvas/engine/blob/3cef14e200edf1a6888224676d3f93b2d1be2686/src/deprecated/deprecated.js#L1178

**Comment by mvaligursky** [comment]
What's the best thing to do here? Perhaps just remove the one from deprecated? It was deprecated for a while.
Exporting the same class name twice is not a good situation.

**Comment by willeastcott** [comment]
The deprecated version should go, presumably.
