### ISSUE TITLE
Wrong use of `this` in SceneGrab

### ISSUE THREAD

**Issue by NewboO** [playcanvas/engine#4399]
While experimenting with SceneGrab, I noticed a possibly incorrect use of `this` on these two lines.

https://github.com/playcanvas/engine/blob/24f325f078c2753ae15948450d3da4b0918932a6/src/framework/scene-grab.js#L158
https://github.com/playcanvas/engine/blob/24f325f078c2753ae15948450d3da4b0918932a6/src/framework/scene-grab.js#L306

The property `colorFormat` is defined in SceneGrab class but here `this` is the Layer so it's always undefined. However, replacing with `self.colorFormat` isn't a solution because it then fails as soon as you try to use post effects with the following error, except if the project is configured to transparent canvas:

> Can't copy render targets of different color formats

As `SceneGrab.colorFormat` depends on whether the canvas is transparent or opaque by checking `WebglGraphicsDevice.defaultFramebufferAlpha`, it ignores the fact that post effects textures format is always `PIXELFORMAT_R8_G8_B8_A8` (at least with Webgl2) and that the first post effect texture is usually the active target when rendering depth layer.

I'm not sure how it should be fixed (make post effects texture format also depends on `WebglGraphicsDevice.defaultFramebufferAlpha`? force `SceneGrab.colorFormat` to `PIXELFORMAT_R8_G8_B8_A8` and correctly use it later?) or even if it should fixed as for now it ends up working fine thanks to texture format defaulting to `PIXELFORMAT_R8_G8_B8_A8`, but relying on a happy coincidence feels unsafe for future.

**Comment by mvaligursky** [comment]
Hey thanks for pointing it out, it should definitely be `self.colorFormat`.
I'll see what can be done with this, but perhaps not before I get to refactor this one more time in order to convert it to a RenderPass at the start of the frame.I agree the format should depend on the format of the camera's render target that the depth layer is currently rendered for.
