### ISSUE TITLE
Add support for AMD FSR / Fidelity FX

### ISSUE THREAD

**Issue by maungers** [playcanvas/engine#4416]
Hi everyone!

I think, need to add an AMD FSR analog to Playcanvas.
I think it has 3 main parts: upscaling, sharpening, temporal anti-aliasing (taa).

The first two I've already tried to apply.
Examples of porting upscaling and sharpening here: https://shadertoy.com/results?query=AMD+FidelityFX.
I applied them in Playcanvas as a post effect, based on the fxaa post effect example.
I got a rendering performance gain of 0.75 of the original size.
I can't show the project with this test because it's broken (now there are attempts to implement taa, but so far without success).

It would be great to render without anti-aliasing using taa.

As for taa, it's similar to the High Quality feature in the model viewer. But AMD FSR taa solves the motion blur problem.

I think this is a very useful option that can greatly improve Playcanvas performance. And it would be great if this was implemented in Playcanvas itself, in a more professional way than my experiments :)

**Comment by mvaligursky** [comment]
Another similar thing we could investigate: https://github.com/GPUOpen-Effects/FidelityFX
