### ISSUE TITLE
Engine Examples external dependency

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#4417]
- I have some issues loading engine examples locally. It's waiting a lot / expires on this https://unpkg.com/@babel/standalone@7.16.7/babel.min.js
![Screenshot 2022-07-11 at 11 40 35](https://user-images.githubusercontent.com/59932779/178246918-0baec40f-536f-498c-8850-e0ff2f5ce6d3.png)

- also our prod engine examples get this if caching is disabed: https://playcanvas.github.io/#/misc/hello-world

I wonder if we should package this with the application instead of loading externally?

**Comment by willeastcott** [comment]
That Babel Standalone script is loaded here:

https://github.com/playcanvas/engine/blob/59ccc5ed7c136b0bfaaee1bbbbc45c89fa8dbc21/examples/src/static/index.html#L11

@ellthompson, is this actually still used? Maybe for this:

https://github.com/playcanvas/engine/blob/59ccc5ed7c136b0bfaaee1bbbbc45c89fa8dbc21/examples/scripts/iframe/index.mustache#L59-L63

**Comment by ellthompson** [comment]
Closing this as babel is no included as a script.
