### ISSUE TITLE
Improve 'Powered by PlayCanvas' log message

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#4420]
when we start some app using built debug version of engine, we get
```
Powered by PlayCanvas 1.55.0-dev 5643813bd
```

but when the app imports engine modules directly, we get
```
Powered by PlayCanvas $_CURRENT_SDK_VERSION $_CURRENT_SDK_REVISION
```

Perhaps avoid the log messages in those cases.

**Comment by kungfooman** [comment]
For the case of `version` this is possible:

```html
<script type="module">
  import p from './package.json' assert {type: 'json'};
  console.log('Powered by PlayCanvas', p.version);
</script>
```

![image](https://user-images.githubusercontent.com/5236548/178278609-dc0548ba-83a9-4bdd-b314-1ad7ab8d8399.png)

The `.git` files may be able to be parsed aswell, but I guess the binary formats make it way harder/impossible.

**Comment by mvaligursky** [comment]
Interesting idea. I tried and get `SyntaxError: /Users/mvaligursky/Snapchat/Dev/engine/src/framework/app-base.js: Support for the experimental syntax 'importAssertions' isn't currently enabled (3:49)` - I guess I'll leave this for later.
