### ISSUE TITLE
Anim event set at time 0 is fired at the start and end of a non looping animation

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4426]
Thread: https://forum.playcanvas.com/t/anim-system-issues/26559/

Project: https://playcanvas.com/project/956782

Anim Event is set on both non looping animations at time 0

The event is fired at the start of the animation and at the end

**Comment by Adolar13** [comment]
Hey, just wanted to check if there has been any progress on this issue? I frequently run into it when linking sounds to animations.

**Comment by yaustar** [comment]
Unfortunately, no progress on this
