### ISSUE TITLE
Animation stuck in initial state after calling Anim reset

### ISSUE THREAD

**Issue by Adolar13** [playcanvas/engine#4439]
Thread: https://forum.playcanvas.com/t/anim-system-issues/26559

Project https://playcanvas.com/project/957771/overview/unable-to-transition-after-reset

Repro steps:

Press P to start Punch Animation
Press R during any time of the animation to call reset() on the anim component
Animation is back in Idle
Press P again

Expected Result is that the punch animation should play again but it does not

**Comment by ellthompson** [comment]
Fixed in #5392
