### ISSUE TITLE
Console warning on specularAntialias in 1.55

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#4455]
In engine version 1.55 there are a number of materials that generate a warning in console:
```
debug.js:78 Ignoring unsupported input property to standard material: specularAntialias
```

Searching the repository for `specularAntialias`, it looks like it is used in some test assets, as well, which will probably produce the same warning.

**Comment by slimbuck** [comment]
Hi @LeXXik , thanks for reporting this. I forgot to suppress this particular warning. This message has started firing because we removed toksvig specular AA which had been broken for a while.
