### ISSUE TITLE
Any plans to support glTF?

### ISSUE THREAD

**Issue by erlend-sh** [playcanvas/engine#446]
So glTF has hit 1.0

https://www.khronos.org/news/press/khronos-finalizes-gltf-1.0-specification

It's made with WebGL engines in mind, so, is there any place for it on the PlayCanvas roadmap?

**Comment by Maksims** [comment]
Hi @erlend-sh, we've developed our own runtime format, to run efficiently to our engine, and we produce it from popular formats like fbx, collada, 3ds, obj.
First we need to find out what benefits using glTF will have comparing to our proprietary format. If there are any and they are significant, then we will consider using glTF.
If there won't be big advantage of such, then we will still support glTF for upload if it becomes popular, but will still produce our internal format from it, as it suits our engine in very efficient way.

We do have plans to improve our model runtime format, and it is in our roadmap.

**Comment by Maksims** [comment]
Feature discussed here: https://github.com/playcanvas/engine/issues/806
