### ISSUE TITLE
Engine 1.55.0 breaks skybox thumbnail renderer in Editor

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4466]
Project: https://playcanvas.com/editor/scene/1452189?use_local_engine=https://code.playcanvas.com/playcanvas-1.55.0.js

Go to CUBEMAP and select New Cubemap. Inspector preview is empty

<img width="443" alt="image" src="https://user-images.githubusercontent.com/16639049/180406378-a1022a03-19a4-48bb-b64a-36fc66b0bf12.png">

Error in console:
```
helpers.ts:111 Uncaught TypeError: e.scene._updateSkybox is not a function
    at Cubemap3dThumbnailRenderer.render (cubemap-3d-thumbnail-renderer.js:145:25)
    at e._renderPreview (cubemap-preview.js:47:35)
    at sentryWrapped (helpers.ts:87:17)
```

**Comment by slimbuck** [comment]
cc @mvaligursky

**Comment by kungfooman** [comment]
A quickfix would be:

```js
const ScenePrototype = pc.Scene.prototype;
if (!ScenePrototype._updateSkybox) {
  ScenePrototype._updateSkybox = ScenePrototype._updateSky;
}
```

![image](https://user-images.githubusercontent.com/5236548/180444699-b072ef1b-7f9a-426e-b901-e507475eeb69.png)
