### ISSUE TITLE
[BUG] glb-parser issue in 1.55

### ISSUE THREAD

**Issue by vogloblinsky** [playcanvas/engine#4472]
### Description

I have an issue while opening my project (https://playcanvas.com/project/924053/overview/3d-skate-tricks) with last release candidate (1.55), and it works fine in previous version.

![image](https://user-images.githubusercontent.com/2841805/180659975-aea6868d-9276-4a03-8368-d42c5012d862.png)

The createMorphTargetCurves function seems to be in glb-parser (https://github.com/playcanvas/engine/blob/7c8f8982a9f0d9be57565e5afc84e030dd83d48d/src/resources/parser/glb-parser.js)

**Comment by slimbuck** [comment]
Can confirm, likely related to https://github.com/playcanvas/engine/pull/4327.

**Comment by kungfooman** [comment]
I just downloaded a glb of @vogloblinsky's project which triggers this error:
[Armature_s_popshoveit_L_guy-caucasian.blend.glb.zip](https://github.com/playcanvas/engine/files/9179275/Armature_s_popshoveit_L_guy-caucasian.blend.glb.zip)
 
The validation report:

![image](https://user-images.githubusercontent.com/5236548/180730518-61e8c746-294f-410a-b86f-e53ed431ea1e.png)

I'm sure the engine shouldn't just crash with an error but error out friendly or try to parse what is possible.

In this case that would be:

```js
    const createMorphTargetCurves = (curve, node, entityPath) =>  {
      if (!outputMap[curve.output]) {
        //debugger;
        console.log("!outputMap[curve.output]");
        return;
      }
```

Then the model still loads, but I have no clue how it is supposed to look:

![image](https://user-images.githubusercontent.com/5236548/180731207-c2b9bcfc-f2c7-40a4-b7cc-c196fbfe6f38.png)

If you can share the original file (e.g. blend for Blender) it would be easier to work it out.

**Comment by vogloblinsky** [comment]
@kungfooman I just send you the model by email.

**Comment by vogloblinsky** [comment]
Just for information, there are many animations in the model, and one attached in the Armature prefixed c_, and one for the skateboard, prefixed s_

**Comment by vogloblinsky** [comment]
I use fbx format for exporting from blender and import in Playcanvas?

**Comment by vogloblinsky** [comment]
Thanks @ellthompson for this quick fix !

**Comment by ellthompson** [comment]
Closed this issue with the fix suggested by @kungfooman . Thanks to both of you for looking into this.
