### ISSUE TITLE
Shadow acne artifacts in highlight engine demo

### ISSUE THREAD

**Issue by MAG-AdrianMeredith** [playcanvas/engine#4473]
### Description

I'm seeing a lot of shadow acne artifacts on the highlight demo.  Can't recall what it looked like before (and therefore if theres a regression) but at the least it should probably be cleaned up.  Surely a simple scenario like this should work by default?

![image](https://user-images.githubusercontent.com/100127317/180729359-0fef277c-0d6f-43db-bb1c-5ac287e71af6.png)

mac book pro m1
chrome

**Comment by slimbuck** [comment]
Thanks so much for reporting! We'll investigate. (My guess would be this is related to clustered lighting).

**Comment by MAG-AdrianMeredith** [comment]
no worries unfortunately I can't recall what it looked like before but with the new default lighting switch, thats set off some alarm bells ringing

**Comment by slimbuck** [comment]
I reproduced this on PROD. Adding `app.scene.clusteredLightingEnabled = false;` fixes the shadows.

**Comment by slimbuck** [comment]
The clustered lighting shadows just appear lower precision than before. More shadowBias is required to remove acne on the example scene. I can't see or think of any obvious reason for this. Could be the difference of depth texture format (RGBA8 vs F32) or perhaps an additional rounding off error in clustered atlas depth pack/unpack.

Either way this will require @mvaligursky to investigate so handing over to him.

**Comment by MAG-AdrianMeredith** [comment]
Should we log another issue for the underlying change?  I noticed this In my app too and have avoided shadows for this reason.  switching back to old lighting has none of those artifacts

**Comment by mvaligursky** [comment]
I added a comment here: https://github.com/playcanvas/engine/issues/2780
