### ISSUE TITLE
WebGL Error when using Cubemap Renderer script v1.55

### ISSUE THREAD

**Issue by MAG-AdrianMeredith** [playcanvas/engine#4477]
### Description

We're using the "cubemap renderer" script to create a cubemap for reflection probes, upgrading from 1.53 > 1.55 they no longer work and I'm seeing WebGL errors in the log 
<img width="1440" alt="Screenshot 2022-07-25 at 14 31 03" src="https://user-images.githubusercontent.com/100127317/180789455-f82c633d-7c60-4ca9-85a9-5ae9cd84124e.png">
<img width="778" alt="image" src="https://user-images.githubusercontent.com/100127317/180789607-d3597a29-0348-4fe3-860f-4a8f98325c37.png">

**Comment by slimbuck** [comment]
We have two engine examples which use the cubemap renderer and both seem to work ok:
https://playcanvas.github.io/#/graphics/box-reflection
https://playcanvas.github.io/#/graphics/render-cubemap

**Comment by MAG-AdrianMeredith** [comment]
I still get the error but weirdly enough if I change the resolution property from 256 > 128 it works?  that makes no sense... 
![image](https://user-images.githubusercontent.com/100127317/180805020-438d88ff-019a-4a95-b138-7a1f5b28cdd0.png)

**Comment by MAG-AdrianMeredith** [comment]
it seems the more I increase the resolution the darker the reflection gets until it can't be seen at all... very strange

**Comment by MAG-AdrianMeredith** [comment]
I've managed to find a work around, it appears to be related it mipmapping.  Changing the cubemap-renderer cubeMap texture from minFilter: FILTER_LINEAR_MIPMAP_LINEAR -> minFilter: FILTER_LINEAR makes it fully resolve again.  weird

**Comment by slimbuck** [comment]
This means the cubemap's mipmaps aren't being generated/updated for some reason.

**Comment by mvaligursky** [comment]
@MAG-AdrianMeredith - would you be able to create some minimal repro project? I'd be keen to have a look. Alternatively, you could also enabled some tracing to see what happens under the hood .. this could show us if mipmaps get generated perhaps. Something like this:

```
pc.Tracing.set(pc.TRACEID_RENDER_FRAME, true);
pc.Tracing.set(pc.TRACEID_RENDER_PASS, true);
pc.Tracing.set(pc.TRACEID_RENDER_PASS_DETAIL, true);
```

**Comment by willeastcott** [comment]
@MAG-AdrianMeredith This issue has not been updated in some time. I just wanted to check if this is still an issue and whether you had a response for @mvaligursky. Thanks! 😄
