### ISSUE TITLE
Different scaling of meshes in particle systems

### ISSUE THREAD

**Issue by vkalpias** [playcanvas/engine#448]
It looks like meshes used in particle systems are scaled differently than when used in model components. They appear to be quite bigger when used in particles. These should ideally be the same as it looks like you need to enter quite small scaling values in the particle component's scale curve to see anything meaningful.

**Comment by mvaligursky** [comment]
It seems to work ok [here](https://playcanvas.vercel.app/#/graphics/particles-mesh)
the ground has size 10. When I create a single particle with size 5 rendering a mesh from glb, I get this:
![Screenshot 2024-12-18 at 16 44 37](https://github.com/user-attachments/assets/3be7b7fa-76ad-4e09-92ac-26f7e9997948)
(mesh seems to be -1..1 range).

I'll close it, but lets reopen if we have some repro.
