### ISSUE TITLE
Clustered lighting or 1.55 could be causing higher GPU times on some project examples

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4487]
Thread: https://forum.playcanvas.com/t/engine-release-v1-55-0/26663/34?u=yaustar

> I’ve seen some updates in the examples, some of them are performing extremely bad in my laptop.
> 
> For reference, playcanvas 1.55.0, resolution 1080p, CPU i7-9750H and GPU RTX 2080:
> 
> [Area lights](https://playcanvas.github.io/#/graphics/area-lights): 750ms each frame (before the update, this example was very fluid)
> [Post effects](https://playcanvas.github.io/#/graphics/post-effects): 2100ms (Before the update, this example was very fluid)
> [Clustered area lights](https://playcanvas.github.io/#/graphics/clustered-area-lights): From 600 to 1300 ms
> [Clustered lighting](https://playcanvas.github.io/#/graphics/clustered-lighting): 100ms (So, clustered lighting sometimes works wonderful)
> The swimming pool example also performed very bad weeks ago, but I took it as a working in progress. Now that the plan is to more 1.55 from candidate to current in a couple of weeks, I wonder if I’m doing something wrong.
> 
> [Area lights](https://playcanvas.github.io/#/graphics/area-lights): 720ms => 220ms
> [Post effects](https://playcanvas.github.io/#/graphics/post-effects): 2100ms => 1300ms
> [Clustered area lights](https://playcanvas.github.io/#/graphics/clustered-area-lights): (600 to 1300ms) => (2600 to 3200ms)
> [Clustered lighting](https://playcanvas.github.io/#/graphics/clustered-lighting): 100ms => 250ms

**Comment by mvaligursky** [comment]
**Closing, based on this replay from the original poster:**

In our PCs all examples work perfectly, smooth at 60fps. I’m talking about GPU 4.5ms and CPU 1.4ms in the post-effects one. The clustered-area-lights even better, GPU 0.9 ms and CPU 2.1 ms

It looks that only my laptop had the problem.

I didn’t know about it, and I really thought playcanvas was having a really bad time updating to 1.55 . The laptop issue is really something unfortunate.
