### ISSUE TITLE
Draco GBLs no longer load in 1.55

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4509]
Example project: https://playcanvas.com/project/730372/overview/loading-draco-compressed-glbs

No error in console

**Comment by mvaligursky** [comment]
maybe related https://github.com/playcanvas/engine/issues/4413

**Comment by yaustar** [comment]
Engine example is fine: https://playcanvas.github.io/#/graphics/multi-view
But the Editor WASM module method is not

**Comment by slimbuck** [comment]
sorry what's the issue?

**Comment by yaustar** [comment]
On 1.55 in the Editor, Draco GLBs cannot be loaded at runtime

**Comment by yaustar** [comment]
Direct link: https://launch.playcanvas.com/1017807?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.55.1.dbg.js

**Comment by slimbuck** [comment]
oh FFFFF?$%!

**Comment by yaustar** [comment]
Yeah, my larger concern is that it may affect other WASM module assets in the Editor that people are using

**Comment by slimbuck** [comment]
no it's a logical error in glb-parser. will submit a fix soon.

**Comment by slimbuck** [comment]
(the decoder module is loading fine)
