### ISSUE TITLE
Shaders issue then publish project only | 1.55.3 

### ISSUE THREAD

**Issue by flyingbaba** [playcanvas/engine#4518]
We noticed today that shaders breaks then project is published / builded https://playcanv.as/p/pssfystW/. 

The issue is not present then Launching the project from the editor. 

### Steps to Reproduce

1. Project: https://playcanvas.com/editor/scene/1291680
2. Fork it. 
3. Publish the project and open it. 

P.s.: Same issue is noticed then using the rest api tools to create a build.

**Comment by slimbuck** [comment]
Hi, looks like the published version is using engine v1.54 instead of v1.55. Will investigate.

**Comment by slimbuck** [comment]
This should now be fixed. So sorry for the trouble!
