### ISSUE TITLE
Debug.error is causing an exception on skinInstance#resolve

### ISSUE THREAD

**Issue by MoserAlex** [playcanvas/engine#4525]
Quick summary of our work to give context:
We are merging multiple skinned meshes into a single skinned mesh, using a base skeleton which contains all the bones for any of the individual meshes. We had the issue where a skin instance was trying access a bone of the skeleton which was not in the hierarchy of our skeleton because of a bug on our side.

While looking into the issue we noticed that the exception was always thrown here:
https://github.com/playcanvas/engine/blob/6bdc8dc881a4ade1cffb0998d6dd5217494eb017/src/scene/skin-instance.js#L105

`rootBone.entity.name` was always causing the error `cannot read property 'name' of undefined`, and I guess this is because rootBone is already a `pc.Entity`. Therefore `rootBone.entity` will always be undefined.

**Comment by mvaligursky** [comment]
Thanks, confirmed! The fix is on the way.
