### ISSUE TITLE
pc.MeshInstance#aabb takes a long time to execute

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#454]
I have a skinned model with 50k verts and 300 bones. It takes about 2 minutes to calculate the bounding boxes when called pc.MeshInstance#aabb. This is a problem on load rather than every frame. I presume it's the nested for loops that are causing the problem.

**Comment by guycalledfrank** [comment]
Optimized in
https://github.com/playcanvas/engine/pull/457
https://github.com/playcanvas/engine/pull/458

Way faster than before, but still not great. We should really think of doing it in FACT.

**Comment by willeastcott** [comment]
Since this is now far, far faster than it was, I'm going to close this issue. If it becomes a problem again, we'll reopen the issue.
