### ISSUE TITLE
AnimEvents aren't created when animations are loaded via anim.assignAnimation

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4542]
Thread: https://forum.playcanvas.com/t/seeking-with-animcomponent/27060

Project: https://playcanvas.com/project/970251/overview/rewinding-animation-events

Animation event is added on the Idle animation and the animation is added via anim.assignAnimation
An event listener is added to script to console out some text but it is never called

Looking at the engine code, AnimEvents is only created on onAnimationAssetLoaded so no events are created here.

Workaround is to add the events manually before calling anim.assignAnimation

**Comment by yaustar** [comment]
Example of workaround: 
https://playcanvas.com/project/970264/overview/rewinding-animation-events-patch

```
// initialize code called once per entity
AddAnimations.prototype.initialize = function() {
    // We can add animations to the component without needing to create a state graph
    // as assignAnimation will create state if one doesn't exist
    
    // We can then later call https://developer.playcanvas.com/en/api/pc.AnimComponentLayer.html#transition
    // to play the state with that animation
    
    // To mimic the older Animation component, the state name will be the name of the asset
    for (var i = 0; i < this.animationAssets.length; ++i) {
        var animationAsset = this.animationAssets[i];
        var animTrack = animationAsset.asset.resource;
        if (animationAsset.asset.data.events) {
            animTrack.events = new pc.AnimEvents(Object.values(animationAsset.asset.data.events));
        }
        this.entity.anim.assignAnimation(animationAsset.stateName, animationAsset.asset.resource);
    }
};
```

**Comment by vogloblinsky** [comment]
Public project available here : https://playcanvas.com/project/970223/overview/debug-seeking-animation

Steps to reproduce the context :
- open JS console
- click on "load ollie"
- wait a little, you should see logs, and the animation will stop on step_0
- click on play, animation continue to step_1
- click on play and after the animation ends.

Steps to reproduce the issue :
- click on "load ollie"
- wait a little, the animation will stop on step_0
- click on Next, the animation move to step_1 (i just updated activeStateCurrentTime)
- click on play and after the animation ends but no log for AnimEvents. But it is strange, they restarted a few seconds later...

**Comment by vogloblinsky** [comment]
I just use the source code of the engine to try debugging my issue.
Seems related to function `activeEventsForFrame` of AnimClip class.
For the step_1 (time stop at 3.5) where i want to stop, if i seek at 3.4, everything is fine, and if i seek at 3.5, it breaks.

**Comment by vogloblinsky** [comment]
@ellthompson Did you watch my debug project ?
Just tested your PR in my local env, and i always have missing events frame.
