### ISSUE TITLE
Unsupported material property useMetalnessSpecularColor

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#4543]
There is warning on some old material (engine 1.55.3):

![image](https://user-images.githubusercontent.com/5677782/184873509-64cdeba6-c3f4-488a-b1ce-21927625975a.png)

**Comment by yaustar** [comment]
Would it be possible to copy that material to a new project and share please?

**Comment by GSterbrant** [comment]
Which engine version are you running? Could be that you need to switch to 1.55, unless you have done that already 🙂

**Comment by yaustar** [comment]
@GSterbrant They are running 1.55.3

**Comment by LeXXik** [comment]
Is there an easy way to identify which material that is?

**Comment by yaustar** [comment]
That's a good question 😅 . @GSterbrant Should we add extra logging to include the material name if possible?

**Comment by LeXXik** [comment]
Found it:
https://playcanvas.com/editor/scene/1502892

**Comment by willeastcott** [comment]
This was resolved by @GSterbrant before the 1.56.0 release:

![image](https://user-images.githubusercontent.com/697563/196009319-e1f6ab47-53fa-497a-8aba-7d6b487ae14d.png)

Presumably it was this PR which resolved the problem: #4478

Therefore, I'm closing this issue. Please reopen if you believe there are any outstanding problems.
