### ISSUE TITLE
fitMode doesn't work on video textures

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/engine#4571]
If you fork [this project](https://playcanvas.com/project/721265/overview/video-in-ui) and attempt to set the fit mode to cover for example, it won't work. The video will not play on the UI according to the fit mode you chose. It works with static images just fine, but it seems that on textures that are updated at runtime, it fails.

**Comment by yaustar** [comment]
Expected:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/16639049/185871183-cf846b40-2b78-49e9-9ca0-f586f15b6e41.png">

Result:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/16639049/185871238-e8ec405a-9054-4ad5-93fb-c69f49a7a2d7.png">

Project repro: https://playcanvas.com/project/972307/overview/video-fitmode
