### ISSUE TITLE
Dynamic refractions don't support scaling

### ISSUE THREAD

**Issue by GSterbrant** [playcanvas/engine#4580]
### Description

When using pixel scaling, the dynamic refractions using the grab pass look like this:

![image](https://user-images.githubusercontent.com/107400752/186145691-30c288c0-e776-4ed8-81df-9115eab5e69d.png)

When they should look like this:

![image](https://user-images.githubusercontent.com/107400752/186145732-9656c2bb-cf23-45e5-853f-5866675f44fa.png)

This is probably due to not taking the pixel scaling into account when sampling the grab pass in the dynamic refraction chunk.

**Comment by mvaligursky** [comment]
The problem seems to be that the SceneGrab allocates the texture with dimension device.width x device.width, instead of basing it of a render target for the camera the grab pass executes for.
