### ISSUE TITLE
Issue with parsinng glb file when it has empty curveData.paths

### ISSUE THREAD

**Issue by aliakseikalosha** [playcanvas/engine#4613]
### Description

In our project we use glb models, and we have issue with parsing the files error is in [glb-parser.js](https://github.com/playcanvas/engine/blob/main/src/resources/parser/glb-parser.js#L1608)
````
if (curveData.paths[0].propertyPath[0] === 'localRotation' && curveData.interpolation !== INTERPOLATION_CUBIC) {
            quatArrays.push(curves[curves.length - 1].output);
        }
````
If curveData has empty array of paths if will gerenrate a `TypeError: curveData.paths[0] is undefined` and stop parsing.

**Comment by mvaligursky** [comment]
Hi ... interesting, this should be easy to fix. Would you be able to share one of the glb files triggering this error? Thanks @aliakseikalosha .

**Comment by mvaligursky** [comment]
hi guys - any chance of a repro here? @aliakseikalosha

**Comment by aliakseikalosha** [comment]
The error was in work project so I can't share it. The new version of the model haven't been triggering same error.
I was trying to reproduce this error with other my own models but have no luck with it.

Anyway as I mentioned before it does not seems as a good idea to expect that all arrays have at least one element.

Sorry for late reply @mvaligursky
