### ISSUE TITLE
Material with Mask using opacity Color Channel renders differently in Editor and Scene

### ISSUE THREAD

**Issue by flyingbaba** [playcanvas/engine#4642]
While trying to use the Mask in a material noticed that it renders differently in Editor and Scene. 

![image](https://user-images.githubusercontent.com/10512039/190594418-7b3e5e4f-a2da-4b35-bd94-7f5dceae7155.png)

### Steps to Reproduce

1. Open Project in Editor https://playcanvas.com/editor/scene/1533357
2. Hit Launch

**Comment by yaustar** [comment]
In the Editor, you have the assets as 'Exclude' which means they are excluded from the project at runtime
<img width="402" alt="image" src="https://user-images.githubusercontent.com/16639049/190595397-0c7f72ae-8702-40f4-80eb-e48265eda1bb.png">

**Comment by flyingbaba** [comment]
@yaustar ah... thank you very much ! And sorry for not beeing attentive.
