### ISSUE TITLE
Screen-Space UI Buttons do not work in WebXR-AR mode

### ISSUE THREAD

**Issue by jpauloruschel** [playcanvas/engine#4653]
### Description

In WebXR-AR mode, screen-space UI buttons do not receive inputs at all. World-space UI buttons work fine, though.

* Sample build (needs to be executed in an WebXR-AR-enabled device, such as a new-ish Android device): https://playcanv.as/b/0ULNdGnS

### Steps to Reproduce

1. Create Scene with WebXR-AR capabilities
2. Add `2D Screen` with a `Button`
3. Launch and open AR mode
4. Try to click on the `Button`, it will not work

**Comment by mvaligursky** [comment]
This is possibly the problem here: https://github.com/playcanvas/engine/issues/3635

**Comment by jpauloruschel** [comment]
> This is possibly the problem here: #3635

The underlying bug behind issue #4653 had to do with the input system, not the Camera or FOV itself, so I do not believe they are actually related.
