### ISSUE TITLE
Main branch engine generates Shader Error in the Editor

### ISSUE THREAD

**Issue by weilichuang** [playcanvas/engine#4659]
Use the git version playcanvas.

Project:https://playcanvas.com/editor/scene/1530394

![shader_err](https://user-images.githubusercontent.com/2355262/191896222-e45bff60-cb09-4e2c-b35f-40956a615f6d.png)

**Comment by slimbuck** [comment]
Thanks for raising this one @weilichuang!

Recent change broke this https://github.com/playcanvas/engine/pull/4636/files#diff-0b850a404fa1dc3f4ed648bac2c701107284d10aee6ef6c2b6dd1f144d7ba409R14

(as well as the diffuseDetail chunk).
