### ISSUE TITLE
[Suspected Bug] Tiling with transparency

### ISSUE THREAD

**Issue by Dinkelborg** [playcanvas/engine#466]
When opening the project in Edge or Internet Explorer the texture tiling is broken.

https://playcanvas.com/project/368009/overview/bugtexturetilingtransparency

Please find the reproduction steps in the project page.
<b>Chrome & Firefox:</b>
![picture_chrome_firefox](https://cloud.githubusercontent.com/assets/8798969/11622846/fa80eaf2-9cc8-11e5-89ab-8bc0052bdc6e.png)
<b>IE &Edge:</b>
![picture_ie_edge](https://cloud.githubusercontent.com/assets/8798969/11622847/fa819574-9cc8-11e5-8028-35beb5661640.png)

**Comment by guycalledfrank** [comment]
Tiling is not broken. The problem with IE is that it pre-mutliplies colors by alpha, and then divides back, ignoring UNPACK_PREMULTIPLY_ALPHA_WEBGL. Closer your alpha to 0, more precision loss occurs on IE.

**Comment by willeastcott** [comment]
Expect Microsoft to fix this sometime next year. But yes, since this is a bug in IE/Edge, I'm going to close this issue. If you are affected by this, maybe consider splitting your opacity map out to a different image.
