### ISSUE TITLE
[feature request] Text Input

### ISSUE THREAD

**Issue by marcusx2** [playcanvas/engine#4676]
Something [like this](https://forum.playcanvas.com/t/released-aphrodite-starter-kit-ui-text-input/9319) or Unity's [Input Field](https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/script-InputField.html). I think this is a basic feature that should really be available without having to pay for a 3rd party plugin.

**Comment by yaustar** [comment]
Duplicate of https://github.com/playcanvas/engine/issues/2483
