### ISSUE TITLE
IOS Audio Context touch event

### ISSUE THREAD

**Issue by marklundin** [playcanvas/engine#4677]
IOS does not seems to recognize a touch drag as a valid interaction to start the audio context. In [this example](https://playcanvas.com/editor/scene/1546176) the box has a script which plays audio on mouse click, however if you begin with a touch drag and then click on the box the audio will not play, and no audio can be be played after. The Sound Manager [becomes stuck](https://github.com/playcanvas/engine/blob/main/src/sound/manager.js#L290) a state where it cannot resume the audio context.

**Demo:**
[This project](https://playcanvas.com/editor/scene/1546176) has a box with a script that plays a sound when you click on it. 
1. Touch drag anywhere on the screen
2.  Click on the box - > No Audio

**What should happen:**
1. Touch drag
2. Click the box -> audio plays

**Comment by marklundin** [comment]
FYI, it seems you can workaround this by using the following, however there's potentially some side effects to this...

```javascript
const updateUnlockingState = _ => {
    if(pc.app.soundManager._unlocked) window.removeEventListener('touchstart', updateUnlockingState )
    pc.app.soundManager._unlocking = false;
};

window.addEventListener('touchstart', updateUnlockingState, true );
```

**Comment by slimbuck** [comment]
Hi @marklundin, this was hopefully fixed in https://github.com/playcanvas/engine/pull/4789.

Please could you confirm with the next engine release?

Thanks!

**Comment by willeastcott** [comment]
I have tested this. @marklundin's project does now work as desired with the latest engine.
