### ISSUE TITLE
Consider moving onAnimationUpdate after frustum culling

### ISSUE THREAD

**Issue by querielo** [playcanvas/engine#4680]
Right now, the engine calls onAnimationUpdate before frustum culling.

<img width="825" alt="Screen Shot 2022-09-29 at 15 25 21" src="https://user-images.githubusercontent.com/104348270/193019468-84652718-6414-465e-8c3e-74ac4407b90a.png">

So, we can prevent expensive animation updates if models are culled.

**Comment by mvaligursky** [comment]
yep, its definitely something we want to add, see this ticket: https://github.com/playcanvas/engine/issues/3563
closing this as duplicate.
