### ISSUE TITLE
STL file format exporter for 3D printing

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4751]
With the rise in 3D printing, we could consider this an option to export to?

https://en.wikipedia.org/wiki/STL_(file_format)

We currently have USDZ and GLB exporters written here that could be used as a base: https://github.com/playcanvas/engine/tree/main/extras/exporters

**Comment by mvaligursky** [comment]
This is unlikely to be prioritised, as PlayCanvas is not the best tool to prepare geometry for 3D printing. I'll close it for now, but we might reopen it if there is larger interest in this.
