### ISSUE TITLE
SoundManager is always `suspended` when AudioContext not available, preventing sound playback

### ISSUE THREAD

**Issue by roger-o3h** [playcanvas/engine#4757]
### Description

When you are running in an environment without html5 web audio — `hasAudioContext()` is false (https://github.com/playcanvas/engine/blob/main/src/platform/audio/capabilities.js#L8) — the SoundManager always reports that it is `suspended` (https://github.com/playcanvas/engine/blob/main/src/platform/sound/manager.js#L117) because its `_context` is always null. A downstream problem this creates is that audio clips will never play.

Furthermore, `_unlocked` never has an opportunity to be set to `true` without AudioContext being present, as the only place it's set is the lazy creation of the AudioContext (https://github.com/playcanvas/engine/blob/main/src/platform/sound/manager.js#L139-L142) and this too causes SoundManager to perpetually report it is in a `suspended` state, preventing sound playback.

One potential fix would be to provide different implementations of `suspended` getter:

```js
    get suspended() {
        if (hasAudioContext()) {
            return !this._context || !this._unlocked || this._context.state !== CONTEXT_STATE_RUNNING;            
        } else {
            return this._selfSuspended;
        }
    }
```

I think this is somewhat critical as it seems to break all sound playback in our project. We have a polyfill for `HTMLAudioElement` in order to route audio through our native app hosting the web view. We force PC to use legacy sound mode by

```js
    delete window.AudioContext;
    delete window.webkitAudioContext;
```

before loading in PC. (It would be cool to have an option to do this, like the OPPOSITE of `forceWebAudioApi`). Our situation is a bit weird, but this issue should equally affect folks who truly don't support html5 web audio.

I'm building a minimal test case and will edit and attach it when complete.

**Comment by roger-o3h** [comment]
[pc-issue-4757.zip](https://github.com/playcanvas/engine/files/9805534/pc-issue-4757.zip)
Attached is a simple repro case. Press the button, get a sound.

* `webaudio.html` works normally, if you view in a browser with HTML5 web audio
* `legacy.html` you will notice no sound, emulating a browser without HTML5 web audio

**Comment by roger-o3h** [comment]
> @roger-o3h is this a regression issue (ie was this working in a previous release of the engine)?

Yes, was working in 1.52.6

**Comment by roger-o3h** [comment]
Just to update, after applying https://github.com/playcanvas/engine/pull/4788, the issue with legacy html audio is still present. In `instance.play()` this still runs:

```
            // suspend immediately if manager is suspended
            if (this._manager.suspended)
                this._onManagerSuspend();
```

and in the new logic, suspended is still dependent on an `AudioContext`:
```
	get running() {
        return this._context && this._context.state === CONTEXT_STATE_RUNNING;
    }

    get suspended() {
        return !this.running;
    }
```

With legacy html audio, there will never be a `_context`, `running` will always be false and `suspended` will always be true, pausing sound instances.

One way to fix this would now be to change `suspended` to be dependent on whether AudioContext is available:

```
    get suspended() {
        if (this.AudioContext) {
            return !this.running;
        } else {
            return this._userSuspended;
        }
    }
```
Or, something could be changed in `instance.js` in the `play()` prototype specific to `if (!hasAudioContext())`.

Grateful for the related fix! Only trying to be helpful in keeping this bug report up to date 🙏

**Comment by willeastcott** [comment]
@roger-o3h Thanks for this info!! I'm sure @slimbuck will get back to you on this tomorrow. But just to confirm, presumably legacy HTML Audio is only used in IE11 these days, right?

**Comment by roger-o3h** [comment]
> @roger-o3h Thanks for this info!! I'm sure @slimbuck will get back to you on this tomorrow. But just to confirm, presumably legacy HTML Audio is only used in IE11 these days, right?

It's true, should be very uncommon now, but I do hope you continue to support it, as we are using a `HTMLAudioElement` polyfill that allows us to do some very custom things with routing our audio in our native application that uses a web view. 🙏 

Just one user, but it's totally fine with me if, for instance, the "suspend" behaviour is dropped for this legacy mode... we just hope it continues to be an option.
