### ISSUE TITLE
Audio is blocked from playing on iOS if user starts with a swipe gesture since 1.56

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4760]
Forum: https://forum.playcanvas.com/t/the-only-way-how-to-start-audio-on-ios-is-by-fast-tap-on-the-screen-no-swipe-or-touch-and-hold-anymore/27850

Using this project as the example: https://playcanvas.com/project/405821

https://launch.playcanvas.com/440098?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.56.0.js will start playing sound on a tap. However, if you swipe it will not play sound and subsequent taps will NOT start the sound.

https://launch.playcanvas.com/440098?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.55.4.js was the last working version.

This issue does not occur on Android

**Comment by yaustar** [comment]
A number of users have hit this issue in some form.

Could also be related to https://github.com/playcanvas/engine/issues/4757

**Comment by slimbuck** [comment]
This sound code is difficult to decipher and the changes made in #4462 are not straightforward.

Not sure if @jpauloruschel has any suggestions for me on this one? 🙏🏻
