### ISSUE TITLE
Clustered lighting reduces performance on some devices / GPUs

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4762]
FPS is shown in the middle of the camera view

---

Using a single directional light: https://playcanvas.com/project/997759/overview/dir-clustured-lighting-in-vr

Tested on a Quest 1

With clustered lighting
72fps in browser
36fps in WebXR VR

Clustered lighting disabled
72fps in browser and WebXR VR

---

Using a single spotlight: https://playcanvas.com/project/997775/overview/spot-clustured-lighting-in-vr

Tested on a Quest 1

With clustered lighting
72fps in browser
24fps in WebXR VR

Clustered lighting disabled
72fps in browser and WebXR VR

---

Update Thu 3 Nov 2022: Disabling shadows brings the FPS back to 72fps with clustered lighting enabled.

**Comment by yaustar** [comment]
I've tried this with latest engine that has Martins PR https://github.com/playcanvas/engine/pull/4761

Still get the same FPS unfortunately.

**Comment by mvaligursky** [comment]
Few times over last months I've considered an option in scene.lighting to disable spot/omni lights .. so pretty much the overhead of clustered lighting would be gone (overhead is there even if no omni/spot lights are used just to check for them) if only the directional light is used. I think it's a good idea and I'll add that.
