### ISSUE TITLE
First Application.update `dt == 0`.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#477]
First update has `0` `dt`. It is due to initially `_time` is `0`.
https://github.com/playcanvas/engine/blob/master/src/framework/application.js#L694

Consider skipping update if `dt === 0`?

**Comment by willeastcott** [comment]
My opinion here is that an initial call to update with dt as 0 means that the first frame rendered will be the start state as specified by scripts' initialize function. This is a good thing IMHO. So I'm going to close this.
