### ISSUE TITLE
Spine integration no longer rendering on iOS 12 and some devices (iPhone 5S)

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4770]
Forum: https://forum.playcanvas.com/t/spine-demo-forked-not-working-in-ipad-air-first-generation/27975

Project: https://playcanvas.com/project/783555/overview/spine-example-38

There's no error besides the one below:
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/16639049/196922487-9853658e-aba9-4083-b2ae-1d0b9051bfbe.png">

Last working version was engine 1.54.1
https://launch.playcanvas.com/1128118?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.54.1.js

**Comment by yaustar** [comment]
Note: Renders correctly on iOS 15

**Comment by mvaligursky** [comment]
I tried Mac OS Webgl1 just in case it's Webgl1 issue, and that renders fine on Chrome and Safari.

**Comment by willeastcott** [comment]
iPhone 6 with iOS 12.5.6:

![IMG_0007](https://user-images.githubusercontent.com/697563/196963448-3e6eb3a1-76c8-4ef7-9182-d291bb2ea639.PNG)

**Comment by yaustar** [comment]
Doesn't work on iPhone 5S on 12.4.5. Will try upgrading to 12.4.6

**Comment by yaustar** [comment]
iPhone 5S on 12.4.6 doesn't render the spine model/animation. Renaming ticket.

**Comment by mvaligursky** [comment]
As iPhone 5S only supports WebGL1, it's not likely we'll investigate this, and so I'm closing the ticket.
