### ISSUE TITLE
Shader compilation issue on devices without extStandardDerivatives

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#4772]
Repro:
- disable extStandardDerivatives in WebglGraphicsDevice by commenting out line `//this.extStandardDerivatives = true;`
- run engine example: render-asset

![Screenshot 2022-10-20 at 12 47 59](https://user-images.githubusercontent.com/59932779/196940387-6fb3464d-ab07-49df-8cba-18e26082c04b.png)

The problem is missing `varying vObjectSpaceUpW;` in the fragment shader.
builtinVaryings in lit-shader.js has that in the list, but those are only added to vertex shader, but not to fragment.

**Comment by GSterbrant** [comment]
Do you have an example device to test this on?

**Comment by mvaligursky** [comment]
I do not, I only simulated one by disabling the extension.
