### ISSUE TITLE
Rendering resolution is higher in WebXR AR than not

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4775]
Project: https://playcanvas.com/project/998364/overview/webxr-ar-camera-high-dpr

When in AR, it looks like we are rendering in a higher resolution than when we are not. Device pixel ratio is disabled

The 'i' icon in the bottom left is an example of this. Expectation is that the resolution should be the same between the two

Normal
![Screenshot_20221020-155231](https://user-images.githubusercontent.com/16639049/196984009-eb19a48c-b03c-4755-a526-2de5987b43cd.png)

In AR
![Screenshot_20221020-155301](https://user-images.githubusercontent.com/16639049/196984293-0d83439e-85b6-4bf1-a8a6-881eb6e2009d.png)

**Comment by Maksims** [comment]
Framebuffer is created for AR session by underlying system.
When starting XR session, it is possible to provide base layer for rendering, with frame buffer scaler! https://www.w3.org/TR/webxr/#xrwebgllayer-interface

Important to ensure how things like Depth Sensing and few others will be affected.

Also, I've avoided Layers all together from integration, as it is large and complex, and requires well thought API and integration design.

**Comment by yaustar** [comment]
@Maksims I'm looking at the XR manager here: https://github.com/playcanvas/engine/blob/main/src/framework/xr/xr-manager.js#L675

And it changes the resolution of the graphics device when we first enter via the framebufferWidth/Height. 

I guess my question here is whether it should be user controllable on what the resolution scale in XR should be? Or should it be left up to the device via [getNativeFramebufferScaleFactor](https://www.w3.org/TR/webxr/#dom-xrwebgllayer-getnativeframebufferscalefactor)?

**Comment by yaustar** [comment]
I was looking at `_onSessionStart` and changing the creation of the layer to:

```
        this._baseLayer = new XRWebGLLayer(session, this.app.graphicsDevice.gl, {
            alpha: true,
            depth: true,
            stencil: true,
            framebufferScaleFactor: adjustedScaleFactor
        });
```
For a test and to match the scale of resolution that is used in the non XR part of the app but the framebuffer being created is still at full resolution with `getNativeFramebufferScaleFactor` returning 1 instead of the value set above 🤔
