### ISSUE TITLE
WebXR AR screen space UI input doesn't register touches correctly

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4776]
Project: https://playcanvas.com/project/998371/overview/webxr-ar-ui-screen-space-broken

Pressing on the very far left corner (shown below) doesn't register you've pressed the button
![image](https://user-images.githubusercontent.com/16639049/196992191-54f1b477-b004-4a23-a887-fb1d0feaab1e.png)

**Comment by yaustar** [comment]
I believe this is because as part of the worldToScreen function call, the camera updates the projection matrix based on the FOV, aspect ratio, etc as shown here:

https://github.com/playcanvas/engine/blob/554e659619a381b1f43ad890121cffd2daae20b5/src/scene/camera.js#L478

However, when in XR, in the renderer, the camera uses a different projection and view matrix
https://github.com/playcanvas/engine/blob/main/src/scene/renderer/forward-renderer.js#L285

Therefore, it looks like the raycasting is using the wrong matrix for transformation of the ray.

**Comment by mvaligursky** [comment]
related to https://github.com/playcanvas/engine/issues/3635

**Comment by yaustar** [comment]
Wondering if we could either:

1. Update the FOV, aspect ratio etc values etc back to camera in the same way 8th Wall and Zappar do it
2. Use the Input XR Sources for the ray when in XR for the element input logic instead of camera projection

**Comment by Maksims** [comment]
For the UI, it should be using input source rays already.

**Comment by yaustar** [comment]
> For the UI, it should be using input source rays already.

@Maksims It seems to be only use that for World Space UI, not screen space?

**Comment by yaustar** [comment]
I've tried 1. in https://playcanvas.com/project/1001902/overview

```
AugmentedRealityManager.prototype._onXrTracking = function () {
    const camera = this.arCameraEntity.camera.camera;
    if (camera.xr && camera.xr.views.length) {
        // calculate frustum based on XR view
        const viewProjMat = new pc.Mat4();
        const view = camera.xr.views[0];
        //viewProjMat.mul2(view.projMat, view.viewOffMat);
        
        viewProjMat.copy(view.projMat);
        const data = viewProjMat.data;

        const fov = (2.0 * Math.atan(1.0 / data[5]) * 180.0) / Math.PI;
        const aspectRatio = data[5] / data[0];
        const farClip = data[14] / (data[10] + 1);
        const nearClip = data[14] / (data[10] - 1);

        this.arCameraEntity.camera.horizontalFov = false;
        this.arCameraEntity.camera.fov = fov;
        this.arCameraEntity.camera.aspectRatio = aspectRatio;
        this.arCameraEntity.camera.farClip = farClip;
        this.arCameraEntity.camera.nearClip = nearClip;
    }

    this.app.fire('ar:onTracking');
};
```

Which is what 8th Wall and Zappar do in their integrations. It looks like that works on the test device I was on
https://user-images.githubusercontent.com/16639049/198676067-ae9f14cb-144c-4109-822b-dd28dcacc15c.mp4

Not sure if this is something we should do in the engine or users are expected to do this on their end as this is explicitly changing the values on the camera. If we did this in the engine, we would need to change the values back when the user exits XR.

**Comment by Maksims** [comment]
When was integratin XR, I thought that camera parameters should become read-only and return actual values that reflect XR session. Indeed.

**Comment by yaustar** [comment]
That could be something we could do. We could add a set of parameters for the camera that reflects the AR camera values (FOV etc) and the getters would return those if we were in the AR session?

**Comment by mvaligursky** [comment]
I didn't give this much thought yet, but my initial thinking was to perhaps have an 'driverByAR' type of flag on a camera .. and cameras with that set would get values updated from AR at the start of the frame (before updates are called on scripts). User would then avoid updating the camera parameters, and everything else would work.

**Comment by Maksims** [comment]
> I think the problem with that is the cameras with that flag would ideally need the FOV and other properties to be 'reset' to what they were before they went into XR so they would have to be saved somewhere

Better would be not affect camera data, and ensure getters return XR data when camera is used as XR view. That way no data management is needed.
