### ISSUE TITLE
Textures no longer automatically downsize to max supported by device since Engine 1.57

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4782]
Thread: https://forum.playcanvas.com/t/playcanvas-1-57-1-doesnt-render-properly-texture-bigger-than-4096x4096-anymore/28062

Project with 8K texture: https://playcanvas.com/project/999540/overview/no-texture-downsizing

1.57 just shows up black: https://playcanv.as/b/a2122cc7
1.56 shows the texture: https://playcanv.as/b/59701a8a

**Comment by slimbuck** [comment]
This is due to ImageBitmap not being downsampled https://github.com/playcanvas/engine/blob/main/src/platform/graphics/webgl/webgl-texture.js#L321.

**Comment by slimbuck** [comment]
Since 2d context drawImage supports ImageBitmap (https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage) the test just needs updating.
