### ISSUE TITLE
WebGL Context lost on MacBook Pro using Integrated Intel GPU

### ISSUE THREAD

**Issue by jpauloruschel** [playcanvas/engine#4784]
### Description

On MacBook Pro 12.6, latest Chrome (Version 106.0.5249.119), and using integrated GPU (Intel UHD Graphics 630 1536 MB), I'm getting issues with the WebGL context being lost and then restored. At first, the scene loads fine, but a few seconds later, the browser hangs for a second, and I get something like this in the console:

<img width="655" alt="Screenshot 2022-10-24 at 15 08 24" src="https://user-images.githubusercontent.com/6392953/197545956-25324ba9-8312-40f9-b389-9836b2fc662a.png">

Depending on the scene, some visual artefacts also appear (for instance, scene Skybox is 'lost' and no longer rendered).

This issue appears on many different projects, but you can use https://playcanvas.com/project/926641 for testing. The issue does not seem appear on simpler, less graphics-heavy scenes.

I tested the same scenes on different setups (any browser in Windows, Safari on Mac) and the issue does *not* appear. It also does not appear when using the dedicated (AMD) GPU.

I am able to mitigate this issue by always using the dedicated GPU.

### WebGL Report

<img width="1383" alt="Screenshot 2022-10-24 at 15 05 44" src="https://user-images.githubusercontent.com/6392953/197545366-ac067e29-e367-4025-847b-8c78b9349d12.png">

### Steps to Reproduce

1. Launch https://playcanvas.com/project/926641 on a MacBook Pro, Chrome.
2. Move camera around for a bit.
3. Check console logs

**Comment by querielo** [comment]
It looks like there is something wrong with disjoint_timer_query. Could you check that your link is correct and the project is not private?
Link: [https://playcanvas.com/project/926641](https://playcanvas.com/project/926641)

**Comment by querielo** [comment]
@jpauloruschel 
It looks like there is something wrong with disjoint_timer_query. Could you check that your link is correct and the project is not private?
Link: https://playcanvas.com/project/926641

**Comment by jpauloruschel** [comment]
Thanks for the response @querielo ! Could you send me your PlayCanvas username, I can add you to the project?

**Comment by querielo** [comment]
> Thanks for the response @querielo ! Could you send me your PlayCanvas username, I can add you to the project?

It is **KIRILL_OSIPOV** (Kirill Osipov)

Apologies for the delayed response

**Comment by mvaligursky** [comment]
I think the problem is coming from mini-stats, those do not handle lost context at the moment (and should).
If you disable mini-stats, do you still have a problem?

**Comment by willeastcott** [comment]
@jpauloruschel Just a little follow up to see if @mvaligursky's advice helped at all. 😄
