### ISSUE TITLE
Highlight shader lines that have errors in console logs

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4786]
We output the error and shader code that has an error, the cherry on top would be to highlight the line as well:

eg https://twitter.com/Doormat23/status/1370309669835653127?t=nOf8E_zuJrYA4pMlKzD_Qw&s=03

![image](https://user-images.githubusercontent.com/16639049/197760822-7c6791c3-874e-44a7-a22f-4d04e4ba97fd.png)

**Comment by mvaligursky** [comment]
This would be nice to have, but our shader error reporting is pretty good already. I'll close this for now, unless there is larger interest.
