### ISSUE TITLE
Add Compound Collision Shapes

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#479]
We need to think of an API and implement Compound Collision Shapes.

Generally there are two approaches:
1. List of shapes within collision component.
2. Entities with collision components, which are children of entity with collision component `compound` set to true.

I give preference to first one for its simpler dependencies and it wont be as troubling in managing ancestor entities relationships.
And it is easier for engine at runtime: wont need to create extra GraphNodes, transformations, track local properties changes to update compound child, etc, etc.

**Comment by redsparkzone** [comment]
Approach #1 seems to be better indeed.
Compound collision would be really great to have!

**Comment by willeastcott** [comment]
But with option 1, how are shapes going to be moved relative to the entity? You'd need to add offsets for at least translation and rotation, and probably scale as well. I think it would get a bit messy. I'm leaning more towards option 2.

**Comment by Maksims** [comment]
Translate and Rotate - yes, Scale - no. Each shape has own params, such as halfExtends for box, or radius for sphere. Those are used instead of scale.
So all it is, list of shapes with types, and their specific params based on type of shape.
In code it can be simple as two vectors (Position, Rotation), and in Editor on selecting entity with compound shapes, we can render gizmos for each shape allowing it to be easily dragged.

**Comment by vkalpias** [comment]
My feeling is it each collider should be a child entity. That way you can attach scripts on each Entity separately and get events on it and also attach children to those Entities to be destroyed for example when the Entity collides with something etc. I think we might be limiting ourselves by having just a list of shapes.

**Comment by Maksims** [comment]
There will be huge number of limitations of what compound child entity can do. As well as extra overhead of managing extra nodes. Where in almost all use cases, physics compound objects are almost 1:1 comparable to trimesh physics objects. Which purpose is to do just physics.
Then what if you want another child entity with physics to not be compound, but be another physics object?
What if you update transform of a child, need to update compound transform too, what is overhead with that taking in account that there is hierarchy now involved?

Please provide examples of what can and cannot be done with both cases. User stories here will be perfect.
Please look at real-world projects, and think how it would look and be implemented with #1 or #2 options?

**Comment by redsparkzone** [comment]
@willeastcott Offset / rotation would be a good practice anyway. A typical example is character with capsule collider. Characters usually have pivot on their feet, so right now adding collider with vertical offset requires creating a child entity and offsetting it. In majority of cases developers still need to adjust offset / rotation, but now it's done via child colliders. If we could move this workflow into a single Collision Component, that would be a little bit more convenient. The only challenge I see is how to make new Collision Component not bloated in terms of UI.

**Comment by willeastcott** [comment]
Agreed @redsparkzone. Having to create a child entity to offset a single collision component is indeed annoying.

**Comment by Maksims** [comment]
In Editor, we have Sound Component with way more properties per each Slot.
Here we probably would have similar, list of child shapes, which are way smaller as they need just position, rotation, type and properties based on type. We can fold each of them, and highlight gizmo (wireframe of shape) in viewport on hover, that gives good idea of which child is which shape. And probably show gizmos for all shapes in viewport, allowing you to drag them easily.
We can implement "selecting" mechanics for children as well easily, allowing to focus on them and orbit camera them. As all modules in editor ready for doing it already.

**Comment by redsparkzone** [comment]
@Maksims 
Indeed, forgot about Sound Component UI.
Reimplementing Collision in the same way would be the most efficient way by me.

**Comment by mast4461** [comment]
@Mikecoon wrote a script for using compound collision shapes. It accesses ammo.js directly. Perhaps it could give some ideas about how to integrate compound collision shapes into PlayCanvas and the editor.

The [script](https://github.com/Mikecoon/compound-shape/blob/master/compound.js) is available on GitHub and its [user manual](https://forum.playcanvas.com/t/compound-shapes-implementation-script/4708) on the PlayCanvas forums.

**Comment by willeastcott** [comment]
Nice, I hadn't seen that before. I was thinking the implementation would be that rigidbody components would search for all collision shapes on the same entity or below in the hierarchy. If there's more than one, a compound collision shape is created. If a collision component is added to an entity, but there's not rigidbody ancestor in the hierarchy, it becomes a trigger volume.

**Comment by Maksims** [comment]
I have started implementing Compound shapes. I follow suggested by @willeastcott: scan descendant entities with collision component and no rigidbody component, and make them as compound child shape.
To prevent unnecessary scanning, I will be implementing `compound` checkbox. If it is checked on collision component, then it will scan descendants.

This approach has limitation: entity scaling - entities and collision shapes scales do not relate, but entity descendant transformations - get affected by scaling, so need to find solutions for it.

Important aspect for this: Editor rendering all collision shapes of a compound when selecting compound collision shape or any of its descendant shapes.
