### ISSUE TITLE
Add option to  set size of shadow map frustum based on bounding boxes of shadow casters.

### ISSUE THREAD

**Issue by querielo** [playcanvas/engine#4812]
Right now, size of shadow map frustum does not depend on size of objects that cast shadows. So, it is hard to achieve high quality of shadows for small objects. It would be great to have an option to keep frustum as small as possible depending on size of objects that cast shadows.

**Comment by mvaligursky** [comment]
duplicate of https://github.com/playcanvas/engine/issues/813, unless I'm mistaken.

**Comment by querielo** [comment]
> duplicate of #813, unless I'm mistaken.

You are right. Thanks!
