### ISSUE TITLE
Particles have strange vertical lines

### ISSUE THREAD

**Issue by ertugrulcetin** [playcanvas/engine#4813]
I’m seeing some strange vertical (pixel-like) lines in the particle system (also other strange stuff as well). This happens when I **zoom in**.

Here is the project: [PlayCanvas | HTML5 Game Engine 3](https://playcanvas.com/editor/scene/1397781)

Also, there is a discussion in the forum: https://forum.playcanvas.com/t/particles-have-strange-vertical-lines/28192

@leonidaspir and @mvaligursky confirmed it.

Here are the images;

![Screen Shot 2022-11-01 at 23 44 41](https://user-images.githubusercontent.com/8271291/199459402-8e87cce2-ee57-41e0-9797-2c35f13947c7.png)
![Screen Shot 2022-11-02 at 10 50 07](https://user-images.githubusercontent.com/8271291/199459392-db88077e-5d88-4931-a09b-3b66cd771bf7.png)
![Screen Shot 2022-11-02 at 10 37 37](https://user-images.githubusercontent.com/8271291/199459411-9319ad3b-81da-4800-9087-167be558b69b.png)

**Comment by mvaligursky** [comment]
Not sure what is happening, it seems related to the Depth Softening … if I set this to 0, the issue goes away.

@GSterbrant  - could you please have a look? It might possibly be related to the changes to the linear depth we encode / decode?

**Comment by yaustar** [comment]
Last working engine version is 1.53.4

Project with the camera pre set up: https://playcanvas.com/project/1003680/overview/f-fireball-particle-issue
Launch tab with 1.53.4: https://launch.playcanvas.com/1578471?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.53.4.js
Launch tab with 1.54.0: https://launch.playcanvas.com/1578471?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.54.0.js

**Comment by GSterbrant** [comment]
I think this issue might be due to an incorrect capture of the scene depth, as demonstrated here:

![image](https://user-images.githubusercontent.com/107400752/199524787-071af652-49b7-4fac-8d0c-581f2228ff0d.png)

This is caused by not running:
```js
    this.entity.camera.requestSceneDepthMap(true);
```
On the camera, which means we never end up running the grab pass for the depth.

**Comment by mvaligursky** [comment]
this warning when using a debug engine is the reason:
<img width="501" alt="Screenshot 2022-11-02 at 15 06 34" src="https://user-images.githubusercontent.com/59932779/199525954-80693e8b-fc4d-4cce-a964-7f7916c015f2.png">

If I create a new script like this, and add it on the scene camera entity, all is good, as the depth for the camera is available

```
var Test = pc.createScript('test');

// initialize code called once per entity
Test.prototype.initialize = function() {
    this.entity.camera.requestSceneDepthMap(true);
};
```

**Comment by leonidaspir** [comment]
Shouldn't the particle system enable that automatically since it's required? Thinking non coders will have trouble working in editor with particles.

**Comment by mvaligursky** [comment]
We considered this when changing the way the depth is requested. Initially, the depth would be enabled on all cameras when a particle needed it, which is costly. Now user can only enable it on a camera that needs it / that renders soft particles. Engine tracking to see if a particle system is on a layer the camera uses is turning out to be a bit tricky, so it has not been done (yet at least). And similarly tracking if a material needs depth texture - that would need tracking to see if any mesh instance using this material is on a layer of the camera.

Short term plan is to add a tickbox to the camera component, allowing user to generate camera depth texture without a script.
