### ISSUE TITLE
Allow collision component to accept mesh instances

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#4828]
Sometimes we generate a collision mesh on the fly, or get the mesh instance from elsewhere. It would be useful, if we could feed the instance directly to the collision component to create a collision mesh. At the same time, making a material optional when creating a new mesh instance, since it is not used for rendering.

**Comment by mvaligursky** [comment]
duplicate of https://github.com/playcanvas/engine/issues/4181
