### ISSUE TITLE
ElementTouchEvent is storing touches as window.Touch objects instead of pc.Touch

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4841]
The API JSDocs and pc.TouchEvent has changedTouches and similar properties as pc.Touch objects. pc.ElementTouchEvent is storing them as window.Touch objects instead.

See: 
https://github.com/playcanvas/engine/blob/main/src/framework/input/element-input.js#L274

Compared to pc.TouchEvent that converts them to pc.Touch
https://github.com/playcanvas/engine/blob/main/src/platform/input/touch-event.js#L90

**Comment by kungfooman** [comment]
Do you mean converting `TouchList` to "pc" `Touch[]` or to fix wrong JSDoc types?

If the event type is changed, wouldn't that break projects? For cases like:

```js
constructor() {
  this.element.on('touchstart', this.touchStart, this);
}
touchStart(e) {
  // using e.changedTouches or e.touches
}
```

**Comment by yaustar** [comment]
> Do you mean converting TouchList to "pc" Touch[] or to fix wrong JSDoc types?

So that it is more inline with the standard `pc.TouchEvent`, I believe that `pc.ElementTouchEvent` `this.touches`,  `this.changedTouches` and `this.touch` should be using `pc.Touch` and match the existing JSDocs.

Yes this could break projects that are dependent on the incorrect behaviour.

**Comment by willeastcott** [comment]
This seems to have been fixed since the issue was originally logged. See:

* [ElementTouchEvent#changedTouches](https://api.playcanvas.com/classes/Engine.ElementTouchEvent.html#changedTouches)
* [TouchEvent#changedTouches](https://api.playcanvas.com/classes/Engine.TouchEvent.html#changedTouches)
