### ISSUE TITLE
Dynamically created ScriptComponent ignores default value of an attribute.

### ISSUE THREAD

**Issue by querielo** [playcanvas/engine#4850]
If one does not pass [the attributes parameter](https://github.com/playcanvas/engine/blob/main/src/framework/components/script/component.js#L616) while creating ScriptComponent then the attributes are null.

**Example**:

```js
var DynamicallyCreatedScript = pc.createScript('dynamicallyCreatedScript');
DynamicallyCreatedScript.prototype.initialize = function() {
    console.log(this.vec3.x);
};
DynamicallyCreatedScript.attributes.add("vec3", { type: "vec3", default: [1, 1, 1] });

// MAIN
var Main = pc.createScript('main');
Main.prototype.initialize = function() {
    const entity = this.entity;

    const script = entity.script;

    script.create("dynamicallyCreatedScript", {});
};
```

_Result_:
<img width="1501" alt="Screen Shot 2022-11-16 at 12 52 56" src="https://user-images.githubusercontent.com/104348270/202134102-39e70ac2-bc84-42b0-9fcf-964d19737ba5.png">

_Expected_: if an attribute is not passed in `script.create("myAwesomeScript", {attributes: {}});` then the engine takes default value of the attribute.

Playable example: https://playcanv.as/b/0edf0fc7 (see console)

**Where is it in the engine?**

https://github.com/playcanvas/engine/blob/main/src/framework/script/script-type.js#L324

**Comment by DarkKelt** [comment]
bump

**Comment by querielo** [comment]
Sorry, it's my fault.
