### ISSUE TITLE
Post effects should be applied just to a camera's render target

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#486]
Currently, post effects on a single camera are applied after all cameras have been rendered. Instead, they should be applied just to the render target of that camera.

**Comment by stzDelongli** [comment]
Is there any plan to solve this issue? Thanks.

**Comment by slimbuck** [comment]
@willeastcott is this still an issue?

**Comment by willeastcott** [comment]
I don't know. This issue was opened before @guycalledfrank added the layer system. So it's possible that this is resolved but I'm not sure unless I test it.

**Comment by mvaligursky** [comment]
This has been improved considerably, I'm closing this.
