### ISSUE TITLE
reproject-texture packSamples overcalculates 4x + index out of bounds

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#4860]
Thank you a lot for your super quick fix @mvaligursky!

The bad news is I have another issue, the good news is that afterwards this should be 4x faster. :sweat_smile: 

I will try to explain by debug session:

![image](https://user-images.githubusercontent.com/5236548/202490827-0e1bb789-f223-48a8-9eaa-b22091675b40.png)

Basically there is a `samples` array of length 8192 and its length is assigned to `numSamples`. Then `numSamples` is iterated over one-by-one and `i` is multiplied by 4 to index the `samples` array again (so basically 75% of that for loop is out-of-bounds).

The same then happens with the `Uint8Array` that has a length of 32768 but is indexed up to 131072.

**Comment by mvaligursky** [comment]
@slimbuck - any thoughts on this one?

**Comment by slimbuck** [comment]
Yep you're absolutely right @kungfooman. Wanna submit a PR with `i < numSamples / 4` ?

**Comment by kungfooman** [comment]
> Yep you're absolutely right @kungfooman. Wanna submit a PR with `i < numSamples / 4` ?

Yep, I can do so tomorrow
