### ISSUE TITLE
Sharpen post-effect

### ISSUE THREAD

**Issue by yarpskendaya** [playcanvas/engine#4866]
In the old Ermis Special Effects package from Playing In Canvas, Leonidas had created a Sharpen effect on the Filmic filter.
ESE is no longer supported, and some of its features were incorporated in this repo under `posteffects/`, but not this sharpen effect.
Now that ESE no longer works, this effect is sorely missed, and we'd love to know if there is anyone out there willing to add it as a script under posteffects/

**Comment by leonidaspir** [comment]
Hey, there is a pull request about Sharpen. It has been closed and the effect didn't make it to the main branch, but I think you can still grab the file from there.

Most likely it will with either no or minimal changes.

https://github.com/playcanvas/engine/pull/3178

**Comment by mvaligursky** [comment]
There is a good change this version would work, that Leonidas contributed here, but it's not fully integrated into the codebase:
https://github.com/playcanvas/engine/pull/3178

I'll close the ticket, but please reopen it if this does not solve it.

**Comment by mvaligursky** [comment]
There's a whole bunch of PRs that need some clean up and than could be merged.
The PRs contain changes to example file as well .. that'd need to be stripped out, ticket for this: https://github.com/playcanvas/engine/issues/3540
