### ISSUE TITLE
Material specular renders differently between clustered lighting and non-clustered lighting

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4867]
Post: https://forum.playcanvas.com/t/spotlight-gives-wrong-result/28440/11?u=yaustar
Project: https://playcanvas.com/project/1010843/overview/specular-highlights-issue

With clustered lighting 
<img width="326" alt="image" src="https://user-images.githubusercontent.com/16639049/203023042-c26915f2-bcf4-400a-ba43-21ba0d163955.png">

Without clustered lighting
<img width="360" alt="image" src="https://user-images.githubusercontent.com/16639049/203023080-80078f14-51b5-4218-8b9b-20c148ce350e.png">

**Comment by GSterbrant** [comment]
This was probably fixed in this PR: https://github.com/playcanvas/engine/pull/4870.
