### ISSUE TITLE
Configurable should be `false` for String shims

### ISSUE THREAD

**Issue by thomcc** [playcanvas/engine#487]
Right now it's true for `String.prototype.startsWith` and `String.prototype.endsWith` in core/string.js. Not only is this against the spec (*very* few things in ES5 and ES6 are non-configurable), but it breaks any script that adds includes something more complete, like es{5,6}-shim, unless they take care to include it first (if you're using something like browserify, this is inconvenient). The breakage only occurs in browsers where the shim is necessary, adding further frustration.

This shouldn't break any code, and should be a trivial change to make.

**Comment by Maksims** [comment]
If some third-party shims will override functionality of those methods which are used in engine, how we can guarantee it won't break the consistency, which might lead to unexpected problems? Plus, surely those shims do same exact check on existence of those methods, which then keeps the engines at the end.
Is there any case of something misbehaving?

**Comment by thomcc** [comment]
It specifically causes a crash when loading es6-shim after PlayCanvas in Safari 8.

They do check if it exists, but they also check to ensure it works exactly as specified in the ES6 spec, and override it if it does not. This is to work around implementation bugs in various browsers.  That said, yours do not because they don't throw when given a regexp (looking at your source, your implementations also don't convert `this` to a string, which could matter if you called it like `String.prototype.startsWith.call(someNonString, ...)`, and there are probably other subtle errors as well).

Regardless of whether or not I care about those specific changes (honestly I don't, and I think the likelihood of the differences between your implementation and the spec mattering are very low), I do want to use the rest of ES6 shim, and if it worked with my build process that would be ideal.

Again, I'm not saying you should remove them, just that you shouldn't set them to non-configurable.

**Comment by Maksims** [comment]
Thanks for a feedback. You can make a PR to change it to configurable, we will merge it.
