### ISSUE TITLE
Broken Input ElementComponents in 1.58.1

### ISSUE THREAD

**Issue by eproasim** [playcanvas/engine#4882]
It appears that Element components with ‘Use Input’ enabled have been negatively affected by changes in 1.58.1. This issue is true for elements with and without a ButtonComponent. When clicking on an input element, the following error is thrown:

Uncaught TypeError: this._clickedEntities is undefined

Provide as much information as possible. Include (where applicable):

* URL to a simple, reproducible test case that illustrates the problem clearly: https://playcanvas.com/editor/scene/1596864
* Screenshots: 
![image](https://user-images.githubusercontent.com/79989325/203603340-5f16ba27-31c3-455a-862a-526fd0b949fa.png)

### Steps to Reproduce

1.     Create a new blank project
2.     Add a screen element and a button element
3.     Launch App and click the button
4.     Repeat steps 1-3 with 1.58.0

**Comment by yaustar** [comment]
I can't reproduce the issue here: https://playcanvas.com/editor/scene/1596875

**Comment by yaustar** [comment]
Uploading Kapture 2022-11-23 at 16.56.35.mp4…

**Comment by eproasim** [comment]
That's strange. I get the error on my end with your project:

![image](https://user-images.githubusercontent.com/79989325/203604978-125a25f6-240c-49bd-bab9-b74625f06603.png)

Firefox only issue perhaps? .... I can confirm it works in Chrome for me.

**Comment by yaustar** [comment]
Seems to be firefox only 🤔

**Comment by yaustar** [comment]
Safari desktop is breaks :(
