### ISSUE TITLE
reprojectTexture options#seamPixels divides by 0

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#4889]
I am testing this code with NormalTangentTest.gltf and it looks strange/pixelated (the right/golden side):

![image](https://user-images.githubusercontent.com/5236548/204144606-06101e27-96d4-479e-af16-941bf24c0216.png)

But I don't know if this is related:

![image](https://user-images.githubusercontent.com/5236548/204144645-aaa6d2ab-5326-422e-98fb-e088b2280782.png)

Basically what happens is that `p` (`seamPixels`) is often 1 and then `2 - 1 * 2 == 0` which is used for division later on:

https://github.com/playcanvas/engine/blob/8127d45776234aea35dd1e12eee957e18088fb22/src/scene/graphics/reproject-texture.js#L480-L496

(this graphics stuff is way above my head, so I don't even know if the pixels are related to division by 0 here)

**Comment by kungfooman** [comment]
I investigated this a bit more, because I would like to remove every NaN / +-Infinity calculation from the engine...

First I realized that we have duplicate calculations going on:

https://github.com/playcanvas/engine/blob/7cf2b82330a85da26d970b51980f3dc3cc2212dc/src/scene/graphics/reproject-texture.js#L483-L491

To make this less abstract, lets take real numbers:

```js
const w = 512;
const p = 1;
const innerWidth = w - p * 2;
```
`innerWidth` will be `510`. Then line 489 calculates: `(innerWidth + p * 2)` ... yes, right, "calculating back" our initial `w`.

What the entire code is doing is calculations like `512 / 510`, `256 / 254`, ...

So we can simplify the code to:
```js
     uvModParam.setValue([ 
         w / innerWidth, 
         h / innerHeight, 
         -p / innerWidth, 
         -p / innerHeight 
     ]); 
```

And since we are dealing with mipmaps here, the calculation eventually reaches the point of `w == 2`...

Lets calculate: `2 / 0`... here we reach `Infinity`... then comes `w == 1`: `1 / -1 == -1`.

This snippet can be used to generate all numbers for quick debugging, just paste it in devtools:

```js
class Vec4 {
  constructor(x, y, z, w) {
    this.x = x;
    this.y = y;
    this.z = z;
    this.w = w;
  }
  toString() {
    return `${this.x} ${this.y} ${this.z} ${this.w}`;
  }
}
// calculate the number of mipmap levels given texture dimensions
const calcLevels = (width, height = 0) => {
    return 1 + Math.floor(Math.log2(Math.max(width, height)));
};
function reprojectTexture(w, h, p) {
  const innerWidth = w - p * 2; // 510
  const innerHeight = h - p * 2;
  const x = w / innerWidth;  // 510 / 512
  const y = h / innerHeight;
  const width = -p / innerWidth;
  const height = -p / innerHeight;
  let backToPixel = p * 512;
  // comment to see pixel values
  backToPixel = 1;
  if (w <= 2 || h <= 2) {
    // possible solution, just return standard values?
    // return [1, 1, 0, 0];
    // debugger;
  }
  return [
    x * backToPixel,
    y * backToPixel,
    width * backToPixel,
    height * backToPixel,
  ];
}
function generatePrefilteredAtlas() {
  const size = 512;
  let s = size / 512;
  // generate mipmaps
  const rect = new Vec4(0, 0, 512 * s, 256 * s);
  const levels = calcLevels(512);
  const data = [];
  for (let i = 0; i < levels; ++i) {
      const uvModParams = reprojectTexture(rect.z, rect.w, s);
      data.push({
        rect: rect + "",
        ...uvModParams
      });
      rect.x += rect.w;
      rect.y += rect.w;
      rect.z = Math.max(1, Math.floor(rect.z * 0.5));
      rect.w = Math.max(1, Math.floor(rect.w * 0.5));
  }
  return data;
}
console.clear();
const data = generatePrefilteredAtlas();
console.table(data);
```

Output:

![image](https://github.com/playcanvas/engine/assets/5236548/c6fb59a8-3ac3-418f-a8b4-9087453d30f1)

I wrote a little test ground to debug this issue and I wanted to understand the difference between the `uvModParams` with `seamPixels` and the ones without (simply `[1, 1, 0, 0]`):

![a](https://github.com/playcanvas/engine/assets/5236548/8a1db117-b81b-40d0-b917-590cc46da77c)

![b](https://github.com/playcanvas/engine/assets/5236548/7505f147-6c89-4463-b274-885fa6cd8b0b)

(can be opened in two tabs and then switch via Ctrl + PgUp/PgDn).

Besides the `seamPixels` movement, I couldn't see any huge difference having `Infinity` in the calculation or not.

Then I simply changed everything by hand:

![peek step change](https://github.com/playcanvas/engine/assets/5236548/8c908e61-d7f1-42f0-a7aa-11fa0230b5ae)

First row is the 512x256 mipmap, 2nd row is the 256x128 mipmap etc.

You can see initially huge differences when changing the `uvModParams`, but for the last four rows I can't see any difference any longer. Basically the mipmap is so small by then that it could contain anything.

Anyhow, detecting the wrong calculations is rather simple, just some code like:

```js
  if (w <= 2 || h <= 2) {
    use default [1, 1, 0, 0] values...
  }
```

Any thoughts how this should be handled?

Another question I have: what is/was the initial point of `seamPixels`? Is there any example (like a glTF model) I can use which requires it (or it looks wrong using [1, 1, 0, 0] as `uvModParam`? So I have some visual feedback for measuring "visual correctness" of these values.

**Comment by slimbuck** [comment]
Hi @kungfooman,

It's really simple. Each mip/roughness level has a single outline of pixels so that at render time we can sample up to the edge of the equirect without worrying about wraparound.

There are only 5 levels of mipmap on an envAtlas, so we don't have to worry about divide by zero.

My guess on the blockiness from your original post is that the normal map is compressed or similar.
