### ISSUE TITLE
Clustered Lighting causes frame stalls on Windows when renders come into view

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4892]
Project: https://playcanvas.com/project/1013489/overview/clustered-lighting-stall

Open launch tab
Click and drag the camera to the right 
When the 3 cubes come into view, the page will stall

Profile
![image](https://user-images.githubusercontent.com/16639049/204303757-22abdf77-cc78-47c4-b7ef-c5d82a7b28fa.png)

The stall does not happen when clustered lighting is disabled

WebGL report
![image](https://user-images.githubusercontent.com/16639049/204303920-a93dfbd1-787f-42f3-9191-129f2f699b27.png)

**Comment by mvaligursky** [comment]
some improvement here https://github.com/playcanvas/engine/pull/5012

**Comment by mvaligursky** [comment]
I'll close this as the delay is due to directx shader compiler, outside of our control.
