### ISSUE TITLE
Prevent an animation from starting repeatedly

### ISSUE THREAD

**Issue by albertvanveen** [playcanvas/engine#4902]
Currently the engine does not prevent that an animation is started repeatedly. This ensures that the animation cannot be played correctly, if the user starts the animation from for example the update function. The user could make a statement for each animation to prevent this, but this is not user friendly.

```
if (this.entity.anim.baseLayer.activeState != 'Walk') {
    this.entity.anim.baseLayer.play('Walk');
}
```

**Comment by yaustar** [comment]
Personally, I'm not keen on adding new API or changing default behaviour for this as you would have to handle both use cases. People who do want to restart the animation and people who don't. For the latter, having an if statement is expected in programming if you don't want something to call code under certain conditions.

**Comment by mvaligursky** [comment]
I agree with @yaustar 's comment. Closing the issue.
