### ISSUE TITLE
Alpha makes object disappear totally in certain cam-view angles

### ISSUE THREAD

**Issue by FutureFireplace** [playcanvas/engine#4909]
Alpha makes object disappear totally in certain cameraview angles. I have already tried to pre-search this/the 'Issue' list by the query: "Alpha rendering", and the issue might resemble https://github.com/playcanvas/engine/issues/1398 to some extent.

* URL to a simple, reproducible test case that illustrates the problem clearly:
https://playcanv.as/b/779b8c03

* Screenshots: video:
 (cf videos below)

* The platform(s)/browser(s) where the issue is seen: 
Chrome and Opera, maybe more

### Steps to Reproduce

In order to secure issue effect: Watch the videos for both 
Chrome: https://deshineshop.amfibios.dk/wp_shp/screen-capture-_23_.mp4
- and Opera browsers: https://deshineshop.amfibios.dk/wp_shp/screen-capture-_24_.mp4
[ps: put up as temp. local servervideos; as I did not bother to make YouTubeversion]

NB: This is quite crucial for a project I have, as the effect relies/combines with a refraction effect (API-adjusted to version 1.55).
The effect uses a shader-chunk that is somewhat better than the recent (still postively/good initiative :-) ) "Dynamic Refraction" setting in the editor.

**Comment by yaustar** [comment]
Can you share the original project please?

Is it just the transparent cup that you are referring to?

**Comment by FutureFireplace** [comment]
https://playcanvas.com/editor/scene/1605543

 - just the cup

**Comment by yaustar** [comment]
This is a classic case of the transparent mesh rendering order issues and is not a bug per say. 

The cup is made up of two meshes as you can see here: 
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/16639049/205679640-90cfd899-b856-469c-8b6c-b6e2b37701ac.png">

And depending on the camera angle, it's rendering in a different order based on the bound boxes distance from the camera.

The straightforward workaround here is to always render the inner mesh before the outer one via layers which is much easier to do with the import hierarchy workflow with render components and what I'm using in this fork.

https://playcanvas.com/project/1016215

https://user-images.githubusercontent.com/16639049/205681723-1314e813-639a-4cc5-a020-17abf6dd9873.mp4




The model component is designed only to have all meshinstances on the model on the same layer(s).
