### ISSUE TITLE
Change the default values of standard material properties.

### ISSUE THREAD

**Issue by querielo** [playcanvas/engine#4938]
Currently, [these properties](https://github.com/playcanvas/engine/blob/main/src/scene/materials/standard-material.js#L1098) have hardcoded values that cannot be redefined for an entire scene or an application. This becomes especially problematic when working with models that are loaded dynamically from .glb-files in different places, as we are required to redefine the properties in each instance to keep values consistent.

It would be extremely useful to have the ability to change the default values of these properties, as it would allow for more flexibility and efficiency in our workflow.

Thank you for considering this request.

Current workaround: load a script right after the engine that redefines [the reset method ](https://github.com/playcanvas/engine/blob/main/src/scene/materials/standard-material.js#L556) of StandardMaterial

```js
const oldReset = pc.StandardMaterial.prototype.reset;
pc.StandardMaterial.prototype.reset = function reset() {
    oldReset.apply(this);
    
    this[`_${YOUR_PROPERTY}`] = PROPARTY_VALUE;
};
```

**Comment by slimbuck** [comment]
Hi @querielo ,

What values are you changing across the board? StandardMaterial is used by the engine internally too so changing defaults might impact more materials than you think.

Thanks

**Comment by querielo** [comment]
> Hi @querielo ,
> 
> What values are you changing across the board? StandardMaterial is used by the engine internally too so changing defaults might impact more materials than you think.
> 
> Thanks

It was `_useSkybox`. Yes, it disables environment lighting for all StandartMaterials, so we enable it ourselves everywhere where we need it. So, for us it is easier to have a whitelist than a blacklist :-)

**Comment by slimbuck** [comment]
We discussed this internally and thought that handling asset.on('load') or similar is probably the correct way to do this (meaning you're modifying your scene assets, not everything globally).

Is there a reason you don't follow this approach?

**Comment by querielo** [comment]
Right now, we modify everything globally as a hack:

1) there are too many assets (maybe, thousand),
2) many of them shouldn't reflect the skybox and have `reflectivity = 1`. To fix all of them needs time.

**Comment by querielo** [comment]
It works for us in many cases because we use .glb-files in different places :-) So, there are 3 solution right now.

1) the hack that I described before
2) set correct values after the asset is loaded (time consuming)
3) fix all assets/.glb (time consuming). In our TODO.

**Comment by mvaligursky** [comment]
I'll close this as I don't think changing the default values for a material is a way to do what you need. This would affect internal materials, for example used by UI system as well, which is not desirable.
