### ISSUE TITLE
assets.load and assets.loadFromUrl to return XHR object if one created internally

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#494]
If assets.load or assets.loadFromUrl makes an XHR, it would be good to return it, otherwise return `null`.
This will allow users to have more control over loading progress enabling them with two actions:
1. Ability to `abort` loading of an asset.
2. Ability to show `progress` of XHR request.

**Comment by probitaille** [comment]
I want to raise some interest about this feature. 

I asked for this feature in the [forum](https://forum.playcanvas.com/t/is-it-possible-to-get-the-progress-of-a-loading-when-using-assetregistry-loadfromurl/15165) today. I would like to see that implemented in the engine.

**Comment by yaustar** [comment]
Closing in favour of https://github.com/playcanvas/engine/issues/2021
