### ISSUE TITLE
Vertex Buffer is using old graphics device API

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#4965]
If one uses `pc.createMesh()`, it would crash here, since `createVertexBufferImpl` was moved out from the graphics device.
https://github.com/playcanvas/engine/blob/0a103d9934372749aba3f27076eecb7744c15b07/src/platform/graphics/vertex-buffer.js#L32

**Comment by LeXXik** [comment]
Actually, looking closer, it seems like it is a vertex buffer, rather than a graphics device. Somewhere a wrong argument is passed probably.

**Comment by mvaligursky** [comment]
Is there some repro for this?

**Comment by LeXXik** [comment]
@mvaligursky I've made one here:
https://playcanvas.com/project/1027097/overview/create-mesh-issue

**Comment by mvaligursky** [comment]
the problem is that pc.createMesh takes a graphicsDevice as first parameter, which you're not supplying, and so it uses an array of positions as a device. And that does not have createVertexBufferImp.

pc.createMesh(positions, normals, tangents, uvs, indices);
