### ISSUE TITLE
Clustered lighting not rendering correctly on Samsung Exynos devices

### ISSUE THREAD

**Issue by AaronLigthart** [playcanvas/engine#4969]
Hi there
Since the release of engine version 1.59.0 when I create a build of my game, Lightning doesn’t render when launching the game on my samsung galaxy s8 or the s20, it’s all dark.
The issue does not appear on desktop or on iPhone and xiomi devices.
Currently, I can resolve the issue by building the game with engine version 1.58.2.

I tried to reproduce the issue with a blank project, but I was not able to reproduce
the issue. Maybe it’s due to our game including mesh generation? but some obstacles are basic playcanvas cubes and those are affected aswell.
Build: https://playcanv.as/b/0146c1a2

latest engine result:
![image](https://user-images.githubusercontent.com/5719804/212042928-dfeccd8a-b10c-4348-9b9e-ad5a662b5f91.png)

older engine result:
![image](https://user-images.githubusercontent.com/5719804/212042850-51a56a48-7eba-49ca-b352-47782ff73733.png)

**Comment by yaustar** [comment]
Does the Samsung device use the Snapdragon or Exynos chipset? Can you share the exact model number please?

**Comment by yaustar** [comment]
Reproduced on Exynos Samsung devices including a Samsung SM-A510F https://www.gsmarena.com/samsung_galaxy_a5_(2016)-7789.php

Cannot reproduce on Samsung Snapdragon devices

**Comment by yaustar** [comment]
After bisecting the commits, this looks like to be the breaking change: https://github.com/playcanvas/engine/pull/4863

It's odd that it worked for you on 1.58.2 as that was broken for me too. There would be times when the lighting looked correct but wasn't.

@AaronLigthart How many lights do you have in the scene? If only a couple and they are always on, the short term workaround for you would be to disable clustered lighting for now

**Comment by yaustar** [comment]
I found that https://playcanvas.github.io/#/graphics/clustered-area-lights has similar issues with lighting on those devices and the same #4863 PR is the breaking change.

Could be related to the particles issue we had before @mvaligursky https://github.com/playcanvas/engine/issues/3460

**Comment by AaronLigthart** [comment]
@yaustar we only have 2 lights in the scene, both omni types. 
one on the player:
![image](https://user-images.githubusercontent.com/5719804/212199670-ed3e2073-6b86-49fe-9a57-ef81315d35e8.png)
and one on an object in the level. I did notice the parent has a scale of 4,4,4 wich should not matter for the lightning component but noted it just in case.
![image](https://user-images.githubusercontent.com/5719804/212199885-5ada8835-a6f1-46f9-8485-799019f087c2.png)

**Comment by leonidaspir** [comment]
I can reproduce this on a similar device (Samsung Galaxy S10 Exynos), both on the PlayCanvas engine examples that use clustered lights and our own projects.

Older engine version (<= 1.58.2) don't have this problem on this device, work as expected.

https://user-images.githubusercontent.com/29543178/216645925-b83ba6d1-7015-4d32-b126-4970690e95b9.mp4

**Comment by yaustar** [comment]
Interesting that an order version of the engine doesn't have this issue 🤔

**Comment by mvaligursky** [comment]
I swapped to use fetch() instead of texture() to read data from relevant textures, which should avoid issues like this, as we specify pixel coordinates, instead of normalized coordianates. I'll have to investigate at some point soon, but this feels like a driver issue or similar.

**Comment by mvaligursky** [comment]
Guys - thanks for the report. If you could test it on your devices I would really appreciate it. Please use this engine version, which contains the fix: https://code.playcanvas.com/playcanvas-latest.dbg.js

@AaronLigthart  @leonidaspir 

And reopen if the issue is not gone for you.

**Comment by leonidaspir** [comment]
Is there a way to use a custom engine version on the engine examples site without rebuilding?

**Comment by yaustar** [comment]
From the other ticket: https://github.com/playcanvas/engine/issues/5074

Without Fix: https://playcanv.as/b/b1e7ea8b
With Fix: https://playcanv.as/b/71b81140

**Comment by leonidaspir** [comment]
Yes, the build with the fix Yaustar shared works as expected on my Samsung Galaxy S10 (Exynos).

![image](https://user-images.githubusercontent.com/29543178/220638777-58cee95a-4b50-4454-8e19-a4f97d695b76.png)

**Comment by leonidaspir** [comment]
Re-opening, clustered lighting is not working (this time at all) in latest v2 PlayCanvas engine, testing on a Samsung A71 (Snapdragon 730). There is no error or warning in the phone browser console.

![Image](https://github.com/user-attachments/assets/b3601450-102e-4d9c-af73-940c69263787)

Turning clustered lighting off in editor makes light work as expected.
