### ISSUE TITLE
pc.Picker decides to pick or not by material.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#497]
[Current implementation](https://github.com/playcanvas/engine/blob/56fec1e7c3ad609eb246ef92dc11b2b1c8c3aa9a/src/scene/pick.js#L171) checks if meshInstance has BasicMaterial or PhongMaterial on it, otherwise it will not treat it as pickable.
This is quiet limiting to cases with custom shaders and custom materials.
Consider changing this with account to things that should not be picked - such as particles I guess.

**Comment by daredevildave** [comment]
No longer applicable
