### ISSUE TITLE
How to detect WebXR passthrough on VR devices like the Quest vs a phone

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#4973]
Now that there is WebXR passthrough on VR devices, we need to be able differentiate between whether the user is on a phone or a VR headset

This is because it is common to have screen space UI for AR experiences on phones but of course that doesn't translate well for VR devices. So we will need to be able know what the difference between the two would be to set up the scene in the 'correct' way.

**Comment by Maksims** [comment]
If device supports DOM Overlay and/or has only 1 XR view, it is safe to use screen space UI.
Although there is no currently a way to find out the number of XR views.

**Comment by yaustar** [comment]
@Maksims Is there a way to know this before entering the XR session?

**Comment by yaustar** [comment]
Tested on the Quest 1 and `window.XRDOMOverlayState` is available there so using XrDomOverlay.supported is not possible 🤔

**Comment by yaustar** [comment]
Interestingly, although `ontouchstart` is available on the Quest headset, `navigator.maxTouchPoints` is 0 so I could use that as a way check if the user is on the VR headset

**Comment by Maksims** [comment]
> @Maksims Is there a way to know this before entering the XR session? (eg DOM overlay)
> 
> ie, is this available before going into the session? https://developer.playcanvas.com/api/pc.XrDomOverlay.html#available

Yes, this flag is available before session start. Bear in mind, there could be a device that supports DOM Overlay and pass-through. So the best would be to detect number of views during the session.

Checking device capabilities - is difficult due to fingerprinting concerns of web APIs.

**Comment by yaustar** [comment]
> Yes, this flag is available before session start. Bear in mind, there could be a device that supports DOM Overlay and pass-through. So the best would be to detect number of views during the session.

Yeah, I found out that the Quest supports this as well as ontouchstart.

Looking at AFrame, they check the user agent instead to know if they are on a VR headset or not: https://github.com/aframevr/aframe/blob/master/src/utils/device.js

**Comment by yaustar** [comment]
Related thread: https://twitter.com/Tojiro/status/1617654460846837760

**Comment by yaustar** [comment]
Looks like the recommend way to do this is to use the official API:

```
if (this.app.xr.session.interactionMode  === "world-space") {
  // draw UI in the world
} else {
  // draw UI directly to the screen
}
```

This can be used on the callback of starting the XR session in the PlayCanvas API
