### ISSUE TITLE
pc.createMesh to accept COLOR and UV1

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#498]
Currently `pc.createMesh` does not allows to add color and uv1 data to vertex buffer.
It would be good to add those to support all possible attributes with this method.

**Comment by willeastcott** [comment]
@guycalledfrank has added support for UV1 to pc.createMesh. The function now just needs vertex color support for your feature request to be fulfilled @Maksims. Feel free to add it if you get a second, @guycalledfrank.

**Comment by Maksims** [comment]
Added in #532
