### ISSUE TITLE
Loading GLBs doesn't show vertex colours

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#5007]
Forum https://forum.playcanvas.com/t/vertex-color-doesnt-show-on-compressed-glb

Our viewer: 
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/16639049/214825890-c58e75c7-e206-4d98-857f-5777cddc6342.png">

Babylon viewer
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/16639049/214825909-bd2b8a6a-23cd-410b-9153-6b0e6aabb1d3.png">

**Comment by slimbuck** [comment]
I believe this only happens when the model is draco compressed.
