### ISSUE TITLE
Triplanar material support

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#5009]
To help speed up model import workflows, especially from other sources like CAD models etc where UV maps are not available, triplanar material can help

**Comment by mvaligursky** [comment]
I don't think this will be a core feature of the engine. When we have a new material type (which we're working on), where you can specify a single front-end shader code, it will be likely just a shader specified this way, so an asset.

**Comment by yaustar** [comment]
Forum post of someone implementing this: https://forum.playcanvas.com/t/triplanar-texture-mapping-code/19725

**Comment by slimbuck** [comment]
Probably best done with planned custom material / shader editor.

**Comment by mvaligursky** [comment]
I'm closing this, as this will not be part of the engine.
