### ISSUE TITLE
Application World Gravity being set on every update

### ISSUE THREAD

**Issue by MushAsterion** [playcanvas/engine#5018]
Fixes: #5018

Hello,

I noticed that the `RigidBodyComponentSystem` class had something going on with gravity setting on its `onUpdate` function. In fact due to some weird stuff from Ammo.js, when the world gravity is set using `this.dynamicsWorld.setGravity(gravity)`, Ammo set it to something close but not exactly the given vector which leads to making this following check always true, setting a new gravity on every update instead of changing it when there is an actual real gravity change on the application.
 
 
https://github.com/playcanvas/engine/blob/6b1a93a7c2dc19f48c70c201100ffdf6e07d5358/src/framework/components/rigid-body/system.js#L868-L873
 
 
Would it be possible to make it a distance check instead? From what I saw on Ammo.js is having a precision around 0.001 or  0.0001, so a code like this should fix the issue:

```JS
const gravity = this.dynamicsWorld.getGravity();
if (this.gravity.distance({ 'x': gravity.x(), 'y': gravity.y(), 'z': gravity.z() }) > 0.001) {
    gravity.setValue(this.gravity.x, this.gravity.y, this.gravity.z);
    this.dynamicsWorld.setGravity(gravity);
}
```
 
 
I was working on a script where I need to disable the world gravity for an entity unfortunately I checked within the Bullet code and as this `setGravity` function is setting individual entity gravity to all entities it overwrites my entity's gravity every update...
 
 
Thank you very much for the consideration and your work!

**Comment by LeXXik** [comment]
Most probably you are simply losing precision when setting the world gravity. If you do any math operations on PlayCanvas gravity vector in your script, the components will have float64 numbers, which then get converted to float32 when applying to Ammo, which ends up losing precision and having a mismatch between Ammo and PC vectors. If that is the case, you should convert your gravity components to float32 values. You can use `Math.fround` for that.
