### ISSUE TITLE
 lot of lags in mobile 

### ISSUE THREAD

**Issue by moshiuzzaman** [playcanvas/engine#5067]
I try to create a car configurator like [BMW i8](https://playcanv.as/p/RqJJ9oU9)
my project link [Configurator](https://playcanvas.com/editor/scene/1656382)
now I discuss my problem.

my project a lot of lags in mobile but BMW i8 is so smooth in mobile. how i solve this?
can anyone give me BMW i8 project editor link or smeller project link?

**Comment by mvaligursky** [comment]
Can you please come and discuss this and get help on the support forum: https://forum.playcanvas.com/
Issues here are for logging bugs and feature request for the engine.
