### ISSUE TITLE
Clustured Lighting Bug on Android (tested on Chrome at Huawei P30 Pro, and S8)

### ISSUE THREAD

**Issue by Rechi86** [playcanvas/engine#5074]
See the forum post for additional infos and demo scene:
https://forum.playcanvas.com/t/clustured-lighting-bug-on-android-tested-on-chrome-at-huaweii-p30-pro-and-s8/29695

**Comment by yaustar** [comment]
Maybe related to https://github.com/playcanvas/engine/issues/4969

@Rechi86 please can you post the exact model numbers/skus for the devices please as different countries can have different SoCs

**Comment by yaustar** [comment]
Interesting, looks like they are all ARM based 🤔 

To help us isolate as we don't have access to some of the devices, can you check the examples linked in this post on the Huawei device please? https://github.com/playcanvas/engine/issues/3460#issuecomment-987039558

**Comment by Rechi86** [comment]
Both particle examples work on the p30 and s8,
an example which didn't work during my tests was this:
https://playcanvas.github.io/#/loaders/glb (only blue light on my devices)
I hope this helps, if I should test anything else just let me know.

**Comment by mvaligursky** [comment]
this has been fixed by https://github.com/playcanvas/engine/pull/5093 and will be part of the engine release in the near future.
