### ISSUE TITLE
Create a central place where we sniff the userAgent instead of all over the place

### ISSUE THREAD

**Issue by vkalpias** [playcanvas/engine#508]
We are currently checking which browser the user is using in lots of different places in the engine. We should instead do this once and have a simple API to get the current browser.

**Comment by daredevildave** [comment]
Use [core/platform.js](https://github.com/playcanvas/engine/blob/master/src/core/platform.js)

**Comment by mvaligursky** [comment]
both the browser and platformName is now exposed, closing.
