### ISSUE TITLE
Massive Frame Rate Lag Issue in 1.61.x (WebGL 2.0 on Mac / iOS)  (< 10 FPS for Box Tween) 

### ISSUE THREAD

**Issue by Mann1ng** [playcanvas/engine#5087]
### Description

We're encountering a significant drop in frame rate and frame consistency with engine 1.61 compared to 1.60 (tested) on iOS and Mac (only) using Chrome and Safari -- when using WebGL 2.0.

It was only just seen yesterday (21-Feb-2023)  with jerky animations  on GLB and FBX and also now reproducible in simple tweens.

In the following demo project, when (testing on Macbook Pro (2021)) using engine 1.60 we see a smooth tween, but running latest engine (1.61.x) shows very lag prone FPS 'jerkiness'. 

I assume the issue is something with in the engine (and perhaps an apple update which effects browsers).

Demo link using latest [broken] :
https://launch.playcanvas.com/1668948?debug=true

Demo link using 1.60 [smooth] :
https://launch.playcanvas.com/1668948?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-1.60.0.js

Browsers tested on: Safari (Mac & iOS), Chrome (Mac). It appears fine on Windows.

Video of Issue:
https://etheria.co/share/playcanvas-fps-lag-issue-1.61.x/playcanvas-lag-issue_1.61.x.mp4

WebGL 2.0 Report:
https://etheria.co/share/playcanvas-fps-lag-issue-1.61.x/WebGL2.0%20Report.pdf

WebGL 1.0 Report:
https://etheria.co/share/playcanvas-fps-lag-issue-1.61.x/WebGL1.0%20Report.pdf

### Steps to Reproduce

1.  On a Mac or iPhone open the above link https://launch.playcanvas.com/1668948?debug=true
2. Play project
3. Notice frame issues

**Comment by slimbuck** [comment]
Hi @Mann1ng ,

Thanks for this detailed repro!

We're aware of a performance regression in 1.61 and will get a fix out ASAP.

Thanks

**Comment by Mann1ng** [comment]
Thanks guys - incredible turnaround, and we are all really appreciating all your awesome work on PlayCanvas.
