### ISSUE TITLE
json documentation

### ISSUE THREAD

**Issue by andreasplesch** [playcanvas/engine#509]
playcanvas uses a json format as a native format to load and export models and scenes. Is there a full description of the json format which the playcanvas engine can parse and render ? I was only able to find the json files used in the examples as a guide but they use only a small feature set.
I do not have or want fbx or collada descriptions of models. I rather would like to generate json directly. What would be the best approach in this situation ?

**Comment by willeastcott** [comment]
Hi there. I just wrote this for you:

http://developer.playcanvas.com/en/user-manual/graphics/file-format/

What do you think?

**Comment by andreasplesch** [comment]
This looks really nice and is a great start. I imagine a complete description is a major job but would enable others to produce exporters. Materials next ?
