### ISSUE TITLE
Fix particle system API documentation

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#5095]
```
 * @property {pc.CurveSet} localVelocityGraph Velocity relative to emitter over lifetime.
 * @property {pc.CurveSet} localVelocityGraph2 If not null, particles pick random values between localVelocityGraph and localVelocityGraph2.
```

This is incorrect as localVelocityGraph2 cannot be null. If a non randomised graph is needed, both localVelocityGraph and localVelocityGraph2 needs to be set to the same graphset

**Comment by willeastcott** [comment]
The API documentation is correct. Closing...
