### ISSUE TITLE
Add hyperlinks to references or inline lists

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5096]
The following descriptions have a **(see pc.INDEXFORMAT_*)** references:
[pc.IndexBuffer Constructor](https://developer.playcanvas.com/en/api/pc.IndexBuffer.html#IndexBuffer)
[pc.IndexBuffer.getFormat](https://developer.playcanvas.com/en/api/pc.IndexBuffer.html#getFormat)
Same in [pc.VertexBuffer](https://developer.playcanvas.com/en/api/pc.VertexBuffer.html) with **(see pc.BUFFER_*)**.

Make them as links, so those can be clicked. Or add those inline, as in [pc.VertexFormat](https://developer.playcanvas.com/en/api/pc.VertexFormat.html#VertexFormat).

**Comment by willeastcott** [comment]
Fixed by #2331.
