### ISSUE TITLE
Add vector + scaled vector math

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5114]
A feature request here.

I know, we don't want to bloat the vector math with convenience methods. However, this one I found I am using too often. Almost every time I do any vector math - when I am trying to add a scaled vector (without changing the original) to another vector.

Normally, one would do something like:
```js
// a + b*2;
const temp = new pc.Vec3();
temp.copy(b).mulScalar(2).add(a);
```

It requires you to allocate a temp vector, if you don't want to change the original. The only way to avoid allocation, you'd need to do a component wise writeout, which is verbose and would better be as part of the vector math methods:

```js
a.addScaled(b, scalar);

// where
a.x += b.x * scalar;
a.y += b.y * scalar;
a.z += b.z * scalar;
```

**Comment by mvaligursky** [comment]
Definitely could be useful.
You can also add a function to your Vec3 prototype, but agree, not as convenient.

**Comment by kungfooman** [comment]
Often it's even more "specialized": offset an existing point with a scaled normal

Example:

```js
pc.Vec3.prototype.mulAdd = function (a, s, b) {
    this.x = a.x + s * b.x;
    this.y = a.y + s * b.y;
    this.z = a.z + s * b.z;
}
const start = new pc.Vec3(100, 200, 300);
const normal = new pc.Vec3(0, 1, 0);
const end = new pc.Vec3();
end.mulAdd(start, 20, normal);
```

(the engine code itself is a good "test suite" for testing generic methods, so the extra methods can show how they shorten existing code in a potential PR)

**Comment by LeXXik** [comment]
@kungfooman I think your example is similar to my first snippet, where you are using a third vector to store the product. I personally prefer the chain variant, though, as it is self-explanatory of the operands in use just by following the chain. Not sure there is a benefit over current API:
```
const temp = new pc.Vec3();
temp.copy(normal).mulScalar(20).add(start);
```

I think `addScaled` would be more generic in this case, as it will be up to developer to decide if a third vector storing the product to be allocated or not.

**Comment by kungfooman** [comment]
So now you prefer the chain variant and apparently have no problem using a temporary vector, why are you proposing a change?

Or what exactly does it make simpler? Like a real-life example of situations you encounter too often.

**Comment by LeXXik** [comment]
Sorry for not being clear :D What I meant is I do prefer the chain one over your suggested `.mulAdd(vec, scalar, vec)`, because both require a third vector, but a chain one is easier to read.

My proposal is to add a `.addScaled(vec, scalar)`. Which modifes the target vector in place, but doesn't create a temporary vector that holds a scaled one.

If we take your example, where I'd like to change the position of a point by some scaled normal, it would be:
```js
position.addScaled(normal, 20);
```
The benefit here, is I only use 2 vectors to end up with the same result as in your example, which uses 3.

**Comment by kungfooman** [comment]
No problem, I just want to hash it out a bit and that's why I asked for real life examples.

Because in most cases I feel that you usually have a starting point, so your example "in full" would still require chaining aswell:

```js
position.copy(start).addScaled(normal, 20);
```

But yes, I see your point, `addScaled` is a little bit "smaller" which by nature should apply to more situations.

**Comment by LeXXik** [comment]
You are correct there, it depends on case by case. It would be up to the developer to decide, whether a temp vector is needed. At least we give a choice. For example, this is a valid case as well:
```js
const pos = entity.getPosition();
pos.addScaled(normal, 20);
entity.setPosition(pos);
```
