### ISSUE TITLE
Mouse event listeners are attached to the window 

### ISSUE THREAD

**Issue by querielo** [playcanvas/engine#5125]
As you can see [here](https://github.com/playcanvas/engine/blob/5a22ee6e885d5f9f880214e7fb96711abd542b95/src/platform/input/mouse.js#L91) mouse event listeners are attached to `window`. Should it be attached to the element that is passed to the function as the parameter?

**Comment by yaustar** [comment]
That does seem wrong 👀 It seems quite old code so may have to wait until @willeastcott can answer if there was a specific reason for it.

**Comment by yaustar** [comment]
Here is the original PR that changed it from using `element` to `window`

https://github.com/playcanvas/engine/commit/7dcc7dcc769ba8cae65167906aea74629d8152ad

**Comment by Maksims** [comment]
It should be on window, because events that will happen over other elements, will propagate to the window, but not to the canvas element.
E.g. mousemove will not trigger if mouse is moved over other DOM element when subscribing to canvas element.
Same for down, up and wheel events.
Keyboard events - same story, they will not trigger if canvas element is not in focus, leading to issues. It is easier to check if keyboard event happened while focused over input element, than catch only when focusing canvas element and then try to subscribe to keyboard events on other DOM elements within a page.

**Comment by yaustar** [comment]
I'm in line with querielo. Seems odd that it was forced at engine level rather than passing it via boilerplate code

**Comment by kungfooman** [comment]
> I'm not sure that the engine has to force usage neither canvas element nor window. Window can be used as a default target.

`window` is not an `Element` and it lacks properties like `clientWidth` which are requested for example here:

https://github.com/playcanvas/engine/blob/5a22ee6e885d5f9f880214e7fb96711abd542b95/src/platform/input/mouse.js#L298-L304

So I feel you will start calculating around with `undefined`, but I didn't test it.

![image](https://user-images.githubusercontent.com/5236548/224010637-9e0fdf73-0596-4594-9e71-350d36b7b21f.png)

**Comment by querielo** [comment]
> `window` is not an `Element` and it lacks properties like `clientWidth` which are requested for example here:

Nice catch. You are right.

But the main point is not about "`window` vs `document.body`". It is about forcing usage some global element instead of the target element that is passed to the attach method.

**Comment by kungfooman** [comment]
> But the main problem is not about "`window` vs `document.body`". It is about forcing usage some global element instead of passed one into the `attach` method.

I already pointed it out, it is not "some global element", it is THE source of mouse events once the mouse leaves the browser window for example. You can only substitute `window` with a "normal" element to a certain degree.

**Comment by yaustar** [comment]
@kungfooman If we changed mouse input (and related events) to be able use either `element` or a `window` and let the user decide what to use, would that handle your concern?

**Comment by kungfooman** [comment]
> @kungfooman If we changed mouse input (and related events) to be able use either `element` or a `window` and let the user decide what to use, would that handle your concerns?

I don't really have too many concerns here, I just can't see the real issue so far.

So I wonder: why do we need to change anything? What doesn't work that should work? Is this fixing any reported issues?

**Comment by querielo** [comment]
Sure, I'm not insisting on finding a solution. The problem I encountered was the inability to prevent mouse events from being transmitted to ScriptComponents through an element that partially covers the canvas. Unfortunately, the problem cannot be solved with typical HTML stuff.

**Comment by querielo** [comment]
Yes. We can do it. But in our case it is a hacky solution, since we have to pass events to some elements and prevent passing events to other elements based on different events. 

So, we redefine the engine Mouse class by a custom Mouse class that has changed the `attach` and `enablePointerLock` methods.

**Comment by willeastcott** [comment]
This hasn't been updated in a few days. Are there any active proposals here for changes to the engine? Or are we sticking with what we have and closing this?

**Comment by querielo** [comment]
If somebody needs to change the behavior they can
1. copy/paster Mouse.js into a Playcanvas project.
2. replace
  a. `window` => `target` in `attach`
  b. `this._target.requestPointerLock` in `enablePointerLock`
3. add 
```js
pc.Mouse = Mouse;
if (pc.app.mouse && pc.app.mouse._target) {
    pc.app.mouse = new Mouse(pc.app.mouse._target);
}
```

I think I close the issue.

**Comment by kungfooman** [comment]
> 2\. a. `window` => `target` in `attach`

In `Mouse#detach` too, I don't know if you do that during the life cycle, just to be on the safe side
