### ISSUE TITLE
Improve engine only example

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5142]
This is an enhancement request.

We have a physics engine-only example with compound shapes (falling chairs). 

Currently every part of every chair takes one draw call. This brings the example into hundreds of draw calls, making it hard to render on low end devices. 

We should improve the example using batching.

**Comment by mvaligursky** [comment]
I considered this few times with multiple examples, that would benefit from batching .. but so far, to keep the examples as simple and focused as possible, I didn't add batching.

**Comment by LeXXik** [comment]
Perhaps we could consider some "batchless" example that would still demonstrate the feature, but would not get us over 100 draw calls.
