### ISSUE TITLE
GraphicsDevice.setBlendState for drawQuadWithShader

### ISSUE THREAD

**Issue by SashaRX** [playcanvas/engine#5146]
No way to change blend mode when rendering to texture. This is function needed for some post effects like bloom, for accumulation Upscale buffer

**Comment by mvaligursky** [comment]
You need to do something like this for example just before calling the drawQuadWithShader:

```
// the next line would not be called per frame
const blendStateAdditive = new BlendState(true, BLENDEQUATION_ADD, BLENDMODE_ONE, BLENDMODE_ONE);

// and these are per frame
device.setBlendState(blending ? blendStateAdditive : BlendState.DEFAULT);
drawQuadWithShader(...);
```

See more here: https://github.com/playcanvas/engine/pull/5083

I'll close this, as I believe this should solve your problem, but please reopen if you have further issues with this.

**Comment by SashaRX** [comment]
I get error in console pc.BlendState is not a constructor

const blendStateAdditive = new pc.BlendState(true, pc.BLENDEQUATION_ADD, pc.BLENDMODE_ONE, pc.BLENDMODE_ONE);
or
const blendStateAdditive = new BlendState(true, BLENDEQUATION_ADD, BLENDMODE_ONE, BLENDMODE_ONE);

it still doesn't find the constructor BlendState

**Comment by mvaligursky** [comment]
Hmm, ok I assumed you're using a main branch of the engine (this is a recent development, not released as part of the official release yet).

If you're using engine 1.61.3 or older, this is different (and will change to what I mentioned above when 1.62 gets release sometimes probably next week).

You need something like this in the meantime:

```
device.setBlendFunction(BLENDMODE_ONE, BLENDMODE_ONE);
device.setBlendEquation(BLENDEQUATION_ADD);
```

**Comment by SashaRX** [comment]
Does not work in the current release, I will wait for 1.62
Temporary solution for me additional blend render targets
Thanks Martin!

**Comment by mvaligursky** [comment]
What specifically does not work?
We use accumulation buffer with custom blend modes, and it works with both engines, using APIs I mentioned.

**Comment by SashaRX** [comment]
this.scope.resolve("srcTexture").setValue(this.bloomRT[u].colorBuffer);

            this.device.setBlendFunction(pc.BLENDMODE_ONE, pc.BLENDMODE_ONE);
            this.device.setBlendEquation(pc.BLENDEQUATION_ADD);

            pc.drawQuadWithShader(this.device, this.bloomRT[u - 1], mUpsampleShader, true);

with this code, accumulation does not occur

**Comment by mvaligursky** [comment]
In that case I do not expect BlendState to fix it, as it provides equivalent functionality using different API.
Have you tried using Spector JS to inspect what goes on?

**Comment by SashaRX** [comment]
[
![image](https://user-images.githubusercontent.com/6702929/225101724-2fc40273-5816-40dd-a4fc-4e677963f4fe.png)
](url)

**Comment by mvaligursky** [comment]
right, so changing blend mode works then?

**Comment by SashaRX** [comment]
```
  this.device.setBlending(true);
  this.device.setBlendFunction(pc.BLENDMODE_ONE, pc.BLENDMODE_ONE);
  this.device.setBlendEquation(pc.BLENDEQUATION_ADD);
```

it's code work!
