### ISSUE TITLE
Enabling Max Pixel Ratio causes apps to render to quarter of the screen on iOS

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#515]
If you enable 'Max Pixel Ratio' in the engine, iOS renders a quarter of the screen.

Here's how it sometimes looks:

![image1](https://cloud.githubusercontent.com/assets/697563/12827959/0e44d15e-cb7a-11e5-9d40-40482d3e04bd.PNG)

Here's how it should look:

![image2](https://cloud.githubusercontent.com/assets/697563/12827977/1f9cb5ca-cb7a-11e5-874c-09c23d146f5e.PNG)

Seems to happen more reliably when a PlayCanvas app is saved to home screen. But it can happen in Launcher too (or a published app run in the regular Safari browser).

**Comment by Maksims** [comment]
Please provide more detailed description of how to replicate and what is wrong.

**Comment by guycalledfrank** [comment]
Happens if you change from portrait to landscape mode. Seems like a bug, yeah.

**Comment by willeastcott** [comment]
How are you reproducing this, @guycalledfrank?

**Comment by guycalledfrank** [comment]
- Enable "device pixel ratio" in scene settings;
- Run in portrait;
- Rotate the phone to landscape.

OR you can run in landscape (it's fine), rotate to portrait, then switch again to landscape - bugged

**Comment by Maksims** [comment]
Can we verify this is still an issue?

**Comment by willeastcott** [comment]
Fixed in iOS 10.
