### ISSUE TITLE
Diffuse Only Light feature 

### ISSUE THREAD

**Issue by figo2264** [playcanvas/engine#5157]
Provide as much information as possible. Include (where applicable):

[https://playcanvas.com/editor/scene/1692776](url)

![image](https://user-images.githubusercontent.com/13344642/225662703-e1fccf70-97aa-49bf-8e98-70d2a47f7dcb.png)

The light reflection looks okay in some case, but it's not fine when it comes to high quality product rendering.

It will be great if we can use Diffuse Light Only without giving up specular.

Hoping this feature is available soon.

**Comment by figo2264** [comment]
No..those white reflection shouldn't be there.

**Comment by mvaligursky** [comment]
Ok that makes sense .. so you're after lights that only add diffuse, which is not physically correct but I see how it would be useful.

**Comment by yaustar** [comment]
Speaking to @GSterbrant, if you would like to look more into the engine on where this is done, it would be in the lighting shader chunks: https://github.com/playcanvas/engine/tree/main/src/scene/shader-lib/chunks/lit/frag

More specifically, the Specular related chunks.

**Comment by slimbuck** [comment]
Hi @figo2264, to disable specular highlight on a material override the chunk like so:
```javascript
const disableSpec = `
float getLightSpecular(vec3 h, vec3 reflDir, vec3 worldNormal, vec3 viewDir, vec3 lightDirNorm, float gloss, mat3 tbn) {
    return 0.0;
}
`;

material.chunks = {
    lightSpecularBlinnPS: disableSpec
};
```

**Comment by figo2264** [comment]
@slimbuck thanks. actually I was adjusting values of the same shader chunk.  I will try on just returning 0.0 value.

**Comment by mvaligursky** [comment]
The main reason spot and omni lights do not support this in the current release is that we'd need to add the data to light texture, and as currently all channels are used, we'd need to add additional texture read for this.

(Ideally forWebGL2 and WebGPU we would add a bit flag though to work around this, but that's more work that has not been done yet)
