### ISSUE TITLE
app.keyboard.wasPressed(pc.KEY_DELETE) always returns false

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#516]
The wasPressed function never returns true on releasing the DELETE key.

**Comment by willeastcott** [comment]
I notice our keyboard handling code reference the keyIdentifier property. According to MDN, this is deprecated so I guess we should update:

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyIdentifier

**Comment by willeastcott** [comment]
On Chrome (Windows), the keypress event has a keyIdentifier of 'U+007' but when was pressed is called, it's looking for 'Delete' in the keymap, not 'U+007'.

**Comment by vkalpias** [comment]
Should be fixed in https://github.com/playcanvas/engine/commit/90b53a1854d213455a6ae336acee52d89cad7706

**Comment by willeastcott** [comment]
Confirmed.
