### ISSUE TITLE
Implement ground-projected skydome

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5160]
We have a solution in some examples, but it'd be great to make it integrated in the Engine (and Editor) to make it easy to use.

https://twitter.com/willeastcott/status/1579461802555215874?lang=en-GB

<img width="569" alt="Screenshot 2023-03-16 at 16 46 25" src="https://user-images.githubusercontent.com/59932779/225692215-418b5ca7-9ea8-486b-9515-51c09195cad9.png">

**Comment by willeastcott** [comment]
The projected skybox approach that used geometry to project the skybox is perhaps overkill for this feature. I would just like to (initially) see basic controls to 'fix' the ground projection for certain skyboxes (so exposing attributes like 'Tripod Height' etc).
