### ISSUE TITLE
Add descriptions to engine-only examples

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5178]
We have some good engine-only examples. Some examples are self-explanatory, but some are hard to understand what they are showing, without reading through the code. It would be good to add some UI way to show a description of what the example is showing and how to use it.

For example, Component Properties loads an example of a box and some lights moving. It is not immediately obvious what the example is demonstrating without reading the code.

![image](https://user-images.githubusercontent.com/5677782/226597556-0b595e7e-f27f-4408-8174-77aa4420e063.png)

**Comment by mvaligursky** [comment]
I wanted to have this many times before, thanks for creating the ticket.

Ideally it would be something rendered using html, to not pollute the example code with element components and similar, and it should handle hyperlinks as well. Something similar to https://threejs.org/examples/#webgl_animation_skinning_blending perhaps.
