### ISSUE TITLE
Shadow artifacts on mobile when using shadows update overrides

### ISSUE THREAD

**Issue by leonidaspir** [playcanvas/engine#5185]
This seems to happen on both Android and iOS. I was unable to reproduce on desktop.

Using PlayCanvas v1.61.3 (latest deployed in editor)

### Steps to Reproduce

1. Open the following engine demo on iOS/Safari: https://playcanvas.github.io/#/graphics/shadow-cascades
2. Disable Every Frame on controls to enable shadow update overrides.
3. Observe artifacts rendering.

https://user-images.githubusercontent.com/29543178/227253281-fe3b90de-4835-4428-99ef-67307682db9f.mp4

**Comment by mvaligursky** [comment]
Hi @leonidaspir - I can confirm the issue on Android with the current live examples, but I can no longer see the issue when running against the main branch, which we should be releasing this week. Could you please check on your devices to confirm this as fixed?

I'll close this, please reopen if you can still reproduce the issue.
