### ISSUE TITLE
shadows don't work with non-bone texture skinning

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#519]
Disable bone textures and you will see that skinned characters no longer have shadows

Add this line to doom 3 gangnam style or another project with skinned characters

```
 app.graphicsDevice.supportsBoneTextures = false;
```

**Comment by guycalledfrank** [comment]
Can't reproduce; Running this line in console in the middle of execution is incorrect; Starting engine with supportsBoneTextures = false doesn't affect shadows.

**Comment by Maksims** [comment]
Due to inactivity closing this issue.
