### ISSUE TITLE
Support EXT_texture_webp

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#5211]
The engine loads webp via browser anyway, so we should add official support for webp https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_texture_webp/README.md.

**Comment by wisehalvdan** [comment]
yeah, this would be really great. webp provides really good size optimizations without causing too much visual problems.

**Comment by slimbuck** [comment]
We have to figure out what to do when running on browsers that don't support webp.

**Comment by yaustar** [comment]
97.6% of browsers support webp https://caniuse.com/webp

Is not doing anything/gracefully not load them an option? 

Also related editor ticket https://github.com/playcanvas/editor/issues/991

**Comment by mvaligursky** [comment]
I believe we decided to support it for browsers that support it, and ignore the rest. And leave it up to the user to decide if they want to use it.

**Comment by willeastcott** [comment]
@mvaligursky Correct. I'm happy to go with that.
