### ISSUE TITLE
Shadowmapping show bias artifacts on mobile

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#523]
Check out this scene on desktop:

![pasted image at 2016_02_17 08_51 pm](https://cloud.githubusercontent.com/assets/697563/13142251/d03d345e-d633-11e5-8a87-2641d81b4bfb.png)

This is how it appears on mobile (iPhone 6):

![slack for ios upload](https://cloud.githubusercontent.com/assets/697563/13142255/d962b0b8-d633-11e5-8fe5-d8b5eebfb8d4.jpg)

This scene has a shadow-casting spotlight.

**Comment by highvrahos** [comment]
We had the same issue with shadowmapping artifacts on iOS, with the latest update issue seems fixed.

**Comment by willeastcott** [comment]
Fixed in 2c1bb5ae20f0e41e1d3a4a53fddc923af1f366e3
