### ISSUE TITLE
Compound shapes with position offset handles incorrect

### ISSUE THREAD

**Issue by xoopx** [playcanvas/engine#5230]
If collision shape has compound parent and has position offset, then physic gots incorect offset. Seem's here is reused Vec3 as pool vector twice. pos = pos.clone(); https://github.com/playcanvas/engine/blob/a1f5765a199c9c42e7984373dab3a620163dbb9b/src/framework/components/collision/system.js#L805 resolves problem

**Comment by LeXXik** [comment]
Would you happen to have a small repro project that shows the issue?

**Comment by xoopx** [comment]
https://playcanvas.com/editor/scene/1715165

**Comment by xoopx** [comment]
![image](https://user-images.githubusercontent.com/13869467/230956007-beef99fd-4e2e-4c9d-8951-f2ff41c90477.png)

I set here breakpoint and while debugger is at break point execute in console command pos = pos.clone(); And as the result seee next screeenshot

![image](https://user-images.githubusercontent.com/13869467/230956542-6c08e5db-8a7a-4c05-bce2-7f41c9ea9a3b.png)

**Comment by LeXXik** [comment]
Yes, I see it. Thank you for the repro! Seems a bug.

**Comment by yaustar** [comment]
Yep, definitely a bug. Great spot!
