### ISSUE TITLE
WebGPU - Are these types correct?

### ISSUE THREAD

**Issue by lp249839965** [playcanvas/engine#5234]
Line 120 is type of GPUTextureSampleType
https://github.com/playcanvas/engine/blob/main/src/platform/graphics/webgpu/webgpu-bind-group-format.js#L120
Line 143 is type of GPUSamplerBindingLayout
https://github.com/playcanvas/engine/blob/main/src/platform/graphics/webgpu/webgpu-bind-group-format.js#L143
But use the same variable of sampleType?

**Comment by slimbuck** [comment]
One is `sampleType` and the other is `samplerType` - quite confusing, but different names!

**Comment by willeastcott** [comment]
Yeah, I think this is just a naming/readability issue. @mvaligursky might want to consider tweaking the naming, IMHO.

**Comment by mvaligursky** [comment]
Closing, we've decided to leave it as is for now.
