### ISSUE TITLE
`_drawCallList.length = 0` in `renderForward` does not make sense 

### ISSUE THREAD

**Issue by scarletsky** [playcanvas/engine#5236]
### Description

The code in `ForwardRenderer#renderForward`

```js
renderForward(camera, allDrawCalls, allDrawCallsCount, sortedLights, pass, cullingMask, drawCallback, layer, flipFaces) {
    const preparedCalls = this.renderForwardPrepareMaterials(camera, allDrawCalls, allDrawCallsCount, sortedLights, cullingMask, layer, pass);
    
    this.renderForwardInternal(camera, preparedCalls, sortedLights, pass, drawCallback, flipFaces);

    _drawCallList.length = 0;
}
```

However the global `_drawCallList` is an object, NOT an array.

```js
const _drawCallList = {
    drawCalls: [],
    isNewMaterial: [],
    lightMaskChanged: []
};
```

This comes from v1.52.2 to now.

**Comment by willeastcott** [comment]
Thanks for logging this, @scarletsky. This is just the sort of bug TypeScript would prevent.... 🤔

**Comment by kungfooman** [comment]
> Thanks for logging this, @scarletsky. This is just the sort of bug TypeScript would prevent.... 🤔

And then define everything as `any/ts-ignore`, which makes it just as useless? Proper JSDoc documentation and `tsconfig/jsconfig.json` settings are key to avoiding this while retaining readability of JavaScript (TS looks like code obfuscation once you understand and use type programming with like two/three generics - and the same TS code looks pretty nice in JSDoc).  But you are on the break to use `@typedef` and other type bugs and then claim the work-creation scheme called TypeScript fixes these issues.

How about finally allowing `@typedef` and adding/improving more JSDoc comments? Issues in doc creation served long enough as excuse, there is simply no will to tackle these issues.

If you don't like my JSDoc plugin in the root repo, you can also easily overwrite the `catharsis` dependency like so:

`npm i xenova/catharsis --save-dev`

By now we should all know that `catharsis` is next to unmaintained when it comes to more advanced types, but it wasn't too hard to extend/improve it. And this is not introducing more hacks - this is fixing root causes (stupid parsers initially developed in 2013 without any fixes in the last years)

Also, exactly one thing needs to be changed, which is the `tsconfig.json` that you added:

```
{
    "compilerOptions": {
        "baseUrl": ".",
        "allowJs": true,
        "checkJs": true,
        "module": "es6",
        "target": "es6",
        "moduleResolution": "node",
        "typeRoots": [ "./node_modules/@webgpu/types", "./node_modules/@types"],
        "strict": true
    },
    "include": ["src/**/*.js"]
}

```
(adding `checkJs: true` and `strict: true`)

TADA:

![image](https://user-images.githubusercontent.com/5236548/231410961-75d61340-4079-46ad-87c5-6b42263f260d.png)

Whatever, I can say what I want anyway, lets argue for ugly and harmful work-creation schemes...

**Comment by Maksims** [comment]
> Thanks for logging this, @scarletsky. This is just the sort of bug TypeScript would prevent.... 🤔

Does this leads to a bug?

**Comment by scarletsky** [comment]
> > Thanks for logging this, @scarletsky. This is just the sort of bug TypeScript would prevent.... 🤔
> 
> Does this leads to a bug?

No, I think what you want to do is to clear the render state here:

```js
_drawCallList. drawCalls.length = 0;
_drawCallList. isNewMaterial.length = 0;
_drawCallList.lightMaskChanged.length = 0;
```

Luckly, in `ForwardRenderer#renderForwardPrepareMaterials`, it will do the same thing before rendering. So it will not trigger any bugs. #:smile:

**Comment by mvaligursky** [comment]
> (adding `checkJs: true` and `strict: true`)

I tested this in https://github.com/playcanvas/engine/pull/5246, please have a look and see if that can be improved, without having too many "errors".
