### ISSUE TITLE
Shader error Sphere map in material with PREFILTERED Cubemap

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#5253]
Forum https://forum.playcanvas.com/t/error-setting-sphere-map-in-material-with-prefiltered-cubemap/30648

Project: https://playcanvas.com/project/1063624/overview/f-prefiltered-cubemap-sphere-ma

Shader error:

```
ewport-error-console.js:159 Shader [Shader Id 2 LitShader-processed] requires texture sampler [texture_envAtlas] which has not been set, while rendering [Pass:RenderAction 0-6 Cam: Camera | Camera | World | Node: entity-1 | entity-1]
editor.once.console.error @ viewport-error-console.js:159
viewport-error-console.js:159 Shader [Shader Id 3 LitShader-processed] requires texture sampler [texture_envAtlas] which has not been set, while rendering [Pass:RenderAction 0-6 Cam: Camera | Camera | World | Node: entity-2 | entity-2]
e
```

**Comment by mvaligursky** [comment]
Ideally, if a generated shader does not need texture_envAtlas, it should not declare it as a uniform.

**Comment by willeastcott** [comment]
Thanks for the repro, @yaustar. I think I've fixed it:

![image](https://github.com/user-attachments/assets/a2d25f29-e268-44d5-a97b-1afa561b77cc)
