### ISSUE TITLE
Custom directional lightmap

### ISSUE THREAD

**Issue by SashaRX** [playcanvas/engine#5263]
Is it possible in some way to use a custom directional lightmap without using the built-in lightmapper and change the co-processing of the directional lightmap. I found the corresponding chunks, but I'm not completely sure that directions are connected at the shader build stage, without using lightmapper?

code js:
material.chunks.lightmapDirPS = fs;

shader:
void getLightMap() {
    dLightmap = vec3( 1.0, 0.0, 0.0);
    dLightmapDir =  vec3( 1.0, 0.0, 0.0);
}

But visually nothing has changed, I think the generator avoids the directional lightmap chunk

**Comment by LeXXik** [comment]
This repo is mainly for bugs. Please, use forum for general questions and support:
https://forum.playcanvas.com/

**Comment by mvaligursky** [comment]
Please start the discussion in the forum.

Custom directional light maps would be definitely possible, but we have not tried this, it would likely involve changes in multiple chunks. Capture your application with Spector JS and inspect the shader that does not work - this way you get to see the whole shader, which makes it easier to understand what needs to be done.
