### ISSUE TITLE
Varience shadow map breaks up fragment shader.

### ISSUE THREAD

**Issue by defektu** [playcanvas/engine#5273]
Activating VSM shadows breaks up in default lit shader (without clustered lighting)

# Error log

``` terminal
ERROR: 0:855: 'getShadowCoordPersp' : no matching overloaded function found

850: getLightDirPoint(light4_position);
851: dAtten = getFalloffLinear(light4_radius, dLightDirW);
852: if (dAtten > 0.00001) {
853: dAtten *= getSpotEffect(light4_direction, light4_innerConeAngle, light4_outerConeAngle, dLightDirNormW);
854: dAtten *= getLightDiffuse(litShaderArgs.worldNormal, dViewDirW, dLightDirW, dLightDirNormW);
855: getShadowCoordPersp(light4_shadowMatrix, light4_shadowParams, dLightDirW);
856: float shadow4 = getShadowSpotVSM32(SHADOWMAP_PASS(light4_shadowMap), dShadowCoord, light4_shadowParams, 15.0, dLightDirW);
857: dAtten *= mix(1.0, shadow4, light4_shadowIntensity);
858: dDiffuseLight += dAtten * light4_color;
859: dHalfDirW = normalize(-dLightDirNormW + dViewDirW);
860: dSpecularLight += getLightSpecular(dHalfDirW, dReflDirW, litShaderArgs.worldNormal, dViewDirW, dLightDirNormW, litShaderArgs.gloss, dTBN) * dAtten * light4_color* litShaderArgs.specularity;
```

### Steps to Reproduce

1. Add any light to scene.
2. Change shadow type to any `Varience Shadow Map` type.
3. getShadowCoordPersp is broken and objects with shadows are invisible.

# Screenshot

![image](https://user-images.githubusercontent.com/33038942/234376104-763bb8f1-9654-439e-94cb-5e13ba4d60cd.png)

**Comment by mvaligursky** [comment]
Thanks for the report @defektu , we'll fix it in the next few days.

**Comment by yaustar** [comment]
Second report: https://forum.playcanvas.com/t/getlightdefuse-error-on-1-62-1-works-alright-on-1-61-3/30802/2

**Comment by mvaligursky** [comment]
This second report seems related to chunk changes, not shadow issue - the error message is different.

**Comment by yaustar** [comment]
My bad, I will go back to support

**Comment by mvaligursky** [comment]
another report https://forum.playcanvas.com/t/suddenly-and-without-changing-anything-i-received-this-error-help/30803

**Comment by yaustar** [comment]
As this affects Editor rendering, should be consider this fix being a patch release?
