### ISSUE TITLE
License banner gone from release/minified builds since 1.57.0

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#5280]
The license banner has been gone from release and minified builds since engine release 1.57.0.

1.56.0:
https://code.playcanvas.com/playcanvas-1.56.0.min.js

1.57.0:
https://code.playcanvas.com/playcanvas-1.57.0.min.js

It seems to be due to this PR from @slimbuck:

https://github.com/playcanvas/engine/pull/4601

Specifically, this line:

https://github.com/playcanvas/engine/pull/4601/files#diff-6814bf77564b4f1c92f5861e184e28fe217c080a047fefa8b73a728f755ec45cR194

**Comment by slimbuck** [comment]
I think I removed the banner because all modules got the banner and it bloated the build.

**Comment by willeastcott** [comment]
I think it should have just been removed from module builds. It was also removed from ES5 builds.

**Comment by smbraun** [comment]
I would like to see some sort of version indication in the file.  We have 10+ different sites running different PlayCanvas Engines. 
 When a breaking change comes out it makes it easier to track down what sites we need to update. Even just having the bare minimum "*  v1.55.0 revision 0cab2ed64" would be fine.

**Comment by yaustar** [comment]
Another way to get the version is to type `pc.version` in the dev console of the hosted
