### ISSUE TITLE
EVENT_MOUSEDOWN fires before Button click event

### ISSUE THREAD

**Issue by tufcode** [playcanvas/engine#5296]
### Description

`EVENT_MOUSEDOWN` fires before button's `click` event, essentially making `stopPropagation()` useless.

This
```ts
app.mouse.on(pc.EVENT_MOUSEDOWN, (e) => {});
```
fires before
```ts
button.element.on("click", (e) => {})
```

* [Repro project](https://playcanvas.com/project/1070379/overview/event-firing-before-ui-event)
* Windows 11, Google Chrome

### Steps to Reproduce

1. Open the repro project
2. Click the big white square
3. Look at browser console

**Comment by yaustar** [comment]
'click' event is on the mouse up event. ie if the mouse down and up event is on the same UI element. See: https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event

The code should look like this:
```
// initialize code called once per entity
Test.prototype.initialize = function() {
    this.button.element.on("mousedown", (e) => { console.log("Button mousedown event fired"); e.stopPropagation(); });
    this.button.element.on("click", () => console.log("Button click event fired"))
    this.app.mouse.on(pc.EVENT_MOUSEDOWN, () => console.log("Mouse down event fired"))
};
```

Which gives you the following output

<img width="381" alt="image" src="https://user-images.githubusercontent.com/16639049/235714930-8a67829c-9800-4ca0-b57e-3a0cd663f888.png">
