### ISSUE TITLE
Draco WASM does not load when used in WebViews like Electron apps 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#5323]
Create an electron app as follows here: https://www.electronforge.io/

1. On command line, run `yarn create electron-app my-app`
2. `cd my-app` 
3. In file explorer, copy the contents of this zip into the src folder of my-app (overwrite index.html)
[draco-example.zip](https://github.com/playcanvas/engine/files/11463743/draco-example.zip)

eg 
![image](https://github.com/playcanvas/engine/assets/16639049/b3804934-09fc-4c14-8368-80ce2bae492c)

4. `yarn start`

App will fail to load Draco with the following error:

![image](https://github.com/playcanvas/engine/assets/16639049/d55b50c5-49be-4446-b0a5-0b918f2186ca)

**Comment by slimbuck** [comment]
Fixed
