### ISSUE TITLE
PR 5109 breaks accessing `element.material` when a material asset is set in the Editor

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#5326]
Tutorial project broken by https://github.com/playcanvas/engine/pull/5109

Project: https://playcanvas.com/project/705273

`this.entity.element.material` is null

CC @MushAsterion

**Comment by mvaligursky** [comment]
It seems there is another issue that is related and needs investigation:
https://forum.playcanvas.com/t/cannot-set-properties-of-alphatest-for-materials-even-on-playcanvas-examples/31387

**Comment by yaustar** [comment]
This is fixed in 1.63.5: https://github.com/playcanvas/engine/releases/tag/v1.63.5
