### ISSUE TITLE
Particle system broken on Samsung Galaxy note 10+

### ISSUE THREAD

**Issue by baghban71** [playcanvas/engine#5342]
This workaround don't work on Samsung Galaxy note 10+ (android 12)

https://github.com/playcanvas/engine/pull/4147

supportsGpuParticles  flag return true on that device 

![photo_2023-05-21_14-27-27](https://github.com/playcanvas/engine/assets/70829913/cb093ff2-9496-46a9-8429-40533b25c35c)

**Comment by yaustar** [comment]
I reverted that workaround in this PR https://github.com/playcanvas/engine/pull/5255 has I couldn't reproduce the issue any more during testing with the original test projects.

Can you provide an example project of the issue you are seeing for the team to test against please?

**Comment by yaustar** [comment]
I wonder if the Mali-G76 is also an affected GPU that either I didn't have access to at time or missed 🤔

**Comment by baghban71** [comment]
This example and any project that contain particle have similar issue on that device : 
https://playcanvas.github.io/#/graphics/particles-spark

**Comment by yaustar** [comment]
@mvaligursky, I can't test against those devices any more. Could you check against Mali-G76 and see if it's specific against that GPU or we can re-add the Samsung Exynos model check again as a catch all.

**Comment by mvaligursky** [comment]
I'd say we add the catch all again.
