### ISSUE TITLE
Feature Request: Subsurface Scattering

### ISSUE THREAD

**Issue by defektu** [playcanvas/engine#5344]
I was working on subsurface scattering implementation over Lit Shader. I did not wanted to open a PR because I'm not sure about implementation is mathematically right.

Here is the project that I've cleaned up for you guys.
https://playcanvas.com/editor/scene/1751652  (?debug=true flag opens up gui.)
https://playcanv.as/p/KW8u9ebM/?debug=true

### Implementation
1. falloffLinearPS
- Added LIGHTS_AVAILABLE for cross-checking.
- `pointLightCount` - total point count
- `lightPointsPos[]` - Array for light positions
- `lightPointsRad[]` - Array for light rads;
2. lightDirPointPS - sets light positions
3. refractionDynamicPS 
- `addSSS()` - adds up sss effect on top of refraction shader.

### Screenshots
SSS on
![image](https://github.com/playcanvas/engine/assets/33038942/3ea7af62-a561-4409-8659-29b45a5613ab)
SSS off
![image](https://github.com/playcanvas/engine/assets/33038942/32b25daf-30a0-4d72-822c-046a9ce1df98)

This is an old build but you can change some variables with dat.gui (debug=true flag opens up gui.): https://playcanv.as/index/ca8102ee
![image](https://github.com/playcanvas/engine/assets/33038942/d6a37224-aaca-47fe-acbb-bfb6cfaa632f)

**Comment by defektu** [comment]
Made a ViolentMonkey script for quick test in editor. 
https://github.com/defektu/Playcanvas-Editor-Scripts
Thanks to @yaustar for good example

**Comment by defektu** [comment]
Hi @mvaligursky , Do you think it would be a good feature implementation? I might create a PR about it.

**Comment by mvaligursky** [comment]
To be honest, perhaps not at the moment. I have few comments at the moment:
- we're trying to follow the glTF material model (including its extensions) for most part at the moment, and are hesitant to add many other functionality, especially if larger and harder to maintain
- your code uses separate arrays of light data, which is really not something I'd like to add to the core engine
- We'd need to make sure this is all physically as correct as it can be, which is non trivial and even you mentioned the doubts.

**Comment by defektu** [comment]
Thanks for the feedback Martin.
Newly introduced arrays can be eliminated by using `light" + i + "_position` & `light" + i + "_radius` in `lit-shader.js` I assume.
On physicaly correct part, I need to cross-check it cause of quick implementation.
If you consider adding it as a render feature after glTF material model milestones just ping me up so I might work over it.

**Comment by mvaligursky** [comment]
> Newly introduced arrays can be eliminated by using `light" + i + "_position` & `light" + i + "_radius` in `lit-shader.js` I assume.

But those are only available in non-clustered mode. Clustered mode encodes lights in textures and so this is harder to do this way.

**Comment by mvaligursky** [comment]
> If you consider adding it as a render feature after glTF material model milestones just ping me up so I might work over it.

Absolutely. Please feel free to create an issue to implement SSS and link this PR there as WIP, so that we won't forget, thanks a lot!
