### ISSUE TITLE
Error decoding Draco GlTF model

### ISSUE THREAD

**Issue by YUNI0107** [playcanvas/engine#5348]
I encountered an issue while trying to decode a droco glTF model in my project. 
It works fine in engine version v1.62.2, but starting from v1.63.0, the model appears broken.
I receive the following error:
**Uncaught TypeError: Cannot read properties of undefined (reading 'x') at Mesh._initBoneAabbs (mesh.js:355:30)**
<img width="387" alt="2023-05-23 下午4 34 54" src="https://github.com/playcanvas/engine/assets/54655528/cb7da3ee-e477-4ae8-9349-9c48b0f221a1">

I have tested other models with skin mesh, and only this Dinosaur model seems to break.
However, I am uncertain if other models might also experience similar issues.

### Steps to Reproduce
1. I have provided an editor project froked from Draco example and the Dinosaur model asset included. 
https://playcanvas.com/project/1078977/overview/draco-test
2. Downgrading to v1.62.2 let the model works as expected.

Thank you!

**Comment by slimbuck** [comment]
Hi @YUNI0107, we saw this one coming! :D https://github.com/playcanvas/engine/pull/5346

**Comment by mvaligursky** [comment]
I confirmed it works with the engine path we're just releasing:
https://launch.playcanvas.com/1752817?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-preview.dbg.js

**Comment by YUNI0107** [comment]
Wow, thank you so much :heart_eyes:
