### ISSUE TITLE
Failing to compile shadow fragment on current main in AR start up kit example when entering AR

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5352]
- create a new project in the Editor using AR starter kit
- run that on the Android, enter the AR mode
- observe the compile error

![ar mode](https://github.com/playcanvas/engine/assets/59932779/fb8585ae-791e-4300-8b9a-4eb5776a34cc)

**Comment by GSterbrant** [comment]
This bug should be fixed with the next release. I have updated the AR starter kit template to reflect the changes done to getShadowPCF3x3.
