### ISSUE TITLE
Re-allocation of object in pc.Keyboard#update

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#536]
this._lastmap = {};

https://github.com/playcanvas/engine/blob/master/src/input/keyboard.js#L245

**Comment by vkalpias** [comment]
Why is this a memory leak? I mean it allocates new memory sure but it's not a leak per se?

**Comment by willeastcott** [comment]
Because update is called every frame and this._lastmap is overwritten with a new object on every call. The previously created and set one is then orphaned and later garbage collected.

**Comment by vkalpias** [comment]
OK just making sure because 'leak' usually means that it's never garbage collected.

**Comment by willeastcott** [comment]
No. For that to happen, there'd be a bug in the JS engine and not our code. :smile:

**Comment by Maksims** [comment]
It is not leak, but re-allocation.
GC does the right job in order to clear memory of unused data, so it is not leaking.

**Comment by daredevildave** [comment]
Fixed in 72fc5b05cc5302c373d4ce6cff0630847f045dee
