### ISSUE TITLE
AudioBuffer not released from memory

### ISSUE THREAD

**Issue by jbromberg** [playcanvas/engine#5361]
When adding a sound and then removing the asset, it's still retained in memory. This can be verified by loading an audio asset and then calling app.assets.remove(asset). If you do this many times with many different songs, you will see memory continue to trickle up.

A reference to the audio buffer is being stored at app.assets._loader._handlers.audio._loader._cache and this keeps it in memory. I'm currently overcoming this by just calling delete on that cache with the url + 'audio' as the key when removing the asset.

Edit: Removing it from the cache does indeed remove the reference to it in the loader however upon inspecting the webpage it appears memory is still not going down. Perhaps there may be another reference to it somewhere.

**Comment by mvaligursky** [comment]
Would you by any chance have a simple project to repro the issue? That would make the fix a lot easier to implement.
Thanks!

**Comment by jbromberg** [comment]
Here's a very simple repro project: https://playcanvas.com/project/1123162/overview/audio-not-released-from-memory

The project has a sound that autoplays and after 2 seconds the sound entity is destroyed and the sound asset is removed from the asset registry. When inspecting, you can see that the audio buffer is still retained in memory.

For reference, I'm using Safari devtools to measure this since this is for a mobile game on iOS.

Here's a screenshot showing the audio still in memory after it should have been removed.

<img width="1395" alt="Screenshot 2023-08-02 at 2 11 33 PM" src="https://github.com/playcanvas/engine/assets/58891459/5fbc745f-2af9-407a-affa-291adfed9424">

**Comment by willeastcott** [comment]
Thanks for the repro, @jbromberg!

So I think you might be missing a call to `Asset#unload`. i.e.:

```javascript
    if (songAsset) {
        this.app.assets.remove(songAsset);
        songAsset.unload();
    }
```

Can you try that and see if it helps?

**Comment by jbromberg** [comment]
That seems to have done it. Thanks!
