### ISSUE TITLE
Possible issue in the reflectionSphereLow.js chunk

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5378]
The mentioned chunk contains line:
```
    vec3 reflDirV = vNormalV;
```

but `vNormalV` does not seem to be added to the fragment shader in any case, only to the vertex shader.

As a repro, "Flying Toasters" project can be launched in WebGPU mode.

**Comment by willeastcott** [comment]
Hey @mvaligursky - this chunk doesn't exist any more. Can this issue be closed?

**Comment by mvaligursky** [comment]
agreed, closing, thanks
