### ISSUE TITLE
Scene changing in Seemore via `SceneRegistry#changeScene` is broken

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#5409]
Very simple, start SeeMore: https://launch.playcanvas.com/1775497?debug=true

Make sure you are running one of the latest versions (best is HEAD ofc, just fork and download the project and fix path in index.html).

Change scene to itself:

```js
pc.app.scenes.changeScene("Level")
```

Result: 

![image](https://github.com/playcanvas/engine/assets/5236548/d9db0f95-007c-48a7-8398-d68e2eac1fa4)

It used to work, this is how I constantly debugged this PR: https://github.com/playcanvas/engine/pull/4626

I figured out the root cause of https://github.com/playcanvas/engine/issues/4649, but now scene changing doesn't even work any longer.

Anyone knows what happened to Seemore? Since this worked before, this is a regression.

**Comment by yaustar** [comment]
I don't think much if any has changed 🤔 

There are a number of `app.on` calls that aren't cleaned up when the script is destroyed via `changeScene`

Eg

```
Door.prototype.postInitialize = function() {
    var doorPos = this.entity.getPosition().clone();
    var cameraToDoor = new pc.Vec3();

    var hingeConstraint = this.entity.script.hingeConstraint;
    this.limits = hingeConstraint.limits.clone();

    this.app.on('cameramove', function (cameraPos) {
        cameraToDoor.sub2(cameraPos, doorPos);
        if (cameraToDoor.length() > 5) {
            var limits = hingeConstraint.limits;
            var closedAngle = (limits.x + limits.y) * 0.5;
            hingeConstraint.limits = new pc.Vec2(closedAngle, closedAngle);
        } else {
            hingeConstraint.limits = this.limits;
        }
    }, this);
};
```

**Comment by kungfooman** [comment]
Thank youuuu @yaustar 

I thought this is the perfect opportunity to test your PR and it works like a charme:

https://github.com/kungfooman/seemore/commit/7d1e074a2d027295a56d543483b9946d9bd0b4eb

No errors anymore, scene changes as it should and events are dealt with properly :pray: :clap: 

Technically this is an issue with Seemore, so should we close this? IMO ideally we would merge your PR and then someone fixes Seemore using `ScriptType#listen`.
