### ISSUE TITLE
MRT direction

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5428]
It is probably known, but MRT example is rendering upside down on WebGL 1 and 2, while rendered correctly on WebGPU.

https://playcanvas.github.io/#/graphics/mrt

![image](https://github.com/playcanvas/engine/assets/5677782/7bcc81c1-1ee7-42e2-914e-f5d8864ee7bb)

**Comment by mvaligursky** [comment]
Yep, WebGL is correct (and the flipY in the example should be removed). We need to sort out all render targets flipping on WebGPU, which is on my todo list.

**Comment by mvaligursky** [comment]
related - fix drawTexture to not render textures upside down: https://github.com/playcanvas/engine/pull/5434
so this looks correctly on WebGL now, and as mentioned, WebGPU needs fixing.

**Comment by mvaligursky** [comment]
Fixed (not the best way) in #5500
