### ISSUE TITLE
Playcanvas API Download App - Error Parsing playcanvas-stable-min.js

### ISSUE THREAD

**Issue by benharvey1213** [playcanvas/engine#5431]
I am using [this guide](https://developer.playcanvas.com/en/user-manual/api/app-download/) to download my app. However, when I try to serve it using http-server, I am receiving this error:

`Uncaught SyntaxError: Unexpected token ')' (at playcanvas-stable.min.js:1:2)`

When I download the app from the playcanvas editor, the playcanvas-stable.min.js file is different than when I download it from the API. Is there anything I'm overlooking or does this need to be fixed?

**Comment by slimbuck** [comment]
Hi, can you check what the version and revision numbers are at the top of the two `playcanvas-stable.min.js` files?

**Comment by slimbuck** [comment]
Could you attach the API engine version here?
