### ISSUE TITLE
Sheen doesn't work as expected when using Specular

### ISSUE THREAD

**Issue by animech-sijo** [playcanvas/engine#5440]
Sheen doesn't work as expected on materials that use Specular setup:

- Color doesn't work as expected - white blows out everything, and all other colors produce the same result.
- Glossiness doesn't change anything - you can only get full glossiness, or use the invert checkbox to get full roughness.

Using Metalness instead of Specular solves these issues. However, since materials use Specular by default, using sheen is very confusing, especially since this limitation isn't documented anywhere (as far as I know). I only figured this out when looking at the [glTF spec](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_sheen#exclusions), which I presume was used as reference.

Is it possible to implement Sheen for Specular as well? If not, can this limitation be communicated more clearly, either in the Help docs, API, or directly in the Playcanvas editor?

**Comment by GSterbrant** [comment]
Hello @animech-sijo. You're right, we have only implemented the Sheen to work with the metalness PBR shaders. Perhaps we should just disable sheen if that workflow isn't used. 

Sheen is a fresnel function primarily, so it would make sense it would look incorrect when not used with similar physics in mind. Thanks for bringing this to our attention!
