### ISSUE TITLE
Possible AR compatibility issue on some android devices

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5450]
It seems PlayCanvas WebXR AR examples do not work on some Android devices, specifically:
- Samsung Galaxy S9+

Devices confirmed working:
- Google Pixel 6

More details: https://forum.playcanvas.com/t/webxr-ar-doesnt-work/31485

**Comment by willeastcott** [comment]
I've also confirmed working in Google Pixel 7a. There was a problem where our developer site wasn't iframing the examples properly that I have just fixed. So I'm going to close this for now.
