### ISSUE TITLE
Huawei RenderTarget to RGBA16F with MAX_SAMPLES - failing to attach framebuffer.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#5455]
On Huawei device when creating render target it fails to attach frame buffer with RGBA16F format with samples set to MAX_SAMPLES (which are 16 on that device).
It leads to WebGL errors when attaching frame buffer.
Reducing samples to 4 or 0 - eliminates the issue.

**Comment by mvaligursky** [comment]
This feels like the device is not reporting this correctly, I think typically only up to 4 samples are supported.
On WebGPU we force this to be 0 or 4, perhaps we need similar solution to WebGL.

**Comment by epreston** [comment]
Is it a Huawei Mate device?  Reporting numbers it does not support ?  People are finding similar things in their testing. 

https://stackoverflow.com/questions/73722913/why-huawei-mate-series-webgl-max-array-texture-layers-set-at-256-this-affect-we
