### ISSUE TITLE
Can't set model in collision component options object

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#546]
This doesn't work:

            entity.addComponent('collision', {
                type:'mesh'
                model: asset.resource
            });

This does work:

            entity.addComponent('collision', {
                type:'mesh'
            });
            this.entity.collision.model = asset.resource;

Is this a bug?

**Comment by vkalpias** [comment]
It might be a little issue with the order in which some things are initialized, it's a bit tricky to fix. However you can do 

```
entity.addComponent('collision', {
    type: 'mesh',
    asset: asset
};
```

**Comment by vkalpias** [comment]
Should be fixed now in https://github.com/playcanvas/engine/commit/26e458d42b3758b33af97475e123f4430f669664
