### ISSUE TITLE
Swap fetch for pc.http

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5468]
We use wrappers to push games to Android/iOS. The wrapper is a native app with a fullscreen browser window that runs PlayCanvas game. At the moment the engine is using `fetch` to get Wasm libraries like draco, basis, etc. Unfortunately, `fetch` is not available in local environments, like wrappers, causing the game not to load.

Please, consider, fallback `fetch` to `pc.http` if `fetch` is not available. Or just replace it altogether.

**Comment by willeastcott** [comment]
`fetch` is 'the future'. I'd rather not step back to `XMLHttpRequest`. Have you considered using a fetch polyfill?

https://www.npmjs.com/package/whatwg-fetch

**Comment by LeXXik** [comment]
Nope, I made this on behalf of our team :)

As a short term, we just fallback to pc.http if fetch is not available. We had to modify the engine code for the fallback. Thought it would be useful to have, until fetch is supported everywhere.

Will forward your advice. Seems like a good approach to take.

**Comment by mvaligursky** [comment]
Closing this, please re-open if further discussion is needed.
