### ISSUE TITLE
Distorted Audio on iPhones

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#551]
There is a known issue on iPhones that after first booting they will often playback sounds with the wrong sample rate.

I'm not sure if there is a possible work around for this, but some suggestions from the phaser forum:

http://www.html5gamedevs.com/topic/19156-ios-92-sound-broken/
https://github.com/Jam3/ios-safe-audio-context/blob/master/index.js

**Comment by willeastcott** [comment]
This doesn't seem to happen any more. iOS may have been patched. Closing.

**Comment by raymondskl** [comment]
I have this happening on our current project with distortion  isolated on ios devices

**Comment by willeastcott** [comment]
What's the repro?

**Comment by willeastcott** [comment]
No repro supplied so closing again. Please reopen if a repro can be obtained.
