### ISSUE TITLE
Redundant shader recompilation

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5512]
We do the material shader compilation at load times, so that the game doesn't freeze mid-game when a new template is instantiated. Recently, we found that the game started stuttering mid-game. The cause is materials were getting their shaders recompiled.

It looks like the new hashing method consumes a different variant string for what should be the same material. I've made an example:
https://playcanvas.com/editor/scene/1815575

1. Press 1 key to instantiate a box.
2. Check console

Box is using a default standard material. Every time you press 1, old box is destroyed and a new one is instantiated.

Notice that the shader gets compiled 3 times, for what should be a one-time operation.

Here are 3 strings that are hashed for the first 3 boxes. From there on, the string seem to match, and a cashed variant is used.
Apart from pass_0  / pass_5 differences, notice also [ object Object ] in the string.

![image](https://github.com/playcanvas/engine/assets/5677782/365d6912-deb6-4d44-9be4-a3753f948416)

**Comment by yohami** [comment]
This one is causing major freezes in all of our games, so I tag this as very urgent :-) @willeastcott

**Comment by mvaligursky** [comment]
I can reproduce this with 1.64.4, and also 1.63.0, but not 1.62.0.
But I can no longer reproduce this on current main which has some related refactorings / fixes. Could you please test against https://code.playcanvas.com/playcanvas-latest.dbg.js to confirm

We're planning to do the engine release (1.65.0) sometimes next week.

**Comment by yohami** [comment]
Is it possible to build using 1.62? we're submitting games to several platforms. The engine version lets me see down to 1.63.3

**Comment by LeXXik** [comment]
Yes, it looks like the release you linked @mvaligursky is better. I don't see those compilations.

**Comment by mvaligursky** [comment]
Good news! I'll close this, but please reopen if you need further support on this.
And hopefully you can wait for this to get released as a minor version next week, as extracting this to a patch would be more complicated.

**Comment by LeXXik** [comment]
@mvaligursky the recent changes definitely removed the duplicates. While testing it, I noticed a re-compilation of what I would assume should be an existing shader (the one engine compiled when app started).

Same project link. Just disable Light 1 entity and enable it back. When you enable it, compilation takes place again.

https://github.com/playcanvas/engine/assets/5677782/2560ea64-10f8-4761-a3d3-8d28ada206e1
