### ISSUE TITLE
Changing Entity Scale not updating its meshInstances AABB

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#552]
If you change scale in runtime, then AABB of meshInstances won't be recalculated leading to frustum culling to cut meshInstances on wrong aabb.
[Here is a project](http://playcanvas.com/editor/scene/419815/launch) that sets bigger scale later after loading, and camera moves so it triggers frustum culling. It is visible how mesh disappears. If scale is set initially to same as in script, then all is fine.

**Comment by guycalledfrank** [comment]
Fixed in https://github.com/playcanvas/engine/pull/553
