### ISSUE TITLE
pc.DEVICETYPE_NULL is not in docs

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5581]
Looks like pc.DEVICETYPE_NULL was not added to docs:

https://developer.playcanvas.com/en/typedocs/functions/createGraphicsDevice.html

**Comment by mvaligursky** [comment]
The docs are generated automatically based on comments (JSDocs) in the code, and are released when the respective engine version is promoted to be used by the Editor.

In this case, DEVICETYPE_NULL has not even been released as part of the engine yet, and should be part of 1.66.0 in a few weeks.
