### ISSUE TITLE
Omni lights expensive - unusable? 

### ISSUE THREAD

**Issue by yohami** [playcanvas/engine#5586]
Got reports saying our games are unplayable on not so old Android devices like the Samsung A73 5G and other models from last year - doing tests we narrowed it down to our use of Omni lights with cluster lighting enabled.
 
I am assuming the high consumption of omni lights is a glitch so Im reporting it here - that type of low performance would make the omnis unusable which is a shame.

Video comparison: 

Directional light with shadows, 60fps:

https://www.youtube.com/watch?v=OvBeLCerU9Y 

One Omni light, no shadows, cluster lights enabled, 30fps or less. On a regular scene we're using around 5 omni lights, but just one kills the device:

https://youtube.com/shorts/92t2RL2mU8w

Tried to disable cluster lights for comparison but we found this other glitch:

 https://github.com/playcanvas/engine/issues/5585

Thanks,
Yohami

**Comment by LeXXik** [comment]
Just to add a note here - the same setup works fine on iPhone.

**Comment by mvaligursky** [comment]
How does this run on the mentioned device?
https://playcanvas.github.io/#/graphics/clustered-lighting

On Pixel6 this is 90fps.

**Comment by yohami** [comment]
Will report back

**Comment by yohami** [comment]
QA reports that the playcanvas demo runs fine at 60fps on that Samsung phone. Puzzling.

**Comment by yohami** [comment]
Here's how the playcanvas demo runs on that device (maybe 40fps) - still better than our game with just one Omni, strange.

https://youtu.be/BhNYrlVFo0s

**Comment by mvaligursky** [comment]
What clustered settings do you use? Disable what you don't need (or everything for testing)

![Screenshot 2023-08-24 at 17 04 05](https://github.com/playcanvas/engine/assets/59932779/a23c71ed-3141-449f-8522-9697eaab9acb)

**Comment by mvaligursky** [comment]
Area lights are expensive. Disable those?
Shadows as well if not needed.

**Comment by yohami** [comment]
Been doing some builds / experiments. Seems like the biggest slowdown is due to Clustered lights with shadows, gets worse with Area lights

Cluster lights disabled, Omni with shadows: 69fps
https://playcanv.as/b/4a990f6c

Cluster and Area lights enabled: 10fps
https://playcanv.as/b/03ace4ec

Cluster lights with shadows, Area lights disabled: 30fps
https://playcanv.as/b/000bd0b3

Cluster lights without shadows, 60fps
https://playcanv.as/b/07f32a9d

Im guessing we can survive without cluster lights if we have 5-10 in scene?

Thoughts welcome

**Comment by Maksims** [comment]
> Been doing some builds / experiments. Seems like the biggest slowdown is due to Clustered lights with shadows, gets worse with Area lights
> 
> Cluster lights disabled, Omni with shadows: 69fps https://playcanv.as/b/4a990f6c
> 
> Cluster and Area lights enabled: 10fps https://playcanv.as/b/03ace4ec
> 
> Cluster lights with shadows, Area lights disabled: 30fps https://playcanv.as/b/000bd0b3
> 
> Cluster lights without shadows, 60fps https://playcanv.as/b/07f32a9d
> 
> Im guessing we can survive without cluster lights if we have 5-10 in scene?
> 
> Thoughts welcome

Clustered lighting has an upfront cost even with little illumination. If you have only a few lights that do mostly overlap - then clustered lights generally not worth it. But if your lights are positioned and sized with very little or no overlap, then clustered lights have benefits.

Also check their settings, such as `lightingMaxLightsPerCell` and `lightingCells`. Reducing these values can improve the performance.

**Comment by mvaligursky** [comment]
> Im guessing we can survive without cluster lights if we have 5-10 in scene?

It very much depends on the devices you need to run on, scene complexity, light placement. There is no generic advices here apart from @Maksims already mentioned. Disable as many features as you need. If there performance is not good enough, try non-clustered lights - but the cost with few of those gets costly pretty fast as well.

Also see here, there's a performance section there https://developer.playcanvas.com/en/user-manual/graphics/lighting/clustered-lighting/

I'll close this as I'm not sure there's any new feature request / bug report, but please re-open if that is not correct.
