### ISSUE TITLE
Build directory not cleared before build "all" targets

### ISSUE THREAD

**Issue by epreston** [playcanvas/engine#5588]
Build directory is not cleared before rebuilding all targets.  

Normally, the expectation is that:
- building one or specific set of targets - do not clear
- building all targets - rimraf the build dir before building

Options:
- Can be done via cli before "npm run build" with a rimraf command.
- Can be done in code in the build script 

Example for rollup.config.mjs in the default export
```js
  // if building a specific format, do not remove build.
  if (!targets.length && existsSync(`build`)) {
    await fs.rm(`build`, { recursive: true });
  }
```

I ran into an issue that confused me when I thought some files were not being built.  They are no longer part of the build but were left there from 3 weeks ago.  Clearing the directory on full builds will ensure this does not happen again.  

It will also ensure extra files are not published to npm bloating the bundle size.  For example "common.js" in the shaders directory, removed in a commit a few weeks ago, in a recent publish.

**Comment by willeastcott** [comment]
The `build` command should probably build the TypeScript declarations too then.

**Comment by mvaligursky** [comment]
keen to do all this @epreston ? I'd love to have this.

**Comment by epreston** [comment]
On the way.

**Comment by epreston** [comment]
Ready for review.  A little re-org for clarity and the normal clean-up logic on "build all".

**Comment by mvaligursky** [comment]
Yes, I got hit by this yesterday and it took me a while to figure out what is missing. It'd be great to add.

**Comment by epreston** [comment]
@willeastcott , @mvaligursky , @kungfooman

A command already exists to build types after the library is built.

`npm run build:publish`

It is defined as:

`"build:publish": "npm run build && npm run build:types",`

You can be confident that it is clean because the first command purges the directory.

**Comment by mvaligursky** [comment]
Hi interesting .. personally I'd remove the publish target and make the build do this. 
@slimbuck @willeastcott - any thoughts?

**Comment by epreston** [comment]
Can I speed up the build 10x first by swapping a few rollup plugins ?  Then we add to it ?

The best in class plugin for this at the moment does both at the same time.  Worth taking a look at.

**Comment by mvaligursky** [comment]
Sure, create a separate issue / pr and go for it, keen to see what it is.
