### ISSUE TITLE
PlayCanvas TS Hit Fraction Casting Error

### ISSUE THREAD

**Issue by lukastomasek** [playcanvas/engine#5599]
- I found a casting error with `hitFraction`
 - It is casted as vec3 instead of number 
![Screenshot 2023-08-29 at 2 30 55 PM](https://github.com/playcanvas/playcanvas-sync/assets/52459545/a732a726-7bfd-4796-81ef-d5ae947dbeae)

**Comment by willeastcott** [comment]
Where did you get that `playcanvas.d.ts` file? If I look at the latest published `playcanvas.d.ts` file, I see:

![image](https://github.com/playcanvas/engine/assets/697563/50c916f2-524e-4368-ac58-cb43f87d2dec)

**Comment by lukastomasek** [comment]
I got that file from one of the pc-sync typescript examples. I will just update then that should fix it

**Comment by willeastcott** [comment]
Oh right. Where is that example?

**Comment by lukastomasek** [comment]
Oh I know what might happened:

**Comment by willeastcott** [comment]
OK, thanks for the update. Closing. 👍
