### ISSUE TITLE
ContainerHandler JSDocs needs fixes to the table

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5605]
See the table here: https://developer.playcanvas.com/en/api/pc.ContainerHandler.html

screenshot

<img width="846" alt="Screenshot 2023-09-01 at 09 03 00" src="https://github.com/playcanvas/engine/assets/59932779/66d58a08-1e1d-41de-ba26-2207941adf58">

**Comment by willeastcott** [comment]
Already fixed here by @epreston:

https://github.com/playcanvas/playcanvas-jsdoc-template/pull/58

**Comment by willeastcott** [comment]
For the record, here's what a local build with latest looks like:

![image](https://github.com/playcanvas/engine/assets/697563/37968b52-9c93-44e0-ab87-ea24ed6889fa)
