### ISSUE TITLE
Allow spaces in examples search

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5609]
This is a feature request to allow spaces in the examples search:

![image](https://github.com/playcanvas/engine/assets/5677782/311bd77a-e9eb-4ecb-82d8-a0e4fbf83980)

![image](https://github.com/playcanvas/engine/assets/5677782/fa602b35-c405-4c7d-a7c6-e565bdcfca13)

**Comment by kungfooman** [comment]
Fixed it here: https://github.com/playcanvas/engine/pull/5555

Live demo: https://examples.killtube.org/#/misc/hello-world

![image](https://github.com/playcanvas/engine/assets/5236548/ff025580-9b3f-4200-8c6b-202d92877eaa)

Commit + more info: https://github.com/playcanvas/engine/pull/5555/commits/1b27b4dc826f26906bd20d9e0ce90b691f0c2b25

Too long don't read: Internally the titles are saved like `MeshDecals`, which contains no space... therefore we can just turn spaces into `.*`. This also allows you to search for e.g. "me de":

![image](https://github.com/playcanvas/engine/assets/5236548/485bd32c-0e24-4a93-b279-00e5737d8f64)
