### ISSUE TITLE
Directional Light shadow map resolution is dependant on camera aspect ratio.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#561]
Changing aspect ratio, making screen very wide will reduce resolution of shadow map of a directional light. Seems like something to do with ortho camera frustum.

**Comment by guycalledfrank** [comment]
Seems expected? Wider your view angle -> larger the camera frustum -> larger the shadow frustum -> lower the resolution.

**Comment by willeastcott** [comment]
I can live with resolution change. It's the banding/artifacts that appear (shadow bias related) as the frustum size changes. Makes it really hard to tune shadows if the window size is variable.

**Comment by guycalledfrank** [comment]
Fixed in https://github.com/playcanvas/engine/pull/657
