### ISSUE TITLE
examples: post effects setTexture('string', null)

### ISSUE THREAD

**Issue by epreston** [playcanvas/engine#5615]
Post effects example is sending "null" texture to setTexture and can't get index.

https://github.com/playcanvas/engine/blob/4b5e4f560437164d4ab0dbedb6022a54c88c0a0b/src/platform/graphics/bind-group.js#L95

I don't think we can rely on texture having a "texture.renderVersionDirty" method until its checked.  Maybe this can be avoided entirely.

**Comment by mvaligursky** [comment]
How do you reproduce this @epreston? The mentioned example works without problem for me on WebGPU.

**Comment by epreston** [comment]
You're right. It's working perfect for me now too on all renderers. Must have been related to other bits.

At the time, `null` was being passed in the texture param.  I thought this might have been a legit use to remove it from the texture array.

I'll close this.
