### ISSUE TITLE
Texture.destroy doesn't reset _glTextureId

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#562]
https://github.com/playcanvas/engine/blob/master/src/graphics/texture.js#L281

Texture.destroy has a check to see if it has already been destroyed but it doesn't work. This means it is possible to call Texture.destroy() multiple times and the VRAM usage is decremented each time.

**Comment by guycalledfrank** [comment]
Fixed in https://github.com/playcanvas/engine/pull/630
