### ISSUE TITLE
Special characters in glb filenames

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5665]
Forum topic: https://forum.playcanvas.com/t/missing-files-error/33067

Some GLB assets are using a special character `|`:
```
KayKit Animated Character|Walk.glb
```
It works in Launcher, but breaks in build:

![image](https://github.com/playcanvas/engine/assets/5677782/eeacd80a-2fa7-49bd-9103-b95ed9310cef)

Repro: 
Download zip and run in local web server:
https://playcanvas.com/project/1142167/overview/underscore-issue

**Comment by yaustar** [comment]
https://github.com/playcanvas/editor/issues/449

**Comment by LeXXik** [comment]
Closing as duplicate.
