### ISSUE TITLE
Safari - Security Error with TexImage2D

### ISSUE THREAD

**Issue by lukastomasek** [playcanvas/engine#5685]
Hey I've encountered this bug with latest version engine on safari web browser: 
![Screenshot 2023-09-27 at 5 08 51 PM](https://github.com/playcanvas/engine/assets/52459545/c04ba9ea-9381-438a-9463-95ffc6aa5d74)

**Comment by mvaligursky** [comment]
I tried to reproduce with the examples on Safari 17 but I don't see this. http://localhost:5000/index.html#/graphics/particles-spark

How do you reproduce this? What exact Safari version are you using? Does it have some side effects (textures not loading?).

**Comment by Maksims** [comment]
Also, provide a specifics of which URL you are launching PlayCanvas application, and from which URL the texture is loaded.
As you might be missing CORS headers if you are trying to load textures cross-domain.

**Comment by lukastomasek** [comment]
I did some more digging and it is a CORS issue. I'm loading my assets from the firebase. I found this on forum which is same problem I had: https://forum.playcanvas.com/t/solved-cors-error-coming-from-playcanvas-engine/27433
I thought it was an engine problem since the error was pointing to the source code. 

Thanks for your help!

**Comment by mvaligursky** [comment]
Thanks for the update, closing for now.
