### ISSUE TITLE
Poor Image quality and performance in "Lumberyard Bistro" compared with babylonjs

### ISSUE THREAD

**Issue by MAG-AdrianMeredith** [playcanvas/engine#5700]
### Description
Comparing appearance and performance to babylonjs this scene is really quite poor

Babylonjs reports around 80-90fps at the same location but playcanvas reports around 30-40.  Though the environment map is different I was unable to replicate the look of babylon which more closely matches the target renders

playcanvas
![Screenshot 2023-09-29 at 13 30 19](https://github.com/playcanvas/engine/assets/100127317/ff92e4b1-9a42-4e13-a8fa-a83db432653a)
babylon js
![Screenshot 2023-09-29 at 13 31 11](https://github.com/playcanvas/engine/assets/100127317/000ab7b5-a2b3-4132-9981-792f2dcdc41e)

### Steps to Reproduce

1. got to and download the model https://developer.nvidia.com/orca/amazon-lumberyard-bistro
2. convert to glb in blender
3.  load it into babylonjs sandbox and playcanvas viewer
4. Both appearance and performance is vastly different

**Comment by epreston** [comment]
Could you link your converted file ?  This is just the "exterior" scene which was converted ?

**Comment by epreston** [comment]
One last bit, your scene is completely inverted. Bike should be facing left and arch on right.  

Kinda points to modification beyond just scaling.

**Comment by epreston** [comment]
From the meta data of the screenshots, it looks like you are on a Apple Mac with an Dell monitor (Dell AW3423DW).

I'll repeat my testing on the same setup (M1 mac with a Dell AW3423DW).

**Comment by epreston** [comment]
M1 Mac Tests:  

This shows a difference in frame time closer to to what you are seeing. 

Assuming you have completed the corrections above, the rendering quality is nearly the same.  Ensure you are using the same light maps.  

All platforms struggle with depth buffer precision unless I heavily reprocess the scene before export.  That's likely why the scene was processed.

The big ticket performance item is:

Playcanvas Viewer: default not resampling hi def (2k) textures, uses 4.6 GB of texture memory
Babylong Sandbox: default resamples textures, uses far less texture memory.

You can see that this is the culprit by just rendering world normals instead.  The purpose of these two tools might differ slightly.  One focusing on what the actual model file contains the other showing what the engine can reprocess.  Both have value.

Second is the default multi-sampling:

Disabling the multi-sample setting on PlayCanvas Viewer is a 50% performance increase with no difference in rendering (identical pixels).

Third is playing animations: 

This is a 10 - 20% performance difference.

**Comment by MAG-AdrianMeredith** [comment]
Theres defininity something really off with the scale and transform but what concerns me is it looks really bad only in playcanvas, every other tool looks good by default.  Playcanvas seems to be rendering everything like its metal

**Comment by MAG-AdrianMeredith** [comment]
I'm also seeing really poor performance in my own application outside of the viewer

**Comment by MAG-AdrianMeredith** [comment]
threejs viewer matches babylon (apart from the broken/inverted scale)

**Comment by MAG-AdrianMeredith** [comment]
p.s. thanks for looking into it I appricate it

**Comment by epreston** [comment]
Could you post your custom file and provide more details ?  The arc way is on the right in the original file and your textures are inverted backwards.  None of these tools can reasonably display the original file converted with the details you provided.

As someone who publishes and contributes to all of these projects, publishes his own, I know well they are within 3% of each other.  Please read the info above to address the graphical issues.

No judgement: if the goal is to make statements, please tell me so.  My time is limited and I don't catch on to these things quickly.

**Comment by slimbuck** [comment]
I've taken a look at this myself and found the following:
- pc model-viewer lighting matches the [khronos reference viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/) closely if you match the environment and its orientation (orientation of the environment makes a huge difference to specular in this scene).
- performance seems roughly equal on my machine to babylon using similar settings (though the babylon fps counter is maxed to 60fps). I suspect the biggest difference between the two in terms of performance is:
    - pc model-viewer renders to native screen pixel resolution, whereas babylon renders to CSS resolution (i.e. on retina displays we're rendering 4x the pixels). You can match babylon resolution by setting "Pixel Scale" in model-viewer to devicePixelRatio.
    - pc model-viewer is rendering with maximum anisotropy on all textures. this will be particularly slow on a scene with this many large textures. I don't see an option for specifying anisotropy in babylon, so assume it's using anisotropy of 1.
- almost all surfaces in this glb are flagged as semi-transparent and I notice the khronos viewer does a much better job of rendering the scene with much less render order popping. I investigated further and believe we should use the same approach in pc - PR incoming (babylon matches pc model-viewer in this respect with much popping).

Comparison with matched lighting:
| PlayCanvas | Khronos |
| --- | --- |
| <img width="800" alt="Screenshot 2023-10-02 at 14 39 34" src="https://github.com/playcanvas/engine/assets/11276292/48d34fd0-9f65-4848-96b4-0d5539fb2aab"> | <img width="800" alt="Screenshot 2023-10-02 at 14 39 32" src="https://github.com/playcanvas/engine/assets/11276292/97a8ae7a-64e7-457b-98a2-6d74d41e7f35"> |

**Comment by slimbuck** [comment]
I also found model-viewer continues to render a shadow catcher depth buffer every frame (for VSM shadow) even when the shadow catcher is disabled.

Of course this adds a lot of overhead on a scene like this. A followup PR will fix this too :)

**Comment by Maksims** [comment]
When benches/tests are made with claims, please provide links to both tests as well as sources (if possible).

**Comment by mvaligursky** [comment]
This seems to be resolved now, closing. Please reopen if that's not the case.
