### ISSUE TITLE
SharedArrayBuffer feature request

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5713]
Currently SharedArrayBuffer is disabled in Launcher, due to the current cross origin policies. This is a feature request to enable its support.

Additional info: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements

**Comment by marklundin** [comment]
Let me take a look at this and have a chat with the team. I'm keen to have this feature but just need to run through any implications.

**Comment by marklundin** [comment]
@LeXXik Just wondering, have you got any specific use case in mind for this?

**Comment by LeXXik** [comment]
I have physics running in a webworker. The state of the physics world is currently not shared with the main thread, which makes some operations, like syncing entities with bodies, more expensive than I'd like them to be.

**Comment by MAG-AdrianMeredith** [comment]
Same here, using webassembly with threads require coop + coep for sharedarray buffer

**Comment by mvaligursky** [comment]
Can this be optional in project settings in the Editor?

**Comment by marklundin** [comment]
@isumygin-sc I think it's only if those 3rd party resources need to use SharedArrayBuffer. Which they shouldn't as it'll be unavailable for them currently. 

I think they do need to have [CORS set though](https://web.dev/articles/cross-origin-isolation-guide)

**Comment by MAG-AdrianMeredith** [comment]
> Can this be optional in project settings in the Editor?

You read my mind

**Comment by MAG-DanielMurdolo** [comment]
Any idea when this work will be undertaken yet?

**Comment by willeastcott** [comment]
We hope to get to this within the next few weeks. Does that work for you?

**Comment by MAG-DanielMurdolo** [comment]
> We hope to get to this within the next few weeks. Does that work for you?

That will work for us. Thank you for the update.

**Comment by isumygin-sc** [comment]
the feature is implemented, will be deployed soon

**Comment by isumygin-sc** [comment]
it's deployed to PROD, please test it there. Don't forget to enable the feature in project settings first.

**Comment by LeXXik** [comment]
Not sure where to find that setting.

**Comment by isumygin-sc** [comment]
![image](https://github.com/playcanvas/engine/assets/141647456/82581b45-bdb9-4944-9c07-56757d653521)

**Comment by MAG-DanielMurdolo** [comment]
Worked perfectly, thank you!
