### ISSUE TITLE
Cube example in README's is leaking resize event

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#5720]
Currently we have this example:

https://github.com/playcanvas/engine/blob/f50389793f971b10ada508e02b77060ec72744a4/README.md?plain=1#L73-L110

And if we `app.destroy()` and then resize the window:

![image](https://github.com/playcanvas/engine/assets/5236548/423f2e32-4086-44f6-b79c-4709bae012dc)

Should we fix this in every README or is it more important to have a short example?

Possible solution:

```js
    // Ensure canvas is resized when window changes size
    const resize = () => app.resizeCanvas();
    window.addEventListener('resize', resize);
    app.on('destroy', () => {
        window.removeEventListener('resize', resize);
    });
```

(imo we should showcase proper event handling as it's a common source of bugs)

**Comment by mvaligursky** [comment]
nice find - yeah we should fix this (and others similar?) examples if possible.

**Comment by mvaligursky** [comment]
Makes sense, closing.
