### ISSUE TITLE
Engine examples memory leak

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5724]
Looks like the engine examples have a memory leak. 

Repro steps:

- Open any engine example, e.g. https://playcanvas.github.io/#/misc/hello-world
- Open Memory tab in the Chrome dev tools
- Click the refresh icon at the top left of live editor

Every time the example is live-reloaded, the memory heap increases.

**Comment by mvaligursky** [comment]
Note: This wont fix with the current example application, as it will soon be replaced in this PR: https://github.com/playcanvas/engine/pull/5555

We'll need to test the new version.

**Comment by LeXXik** [comment]
Thank you for looking into it @kungfooman! 

PS
I noticed your linked site throws in hello world example when clicking refresh icon and using WebGPU. Probably just work in progress.

**Comment by mvaligursky** [comment]
> I noticed your linked site throws in hello world example when clicking refresh icon and using WebGPU.

I'm not getting this. Any details?

**Comment by LeXXik** [comment]
I have this:
![image](https://github.com/playcanvas/engine/assets/5677782/de24c158-7cfd-457c-b1c9-7503e6f3fa8b)

**Comment by mvaligursky** [comment]
I think we had this before, when hitting reload example on a lot .. and when the example would ru on destroyed app. I have not seen that since it was fixed, but maybe there is still some way. Maybe WebGPU fails to initialize. Can you run https://playcanvas.github.io/ in WebGPU mode?

**Comment by LeXXik** [comment]
https://github.com/playcanvas/engine/assets/5677782/a03e1d89-b143-43c2-a2d7-92e3c6e47cfe

**Comment by LeXXik** [comment]
Closing this, as the new examples don't exhibit this. For the WebGPU issue, please refer to #5729.
