### ISSUE TITLE
Mesh instance world AABB update

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5725]
This is a follow up to forum: https://forum.playcanvas.com/t/boundingbox-of-a-moving-mesh-does-not-update-properly/33296/11

This ticket is to evaluate whether mesh instance world AABB behavior is correct.

Repro: https://playcanvas.com/project/1147680/overview/mesh-instance-issue

**Comment by lucaheft** [comment]
Here is another sample project, which illustrates this issue:
https://playcanvas.com/project/1147948/overview/mesh-instance-aabb-update

Yellow → Mesh aabb
Magenta → MeshInstance aabb

**Comment by mvaligursky** [comment]
Agreed, it seems this is not handled and so the world aabb does not get updated - as that one is cached and only gets updated when transform changes. So the workaround is to update the transform.
