### ISSUE TITLE
Anti Aliasing is suddenly deactivated

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#5727]
Example before/after:

![image](https://github.com/playcanvas/engine/assets/5236548/b04c6a1c-56b9-4d3b-bd25-3b702180b62c)

Last PR I could find is: https://github.com/playcanvas/engine/pull/5679

Is this expected behaviour?

**Comment by mvaligursky** [comment]
I'm not sure I can confirm. I loaded `https://playcanvas.github.io/#/misc/hello-world`

Then add this line to render into low resolution and make it visible:

![Screenshot 2023-10-06 at 15 09 43](https://github.com/playcanvas/engine/assets/59932779/cec45aa2-a5df-45cf-87f4-d22eb5252cce)

and then toggle antialias this way:

![Screenshot 2023-10-06 at 15 10 42](https://github.com/playcanvas/engine/assets/59932779/906948ce-e7d7-44e8-b850-4d126f7b1943)

and that seems to work ok with expected difference between `true` and `false`. Same in the blend-trees-1d example.
