### ISSUE TITLE
iPhone 6 + iOS 9.3.1 + Safari 9: Transparent materials look white from far/medium distance #3

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#573]
See details here: https://github.com/playcanvas/webvr/issues/3

Seems like this is an engine bug rather than something specific to the webvr library. Possibly render states when using viewports on the camera?

**Comment by guycalledfrank** [comment]
Is there an easier way to reproduce?

**Comment by willeastcott** [comment]
No reproducible was ever provided so I'm closing this.
