### ISSUE TITLE
[Bug] Shadow flickering on dynamic rigidbodies

### ISSUE THREAD

**Issue by redsparkzone** [playcanvas/engine#575]
Sample project:
https://playcanvas.com/project/393993/overview/shadow-flickering-bug

Just hit play and see the shadow flickering.
Adjusting shadow distance and bias wasn't able to eliminate the issue.

**Comment by redsparkzone** [comment]
Turns out that happens if directional light is looking strictly down, i.e, with (0,0,0) rotation. If you rotate is slightly, for example to (-1, 1, 0) - the issues gets solved.

**Comment by willeastcott** [comment]
Definitely one for @guycalledfrank

**Comment by guycalledfrank** [comment]
Should be fixed in https://github.com/playcanvas/engine/issues/575
