### ISSUE TITLE
Procedural mesh index issue

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5755]
Trying to read the first triangle of a procedural mesh, e.g. a default box. I would expect the first 3 indices to point to the vertices of the first triangle, but this is not the case.

Repro:
https://playcanvas.com/project/1151371/overview/procedural-mesh-index-issue

![image](https://github.com/playcanvas/engine/assets/5677782/3bfb5941-e9c3-4d1c-bd6f-421ecd0385c8)

Possibly related: https://github.com/playcanvas/engine/issues/5637

**Comment by mvaligursky** [comment]
Your example has the issue and not the engine fortunately. You need to multiply index by 3 like this:

```
    start.set(pos[a*3], pos[a*3+1], pos[a*3+2]);
    end.set(pos[b*3], pos[b*3+1], pos[b*3+2]);

    this.app.drawLine(start, end, pc.Color.WHITE, false);

    start.set(pos[b*3], pos[b*3+1], pos[b*3+2]);
    end.set(pos[c*3], pos[c*3+1], pos[c*3+2]);

    this.app.drawLine(start, end, pc.Color.WHITE, false);
    
    start.set(pos[c*3], pos[c*3+1], pos[c*3+2]);
    end.set(pos[a*3], pos[a*3+1], pos[a*3+2]);

    this.app.drawLine(start, end, pc.Color.WHITE, false);
```

and get this
![Screenshot 2023-10-16 at 09 51 43](https://github.com/playcanvas/engine/assets/59932779/384900b0-9e27-467a-8917-107e6165f769)
