### ISSUE TITLE
Swizzling for VecN classes

### ISSUE THREAD

**Issue by kpal81xd** [playcanvas/engine#5771]
### Description

Implement swizzling like in GLSL for vectors for more compact and readable vector transposition and manipulation.

### Example

``` js
const a0 = new pc.Vec2(1, 2); // { x: 1, y: 2 }
const a1 = v0.yx; // { x: 2, y: 1 }
const a2 = v0.yy; // { x: 2, y: 2 }

const  b0 = new pc.Vec3(1, 2, 3); // { x: 1, y: 2, z: 3 }
const b1 = b0.xy; // { x: 1, y: 2 } (notice the change in shape to Vec2)
```

### Implementation

- I have created a prototype of this already on a local branch for a PR which trivially reconstructs a new Vector depending on the property name using Object descriptors unless the axis ordering is the same in which case a clone of the original vector is returned.
- Looking into using matrix transformations instead but that would also involve reconstructing the vector regardless to maintain the original vector.

### Potential Issues

- The number of swizzle properties increases exponentially with each dimension as shown with the `Vec3` and `Vec4` classes and causes them to be bloated with a lot of unused getters. A potential solution would be to predefine which swizzle properties you would use or in the case of the editor to perform an automatic "find and replace" style macro when saving your script (Possibly use a custom Babel extension?).

| Dimensions | Swizzle Property Count |
| ----------- | ----------- |
| 2 | 28 |
| 3 | 117 |
| 4 |  336 |

**Comment by marklundin** [comment]
Hey @kpal81xd, this is great, but my main concern is that I'm assuming it creates new vectors, which can quickly add up. It's not as clean, but using something like `b = new Vec2(a.y, a.x)` at least makes it clear a new Vector is being created.

**Comment by willeastcott** [comment]
Yep, agreed. This could potentially lead to performance issues and contribute to garbage collection stalls. Plus it'll grow an API we have traditionally tried to keep as small and focused as possible (we are extremely keen to keep the engine as lightweight as possible - unlike native engines). I gotta say, I've never seen anyone request vector swizzling CPU side and I'm not hugely keen on developing a solution to a problem that doesn't necessarily exist. Thanks for thinking about this though!

**Comment by mvaligursky** [comment]
I'll close this as it's not likely we'll be implementing this.
