### ISSUE TITLE
Error when canvas display is none

### ISSUE THREAD

**Issue by marklundin** [playcanvas/engine#5806]
When the a canvas is hidden using css 

```javascript 
document.body.querySelector('#application-canvas').style.display = "none";
``` 
The graphics device throws

`Framebuffer creation failed with error code FRAMEBUFFER_INCOMPLETE_ATTACHMENT, render target: WebglFramebuffer MSAA`

See this repro https://launch.playcanvas.com/1406528?debug=true and https://forum.playcanvas.com/t/engine-1-66-assert-failed-framebuffer-creation-failed/33734/3

**Comment by marklundin** [comment]
closing this as per [this comment](https://github.com/playcanvas/engine/pull/5807#discussion_r1387722930) It's important that users are able to know  when they have an invalid canvas dimension

**Comment by mvaligursky** [comment]
I'll add some logging to make it clear to the user what the problem is.
