### ISSUE TITLE
[Examples] Make HIDDEN flag to hide examples from build

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5812]
We used to have a system where HIDDEN flag would allow the example for local development, but exclude it from the published build, which is used to submit work-in-progress examples.

`lit-material.mjs` currently has this 
`    static HIDDEN = true;`
but it is not used, and the example is excluded instead manually this way:
```
// export * from "./lit-material";   // note that this is also excluded in read-dir.mjs
```

Perhaps we could:
- ignore examples with HIDDEN when using `npm run build`
- include them when doing `npm run develop`

**Comment by mvaligursky** [comment]
@kungfooman - would you have any thoughts on this, how much work is involved?
(Note a huge priority, but nice to have if easy to do)

**Comment by kungfooman** [comment]
Good idea to have work-in-progress examples excluded in Release, so one can concentrate on what really matters... without worrying to have work-in-progress accidentally published by forgetting to exlude it again later.

I didn't attempt it so far, but it's probably changing like max 5 lines here and there.
