### ISSUE TITLE
Splats not rendering on iPhone XS

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#5822]
Device is on iOS 17.1.1. Neither SuperSplat or the Viewer work.

Works fine on iPhone 14 Pro.

**Comment by mvaligursky** [comment]
The shader does not compile on WebGL 1 as well

**Comment by LeXXik** [comment]
Works fine on 12 Pro Max.

**Comment by willeastcott** [comment]
@LeXXik Good to know. I checked my XS - WebGL 2.0 is available on the device.

**Comment by slimbuck** [comment]
Fix for webgl1 in https://github.com/playcanvas/engine/pull/5835

**Comment by willeastcott** [comment]
Seems fine now:

![Image from iOS](https://github.com/playcanvas/engine/assets/697563/a73d109b-e992-4464-a674-f29f9ed7a121)

Closing.
