### ISSUE TITLE
Adding a layer with a RenderTarget that requests depth rendering does not actually render depth

### ISSUE THREAD

**Issue by MAG-ME** [playcanvas/engine#5823]
### Description

With the following scenario the `RenderPass` including the depth buffer does not output depth information. It seems the code that sets the flag to request depth rendering in `frame-fraph.js` can only set the flag `storeDepth` when there is a previous pass for the render target. In this case the render target only has a single pass and so the flag cannot be set.

### Steps to Reproduce

1. Create a render target with an attached texture for the depth buffer
2. Add a layer with this render target
3. Use the depth buffer in a post processing layer

```
      depthTexture = new pc.Texture(renderer._app.graphicsDevice, {
        width: app.graphicsDevice.canvas.clientWidth,
        height: app.graphicsDevice.canvas.clientHeight,
        format: pc.PIXELFORMAT_DEPTH,
        mipmaps: false,
        minFilter: pc.FILTER_NEAREST,
        magFilter: pc.FILTER_NEAREST,
        addressU: pc.ADDRESS_CLAMP_TO_EDGE,
        addressV: pc.ADDRESS_CLAMP_TO_EDGE,
      });
      depthTexture.upload();

      renderTarget = new pc.RenderTarget({
        colorBuffer: colorTexture,
        depthBuffer: depthTexture,
        depth: true,
        autoResolve: false,
      });

      outlineCamera = new pc.Entity();
      outlineCamera.addComponent('camera', {
        clearColor: new pc.Color(0.0, 0.0, 0.0, 0.0),
        layers: [outlineLayer.id],
        fov: cameraComponent.fov,
        nearClip: cameraComponent.nearClip,
        farClip: cameraComponent.farClip,
      });

      outlineLayer = new pc.Layer({
        name: "OutlineLayer",
      });
      app.scene.layers.insert(outlineLayer, 0);

      outlineLayer.renderTarget = renderTarget;
      outlineLayer.passThrough = true;
```

**Comment by mvaligursky** [comment]
Marking this fixes in https://github.com/playcanvas/engine/pull/6918 as the main issue here is sorted.
Note that the engine v2 removes the support for Layer.renderTarget and so this specific case was not tested, as it's no longer possible.
