### ISSUE TITLE
2D screen broken when setting canvas display to none

### ISSUE THREAD

**Issue by NewboO** [playcanvas/engine#5841]
Since 1.66.0, 2D screens are no longer working after hiding the canvas.

### Steps to Reproduce

1. Add a 2D screen to scene with some elements
2. Hide the canvas using `document.getElementById('application-canvas').style.setProperty('display', 'none')`
3. Unhide the canvas using `document.getElementById('application-canvas').style.removeProperty('display')`
4. The 2D screen is now gone forever

3D screens are still working correctly though.

**Comment by mvaligursky** [comment]
possibly related to https://github.com/playcanvas/engine/issues/5806
