### ISSUE TITLE
Spelling Mistake Reporting

### ISSUE THREAD

**Issue by arcadian-st** [playcanvas/engine#5855]
### Description

I apologize for openning an issue for a small case, but it seems that there is a spelling mistake at [event-handle.js](https://github.com/playcanvas/engine/blob/main/src/core/event-handle.js) Line 93:
```javascript
        Debug.deprecated('Using chaning with EventHandler.once is deprecated, subscribe to an event from EventHandler directly instead.');
```
I suppose the "chaning" here should be "chaining" comparing with Line 88 of the same script.

**Comment by kungfooman** [comment]
Nice find, would you like to try submitting a pull request (PR)?

**Comment by Maksims** [comment]
Usually @willeastcott spots my bad writing 😋🙏
