### ISSUE TITLE
PLY file exported from SuperSplat fails to parse using PlyParser

### ISSUE THREAD

**Issue by movAX13h** [playcanvas/engine#5865]
I've tried to load and display a compressed PLY file that I exported from SuperSplat in a PlayCanvas project using **PlyParser** from **playcanvas-extras** via the `registerPlyParser` function like in the example but the parser fails in SplatData.transform (splat-data.js).

The x prop is undefined and the resulting error is: `Cannot read properties of undefined (reading '0')`.

The file loads without problems in SuperSplat.

I've tried `biker.ply` from the examples to verify that nothing else is wrong in my setup and it loaded successfully.

I've noticed differences in the file header but I've not looked into the details of the ply file format and the parser enough to make further conclusions.

Here's the ply file that's not working (made by me).
[zimmerpflanze1.zip](https://github.com/playcanvas/engine/files/13493716/zimmerpflanze1.zip)

Is SuperSplat using the extras or does it have its own parser? I know, I could look it up but it's late now ... and others might run into the same problem. Sorry if this bug request is too early.

**Comment by slimbuck** [comment]
Hi @movAX13h,

By default the PLY loader only loads the default property data and this means by default the compressed data is ignored.

Here is an example project that demonstrates how to load the PLY:

https://playcanvas.com/project/1165904/overview/gaussiansplatdemo

The important bit overriding the element filter is in `gs.js`:
```javascript
const gsAsset = new pc.Asset('gsModel', 'container', this.modelAsset.file, { elementFilter: () => true });
```

I would like to change it so all PLY data is loaded by default and require override only if user wants to limit data. I'll submit PR with that change.

Thanks so much for reporting the issue!

**Comment by movAX13h** [comment]
Thank you very much for your response.
The elementFilter setting did the trick!

**Comment by mvaligursky** [comment]
Closing as this seems to be solved.

**Comment by willeastcott** [comment]
Seems resolved. Closing...
