### ISSUE TITLE
Can't enlarge vertex buffer

### ISSUE THREAD

**Issue by thisredone** [playcanvas/engine#5878]
after #5758 can't enlarge vertex buffers

![image](https://github.com/playcanvas/engine/assets/1191844/4807a006-9608-4bc7-8775-0c20e306658a)

`bufferSubData` throws when calling `vertexBuffer.setData` with bigger buffer. This breaks for example instancing

**Comment by mvaligursky** [comment]
The API was not designed to allow you to resize a VB this way, you need to re-create the VertexBuffer. You can always also create it larger and use only portion of it.
What you do worked by accident, and won't work on WebGPU for example.

**Comment by slimbuck** [comment]
See the base class https://github.com/playcanvas/engine/blob/main/src/platform/graphics/vertex-buffer.js#L139

**Comment by mvaligursky** [comment]
the setData used to error for a long time now .. how were you using it without getting the errors?
<img width="1436" alt="Screenshot 2023-12-05 at 12 48 45" src="https://github.com/playcanvas/engine/assets/59932779/a47c4f18-557e-4175-b4b0-d47c11126360">

I think what you should do is to call `vb.Lock();`, update partial data as needed, and then `vb.unlock();`
The number of instances for instancing can be then controlled using `MeshInstance.instancingCount = 10;`

**Comment by thisredone** [comment]
I was always updating buffer.byteLength when updating the contents so the Debug.error never came up ;-)
