### ISSUE TITLE
WebXR hit test bugs

### ISSUE THREAD

**Issue by slimbuck** [playcanvas/engine#5884]
After #5778 hit tests are being raised even if there aren't any results.

The previous code raised an event for every result in the array, while the new code doesn't check if any results were received. The first hit test is reported as (0, 0, 0).

I fixed this locally by adding the following test, but there may be a better way.
```javascript 
    updateHitResults(results, inputSource) {
        if (results.length === 0)
            return;
```

Also, if you initiate hit testing with `xr.hitTest.start` (and specify profile 'generic-touchscreen', if that matters), then `hitTestSourcesSet` is not populated with the hit test source and no hit tests are reported.

These two issues mean model-viewer XR mode no longer works.

cc @Maksims

**Comment by Maksims** [comment]
Will debug it asap.
