### ISSUE TITLE
Depth Target change resolution in one axis will lead to bug.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#589]
On this line: https://github.com/playcanvas/engine/blob/master/src/scene/forward-renderer.js#L924
Condition assumes that changing of render target resolution have to happen with width and height at the same time, but what if resolution is changed in horizontal or vertical direction only.
Then it will not recreate render target, which will lead to a bug.

And `meshInstance` is not defined in a loop above, how does it checks it's blending for first iteration?:
https://github.com/playcanvas/engine/blob/master/src/scene/forward-renderer.js#L953

**Comment by guycalledfrank** [comment]
Fixed 
https://github.com/playcanvas/engine/pull/590
https://github.com/playcanvas/engine/pull/591
