### ISSUE TITLE
Remove support for cheap sphere-map reflection option

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#5933]
We have two chunks to evaluate sphere-map reflection: 
- reflectionSphere.js
- reflectionSphereLow.js

The low version is used when there are less than 16 fragment uniforms available., but this no longer compiles as the fragment is not maintained. I suggest we simply remove it and use the reflection of the better quality at all times.

Current issue with the chunk:

```
vec3 calcReflection(vec3 reflDir, float gloss) {
    vec3 reflDirV = vNormalV;    /////////////// vNormalV is not defined, it was likely renamed in the past.

    vec2 sphereMapUv = reflDirV.xy * 0.5 + 0.5;
    return $DECODE(texture2D(texture_sphereMap, sphereMapUv));
}

```

**Comment by willeastcott** [comment]
Doesn't this suggest we're guaranteed to have a minimum of 64:

https://web3dsurvey.com/webgl/parameters/MAX_FRAGMENT_UNIFORM_VECTORS

**Comment by willeastcott** [comment]
DELETE IT! 😆
