### ISSUE TITLE
License needs a year bump

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5937]
The MIT license needs a year update:

https://github.com/playcanvas/engine/blob/b7a9995038c8db9718efca759a1d40adb287c61f/LICENSE#L1

**Comment by willeastcott** [comment]
Does it? I mean, VS Code is still on 2015!

https://github.com/microsoft/vscode/blob/main/LICENSE.txt

😆

**Comment by LeXXik** [comment]
It actually says "present", meaning from 2015 till present day :)

**Comment by willeastcott** [comment]
This has now been done.
