### ISSUE TITLE
Forward renderer reallocates every frame

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#594]
Where shadow params (resolution and bias) are set for shader uniforms, a new array is allocated on every call. This generates garbage every frame.

For example:

scope.resolve(light + "_shadowParams").setValue([spot._shadowResolution, spot._normalOffsetBias, bias, 1.0 / spot.getAttenuationEnd()]);

**Comment by guycalledfrank** [comment]
Fixed in https://github.com/playcanvas/engine/pull/623
