### ISSUE TITLE
Missing TypeDoc classes

### ISSUE THREAD

**Issue by marklundin** [playcanvas/engine#5966]
A number of engine classes including XR ones such as [XRHand](https://github.com/playcanvas/engine/blob/main/src/framework/xr/xr-hand.js) and [XRFinger](https://github.com/playcanvas/engine/blob/main/src/framework/xr/xr-finger.js) are not being picked up by typedoc and therefore no documentation is available for them. This seems to be because they're only used as [`@private`](https://github.com/playcanvas/engine/blob/2c9437f6fd2a07e36457db07fb89990660ad7fd8/src/framework/xr/xr-joint.js#L39) members of other classes and presumably typedoc skips them as non public api, and they're not re-exported by index.js.

The current developer api documentation however [does include](https://developer.playcanvas.com/en/api/pc.XrHand.html) [these classes](https://developer.playcanvas.com/en/api/pc.XrFinger.html), and there are inbound links in the developer site.

Options are we could force typedoc to include these, either by exporting them, or simply just adding them to the list of typedoc entry points. Or we can keep as-is and just remove any references to them. Any thoughts here @mvaligursky @Maksims ?

**Comment by Maksims** [comment]
They should be in Docs and should be available by autocomplete. As they are publicly facing APIs.
They are constructed and assigned to private members, which then are exposed through get accessors as a public properties.

**Comment by mvaligursky** [comment]
I think those just need to be added to the root index.js - all public APIs should be exported from there.
