### ISSUE TITLE
device variable used by not defined

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#597]
In `Material.setParameters()`

https://github.com/playcanvas/engine/blob/master/src/scene/material.js#L313

**Comment by guycalledfrank** [comment]
Was this way since forever. Also, nobody ever used this function, maybe just delete it?

**Comment by Maksims** [comment]
Link in first post points to master, so it is not pointing to right line anymore, is this still an issue?

**Comment by willeastcott** [comment]
The offending lines are now commented out so closing.
