### ISSUE TITLE
WebGPU crash

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#5973]
I think Martin is aware of this, but adding here for tracking.

WebGPU examples crash on Win11 Chrome with error:

![image](https://github.com/playcanvas/engine/assets/5677782/dfcbf29b-ed47-423e-8998-1a1be767fc2f)

**Comment by mvaligursky** [comment]
Hi .. thanks, I'm not aware. By the way, for completeness, which Chrome version are you using.

**Comment by LeXXik** [comment]
Version 121.0.6167.85 (Official Build) beta (64-bit)

Can't find it immediately, but we discussed it briefly in another topic. You said my browser reports something is supported, but not implemented and I that I should try to comment out something in the sources. Commenting it out removed the error.

**Comment by mvaligursky** [comment]
For me on Win10:
Works: Version 120.0.6099.225 (Official Build) (64-bit)
Does not work: Version 121.0.6167.86 (Official Build) (64-bit)
