### ISSUE TITLE
Multi-app example issue

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6018]
The new multi-app example doesn't remove new app instances for me, when `Remove` button is pressed. No console errors.

On Win11 Chrome (Version 122.0.6261.6 (Official Build) beta (64-bit)).

https://playcanvas.github.io/#/misc/multi-application

**Comment by erikdubbelboer** [comment]
Easy fix: https://github.com/playcanvas/engine/pull/6020
