### ISSUE TITLE
SoundComponent events propagation from instance up to slot and component

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#602]
It would be very useful and convenient to subscribe to SoundSlot or SoundComponent `end` event, to get notified when any of instances finished playing, especially in case of non-overlapping slots.

Consider propagating events, for each higher fire it would add extra arguments to callback.
For instance (as is):
```javascript
var instance = entity.sound.slot('shot').play();
instance.on('end', function() {
    // ...
});
```
For slot:
```javascript
entity.sound.slot('shot').on('end', function(instance) {
    // ...
});
```
For component:
```javascript
entity.sound.on('end', function(slot, instance) {
    // ...
});
```

It would be great to propagate almost all events from instances all the way up, as to allow more convenient ways to handle different situations and avoid a need to resubscribe for each individual instance again and again.

**Comment by vkalpias** [comment]
Fixed in https://github.com/playcanvas/engine/commit/5519248787642e75e1606be4b5efac5d945e3979
