### ISSUE TITLE
WebXR issue on PICO Neo 3

### ISSUE THREAD

**Issue by Sycmasters** [playcanvas/engine#6045]
I'm working on a WebXR experience, and everything was functioning well until the update to version 1.68.1 from 1.68. Since the update, all my WebXR projects have stopped working on the PICO Neo 3 headset. However, they continue to work on Meta Quest headsets. Even PC tutorials aren't working.

Here's a link to the tutorial I'm referencing. If this works, there shouldn't be any issues:
https://developer.playcanvas.com/tutorials/webxr-vr-lab/

![image](https://github.com/playcanvas/engine/assets/6709040/72a37466-391b-441d-b591-08bc62ab695e)

The problem occurs specifically on the PICO Browser.

### Steps to Reproduce
1. Open the PICO browser.
2. Navigate to [WebXR VR Lab Tutorial](https://developer.playcanvas.com/tutorials/webxr-vr-lab/).
3. Attempt to enter WebXR mode.

**Comment by willeastcott** [comment]
Hey @Maksims, do you know what's new in 1.68.1 that could have caused this?

**Comment by Maksims** [comment]
There were no changes between 1.68.0 and 1.68.1 that affected anything in the engine related to WebXR or feature detection.
I unfortunately do not have PICO device to test.

To ensure it is only a version related, I've made 2 builds of the VR Starter Kit:
1.68.0 https://playcanv.as/b/548eb056
1.68.1 https://playcanv.as/b/86ea0a35

@Sycmasters please let me know if you do see a problem between these two versions also. If not, then the issue must be due to something else.

**Comment by Sycmasters** [comment]
Hi @Maksims

There's no difference in functionality between version 1.68.0 and 1.68.1; neither works for my project. I've tested it, and the last version that works correctly is 1.67.x.

![image](https://github.com/playcanvas/engine/assets/6709040/b5c5d976-c09c-40af-9038-cffab07f58b3)

So, the issue started with version 1.68.0, while everything operates as expected in version 1.67.x.

**Comment by Maksims** [comment]
> Hi @Maksims
> 
> There's no difference in functionality between version 1.68.0 and 1.68.1; neither works for my project. I've tested it, and the last version that works correctly is 1.67.x.
> 
> So, the issue started with version 1.68.0, while everything operates as expected in version 1.67.x.

So the issue is with the 67 to 68 update. Do you have console logs?

**Comment by Sycmasters** [comment]
@Maksims Yes exactly, but sadly I don't have any logs, it doesn't give back any logs, I just try to enter VR mode and immediately 
 takes me back to a normal web browser without any logs or errors, since I'm not sure what is happening I cannot provide more info than that I'm sorry.

**Comment by Sycmasters** [comment]
Following up on this issue, it seems like my non-PlayCanvas projects work on PICO, so it seems is an engine compatibility issue, but reviewing there is no log or anything that I can provide so I'm still lost about this.

**Comment by fimbox** [comment]
Same here on Pico4. The WebVR Demo does not start VR mode, here is the console output:

![image](https://github.com/playcanvas/engine/assets/28051000/bced87b5-de71-4bd2-99b2-e92d9ee1ea32)

1.67.3 works
1.68.0+ does not start VR mode

**Comment by Maksims** [comment]
This is very helpful! I will make a PR that allows XR features to detect availability in an alternative way.

In short: Pico WebXR implementation is somewhat outdated, that is why it has this property missing.

**Comment by Maksims** [comment]
@Sycmasters, @fimbox pushed a fix, if you could check it with custom built engine on your device, would be awesome.

**Comment by mrxz** [comment]
It seems that #6181 hasn't resolved the issue. When testing with the Pico Browser on a Pico Neo3 Link, I get roughly the same stacktrace as @fimbox reported, pointing to [xr-anchors.js#L181](https://github.com/playcanvas/engine/blob/ca16243422d86e8c0d6f1c3544d484055edcea92/src/framework/xr/xr-anchors.js#L181).

A crude workaround that I'm currently using for the Pico Browser:
```js
XRSession.prototype.enabledFeatures = [];
```
Alternatively it does work with Wolvic, both the gecko based version from the Pico Store as well as with the Chromium based build (sideloaded).

For reference:
- Pico Browser: 3.3.45
- Pico OS: v5.12.2.0.S

**Comment by Maksims** [comment]
Checked the source, that place I've missed, need to slightly change it. Thanks for pointing to where issue happens.
Adding `XRSession.prototype.enabledFeatures` will confuse the system, as it will perceive like nothing is available - so it is not a good workaround.

I've just made a PR to fix this particular place: https://github.com/playcanvas/engine/pull/7654

**Comment by Maksims** [comment]
> Thanks for the prompt fix!

No problem. 

> Though the Pico Browser on the Neo3 really doesn't implement any meaningful WebXR features beyond the bare minimum (only `layers` beyond `viewer/local/...`). An empty array is sadly very close to what it would be were it implemented 😅

Hopefully they will be updating their browser with more features, likely once AndroidXR will be commercially available (they're likely to support a lot of WebXR features).
