### ISSUE TITLE
GSplats stereoscopic rendering (viewport size issues)

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#6053]
Currently GSplats has to use [viewport dimensions](https://github.com/playcanvas/engine/blob/7f9cb585a83ee6f6986e94cb2e3da4c95f18c27b/src/scene/gsplat/gsplat-instance.js#L138-L144) which affects the way they are rotated and scaled. Aspect ratio of this viewport is the main driving element. In WebXR stereoscopic scenario, viewport is split into two so the the renderer of the splats look wrong.

The quick workaround I've made is to detect if there are multiple XR views, and split viewport width in two:

```javascript
const viewport = [0, 0];

pc.GSplatInstance.prototype.updateViewport = function () {
    const device = this.splat.device;

    viewport[0] = device.width;
    viewport[1] = device.height;

    if (app.xr.active && app.xr.views.list.length === 2)
        viewport[0] /= 2;

    this.material.setParameter('viewport', viewport);
};
```

But it needs a slightly better solution, for getting an actual viewport of a view.

**Comment by mvaligursky** [comment]
another mention: https://forum.playcanvas.com/t/apple-vision-pro-examples/36024/12
