### ISSUE TITLE
Polyfills should be a build step only

### ISSUE THREAD

**Issue by marklundin** [playcanvas/engine#6072]
The engine currently ships with a [load of polyfills](https://github.com/playcanvas/engine/tree/main/src/polyfill) which are [automatically imported](https://github.com/playcanvas/engine/blob/631493694dd3fb23c9c79fa77c6f4a6380c3aa1c/src/index.js#L12-L22) in a build whether you need them or not. Consequently building against a modern target like ES2020 inlines these polyfils when they're actually not required. In addition, if playcanvas is included in a project with it's own build step + polyfills, these would likely clash. 

Ideally polyfills should be part of the build step and not the source code. Using core-js with babel-preset-env or similar, only the required polyfills are chosen based on the chosen output target

**Comment by marklundin** [comment]
> Perhaps we should only add them when building ES5 targets, but not when building ESM?

We also don't include a polyfill for `Object.entries()` which is partially responsible for #6011. So including it as part of the build would catch whenever we introduced a new language feature an polyfill for it

**Comment by marklundin** [comment]
For now though, you're probably right @mvaligursky, we can just add a conditional flag that omits from the ES6 build

**Comment by slimbuck** [comment]
Wouldn't it be easier to change the engine compile process to translate output ESM build to UMD and have that step add the polyfills?

**Comment by marklundin** [comment]
[core-js](https://github.com/zloirock/core-js/tree/master) does this. However some initial tests show it's quite aggressive. For example including `new Float32Array()` [adds polyfills for all methods](https://babeljs.io/repl#?browsers=chrome%208&build=&builtIns=usage&corejs=3.21&spec=true&loose=true&code_lz=HYUw7gBAYgNg9gQwC4GYBMBBATlhBPACgEog&debug=false&forceAllTransforms=true&modules=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=unambiguous&lineWrap=false&presets=env&prettier=false&targets=&version=7.23.10&externalPlugins=babel-plugin-syntax-dynamic-import%406.18.0%2C%40babel%2Fplugin-syntax-dynamic-import%407.8.3&assumptions=%7B%7D), even those methods are never called. I imagine this is by design (maybe some of the polyfills depend on each other), but as our build UMD target is pretty old, core-js is adding around 160Kb of code, just for TypedArray. 

Auto-polyfilling definitely seems like the right way to go, but it needs some more investigation and optimisation. Either way, as #6011 shows, we don't have a polyfill for `Object.entries`, which is [used in a few places](https://github.com/search?q=repo%3Aplaycanvas%2Fengine%20Object.entries&type=code), so the current UMD build has not worked with those code paths on [pre Chrome 54 era](https://caniuse.com/?search=Object.entries) browsers.

**Comment by mvaligursky** [comment]
Considering we're hoping to deprecate the IMD build in no too distant future, we might just add that single polyfill missing at the moment and call it a day for now.

**Comment by marklundin** [comment]
I think that's fine for now, we just exclude these in the ES6 build

**Comment by marklundin** [comment]
Closing for now. ESM build omits the polyfills.
