### ISSUE TITLE
Investigate running engine examples in WebGPU mode using Safari

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#6088]
Safari now has a behind flag version of the WebGPU in tech preview: https://twitter.com/quicksave2k/status/1737758115720769708

I tested this with Safari Tech Preview Release 189 (Safari 17.4, WebKit 19619.1.3.2)

When running local build of the examples, for example shapes, I get validation errors with no reasons listed:

<img width="1139" alt="Screenshot 2024-02-26 at 12 29 20" src="https://github.com/playcanvas/engine/assets/59932779/f8bd0a7e-d825-490b-91a1-06bc138acb31">

Interestingly, when I disable our validation (commend out inside of functions in `WebgpuDebug` class, the browser does not log out any validation issues, which it should. Do they have some validation API issues?

The end result is, that in neither case, the examples work. We get different clear color in few examples, so it seems the clear color works in some cases, but nothing else gets rendered.

Often we also get
<img width="363" alt="Screenshot 2024-02-26 at 12 28 44" src="https://github.com/playcanvas/engine/assets/59932779/017102a6-323a-4778-bb44-c2fa12391beb">

**Comment by mwyrzykowski** [comment]
I commented in the webkit report but at least one issue, there appear to be several, is that playcanvas is assuming an alignment of 32 bytes for dynamic offsets, based on the 288 value observed. The specification default is 256 and 288 is not divisible by 256. I filed https://bugs.webkit.org/show_bug.cgi?id=272378 to fix the error message

I locally modified WebKit's alignment to be 32, but I see other errors and continue to investigate.

**Comment by mvaligursky** [comment]
@mwyrzykowski - thanks for the update, much appreciated. I responded on the original webkit ticket.

**Comment by willeastcott** [comment]
@mvaligursky Can this be closed now? The two logged WebKit issues are now marked as RESOLVED FIXED.

**Comment by mvaligursky** [comment]
I'll close it when the Safari Tech Preview contains fixes I can verify.

**Comment by mvaligursky** [comment]
Confirmed fixed in Safari Tech Preview 194
