### ISSUE TITLE
Stopped working with SvelteKit / Vite SSR

### ISSUE THREAD

**Issue by michaelfranzl** [playcanvas/engine#6105]
### Description

I'm using Playcanvas in SvelteKit. This works well up until Playcanvas v1.65.5 but stops working when upgrading to the following release of Playcanvas, which is v1.66.0 (and newer).

### Steps to Reproduce

The issue is reproducible with minimal effort.

Using Node.js v20.11.1 LTS, create a new SvelteKit application:

```bash
mkdir test
cd test
npm create svelte@latest # interactively accept all defaults
npm i
```

In the file `src/routes/+page.svelte` import Playcanvas and instantiate a `Vec3`:

```js
import * as pc from 'playcanvas';
const vec3 = new pc.Vec3();
```

Save the file and start the server:

```
npm run dev
```

Access the URL printed in the terminal (either using browser or using curl/wget).

Vite immediately crashes with the following messages:

```
  VITE v5.1.4  ready in 615 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network:  use --host to expose
  ➜  press h + enter to show help
TypeError: __vite_ssr_import_4__.Vec3 is not a constructor
    at /path/to/test/src/routes/+page.svelte:8:12
    at Object.$$render (/path/to/test/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.default (/path/to/test/.svelte-kit/generated/root.svelte:45:41)
    at eval (/path/to/test/src/routes/+layout.svelte:20:218)
    at Object.$$render (/path/to/test/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at /path/to/test/.svelte-kit/generated/root.svelte:44:40
    at $$render (/path/to/test/node_modules/svelte/src/runtime/internal/ssr.js:156:16)
    at Object.render (/path/toS/test/node_modules/svelte/src/runtime/internal/ssr.js:164:17)
    at Module.render_response (/path/to/test/node_modules/@sveltejs/kit/src/runtime/server/page/render.js:171:29)
    at async Module.render_page (/path/to/test/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:286:10
```

I tested with Vite v4.5 and current (v5.0) and @sveltejs/kit v1.27 and current (v2.0), with the same results.

**Comment by mvaligursky** [comment]
@marklundin - any idea here?

**Comment by marklundin** [comment]
Hey @michaelfranzl, thanks for flagging this and the detailed repro.

Great catch. It looks like the engine [was updated in 1.66.0](https://github.com/playcanvas/engine/pull/5635/files) to use type module in the package.json https://github.com/playcanvas/engine/blob/d75dba58a5ca60178f31d4a9c7e5bcb094e75eb3/package.json#L24

My understanding is that If the type is a module, then Node expects `main' to be a ES module, which it actually is not.

For the time being, you should be able to directly import the ES6 build using `import { Vec3 } from 'playcanvas/build/playcanvas.mjs'`. But we'll need to update our side to correctly handle this.

**Comment by marklundin** [comment]
It looks like we can fix this by including an exports field

```json
"exports": {
  ".": {
    "import": "./build/playcanvas.mjs",
    "require": "./build/playcanvas.js"
  }
},
```

This looks like the recommended approach for  Node > 10 https://nodejs.org/api/packages.html#package-entry-points

**Comment by kpal81xd** [comment]
Yep that looks fine to me had a similar issue with exports for react on PCUI. Ill make a PR to add that change

**Comment by marklundin** [comment]
Yep, I think we still need the existing `main` and `modules` fields for older versions of Node, but this should at least "feature detect" if import is available
