### ISSUE TITLE
Exception noted when using bloom renderpass

### ISSUE THREAD

**Issue by MAG-AdrianMeredith** [playcanvas/engine#6113]
### Description

I'm seeing an exception after testing the lastest builds when using the new renderpasses.  Looking at the code in vscode makes it quite clear that it can be undefined so looks like a simple oversight

![image](https://github.com/playcanvas/engine/assets/100127317/0a862353-aff2-4c9f-81f4-2178fcd2d4a1)

exception here 
playcanvas.mjs:32653 Uncaught TypeError: Cannot read properties of null (reading 'id')
    at ForwardRenderer.buildFrameGraph (playcanvas.mjs:32653:1)
    at AppBase.renderComposition (playcanvas.mjs:42356:1)
    at AppBase.render (playcanvas.mjs:42352:1)
    at eval (playcanvas.mjs:42761:1)
    
  I don't have an example repo case but hopefully the ide warning is enough

**Comment by mvaligursky** [comment]
Could you please look in the debugger to see when this happens? Render actions are created for rendering of layers, so typically this cannot be null. Is there maybe an instance of RenderPassForward with no layers added to it?

**Comment by MAG-AdrianMeredith** [comment]
Looks like it happens when we use our "Outline" posteffect it appears to be creating 3 renderActions, with the last one being totally empty.  Any background information on what creates render actions?

![Screenshot 2024-03-06 at 14 56 32](https://github.com/playcanvas/engine/assets/100127317/df72ed14-03d3-42d5-ae83-61b482c2f097)

**Comment by MAG-AdrianMeredith** [comment]
Do post effects still work in the new world or does this need porting to render passes?

**Comment by mvaligursky** [comment]
Post-effects work if you do not use render passes.
If you use render passes, you cannot use post-effects as those are not converted to render passes.

**Comment by MAG-AdrianMeredith** [comment]
Thats probably the issue then would it be unreasonable to log an error to the console in this case?

**Comment by mvaligursky** [comment]
Yeah that's definitely on the list. For now it's just a work in progress that's not released for public use. When we'll get it release-ready and documented, we'll port multiple engine examples to use it, make sure issues / errors are reported and similar.

I'll see if I can add some assets for case early though.

**Comment by MAG-AdrianMeredith** [comment]
Thanks for your help, this is is why I wanted to test things to see what breaks ;). I'll give it another go again next release or two

**Comment by mvaligursky** [comment]
The fix was released in https://github.com/playcanvas/engine/releases/tag/v2.1.0, I forgot which PR.
