### ISSUE TITLE
Missing documentation on many properties

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#612]
There is number of missing references for fields on different components:

light.bake
light.affectDynamic
light.affectLightmapped
light.shadowUpdateMode
light.shadowType
light.vsmBlurMode
light.vsmBlurSize

model.castShadowsLightmap
model.lightmapped
model.resolution
model.lightmapSizeMultiplier

material.aoMapUv
material.aoMapOffset
material.aoMapTiling
material.aoMapVertexColor
material.diffuseMapUv
material.diffuseMapVertexColor
material.metalnessMapUv
material.metalnessMapOffset
material.metalnessMapTiling
material.metalnessMapVertexColor
material.specularMapUv
material.specularMapVertexColor
material.glossMapUv
material.glossMapVertexColor
material.emissiveMapUv
material.emissiveMapVertexColor
material.opacityMapUv
material.opacityMapVertexColor
material.normalMapUv
material.heightMapUv
material.lightMapUv
material.lightMapOffset
material.lightMapTiling
material.lightMapVertexColor

scene.lightmapSizeMultiplier
scene.lightmapMaxResolution

**Comment by guycalledfrank** [comment]
What is model.resolution?

**Comment by guycalledfrank** [comment]
Added in https://github.com/playcanvas/engine/pull/615
