### ISSUE TITLE
`app.xr.input` `add` event does not fire in `pc.XRTYPE_AR` (`immersive-ar`) mode

### ISSUE THREAD

**Issue by josephrocca** [playcanvas/engine#6126]
### Description

Changing instances of `pc.XRTYPE_VR` to `pc.XRTYPE_AR` on this example: https://playcanvas.github.io/#/xr/vr-hands cause hands to no longer be detected.

### Steps to Reproduce

1. Visit https://playcanvas.github.io/#/xr/vr-hands
2. Ctrl+F for `XRTYPE_VR` (there are two instances)
3. Change them to `XRTYPE_AR` and click the reload button
4. Observe that the hands are no longer there - the `app.xr.input.on('add', ...)` handler does not fire.

**Comment by Maksims** [comment]
Thank you for report. This has been fixed recently in this PR: https://github.com/playcanvas/engine/pull/6069
It will be released to everyone with next engine release likely.

**Comment by josephrocca** [comment]
Nice, thanks!
