### ISSUE TITLE
pc.http.post does not correctly encode data for when form-encoding

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#614]
It's using deprecated function encode instead of encodeURIComponent. For example sending the key value pair: "email": "test+test@example.com" doesn't work correctly.

**Comment by void-ecs** [comment]
This should be very easy to fix, just replace ```escape``` with ```encodeURIComponent``` in ```http.js``` but still not yet, after 2 years. And we have to use ```unescape``` on our server side.

Is there any reason for not fixing this?

**Comment by willeastcott** [comment]
Oh wow, a great example of a bug report which got buried under more recent bug reports. Anyway, I've made an attempt at a fix - see #3847. However, my knowledge of HTTP requests and sending form data is minimal so hopefully my fix is correct!
