### ISSUE TITLE
1.69.0 Install error - Node 16.0

### ISSUE THREAD

**Issue by marklundin** [playcanvas/engine#6152]
There is an error in [v1.69.0](https://github.com/playcanvas/engine/releases/tag/v1.69.0) which prevents the engine being installed using various package managers such as yarn, pnpm or npm.

This has been reported [on the forum](https://forum.playcanvas.com/t/engine-release-v1-69-0/35174/7) but it is also affecting some CDN's

[ESM.sh v1.69.1](https://esm.sh/playcanvas@1.69.1) ❌
[ESM.sh v1.69.0](https://esm.sh/playcanvas@1.69.0) ❌
[ESM.sh v1.68.1](https://esm.sh/playcanvas@1.68.1) ✅ 

[Skypack v1.69.1](https://cdn.skypack.dev/playcanvas@v1.69.1) ✅ 
[Skypack v1.69.0](https://cdn.skypack.dev/playcanvas@v1.69.0) ❌
[Skypack v1.68.1](https://cdn.skypack.dev/playcanvas@v1.68.1) ✅ 

This seems to be 2 separate issues.  
- [x] No extras mjs files was included. https://github.com/playcanvas/engine/pull/6153
- [ ]  Versions of  Node  < 18 cannot resolve the circular dependancy at https://github.com/playcanvas/engine/blob/607e3a8e7fe621087c32b2b60b38e2c73b25365e/package.json#L108

**Update** - *added 1.69.1*

**Comment by marklundin** [comment]
It looks like `playcanvas-extras.mjs` is listed as an export, but the file is not included in the build

https://github.com/playcanvas/engine/blob/607e3a8e7fe621087c32b2b60b38e2c73b25365e/package.json#L29

https://github.com/playcanvas/engine/blob/607e3a8e7fe621087c32b2b60b38e2c73b25365e/package.json#L85-L103

**Comment by marklundin** [comment]
Keeping this open, as it be also be related to https://github.com/playcanvas/engine/blob/607e3a8e7fe621087c32b2b60b38e2c73b25365e/package.json#L108

**Comment by Maksims** [comment]
We've had also issues installing 1.69.0, and it was a very obscured error.
1.68.2 - works great.

**Comment by LeXXik** [comment]
Worked for me using `yarn add playcanvas -D`:
```json
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "playcanvas": "^1.69.1"
  }
}
```

**Comment by marklundin** [comment]
Node v16 seems to have an issue resolving the circular dependancy at https://github.com/playcanvas/engine/blob/607e3a8e7fe621087c32b2b60b38e2c73b25365e/package.json#L108

**Comment by MAG-AdrianMeredith** [comment]
version v21.1.0 of node does not work.  From my experience having a circular dependency is always a bad idea, whatever it is for could there be a better way?  The issue I see is not that it can't find it, its also that its stuck in a infinite loop, it tries to fetch playcanvas, then tries to fetch the playcanvas of the playcanvas etc

**Comment by marklundin** [comment]
Thanks @MAG-AdrianMeredith we're looking into it. Can you confirm what version of yarn you're using?

**Comment by willeastcott** [comment]
@marklundin This is now fixed, right?
