### ISSUE TITLE
StandardMaterial options to disable/override features

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#619]
There is a number of features that would be good to be able to disable for a material, this would allow scale down complexity of material down to basic without a need to write customChunks or play with material from the code.

`noLight` - ignores all scene light
`ignoreSkybox` - ignores scene skybox (IBL)
`gammaCorrection` - allows to override global gamma correction
`toneMapping` - allows to override global tone mapping
`exposure` - allows to override global exposure

**Comment by guycalledfrank** [comment]
Suggestion:

useLighting
useSkybox
useGammaTonemap

noFog -> useFog?

**Comment by guycalledfrank** [comment]
Added in https://github.com/playcanvas/engine/pull/621
