### ISSUE TITLE
Anim Blend Tree takes incorrect name

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6196]
Forum: https://forum.playcanvas.com/t/nested-blend-trees/35338
Repro: https://playcanvas.com/project/1202126/overview/nest-blend-trees

When Anim Blend Tree loops through children, it takes a parent's name, instead of a child's one.

![image](https://github.com/playcanvas/engine/assets/5677782/249a87c0-2317-429b-abaf-075d6c5569d8)

**Comment by mvaligursky** [comment]
Thanks for creating the issue @LeXXik 

I cloned the project here to preserve it in its current state: https://playcanvas.com/project/1202421/overview/nest-blend-trees-bug-fork
