### ISSUE TITLE
[RFC] Improve Audio API

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#62]
We currently don't expose much of the Audio API through the AudioManager, Channel, Sound interfaces.

This is a request for features that you would like to see added to the API. Please comment on this thread with your requirements.

**Comment by marquizzo** [comment]
I recommend adding a "seeking through media" functionality so the developer can jump to a specific time point in the audio. This would be very handy when working with sound effect sprites for game development.

For example:

    pc.AudioSource.currentTime = 6;
    pc.AudioSource.duration = 3.5;
    pc.AudioSource.play();

Would start playing the audio at the 6-second mark, and stop after 3.5 seconds of playback have elapsed.

An `onEnded` and `onLoop` event callback would also be very helpful.

**Comment by daredevildave** [comment]
New Sound Component and Sound API is awesome!
