### ISSUE TITLE
Add support for the XR emulator

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6210]
To improve the DX, it would be nice if we could add support for the XR emulator:

![image](https://github.com/playcanvas/engine/assets/5677782/8941a82c-b459-406b-b3c2-8441b7073706)

https://chromewebstore.google.com/detail/webxr-api-emulator/mjddjgeghkdijejnciaefnkjmkafnnje
https://github.com/MozillaReality/WebXR-emulator-extension

It looks like Three and Babylon are working out of the box, but I couldn't make PlayCanvas examples work.

**Comment by Maksims** [comment]
This emulator is outdated, we do recommend a way more up-to-date and improved version, [mentioned](https://developer.playcanvas.com/user-manual/xr/#testing-webxr-without-xr-device) in docs: https://chromewebstore.google.com/detail/immersive-web-emulator/cgffilbpcibhmcfbgggfhfolhkfbhmik
