### ISSUE TITLE
Camera non-default viewport size ignores camera clear color

### ISSUE THREAD

**Issue by MarlonLam** [playcanvas/engine#6231]
### Description
When changing the camera viewport from default (0, 0, 1, 1) to non-default values e.g. (0.01, 0, 1, 1), the camera's clear color is ignored.

### Test URL
Test project: https://playcanvas.com/editor/scene/1980662

### Screenshots
(0, 0, 1, 1):
![image](https://github.com/playcanvas/engine/assets/84392311/dc802bb0-4712-4b80-95d2-7b950333930c)

(0.01, 0, 1, 1):
![image](https://github.com/playcanvas/engine/assets/84392311/87b682e4-2bab-4710-af71-83a84990f478)

### Platform
Tested in Edge

### Steps to Reproduce

1. Set camera viewport size to something other than (0, 0, 1, 1)
2. Launch

### Additional Notes

From my own digging around, I found a property assignment for "clearColor":
https://github.com/playcanvas/engine/blob/4ab0aceb0a4440eebb854a6e24e07dcf02805d66/src/scene/renderer/render-pass-forward.js#L273-L280

But in "renderForwardLayer" function, the property read is "clearColors":
https://github.com/playcanvas/engine/blob/4ab0aceb0a4440eebb854a6e24e07dcf02805d66/src/scene/renderer/forward-renderer.js#L696-L701

**Comment by mvaligursky** [comment]
Thanks for this, easy to fix if you just point it out to us!
