### ISSUE TITLE
Particle system shows artifacts on iPhone 6 when autoPlay is false

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#627]
To repro, in Editor:

- Create new scene
- Add new particle system
- Uncheck autoplay
- Run on iPhone 6 in the launcher

You'll see this:

![slack for ios upload](https://cloud.githubusercontent.com/assets/697563/15866690/9fa995ee-2cd7-11e6-8dc0-0ca992c24b27.jpg)

Note the streaked particles. 

We need to discard particle system draw calls before playing and after fully stopping. That should fix the problem.

**Comment by guycalledfrank** [comment]
Fixed in https://github.com/playcanvas/engine/pull/629
