### ISSUE TITLE
Engine ESM split bundled and unbundled building

### ISSUE THREAD

**Issue by kpal81xd** [playcanvas/engine#6286]
Allow building and watching of the engine ESM bundled and unbundled as separate options (as well as both)

**Comment by GamesTocaBoca** [comment]
Splitting engine ECMAScript Modules (ESM) into bundled and unbundled versions is common in web development. Bundled ESM combines all modules into a single file for performance benefits and wider browser support. Unbundled ESM maintains modular structure for better organization and debugging, often used in large projects. Both approaches have their place depending on factors like project size and performance requirements.

**Comment by kpal81xd** [comment]
We already have both included in the npm package this issue it just for being able to build them independently
