### ISSUE TITLE
non-existent module path in package.json

### ISSUE THREAD

**Issue by gVguy** [playcanvas/engine#6292]
### Description

In package.json after installing the package, "module" & "exports.imports" fields lead to a non-existent path.
Which causes the error when bundling.
```
"build/playcanvas/src/index.js",
```
should probably be instead
```
"build/playcanvas.mjs",
```
<img width="662" alt="Screenshot 2024-04-26 at 13 51 22" src="https://github.com/playcanvas/engine/assets/88876408/31c1a131-5967-45ca-9e81-8a35f956b4d7">

### Steps to Reproduce

1. npm i playcanvas@latest
2. see node_modules/playcanvas/package.json

**Comment by kpal81xd** [comment]
That should include the unbundled versions not the bundled so they need to be added to the published build
