### ISSUE TITLE
ScriptType does not support class syntax

### ISSUE THREAD

**Issue by AlexAPPi** [playcanvas/engine#6316]
Script argument type conversion does not occur if both a property and a script attribute exist.

```javascript
    class TestFailVec3 extends pc.ScriptType {
        vec;
        initialize() {
            console.log(this.vec);
        }
    }
    pc.registerScript(TestFailVec3, 'TestFailVec3');
    TestFailVec3.attributes.add('vec', { type: 'vec3', default: [0, 100, 0] });
```

```javascript
    class TestOkVec3 extends pc.ScriptType {
        initialize() {
            console.log(this.vec);
        }
    }
    pc.registerScript(TestOkVec3, 'TestOkVec3');
    TestOkVec3.attributes.add('vec', { type: 'vec3', default: [0, 100, 0] });
 ```
 
 
![image](https://github.com/playcanvas/engine/assets/7705172/ed5252b3-1b17-4b3d-b9d5-b42eab85b9b6)

**Comment by AlexAPPi** [comment]
This also applies to other complex types: vec2, entity, ...

**Comment by marklundin** [comment]
Thanks @AlexAPPi, you've hit on an important point.

When an ES6 class members  is defined, it is non configurable. Currently ScriptAttribute attempts to redefine the member using `Object.defineProperty` which effectively becomes a no-op. This prevents the type conversion and attribute events from working.

```javascript
class Test { fail = 'should be overridden' }
Object.defineProperty(Test.prototype, 'fail',  { value: 100 });
test = new Test()
console.log(test.fail) // 'should be overridden'
```

I've created an [editor repro here](https://playcanvas.com/editor/scene/1991522)

For the time being, you'll need to avoid declaring attribute in the class body, or alternatively use the `var MyClass = pc.createScript` syntax. We plan on solving this limitation with the newer [ESM Scripts](https://github.com/playcanvas/editor/issues/1148)

**Comment by LeXXik** [comment]
At the moment, the issue can be very obscure, as it doesn't warn the developer. This can lead to bugs that are hard to debug. We should add a warning.

**Comment by marklundin** [comment]
Yep this is not ideal, but unfortunately I don't think this is possible to catch at run-time without instantiating the class first.  A solution is to prevent users using the class notation or declaring members in the class body. Neither are ideal
