### ISSUE TITLE
Improve Gaussian Splats performance

### ISSUE THREAD

**Issue by cognitiveplus** [playcanvas/engine#6344]
Recently Adobe researchers published a paper called [GS-LRM: Large Reconstruction Model for 3D Gaussian Splatting](https://sai-bi.github.io/project/gs-lrm/).

The page contains real-time demos featuring this viewer: [antimatter15](https://github.com/antimatter15) / [splat](https://github.com/antimatter15/splat).

What's interesting about it is that it produces solid 60fps on M1 Air even with advanced scenes, while the same PLY imported into PlayCanvas results in less FPS (with Device Pixel Ratio unchecked).

For example:
https://sai-bi.github.io/project/gs-lrm/viewer/index.html?is_object=false&url=https://huggingface.co/datasets/saibi/gs-lrm/resolve/main/scene_assets/002000_gaussians.ply
https://playcanv.as/index/7d0ab8f5 (https://playcanvas.com/project/1214533/)

From viewer description it looks like it's doing splat sorting on CPU in a separate worker thread on async basis:
> the final approach that i settled on is to run the sorting process on the CPU in a webworker, which happens a bit more slowly (at roughly 4fps whereas the main render is at 60fps), but that's fine because most of the time when you are moving around the z order doesn't actually change very fast (this results in momentary artifacts when jumping directly between different camera orientations on opposite sides).

I guess PC might introduce similar configuration for 3DGS, with selector in inspector allowing to choose a sorting algo.

**Comment by mvaligursky** [comment]
We're doing splat sorting on a separate thread, and that bit is pretty fast. - faster than 4fps for sure I think. 1M splats in about 4ms on M1 Max.
But we have other bottlenecks we're investigating currently.

**Comment by MAG-AdrianMeredith** [comment]
The sorting is definitely the slowest part in my experience, it causes a lot of hitching as the gpu upload locks rendering so the fps meter might be reporting a good fps but its dropping frames.  
Its still awesome though, especially for a first release

**Comment by mvaligursky** [comment]
related: https://github.com/playcanvas/engine/pull/6352

**Comment by willeastcott** [comment]
Closing this since it was addressed by https://github.com/playcanvas/engine/pull/6357

Released as part of v1.71.0:

https://github.com/playcanvas/engine/releases/tag/v1.71.0
