### ISSUE TITLE
Gizmo movement plane

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6346]
This is a feature request to add a fourth movement plane to gizmo, which is always orthogonal to camera's forward normal.

**Comment by mvaligursky** [comment]
Would you have some examples on how this is done elsewhere to clarify what is requested here? Is it a zoom control in a way?

**Comment by LeXXik** [comment]
Its just so much faster to move objects, especially with hotkeys. In Editor a similar operation is a bit tiring, trying to precisely click the arrows for every small movement. You get a fatigue super quickly.


https://github.com/playcanvas/engine/assets/5677782/3c6c389f-2503-4fc5-afb3-0f29e5118d42

**Comment by mvaligursky** [comment]
Nice, that looks awesome, thanks!

**Comment by kpal81xd** [comment]
Okay this might be the point where we shift the editor to use the new gizmo system
