### ISSUE TITLE
Playcanvas audio not working on chrome experimental 

### ISSUE THREAD

**Issue by mrLoganite** [playcanvas/engine#638]
No playcanvas games produce any audio in Chrome Experimental on the HTC Vive when many other applications including other tabs in the browser do.

Steps to reproduce problem. 

1) connect htc vive
2) start steamVR so that the vive is active 
3) open browser on chrome experimental and access any site with audio (youtube for example) and you will be able to hear the audio through headphones connected to the HTC vive audio jack.
4) open another tab to playcanvas and launch any playcanvas game and no audio will output to the HTC audio jack.

 normal chrome outputs playcanvas audio fine but the new chrome build does not , I thought I better give you the heads up.

**Comment by willeastcott** [comment]
This is because the experimental build of Chrome is based on Chromium, which doesn't support MP3 playback.
