### ISSUE TITLE
TypeError: e is not a constructor on loading glb model from ceisium

### ISSUE THREAD

**Issue by MAG-AdrianMeredith** [playcanvas/engine#6389]
### Description
The attached model throws an error when loaded into playcanvas.  It loads in other gltf renders (e.g. babylonjs).  It appears the code is doing something baffling trying to instanciate the string "Entity" not the Entity object itself.  I can't tell what specifically is unique about this model but thats likely not important.

actual:
![image](https://github.com/playcanvas/engine/assets/100127317/c422683a-e450-4779-b94e-1a3c04c7f2fb)

expected: 
![image](https://github.com/playcanvas/engine/assets/100127317/0a188aec-afff-400a-8df9-8b41558d8729)

### Steps to Reproduce

* got to https://playcanvas.com/viewer
* drag in the attached model
* error is thrown

[yotei.glb.zip](https://github.com/playcanvas/engine/files/15332495/yotei.glb.zip)

**Comment by MAG-AdrianMeredith** [comment]
Thanks guys as always,  I must admit the fix did give me a chuckle.  Someone was coding late at night when they wrote that ;)

**Comment by slimbuck** [comment]
Thanks so much for reporting the issue and adding a simple with repro - makes all the difference <3 <3
