### ISSUE TITLE
More optimal rendering of VR cameras

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#641]
Check out this article (posted by @edankwan in the WebVR Slack channel):

http://www.iquilezles.org/www/articles/stereo/stereo.htm

Obviously, we can't do geometry shaders in WebGL buuuuuut...

Perhaps we could create a dedicated code path in the pc.ForwardRenderer that takes into account you are rendering two extremely similar camera frusta.

**Comment by Maksims** [comment]
Added in https://github.com/playcanvas/engine/commit/c399d85740d77c074c96e1abf40b9d690d2857e8
