### ISSUE TITLE
IntersectRay || IntersectsRay

### ISSUE THREAD

**Issue by RossLote** [playcanvas/engine#644]
Is there a good reason that a BoundingBox and a BoundingSphere have different method names for checking a ray intersection. Is it just a typo?

**Comment by willeastcott** [comment]
Neither function appears to be official API yet - they don't appear in the API reference manual. However, I believe both should be 'intersectsRay' (with s).

**Comment by Maksims** [comment]
Fixed in: https://github.com/playcanvas/engine/commit/6b330c5d84057447063309bc5e6859580067b778
