### ISSUE TITLE
VSM issues with Point Lights

### ISSUE THREAD

**Issue by redsparkzone** [playcanvas/engine#656]
Seems like VSM blurring doesn't work on points lights at all. And also some strange artifacts are present, see plane borders.

Test project:
https://playcanvas.com/editor/scene/442476

![image](https://cloud.githubusercontent.com/assets/5297578/16544725/48d5b1f2-4119-11e6-944b-f5cb0041e005.png)

Windows 10, latest Chrome, Iris Pro 5200

**Comment by guycalledfrank** [comment]
Hi. VSM is not supported for point lights yet (but it's planned... stay tuned). The fact that you could enable it for point light is actually a bug, which is fixed https://github.com/playcanvas/engine/pull/660
