### ISSUE TITLE
Why is there no Chinese documentation?

### ISSUE THREAD

**Issue by StevenMty** [playcanvas/engine#6633]
我迫切需要中文文档，请恢复中文文档链接，谢谢！

**Comment by kungfooman** [comment]
Are you talking about the Zhōngwén README?

It's here: https://github.com/playcanvas/engine/blob/main/README-zh.md

**Comment by StevenMty** [comment]
> 您说的是中文 README 吗？
> 
> 它在这里：https://github.com/playcanvas/engine/blob/main/README-zh.md

Think's，But I mean is the user manual and API document

**Comment by willeastcott** [comment]
I'm going to close this since we don't have any plans to provide Chinese translations of the API reference manual in the near future. If the community would like to contribute and maintain this, great. But the core team has no expertise in translating into Chinese.
