### ISSUE TITLE
Import URL resolution

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6638]
There is some issue with resolving relative paths in module scripts.

Minimum repro app:
[app.zip](https://github.com/playcanvas/engine/files/15467901/app.zip)

```
npm install
node app.mjs
```
```
localhost:3000/printer/
```

![image](https://github.com/playcanvas/engine/assets/5677782/7c05cd91-1c17-4fa5-b520-e67be6a877ce)

**Comment by marklundin** [comment]
Thanks for flagging this @LeXXik. So on export the paths in import statements are normalized which won't work if the app is above the root. I'll update this so that import paths are relative to the importing module, which should fix this.

**Comment by yohami** [comment]
Any progress on this one? @marklundin

**Comment by marklundin** [comment]
We have a patch for this on both the engine and editor side. I'll let you know as soon as it's out

**Comment by yohami** [comment]
Awesome

**Comment by marklundin** [comment]
This has been fixed and deployed now

**Comment by yohami** [comment]
Thanks, I just made a build and the root issue seems to be resolved, there's a new error now

https://nowwa.io/toy/65c1daec34d8b9198d1fc77b/Web/

![image](https://github.com/playcanvas/engine/assets/12057409/3360d348-72e8-4fd8-a814-6ca4e97b9417)

Script seems to be unrecognized at the time of import

![image](https://github.com/playcanvas/engine/assets/12057409/7d7f2dcd-24e0-4758-9cd8-abe8310c7663)

@LeXXik will probably chime in

**Comment by yohami** [comment]
Update, it's happening on the IDE as well

**Comment by yohami** [comment]
Ignore it, this was on our side :-)

**Comment by marklundin** [comment]
Yep `Script` was reverted in https://github.com/playcanvas/engine/pull/6355, so use ScriptType for now. It will replaced with a new Script class when [this](https://github.com/playcanvas/engine/pull/6367) lands

**Comment by yohami** [comment]
Yep it works now, thanks a lot!
