### ISSUE TITLE
Allow frustum point test to consume vector components

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6651]
At the moment frustum only accepts a vector for point test:

https://github.com/playcanvas/engine/blob/55a3ff8845f0cf30829aeec515f24ac98b6baf4d/src/core/shape/frustum.js#L128

This is a feature request to allow supplying vector component scalars as well. Similar to graph node's `setPosition`.

**Comment by mvaligursky** [comment]
To be honest, I'm not super keen on overloading function signatures this way.

**Comment by LeXXik** [comment]
Is there a better way avoiding a new vector allocation? Speaking of which I also don't really like such overloads. In our custom components we use different methods for vectors and scalars.

**Comment by mvaligursky** [comment]
for most people, the performance impact of creating a Vec3 here is small. For people that care more, they can create a global Vec3 and use it for this purpose.
