### ISSUE TITLE
HIde undocumented setters and getters from public API

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#6652]
It seems those are currently visible as public API. Example in the CameraComponent:

https://api.playcanvas.com/classes/Engine.CameraComponent.html#renderSceneColorMap

check the code it links .. there is no JSDocs block, but it's still exposed as public on the docs.

![Screenshot 2024-06-03 at 15 39 57](https://github.com/playcanvas/engine/assets/59932779/3e724672-bc86-4bfe-9646-9f281be51437)

**Comment by LeXXik** [comment]
Should they go under Private or be completely hidden?
![image](https://github.com/playcanvas/engine/assets/5677782/80ed3535-ce77-4a60-bcc6-deb4d5226f85)

**Comment by mvaligursky** [comment]
yep, they should be under private. The question is why are they public.

**Comment by willeastcott** [comment]
I believe it's because of this:

https://github.com/playcanvas/api-reference/blob/main/typedoc.json#L26-L28

**Comment by LeXXik** [comment]
Pretty sure if you remove the docs from the property and add to accessor with private tag, it should do it. Let me try.

**Comment by LeXXik** [comment]
Something like this, perhaps?

**Comment by willeastcott** [comment]
@LeXXik I believe I have now addressed this in #6685. Check it out. 😄
