### ISSUE TITLE
3D Gaussian Splats not working

### ISSUE THREAD

**Issue by Equilento** [playcanvas/engine#6668]
Gaussian Splats don't seem to work anymore. They are invisible and when launched this is the error.
Tested in Blank Project, Model Viewer, VR kit, WebXR AR Starter Kit. 
It does work in WebXR AR Starter Kit.

```
Failed to compile fragment shader:

ERROR: 0:181: 'assign' : l-value required (can't modify an input "color")

176: if (A < -4.0) discard;
177: float B = exp(A) * color.a;
178:
179:
180:
181: color.rgb = gammaCorrectOutput(toneMap(decodeGamma(color.rgb)));
182:
183: return vec4(color.rgb, B);
184: }
185:
186: void main(void)
while rendering Pass:RenderPassForward | Camera: Camera, Layer: World(TRANSP) | Node: HNK1.compressed, Material: compressedSplatMaterial

[object Object]
Provide as much information as possible. Include (where applicable):
```

Tested on Google Chrome and Brave.

**Comment by slimbuck** [comment]
Oops, we should have noticed this error, thanks so much for reporting.

The issue is a shader generation error when tonemapping is enabled. Fix is coming!
