### ISSUE TITLE
WebGL: Failed to link shader program

### ISSUE THREAD

**Issue by erikdubbelboer** [playcanvas/engine#6678]
This error is affecting roughly 8% of the users of https://poki.com/en/preview/94176748-9ef8-42c9-a44e-a95b70ec5680/da472bf8-04fa-4660-a885-2c2b6b783dda

Affects **only desktop** Chrome based browsers. Versions up to and including Chrome 114. But **none after** that, so it might have been a bug in the WebGPU implementation of Chrome.

I'm afraid the Poki error capturing doesn't capture any more details at the moment. Any specific details that could be useful can be added to this system if you have any suggestions.

```
console.error: ["Failed to link shader program. Error: C:\\fakepath(264,12-41): error X3013: 'tex2Dgrad': no matching 2 parameter intrinsic function
C:\\fakepath(264,12-41): error X3013: Possible intrinsic functions are:
C:\\fakepath(264,12-41): error X3013: tex2Dgrad(sampler2D, float2|half2|min10float2|min16float2, float2|half2|min10float2|min16float2, float2|half2|min10float2|min16float2)

Warning: D3D shader compilation failed with default flags. (ps_3_0)
 Retrying with avoid flow control
C:\\fakepath(264,12-41): error X3013: 'tex2Dgrad': no matching 2 parameter intrinsic function
C:\\fakepath(264,12-41): error X3013: Possible intrinsic functions are:
C:\\fakepath(264,12-41): error X3013: tex2Dgrad(sampler2D, float2|half2|min10float2|min16float2, float2|half2|min10float2|min16float2, float2|half2|min10float2|min16float2)

Warning: D3D shader compilation failed with avoid flow control flags. (ps_3_0)
 Retrying with prefer flow control
C:\\fakepath(264,12-41): error X3013: 'tex2Dgrad': no matching 2 par...
```

**Comment by mvaligursky** [comment]
I agree with you that this seems fixed.
Our code base does not even have a single use of `tex2Dgrad` currently, so there is not much we can do here to avoid this on the older browsers, this seems some internal isssue perhaps.

Thanks for all the reports @erikdubbelboer
