### ISSUE TITLE
Compressed gsplat loads very slowly when the asset is created by scripting

### ISSUE THREAD

**Issue by ludovit-as** [playcanvas/engine#6699]
With the new version, loading gaussian splats with a script, as in the linked project has become much slower and sometimes even crashes the browser (more likely to crash at higher resolutions, and also when more of the splat is visible in the first frame).

If the splat is barely visible on the first frame, the problem goes away. This can be demonstrated by enabling the `offsetFirst` attribute on the linked project.

Project to reproduce: https://playcanvas.com/project/1228429/
Related forum post: https://forum.playcanvas.com/t/gsplat-loads-very-slowly-and-sometimes-crashes-after-udpate/36049

**Comment by slimbuck** [comment]
I think the first frame is rendering all particles at the same place large on screen and this takes too long, causing the browser to kill the tab. Will continue investigating.

**Comment by slimbuck** [comment]
A fix for this was released yesterday in [Engine v1.71.6](https://github.com/playcanvas/engine/releases/tag/v1.71.6).

You can test it in the editor if you enable "Use Release Candidate" in Launch settings.

**Comment by ludovit-as** [comment]
It works as expected now. Thank you very much for the quick and effective fix!
