### ISSUE TITLE
Store light / material / ambient / fog colors always in linear space

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#6709]
Based on the `Scene.gammaCorrection`, we store those colors either in gamma (this is the default), or linear space (when gamma is disabled). This causes two problems:
- when gammaCorrection changes, the scene looks visually different, as the shader math is the same, but its input colors uniforms are different. So when we switch to HDR, the scene is too bright.
- we cannot correctly handle multiple cameras, one using sRGB and one linear, as colors are adjusted based on a global gamma setting.

Suggestion:
- always store these colors in linear only (as is the default behaviour currently)
- Scene.gammaCorrection should only affect the way pixels are written to render target, not encoding of inputs

I would expect no impact to majority or maybe even all users, as our HDR rendering path was hardly functional till now.

some of the relevant code:

https://github.com/playcanvas/engine/blob/5a6ff8668e0c0f3deb56ce89d4897b523b020abd/src/scene/materials/standard-material.js#L1101-L1109

https://github.com/playcanvas/engine/blob/5a6ff8668e0c0f3deb56ce89d4897b523b020abd/src/scene/renderer/forward-renderer.js#L150-L154

https://github.com/playcanvas/engine/blob/5a6ff8668e0c0f3deb56ce89d4897b523b020abd/src/scene/renderer/forward-renderer.js#L231

https://github.com/playcanvas/engine/blob/5a6ff8668e0c0f3deb56ce89d4897b523b020abd/src/scene/renderer/forward-renderer.js#L780-L784

**Comment by MAG-AdrianMeredith** [comment]
This sounds like it would explain a lot, as someone who mostly runs playcanvas in hdr mode we've struggled a while with consistency over the two modes (e.g. gsplats are very different right now).  I'll be sure to give the PR a test if and when there is one

**Comment by mvaligursky** [comment]
> This sounds like it would explain a lot, as someone who mostly runs playcanvas in hdr mode we've struggled a while with consistency over the two modes (e.g. gsplats are very different right now). I'll be sure to give the PR a test if and when there is one

yep, there will be a PR today / tomorrow for this.
