### ISSUE TITLE
An assert in the engine example related to sorted components

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#6717]
in the example folder run `npm run develop` and load the ReflectionBox example. This is what you get:

<img width="550" alt="Screenshot 2024-06-19 at 09 39 28" src="https://github.com/playcanvas/engine/assets/59932779/f12e59a2-3a4d-4498-aca0-ae8ec235b7f0">

**Comment by mvaligursky** [comment]
@LeXXik

**Comment by mvaligursky** [comment]
also the Physics -> Vehicle example.

**Comment by LeXXik** [comment]
Looks like we can't use a shared array as a temp store.

**Comment by mvaligursky** [comment]
> Looks like we can't use a shared array as a temp store.

Yep, I had a feeling this might be the case, so asked to add the assert. :(

**Comment by LeXXik** [comment]
I'm afraid the issue is not with the clearing of the array. The use case is: on enable, an entity A is adding another entity B into hierarchy via a script. So, while we are going through entity B components, the shared array contains the components of A, which we haven't finished looping through.

**Comment by LeXXik** [comment]
The only options I see:
1. Change back to the original design with an array per entity instance.
2. Allocate a new array in the getter on hierarchy state change.

Any other ideas?

**Comment by mvaligursky** [comment]
It's all isolated inside the Entity module.
Instead of a single temp array, we can have a pool of them, and return them back when no longer needed.

**Comment by mvaligursky** [comment]
```
const pool = [];

const getTempArray = () => {
	return pool.pop() ?? new Array();
}

const releaseTempArray = (a) => {
	pool.push(a);
}
```
