### ISSUE TITLE
Engine-only example crash

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6724]
Originally reported in #6723 

Needs an investigation, if the error is caused by something else.

Repro:

- open Vehicle example
- click the code refresh button

![image](https://github.com/playcanvas/engine/assets/5677782/ba2c3f2a-5eb6-4311-88fa-a456d17ab040)

**Comment by kungfooman** [comment]
Funny, did a bunch of tests and this is what happened so far:

1) It either just works
2) Same bug as you have
3) Tires go crazy (either stuck in each other or stuck in ground):

![image](https://github.com/playcanvas/engine/assets/5236548/468f1bc3-8465-492b-b893-c50b5f928acb)

**Comment by kungfooman** [comment]
I'm in the process of adding steering wheel support to the Vehicle script in an RTI session and stumbled over this again after some dozen reloads:

![image](https://github.com/user-attachments/assets/d262d886-f1b7-42fe-ac5a-7ff822934a92)

(if someone wants to add conditional breakpoints for debugging)

**Comment by kungfooman** [comment]
Investigating a bit more, I hope I found the main problem, still testing:

In the ammo wasm at `0x01FE20` you can use this conditional breakpoint: `stack[0].value === 0 || stack[1].value === 0 || stack[2].value === 0`. This will trigger whenever this happens for some debugging directly at that place.

With more RTI debugging I figured that the first occurance of `NaN` happens here:

![image](https://github.com/user-attachments/assets/49afa7b0-d853-4014-bcd5-942a610f33c0)

And this gave me an idea for a solution which seems to fix this, but I have to test a bit more... basically this contains the problem:

```
    // Add wheels to the vehicle
    var wheelAxle = new Ammo.btVector3(-1, 0, 0);
    var wheelDirection = new Ammo.btVector3(0, -1, 0);
    var connectionPoint = new Ammo.btVector3(0, 0, 0);

    this.wheels.forEach(function (wheelEntity) {
        var wheelScript = wheelEntity.script.vehicleWheel;

        var frictionSlip = wheelScript.frictionSlip;
        var isFront = wheelScript.isFront;
        var radius = wheelScript.radius;
        var rollInfluence = wheelScript.rollInfluence;
        var suspensionCompression = wheelScript.suspensionCompression;
        var suspensionDamping = wheelScript.suspensionDamping;
        var suspensionRestLength = wheelScript.suspensionRestLength;
        var suspensionStiffness = wheelScript.suspensionStiffness;

        var wheelPos = wheelEntity.getLocalPosition();
        connectionPoint.setValue(wheelPos.x, wheelPos.y, wheelPos.z);
        var wheelInfo = vehicle.addWheel(connectionPoint, wheelDirection, wheelAxle, suspensionRestLength, radius, tuning, isFront);

        wheelInfo.set_m_suspensionStiffness(suspensionStiffness);
        wheelInfo.set_m_wheelsDampingRelaxation(suspensionDamping);
        wheelInfo.set_m_wheelsDampingCompression(suspensionCompression);
        wheelInfo.set_m_frictionSlip(frictionSlip);
        wheelInfo.set_m_rollInfluence(rollInfluence);
    }, this);

    Ammo.destroy(wheelAxle);
    Ammo.destroy(wheelDirection);
    Ammo.destroy(connectionPoint);
```

We are `malloc`'ing these three Ammo vectors, put the *same* into four calls of `vehicle.addWheel` and then free them while they are still linked into the vehicle. So based on malloc randomness the values get overwritten with something else, causing both the `NaN` issue and `null function or function signature mismatch`.

Possible solution?

Free those vectors later and don't reuse them for each wheel.

**Comment by LeXXik** [comment]
Great investigation! Looks like you are correct. Those vectors are stored as reference, and not get copied to each wheel:

https://github.com/bulletphysics/bullet3/blob/e9c461b0ace140d5c73972760781d94b7b5eee53/src/BulletDynamics/Vehicle/btRaycastVehicle.cpp#L59-L65

**Comment by kungfooman** [comment]
Nice, thank you for the quick check in actual source!

So I guess we could just make an array, add these three vectors for each wheel and just `toFree.forEach(Ammo.destroy)` or something (at the place where we destroy the vehicle aswell). Would you like to work the details out for a PR?

**Comment by LeXXik** [comment]
Ah, right, it has the operator overload. Hmm.

**Comment by kungfooman** [comment]
Just printed the vectors:

![image](https://github.com/user-attachments/assets/dee86562-13e2-4db7-a96e-4caa6e9bd7e8)

Via:

```js
    // Add wheels to the vehicle
    var wheelAxle = new Ammo.btVector3(-1, 0, 0);
    var wheelDirection = new Ammo.btVector3(0, -1, 0);
    var connectionPoint = new Ammo.btVector3(0, 0, 0);
    console.log('wheelAxle.kB', wheelAxle.kB);
    console.log('wheelDirection.kB', wheelDirection.kB);
    console.log('connectionPoint.kB', connectionPoint.kB);
```

And then testing the pointers from vehicle, which should be the same pointers, if not copied by value (aka only a pointer/reference copy):

![image](https://github.com/user-attachments/assets/3d9a5960-284c-4823-85db-e021da69e01b)

And they seem to be all independent... quite a strange mystery :ghost:

**Comment by LeXXik** [comment]
I've looked into it a bit. What I've noticed is that something doesn't get cleaned up in the Wasm on restart. The examples instantiate Ammo once and re-use the instance when the reset button is pressed. If you look at the very first object that the engine is creating on libraryLoad in rigidbody component system, the pointer should be the same no matter how many times you refresh browser - it is the first object (user created one). However, if you press the restart button, the pointer is different, indicating there is some dangling stuff from the previous run.

https://github.com/playcanvas/engine/blob/5be4181d68b6f19f5a269cf1bcef6802bb8c271d/src/framework/components/rigid-body/system.js#L381

If I hard reset Ammo by forcing it to initialize again, instead of re-using old instance, then the issue goes away. Refreshing browser or hitting reset button give the same result.

https://github.com/playcanvas/engine/blob/5be4181d68b6f19f5a269cf1bcef6802bb8c271d/src/core/wasm-module.js#L171-L183

```js
    static getInstance(moduleName, callback) {
        const module = Impl.getModule(moduleName);

        // if (module.instance) {
        //     callback(module.instance);
        // } else {
            module.callbacks.push(callback);
            module.initializing = false;
            if (module.config) {
                // config has been provided, kick off module initialize
                Impl.initialize(moduleName, module);
            }
        // }
    }
````

**Comment by LeXXik** [comment]
I think the proper fix would be to instantiate a new Ammo instance on reset, as the engine keeps creating new objects in the same Wasm instance, until we eventually run out of memory. I guess something gets referenced to an old object or something.

**Comment by kungfooman** [comment]
Doing a full Ammo instance reset just covers that we have memory leaks that may show up in other scenarios aswell? For example spawning/destroying many cars in a GTA style game. I would like a solution that goes to the root of the problem here :see_no_evil:

**Comment by LeXXik** [comment]
That should be fine. I mean creating multiple cars should be no issue here.

I think the problem comes from the fact that when we click reset button, the engine creates a duplicate dynamics world, dispatcher, overlapping pairs cache, etc. without destroying old ones, and something internally gets referred to either duplicate or old system. Clicking reset button would then create yet another set of those. If we don't destroy the old Wasm instance altogether, then we should clear the current instance before creating them again.

I think the fact that it doesn't crash if you don't destroy vectors is just a lucky circumstance.

**Comment by kungfooman** [comment]
> I think the problem comes from the fact that when we click reset button, the engine creates a duplicate dynamics world, dispatcher, overlapping pairs cache, etc. without destroying old ones, and something internally gets referred to either duplicate or old system.

They are created here:

https://github.com/playcanvas/engine/blob/e20814af54ad1e7d87e80a7e6904da073ddf2575/src/framework/components/rigid-body/system.js#L381-L385

And deleted here on refresh:

https://github.com/playcanvas/engine/blob/e20814af54ad1e7d87e80a7e6904da073ddf2575/src/framework/components/rigid-body/system.js#L1037-L1055

Since we call `this._app.destroy(); ` for a refresh which then snowballs to everything else:

https://github.com/playcanvas/engine/blob/e20814af54ad1e7d87e80a7e6904da073ddf2575/examples/iframe/loader.mjs#L207-L214

But memory leaks seem obvious here:

https://github.com/playcanvas/engine/blob/e20814af54ad1e7d87e80a7e6904da073ddf2575/src/framework/components/collision/trigger.js#L28-L30

https://github.com/playcanvas/engine/blob/e20814af54ad1e7d87e80a7e6904da073ddf2575/src/framework/components/rigid-body/component.js#L179-L187

https://github.com/playcanvas/engine/blob/e20814af54ad1e7d87e80a7e6904da073ddf2575/src/framework/components/rigid-body/system.js#L395-L396

For starters... at least I don't see any corresponding `Ammo.destroy` for these.

My gut feeling is we reuse old pointers from e.g. those and that corrupts the memory state - we just have to make sure we free properly what we allocate and the errors should just disappear.

**Comment by kungfooman** [comment]
So I rewrote literally every `new Ammo.btWhatever` and every `Ammo.destroy` to meticulously keep track of every Ammo object:

**src/framework/components/ammo.js**:

```js
const trackedObjects = [];
let createCount = 0;
let deleteCount = 0;
function ammoTrack(object) {
  trackedObjects.push(object);
  object.deleteCount = 0;
  object.stack = new Error().stack; // Track *where* it was created
  createCount++;
  return object;
}
function ammoPurge() {
  for (const o of trackedObjects) {
    if (o.deleteCount === 0) {
      console.log("Purge", o);
      ammoDestroy(o);
    }
  }
}
function ammoOverview() {
  let a = 0;
  let b = 0;
  for (const o of trackedObjects) {
    if (o.deleteCount === 0) {
      a++;
    } else {
      b++;
    }
  }
  console.log(`ammoOverview notDeleted=${a} deleted=${b} createCount=${createCount} deleteCount=${deleteCount}`);
}
function ammoDestroy(o) {
  deleteCount++;
  o.deleteCount++;
  if (o.deleteCount > 1) {
    // Should be deleted only once...
    debugger;
  }
  try {
    Ammo.destroy(o);
  } catch (e) {
    console.warn("ammoDestroy> whatever");
  }
}
export {ammoTrack, ammoPurge, ammoOverview, ammoDestroy, trackedObjects};

```

After a refresh I call `pc.ammoOverview()` and every refresh added 64 Ammo objects that were never destroyed (`o.destroyCount === 0`). Okay, but which? Easy to look into the logged stack for each object:

![image](https://github.com/user-attachments/assets/91cb0cf9-e073-46b8-82e3-3d53142d5f4a)

Clear thing, rigidbody objects aren't freed.

Remember that 10x5 wall in the Vehicle example? Those get never freed it seems.

Usually I can refresh the example 9x.

If I turn the 10x5 wall into a 20x5 wall I can refresh 7x.
If I turn the 10x5 wall into a 30x5 wall I can refresh 2x.
If I turn the 10x5 wall into a 40x5 wall I can refresh 1x.

I counted 64 unfreed objects, but the wall in itself is of course only 50 rigid bodies... but that's a start that should be fixed.

**Comment by willeastcott** [comment]
This is great detective work. I'm guessing the rigid bodies are not destroyed because the hierarchy is never explicitly destroyed? If it _was_ explicitly destroyed, the components wouldn't be removed from all entities, and when a `RigidBodyComponent` is removed from an entity, the Ammo body _is_ destroyed.
