### ISSUE TITLE
Using the vertex bus and index bus for meshes.

### ISSUE THREAD

**Issue by AlexAPPi** [playcanvas/engine#6748]
When writing a terrain system, I need to reuse buffers, it would be nice to implement this for the mesh API.

```
const maxNumIndex = 123;
const indexArray = new Uint32Array(maxNumIndex);

....
const indexBufferOptions = undefined; // TODO for webgpu support
const indexBuffer  = new pc.IndexBuffer(
    app.graphicsDevice,
    pc.INDEXFORMAT_UINT32,
    indexArray.length,
    pc.BUFFER_STATIC,
    indexArray,
    indexBufferOptions
);

const mesh = new pc.Mesh(app.graphicsDevice);
mesh.indexBuffer[0] = indexBuffer;

....

mesh.setIndices(indexArray, 10); // <- here i use 1 buffer
mesh.update(pc.PRIMITIVE_TRIANGLES, false);
```

https://github.com/playcanvas/engine/blob/57cbfd450f300238969d580d1a2912eb9b71975a/src/scene/mesh.js#L1021
https://github.com/playcanvas/engine/blob/57cbfd450f300238969d580d1a2912eb9b71975a/src/platform/graphics/index-buffer.js#L196

* A similar situation with vertices

**Comment by mvaligursky** [comment]
Hi @AlexAPPi  .. could please provide more details of what you're trying to do? I'm not sure I understand this issue.

**Comment by AlexAPPi** [comment]
> Hi @AlexAPPi .. could please provide more details of what you're trying to do? I'm not sure I understand this issue.

Hi! I use the same buffer for the model, and modify it, every time it is unloaded to the GPU, the engine makes a copy of the same buffer, although there is no point in doing this, because this is the same buffer.

**Comment by mvaligursky** [comment]
The Mesh has two possible ways to use it, see here: https://api.playcanvas.com/classes/Engine.Mesh.html
- a simple way - see example at that link
- a more manual way of using Vertex and Index buffer directly

What you can do is to create Vertex and Index buffer yourself and upload data to them as needed. In this case, you would not use `mesh.setIndices()` and `mesh.update()`, but manage buffers yourself.

I'll close this as I believe this is what you need, but please re-open if I missed something.
