### ISSUE TITLE
USDZ export - error when exporting a model with compressed textures

### ISSUE THREAD

**Issue by MAG-ThomasGreenhalgh** [playcanvas/engine#6798]
### Description

I'm seeing an error when I try to export a model with compressed textures to USDZ with the `UsdzExporter`:

![export-error](https://github.com/playcanvas/engine/assets/111896829/b643afe3-9e65-4738-910b-3573862d7e22)

![export-error-breakpoint](https://github.com/playcanvas/engine/assets/111896829/21128642-b60d-4dbe-981f-336cdf4f1060)

### Steps to Reproduce

After loading a model with compressed textures (using the Basis WASM module), running the following on the created entity will result in the error:

![image](https://github.com/playcanvas/engine/assets/111896829/4691845a-4476-4826-b1e3-290c71ccb8a8)

**Comment by mvaligursky** [comment]
I cannot reproduce this. I added a model with basis texture to https://playcanvas.vercel.app/#/loaders/usdz-export

Basically these bits:

<img width="984" alt="Screenshot 2024-09-02 at 16 31 37" src="https://github.com/user-attachments/assets/e8df13df-e931-4f5e-b547-fe0ab7a63fdd">

This is the mesh I see in that example when reloaded, using a basis texture:
![Screenshot 2024-09-02 at 16 32 18](https://github.com/user-attachments/assets/c056283f-5199-4caf-9c69-26ec32bd4fbb)

and this is what I see in usdz viewer in my mac:
<img width="936" alt="Screenshot 2024-09-02 at 16 32 27" src="https://github.com/user-attachments/assets/e0441d54-a5e5-4332-9ee3-b15ebfb3f3c3">

Is it possible you have not loaded basis wasm files?

I'll close as this seems to work.
