### ISSUE TITLE
Array util function is buggy

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#6813]
I just saw that @willeastcott removed the set util file in https://github.com/playcanvas/engine/commit/f12ab342763ce9a077cf2e0bbe77e3a1018383c1 and took a look at the array one:

https://github.com/playcanvas/engine/blob/main/src/core/array-utils.js

Test code:

```js
function equals(arr1, arr2) {

        if (arr1.size !== arr2.size) {
            return false;
        }
        for (let i = 0; i < arr1.length; i++) {
            if (arr1[i] !== arr2[i]) {
                return false;
            }
        }
        return true;
    }
equals([1, 2], [1, 2, 3]); // Outputs: true
```

It's clearly wrong, since it needs to access `length`.

**Comment by mvaligursky** [comment]
yeah what is that `.size` doing there!

**Comment by mvaligursky** [comment]
Luckily it only gets used on an equal sized arrays .. so this has no impact. But much appreciated you finding this out!

**Comment by kungfooman** [comment]
> yeah what is that `.size` doing there! What was I thinking! :)

Lets blame the ES people for introducing different nomenclature just to confuse everyone :sweat_smile:
