### ISSUE TITLE
Entity.addChild() slows dramatically when there are lots of entities

### ISSUE THREAD

**Issue by growf** [playcanvas/engine#685]
Entity.addChild() performs a tree-search starting from the root to check if a new child has already been added:
```
var root = this.root;
var dupe = root.findOne("getGuid", child._guid);
if (dupe) {
    throw new Error("GUID already exists in graph");
}
```
This is bad because, in the normal scheme of things, the new child _won't_ exist and that tree-search will visit every single node. As the number of entities increases adding new entities becomes slower and slower.

Instead there ought to be an object at the root whose keys represent all GUIDs in the tree allowing this duplication check to be performed as a simple test for existence in that object.

**Comment by vkalpias** [comment]
Removed that check in https://github.com/playcanvas/engine/commit/0ece70b3a9b1021f417116f38698430bacd80e48 because the test that already checks if a child is already parented when `addChild` or `insertChild` are called should be enough.
