### ISSUE TITLE
AnimComponentLayer.getAnimationAsset does not return expected Asset type

### ISSUE THREAD

**Issue by Mintytorus** [playcanvas/engine#6859]
### Description

The documentation for [AnimComponentLayer.getAnimationAsset](https://api.playcanvas.com/classes/Engine.AnimComponentLayer.html#getAnimationAsset) says it returns the animation asset (i.e. a `pc.Asset` instance). In practice it returns an object of the type: `{asset: number | null}` (with the number being the asset id)

Example project (this also reproduces a template issue that I'll be filing too - in this case I'm mostly concerned with the left entity)
https://playcanvas.com/project/1240526 [published build](https://playcanv.as/p/lwjjMcp5/)

### Steps to Reproduce

1. Create an entity with an animation graph + default layer and state
2. Wire up render asset + animation for the default state
3. Get the layer from the `entity.anim` component in script
4. Call `layer.getAnimationAsset` for the default state name

**Expected result (as per the documentation):** a `pc.Asset` instance
**Observed result:** an object with an "asset" field containing the asset id

**Comment by kpal81xd** [comment]
Okay having a look at the anim component the type on the documentation is incorrect it should be the expected type of `{asset: number | null}`

**Comment by willeastcott** [comment]
But is that consistent with the rest of the API? It is a bit misleading. If the function was `getAnimationAssetId`, it'd make more sense.

**Comment by kpal81xd** [comment]
Ignore I was looking at a diff function changing now 👍
