### ISSUE TITLE
Missing attributes after upgrade engine version to 2.0.0-alpha and use registerScript

### ISSUE THREAD

**Issue by StevenYAChen** [playcanvas/engine#6880]
### Description

example script class:
```
class MyClass extends pc.ScriptType {
  initialize() {
    console.log('MyClass this: ', this);
    this.myAttribute;
  }
}

pc.registerScript(MyClass, 'myClass');

MyClass.attributes.add('myAttribute', {
  type: 'string',
  default: '',
});
```

engine version 1.73.4:
<img width="1063" alt="regiterScriptBefore" src="https://github.com/user-attachments/assets/bf6dce43-afeb-4c8d-9e63-99e7156849ef">

engine version 2.0.0-alpha:
<img width="781" alt="regiterScriptAfter" src="https://github.com/user-attachments/assets/b8045dac-df95-4f4c-8aec-b648d5e66e7b">

this.__attributes of the script instance becomes undefined after upgrading engine version to 2.0.0-alpha

**Comment by marklundin** [comment]
Thanks @StevenYAChen. I've managed to replicate this. Fix incoming
