### ISSUE TITLE
Unable to load srgb compressed textures in playcanvas 2.0

### ISSUE THREAD

**Issue by MAG-AdrianMeredith** [playcanvas/engine#6904]
When attempting to load textures under the following types:

PIXELFORMAT_DXT1_SRGB
PIXELFORMAT_DXT3_SRGB
PIXELFORMAT_DXT5_SRGB

The incorrect extension **WEBGL_compressed_texture_s3tc** is used instead of **WEBGL_compressed_texture_s3tc_srgb** causing the formatType to return undefined and the texture to fail to load. replacing it with the above plus this change fixes the issue

![image](https://github.com/user-attachments/assets/215e0779-973f-412f-9806-1c9aed857bd3)

and 
![image](https://github.com/user-attachments/assets/40584a69-f0ff-47e2-9061-fad544dcbcee)

p.s. I signed the contributor agreement a while back but I don't have access to push branches and now that page is missing entirely otherwise I'd do the fix for you.

```
remote: Permission to playcanvas/engine.git denied to Adriaaaaan.
fatal: unable to access 'https://github.com/playcanvas/engine.git/': The requested URL returned error: 403
```

**Comment by mvaligursky** [comment]
@MAG-AdrianMeredith - thanks for the report, I'll have a look.
You need to fork the repo, and then create a PR merging from your repo to our repo.
