### ISSUE TITLE
Splat Scene  which is showed in editor or supersplat  is   different with other splat viewer

### ISSUE THREAD

**Issue by nmgyaoyuan** [playcanvas/engine#6921]
**Playcanvas  show :**

![playcanvas](https://github.com/user-attachments/assets/202657e5-8677-4489-ba09-0a2f496f7282)

**other viewer:**

![other](https://github.com/user-attachments/assets/0f626fb0-a046-4c42-8582-19d0211a3249)

**Comment by willeastcott** [comment]
In the PlayCanvas screenshot, you have a skybox set but in the other viewer, the background is black. You could remove the skybox in PlayCanvas (go to SETTINGS > RENDERING and remove the skybox). Then set your camera's clear color to black.

Other things to check:

1. The far clip value for your camera.
2. The tonemapping setting for your scene. For a scene with 3DGS, set it to Linear (again, in SETTINGS > RENDERING).

**Comment by nmgyaoyuan** [comment]
willeastcott, thanks!   the  issue is solved.    

 changed: (1) removed the skybox ;  (2) clear color to black ;  (3) far clip set  10000 ;  (4)  set to linear .  

the **main reason** is  the  view angle :)  

**unsuitable angle ：**
![changed-settings](https://github.com/user-attachments/assets/719a0436-95ee-4339-8245-9a8b038a5468)

------------------------------------------------------------------------------------------------------------------------
**suitable angle ：**

![suitable-angle](https://github.com/user-attachments/assets/333ca6ca-34fc-4b52-900d-ef97b1c52ca4)
