### ISSUE TITLE
Engine 2.0 graphics device crash

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#6930]
If `shader` property is undefined on webgl graphics device, the application will crash:

![image](https://github.com/user-attachments/assets/e49c521d-d4bd-4eba-9b66-cd5c4c4454c9)

![image](https://github.com/user-attachments/assets/5c9bd8d2-56d6-48e6-afdf-8215dab19144)

![image](https://github.com/user-attachments/assets/1a26ca97-c662-43ab-8025-c9a2c50b7859)

**Comment by LeXXik** [comment]
This is a showstopper for us. It looks like rest API now rejects a build, if the project has an asset with .mjs extension (even if we don't use any ESM script features), so we have to use 2.0 version. This now breaks all our games.

**Comment by LeXXik** [comment]
I will see if I can make a repro.

**Comment by mvaligursky** [comment]
mat.variants.get(hash) should never return undefined, but always a shader .. step in to that. What type is the material?

**Comment by mvaligursky** [comment]
This seems to be the user error. `material.shader` has been deprecated and needs to be updated, see here https://github.com/playcanvas/engine/pull/6831
