### ISSUE TITLE
Examples - slow loading (too many network requests 820!)

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#6935]
The current example loads every script as an individual network request, so the basic page takes 820!!! network requests! Even on the local network. Browsers do throttle many requests, as they can only process a limited number of concurrent requests, idling others. With higher latency cases, this leads to very slow loading, regardless of file sizes.

Moreover, the individual files are not hashed/tagged in URL, making them non-unique from a caching point of view, which forces the use of "soft-cache" (304), so even when a user has cached the page, it still will make requests to each file.

During local development, this is very noticeable as updating the engine or example in VSCode, and refreshing the page - take another 1.5 seconds to load.

Also, switching between examples - reloads everything, and making every request again and again.

A single engine file - will solve that issue.

**Comment by kpal81xd** [comment]
Switching from the unbundled to bundled version of the source should resolve this issue Ill work on a fix :+1

**Comment by kpal81xd** [comment]
So currently you can specify the the env flag `ENGINE_PATH` to load a custom engine build for development: `ENGINE_PATH=../build/playcanvas.mjs npm run develop`

**Comment by Maksims** [comment]
> Member

It probably should be a default.
Also the published examples, are loading all individual scripts: https://playcanvas.vercel.app/#/misc/hello-world

**Comment by kpal81xd** [comment]
> > Member
> 
> If that would be an option in npm scripts, and documented - that will be great! Also the published examples, are loading all individual scripts: https://playcanvas.vercel.app/#/misc/hello-world

Under the [readme](https://github.com/playcanvas/engine/tree/main/examples) there should be a section on local examples development explaining how you can use that ENV variable. 

As for the published examples yea they are using the unbundled engine currently but I can switch that back to the bundled one 👍

**Comment by mvaligursky** [comment]
I think the main reason `npm run local` uses unbundled version is that it allows changes on both examples and engine source code with just this command, no need to build the engine.
