### ISSUE TITLE
A static version of `new Vec3(0.5, 0.5, 0.5)`?

### ISSUE THREAD

**Issue by kungfooman** [playcanvas/engine#6936]
I've needed a `new Vec3(0.5, 0.5, 0.5)` multiple times and somehow it surprises me every time we don't have a static `Vec3` for that.

I'm not sure how it should be named, I did a quick GitHub code search and people call it all kinds of names:

 - [Center](https://github.com/Technici4n/Modern-Dynamics/blob/c3d58bdab24df0507d5194433c77af90052b79f4/src/main/java/dev/technici4n/moderndynamics/client/ber/PipeBlockEntityRenderer.java#L108)
 - [Grey](https://github.com/AlexBenton/Teaching/blob/0056b0c931032935f2675da82595f436c5f256d7/FGraphics1920/framework/src/main/java/com/bentonian/framework/mesh/primitive/Plane.java#L14)
 - [VEC_HALF](https://github.com/CalenXwX/BuildCraft/blob/da78ece9b8d04dcdad184d9e0145c08ceae3bd1f/common/buildcraft/lib/misc/VecUtil.java#L24)
 - [CENTER_OF_ORIGIN](https://github.com/Milkyway-Team/mw-core/blob/ea9cb1850cd4880ebf073bbfaf4b20def25d39c5/src/main/java/com/pouffy/mw_core/util/VecHelper.java#L25)

And variations thereof like `VEC_CENTER` or more specific terms like `defaultHalfExtents` etc.

In the context of PC I would like `Vec3.HALF` (simply the shortest and `center` sounds somehow relative).

Would this be feasible or considered API bloat?

**Comment by LeXXik** [comment]
+1
I like `Vec3,HALF`.

**Comment by Maksims** [comment]
Use of static vectors - are common for "resetting" a vector, but often devs have couple of temporary reusable vectors, and can do something like:
```js
vecA.add(vecB.set(0.5, 0.5, 0.5))
```

While it can be useful, at the same time if you don't know about even Vec3.ONE, dev might as well use `set` on the temporary vector.

**Comment by LeXXik** [comment]
I often use it with custom physics, e.g. for setting a default half extents, and other occasions, where you don't have temp vectors. Could look something like this.

```js
class A {
    _halfExtents = Vec3.HALF;

    set halfExtents(vec) {
        if (this._halfExtents === Vec3.HALF) {
            this._halfExtents = vec.clone();
        } else {
            this._halfExtents.copy(vec);
        }
    }
}
```

**Comment by LeXXik** [comment]
> ```js
> vecA.add(vecB.set(0.5, 0.5, 0.5))
> ```

I was thinking, why, when we have `vecA.addScalars(0.5, 0.5, 0.5)`, but then realized, its an extension in our framework. Can't live without it :)
