### ISSUE TITLE
[BUG] Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kketan707** [playcanvas/engine#6976]
### Description

Colliding two compound colliders with kinematics giving error  **Uncaught RangeError: Maximum call stack size exceeded**

I tried to simulate the issue
* Simulated project : [https://playcanvas.com/project/1256880/overview/test-call-stack-error](https://playcanvas.com/project/1256880/overview/test-call-stack-error)
* ![image](https://github.com/user-attachments/assets/8302a772-3882-4a2c-ad73-a3691b0885c0)

**Comment by LeXXik** [comment]
Needs to be verified against https://github.com/playcanvas/engine/commit/6f2f8cb985831e2c376aa3f6dac1178be0ec9fde

**Comment by mvaligursky** [comment]
I think it happens with that fix as well .. I created a preview engine release from main_v1 containing this fix, and this still fails: https://launch.playcanvas.com/2075251?debug=true&use_local_engine=https://code.playcanvas.com/playcanvas-preview.js
