### ISSUE TITLE
Fog issue (driver bug)

### ISSUE THREAD

**Issue by marionieto** [playcanvas/engine#700]
The fog was not working in a few devices.
Devices: 
- Moto E xt1021 Chrome
- Moto G Chrome
- LG G2 Chrome

Fog setup
Color: ff0000
Type: Linear
Start:18
End:80

**Comment by willeastcott** [comment]
I've tried to recreate the bug with this app:

http://playcanv.as/p/5MYLz99N/

Original project:

https://playcanvas.com/project/413360/overview/fog-bug

We don't have any of those devices in the office. We get:

Nexus 5X:
![image](https://cloud.githubusercontent.com/assets/697563/17211975/499a09b2-54c4-11e6-91fb-5e8a534c3693.png)

One Plus Two:
![image](https://cloud.githubusercontent.com/assets/697563/17211985/53c517c4-54c4-11e6-99b6-bc5be6cfbc94.png)

Samsung Galaxy Tab S:
![image](https://cloud.githubusercontent.com/assets/697563/17211992/5e1a2340-54c4-11e6-8aa8-9f6820938692.png)

Samsung Galaxy Alpha:
![image](https://cloud.githubusercontent.com/assets/697563/17211998/67d75cb8-54c4-11e6-8666-69916459209b.png)

Samsung Galaxy S6 Edge:
![screenshot_2016-07-28-11-57-07](https://cloud.githubusercontent.com/assets/697563/17212019/7bbad868-54c4-11e6-9046-0e5e9323d85f.png)

Can you verify that this app also exhibits the problem on the Motos/LG G2? Do you have Android devices that do not display the problem?

**Comment by marionieto** [comment]
I tested your example and it has the same issue.

Motorola Moto E xt1021 Chrome:
![motoext1021chrome](https://cloud.githubusercontent.com/assets/2238679/17212886/06b52d8c-54a8-11e6-976e-f1df3b37c39d.png)

LG G2 Chrome:
![lg_g2](https://cloud.githubusercontent.com/assets/2238679/17213081/1fe0b000-54a9-11e6-9f2f-1c0061b568a1.jpg)

**Comment by guycalledfrank** [comment]
Does the problem persist if you disable gamma correction (set to 1) and tonemapping (set to linear) in the scene settings?

**Comment by willeastcott** [comment]
Some extra info about device GPUs:

Moto E: Adreno 302
Moto G: Adreno 305
LG G2: Adreno 330

Notice a theme? ;)

**Comment by marionieto** [comment]
I did a new test with the suggestions of frank and it didn't work.
The setup of the new test: 
![image](https://cloud.githubusercontent.com/assets/2238679/17216247/44aa3958-54b6-11e6-91b8-77c10ac74b7e.png)

**Comment by willeastcott** [comment]
@guycalledfrank Maybe the way to debug/resolve this is to create a script that creates and assigns a minimal shader that implements fogging of a white color and pretty much nothing else. Then we can ask Mario to tweak the shader until we track down the offending line. Might take a few iterations, but could work. :/

**Comment by guycalledfrank** [comment]
marionieto, how does this project look on your phones?
https://playcanv.as/b/OzyzLJPu/

**Comment by marionieto** [comment]
@guycalledfrank I tested in a few devices and these are the results:

Apple iPhone 6 iOS 9.3.3 Safari:
![image](https://cloud.githubusercontent.com/assets/2238679/17251314/9d601d42-557e-11e6-8a9a-88969ed94512.png)
 
LG G2 android 4.4.2 Chrome 51.0.2704.81:
![image](https://cloud.githubusercontent.com/assets/2238679/17251007/49c3b42e-557d-11e6-9233-cfe544a67c48.png)

Motorola Moto E XT1021  Android 4.4.4 Chrome 52.0.2743.91:
![image](https://cloud.githubusercontent.com/assets/2238679/17251028/60bf6998-557d-11e6-8112-aaa8625acc81.png)

**Comment by guycalledfrank** [comment]
So it seems like these devices have some driver bug. @willeastcott just emailed some driver people about this problem. In case if fixing it would take too long for them, we can try to add a temporary workaround.

**Comment by Maksims** [comment]
Is this been addressed?

**Comment by willeastcott** [comment]
This is now very old so I'm going to close it since I suspect this problem has been fixed either by Chrome or Android updates. Plus, it's not a PlayCanvas bug but a driver bug.
