### ISSUE TITLE
glTF Exporter: Non-ASCII characters corrupted in exported data

### ISSUE THREAD

**Issue by yushimatenjin** [playcanvas/engine#7030]
## Description 

Hello,

I've encountered an issue while using the PlayCanvas glTF Exporter. 
It appears that the exporter is not functioning correctly when entity names, materials, or textures contain non-ASCII characters.

## Version 

- PlayCanvas Engine v2.1.0

## Steps to Reproduce

1. Here are the sample project and execution URLs:
- Project URL: https://playcanvas.com/editor/project/1265143
- Execution URL: https://playcanv.as/p/4xbkD82g/

2. Attempt to export the models using the glTF Exporter:
a. Model with English-only content
b. Model with Japanese characters in entity/material/texture names
c. Model with emoji in the entity name
3. Try to load the exported models in PlayCanvas Viewer and Blender

### 1. English Only 
- Entity name + texture + material name are in English.

![result001](https://github.com/user-attachments/assets/5b8ab0c0-71f6-4abf-b350-0c29d3e7dddd)

- This worked normally, and I could load it without issues in both the PlayCanvas Viewer and Blender.

### 2. Containing Japanese characters
- Entity name + texture + material name are in Japanese.

![result002](https://github.com/user-attachments/assets/8653da43-bbf3-4111-aa3a-678cb7eef54c)

 - The model can be viewed in the PlayCanvas Viewer but entity names appear corrupted, indicating that the export wasn't successful
 - I couldn't import the exported model data into Blender

### 3. Containing emojis

- Entity name includes an emoji.

![emoji003](https://github.com/user-attachments/assets/42050e56-3b4d-4178-be49-219fc2ea543e)

- This model couldn't be loaded even in the PlayCanvas model viewer.

Has anyone else experienced this problem or know of a workaround? Any assistance would be greatly appreciated.

Thank you for your help.

**Comment by willeastcott** [comment]
Thanks for the detailed bug report. It was very useful to resolving the problem! 🙏

**Comment by yushimatenjin** [comment]
Thank you so much for your quick response to this !!
