### ISSUE TITLE
Example 'Editor' does not fully function on WebGPU

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#7035]
This is the warning on WebGPU which needs to be addressed:
`pc.Picker#getSelection is not supported on WebGPU, use pc.Picker#getSelectionAsync instead.`

As a result, the object picking in the scene does not work.

**Comment by kpal81xd** [comment]
Does this issue still exist? I cannot replicate it @mvaligursky

**Comment by mvaligursky** [comment]
in WebGPU mode I cannot pick the objects: https://playcanvas.vercel.app/#/misc/editor
