### ISSUE TITLE
Example 'Compound Collision' no longer works correctly

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#7036]
repro: https://playcanvas.vercel.app/#/physics/compound-collision

Notice that the legs and backrest of the chair no longer colliders with the ground.

<img width="694" alt="Screenshot 2024-10-15 at 11 21 33" src="https://github.com/user-attachments/assets/8abb4583-b6f5-4ebe-a851-586a0c39cf37">

**Comment by willeastcott** [comment]
I suspect @LeXXik might know more.
