### ISSUE TITLE
Error to run examples after build

### ISSUE THREAD

**Issue by khoaho** [playcanvas/engine#707]
Hi,

I got the error when running any example in the examples folder:
playcanvas-latest.js:3898 Uncaught TypeError: Cannot set property 'stencil' of undefined

The error happens at `options.stencil = true;` at line 3898 of playcanvas-latest.js:

>   var GraphicsDevice = function(canvas, options) {
    this.gl = undefined;
    this.canvas = canvas;
    this.shader = null;
    this.indexBuffer = null;
    this.vertexBuffers = [];
    this.vbOffsets = [];
    this.precision = "highp";
    this._enableAutoInstancing = false;
    this.autoInstancingMaxObjects = 16384;
    this.attributesInvalidated = true;
    this.boundBuffer = null;
    this.instancedAttribs = {};
    this.enabledAttributes = {};
    this.textureUnits = [];
    this.commitFunction = {};
    this._maxPixelRatio = 1;
    this._width = 0;
    this._height = 0;
    this.updateClientRect();
    if (!window.WebGLRenderingContext) {
      throw new pc.UnsupportedBrowserError;
    }
    if (canvas) {
      options.stencil = true;
      this.gl = _createContext(canvas, options);
    }

Thank you.

**Comment by willeastcott** [comment]
@guycalledfrank has now fixed this so closing this issue...

**Comment by khoaho** [comment]
I confirm the issue was fixed. All examples are working now. Thank you.
