### ISSUE TITLE
Investigate using R8 format for CanvasFont instead of RGBA8

### ISSUE THREAD

**Issue by mvaligursky** [playcanvas/engine#7084]
- WebGL2 / WebGPU supports rendering to R8
- if the texture the CanvasFont uses is grayscale, R8 should be all that is needed

related forum thread: https://forum.playcanvas.com/t/msdf-font-canvasfont-textmesh-issues-supporting-japanese/38149

**Comment by MAG-AdrianMeredith** [comment]
The alternative I've used before is to "atlas" the font into each colour channel separately which has the same overall effect if you have lots of characters

**Comment by mvaligursky** [comment]
This cannot be done in general, as fonts contain colors.
Example here using emojis: https://playcanvas.com/project/702920/overview/canvas-font-example
And so in general case we need to keep sing RGBA8
