### ISSUE TITLE
Positional audio

### ISSUE THREAD

**Issue by LeXXik** [playcanvas/engine#7090]
The positional sound example has no positional audio. The audio should be played in left and right ears, corresponding to robot position compared to camera. At the moment the audio is normal, without 3D effect.

https://playcanvas.vercel.app/#/sound/positional

**Comment by mvaligursky** [comment]
agreed. Tested against example from main_v1 and the situation is the same there, which means broken for months now.

**Comment by LeXXik** [comment]
This might not be an engine issue. 

Checking the article here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics

There are some examples given, using three:
https://mdn.github.io/webaudio-examples/spatialization/
https://mdn.github.io/webaudio-examples/stereo-panner-node/

They don't seem to work either for me. Web Audio issue?

**Comment by LeXXik** [comment]
Linking https://github.com/WebAudio/web-audio-api/issues/2609

**Comment by liamdon** [comment]
Using Chrome on macOS, on the MDN boombox example: 
* I have correct stereo panning if I only move the boombox left and right. It seems like it's in a 2D mode.
* If I change the height (up and down), there is a noticeable switch into "spatial" mode. The sound is quieter but more obviously spatialized. Stereo panning continues to work, but now it sounds more natural/realistic.
* If I change the depth (in and out) or rotation, there is another switch. Now stereo is broken. If I bring the depth back to the default and move left and right, there is no stereo panning.

**Comment by LeXXik** [comment]
This seems to be fixed now in browser. The robot example could be improved to make the positional sound changing ears more prominent, but it is working atm. Closing.
