### ISSUE TITLE
RigidBody 'collisionend' handler does not get ContactResult but other entity

### ISSUE THREAD

**Issue by movAX13h** [playcanvas/engine#7108]
Documentation states that the 'collisionend' handler is passed a ContactResult object:
https://api.playcanvas.com/classes/Engine.RigidBodyComponent.html#EVENT_COLLISIONEND

But it is actually getting just the other entity:
https://github.com/playcanvas/engine/blob/00e2f0291447712fd41df4943f1f8ceddeab0980/src/framework/components/rigid-body/system.js#L787

'collisionstart' is correct.

Changing this will break projects using the passed object in the handler.

**Comment by LeXXik** [comment]
This is a documentation issue. When contact ends, it does not suppose to send contact data, like normal and world position. Only the entity.

**Comment by willeastcott** [comment]
Fixed and also cherry picked to `main_v1` also.
