### ISSUE TITLE
Baking light type change have some shadowmap caching issues.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#713]
There are some bugs with shadow maps being cached or similar when using baking lights and changing light types. This as well leads to light to be assumed same type of light when calculating direction during lightmap baking.

Project for repro: https://playcanvas.com/editor/scene/450107
Steps:
1. bake
2. select light and change type to spot/direct (whichever you had not)
3. bake
Issue will be apparent in weird shadowmap artefacts and the fact direction in lightmap not changed as supposed to. Refreshing editor "fixes" issue, means it is some internal caching/flag issue when deciding to avoid recalculating some extra stuff.

This how it looks when switched from directional to spot:
![image](https://cloud.githubusercontent.com/assets/636263/17438776/75a4e6fe-5b1c-11e6-8d2f-d3542c2fc296.png)

And here how it looks when after refresh changing from spot to directional:
![image](https://cloud.githubusercontent.com/assets/636263/17438814/a5ab1d32-5b1c-11e6-8da9-8f6e26a364de.png)

**Comment by guycalledfrank** [comment]
Seems to only happen in "Color + Dir" mode.

**Comment by guycalledfrank** [comment]
Fixed in https://github.com/playcanvas/engine/pull/723
