### ISSUE TITLE
WebGL errors when cloning particle systems

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#714]
As reported here: http://forum.playcanvas.com/t/problem-with-particles/2260

Steps to reproduce:

1. Create an entity with particle system
2. Clone entity with particle system
3. Call entity.destroy on new clone
4. Clone original entity again.

Probably due to recently added particleemitter.destroy() method and some shared properties.

**Comment by ejacquier** [comment]
Hi,

Any idea when this will be fixed?
This is major for us and using the enable/disable workaround would be very time consuming.

Thanks,
Emmanuel

**Comment by guycalledfrank** [comment]
var p2 = this.entity.clone();
    p2.destroy();

I do this in an update loop of an entity with particle system attached. No errors. Maybe there are other conditions?

**Comment by daredevildave** [comment]
See this project: https://playcanvas.com/project/415342/overview/particle-cloning-test

**Comment by guycalledfrank** [comment]
That should be resolved in https://github.com/playcanvas/engine/pull/718

**Comment by daredevildave** [comment]
This is now deployed.
