### ISSUE TITLE
GltfExporter - GLB Files Compliance with glTF 2.0 Specifications

### ISSUE THREAD

**Issue by AlbertoMalavasi** [playcanvas/engine#7144]
Description

GLB files exported seems not to comply with glTF 2.0 specifications, leading to potential rendering issues. The validator identifies multiple errors related to inconsistent bufferView target assignments and missing skin definitions for skinned meshes. These issues result in an invalid file that may not render correctly or work as intended in standard glTF viewers.

Export Tool: [PlayCanvas GltfExporter](https://api.playcanvas.com/classes/Engine.GltfExporter.html)

File/Example: [Link](https://playcanvas.vercel.app/#/loaders/gltf-export)

Validator Tool: KhronosGroup glTF Validator (Version 2.0.0-dev.3.9)

Issue Summary:

Critical Errors: Buffer view target overrides (e.g., IndexBuffer overwritten as Image or VertexBuffer overwritten as IndexBuffer).

Warnings: Missing skin definitions for nodes with skinned meshes.

Info: Unused attributes (TEXCOORD_1) and empty nodes.

Impact: The GLB file seems not to comply with glTF 2.0 specifications, leading to potential rendering issues.

[ValidationReport.pdf](https://github.com/user-attachments/files/17932265/ValidationReport.pdf)

**Comment by mvaligursky** [comment]
related to https://github.com/playcanvas/engine/issues/5001

**Comment by willeastcott** [comment]
I've fixed the critical buffer view target overrides issue here:

https://github.com/playcanvas/engine/pull/7152

![image](https://github.com/user-attachments/assets/20dd4d24-5067-49b8-b825-4fa258dc39e5)

**Comment by willeastcott** [comment]
I've also submitted a PR that optionally strips unused vertex attributes but it defaults to false (since we can't make assumptions about what you plan to do with vertex attributes at runtime - say with a custom shader):

https://github.com/playcanvas/engine/pull/7153

**Comment by AlbertoMalavasi** [comment]
Thank you, @willeastcott, for both. We really appreciate your help.

**Comment by willeastcott** [comment]
@AlbertoMalavasi I just submitted a further PR to correctly export skinning data as well so those warnings should disappear with the next minor release of the engine too.
