### ISSUE TITLE
Outline renderer overwrites any onPreRenderLayer function on a camera

### ISSUE THREAD

**Issue by MAG-ME** [playcanvas/engine#7150]
### Outline renderer overwrites any `onPreRenderLayer` function on a camera

If the camera being used to render a scene has an `onPreRenderLayer` function assigned the outliner code will overwrite that function when activated and reset it to null when de-activated. This is happening in the `frameUpdate` method. The existing function, if present, should be preserved and called as well as the outline renderer's own `onPreRenderLayer` function.

**Comment by mvaligursky** [comment]
fixed by #7156
