### ISSUE TITLE
Allow simulating particles in local space

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#716]
- Sometimes it's desired;
- It's cheaper.

**Comment by Maksims** [comment]
Moving train is good example, but it's not really "local" to particle emitter, but to some other node.

**Comment by guycalledfrank** [comment]
Current quick implementation: https://github.com/playcanvas/engine/pull/717
Note that it's possible to implement much more efficiently. We don't need to store intermediate particle state for local-space systems.

@Maksims Moving train should be world-space, at least when I think of smoke...

**Comment by daredevildave** [comment]
Note, implementation referenced in #717 doesn't work. We'll have to do something more "proper"

**Comment by cainmartin** [comment]
Any traction on this issue? One use case that is common is muzzle flash or charge up effect on a weapon. Unfortunately it makes it impossible to use the particle system for such effects as the particle is left behind as (for instance) a character moves.

**Comment by Pheater** [comment]
I would be interested in this feature as well.

**Comment by willeastcott** [comment]
Today, we deployed [Engine v1.17.0](https://github.com/playcanvas/engine/releases/tag/v1.17.0) which has support for local space particles.
