### ISSUE TITLE
Contact shadows look broken

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#7196]
They do not look _at all_ what I would expect from contact shadows:

![image](https://github.com/user-attachments/assets/c2dd4597-e924-4c34-a1b4-933bb0d2a1ba)

We should invest some time to improve their fidelity. Particularly since this is public API with a public example in the examples browser.

**Comment by mvaligursky** [comment]
related attempted fix: https://github.com/playcanvas/engine/pull/5483

**Comment by willeastcott** [comment]
Well, that PR does certainly improve the visuals. So if it's a significant improvement, any reason not to merge?
