### ISSUE TITLE
renderLine - with multiple cameras

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#720]
Currently renderLine will render only in one camera, making it pretty "annoying" when it is required to use multiple cameras.

It would be really good to have a way to specify which camera should render it.
Camera has a cullingMask which is used to define which object is visible within which camera. Same property could be used for lines, by default with 0xFFFFFFFF mask. That would allow users to define in which camera lines have to be drawn if they need precise control over it, as well as be able to render lines in all cameras (except shadowmaps, lightmaps, etc).

**Comment by daredevildave** [comment]
Fixed in #1124
