### ISSUE TITLE
Parallax + No normal map + Lightmap = shader error

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#721]
Shader generator seems to behave wrong given this combination.

**Comment by willeastcott** [comment]
A parallax map without a normal map? Does that even make sense?

**Comment by guycalledfrank** [comment]
Not much. Pixel displacement will work, but it would still be lit based on vertex normals. We still allow it however.

**Comment by willeastcott** [comment]
This no longer seems to happen:

![image](https://user-images.githubusercontent.com/697563/33803306-7e22a20a-dd41-11e7-86ae-76a1c7638266.png)

@guycalledfrank - if you think I'm closing this prematurely, please re-open.
