### ISSUE TITLE
Graphic issue with some Android devices

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#728]
See this thread: http://forum.playcanvas.com/t/speckles-on-android/2409

![screen](https://i.imgur.com/Wm7cE64.png)

**Comment by guycalledfrank** [comment]
Can't reproduce it on Samsung Tab S. Only specific to some GPUs?
![screenshot_2016-09-07-19-22-28](https://cloud.githubusercontent.com/assets/7008423/18322170/9060f4e0-7531-11e6-9802-51214952f9ed.png)

**Comment by guycalledfrank** [comment]
Which project exactly is it?

**Comment by guycalledfrank** [comment]
Can't reproduce it on Samsung Tab S. Specific to some GPUs?
![screenshot_2016-09-07-19-31-54](https://cloud.githubusercontent.com/assets/7008423/18322328/6ff46042-7532-11e6-9a61-68f53799935a.png)

**Comment by Maksims** [comment]
If this has been addressed?

**Comment by willeastcott** [comment]
Closing due to age of bug. No similar reports of such artifacts have come in over the last year.
