### ISSUE TITLE
About the main file

### ISSUE THREAD

**Issue by x09326** [playcanvas/engine#736]
Hi, I'm going to host this lib on [cdnjs](https://cdnjs.com).
But I don't know which files should be added.
Could you explain to me?
Thanks!

https://github.com/cdnjs/cdnjs/issues/8508

**Comment by willeastcott** [comment]
You just need to build and include the built JS library. Probably best to include the minified and unminified library.

- Clone the repo
- Switch to stable branch
- Run node build.js in the build folder. This will generate playcanvas-latest.js
- Check the last commit of the form [RELEASE] vX.XXX.X. This is the build version.
- Rebuild unminified: node build.js -l 0 -o playcanvas-X.XXX.X.js
- Rebuild again minified: node build.js -l 1 -o playcanvas-X.XXX.X.min.js

**Comment by daredevildave** [comment]
It looks like cdnjs wants you to link to a "published" version. Which makes me think we should:

**Comment by PeterDaveHello** [comment]
Hi @willeastcott, is it possible to release the official builds? It'll be a good "reference" since sometimes we can not so easily make sure if the built files been built 100% correctly, and for security reason, it'll be better to use a official build(if there is one), actually CDNJS started to support (subresource integrity) recently, this is also for security and integrity, we believe it'll be better to have the dist files from official, not us, what do you think? Thanks.

**Comment by daredevildave** [comment]
After this issue, I got thinking about this. 

So first off, we do have official builds on code.playcanvas.com. All builds are there, including the most recent stable as `playcanvas-stable.min.js` and the latest master as `playcanvas-latest.min.js`. However, we don't list these anywhere.

There are a few options:

1. Create an index page for code.playcanvas.com that links to all the versions so people can find them.

2. Check builds into the main repo. I don't really like this as we create builds almost daily and it just feels like bloating the repo.

3. Check builds into another repo. e.g `engine-builds`

4. Publish builds to npm.

5. Several of the above.

**Comment by PeterDaveHello** [comment]
Option 3 looks good, there are some libraries have this method for bower release, it'll be great!

**Comment by Maksims** [comment]
There are engine builds available here: https://github.com/playcanvas/engine#how-to-build
