### ISSUE TITLE
Asset loader should retry failed assets

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#737]
To avoid small network hiccups the asset loader should make multiple attempts to reload textures (potentially with exponential back off).

If an application thinks that a resource should be available (e.g. it is listed in the asset registry) there is no reason to assume a failure is anything but a temporary outage.

**Comment by Maksims** [comment]
This perhaps should take in account XHR behaviours to check response statuses, so to avoid requesting when valid 404 is given.
It will have a cost of requesting again by polluting request queue so should be done with care.

**Comment by yaustar** [comment]
@vkalpias implemented retry of failed assets
![Uploading image.png…]()
