### ISSUE TITLE
What should happen when applying opacity less than 1 to a node with descendants?

### ISSUE THREAD

**Issue by trusktr** [playcanvas/engine#740]
Hello Dave, Will, and contributors,

I'd like your opinion:

If we have a node in a 3D scene, and it has many descendants (a sub tree), what should happen when we apply opacity with a value less than `1` to it?
1. It, and all of it's children should become transparent, multiplying opacities down the scene graph.
2. It's content should become transparent but not that of its descendants.
3. Same as (1), but the whole object should be flattened into a plane.

The reason I want your opinion is because the new specs for CSS 3D (css-transforms) [state here](https://drafts.csswg.org/css-transforms/#grouping-property-values) that the answer is (3).

To see what I mean, view these two examples in Chrome 53 or higher:
- https://jsfiddle.net/trusktr/ymonmo70/16
- https://jsfiddle.net/trusktr/ymonmo70/17

The second example has opacity applied to the node that contains all the sub-nodes which compose the car. The opacity, according to spec, flattens the car into a plane (turns it into paper!).

I'm asking various 3D engine authors for opinions of what the correct or most expected behavior should be.

All the best,
~ Joe

**Comment by Maksims** [comment]
In our case, materials - is what contain opacity information. Materials are applied on meshInstances, which are part of model component of an Entity.
Entities are part of scene graph, but properties of opacity are not applied to entities, they are applied to materials.
If you visualise structure, then you will get a tree with leaves, where leaves - are meshes with materials, they are not within the graph, so they can't be inherited.

So in PlayCanvas, any material properties are applied only to meshes that material is applied on, and have no any ability to propagate through scene graph to siblings.
