### ISSUE TITLE
The particle system uses the same entity as its graph node 

### ISSUE THREAD

**Issue by vkalpias** [playcanvas/engine#746]
In the particle system component in onEnable we do `this.psys.graph = this.entity;` instead of creating a new pc.GraphNode and assigning that as the graph (and then that new graph node would be a child of the Entity like the model component does). This means that when onRemove is called in ParticleSystemComponentSystem we do `entity.removeChild(data.model.getGraph());` but here `entity === data.model.getGraph()` so essentially this calls `entity.removeChild(entity)` which is kinda wrong.. 

The tricky bit fixing this is making sure that we remove the new pc.GraphNode when we re-create the emitter.

**Comment by mvaligursky** [comment]
the thing is .. I like that it does not use extra GraphNode .. new render component does the same and uses just this.entity without any extra node.

**Comment by willeastcott** [comment]
@mvaligursky My results:

* 1.38.4 - no lag (https://launch.playcanvas.com/1088894?use_local_engine=https://code.playcanvas.com/playcanvas-1.38.4.js)
* 1.39.0 - lag (https://launch.playcanvas.com/1088894?use_local_engine=https://code.playcanvas.com/playcanvas-1.39.0.js)
* 1.39.3 - lag (https://launch.playcanvas.com/1088894?use_local_engine=https://code.playcanvas.com/playcanvas-1.39.3.js)

So yes, it still seems to be a problem with the latest engine.

**Comment by willeastcott** [comment]
The `ParticleSystemComponent` does not need to have a `Model`. I've removed it which renders this issue solved, IMHO.
