### ISSUE TITLE
PCF bias generates artefacts

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#752]
Without shadows:

![image](https://cloud.githubusercontent.com/assets/697563/19481013/6c73af36-9544-11e6-87d7-82cff667c724.png)

With shadows:

![image](https://cloud.githubusercontent.com/assets/697563/19481024/771bd5d0-9544-11e6-9504-5d4398a80a46.png)

**Comment by guycalledfrank** [comment]
Should be gone at least when running WebGL 2.0 after this: https://github.com/playcanvas/engine/pull/892
1.0 still has the artifacts, but can be fixed

**Comment by willeastcott** [comment]
I can no longer reproduce these artifacts. Therefore, I am closing this issue. If anything similar is found again, a new issue can be logged.
