### ISSUE TITLE
Consider supporting failIfMajorPerformanceCaveat on webgl canvas

### ISSUE THREAD

**Issue by daredevildave** [playcanvas/engine#758]
The WebGL spec has a new option failIfMajorPerformanceCaveat which means context creation fails if the browser is using a software renderer for example.

Seems likely that many PlayCanvas applications won't perform adequately with a software renderer so we should consider setting this to true, or at least allowing a user to set it to true

**Comment by willeastcott** [comment]
We already support this in the engine. Just set this property on option.graphicsDeviceOptions, where options is an argument of the pc.Application constructor. The graphicsDeviceOptions object is passed directly into getContext when wrangling the WebGL context. I suggest closing this, @daredevildave.
