### ISSUE TITLE
Particle Effects don't render correctly when moved in the world

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#759]
From this thread: http://forum.playcanvas.com/t/particle-not-play-again-sometimes/2588/5

I've reproduced the issue with this project: https://playcanvas.com/project/432274/overview/particle-issue-from-forums

Video of the bug: https://drive.google.com/file/d/0B-I0B3mugV-Gazh3V2ZuM2RoRHc/view?usp=sharing

The issue exists for all the particle effects but the one it is most noticeable on is the death one where the player collides into an obstacle. The particle effect gets moved to the position of the cat when it collides and then reset() and play() gets called on the particle effect in the same function.

To reproduce, hit the first object and the particle effect plays, then when the player hits another object 10 so objects into the road on the second run, the particles don't render and on the third run, hit the first object again, there's this weird sorting issue that renders the particles on the object and on the background but not above the road (see attached pics)

![c-80982457-6faf-4999-95ac-0170933a3bfa](https://cloud.githubusercontent.com/assets/16639049/19650125/11f45770-9a00-11e6-9b30-80b6aadec4b3.png)

![c-d0eba4d0-53ba-49d6-89cd-515ff32f25a9](https://cloud.githubusercontent.com/assets/16639049/19650131/17d5919a-9a00-11e6-9b13-a14811dc5c2e.png)

**Comment by yaustar** [comment]
From this thread: http://forum.playcanvas.com/t/particle-not-play-again-sometimes/2588/5

I've reproduced the issue with this project: https://playcanvas.com/project/432274/overview/particle-issue-from-forums

The issue exists for all the particle effects but the one it is most noticeable on is the death one where the player collides into an obstacle. The particle effect gets moved to the position of the cat when it collides and then reset() and play() gets called on the particle effect.

To reproduce, hit the first object and the particle effect plays, then when the player hits another object 10 so objects into the road on the second run, the particles don't render and on the third run, hit the first object again, there's this weird sorting issue that renders the particles on the object and on the background but not above the road (see attached pics)

![c-80982457-6faf-4999-95ac-0170933a3bfa](https://cloud.githubusercontent.com/assets/16639049/19650125/11f45770-9a00-11e6-9b30-80b6aadec4b3.png)

![c-d0eba4d0-53ba-49d6-89cd-515ff32f25a9](https://cloud.githubusercontent.com/assets/16639049/19650131/17d5919a-9a00-11e6-9b13-a14811dc5c2e.png)

**Comment by guycalledfrank** [comment]
Can you make a simple example without requiring to play the kitten game?

**Comment by yaustar** [comment]
Simplified version: https://playcanvas.com/project/432829/overview/simplified-particle-problem

Press 0 to teleport the camera and particle effect to the origin
Press 1 to teleport the camera and particle effect to 100 units in the Z axis
Press Space to reset and play the particle effect

Particle effect is set to 1 sec lifetime

To reproduce: 
Press 0, then press Space to trigger the particle effect. Effect plays.
After all the particles disappear, press 1, then press Space to trigger the particle effect. Effect does not play (you may get one or two particles show up at the end). 
Wait a couple of seconds, press Space again and particle effect will play like normal

**Comment by guycalledfrank** [comment]
Seems to be fixed in https://github.com/playcanvas/engine/pull/762 (wait for it to deploy on prod)
