### ISSUE TITLE
Lightmap baking stops working when changing between Shadow Type

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#764]
Sample Project: https://playcanvas.com/project/433362/overview/shadowmap-baking-bug

To reproduce:
1. Select light from scene
2. Change ShadowType from Variance Shadow Map (32bit) to Variance Shadow Map (8bit)
3. Rebake the scene (Ctrl + B)
4. Change ShadowType from Variance Shadow Map (8bit) to Variance Shadow Map (32bit)
5. Rebake the scene (Ctrl + B)
6. Shadow maps fail to generate and the following error appears on console: 
[.Offscreen-For-WebGL-0x7fdcb1bd3000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

Video of bug can be found here: https://drive.google.com/file/d/0B-I0B3mugV-GMXlheURLTTFFMTA/view?usp=sharing

**Comment by mvaligursky** [comment]
I tested this and it works without problem - must have been fixed already. Closing.
