### ISSUE TITLE
Odd artifact on particle effect when it is moved multiple times 

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#767]
Related to: https://github.com/playcanvas/engine/issues/759

Project: https://playcanvas.com/editor/scene/469362
Video: https://drive.google.com/open?id=0B-I0B3mugV-GVzljZk5fMmp3WVk

Repro steps: 
1. Hit the first obstacle. White/grey cubes that spawn look fine
2. Hit the 10th-ish obstacle that is far. White/grey cubes that spawn look fine
3. Hit the first obstacle again. White/grey cubes have an odd edge/artifact

![pasted image at 2016_10_27 12_38 pm](https://cloud.githubusercontent.com/assets/16639049/19934243/d93f69f0-a10d-11e6-91e2-5ad7f244b766.png)

What is odd that if I change the road material to a newly created one with exactly the same settings and textures, it looks fine. @Maksims thinks it might be related to the order of drawing and using a different material may change the order?

Unfortunately I can't create a smaller project for this.

**Comment by guycalledfrank** [comment]
Please, can you at least make the replay button work on PC?

**Comment by yaustar** [comment]
I can try. In the meantime, you can use the Developer tools to 'fake' it.

**Comment by yaustar** [comment]
Fixed replay button on PC

**Comment by guycalledfrank** [comment]
PinkFloorMaterial had Alpha enabled. Disabling it fixes the problem for me.

**Comment by yaustar** [comment]
Thanks for looking into it!

**Comment by WingMrL** [comment]
Thank you very much !
