### ISSUE TITLE
Issues with particlesystem and pack8

### ISSUE THREAD

**Issue by vkalpias** [playcanvas/engine#770]
Create a particle system that has `autoplay = false` and `loop = false`.  In code set its position and play it. Then change its position and play it again. You should notice (maybe not in all platforms) that some particles spawn in the old location. This seems to be fixed if we change `this.pack8 = true` to `this.pack8 = false` in the particle emitter.

This happens on a Macbook Air 2013.

**Comment by vkalpias** [comment]
Another issue solved the same way is having a particle system with initial velocity e.g.:

particle count: 6
emission rate: 0.01, 0.01
initial velocity: 2

See attached gifs for behaviour.

![correct](https://cloud.githubusercontent.com/assets/850969/20002700/ca89c0c6-a28a-11e6-8861-a61494adaf76.gif)

![wrong](https://cloud.githubusercontent.com/assets/850969/20002703/cf7d63bc-a28a-11e6-9b65-dc8363e92717.gif)

**Comment by willeastcott** [comment]
I believe that Engine v1.17.0 has fixed your problem so I am closing this now. If you find that a problem remains, please reopen the issue.
