### ISSUE TITLE
Light falloff modes reversed?

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#773]
This is Linear:

![image](https://cloud.githubusercontent.com/assets/697563/20099271/882470dc-a5af-11e6-8d79-57ae8f7b7b3e.png)

This is Inverse Squared:

![image](https://cloud.githubusercontent.com/assets/697563/20099277/91d70dba-a5af-11e6-884c-53139d2687a7.png)

Are they reversed?

**Comment by Maksims** [comment]
This is not bug, and hasn't been tested properly.
With Linear Tonemapping it will look over-bright. But falloff is actually squared.

Linear:
![Linear](https://cloud.githubusercontent.com/assets/636263/20100353/12267992-a5b5-11e6-9e6e-32b9344fd76e.png)

Inverse Squared
![Inverse Squared](https://cloud.githubusercontent.com/assets/636263/20100361/18b204de-a5b5-11e6-901b-7094b4b3b657.png)
