### ISSUE TITLE
Area Lights

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#774]
Add Area Lights with different techniques, even if their functionality is partly limited (no shadows for example).

It would be great to have: `Sphere`, `Capsule`, `Plane` area light shapes.

**Comment by mvaligursky** [comment]
current forum thread: https://forum.playcanvas.com/t/are-area-lights-supported/14647/5

**Comment by raytranuk** [comment]
Some thoughts on implementation - seems like there is 2 approaches to consider:
1. add a new type of light e.g `LIGHTTYPE_AREA` to existing light types: `LIGHTTYPE_DIRECTIONAL`, `LIGHTTYPE_POINT`, `LIGHTTYPE_SPOT`
2. OR add Area light properties to the existing light types - along the same lines as the shadow related properties.

I would probably lean towards the second option - and use the same mechanisms to expose the extra area light data to the shaders and switch to area light shader chunks, that the shadow properties use. It may also be easier to work with in editor-based projects - as developers can add and use existing light types in scenes - and have project script add in the area light properties - until area light editor support is added (which would normally be done by adding a editor feature request issue here: https://github.com/playcanvas/editor).

**Comment by Maksims** [comment]
From shader implementation point of view and in engine, area lights shadows - is a complex issue. But I don't believe because there are no shadows, such light types should not be added.
There are many types of area lights: quad, sphere, capsule, and possibly more. All of them can have luminosity and some of them might have texture, like quad.
It will be best to separate them as different light types from engine point of view:
1. Horizontal feature set instead of vertical complexity of existing features.
2. There is different logic with shadows and availability of them as well as type depends on light type (current logic, good to preserve).
3. Clear code separation will have clear shader chunks and easier to modify for shader developers.

**Comment by marklundin** [comment]
Yes, this is valid. I'm only thinking about quad area lights in this instance, but any new code introduced would need to accommodate future variations of other area lights.

In terms of implementing linearly transformed cosines, each quad area light requires the following properties

``` c
vec3 color;
float intensity;
bool twoSided;
sampler2D texture;
```

It also requires width, height, position, and rotation, which can obviously be in various formats. In three, I believe they just have a vec2 position, and width height are supplied as vec3's which have been rotated to the plane

**Comment by Maksims** [comment]
> It also requires width, height, position, and rotation, which can obviously be in various formats. In three, I believe they just have a vec2 position, and width height are supplied as vec3's which have been rotated to the plane

In case of quad light, it will be **width** and **position**, in form of Vec2 (size). And position with rotation comes from entity transformation, like with other light sources.

I wander though, regarding scaling. Should it affect area light sources in terms of their size. Perhaps it should, as it makes sense to have models with light sources, move them around and scale their parents and expect children lights to scale accordingly. Especially as most of the time developers will add models with relevant area light meshes with emissive materials. But not always.

Another thing, is area light itself is renderable object, it has a volume of light, specifically emissive object with its material based on light color and intensity. It probably should be on by default, but should be possible to disable it.

Biggest use cases probably will come in form of rendering them to lightmaps, with directional information baked into lightmap - this is another thing to look into.

**Comment by marklundin** [comment]
Just a quick update on this. I've taken a first pass as this and have successfully added the basic features for  a quad area light.

![image](https://user-images.githubusercontent.com/430764/98163418-b4cd7680-1eda-11eb-82af-7a9ce74f7eb3.png)

I've opted to add an additional Light type mainly as I saw this as the quickest and most convenient route, however I'm aware this is effectively only a lit quad and, as pointed out, area lights can take many shapes. The light mapping doesn't currently work, and I'm unsure where to start with this tbh.

The main pain points thus far are

1. Banding - some very obvious banding in the lit surfaces. This isn't an issue with the implementation per se, I've thought about adding some dithering at the end of the standard material pass, but this is essentially a separate issue to discuss.

2. The LTC's rely on a fairly significant LUT that needs to be uploaded as a texture to the GPU. Currently I've got this as a large array which is compiled into the engine which of course is not ideal, so I'd be interested in hearing ideas on this. Also the data is a floating point texture, so there is an issue around extension support etc.

I'm now aiming to get texture support for the area lights. Also I'd love to get this tested as an in editor feature, but Im not sure if there is a dev workflow for the editor to use a custom engine

**Comment by mvaligursky** [comment]
That's looking very nice! Great progress.

Regarding the float textures .. have a look here at what I've done for storing morph targets in the texture:
https://github.com/playcanvas/engine/blob/master/src/scene/morph.js

see how I detect float / half float format support in the constructor (_textureFormat) and then at the end of the file create texture and fill it up with data.

One idea related to large LUT could be to store it in separate .js file and include it in the project only when needed. Maybe something similar to what is done with mini-stats here: https://github.com/playcanvas/engine/tree/master/extras
and here https://github.com/playcanvas/engine/blob/adf7ddbea80be74dc4d2478b511397f8d794e843/rollup.config.js#L166-L179
This is how engine examples then use it: https://github.com/playcanvas/engine/blob/adf7ddbea80be74dc4d2478b511397f8d794e843/examples/graphics/grab-pass.html#L9

Lightmapping takes place https://github.com/playcanvas/engine/blob/master/src/scene/lightmapper.js but that is something we can perhaps help with when main implementation is ready?

Editor feature will most  likely need to be implemented on our side when engine side is done, this is not exposed to developers at this stage.

Super exciting!

**Comment by marklundin** [comment]
Thanks @mvaligursky I'll look into this. I was wondering if using `import()` to code split and keep this out of the main bundle, but I'll look into the extras bundle.

Also, I think it makes sense to also use the LTC with the specular clearcoat for consistency even though this requires additional taps on the Lut.

I'd also be keen to know what you're thoughts are about specifying the quad dimensions. Whether this should be as width/height independently or by having a unit quad and using the scale of the entity transformation.

**Comment by mvaligursky** [comment]
I'm familiar with the sparate bundles like we used for the extras -  so that should work, but I'm sure @willeastcott will suggest other options as well?

I think it would probably be good to handle clearcoat if not too much trouble, we could always expose it under an option if that becomes too expensive. But the quality of this for some use cases (cars under area lights) could look amazing with it.

Regarding the quad dimensions - I would expose it as a properties of the light and keep the transform scale out of it. I think when we had a discussion with the team regarding this, we agreed it'd be the best to create new light type - area light, and if we end up adding additional shapes of the area light, the shape / dimensions of it would be exposed as properties of this area light type. So you're on the good path here I think.

**Comment by mvaligursky** [comment]
By the way, please let us know if you need help with anything on this. Once you create the initial PR, we can help out to bring it to the finish line if needed.

**Comment by marklundin** [comment]
Thanks @mvaligursky. I'll just add the clearcoat, width/height scaling and then split the LUT lookup to use half floats for WebGL1

**Comment by mvaligursky** [comment]
I wonder if we need to do anything on devices not supporting half nor float texture format. In our particle system that runs on GPU we encode float data to series of RBGA8 textures .. but I guess maybe an easiest solution here would be to just fall back to spot light or something?

**Comment by willeastcott** [comment]
On the subject of the LUT, how big is it exactly? The `playcanvas-extras.js` file just contains the `pcx.MiniStats` API for now. It's unclear how the extras lib will evolve and what it will contain. MiniStats is really a development-time utility and not expected to be included in a shipped app. Are there tricks to compress/quantize the LUT somehow?

**Comment by mvaligursky** [comment]
What I was suggesting is to create a separate module like extras/mini-stats. Maybe extras/arealights, to be included when user wants to use area lights. Maybe similar to physics engine - users need to then include the file in their project to use the lights?

**Comment by willeastcott** [comment]
Perhaps. But lighting-related code is so ingrained in the core engine, it might be difficult to write this as an isolated/independent lib.

**Comment by marklundin** [comment]
There are 2 luts coming in around 80kb. This can be reduced for example
storing as binary, but I've not really looked into it yet. The second Lut
is an optimised Fresnel term so maybe that could be swapped out for the
schlicks approximation.

**Comment by raytranuk** [comment]
Another possibility is to generate the luts on app startup - if they can be generated in around the same amount of time as they would take to download - and assuming the lut generation code itself is smaller than 80kb.

**Comment by raytranuk** [comment]
> we agreed it'd be the best to create new light type - area light, and if we end up adding additional shapes of the area light, the shape / dimensions of it would be exposed as properties of this area light type.

After more consideration, I do still favor adding a shape property to current punctual lights - as this means the user/system can choose to enable approximations to area lights for weaker platforms (or automatically, as the light gets further away from carmera) without scenes having to set up with multiple versions of the lights - it also opens up the possibility of using current shadows with area lights as a rough approximation for dynamic shadows, but add a better approximation for when rendering to light maps (or cached static shadow maps).

>I wonder if we need to do anything on devices not supporting half nor float texture format. In our particle system that runs on GPU we encode float data to series of RBGA8 textures .. but I guess maybe an easiest solution here would be to just fall back to spot light or something?

If we did have shape as a property, when the shape property is not useable it could fallback to alternative/cheaper shapes - including down to the cheapest shape: an infinitesimally small point.

Anyway, looking forward to more discussion as this feature progresses.

**Comment by marklundin** [comment]
I've submitted a first PR for this under #2535. There is a simple (demo implementation here)[https://playcanvas.com/project/730762/overview/arealight] which you can test against the built engine.
