### ISSUE TITLE
Culling problems for Editor grid

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#777]
I'm assuming this is an engine problem but feel free to disagree. It's quite easy to have the Editor grid disappear. e.g. In the starter scene, go from here:

![image](https://cloud.githubusercontent.com/assets/697563/20242916/c92ca154-a937-11e6-9edd-32dadd3a51be.png)

And move the camera slightly:

![image](https://cloud.githubusercontent.com/assets/697563/20242918/db8b940e-a937-11e6-91c1-e90694dc16ff.png)

**Comment by Maksims** [comment]
That is Editor problem as it does not provide correct AABB for mesh.

**Comment by willeastcott** [comment]
Oh right. Is this issue already logged then?

**Comment by Maksims** [comment]
I think ticket in jira, to make whole new useful grid system. As current one is a bit useless :)

**Comment by willeastcott** [comment]
OK, I'll close this then.
