### ISSUE TITLE
Bounding Box and Bounding Sphere should share similar API

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#779]
Bounding Sphere has 'intersectRay'
Bounding Box has 'intersectsRay'

The two functions also return different data (one returns a new ray and the other a boolean).

Bounding Box can also check against another Box whereas Bounding Sphere doesn't have an equivalent function.

**Comment by daredevildave** [comment]
See also #644.

**Comment by Maksims** [comment]
Fixed in https://github.com/playcanvas/engine/commit/722469b3054b755eba11aa6641cfe63d35df060b
