### ISSUE TITLE
createSkinnedMesh helper

### ISSUE THREAD

**Issue by majimboo** [playcanvas/engine#785]
I think we should add a new function or extend `createMesh` that would create a mesh that has the options for `pc.SEMANTIC_BLENDWEIGHT` and `pc.SEMANTIC_BLENDINDICES`

Something like:

    var positions = [];
    var normals   = [];
    var uvs       = [];
    var indices   = [];
    var blendIndices = [];
    var blendWeights = [];

    var options = {
      normals : normals,
      uvs     : uvs,
      indices : indices,
      blendIndices: blendIndices,
      blendWeights: blendWeights
    };

    var mesh = pc.createMesh(app.graphicsDevice, positions, options);

**Comment by willeastcott** [comment]
Fixed by #786 so closing
