### ISSUE TITLE
The touch and mouse events should behave the same way across all platforms

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#787]
At the moment, Android and iOS behave differently. When the app has registered both mouse and touch events, both the mouse down and touch start event gets fired in PlayCanvas.

Tapping on the either the sphere or cube on Android will trigger two animations, one 'pulse' for the initial touch (touchStart) and another when the finger has left the screen (mouseDown).

On iOS, only the touch events are triggered.

It's currently possible to get around this in the project by calling preventDefault() on the actual event within the callback for touchStart.

Edit: There is some concern on whether preventDefault() prevents any other desired events such as scrolling on a div. 

Example project: https://playcanvas.com/project/439579/overview/mouse-and-touch-event-bug (look in shape-picker.js for the relevant code).

**Comment by yaustar** [comment]
Read a little more into touchEvents it looks like the advice is to use preventDefault() to prevent the mouse events: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#Additional_tips

According to the W3C, the default action is to perform a series of the mouse events: https://www.w3.org/TR/touch-events/#touch-interface

**Comment by willeastcott** [comment]
I don't personally consider there to be a bug here. You should call `preventDefault` in your event handlers, as you point out. Should this be closed?

**Comment by yaustar** [comment]
Yeah, we can close this. I think it makes more sense to move to pointer events instead
