### ISSUE TITLE
Fly camera example not working with engine v0.201.0 6562a09

### ISSUE THREAD

**Issue by pietrovismara** [playcanvas/engine#789]
The [fly camera example](http://playcanvas.github.io/#camera/first_person/index.html) seems to be working with the engine v0.181.0-dev 6e8e3c6.
When testing it local with the stable release of the engine i get no errors, but the camera is freezed, i cannot move it. 
Probably the example js should be adapted to the actual stable release?

**Comment by willeastcott** [comment]
Fixed in f2f81afd2eb9c4de42f60d57a4adc2990e53c9a2
