### ISSUE TITLE
Convert from various panorama projections to cubemap

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#794]
It'd be very nice to create cubemaps from latitude/longitude or vertical cross projections. Requires small engine utils + editor support.

**Comment by Maksims** [comment]
Here is forum discussion regarding that feature: http://forum.playcanvas.com/t/iray-pascal-spherical-camera-photospheres/2797

It worth thinking about different approaches and their cons/pros.

**Comment by guycalledfrank** [comment]
Converting to 6 face assets in Editor would be the best, I guess.

**Comment by Maksims** [comment]
I agree, that would not blow up the engine, and prevent complicated branches in logic with cubemaps and will not introduce runtime conversion performance hit.

**Comment by willeastcott** [comment]
Assigning this one to you @slimbuck, since you're super-keen to refresh PlayCanvas' cubemap handling. 😄

**Comment by willeastcott** [comment]
@slimbuck Does the addition of [`reprojectTexture`](https://developer.playcanvas.com/api/pc.html#reprojectTexture) address this? If not, what work would be required to justifiably close this issue, in your opinion?

**Comment by slimbuck** [comment]
Engine handles equirect only and not possible in editor yet.

**Comment by slimbuck** [comment]
Perhaps we need an issue in the editor where we can start discussing design around this support.

**Comment by mvaligursky** [comment]
yep, I think there already is an issue for this in Editor repo.

**Comment by willeastcott** [comment]
If that is so and the engine support is done, I'm closing this. If you believe that supporting vertical cross projection is useful @slimbuck, please open a new issue.
