### ISSUE TITLE
Custom rendering API

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#798]
We should have a proper API to allow rendering selected objects to selected textures with selected shaders. It's often desirable, be it object icons, or rendering reflections into a render target.
The API should allow:
- Rendering a provided array of meshInstances and lights from any camera into any RT
- Overriding scene shaders/chunks while rendering
- Optionally ignore gamma/tonemap/fog/other global things

**Comment by Maksims** [comment]
> Optionally ignore gamma/tonemap/fog/other global things

That is managed by materials isn't it?
And by `Scene`. Multiple Scenes (Worlds?) could do exactly that, as they would contain specific models and lights, and can have own settings of gamma/tonemap/fog etc.
So basically, it is almost there, but needs to be changed so it is easier to work with.

**Comment by daredevildave** [comment]
Layer system seems to address this. For any additional features please open a new issue.
