### ISSUE TITLE
Looped animation doesn't lerp from end to start frame

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#799]
Visible if you set loop + low speed.

**Comment by willeastcott** [comment]
We're in the process of deprecating the current animation system. But assigning to @slimbuck in case this is something worth investigating.

**Comment by willeastcott** [comment]
Just thinking about this, if you _do_ lerp from the last frame to the first frame of an animation, what should be the duration of that lerp? Why is it wrong to immediately from the last two keys to the first two (as interpolation pairs)?

**Comment by slimbuck** [comment]
Clamping either side of animation keyframes is pretty standard, including glTF which says:

`... Before and after the provided input range, output should be "clamped" to the nearest end of the input range. For example, if the earliest sampler input for an animation is t=10, a client implementation should begin playback of that animation at t=0 with output clamped to the first output value.`

If an animator wants smoothly repeating animation, it's up to them to ensure start and end keyframes are matched accordingly.

**Comment by willeastcott** [comment]
So you're saying this is a data authoring problem? Can we close this?

**Comment by slimbuck** [comment]
Yup, closing out.
