### ISSUE TITLE
Add example showing the loading of a cubemap asset

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#800]
Ideally, we should show loading of both prefiltered and unprefiltered cubemaps.

**Comment by ImmanuelSamuel** [comment]
Yes this would be very helpful. I am trying to get the following to work but I only get a back background.
```
app.assets.loadFromUrl("/dds/space.dds", "cubemap", function (err, asset) {
    app.scene.skybox = asset.resource;
}); 
```
If I don't assign it I can see the camera clear color. So I believe there is something wrong with loading the faces.

**Comment by willeastcott** [comment]
We now have this:

https://github.com/playcanvas/engine/blob/master/examples/graphics/material-physical.html#L48

So I'm closing for now.
