### ISSUE TITLE
Normalize a Vec3 doesn't work when the length is zero

### ISSUE THREAD

**Issue by marionieto** [playcanvas/engine#808]
I did this:
`var vec = new pc.Vec3(0.0,0.0,0);`
`vec.normalize();`
`console.log("x: "+ vec.x + " y: "+ vec.y  + " z: "+ vec.z);`

Current Result:
`x: NaN y:NaN z:NaN`

Expected Result:
`x: 0 y:0 z:0`

**Comment by willeastcott** [comment]
0, 0, 0 isn't a normalized vector - I wouldn't expect that as the result. I'm not sure how this will help. If you're concerned that you might have a zero length vector, do:

if (v.length() > 0) {
    v.normalize();
}

**Comment by Maksims** [comment]
I would definitely make it at least not.to return NaN indeed.

**Comment by willeastcott** [comment]
OK. Fixed in https://github.com/playcanvas/engine/commit/bfcd6a26956deaeffb931ba3f711f8dc3feaaaf1
