### ISSUE TITLE
Elements: masking child elements

### ISSUE THREAD

**Issue by yard** [playcanvas/engine#819]
Hi guys,

As per https://github.com/playcanvas/engine/pull/816 I suggest to implement simple and efficient child masking using stencil buffer.

This feature is a must for many UI components, especially, scroll panels: the content outside visible area should not be drawn and, taking into account, the user is to decide which UI components to put into a scrollable area, it seems to be a good to have a generic mechanism for that.

The implementation idea is very simple: if we agree that basic renderable elements' are texts and images, we only have to maintain stencil parameters for the element hierarchy, updating reference stencil value for children once the parent masking settings change. 

Making the implementation even more universal, we can make Image components drive masking: the Images might be told to modify stencil buffer so that it's possible to create arbitrary shapes for masking. Using a default transparent texture filling the whole element's rect will give us a rectangular stencil area at a cost of 2 triangle rasterisation.

Please let me know if that sounds like a good idea.

**Comment by TobiasWehrum** [comment]
That's the second time I google for a PlayCanvas feature I'd need just to find one of your threads here - pointing to #816, which seems to have everything I could ever wish for, but apparently was never integrated...

**Comment by willeastcott** [comment]
Fixed in https://github.com/playcanvas/engine/pull/1118
