### ISSUE TITLE
Conventions for debugging additions

### ISSUE THREAD

**Issue by yard** [playcanvas/engine#820]
Hi @Maksims  and @daredevildave,

As per https://github.com/playcanvas/engine/pull/816 you suggested to take out `debugColor` property which I introduced to be able to "outline" UI elements' bounds.

While I do appreciate this is probably not the best approach to keep these things in the engine code, what's you suggestion on managing such things? I mean many users might find such debug additions helpful during the development, thus it should be somehow easily accessible, but I am not sure how exactly to keep that? @Maksims suggested to wrap the code into debug defines, which might be an option.

Do you actually have any repo or a part of an engine where such debugging routines can live? I bet it should be something well-known and easy to use for it to make sense – noone would think of googling such scripts if we keep it completely separate, but those come in really really handy some times.

**Comment by Maksims** [comment]
Previously we had debugging and visualizing features for collision, cameras, lights, and some other gizmos. And it looked liked no one actually have used them. Reason they were put there in first place is to render them in Editor. We've decided to remove them from the engine to keep engine cleaner, and implement it as own things in Editor.

More of a question - how easy or hard will it be for somebody to implement border code - how flexible is the system that would allow easily make such modification.

**Comment by yard** [comment]
You know, my question is quite generic: in most instances you either have something right at your fingertips or you quickly reinvent the wheel. The point is to put something easily accessible - not in the engine maybe, but still straightforward to find and use. 

Keeping this stuff solely in the editor is a politically biased decision as it prevents guys using these things from outside (when no editor is involved)

**Comment by Maksims** [comment]
Then perhaps hidden under DEBUG #define will do the good trick :)

**Comment by yard** [comment]
@guycalledfrank and @daredevildave – what do you think?

If debug define is OK, I would wrap the code into it before submitting as a PR.

**Comment by willeastcott** [comment]
Some time ago, we introduced the following convention for predicating debug code in the engine:

```
// #ifdef DEBUG
   doDebugStuff();
// #endif
```
Example:

https://github.com/playcanvas/engine/blob/master/src/math/mat4.js#L805

Therefore, I'm closing this.
