### ISSUE TITLE
Animations: smooth interpolation

### ISSUE THREAD

**Issue by yard** [playcanvas/engine#823]
Hi guys,

It looks like current animation interpolation is linear between keyframes. It seems to be a good idea to be able to specify curve parameters (i.e. In/out tangents or in any other form). 

Are there any plans/wip for that?

**Comment by Maksims** [comment]
We are planning work on Animations 2.0, which will be a whole rework for animations system, covering: file format simplification; morphing; playing groups of bones; better work with bones; much better control over animation playback; slots like on sound component; and many many other things. Right now animation is one of the weakest parts in engine. And huge system needs to be put in place. Loads of thinking :)

**Comment by yard** [comment]
I see your point, this way there is probably no point in bringing this up now :)
