### ISSUE TITLE
Engine references responseXML which is IE only

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#827]
Check this out:

https://github.com/playcanvas/engine/blob/18bdc36d108031beca3fbfab948feb911eea2159/src/net/http.js#L382

Throws an exception in Chrome when loading an XML doc because responseXML is undefined. 

Apparently, this is IE only:

http://stackoverflow.com/questions/12460813/null-responsexml-xml-value-in-chrome

**Comment by daredevildave** [comment]
I believe responseXML is a part of the standard XML object: https://xhr.spec.whatwg.org/#the-responsexml-attribute (your link is referring to the `.xml` property)

Our bug is that we aren't setting the responseType of the request to document.

**Comment by daredevildave** [comment]
Deployed

**Comment by joonjoonjoon** [comment]
I got this exact error when using Playcanvas-spine. If I export with the Spine exported '.atlas' file, I get the "InvalidStateError: responseXML is only available if responseType is '' or 'document'.". If I remove the file from the project, it works as expected. (both tests done in Firefox)

**Comment by joonjoonjoon** [comment]
renaming the **.atlas** file to **.atlas.xml** fixed the problem, but I had to re-upload it as renaming inside the editor doesn't actually cause the exported file to be renamed.
