### ISSUE TITLE
Ammo.js Dependency

### ISSUE THREAD

**Issue by justingeeslin** [playcanvas/engine#831]
Should Ammo.js be considered a dependency in the package.json? 
```
"dependencies": {
    "ammo.js": "https://github.com/kripken/ammo.js"
  }
```

**Comment by willeastcott** [comment]
No, I don't feel like it's a hard dependency really. From the looks of things, the ammo.js node package is no longer updated:

https://www.npmjs.com/package/ammo.js

And the package.json is not regularly updated with a meaningful version.

The only dependency on ammo is the link to the version of the library that we recommend. For example:

https://github.com/playcanvas/engine/blob/master/examples/physics/falling_shapes/index.html#L5

I don't think the library is required anywhere else in the codebase. Now, as an end user, sure, you're likely to want to use ammo.js, and if so, either grab the latest build from kripken's repo, or use the latest on https://code.playcanvas.com  

I think I'll add a comment in the engine's top-level readme to explain all this.
