### ISSUE TITLE
Separate blending settings for color and alpha channels

### ISSUE THREAD

**Issue by yard** [playcanvas/engine#835]
Hi guys,

Just wondering why Playcanvas only provides the abstraction on top of WebGL's blendFunc / blendEquation, and no way to manipulate blendFuncSeparate / blendEquationSeparate?

Is there anything behind that decision (as the latter seems to be a more general form of the former)?

**Comment by guycalledfrank** [comment]
I added it in the upcoming PR, so should be merged soon: https://github.com/guycalledfrank/engine/commit/f08056da0d3eee68590b083384508305c787ce01

**Comment by yard** [comment]
Cool! Closing the issue then :)

**Comment by guycalledfrank** [comment]
It's merged now: https://github.com/playcanvas/engine/pull/873
