### ISSUE TITLE
Camera entity local position not being updated when presenting in WebVR

### ISSUE THREAD

**Issue by yaustar** [playcanvas/engine#840]
When the user is in VR with a headset that has positional tracking, the getLocalPosition() of the camera entity is always 0, 0, 0

**Comment by willeastcott** [comment]
WebVR has now be deprecated and replaced with the new WebXR APIs. Therefore, I'm closing this. But please re-open if you find this to still be a problem under WebXR. @Maksims might be able to confirm this is a non-issue.

**Comment by Maksims** [comment]
Not an issue anymore. Now position will be the real position of viewer. In case of 2 view VR, it will be between eyes.
