### ISSUE TITLE
Entity transform: Set scale axes to zero

### ISSUE THREAD

**Issue by guidodedalord** [playcanvas/engine#847]
Hi guys,

I have an entity with scale 0 in the X axis, and a warning on the console appears.
" pc.Mat4#invertTo3x3: Matrix not invertible. "

It's logically OK, but the problem it's that it's creating objects constantly, and this it's very expensive, specially on mobiles.

I think it would be a good idea another solution because in some cases you want to scale it to 0 to pretend that it's disabled. 
Also I know that sometimes animation artists set scales to 0 to hide elements in an animation. For example, if the player has a arrow and a bow, and after throwing the arrow this element has to disappear after 'x' seconds, the artist can scale it to zero.

Thank you!

**Comment by Maksims** [comment]
Agree on this one. Previously we used to make a lot of warnings and error logs. Now there are defines for engine, and perhaps this warnings should go behind `DEBUG` define, to ensure production engine is not logging this stuff.

Please consider making simple PR to address this, we will be very happy to have another [contributor](https://github.com/playcanvas/engine/blob/master/CONTRIB.md).
