### ISSUE TITLE
cloned model is not cloning all properties.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#848]
Seems like cloned models, will not properly clone meshes. Leading to some properties set to default. For example `meshInstance.mask`. It seems that meshInstances are not cloned properly, but re-created, leading to many properties to be ignored.

It is not the case with use of `ModelComponent` as it sets back all it's properties. But they are not that narrow to each meshInstance as well.

**Comment by sethgillett** [comment]
Is this issue closed?

**Comment by willeastcott** [comment]
It seems so, yes.
