### ISSUE TITLE
Change lightmapper-reserved bits to larger values

### ISSUE THREAD

**Issue by guycalledfrank** [playcanvas/engine#851]
Lightmapper reserves first 3 bits to filter dynamic lights: https://github.com/playcanvas/engine/blob/master/src/scene/lightmapper.js#L4
It would be better to change their values to something larger, because it's tempting for users to change the first bits when they're working with bit masks, and then lightmapper can unexpectedly override those.

**Comment by mvaligursky** [comment]
closing this as the lightmapper has changed a lot and this does not feel relevant anymore?
