### ISSUE TITLE
Can I use Playcanvas with js library like jquery, react 

### ISSUE THREAD

**Issue by wanghuatao** [playcanvas/engine#856]

**Comment by Maksims** [comment]
Yes you can use any libraries you want.
PlayCanvas Engine is just another library that uses some JavaScript.

Best place to ask similar nature questions would be a forum: http://forum.playcanvas.com/

**Comment by trusktr** [comment]
Maybe a better question would've been "Is there a React interface for PlayCanvas?".

**Comment by willeastcott** [comment]
There's not integration of React with PlayCanvas as far as I'm aware.
