### ISSUE TITLE
Codepen demo is broken for PlayCanvas v0.208.0 (current latest version)

### ISSUE THREAD

**Issue by felladrin** [playcanvas/engine#867]
The demo at <http://codepen.io/playcanvas/pen/NPbxMj> (referenced on [README](https://github.com/playcanvas/engine/blob/master/README.md), line 103) is broken for `PlayCanvas 0.208.0-dev 421aeac`.

![image](https://cloud.githubusercontent.com/assets/418083/23469101/7710f2a4-fe81-11e6-98f9-2ce149c9023d.png)

**Comment by Maksims** [comment]
Fixed https://github.com/playcanvas/engine/commit/60e3805e3f83b8a62263b8e51099f26666763b36
