### ISSUE TITLE
Depth texture instead of pack/unpack.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#88]
For ShadowMaps consider using [WEBGL_depth_texture ](https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/) instead of pack/unpack for browsers that do support that extension, [82%](http://webglstats.com/#highcharts-42).
And use pack/unpack as fallback.

**Comment by guycalledfrank** [comment]
Implemented it, but didn't found significant performance difference. Same on PC, very slightly faster on a Mali GPU tablet, slightly slower (why?) on iPhone 5s.
