### ISSUE TITLE
IE11, Web Audio API, load mp3 without Media Pack installed.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#89]
If on Windows 8 in IE11 Audio API is not supported fully, it will report it's availability but will fail to work.
Installing [Media Feature Pack for N and KN versions of Windows 8.1](http://www.microsoft.com/en-us/download/details.aspx?id=40744) solves the problem.
Engine should not fail [screen](https://pbs.twimg.com/media/B3KQ1tYCAAA4Kfr.png:large) and expect such scenario, fallback to basic audio and still run the game. Without media pack it assumed it supports Web Audio API, then tried to load mp3 but failed to decode it, threw exception and just failed to play the game.
Is Audio considered high priority that will lead to big fail if it wont load, or should be considered as not mandatory asset, and potentially can fail to load but still will run the game as that would be expected case scenario.

**Comment by willeastcott** [comment]
@vkalpias Can we close this now?

**Comment by vkalpias** [comment]
The engine doesn't fail if some audio files are not loaded so yeah
