### ISSUE TITLE
AssetRegistry load method dose not load "mapping" for model asset

### ISSUE THREAD

**Issue by shawn0326** [playcanvas/engine#895]
loadFromUrl method can load "mapping" data for model asset, but load method can't.

because of this, i must do this in my code:

````
        var assets = app.assets.list();
        var count = 0;
        for(var i = 0; i < assets.length; i++) {
            var asset = assets[i];
            asset.on("load", function(asset) {
                count++;
                if(count === assets.length) {
                    main();
                }
            });
            if(asset.type === "model") {
                app.assets.loadFromUrl("../assets/Playbot/Playbot.json", "model", function() {});
            } else {
                app.assets.load(asset);
            }
        }
````

so, why not load "mapping" data for model asset when i call load method?

**Comment by Maksims** [comment]
Can you provide complete example with only the problem replicated?

**Comment by daredevildave** [comment]
Sorry, it took a long time for me to see this...

When loading from an asset the mapping data should be contained in `asset.data` which is why it doesn't try and load a mapping file.
