### ISSUE TITLE
Number of AudioContext has limit based on hardware.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#897]
There is a limit across all tabs in a browser based on hardware of how many AudioContext object can be created.
If it exceeds the limit, in some cases as little as 6, then it will throw exception:

> Error: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater or equal to the maximum bound (6).

We need to handle this scenario, and avoid complete engine crash when such exception happens.
Additionally engine should be "OK" when there is no context and simply do no audio and not crash if audio functions are used around the app.

**Comment by willeastcott** [comment]
Oooor, just fall back to audio tag (as is the case when Web Audio API is not available).

**Comment by willeastcott** [comment]
Just to chip in again, I did try to debug and fix this, but on my Win10 machine, I can create 25 browser tabs playing a looping sound with Web Audio and it works fine. I gave up at 25. Unless we can actually find a system that exhibits the problem, we'll have to close this.
