### ISSUE TITLE
Colorshifts in cubemap

### ISSUE THREAD

**Issue by ImmanuelSamuel** [playcanvas/engine#898]
I added a cubemap using scene.skybox however the colors are messed up.
Right is the true cubemap left is from pc.

![image](https://cloud.githubusercontent.com/assets/7865018/24583451/663e93c8-1718-11e7-9969-20999ccba852.png)

**Comment by guycalledfrank** [comment]
That's weird, do you have a project link to debug?

**Comment by ImmanuelSamuel** [comment]
I was just trying it out locally. I stripped everything from my code and just ran the cubemap part. 
I did some testing and am quite certain that its the dds file thats the issue. 

Check out the space dds file. If I use the png then its alright.

**Comment by guycalledfrank** [comment]
Where do you get the DDS and how do you load it?

**Comment by ImmanuelSamuel** [comment]
The software is called spacescape. I tried multiple. They all give me the same shifted colors.
```
app.assets.loadFromUrl("/dds/clouds1.dds", "texture", function (err, asset) {
    app.scene.skybox = asset.resource;
});
```

**Comment by guycalledfrank** [comment]
Ah, yes, DDS can be RGBA and BGRA, I think latter might be your case. Apparently engine tries to load it as RGBA, and get it all blue. The engine only supports a small subset of DDS formats, which are used internally and map directly to WebGL formats, and WebGL doesn't have the BGRA format. Are you sure there are no export format options in the spacescape?

**Comment by ImmanuelSamuel** [comment]
I checked that and it says 8bit RGBA as the output format. Thats why I wanted to see if pc uses some other format.

**Comment by ImmanuelSamuel** [comment]
How can I modify the code above to construct a cupemap texture from jpegs?

**Comment by guycalledfrank** [comment]
@Maksims can answer that better than me, but I can suggest an easy fix. If you use the engine locally, you can go here https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/chunks/reflectionCube.frag#L6 and replace ".rgb" with ".bgr".
If you want to control it per-material, and not change everywhere, you can make a changed copy of this file. After you get the modified file's string, you can plug it into individual material: `material.chunks.reflectionCubePS = modifiedCode; material.update();`

**Comment by ImmanuelSamuel** [comment]
But this is the skybox. How can I get the material instance of the skybox? RIght now I am just using ```app.scene.skybox```

**Comment by guycalledfrank** [comment]
The sphere you're using can be patched the way I mentioned, but skybox, yes, needs separate patching, you can try adding https://github.com/playcanvas/engine/blob/master/src/graphics/program-lib/chunks/skybox.frag#L5 ".bgra;" in the end

**Comment by ImmanuelSamuel** [comment]
Is there a way of doing ```material.chunks.reflectionCubePS = modifiedCode; material.update();``` for skybox?

**Comment by guycalledfrank** [comment]
You can try simply `pc.shaderChunks,skyboxPS = newCode;`

**Comment by ImmanuelSamuel** [comment]
Ok I tried that but it doesnt reflect the change. Maybe the skybox material needs to be updated after I set it? I tried ```app.scene.update()``` but thatt doesn't work.

**Comment by ImmanuelSamuel** [comment]
Also currently the reflections need to be set by myself by hand each time. Also the reflections do not reflect other objects. I see you have mentioned this previously
![image](https://cloud.githubusercontent.com/assets/7865018/25029251/93f97c18-2089-11e7-9f11-ce61a1b4fa1c.png)

The post was on 2014. So any updates on setting up the reflection probes in the latest pc release?

**Comment by guycalledfrank** [comment]
Cubemaps are assigned automatically based on skybox, but only if they're prefiltered (that means they can support different levels of material glossiness).
Reflections probes are planned, and I'm sorry it's still not implemented, but we had too many important other features to work on... 
Mirror reflection is better done without any cubemaps and probes, but with an additional render pass, using reflected camera matrix. "After the Flood" demo had planar mirrors and water that did exactly that, and we're going to open-source it soon. It relied on a few additional helpers in the engine code though.

**Comment by MackeyK24** [comment]
Yo @guycalledfrank ... Is this Still true... These are the ONLY DDS FORMATS as of July 2018.

Ah, yes, DDS can be RGBA and BGRA, I think latter might be your case. Apparently engine tries to load it as RGBA, and you get it all blue. The engine only supports a small subset of DDS formats (RGBA8, DXT1, DXT5, RGBA32F), which are used internally and map directly to WebGL formats, and WebGL doesn't have the BGRA format. Are you sure there are no export format options in the spacescape?

So no RGBA16F ... 

I am using cfmt command line... so it can export whatever...
its just RGBA8 losses so much and RGBA32F is a little BIG... RGBA16F looked really good for WebGL games... Just wondering of any plans to RGBA16F support for DDS ?
