### ISSUE TITLE
Instancing broken

### ISSUE THREAD

**Issue by willeastcott** [playcanvas/engine#900]
This project no longer runs in Chrome:

https://playcanvas.com/project/442322/overview/Creating%20Rigid%20Bodies%20in%20Code

Error is:

Uncaught TypeError: this.extInstancing.vertexAttribDivisorANGLE is not a function
    at GraphicsDevice.draw (playcanvas-stable.dbg.js:5347)
    at ForwardRenderer.drawInstance (playcanvas-stable.dbg.js:9642)
    at ForwardRenderer.renderShadows (playcanvas-stable.dbg.js:9887)
    at ForwardRenderer.render (playcanvas-stable.dbg.js:10545)
    at Application.render (playcanvas-stable.dbg.js:19319)
    at playcanvas-stable.dbg.js:19631

Only happens for WebGL 2.

**Comment by guycalledfrank** [comment]
It should be removed and we should re-think the API, the way it works right now is not useful enough.

**Comment by willeastcott** [comment]
Agreed.

**Comment by willeastcott** [comment]
So, @guycalledfrank, I just updated that project to use the new batching functionality. Works great. Draw calls drop from ~2000 to ~100 and render time goes from about 9ms to about 2ms on my laptop. Nice. I notice the auto instancing code paths are still in the engine. Does the new batching completely supersede it? Can it now be deleted?

**Comment by guycalledfrank** [comment]
I think existing instancing functionality should be deleted. It wasn't designed properly, and it's broken now... but it doesn't mean we should ignore integrating instancing properly.

One way I see is to make it a BatchGroup property (boolean), so it will be Static, Dynamic, Static+Instanced, Dynamic+Instanced... in this case, if hardware supports it, we will use instancing while assembling batch group meshes.

**Comment by willeastcott** [comment]
Well, I don't think it was ever promoted to public API so go right ahead.

**Comment by mvaligursky** [comment]
we now have public API for this, closing.

5f7c5010 Hardware Instancing fixes / sample (#1846) (#1856)
