### ISSUE TITLE
Post Effects + MSAA functionality

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#901]
Currently there is no way to specify number of samples for post effects and no ability to call `resolve` on input buffers to preserve AA for post-effects.
With WebGL 2.0 render targets can have Anti-Aliasing.

**Comment by willeastcott** [comment]
This was fixed by @slimbuck with the following PR: https://github.com/playcanvas/engine/pull/1650

Please re-open if you feel there's anything more left to be done on this. Thanks!
