### ISSUE TITLE
Lights not working in IE11 and Edge browser.

### ISSUE THREAD

**Issue by kishlayaS** [playcanvas/engine#943]
Here is the preview [link](https://playcanv.as/p/W7VEWs0v/).
A fork of the task is also available (CubeTaskForDebug).
Cheers

**Comment by guycalledfrank** [comment]
Specular light is present, but there's no diffuse. Also happens on iphone. Investigating.

**Comment by guycalledfrank** [comment]
Can you give the link to your fork please?

**Comment by willeastcott** [comment]
Here you go @guycalledfrank:

https://playcanvas.com/project/486581/overview/cubetaskfordebug

**Comment by guycalledfrank** [comment]
Thanks. The problem seems to be in the PNG (the diffuse map).
IE and iOS Safari particularly pre-multiply PNG color by its alpha, when reading.
squareTextured.png seems to be transparent, and that's a problem for these browsers.

**Comment by kishlayaS** [comment]
@guycalledfrank @willeastcott Splitting diffuse and opacity maps into separate texture fixed the issue.
Thanks for the support 👍
