### ISSUE TITLE
rendering issues on iOS 11

### ISSUE THREAD

**Issue by filharvey** [playcanvas/engine#948]
I have a could of tests from the editor exported and they were working on iOS but with the new iOS 11 beta seeing issues.

This one works ok.

https://dl.dropboxusercontent.com/u/1722/tactics/index.html

This one does not render the 3D elements.

https://dl.dropboxusercontent.com/u/1722/treys/index.html

I also see this on another app I'm working on.

Thanks

Phil

**Comment by filharvey** [comment]
Any updates?

**Comment by guycalledfrank** [comment]
Sorry, haven't installed iOS 11 yet. Perhaps they'll fix it after leaving beta? Are other WebGL demos (non-PlayCanvas) work?

**Comment by daredevildave** [comment]
Hi @filharvey 

We'll look into this once we get an iOS 11 device (soon). Do you see any error messages in the console when it fails to render?

**Comment by filharvey** [comment]
k, looks like it is now fixed with the latest beta. I will keep you informed on it.
