### ISSUE TITLE
Script attributes are not initialized if script is added to active entity.

### ISSUE THREAD

**Issue by Maksims** [playcanvas/engine#949]
If entity is already in hierarchy, being enabled and app is running, when script is added attributes do not get initialized.

Here is replication example: https://codepen.io/moka/pen/mwrWmE

Consider looking into option of initializing attributes at the moment when script is added to entity, not when it is getting enabled in hierarchy.

**Comment by vkalpias** [comment]
Should be fixed with https://github.com/playcanvas/engine/pull/1178

**Comment by l-7777777** [comment]
still not working

**Comment by vkalpias** [comment]
Please provide an example that reproduces this bug. Thank you

**Comment by willeastcott** [comment]
Hey @l-7777777 - are you able to provide an example showing the problem?
