### ISSUE TITLE
Issue with Elements and anchors.

### ISSUE THREAD

**Issue by filharvey** [playcanvas/engine#950]
I'm trying to have it so that a element is stretched across the screen, but the positioning of it seems really strange.

```
var panelAsset = Game.instance.app.assets.find("grey_panel", "texture");
entity.addComponent('element', {
                    anchor: new pc.Vec4(0.5, 1, 0.5, 0),        // {l, b, r, t}
                    pivot: new pc.Vec2 (0.5, 0.5),
                    width: 640,
                    height: 800,
                    type: "image",
                    textureAsset: panelAsset
                });

entity.setLocalPosition (0, 0, 0);

```
The screen is 640 x 1138. But the panel is appearing not in the center of the screen but off the edge of the screen

This is what the layout should look like

[example](https://dl.dropboxusercontent.com/u/1722/example.png)

but this is how it is appearing

[wrong](https://dl.dropboxusercontent.com/u/1722/error1.png)

I've basically written a JSON export for unity to export and then import to place all items in the correct location. 

As you can see most of the items appear in the correct location if the anchor is (0.5, 0.5, 0.5, 0.5). But if I change to to (0.5, 1, 0.5, 0). It all breaks.

**Comment by daredevildave** [comment]
Anchors are measured from bottom left. So you should set the anchor to (0.5,0,0.5,1). 

In addition, if you are splitting the anchor (b=0,t=1), then setting the height is invalid as the height is determined by the margins and the anchor. You should probably do this:

```
{
	anchor: new pc.Vec4(0.5, 0, 0.5, 1),
	pivot: new pc.Vec2(0.5, 0.5),
	width: 640,
	top: 0,
	bottom: 0,
	type: "image",
	textureAsset: panelAsset
}
```


Finally, note that the element component is not released yet and is still in development so you may find bugs and the API may change without notice. ☠️

**Comment by filharvey** [comment]
Thanks for the update, will try this. Yep i know elements is unreleased but is definitely a needed addition. Also nearly working to my desires.

**Comment by ImmanuelSamuel** [comment]
When attaching elements to screen what is the bottom left.
```
screen.addComponent("screen", {
      resolution: new pc.Vec2(100,100),
      screenSpace: false,
    });

    element.addComponent("element", {
        anchor: [.5,0,.5,1],
        pivot: [.5,.5],
        type: "text",
        alignment: [0,0],
        top: 0,
        left: -100,
        height: 10,
        width: 10,
        text: this.title,
        fontSize: .3,
        fontAsset: fontAsset,
        color: new pc.Color(0,0,0)
    });
```

the element doesnt budge even a slight bit left even if ```lef: 1000```. Seems like the screen component's left coordinate some where far away.
