### ISSUE TITLE
Picker and Overlapping Elements Images / Text

### ISSUE THREAD

**Issue by filharvey** [playcanvas/engine#953]
Using the new Element Component, if you have 2 overlapping images, the picker sometimes picks the element which is behind. This is due to the fact that elements are being sorted by their material ID's. This value for me is 3 for all the elements, so they end up being sorted randomly, and not in depth order. And then all Text elements have a value of 5.

Current fix to get around this is to set their pick flag to false.

```
entity.element._text._meshInstance.pick = false;
entity.element._image._meshInstance.pick = false;

```

Could elements be sorted by their display order, so that picking works properly. Also could the pick flag be exposed at a higher level.

**Comment by daredevildave** [comment]
Looks like there is a difference between the way the forward renderer sorts and the picker sorts draw calls. Looks like a bug in the picker to me.

**Comment by filharvey** [comment]
any updates on this?

**Comment by guycalledfrank** [comment]
Pushed a fix
