### ISSUE TITLE
this.screen.screen is undefined / leaking Element / dangling set:resolution event handler

### ISSUE THREAD

**Issue by Leander1P** [playcanvas/engine#992]
On browser resize, we're seeing:

```
TypeError: this.screen.screen is undefined playcanvas-stable.dbg.js:26924:13
	_calculateLocalAnchors https://code.playcanvas.com/playcanvas-stable.dbg.js:26924:13
	_calculateSize https://code.playcanvas.com/playcanvas-stable.dbg.js:26980:5
	_onScreenResize https://code.playcanvas.com/playcanvas-stable.dbg.js:26911:5
	fire https://code.playcanvas.com/playcanvas-stable.dbg.js:608:5
	set https://code.playcanvas.com/playcanvas-stable.dbg.js:26576:5
	_onResize https://code.playcanvas.com/playcanvas-stable.dbg.js:26562:7
	fire https://code.playcanvas.com/playcanvas-stable.dbg.js:608:5
	resizeCanvas https://code.playcanvas.com/playcanvas-stable.dbg.js:5848:5
	setCanvasResolution https://code.playcanvas.com/playcanvas-stable.dbg.js:20545:5
	resizeCanvas https://code.playcanvas.com/playcanvas-stable.dbg.js:20617:9
	reflow [...]
```

The statement is https://github.com/playcanvas/engine/blob/7f54ed08ca0615615d53146494778bf07c84279a/src/framework/components/element/component.js#L389

Exploring a bit:

The image element and `this.screen` in question appear to have been destroyed by a prior scene transition (entities have parents, but each parent has no children).

It seems plausible that the `set:resolution` event (which is what's being triggered in the upper `fire` in the stack above) needs to be `off`ed.  This event handler looks like it is set up in `framework/components/element/component.js` in `_updateScreen`.

Not sure if there needs to be a destroy override or if it would suffice to do something like `_updateScreen(null)` in the `onRemove` handler?

**Comment by Leander1P** [comment]
(Apologies while I chase my tail a bit here; I can probably whip up a minimal repro case if this doesn't prove fruitful. =)

Looking further up the stack, perhaps it's actually the `resizecanvas` event that's the important link? I don't see the `resizecanvas` for ScreenComponent `off`'d either?

https://github.com/playcanvas/engine/blob/d0e2c802a37ae721b5b29117103a0e23e36781d0/src/framework/components/screen/component.js#L39

**Comment by vkalpias** [comment]
Thanks for reporting! Pushed a fix https://github.com/playcanvas/engine/commit/1f2d33a5a0daf112c4afe600f7f6d34a6aeec751

**Comment by Leander1P** [comment]
No longer getting the undefined error and I don't see ScreenComponent hanging around in heap snapshots after the scene.  Thanks!
