### ISSUE TITLE
update included webvr-polyfill

### ISSUE THREAD

**Issue by tomkuipers** [playcanvas/engine#995]
Please update to the most recent version of webvr-polyfill. In recent versions the online Device Parameter Database now points to https://dpdb.webvr.rocks/dpdb.json, which is updated more frequent than https://storage.googleapis.com/cardboard-dpdb/dpdb.json. See project https://github.com/WebVRRocks/webvr-polyfill-dpdb.
This will get rid of "No DPDB device match." for more devices.

**Comment by willeastcott** [comment]
Thoughts @daredevildave?

**Comment by daredevildave** [comment]
Updated to version 0.9.39
